### ISSUE TITLE
/app/x-ui: line 1: syntax error: unexpected "("

### ISSUE THREAD

**Issue by jeffscrum** [MHSanaei/3x-ui#1003]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

```
3x-ui  | Server ready
3x-ui  | /app/x-ui: line 1: syntax error: unexpected "("
3x-ui exited with code 2
```

### Version of 3x-ui

<details>
fresh install v1.7.8, docker version
</details>

### x-ui log reports or xray log

<details>
n/a
</details>

**Comment by zertf** [comment]
Hi! How did you solve the problem? I have the same error.

**Comment by zertf** [comment]
I've solved it! You need an x86 architecture to work properly, not arm64

**Comment by EmbeddedAndMore** [comment]
Hmm, weird. it uses `alpine` image, so there is no `bash`. but this doesn't make a problem for x86 arch (idk why!!). so to fix just 
1- install bash in Dockerfile.<br/>
`RUN apk add --no-cache --upgrade bash` 
2- build the image again. in the project's folder do:<br/>
`docker build -t 3x-ui .`
3- and make docker-compose.yml load local image. replace the image entry to:<br/> 
`image: x-ui:latest`
