### ISSUE TITLE
تنظیم ترافیک کانفیگ روی یک یا چند آیپی خاص

### ISSUE THREAD

**Issue by JackSonJson** [MHSanaei/3x-ui#1006]
ایا میتوان تمامی ترافیک کانفیگ را بجز ip هایی که مدنظر داریم محدود کرد؟ در مثال های زیر موردی درباره این موضوع پیدا نکردم. 

https://github.com/MHSanaei/3x-ui/tree/main/media/configs

لطفا یک مثال بزنید که چگونه میتوانیم ترافیک یک کانفیگ را محدود به آی پی خاص کنیم. برای مثال ترافیک کانفیگ در صورتی که ip یک سایت یا برنامه 123.123.123.123 یا 321.321.321.321 بود تبادل بشود و در غیراینصورت عمل نکند.

**Comment by uzer0098** [comment]
سمت سرور نمیشه و فقط روی برنامه های سمت کلاینت با استفاده از routing میشه

**Comment by JackSonJson** [comment]
لطفا توضیحات بیشتری ارائه کنید

**Comment by JackSonJson** [comment]
> سمت سرور نمیشه و فقط روی برنامه های سمت کلاینت با استفاده از routing میشه

لطفا توضیحات بیشتری ارائه کنید
