### ISSUE TITLE
Fail2ban status error

### ISSUE THREAD

**Issue by arman2012** [MHSanaei/3x-ui#1008]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام بنده fail2ban رو نصب کردم از پنل و پیغام نصب درست هم دیدم ولی وقتی fail2ban status رو میزنم که وضعیت رو ببینم این ارور رو مشاهده میکنم و کلا سیستم تک کاربره کار نمیکنه برام
× fail2ban.service - Fail2Ban Service
     Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor prese
t: enabled)
     Active: failed (Result: exit-code) since Sat 2023-09-02 11:29:02
 EEST; 7s ago
       Docs: man:fail2ban(1)
   Main PID: 311747 (code=exited, status=255/EXCEPTION)
        CPU: 188ms

Sep 02 11:29:02 latvia2.ip-ptr.tech systemd[1]: Started Fail2Ban Service.
Sep 02 11:29:02 latvia2.ip-ptr.tech fail2ban-server[311747]: 2023-09-02 11:29:02
,632 fail2ban                [311747]: ERROR   Failed during configuration: Have
 not found any log file for sshd jail
Sep 02 11:29:02 latvia2.ip-ptr.tech fail2ban-server[311747]: 2023-09-02 11:29:02
,646 fail2ban                [311747]: ERROR   Async configuration of server fai
led
Sep 02 11:29:02 latvia2.ip-ptr.tech systemd[1]: fail2ban
.service: Main process exited, code=exited, status=255/EXCEPTION
Sep 02 11:29:02 latvia2.ip-ptr.tech systemd[1]:
fail2ban.service: Failed with result 'exit-code'.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by mehrdadrzy** [comment]
سرورهای منم همین مشکل رو دارن

**Comment by salario07** [comment]
I had this issue until I ran `unminimize` on the server. This enables features related to user login which seems required for this functionality.

**Comment by mohammadi939** [comment]
سلام ، اونایی که از دبیان استفاده میکننچک کنن که پایتون۳ نصب باشه 
`apt install python3-systemd`
و بعد یه قسمتی هست که باید به کانفیگ Fail2ban اضافه کنید:
`echo -e "[sshd]\nbackend=systemd\nenabled=true" | sudo tee /etc/fail2ban/jail.local`
بکِند باید از auto به systemd تغییر کنه ، که با کد بالایی میتونین این کار رو خودکار انجام بدین.
در آخر هم یه بار سرویس رو ریستارت کنید:
`systemctl status fail2ban.service`
