### ISSUE TITLE
Please consider adding support for TUIC proxy

### ISSUE THREAD

**Issue by livingfree2023** [MHSanaei/3x-ui#1014]
I've been using TUIC 1.0 (https://github.com/EAimTY/tuic) and it was able to achieve 20-40% network speed increase. There are some scripts (https://github.com/mack-a/v2ray-agent) that can install TUIC server. I hope 3x-ui will be the first to provide GUI to TUIC. 

Thanks

**Comment by sepehrrostami** [comment]
TUIC would restrict your SNI by ISPs
