### ISSUE TITLE
RAM Usage issue

### ISSUE THREAD

**Issue by qfewzz** [MHSanaei/3x-ui#1017]
### Welcome

- [x] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

من از آخرین نسخه پنل و هسته xray استفاده میکنم. پنل 1.7.8 و xray 1.8.4.
مصرف رم خود به خود میره بالا. هر چند ساعت یکبار باید restart بزنم. فقط 5 تا کاربر دارم. در گروه بهم گفتن که باید log رو غیرفعال کنم تا مشکل حل بشه. نمیتونم اینکارو انجام بدم.
لطفا این باگ رو رفع کنید که با وجود فعال بودن log، مصرف رم زیاد نباشه.
به نظر میاد مشکل از پنل نیست و از هسته xray ویرایش شده هست. البته دقیق بررسی نکردم.
از این دستور استفاده میکنم، ولی فایده نداره، باید کلا restart بشه که مصرف رم بیاد پایین.
`sync; echo 3 > /proc/sys/vm/drop_caches`

و اینو هم بگم که از ip limit استفاده نمیکنم.

یچیز عجیبی هم اتفاق افتاده برام، من از اول Log رو فعال کرده بودم، از نسخه قدیمی تر پنل استفاده میکردم و مشکل رم نداشتم، بدون اینکه هیچ آپدیتی یا تغییری ایجاد کنم، خود به خود مصرف رم رفت بالا. آپدیت کردم که شاید حل بشه، که نشد.
باتشکر

### Version of 3x-ui

1.7.8

### x-ui log reports or xray log

not needed

**Comment by Bullshark21** [comment]
درود بله این مشکل منم با اخرین نسخه پنل دارم امیدوارم برطرف بشه

**Comment by MHSanaei** [comment]
از ورژن ۱.۷.۵ پنل، ما از هسته اصلی ایکس ری استفاده کردیم و هسته سفارشی کنار گذاشته شده 
لطفا لاگ رو بررسی کنید ارور و یا خطایی اگر موجود هست بفرمایید
وارپ هم در افزایش رم بی تاثیر نیست

**Comment by AmoAlireza** [comment]
هسته xray پنل روی 1.8.0 بزارید مشکل حل میشه.

**Comment by AEydi** [comment]
> هسته xray پنل روی 1.8.0 بزارید مشکل حل میشه.

درست نشد با این
برا من روی نسخه قبلی این مشکل بوجود آمد
با دوباره ایجاد کردن کاربر ها حل شده بود
ولی این بار درست نشد

تفاوتی که با نسخه قبلی بوجود اومده اینه که توی قبلی رم خیلی با سرعت بیشتری زیاد میشد و تو زمان مشابه به 300 مگ می رسید در حالی که این به 80 میرسه برای مثال
و با رسیدن به حدود این مقادیر cpu چند ثانیه یه بار به 100 میرسه و اگر بیشتر بمونه و ریستارت نشه میچسبه به 100
در شرایط عادی حدود 10 هستش

**Comment by black-sec** [comment]
منم دقیقا مشکل شما رو دارم تونستین رفع کنین ؟؟

**Comment by qfewzz** [comment]
آقای ثنایی گفتن که از هسته xray اصلی استفاده می کنن.
من تعداد کاربرام کمه، واسه همین تست کردن این راهکار رو به عهده شما میزارم. هسته xray رو بدون پنل run کنید(برای تست و صرفا برای زمان محدود). در اینصورت قابلیت های پنل رو از دست میدید، مثلا حجم مصرف شده رو حساب نمیکنه. برای اینکار ابتدا نسخه هسته xray رو از پنل تغییر بدید به یک نسخه خاصی که مدنظرتون هست، مثلا 1.8.0، بعدش پیش نیاز رو نصب کنید:

`sudo apt install tmux`

برای اجرای هسته xray بدون پنل:
`x-ui stop; tmux kill-session -t "xray-only"; tmux new-session -s "xray-only" -d '/usr/local/x-ui/bin/xray-linux-amd64 -c /usr/local/x-ui/bin/config.json';`

برای متوقف کردن:
`tmux kill-session -t "xray-only"`

برای اجرای مجدد هسته xray با پنل:
`x-ui restart`

**Comment by qfewzz** [comment]
@MHSanaei 
از وارپ استفاده نمی کنم و هیچ خطایی هم پیدا نکردم. فعلا با همین روشی که در پست قبل گفتم و هسته 1.8.0 جلو میرم و نتیجه رو اعلام می کنم.

**Comment by qfewzz** [comment]
@MHSanaei
مشکل رو پیدا کردم، همش تقصیر fallback ها هست :( 
کانفیگ معمولی درست کردم و از fallback ها استفاده نکردم، درست شد.
بارها تست کردم تا مطئن بشم موضوع دیگه ای روی نبوده و حتما fallback ها بودن.
مشکل بقیه دوستان ممکنه متفاوت باشه، من فقط تجربه خودم رو به اشتراک گذاشتم.

**Comment by AEydi** [comment]
> > هسته xray پنل روی 1.8.0 بزارید مشکل حل میشه.
> 
> درست نشد با این برا من روی نسخه قبلی این مشکل بوجود آمد با دوباره ایجاد کردن کاربر ها حل شده بود البته فکر میکنم ولی این بار درست نشد
> 
> تفاوتی که با نسخه قبلی بوجود اومده اینه که توی قبلی رم با سرعت بیشتری زیاد میشد و تو زمان مشابه به 300 مگ می رسید در حالی که این به 80 میرسه برای مثال و با رسیدن به حدود این مقادیر cpu چند ثانیه یه بار به 100 میرسه و اگر بیشتر بمونه و ریستارت نشه میچسبه به 100 در شرایط عادی حدود 10 هستش

من تست کردم دوباره ساختن کاربرها تاثیری نداشت
بنظرم مشکل از ربات تلگرام باشه
غیر فعالش کردم مدتی و درست شده بود، دفعه قبل هم غیر فعال شده بود
و دوباره که فعالش کردم دیگه فعلا مشکلی نداره بعد دو روز
ولی خب دقیق نفهمیدم باگ از کجاست فعلا

**Comment by bomozi** [comment]
> از ورژن ۱.۷.۵ پنل، ما از هسته اصلی ایکس ری استفاده کردیم و هسته سفارشی کنار گذاشته شده لطفا لاگ رو بررسی کنید ارور و یا خطایی اگر موجود هست بفرمایید وارپ هم در افزایش رم بی تاثیر نیست

درود و وقت بخیر و سپاس از پنل عالی شما
من هم مشکل RAM Usage رو دارم
با تغییر ورژن XRAY Core به 1.8.1 مشکل برطرف میشه
منتها با تغییر ورژن XRAY Core به نسخه های پایدار 1.8.4 و 1.8.6 مشکل RAM Usage به وجود می آید. مدام مصرف RAM بالا رفته تا سرویس XRAY Core ریستارت میشه.
متوجه شدم تعداد کاربرهای سرور در میزان سرعت افزایش RAM تاثیر می گذارد. به همین منوال ادامه پیدا کرده تا سرویس XRAY Core در نهایت Restart می شود.

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
