### ISSUE TITLE
IP Limit CPU overload!

### ISSUE THREAD

**Issue by 4erdenko** [MHSanaei/3x-ui#1027]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

VLESS + Reality
I created 30 configs yesterday with a limit of 1 IP.
Today I thought I had manually turned off all of them, but no, a couple did, turned off the rest and the loads disappeared abruptly.

Even though the configs were not even with users.
I.e. on the latest version, when using IP limit in the panel running through Docker, we have an interval load on the CPU, systematically growing.

I think this is some kind of serious bug.

In this image, ip limit is turned off on every config.
![without](https://github.com/MHSanaei/3x-ui/assets/93295097/627d3ce8-8863-49f7-8912-6945c70564cc)

Here I have enabled IP limit on 1 config that no one is connected to.
![with](https://github.com/MHSanaei/3x-ui/assets/93295097/5039b523-1649-4f2f-8abb-6ab9ef3531fe)

### Version of 3x-ui

1.7.8

### x-ui log reports or xray log

logs doesnt have any errors

**Comment by qfewzz** [comment]
I think applying IP limit using an external tool is not a good solution. Adding this feature to xray core is more efficient and less resource intensive. but of course it requires time to edit xray core and do this efficiently. I'm not a Go developer, so I can't contribute on this. But I have some ideas to implement this.

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
