### ISSUE TITLE
cpu

### ISSUE THREAD

**Issue by tesinstas** [MHSanaei/3x-ui#1035]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

بعد از بکاپ گرفتن ، سی پیو میاد رو 100 و دیگه با ریبوت هم درست نمیشه ، باید یه بار ریبیلد شه سرور و دوباره نصب شه پنل.
(روی چند تا سرور تست کردم ، همگی مشکلو داشتن )

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by eloravpn** [comment]
منم همین مشکل رو دارم

**Comment by Hasan-Torabi** [comment]
من هم این مشکل رو دارم.

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
