### ISSUE TITLE
aarch64 can't run docker image

### ISSUE THREAD

**Issue by likeman66** [MHSanaei/3x-ui#1038]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

not matter i pull the latest or the docker pull ghcr.io/mhsanaei/3x-ui:v1.7.8@sha256:080453119567254819d5e118036e0afd094b874c2c6479d563fb0201c281e841 (arm64 version) images, when exec docker-compose up, it returns following error: 
<img width="279" alt="image" src="https://github.com/MHSanaei/3x-ui/assets/59259075/3a5d9a30-a5cd-4bf6-9e5b-6bc71374819b">

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by likeman66** [comment]
> 是的我在甲骨文arm上运行也是一直停止并报错

自己clone一下，然后改下dockerfile，自己编一个arm就行了

**Comment by leic4u** [comment]
Is there an official ARM64 image?

**Comment by likeman66** [comment]
> Is there an official ARM64 image?

I think there is some kind of arm image, but you can't actually run it. You can just clone the project and change the Dockerfile that contains non-arm denpency to arm denpency and build it.

**Comment by leic4u** [comment]
> > Is there an official ARM64 image?
> 
> I think there is some kind of arm images, but you can't actually run it. You can just clone the project and change the Dockerfile that contains non-arm denpency to arm denpency and build it.

It's so difficult for the non-programers, just like me...😂

**Comment by likeman66** [comment]
> > > Is there an official ARM64 image?
> > 
> > 
> > I think there is some kind of arm images, but you can't actually run it. You can just clone the project and change the Dockerfile that contains non-arm denpency to arm denpency and build it.
> 
> It's so difficult for the non-programers, just like me...😂

-----Comand-----
`git clone https://github.com/MHSanaei/3x-ui.git && cd 3x-ui`

```
echo '
# ========================================================
# Stage: Builder
# ========================================================
FROM --platform=linux/arm64 golang:alpine AS builder
WORKDIR /app
ARG TARGETARCH
ENV CGO_ENABLED=1

RUN apk --no-cache --update add \
  build-base \
  gcc \
  wget \
  unzip

COPY . .

RUN go build -o build/x-ui main.go
RUN ./DockerInit.sh "arm64"

# ========================================================
# Stage: Final Image of 3x-ui
# ========================================================
FROM alpine
ENV TZ=Asia/Tehran
WORKDIR /app

RUN apk add --no-cache --update \
  ca-certificates \
  tzdata \
  fail2ban

COPY --from=builder  /app/build/ /app/
COPY --from=builder  /app/DockerEntrypoint.sh /app/
COPY --from=builder  /app/x-ui.sh /usr/bin/x-ui

# Configure fail2ban
RUN rm -f /etc/fail2ban/jail.d/alpine-ssh.conf \
  && cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local \
  && sed -i "s/^\[ssh\]$/&\nenabled = false/" /etc/fail2ban/jail.local \
  && sed -i "s/^\[sshd\]$/&\nenabled = false/" /etc/fail2ban/jail.local \
  && sed -i "s/#allowipv6 = auto/allowipv6 = auto/g" /etc/fail2ban/fail2ban.conf

RUN chmod +x \
  /app/DockerEntrypoint.sh \
  /app/x-ui \
  /usr/bin/x-ui

VOLUME [ "/etc/x-ui" ]
ENTRYPOINT [ "/app/DockerEntrypoint.sh" ]
' > Dockerfile
```

`sudo docker build -t 3x-ui-arm.`

`sudo docker images`
-----End-----

you now should be able to see a docker image called 3x-ui-arm which is the image you just built, then run it as normal

**Comment by Tinnci** [comment]
> > > Is there an official ARM64 image?
> > 
> > 
> > I think there is some kind of arm images, but you can't actually run it. You can just clone the project and change the Dockerfile that contains non-arm denpency to arm denpency and build it.
> 
> It's so difficult for the non-programers, just like me...😂

Just use a modified dockerfile as follows to compile a docker for aarch64, and compile using `docker build --platform=linux/arm64 -t aas/x-ui:arm64 .`:
```
# ========================================================
# Stage: Builder
# ========================================================
FROM --platform=linux/arm64 golang:1.21-alpine AS builder
WORKDIR /app
ARG TARGETARCH
ENV CGO_ENABLED=1
ENV CGO_CFLAGS="-D_LARGEFILE64_SOURCE"

RUN apk --no-cache --update add \
  build-base \
  gcc \
  wget \
  unzip

COPY . .

RUN GOOS=linux GOARCH=arm64 go build -o build/x-ui main.go
RUN ./DockerInit.sh "$TARGETARCH"

# ========================================================
# Stage: Final Image of 3x-ui
# ========================================================
FROM arm64v8/alpine
ENV TZ=Asia/Tehran
WORKDIR /app

RUN apk add --no-cache --update \
  ca-certificates \
  tzdata \
  fail2ban

COPY --from=builder  /app/build/ /app/
COPY --from=builder  /app/DockerEntrypoint.sh /app/
COPY --from=builder  /app/x-ui.sh /usr/bin/x-ui

# Configure fail2ban
RUN rm -f /etc/fail2ban/jail.d/alpine-ssh.conf \
  && cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local \
  && sed -i "s/^\[ssh\]$/&\nenabled = false/" /etc/fail2ban/jail.local \
  && sed -i "s/^\[sshd\]$/&\nenabled = false/" /etc/fail2ban/jail.local \
  && sed -i "s/#allowipv6 = auto/allowipv6 = auto/g" /etc/fail2ban/fail2ban.conf

RUN chmod +x \
  /app/DockerEntrypoint.sh \
  /app/x-ui \
  /usr/bin/x-ui

VOLUME [ "/etc/x-ui" ]
ENTRYPOINT [ "/app/DockerEntrypoint.sh" ]
```

And then use `docker save -o x-ui.tar [YourName]/x-ui:arm64` to export
Import the .tar using the docker of your targeted Arm machine.

**Comment by Tinnci** [comment]
> > > Is there an official ARM64 image?
> > 
> > 
> > I think there is some kind of arm images, but you can't actually run it. You can just clone the project and change the Dockerfile that contains non-arm denpency to arm denpency and build it.
> 
> It's so difficult for the non-programers, just like me...😂

Meanwhile i will provide a link to the latest ARM64 docker build of my own, run and tested on a Xiaomi Router AX5 JDCloud ARMv8 Processor rev 4 (v8l) x 4 targeted| ipq60xx/generic running openwrt, use at your own risk!

https://mega.nz/file/msQVzYwY#NocJYidcYgatzLjEO3yJ-5ZVwfPB_AOiFXJ2D9iC1dY

**Comment by MHSanaei** [comment]
problem solved 
reinstall it

**Comment by leic4u** [comment]
Thanks bro. I have reinstalled the docker images and it works correctly.
