### ISSUE TITLE
limits doesn't work

### ISSUE THREAD

**Issue by sinascorpion** [MHSanaei/3x-ui#1039]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

the time limit and total flow limit don't work. after finishing the flow config still works

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by neerro** [comment]
Confirm this issue. I've tried to set-up limit for 1,2,3 users but connected 5 users from different IP's had ongoing using connection.
