### ISSUE TITLE
api not working 

### ISSUE THREAD

**Issue by Ghasem1243** [MHSanaei/3x-ui#1053]
سلام خسته نباشید ,
نمی شد با api  که در سایت گذاشتین یک کلاینت لا آپدیت کرد api که گذاشتین:
ip:port/panel/api/inbounds/updateClient/UUID

ارور 404 میداد صفحه پیدا نمیشد مجبور شدم از این کد پایین استفاده کردم امیدوارم درست کنید 

 
ip:port/panel/inbound/updateClient/UUID

**Comment by Mohammadgb0078** [comment]
اگه برا پنلت Path گذاشتی اونم اضافه کن
