### ISSUE TITLE
فعال سازی تلگرام در سرور ایران

### ISSUE THREAD

**Issue by sohrabp72** [MHSanaei/3x-ui#1061]
سلام
من پنلم روی سرور ایران هست. میخوام از قابلیت تلگرام برای پشتیبان‌گیری استفاده کنم.
کسی راهی میشناسه معرفی کنه؟
راسی طبق این لینک جلو رفتم چندین بار اما جواب نگرفتم
[https://github.com/alireza0/x-ui/issues/252](url)

**Comment by itmanpro** [comment]
به نظر من بهترین راهکار فراهم سازی امکان تغییر دستی آدرس api.telegram.org هست 
اینجوری کاربر به سلیقه خودش میتونه از انواع راهکار برای دور زدن این مشکل استفاده کنه
درخواست دادم تو همین بخش امیدوارم بررسی و اعمال بشه

**Comment by hadiiiiiiiii** [comment]
> سلام من پنلم روی سرور ایران هست. میخوام از قابلیت تلگرام برای پشتیبان‌گیری استفاده کنم. کسی راهی میشناسه معرفی کنه؟ راسی طبق این لینک جلو رفتم چندین بار اما جواب نگرفتم [https://github.com/alireza0/x-ui/issues/252](url)

منم این روش رو رفتم جواب نگرفتم. 
https://github.com/alireza0/x-ui/issues/571
اگر کسی راهکاری داره ارائه بده ممنون میشم.

**Comment by badmast** [comment]
اگر بخشی اضافه بشه که بتونیم آدرس ورکری که با این (https://github.com/soheylfarzane/TelegramByapss) روش ساختیم رو جایگزین آدرس API تلگرام کنیم، مشکل تلگرام در سرور‌های ایران حل میشه.

در این فایل (web/service/tgbot.go) از این کد (mymmrac/telego) استفاده شده که در خط ۱۷ فایل mymmrac/telego/bot.go  آدرس APIای که برای تلگرام ازش استفاده می‌کنه رو میشه تغییر داد.
