### ISSUE TITLE
مشاهده زمان و حجم کاربر از طریق با تلگرام

### ISSUE THREAD

**Issue by Parsa-n** [MHSanaei/3x-ui#1062]
بات تلگرامو ساختم ولی فقط برای دسترسی ادمینه. چجوری میتونم به یوزرهام که کانفیگی دادم رو بشه ببینن که چقدر از زمان و حجم کانفیگشون مونده ؟؟؟

**Comment by moh3nat** [comment]
باید در  کلاینت فیلد تلگرام  id مشتریت رو بدون @ وارد کنی
