### ISSUE TITLE
Xray: Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: unsupported cipher method:

### ISSUE THREAD

**Issue by MountU0** [MHSanaei/3x-ui#1063]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Xray 1.8.4 (Xray, Penetrates Everything.) Custom (go1.21.0 linux/amd64)

A unified platform for anti-censorship.

2023/09/17 16:13:36 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: unsupported cipher method:

chacha20-ietf-poly1305
----------------
I'm using a Shadowsocks inbound with chacha20-ietf-poly1305

![image](https://github.com/MHSanaei/3x-ui/assets/70737904/8dd14bb7-94ec-44a5-9b1f-e8c823e46024)

### Version of 3x-ui

<details>

x-ui 1.7.8 Xray: v1.8.4

</details>

### x-ui log reports or xray log

<details>

2023/09/17 16:16:06 DEBUG - restart xray, force:false
2023/09/17 16:15:36 DEBUG - restart xray, force:false
2023/09/17 16:15:06 DEBUG - restart xray, force:false
2023/09/17 16:14:36 DEBUG - restart xray, force:false
2023/09/17 16:14:06 DEBUG - restart xray, force:false
2023/09/17 16:13:36 DEBUG - restart xray, force:false
2023/09/17 16:13:06 DEBUG - restart xray, force:false
2023/09/17 16:12:36 DEBUG - restart xray, force:false
2023/09/17 16:12:06 DEBUG - restart xray, force:false
2023/09/17 16:11:36 DEBUG - restart xray, force:false
2023/09/17 16:11:06 DEBUG - restart xray, force:false
2023/09/17 16:10:36 DEBUG - restart xray, force:false
2023/09/17 16:10:06 DEBUG - restart xray, force:false
2023/09/17 16:09:36 DEBUG - restart xray, force:false
2023/09/17 16:09:06 DEBUG - restart xray, force:false
2023/09/17 16:08:36 DEBUG - restart xray, force:false
2023/09/17 16:08:06 DEBUG - restart xray, force:false
2023/09/17 16:07:36 DEBUG - restart xray, force:false
2023/09/17 16:07:06 DEBUG - restart xray, force:false
2023/09/17 16:06:36 DEBUG - restart xray, force:false
2023/09/17 16:06:06 DEBUG - restart xray, force:false
2023/09/17 16:05:36 DEBUG - restart xray, force:false
2023/09/17 16:05:06 DEBUG - restart xray, force:false
2023/09/17 16:04:36 DEBUG - restart xray, force:false
2023/09/17 16:04:06 DEBUG - restart xray, force:false
2023/09/17 16:03:36 DEBUG - restart xray, force:false
2023/09/17 16:03:06 DEBUG - restart xray, force:false
2023/09/17 16:02:36 DEBUG - restart xray, force:false
2023/09/17 16:02:06 DEBUG - restart xray, force:false
2023/09/17 16:01:36 DEBUG - restart xray, force:false
2023/09/17 16:01:06 DEBUG - restart xray, force:false
2023/09/17 16:00:36 DEBUG - restart xray, force:false
2023/09/17 16:00:06 DEBUG - restart xray, force:false
2023/09/17 15:59:36 DEBUG - restart xray, force:false
2023/09/17 15:59:06 DEBUG - restart xray, force:false
2023/09/17 15:58:36 DEBUG - restart xray, force:false
2023/09/17 15:58:06 DEBUG - restart xray, force:false
2023/09/17 15:57:36 DEBUG - restart xray, force:false
2023/09/17 15:57:06 DEBUG - restart xray, force:false
2023/09/17 15:56:36 DEBUG - restart xray, force:false
2023/09/17 15:56:06 DEBUG - restart xray, force:false
2023/09/17 15:55:36 DEBUG - restart xray, force:false
2023/09/17 15:55:06 DEBUG - restart xray, force:false
2023/09/17 15:54:36 DEBUG - restart xray, force:false
2023/09/17 15:54:06 DEBUG - restart xray, force:false
2023/09/17 15:53:36 DEBUG - restart xray, force:false
2023/09/17 15:53:06 DEBUG - restart xray, force:false
2023/09/17 15:52:36 DEBUG - restart xray, force:false
2023/09/17 15:51:26 DEBUG - restart xray, force:true
2023/09/17 15:51:26 INFO - web server run http on[::]:54321
2023/09/17 15:51:26 WARNING - stop server err:multierr: close tcp [::]:54321: use of closed network connection | 
2023/09/17 15:51:26 DEBUG - stop xray
2023/09/17 15:51:16 DEBUG - restart xray, force:false
2023/09/17 15:50:46 DEBUG - restart xray, force:false
2023/09/17 15:50:16 DEBUG - restart xray, force:false
2023/09/17 15:49:46 DEBUG - restart xray, force:false
2023/09/17 15:49:16 DEBUG - restart xray, force:false
2023/09/17 15:48:46 DEBUG - restart xray, force:false
2023/09/17 15:48:16 DEBUG - restart xray, force:false
2023/09/17 15:47:46 DEBUG - restart xray, force:false
2023/09/17 15:47:16 DEBUG - restart xray, force:false
2023/09/17 15:46:46 DEBUG - restart xray, force:false
2023/09/17 15:46:16 DEBUG - restart xray, force:false
2023/09/17 15:45:46 DEBUG - restart xray, force:false
2023/09/17 15:45:16 DEBUG - restart xray, force:false
2023/09/17 15:44:46 DEBUG - restart xray, force:false
2023/09/17 15:44:16 DEBUG - restart xray, force:false
2023/09/17 15:43:46 DEBUG - restart xray, force:false
2023/09/17 15:43:16 DEBUG - restart xray, force:false
2023/09/17 15:42:46 DEBUG - restart xray, force:false
2023/09/17 15:42:16 DEBUG - restart xray, force:false
2023/09/17 15:41:46 DEBUG - restart xray, force:false
2023/09/17 15:41:16 DEBUG - restart xray, force:false
2023/09/17 15:40:46 DEBUG - restart xray, force:false
2023/09/17 15:40:16 DEBUG - restart xray, force:false
2023/09/17 15:39:46 DEBUG - restart xray, force:false
2023/09/17 15:39:16 DEBUG - restart xray, force:false
2023/09/17 15:38:46 DEBUG - restart xray, force:false
2023/09/17 15:38:16 DEBUG - restart xray, force:false
2023/09/17 15:37:46 DEBUG - restart xray, force:false
2023/09/17 15:37:16 DEBUG - restart xray, force:false
2023/09/17 15:36:46 DEBUG - restart xray, force:false
2023/09/17 15:36:16 DEBUG - restart xray, force:false
2023/09/17 15:35:46 DEBUG - restart xray, force:false
2023/09/17 15:35:16 DEBUG - restart xray, force:false
2023/09/17 15:34:46 DEBUG - restart xray, force:false
2023/09/17 15:34:16 DEBUG - restart xray, force:false
2023/09/17 15:33:46 DEBUG - restart xray, force:false
2023/09/17 15:33:16 DEBUG - restart xray, force:false
2023/09/17 15:32:46 DEBUG - restart xray, force:false
2023/09/17 15:32:16 DEBUG - restart xray, force:false
2023/09/17 15:31:46 DEBUG - restart xray, force:false
2023/09/17 15:31:16 DEBUG - restart xray, force:false
2023/09/17 15:30:46 DEBUG - restart xray, force:false
2023/09/17 15:30:16 DEBUG - restart xray, force:false
2023/09/17 15:29:46 DEBUG - restart xray, force:false
2023/09/17 15:29:16 DEBUG - restart xray, force:false
2023/09/17 15:28:46 DEBUG - restart xray, force:false
2023/09/17 15:28:16 DEBUG - restart xray, force:false
2023/09/17 15:27:46 DEBUG - restart xray, force:false
2023/09/17 15:27:16 DEBUG - restart xray, force:false

</details>

**Comment by MountU0** [comment]
When you sending an api post request its compulsory to put "method".

It's like that:
    json_val = {
        "clients": [{"id": f"{tg_id}",
        "password": f"{password}",
        "email": f"{tg_id}",
        "limitIp": 1,
        "method": "aes-256-gcm",
        "totalGB": 0,
        "expiryTime": 0,
        "enable": enable,
        "tgId": "",
        "subId": f"{subId}"}]
    }

**Comment by poznavatel** [comment]
Similar problem.
![2023-10-23_092612](https://github.com/MHSanaei/3x-ui/assets/73876405/9046daaa-74aa-458f-b70d-c642919d3994)

This appeared after the update to v1.7.9.

**Errors in the logs are like this:**

ERROR[0237] dns: exchange failed for classify-client.services.mozilla.com. IN A: Post "https://8.8.8.8/dns-query": dial tcp 193.xx.xx.xx:433: connectex: No connection could be made because the target machine actively refused it.
ERROR[0238] dns: exchange failed for dns.msftncsi.com. IN A: Post "https://8.8.8.8/dns-query": dial tcp 193.xx.xx.xx:433: connectex: No connection could be made because the target machine actively refused it.

---

There is no connection either on the PC or on the phone.

**Comment by poznavatel** [comment]
> Similar problem. ![2023-10-23_092612](https://user-images.githubusercontent.com/73876405/277247088-9046daaa-74aa-458f-b70d-c642919d3994.jpg)
> 
> This appeared after the update to v1.7.9.
> 
> **Errors in the logs are like this:**
> 
> ERROR[0237] dns: exchange failed for classify-client.services.mozilla.com. IN A: Post "https://8.8.8.8/dns-query": dial tcp 193.xx.xx.xx:433: connectex: No connection could be made because the target machine actively refused it. ERROR[0238] dns: exchange failed for dns.msftncsi.com. IN A: Post "https://8.8.8.8/dns-query": dial tcp 193.xx.xx.xx:433: connectex: No connection could be made because the target machine actively refused it.
> 
> There is no connection either on the PC or on the phone.

I reset the settings and everything was resolved.

**Comment by blca1** [comment]
How to solve the problem?

**Comment by MountU0** [comment]
Answered above

> How to solve the problem?

**Comment by blca1** [comment]
> Answered above
> 
> > How to solve the problem?

"method": "aes-256-gcm" 
I don't have this option in my configuration

**Comment by MHSanaei** [comment]
@blca1 go to xray configs and click on "reset to default" 
then set your settings again

**Comment by anartikov** [comment]
A similar problem has appeared today. Everything worked fine yesterday. I didn't change any settings.
