### ISSUE TITLE
نحوه اپدیت پنل

### ISSUE THREAD

**Issue by Hameddevflutter** [MHSanaei/3x-ui#1066]
دوستان من میخوام پنل و اپدیت کنم به مشکل میخورم

**Comment by Saeedg21** [comment]
از دیتابیست پشتیبان بگیری کافی هست مشکلی هم باشه میتونی خودت حذف و نصب مجدد کنی و دیتابیس رو بارگذاری کنی و همه کانفیگ هات بیاد

**Comment by Hameddevflutter** [comment]
آهان دمت گرم نمیشه پس از طریق ssh اپدیت زد باید حتما پاک بشه ؟

**Comment by MHSanaei** [comment]
x-ui update

Or

x-ui then number 2 

Or

bash <(curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh)
