### ISSUE TITLE
آستانه ترافیک باقی مانده و آستانه زمان باقی مانده

### ISSUE THREAD

**Issue by elegance666** [MHSanaei/3x-ui#1067]
سلام، کسی میدونه این دوتا هشدار آیا به آی دی تلگرام اکانت ها ارسال میشه یا به chat id که در قسمت تنظیمات تلگرام وارد شده؟
من میخوام با یک بات بخونم اینارو ولی نمیدونم به کجا ارسال میشه....

**Comment by Saeedg21** [comment]
chat_id admin
