### ISSUE TITLE
محاسبه اشتباه ترافیک

### ISSUE THREAD

**Issue by m2tts2001** [MHSanaei/3x-ui#1070]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

با سلام و خسته نباشید
امروز یه چیز خیلی مهم دریافتم
من رو سرورم دوتا پنل بالا آوردم یکی با داکر یکی عادی
بعد از مدتی دارم چک میکنم میبینم کلا محاسبه ترافیک اختلال پیدا کرده و کمتر محاسبه میشه. این اختلال هم برای پنل اصلی و هم برای پنل روی داکر وجود داره. چندین بار تست کردم و فایل های مختلف رو با حجم مشخص و با چندین سرور تست گرفتم گاهی حتی ترافیک مصرفی رو در حد نصف نشون میده.
برای سرور هایی که فقط پنل اصلی نصبه محاسبه ترافیک هیچ مشکلی نداره فقط اونایی که همزمان هر دو وصل هست
اینم بگم که از آخرین ورژن استفاده میکنم. نام یوزرها هیچ مشکلی نداره و از فاصله و ... در نان یوزر استفاده نشده.
حدسم اینه که باید پورت 62789 که هسته داره لیسن میکنه برای این دوتا فرق کنه وگرنهاین اختلال وجود داره. 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
سلام
به دلیل اینکه نباید روی یه سرور دوتا پنل نصب کرد اختلال ب وجود میاد

**Comment by m2tts2001** [comment]
پورت 62789 که داخل کانفیگ xray پنل هست رو برای یکی از پنل ها تغییر دادم و درست شد محاسبه ترافیک.
