### ISSUE TITLE
مصرف عجیب 

### ISSUE THREAD

**Issue by amg9898** [MHSanaei/3x-ui#1071]
سلام خسته نباشید

من پنل شما رو دارم عالیه اما به مشکل عجیبی خوردم
این مصرف کل کاربراست هیچ کاربری هم حذف نشده

![image](https://github.com/MHSanaei/3x-ui/assets/105120098/6c5f26af-ddb5-49bb-a9bf-8923b46c7241)
اما این حجم کل مصرف شده هر لحظه هم میره بالاتر
![image](https://github.com/MHSanaei/3x-ui/assets/105120098/0305e255-3d80-4390-85cd-084606e9b062)

چیکار کنم

**Comment by S0R0SH** [comment]
دقیقا منم دوروزه اینطوری شدم چرا ؟؟!؟!؟!؟! 🤢🤢🤢🤢🤢🤢🤢🤢

**Comment by S0R0SH** [comment]
تعداد TCP Connection ها مثلا 90 هست یهو تا 2300 یا 1800 میره بالا بعد cpu هم میچسبه درصورتیکه قبلا مصرف cpu زیر 30% بوده !!! تمامی کاربرهای جدید این دوروزه هم پاک کردم گفتم شاید یه کانفیگی این وسط داره اذیت میکنه بازم فرقی نکرد. برش گردوندم به بک آپ یک هفته پیش بازم حل نشد ؟! چرا ؟

**Comment by AntoniMatrix** [comment]
دقیقا دو روزه اینجوری شده مصرف CPU و memory بطور وحشتناکی میره بالا و کانفیگ ها قطع و وصل میشه من از ورژن 1.7.6 اپدیت کردم به 1.7.8 بهتر شد ولی همچنان مشکل هست و فقط یکم CPU پیادار تر شده

**Comment by S0R0SH** [comment]
نمیدونم آقا محسن چکار کرد یا نکرد ولی امروز انگار cpu نمیکشه. شما هم اینطوری هستید ؟ انگار اوکی شده

**Comment by AntoniMatrix** [comment]
اره چک کردم یکم بعد از کامنت من اوکی شد مصرف cpu و رم پایدار شده

**Comment by AntoniMatrix** [comment]
ولی اگر چیزی رو تغییر داده باشه فکر کنم باید اپدیت نسخه جدید بدن البته
نمیدونم من از این موردش خیلی سر در نمیارم

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
