### ISSUE TITLE
سلام دلیل این ارور چیه و باید چیگار کرد؟

### ISSUE THREAD

**Issue by aliafraz744** [MHSanaei/3x-ui#1074]
Xray 1.8.4 (Xray, Penetrates Everything.) Custom (go1.21.0 linux/amd64)

A unified platform for anti-censorship.

2023/09/19 20:18:39 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: VLESS clients: "flow" doesn't support "xtls-rprx-direct" in this version

**Comment by Arman-nsb** [comment]
سلام، دیتابیس قدیمی منتقل کردید به پنل جدید ؟

**Comment by aliafraz744** [comment]
> xtls-rprx-direct

سلام من اصلا چیزی سر در نمیارم خداوکیلی آمیانه بگو باید چ کنم

**Comment by aliafraz744** [comment]
> فلو xtls-rprx-direct منسوخ شد. از دیتابیس پاکش کنید به کمک ابزار SQLite Database Browser

چجوری

**Comment by MHSanaei** [comment]
شما دیتابیس قدیمی رو ریخیتن روی پنل
برای حل این مشکل بعد از ابجایی دیتابیس یکبار پنل رو اپدیت کنید تا مشکلات دیتابیس حل بشه
روش های اپدیت هم یا از لینک bash استفاده کنید یا x-ui update

**Comment by ToorajValaee** [comment]
It's because there was a client with xtls valued xtls-rprx-direct

to fix it, just edit your clients and make not in xtls, if xtls is off, then turn it on, change it to not and then you can turn it off again
