### ISSUE TITLE
Dont work IP Limit

### ISSUE THREAD

**Issue by Parsa-n** [MHSanaei/3x-ui#1084]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

ای پی لیمیت تعریف میکنم اما کار نمیکنه اصن. تو قسمت لاگ هم میبینم مثلا ۲ تا میزارم اما میشه ۵ نفر همزمان هم وصل شد. پنل رو هم از اول اوردم بالا باز این مشکل برطرف نشد. ممنون میشم کمک کنید.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by neerro** [comment]
Actually It doesn't work for me too with several different IP's. IP's not from local network :)

**Comment by blackgyana** [comment]
ip limit works only with "None" in Flow user param
