### ISSUE TITLE
define limited user (تعریف کاربر محدود شده)

### ISSUE THREAD

**Issue by bmv2020** [MHSanaei/3x-ui#1085]
Hi
I wanted you to add a feature so that we can define a user that can only manipulate users of the inbound. It means that he can add and remove users and disable them, but he cannot change other configurations of the system. It means that he cannot change the settings of this inbound and its maximum volume. With this method, we can create a panel and give this limited user to the seller, who can manage the users himself, but cannot make any changes in the server, and also cannot abuse the specified volume of this inbound.

سلام
می خواستم یه فیچر اضافه کنید بابت اینکه بتونیم یک یوزر تعریف کنیم که فقط امکان دستکاری روی کاربرای یک اینباند رو داشته باشه. یعنی بتونه کاربر اضافه و کم کنه و غیر فعال کنه ولی نتونه جای دیگه سیستم رو عوض کنه. یعنی نتونه تنظیمات اینباند و حداکثر حجمش رو عوض کنه. با این روش می تونیم یک پنل بسازیم و این یوزر محدود رو به فروشنده بدیم که خودش یوزر ها رو مدیریت کنه ولی نتونه هیچ تغییری تو سرور بده و همچنین از حجم مشخص شده اینباند نتونه تجاورز کنه.

**Comment by wulfric93** [comment]
این حالت اگر ایجاد بشه عالیه

**Comment by Ghasem1243** [comment]
من اینکار را کردم ولی با ربات تلگرام به طرف یک پورت میدم که فقط با این پورت میتونی بسازه و تمدید کنه در ضمن هر اکانت که بسازه یا تمدید کنه  توی لیست بدهیش میاد
