### ISSUE TITLE
ناپدید شدن یوزر ها در قسمت اینبوند

### ISSUE THREAD

**Issue by MahdiTvK5** [MHSanaei/3x-ui#1086]
سلام من یوزر هام در اینبوند ناپدید شدن و انگار پنل از صفره ولی یوزر هام کانکتن مشکل از کجا میتونه باشه ؟

**Comment by blckb0x** [comment]
مشکل مشابه دارم. برای من بعد از وصل کردن پنل ویزویز مشکل به وجود اومده. وقتی وارد صفحه اینباند میشی کاملا خالیه. فیتلر هارو یکبار فعال و غیر فعال کنی تعدادی اینباند قدیمی نمایش میده اما جدیدا رو نمیاره. دیتابیس به ظاهر مشکلی نداره. به ورژن های قدیمی تر داونگرید کردم اما هنوز مشکل پابرجاست. سعی میکنم برنامه رو ریبیلد کنم نتیجه رو اعلام میکنم. ممنون میشم کسی راه حلی داره بگه!!

**Comment by blckb0x** [comment]
> مشکل مشابه دارم. برای من بعد از وصل کردن پنل ویزویز مشکل به وجود اومده. وقتی وارد صفحه اینباند میشی کاملا خالیه. فیتلر هارو یکبار فعال و غیر فعال کنی تعدادی اینباند قدیمی نمایش میده اما جدیدا رو نمیاره. دیتابیس به ظاهر مشکلی نداره. به ورژن های قدیمی تر داونگرید کردم اما هنوز مشکل پابرجاست. سعی میکنم برنامه رو ریبیلد کنم نتیجه رو اعلام میکنم. ممنون میشم کسی راه حلی داره بگه!!

مشکل از دیتابیس بود. ربات ویزویز یوزر رو از اینبوند حذف کرده بود اینبوند خالی مونده بود. یه صورت دستی از دیتابیس اینبوند رو حذف کردم و دوباره روی سرور آپلود کردم.

**Comment by MahdiTvK5** [comment]
> مشکل مشابه دارم. برای من بعد از وصل کردن پنل ویزویز مشکل به وجود اومده. وقتی وارد صفحه اینباند میشی کاملا خالیه. فیتلر هارو یکبار فعال و غیر فعال کنی تعدادی اینباند قدیمی نمایش میده اما جدیدا رو نمیاره. دیتابیس به ظاهر مشکلی نداره. به ورژن های قدیمی تر داونگرید کردم اما هنوز مشکل پابرجاست. سعی میکنم برنامه رو ریبیلد کنم نتیجه رو اعلام میکنم. ممنون میشم کسی راه حلی داره بگه!!

من مشکلم از سمت رباتی بود که خودم طراحی کرده بودم یوزر اصلی رو حذف کرده بودم و به همین علت اینبوند ها نمایش داده نمیشدن ، مجددا یوزر اصلی رو که ناخواسته حذف شده بود رو ادد کردم داخل دیتابیس مشکلم برطرف شد ، میدونم خیلی دور شده ولی شاید برای افرادی دور بوده باشه شما خودتم که پیدا کردید راه حل رو
