### ISSUE TITLE
نحوه اتصال یوزر ها در ساب اسکریپشن

### ISSUE THREAD

**Issue by bestkilleriranlod** [MHSanaei/3x-ui#1088]
سلام خدمت دوستان
قابلیتی هست در پنل تا بشه یک ساب اسکریپشن به کاربر داد ولی چندین اینباند برای کاربر تنظیم بشه
مثلا الان هر یوزری در هر اینباندی ایجاد بشه لینک ساب اسکریپشنش تولید میشه برای همون اینباند
ولی مشکلی که هست زمانیکه نیاز هست برای یک کاربر چندین کانفیگ با پرتکل های مختلف ایجاد بشه امکانش نیست
ممنون میشم راهنمایی کنید اگر راهی هست

**Comment by rooshanak** [comment]
آره میشه. شما دو تا اینباند درست می کنی با اسم ساب یک شکل

**Comment by bestkilleriranlod** [comment]
اینکارو که میکنم باگ زیاد داره
یک اینکه مسئله حجم ها سینک نیستن
یک مسئله اینکه ایمیل ها میگه یکسان نباید باشن
یک مسئله اینکه uuid ها یکسان نمیتونن باشن
در کل اینا فکر میکنم باید سیستمی تنظیم بشه
