### ISSUE TITLE
قرار دادن ای پی کلادفلر برای کانفیگ

### ISSUE THREAD

**Issue by radinVFX** [MHSanaei/3x-ui#1089]
درود
بنده قصد دارم ای پی تمیز کلادفلر به اینباندم بدم
اما وقتی در قسمت listening ip اینباندم قرار میدم ( چه ای پی چه دامین ) هسته ایکس ری اررور میده و متوقف میشه
باید در listening ip، ای پی کلادفلر رو بدم؟
میشه به جای ای پی دامین داد؟
دلیل مشکلم چه چیزی میتونه باشه؟

**Comment by misagh72** [comment]
![Opera Snapshot_2023-09-29_222355_209 38 200 85](https://github.com/MHSanaei/3x-ui/assets/49818860/eb1a9cb8-c782-45bb-8f7f-df01ef408e79)
دراین قسمت باید قرار بدین

**Comment by radinVFX** [comment]
خیلی ممنون از راهنماییتون
امکانش هست کمی بیشتر توضیح بدید
مثلا:
ایا باید از پورت کلادفلر استفاده کنم؟
در قسمت sni خالی باشه موردی نداره؟
می توانم در کنار vmess و ws از tls هم استفاده کنم و دامینم رو قرار بدم؟
@misagh72

**Comment by misagh72** [comment]
بله وقتی پروکسی روی دامنه روشن میکنید باید فقط از پورت ها مخصوص استفاده کنید 
در قسمت sni باید دامنه خودتون رو با پروکسی روشن و domain name سایت روی کلوفلر یا ای پی قرار بدین
