### ISSUE TITLE
huge database problem

### ISSUE THREAD

**Issue by kalilovers** [MHSanaei/3x-ui#1103]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

There is a big problem in the database. When we delete users, they remain in the database and over time it causes the database to become heavy and problematic. For this reason, even though the number of clients decreases, the size of the database only increases 

so important . i checked with sql lite

i have only 400 client . most of these removed in panel . update not fix it

https://app.gemoo.com/share/image-annotation/568139105089368064?codeId=DGqyN1EjOxBab&origin=imageurlgenerator

### Version of 3x-ui

<latest>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by AmoAlireza** [comment]
there is option called Vacuum on your sqlite expert, just open the database file and press the Vacuum.
![Capture](https://github.com/MHSanaei/3x-ui/assets/79990596/6e9e39eb-3d81-4b1f-b8e1-978cf2cd30e4)

**Comment by StayAway32** [comment]
@AmoAlireza can you do the same on ssh ? is it possible to install sqlite on my pc and remotely connect to servers db to issue cleaning stuff like vacuum ? thanks

**Comment by StayAway32** [comment]
or if there is a command i can use after :
apt-get install sqlite3
in order to get the vacuum going via ssh
thanks

**Comment by AmoAlireza** [comment]
yes you can.
first install sqlite3: ```apt install sqlite3```
enter the crontab: ```crontab -e```
then enter this line: ``` 0 0 * * * sqlite3 /etc/x-ui/x-ui.db 'VACUUM;' ```

this will vacuum the database file every day automatic.

**Comment by StayAway32** [comment]
@AmoAlireza thanks alot i have done the following and put the line in the config it brought for me :)
have a great day

**Comment by kalilovers** [comment]
> yes you can. first install sqlite3: `apt install sqlite3` enter the crontab: `crontab -e` then enter this line: `0 0 * * * sqlite3 /etc/x-ui/x-ui.db 'VACUUM;'`
> 
> this will vacuum the database file every day automatic.

whats do this vacuum ?

**Comment by AmoAlireza** [comment]
> > yes you can. first install sqlite3: `apt install sqlite3` enter the crontab: `crontab -e` then enter this line: `0 0 * * * sqlite3 /etc/x-ui/x-ui.db 'VACUUM;'`
> > this will vacuum the database file every day automatic.
> 
> whats do this vacuum ?

https://www.sqlite.org/lang_vacuum.html
