### ISSUE TITLE
xray core restart problem

### ISSUE THREAD

**Issue by xDShahab** [MHSanaei/3x-ui#1106]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

با سلام 
اول از همه تشکر بابت پشتیبانی خوبتون

یک مشکلی که چند روز هست بنده و بعضی از دوستان باهاش روبه رو هستیم اینه که هر 5 تا 10 دقیقه xray core ریستارت میشه
ورژن های 1.7.1 و 1.7.8 رو تست کردم
با یوزر های فعال تست کردم
با یوزر های غیرفعال تست کردم
xray core رو به ورژن های مختلف تغییر دادم
CPU و Ram  سرور به اندازه کافی هست
هارد سرور جا داره

لطفا راهنمایی کنید که چیکار کنیم

با تشکر

### Version of 3x-ui

<details>

```console
# 1.7.8
```

</details>

### x-ui log reports or xray log

<details>

```console

```

</details>

**Comment by javadghasemi** [comment]
Hi. this is my problem too.

**Comment by javadghasemi** [comment]
Hi. This is my problem too.

**Comment by Ahmedeisa25** [comment]
I have same proplem tried many servers all has same issue

**Comment by somebodywashere** [comment]
Send your logs guys. If you can't catch any just make a screenshot when it appears on the panel (when red error instead of green running status)
