### ISSUE TITLE
How to manage inbounds via shell/script

### ISSUE THREAD

**Issue by blackgyana** [MHSanaei/3x-ui#1107]
Hi
I just want to create/edit/delete inbounds without using UI, but using API backend to execute some shell commands for this purpose. Is it possible now?

**Comment by blackgyana** [comment]
as I understand it, so far this is only possible through the web api

**Comment by jalalsaberi** [comment]
you can use the api

https://gist.github.com/mehdikhody/9a862801a2e41f6b5fb6bbc7e1326044
