### ISSUE TITLE
Telegram Notification Inbound/Client Expire Date

### ISSUE THREAD

**Issue by pro9793** [MHSanaei/3x-ui#1110]
Please make the notification by Telegram Bot - for example 24h before the expire date/time of inbound/client. And the Filter "depleting soon" is not working with Inbounds. Thanks!

**Comment by freeiance** [comment]
There are two configs in panel settings named `Traffic threshold for notification` and `Expiration threshold for notification` in first tab of `Panel Settings` but they don't work properly and do not send any message on expiration or hitting traffic limit!

This is a BUG!

**Comment by pro9793** [comment]
> There are two configs in panel settings named `Traffic threshold for notification` and `Expiration threshold for notification` in first tab of `Panel Settings` but they don't work properly and do not send any message on expiration or hitting traffic limit!
> 
> This is a BUG!

Yes, these settings in panel doesn't work.

**Comment by mse7810** [comment]
سلام مهندس. https://github.com/diditra/x-ui
اگه میشه رباط اینو به پنل خودتون اضاف کنید.
این رباط عالیه
