### ISSUE TITLE
Cpu 100

### ISSUE THREAD

**Issue by omrani77** [MHSanaei/3x-ui#1112]
![Screenshot_2023-10-07-20-02-48-304_org.telegram.messenger.jpg](https://github.com/MHSanaei/3x-ui/assets/75359189/2b1615ca-b4cf-4ed9-8b0f-c9cc373307ea)

چرا؟

**Comment by saeedjamshidi** [comment]
یک بار پنل رو آپدیت کن مشکل برطرف می‌شه
دیتا هم پاک نمی‌شه

![image](https://github.com/MHSanaei/3x-ui/assets/32639886/fd25cbe2-582d-4844-9fea-4c3130ef84de)

**Comment by mrlollollol** [comment]
سلام
منم همین مشکل رو داشتم و آپدیت کردم
فعلا که اوکیه...ممنون

**Comment by arian2240** [comment]
> سلام منم همین مشکل رو داشتم و آپدیت کردم فعلا که اوکیه...ممنون

من تو اخرین نسخه این مشکلو دارم چطوری با اپدیت حل کردید شما اوردم نسخه پایین تر حل شد

**Comment by saeedjamshidi** [comment]
الان چون نسخه‌ی جدید ریلیز نشده، با آپدیت کردن، همان نسخه‌ی آخر مجدد نصب می‌شه و علت مصرف بالای CPU هر چه که هست (احتمالا باگ امنیتی باشه) برطرف می‌شه. 
ممکنه این باگ در نسخه‌های پایین‌تر وجود نداشته باشه، که در این صورت احتمالا دیگه به این مشکل برنخواهید خورد.

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
