### ISSUE TITLE
Hello admin

### ISSUE THREAD

**Issue by Thaomtam** [MHSanaei/3x-ui#1114]
Hello admin, I want to ask about the fact that I have a server running 3x-ui. Can I add configuration from another vps on the server running 3x-ui? If so, please cite the instructions for use. Tks

**Comment by neerro** [comment]
Which kind of configuration you wanna add?

**Comment by Thaomtam** [comment]
> Which kind of configuration you wanna add?

VPS A + configured from vps B, same as v2board nodes
