### ISSUE TITLE
99.9% hard disk space

### ISSUE THREAD

**Issue by AFord7373** [MHSanaei/3x-ui#1123]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [ ] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

The server hard drive space is completely full. I can no longer create profiles. How can I clear it so as not to affect the operation of the configs? And how can I clean it according to a script every 2 days?
![chrome_EoWLyltVZo](https://github.com/MHSanaei/3x-ui/assets/147619340/5c274e11-8594-4fda-b4c8-0fba8e095b68)
![chrome_e39fPuaJ3f](https://github.com/MHSanaei/3x-ui/assets/147619340/8c59b4b5-8104-47f8-81a3-60858359406b)

### Version of 3x-ui

<details>

```console
# 1.7.8
```

</details>

### x-ui log reports or xray log

<details>

```console
# 2023/10/11 15:59:27 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:59:17 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:59:07 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:58:57 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:58:47 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:58:37 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:58:27 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:58:17 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:58:07 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:57:57 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:57:47 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:57:37 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:57:27 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:57:17 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:57:07 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:56:57 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:56:47 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:56:37 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:56:27 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:56:17 WARNING - AddClientTraffic update data database or disk is full
2023/10/11 15:56:07 WARNING - AddClientTraffic update data database or disk is full
```

</details>

**Comment by wulfric93** [comment]
Just Remove access.log file at /usr/local/x-ui/access.log
and if you don't use ip limit feature, delete this section from your x-ui template :
"log": {
    "access": "./access.log",
    "error": "./error.log",
    "loglevel": "warning"
  },

**Comment by AFord7373** [comment]
> Just Remove access.log file at /usr/local/x-ui/access.log and if you don't use ip limit feature, delete this section from your x-ui template : "log": { "access": "./access.log", "error": "./error.log", "loglevel": "warning" },

I'm using fork of x-ui (3x-ui). Could this affect the location of the file? I can't find it on my system.
![BvSsh_o47twBSbbQ](https://github.com/MHSanaei/3x-ui/assets/147619340/5d5dcfe0-3650-46b2-bc6a-312eb0ec4966)
![BvSsh_AipXZbYjEa](https://github.com/MHSanaei/3x-ui/assets/147619340/fa432beb-02f3-4d8e-8ce3-359873eb6f52)
![totermw_U9fnpXFSbV](https://github.com/MHSanaei/3x-ui/assets/147619340/045b5066-fe18-4b97-8365-74442b792482)
