### ISSUE TITLE
مشکل ای پی لیمیت

### ISSUE THREAD

**Issue by mahsat-ir** [MHSanaei/3x-ui#1126]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

درود بر شما که در راه آزادی اطلاعات در ایران تلاش میکنید
fail2ban رو بدون مشکل از طریق گزینه 17 فعال و نصب کردم 
چک استاتوسم میزنم بدون مشکل فعال شده
ای پی هایی که باید لیمیت بشن هم در 3xipl.log گزارش داده میشن 
اما سیستم هیچ محدودیتی برای کتنکشن قائل نمیشه !
ممنون میشم راهنمایی کنید

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by AmoAlireza** [comment]
آپشن ip limit فقط بصورت مستقیم عمل میکنه و اگر تانل استفاده میکنید کار نمیکنه.

ولی اگر بصورت مستقیم هستید با نرم افزار sqlite expert فایل x-ui.db باز کنید و داخل قسمت inbound_client_ips تمامی ای پی کاربران delete record کنید و یکبار هم از قابلیت vacuum استفاده کنید.

برای اینکه اشتباهی کسی محدود نشه قابلیتی وجود داره که چند بار تست میکنه که آیا کاربر با چندین دستگاه متصل شده یا نه پس همون موقع وقتی کاربر مورد تعین شده در قسمت ip limit به حدش رسید انتظار اینکه سریع کاربر اضافی محدود کنه نداشته باشید و در مدت 1 دقیقه این وضوع تست کنید.

**Comment by mahsat-ir** [comment]
مشکل     "access": "./access.log", بود که باید در فایل پیکربندی ایکس ری وارد میشد
