### ISSUE TITLE
 نمایش کاربر انلاین و اضافه کردن پروتکل hysteria

### ISSUE THREAD

**Issue by mostafs** [MHSanaei/3x-ui#1128]
سلام و خدا قوت
امکان نمایش کاربر انلاین رو لطفا ایجاد کنید
اگه میشه پروتکل hysteria  رو اضافه بکنین  

سپاس فراوان

**Comment by uzer98** [comment]
اگه پروتکل hysteria,TUIC اضافه بشه خیلی عالیه
تو‌اولویت هاتون قرار بدید
نمایش کاربران آنلاین هم خوبه

**Comment by mmwong1984** [comment]
@MHSanaei I wish you can add hysteria soon, it is wonderful

**Comment by livingfree2023** [comment]
Hysteria 2 works very well, hope we can support it soon
