### ISSUE TITLE
Fail2Ban - Docker installation

### ISSUE THREAD

**Issue by dev-ehsan-babaei** [MHSanaei/3x-ui#1129]
Hi,

Is there any way to install fail2ban via docker installation method?
Or any way to exec x-ui command in docker at all?

**Comment by kksudo** [comment]
I guess fail2ban already in the Docker, but with 0 enable jails. Also I can't find the way to configure it without rebuild the Docker image. 
[Here](https://github.com/MHSanaei/3x-ui/blob/main/Dockerfile#L36) is installation
Still wait here to answer about this topic.

**Comment by dev-ehsan-babaei** [comment]
Found the solution...
we should add below field to xray config:
"log": {
"loglevel": "warning",
"access": "./access.log",
"error": "./error.log"
},

**Comment by kksudo** [comment]
BTW, how to configure fail2ban jails? What is default job for fail2ban? 
Block unsuccessful auth to the proxy\vpn, but there is no enable jails ....

fail2ban-client  status
````
Status
|- Number of jail:	0
`- Jail list:
```

**Comment by dev-ehsan-babaei** [comment]
submitted new issue:
https://github.com/MHSanaei/3x-ui/issues/1168
