### ISSUE TITLE
Cron job format

### ISSUE THREAD

**Issue by elegance666** [MHSanaei/3x-ui#1130]
برای کران جاب تلگرام میشه اینطوری نوشت؟
@every 23h 59m 30s

کار میکته هر ۲۳ ساعت و ۵۹ دقیقه و ۳۰ ثانیه؟

**Comment by AmoAlireza** [comment]
بله این امکان هست.
همچنین میتونید به اینصورت هم استفاده کنید:```daily at 23:59:30@```

**Comment by z0ow** [comment]
I am encountering the same problem as you.

The cron job format can be retrieved from [go/cron](https://pkg.go.dev/github.com/robfig/cron).

In brief, you could use "seconds minutes hours days months years" a total of six fields to specify when to send the notification. It slightly differs from the Linux cron job but is easy to understand.

Besides, it also can be written in "@hourly xxx" from the documentation.
