### ISSUE TITLE
x-ui update in command line cannot be executed successfully.

### ISSUE THREAD

**Issue by ghost** [MHSanaei/3x-ui#1132]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

x-ui update in command line cannot be executed successfully.
Try typing "n" or just press "Enter"
but always wrong.
I checked the x-ui log, but didn't see any information about this.

<img width="841" alt="Snipaste__name_desk__2023-10-16_03-29" src="https://github.com/MHSanaei/3x-ui/assets/118535944/5d7fb016-6a6a-46eb-9a76-f34af1cca863">

OS: Ubuntu 22.04

### Version of 3x-ui

<details>

```console
1.7.8
```

</details>

### x-ui log reports or xray log

<details>

```console
Nolog.
I use the x-ui command line
```
</details>

**Comment by AmoAlireza** [comment]
this is asking you do you want to continue? and you type (n)o or press enter and enter by default is (n)o, so what's the problem?
just type (y)es if you want to update the x-ui.

yes = (y)es
no = (n)o
