### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Mahdi84S** [MHSanaei/3x-ui#1134]
سلام
API ورود با توکن امنیتی را نگذاشتید
اگر گذاشتید یا API دارید لطف کنید برام بفرستید.
با تشکر.

**Comment by alirahimi818** [comment]
> سلام API ورود با توکن امنیتی را نگذاشتید اگر گذاشتید یا API دارید لطف کنید برام بفرستید. با تشکر.
از مقدار LoginSecret برای توکن امنیتی استفاده کنید

`{username: '', password: '', LoginSecret: ''}`

**Comment by Mahdi84S** [comment]
> > سلام API ورود با توکن امنیتی را نگذاشتید اگر گذاشتید یا API دارید لطف کنید برام بفرستید. با تشکر.
> 
> از مقدار LoginSecret برای توکن امنیتی استفاده کنید
> 
> `{username: '', password: '', LoginSecret: ''}`
> 

درود
تست کردم ولی کار نکرد

**Comment by alirahimi818** [comment]
> > > سلام API ورود با توکن امنیتی را نگذاشتید اگر گذاشتید یا API دارید لطف کنید برام بفرستید. با تشکر.
> > 
> > 
> > از مقدار LoginSecret برای توکن امنیتی استفاده کنید
> > `{username: '', password: '', LoginSecret: ''}`
> 
> درود تست کردم ولی کار نکرد


عذرخواهی میکنم حرف اول رو باید بصورت کوچک وارد کنید
loginSecret

```
{username: '', password: '', loginSecret: ''}
```

**Comment by Mahdi84S** [comment]
درست شد

**Comment by Mahdi84S** [comment]
درست شد ، خیلی ممنون

**Comment by Mahdi84S** [comment]
> > > > سلام API ورود با توکن امنیتی را نگذاشتید اگر گذاشتید یا API دارید لطف کنید برام بفرستید. با تشکر.
> > > 
> > > 
> > > از مقدار LoginSecret برای توکن امنیتی استفاده کنید
> > > `{username: '', password: '', LoginSecret: ''}`
> > 
> > 
> > درود تست کردم ولی کار نکرد
> 
> عذرخواهی میکنم حرف اول رو باید بصورت کوچک وارد کنید loginSecret
> 
> ```
> {username: '', password: '', loginSecret: ''}
> ```


درست شد ، خیلی ممنون.

**Comment by Mahdi84S** [comment]
> > > > سلام API ورود با توکن امنیتی را نگذاشتید اگر گذاشتید یا API دارید لطف کنید برام بفرستید. با تشکر.
> > > 
> > > 
> > > از مقدار LoginSecret برای توکن امنیتی استفاده کنید
> > > `{username: '', password: '', LoginSecret: ''}`
> > 
> > 
> > درود تست کردم ولی کار نکرد
> 
> عذرخواهی میکنم حرف اول رو باید بصورت کوچک وارد کنید loginSecret
> 
> ```
> {username: '', password: '', loginSecret: ''}
> ```


کار کرد ، خیلی ممنون.
