### ISSUE TITLE
I have an error in x-ui log

### ISSUE THREAD

**Issue by roozbehsat** [MHSanaei/3x-ui#1138]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I have this error all the time in x-ui log after update to 1.79 :
Oct 18 18:03:47 winning-anemone /usr/local/x-ui/x-ui[567]: WARNING - access.log doesn't exist in your config.json
Oct 18 18:03:57 winning-anemone /usr/local/x-ui/x-ui[567]: WARNING - access.log doesn't exist in your config.json
please help...

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
Hi
Because you use iplimit you need access.log on your xray configuration
Like this

  "log": {
  "loglevel": "warning",
  "access": "./access.log",
  "error": "./error.log"
  },

**Comment by roozbehsat** [comment]
Thanks for your support
One more question:
If I add this in my config, my ip limit is lost?

**Comment by roozbehsat** [comment]
I use failban two... Before new update I don't have this problem... I add this line to my config...

**Comment by am102m** [comment]
I add  "access": "./access.log",   to config.json  :
  "log": {
    "loglevel": "warning",
     "access": "./access.log",
    "error": "./error.log"

  , but after restart x-ui , this line "access": "./access.log"   disappear

**Comment by lvlehr4d** [comment]
سلام روز بخیر ممنون از زحماتتون
