### ISSUE TITLE
ip limit and fail2ban dosen't work in version 1.7.9

### ISSUE THREAD

**Issue by roozbehsat** [MHSanaei/3x-ui#1139]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

متاسفانه در ورژن جدید iplimit و fail2ban کار نمیکنه...
![Screenshot (332)](https://github.com/MHSanaei/3x-ui/assets/119633123/302a0c08-c018-4f92-92b2-d2fc92169e49)
![Screenshot (333)](https://github.com/MHSanaei/3x-ui/assets/119633123/6a0948fc-1aff-4114-b2b3-7a6fdcae88a8)

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by somebodywashere** [comment]
Hello! It doesn't mean that it doesn't work. Send us your 3xipl-banned log via menu x-ui ->17 -> 4 

Also please show your /var/log/fail2ban.log

**Comment by somebodywashere** [comment]
As we talked before there's something wrong with your configuration. You need to have access.log
