### ISSUE TITLE
ip در اپدیت جدید 1.7.9    عدم نمایش 

### ISSUE THREAD

**Issue by qar4al** [MHSanaei/3x-ui#1141]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

توی اپدیت جدید IP نمایش داده نمیشه توی پنل و خالی نشون میده و خالی نشون میده 

![Screenshot 2023-10-19 103713](https://github.com/MHSanaei/3x-ui/assets/63839880/7e5a0ea8-4f09-4df2-9057-920efe3dae2a)
### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
برای اینکه iplimit option هست و برای استفاده باید دو مورد رو انجام بدید یکی اضافه کردن access log به داخل کانفیگ xray 
مورد بعدی نصب fail2ban

"log": {
"loglevel": "warning",
"access": "./access.log",
"error": "./error.log"
},
