### ISSUE TITLE
Update to 1.7.9 - I can't login as admin

### ISSUE THREAD

**Issue by VecH** [MHSanaei/3x-ui#1143]
### Welcome

- [x] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

After update to 1.7.9 version and restart docker container
I can't login as admin

I see my data (name, password and token) in the x-ui.db database
But when I log in I get a login error: Invalid username or password.

p.s. I asked earlier, but no one answered me
Why after the update it still shows that I have the old version 1.7.6

### Version of 3x-ui

version
<details>

```console
1.7.9
```

</details>

### x-ui log reports or xray log

`docker logs 3x-ui`
<details>

```console
2023/10/19 16:41:41 x-ui 1.7.6
2023/10/19 16:41:41 INFO - web server run https on [::]:20020
2023/10/19 16:41:54 WARNING - wrong username or password: "username" "Password"
2023/10/19 16:42:02 WARNING - wrong username or password: "username" "Password"
2023/10/19 16:47:06 WARNING - wrong username or password: "username" "Password"

```

</details>

**Comment by David-Azaani** [comment]
hi
i have the same issue

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/2138#issuecomment-2019435367
