### ISSUE TITLE
Access log Does Not Exist

### ISSUE THREAD

**Issue by StayAway32** [MHSanaei/3x-ui#1146]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام بعد از آپدیت جدید این ارور هر 10 ثانیه بالا میاد کسی میتونه راهنمایی کنه ؟ با تشکر

usr/local/x-ui/x-ui[867]: WARNING - access.log doesn't exist in your config.json

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/1138#issuecomment-1768685978
