### ISSUE TITLE
اختلال تانل با geoip:private

### ISSUE THREAD

**Issue by armanempier** [MHSanaei/3x-ui#1149]
سلام
بعد از آپدیت به 1.7.9 اختلال پیش اومده و واتساپ و یوتیوب و یکسری سایت ها باز نمیشدن . بعد از دو روز تلاش فهمیدم مشکل از geoip:private هست که با حذف کردنش مشکل برطرف شد.
چجوری میشه این مورد رو اصلاح کرد؟

**Comment by armanempier** [comment]
آخه جالبه برام برای کل کاربرام این مشکل پیش اومده بود و همه مشکل داشتن و وقتی geoip:private رو حذف کردم از پنل سرور ایران حل شد مشکل

**Comment by kalilovers** [comment]
بهترین راه اینه یه سرور با ایپی تمیز خارجی بگیرید رو اون dns راه اندازی کنید سروراتونو به اون وصل کنید
