### ISSUE TITLE
نصب سنایی و اجرای آن روی داکر

### ISSUE THREAD

**Issue by Saliizan** [MHSanaei/3x-ui#1151]
درود، من سنایی رو از طریق داکر نصب کردم اما نمی‌دونم چطوری می‌تونم به منوی x-ui سنایی روی داکتر دسترسی داشته باشم، بعد از نصب هم خروجی نداد که دستورات چی هستن مثل پنل مرزبان، لطفاً راهنمایی کنید ممنون می‌شم.

**Comment by ali4crypto** [comment]
سلام.منم دقیقا همین مشکل رو دارم و نمیدونم چطور وارد قسمت مدیریت x-ui که با داکر نصب شده برم؟
لطفا راهنمایی کنید

**Comment by EmirHosen** [comment]
> سلام.منم دقیقا همین مشکل رو دارم و نمیدونم چطور وارد قسمت مدیریت x-ui که با داکر نصب شده برم؟ لطفا راهنمایی کنید

برای ورود به پنل باید با اضافه کردن پورت 2083 به انتهای ادرس دامنه یا آیپی وارد پنل شوید.

**Comment by EmirHosen** [comment]
> درود، من سنایی رو از طریق داکر نصب کردم اما نمی‌دونم چطوری می‌تونم به منوی x-ui سنایی روی داکتر دسترسی داشته باشم، بعد از نصب هم خروجی نداد که دستورات چی هستن مثل پنل مرزبان، لطفاً راهنمایی کنید ممنون می‌شم.

برای ورود به پنل باید با اضافه کردن پورت 2083 به انتهای ادرس دامنه یا آیپی وارد پنل شوید.
