### ISSUE TITLE
مشکل وارپ پلاس و قطعی لینک ها بعد از فعالسازی وارپ در پنل

### ISSUE THREAD

**Issue by niiaco** [MHSanaei/3x-ui#1152]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام . ظاهرا مدتیه پنل با وارپ سازگار نیست - اکانت وارپ پلاس زده میشه (پورت تغییر داده میشه) بعد از فعالسازی از داخل پنل بخش warp configs  آیتم ها رو که فعال میکنم کانکشن ها قطع میشن!
نسخه ی پنل آخرین نسخه ی ریلیز شده هست

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
پورت وارپ پراکسی باید روی ۴۰ هزار باشه در صورت تغییر باید داخل کانفیگ ایکس ری در صفحه تنظیمات تغییر داده بشه
