### ISSUE TITLE
warp for all domains !

### ISSUE THREAD

**Issue by nooblk-98** [MHSanaei/3x-ui#1156]
how enable warp mode for all domains without adding one by one

**Comment by wulfric93** [comment]
`  {
    "protocol": "socks",
    "settings": {
      "servers": [
        {
          "address": "127.0.0.1",
          "port": 40000  #Your WARP Port (Default : 40000)
        }
      ]
    }
  },
  {
    "tag": "blocked",
    "protocol": "blackhole",
    "settings": {}
  }`

**Comment by DxtorJa** [comment]
![image](https://github.com/MHSanaei/3x-ui/assets/125950957/4a1e0913-0cd6-424b-872d-daa3ed9d852f)
 Already did but no work

**Comment by wulfric93** [comment]
Take a closer look at it
is your outbound order is as the one I've provided?
