### ISSUE TITLE
اضافه کردن پروتکل hysteria2 و‌Tuic

### ISSUE THREAD

**Issue by ali4crypto** [MHSanaei/3x-ui#1158]
سلام
لطفا اگه امکانش هست پروتکلهای hysteria2 و‌Tuic رو به پنل اضافه کنید.تا مجبور نشیم به خاطر این دو پروتکل یه پنل مجزا نصب کنیم

**Comment by misagh72** [comment]
نمیشه هسته پنل xray هست این دوتا رو هم ساپورت نمیکنه

**Comment by meta-syfu** [comment]
> نمیشه هسته پنل xray هست این دوتا رو هم ساپورت نمیکنه

نمیشه برای این پروتکل ها از هسته دیگری استفاده کنه؟بطور خودکار..
