### ISSUE TITLE
Block phishing and malware websites.

### ISSUE THREAD

**Issue by mmrabbani** [MHSanaei/3x-ui#1161]
برای حذف سایت‌های حاوی بدافزار می‌توان رویکردهای مختلفی داشت.
۱. یکی از استفاده از لیست تهیه شده توسط  @Chocolate4U است که خودتون اینجا ذکر کردید.

https://github.com/MHSanaei/3x-ui/pull/1047#issuecomment-1768790989

۲. یکی دیگه استفاده از anti-malware cloudflare DNS است. 1.1.1.2
https://blog.cloudflare.com/introducing-1-1-1-1-for-families/
نمی‌دونم کلودفلر چقدر فیشینگ‌های ایرانی رو هم بلاک میکنه. ولی در منابع راه حل اول، منابع ایرانی هم هست. نکته دیگر آنکه کسی که family protection در پنل را روشن می‌کند و پنل DNS را به 1.1.1.3 تغییر می‌دهد، عملا در کنار سایت های بزرگسالان، بدافزارها هم بلاک می‌شوند.

۳. استفاده از هر دو راه حل هم‌زمان

می‌توانید برای خاموش یا روشن کردن این قابلیت در پنل دکمه ای بگذارید یا اینکه این قابلیت برای همه روشن باشد (کسی هست که بخواهد به سایت حاوی بدافزار مراجعه کند؟). ولی اگر تصمیم گرفتید که چنین دکمه ای را بگذارید، پیشنهاد من این است که این قابلیت به صورت پیش‌فرض روشن باشد و اگر کاربری خواست آن را خاموش کند. اینطوی کاربرهای خیلی بیشتری از بدافزارها در امان خواهند ماند

**Comment by tsgcoltd** [comment]
سلام
ممنون از اطلاعاتتون
من از این کد استاده میکنم و هرچی رو که یدا مینم بهش اضافه میکنم ولی اسامی فارسی رو نمیتونم اضافه کتم و سیستم ارور میده 
اگه ممگنه یه راهنمایی بفرمایید
 "outboundTag": "blocked",
        "domain": [
          "ext:geosite_IR.dat:category-ads-all",
          "regexp:.*\\.ir$",
          "regexp:.*\\.xn--mgba3a4f16a$",
          "ext:geosite_IR.dat:ir",
          "geosite:cn",
          "regexp:.*\\.cn$",
          "geosite:category-gov-ru",
          "regexp:.*\\.ru$",
          "snapp",
          "digikala",
          "tapsi",
          "divar",
          "bank",
          "sb24.com",
          "sheypoor.com",
          "anten",
          "xvideos.com",
          "speedtest.net",
          "porn",
          "my.mci.ir",
          "xxx",
          "Torob.com",
          "my.medu.ir",
          "downloadha.com",
          "P30download.com",
          "xnxx",
          "Pornhub",
          "pornhub.com",
          "XNXX.COM",
          "fuq.com",
          "xhamster.com",
          "porn.com",
          "redporn.porn",
          "largehdtube.com",
          "xHamster",
          "xhamster3.com",
          "maturetube.com",
          "PORN",
          "porn-plus.com",
          "xnxx.com",
          "tubepleasure.com",
          "new-porn.video",
          "YouPorn",
          "youporn.com",
          "goldpornfilms.com",
          "largepornfilms.com",
          "hornybank.com",
          "porn300.com",
          "zzztube.com",
          "bestandfree.com",
          "pornhat.one",
          "hello.porn",
          "tubepleasure.com",
          "tnaflix.com",
          "onlybestporn.com",
          "Looti.net",
          "Looti.org",
          "Pornkai.con",
          "Sexiha.com",
          "Nikstar",
          "Babakfilm",
          "shahvani.me",
          "shahvani.com",
          "shahvani.top",
          "shahvani",
          "shahvanii",
          "shahvani.net",
          "anal",
          "gay",
          "guy",
          "pussy",
          "ass",
          "asshole",
          "kon",
          "kos",
          "koos",
          "hole"
        ]
