### ISSUE TITLE
از کار افتادن حذف تبلیفات در آپدیت جدید

### ISSUE THREAD

**Issue by hamidmoghavvemi** [MHSanaei/3x-ui#1165]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام. من از تنظیمات پنل شما از گزینه ی ریموو اد( تبلیغات) استفاده می کردم.
تا به حال مشکل نداشت و به درستی داشت کار می کرد. ولی توی آپدیت جدید دیگه کار نمی کنه

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>v1.7.9

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>v1.7.9

**Comment by Amirbazz** [comment]
منم مشکل مشابه دارم بنظر loyalsoldier در مسدود کردن تبلیغات به خوبی عمل نمیکنه
اگه فایلهای geo ترکیب هردو v2fly domain list community و Chocolate4U (برا مسدودسازی سایتهای ایرانی) بشه نتیجه بهتر میشه بنظرم

**Comment by mmrabbani** [comment]
مشکل حل شده و باید منتظر باشید با آپدیت بعدی حل میشه
https://github.com/MHSanaei/3x-ui/commit/ff55ddd036e2af798e34c4bca6c44cd9ff254786

**Comment by behzadti** [comment]
> مشکل حل شده و باید منتظر باشید با آپدیت بعدی حل میشه [ff55ddd](https://github.com/MHSanaei/3x-ui/commit/ff55ddd036e2af798e34c4bca6c44cd9ff254786)

جسارتا دقیق کدوم آپدیت؟ چون همچنان تا بدین تاریخ مشکل پابرجاس

**Comment by mmrabbani** [comment]
خیلی وقته که مشکل حل شده. کلا چند روز اون مشکل وجود داشت
۱. اگر از خیلی وقت پیش پنل رو دارید ممکنه reset کردن تنظیمات و تنظیم دوباره کمک کنه.
۲. در نظر داشته باشید که بلاک کردن همه تبلیغ ها از طرف سرور امکان پذیر نیست. مثلا تبلیغات یوتیوب توسط هیچ ابزاری در سرور حذف نمیشن و باید بر روی مرورگر کلاینت ابزاری نصب شود. ولی مثلا google ads یا یکتانت کاملا از طرف سرور بلاک میشن.
به نظرم این issue رو میشه به عنوان حل شده بست
