### ISSUE TITLE
راهنمایی در مورد Telegram ID 

### ISSUE THREAD

**Issue by mahmod31** [MHSanaei/3x-ui#1166]
با سلام 
لطفا در مورد گزینه Telegram ID در قسمت add client
 توضیح بدین که میشه مستقیم یوزر رو به ربات هدایت کرد برای مشاهده پروفایلش یا نه ؟

**Comment by wulfric93** [comment]
توی این قسمت :
![Uploading image.png…]()
آیدی عددی یا آیدی حرفی کاربر رو بزنید میتونه مستقیم با زدن دکمه get usage یا به فارسی "آمار کاربر" رو مشاهده کنه
