### ISSUE TITLE
IP limit not working on Docker

### ISSUE THREAD

**Issue by dev-ehsan-babaei** [MHSanaei/3x-ui#1168]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![Screenshot 2023-10-26 143810](https://github.com/MHSanaei/3x-ui/assets/108184286/a3b2a961-a1ac-42e3-bb39-b95dd536bf17)

Logs IPs but cannot ban extra ones.
this is included in Xray config:

{
  "log": {
    "loglevel": "warning",
    "access": "./access.log",
    "error": "./error.log"
  },

### Version of 3x-ui

<details>

1.7.9

</details>

### x-ui log reports or xray log

<details>

/etc/fail2ban # fail2ban-client status
Status
|- Number of jail:      0
`- Jail list:

</details>

**Comment by zertf** [comment]
I think i found answer https://openode.ru/topic/529-3x-ui-xray-shadowsocks-kak-zamena-wireguard-docker-edition/?do=findComment&comment=1858

**Comment by dev-ehsan-babaei** [comment]
@zertf 
Yes it works, but i worry about its side effects, so I asked for authors' guide.

**Comment by alirezaimi** [comment]
not work for me too .

**Comment by u-gayashan** [comment]
did anyone find the answer??
