### ISSUE TITLE
کارنکردن تک کاربره

### ISSUE THREAD

**Issue by reza2450** [MHSanaei/3x-ui#1170]
سلام وقت بخیر خسته نباشید
من پنل رو نصب کردم بعد از اجرا ازطریق ساخت اینباند توی ایپی لیمیت کلاینت 1 رو وارد کردم بعد file2ban روو هم نصب کردم اما بازم تک کاربره نمیشه کسی میدونه مشکل از کجاست

**Comment by misagh72** [comment]
تانل و Cdn تک کاربره نمیشن فقط مستقیم

**Comment by hrasoul2** [comment]
برید قسمت تنظیمات Xray Configuration
گزینه Complete Template
این خط رو پیدا کنید  
 "log": {
    "loglevel": "warning",
    },
و بجاش
"log": {
"loglevel": "warning",
"access": "./access.log",
"error": "./error.log"
},
این رو بزارید دقیق
بعد سیو کنید و ریست کنید پنل رو اوکی میشه

**Comment by tohidtnt** [comment]
دوستان وقتی تانل میزنید این گزینه file2ban رو نصب نکنید و اجرا نکنید. چون آیپی سرور تانل شده بن میشه.

**Comment by alrz-usfi** [comment]
راحی هست روی CDN درست بشه؟
برای من ای پی رو توی لاگ نشون میده که بن شده ولی هیچ تفاوت و اختلالی روی اون کاربر ایجاد نمیشه. مشکل از کجاست؟

**Comment by hrasoul2** [comment]
نه متاسفانه
چون از پشت cdn رد میشه در نهایت تمام ایپی ها تبدیل به یک ایپی کلودفلر میشه و اونجاس که fail2ban همه رو یه ایپی تشخیص میده و نمیتونه بن کنه

**Comment by alrz-usfi** [comment]
> نه متاسفانه چون از پشت cdn رد میشه در نهایت تمام ایپی ها تبدیل به یک ایپی کلودفلر میشه و اونجاس که fail2ban همه رو یه ایپی تشخیص میده و نمیتونه بن کنه

اخه کامل تشخیص میده هر IP رو. ینی دو نفر به یه کانکشن وصلن رو با ای پی های خودشون کامل نشون میده، یکی رو بن میکنه ولی این بن شدنه هیچ تاثیری نداره!!!

**Comment by hrasoul2** [comment]
این درسته
ولی گفتم ببین اون ایپی که بن میشه بخاطر cdn ایپیش تبدیل به ایپی کلودفلر میشه و تو سرور پردازش میشه
سر همین بن نمیشه و میتونه وصل بشه
شما راه داری که این کارو بکنی
ولی باید بصورت دستی دستورات فایروال بزنی تو سرورت
