### ISSUE TITLE
IP log Not working

### ISSUE THREAD

**Issue by Sharevex** [MHSanaei/3x-ui#1174]
Hello to the great team of 3x-ui , I'm using the latest version of 3x-ui panel and I'm on ubuntu 22.04 , but my ip limit function of the panel is not working . it should log the number of ip's connected to a config but it only shows "1" of the "multiple" ip's connected .
How can i solve this problem ?
I'd be thankful for all the help . 
![image](https://github.com/MHSanaei/3x-ui/assets/60724506/db433eb8-f3bb-43e7-b645-3c328c42632f)
Here is an instance , in this case 4 ip's are connected but only one of them is being shown .

**Comment by MHSanaei** [comment]
Please check your logs 
You can find it on first page

**Comment by Sharevex** [comment]
Here is my logs file :
![IMG_20231028_225427](https://github.com/MHSanaei/3x-ui/assets/60724506/6f404b06-fdf4-4abe-a828-a5a96c436df5)

This is the only problem, I tested in 100 lines mode as well.
How should I fix the problem?
Thanks for the help in advance

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/1138#issuecomment-1768685978
