### ISSUE TITLE
ارور پنل بعد از آپدیت به 1.7.9

### ISSUE THREAD

**Issue by AliHemmati79** [MHSanaei/3x-ui#1175]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام، بعد از آپدیت پنل به نسخه 1.7.9 با این ارور مواجه میشم:

Xray 1.8.4 (Xray, Penetrates Everything.) Custom (go1.21.0 linux/amd64)

A unified platform for anti-censorship.

2023/10/28 20:33:32 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: ext:iran.dat:ir > infra/conf: failed to load external sites: ir from iran.dat > infra/conf: failed to load file: iran.dat > infra/conf: failed to open file: iran.dat > open /usr/local/x-ui/bin/iran.dat: no such file or directory

مشکل چیه؟ ممنون میشم راهنمایی کنید.

### Version of 3x-ui

1.7.9

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
important : after v1.7.9 you need to click on "Reset to Default Configuration" and set your settings again

**Comment by AliHemmati79** [comment]
Thank you❤️😍
