### ISSUE TITLE
IP limit issue in version 1.7.9

### ISSUE THREAD

**Issue by Argo160** [MHSanaei/3x-ui#1177]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام وقت بخیر
اگه در پنجره ای که آی پی یوزر میافته اقدام به Clear The Log  کنید بعد از اون دیگه هیچی آی پی ای ثبت نمیشه و عملا کانفیگ ها نامحدود میشن.
باگ بزرگیه در این نسخه آخری که امیدوارم زودتر رفع بشه

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by ARES11430** [comment]
سلام این مطلب درسته و وقتی لاگ آی پی ها پاک میشه دیگه لاگ نمیندازه و عملا میتونن از چندین آی پی به کانفیگ وصل بشن

**Comment by MHSanaei** [comment]
لطفا logs رو چک کنید 
در داخل صفحه پنل هست

**Comment by MHSanaei** [comment]
و به احتمال خیلی زیاد مشکل شما هم مثل بقیه دوستان هست 
این مورد رو انجام بدید
https://github.com/MHSanaei/3x-ui/issues/1138#issuecomment-1768685978

**Comment by Argo160** [comment]
> و به احتمال خیلی زیاد مشکل شما هم مثل بقیه دوستان هست این مورد رو انجام بدید [#1138 (comment)](https://github.com/MHSanaei/3x-ui/issues/1138#issuecomment-1768685978)

ممنون جناب Sanaei 
ولی این بخش از کد وجود داره

![Capture](https://github.com/MHSanaei/3x-ui/assets/116899376/0542e938-ec0e-4ac2-9a0a-aed6ee5852b4)

**Comment by Argo160** [comment]
> لطفا logs رو چک کنید در داخل صفحه پنل هست

خدمت شما:
![Capture](https://github.com/MHSanaei/3x-ui/assets/116899376/6044c88c-1eb0-4958-a810-6423146df3b3)

**Comment by Argo160** [comment]
> لطفا logs رو چک کنید در داخل صفحه پنل هست

جناب سنایی اگه کمکتون میکنه باید بگم از بین ده تا کانفیگ موجود، فقط روی سه تاش ارور 404 میگیرم. و آی پی لیمیت روی اون سه تا کار نمیکنه. با اینکه تمام تنظیمات هر ده تا کانفیگ یکی هستن

**Comment by ARES11430** [comment]
![Capture](https://github.com/MHSanaei/3x-ui/assets/23665981/98d94468-084f-4bc5-b63f-d47a9bec561f)

**Comment by ARES11430** [comment]
> ![Capture](https://user-images.githubusercontent.com/23665981/279099634-98d94468-084f-4bc5-b63f-d47a9bec561f.PNG)

سلام جناب ثنایی منم همین مشکل رو دارم.

ببینید من clear ip رو که میزنم داخل پروفایل کاربر تمیز میشه. اما مشکل اینجاست با اینکه الان کاربر در حال استفاده از سرویس هست دیگه آی پی براش لاگ نمیشه. عملا میتونه به صورت نامحدود از سرویس استفاده کنه با آی پی هاش مختلف

**Comment by MHSanaei** [comment]
@ARES11430 لطفا لاگ رو بررسی کنید 
و مقدارش رو از 20 بیشتر کنید عکس بگیرید بفرستید

**Comment by ARES11430** [comment]
![Capture2](https://github.com/MHSanaei/3x-ui/assets/23665981/1f20bc51-05a7-4a5e-a29c-521e2f5358b2)

**Comment by ARES11430** [comment]
> ![Capture2](https://user-images.githubusercontent.com/23665981/279159453-1f20bc51-05a7-4a5e-a29c-521e2f5358b2.PNG)

در ضمن چک کردم و این دستورات داخل تمپلیت هم هست 
"log": {
"loglevel": "warning",
"access": "./access.log",
"error": "./error.log"
},

**Comment by MHSanaei** [comment]
@ARES11430 دوست عزیز همونطور که میبینید ارور access log دارید 
احتمالا این مورد رو درست قرار ندادید یا بعد از قرار دادن سیو و ریبوت نکردید

**Comment by alirezaimi** [comment]
for me in show this log 
![image](https://github.com/MHSanaei/3x-ui/assets/1029949/290b6640-c5d8-4a39-9243-a872d2640384)
and nothing happened . users still working !
i'm running v1.7.9 in container .

**Comment by ARES11430** [comment]
> سلام تونستید حل کنید مشکل رو؟

خیر من downgrade کردم

**Comment by hrasoul2** [comment]
با 

> > سلام تونستید حل کنید مشکل رو؟
> 
> خیر من downgrade کردم
با downgrade حل شد؟
به چه نسخه ای؟

**Comment by ARES11430** [comment]
> با
> 
> > > سلام تونستید حل کنید مشکل رو؟
> > 
> > 
> > خیر من downgrade کردم
> > با downgrade حل شد؟
> > به چه نسخه ای؟

بله 1.7.8 فقط بعد دانگرید هم باید ریست کنید تنظیمات پنل رو مجدد
