### ISSUE TITLE
WARNING - access.log doesn't exist in your config.json

### ISSUE THREAD

**Issue by mtad2002** [MHSanaei/3x-ui#1179]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

در بخش چک  استوس لاگ کامند x-ui این خطا هر 10 ثانیه تکرار میشه

Oct 30 18:40:04 a2s5-2 /usr/local/x-ui/x-ui[1558]: WARNING - access.log doesn't exist in your config.json
Oct 30 18:40:14 a2s5-2 /usr/local/x-ui/x-ui[1558]: WARNING - access.log doesn't exist in your config.json
Oct 30 18:40:24 a2s5-2 /usr/local/x-ui/x-ui[1558]: WARNING - access.log doesn't exist in your config.json
Oct 30 18:40:34 a2s5-2 /usr/local/x-ui/x-ui[1558]: WARNING - access.log doesn't exist in your config.json
Oct 30 18:40:44 a2s5-2 /usr/local/x-ui/x-ui[1558]: WARNING - access.log doesn't exist in your config.json
Oct 30 18:40:54 a2s5-2 /usr/local/x-ui/x-ui[1558]: WARNING - access.log doesn't exist in your config.json

### Version of 3x-ui

1.7.9

### x-ui log reports or xray log

<details>

Oct 30 18:40:04 a2s5-2 /usr/local/x-ui/x-ui[1558]: WARNING - access.log doesn't exist in your config.json
Oct 30 18:40:14 a2s5-2 /usr/local/x-ui/x-ui[1558]: WARNING - access.log doesn't exist in your config.json
Oct 30 18:40:24 a2s5-2 /usr/local/x-ui/x-ui[1558]: WARNING - access.log doesn't exist in your config.json
Oct 30 18:40:34 a2s5-2 /usr/local/x-ui/x-ui[1558]: WARNING - access.log doesn't exist in your config.json
Oct 30 18:40:44 a2s5-2 /usr/local/x-ui/x-ui[1558]: WARNING - access.log doesn't exist in your config.json
Oct 30 18:40:54 a2s5-2 /usr/local/x-ui/x-ui[1558]: WARNING - access.log doesn't exist in your config.json

</details>

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/1138#issuecomment-1768685978
