### ISSUE TITLE
High usage CPU

### ISSUE THREAD

**Issue by AliHemmati79** [MHSanaei/3x-ui#1180]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام
علت اشغال سیپیو توسط این بخش چی میتونه باشه؟ اکثر مواقع تا 100% هم میره و پنل زود به زود ریستارت میشه و افت سرعت داره
قبلا همچین مشکلی نبود بعدا با این مشکل مواجه شدم و کاربر زیادی هم داخل پنل ندارم.
ممنون میشم راهنمایی کنید
-
![x-ui](https://github.com/MHSanaei/3x-ui/assets/99415271/b25a6962-027e-4ce5-b665-cd16051cf204)

### Version of 3x-ui

<details>

```console
1.7.9
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
سلام لطفا logs رو در داخل صفحه اول پنل چک‌کنید

**Comment by AliHemmati79** [comment]
سلام بدین شکل بود
![x-ui2](https://github.com/MHSanaei/3x-ui/assets/99415271/4848ca49-ab88-4e78-ab3b-33c94f623688)
![x-ui 3](https://github.com/MHSanaei/3x-ui/assets/99415271/35ead8a0-f244-4c78-959c-f646334786d4)


[x-ui.log](https://github.com/MHSanaei/3x-ui/files/13213413/x-ui.log)

**Comment by MHSanaei** [comment]
خب علت اینه شما iplimit فعال دارید ولی fail2ban رو نصب نکردید
برید داخل سرور و از طریق منوی پنل نصب کنید

**Comment by AliHemmati79** [comment]
ممنون

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
