### ISSUE TITLE
غیر فعال شدن پنل بعد اپدیت از ۱.۷.۸ به ۱.۷.۹

### ISSUE THREAD

**Issue by ali4crypto** [MHSanaei/3x-ui#1181]
سلام
لطفا. راهنمایی کنید
پنل رو از ورژن ۱.۷.۸ به ۱.۷.۹ اپدیت کردم اما بعدش قسمت استاتوس 3x پنل اررور داد و پنل از کار افتاد
و مجبور شدم دوباره ۱.۷.۸ رو نصب کنم تا بکاپم قابل استفاده باشه.
![IMG_0756](https://github.com/MHSanaei/3x-ui/assets/148659563/17fa065e-5584-4d37-a3f6-3d6bbee49a84)
![IMG_0754](https://github.com/MHSanaei/3x-ui/assets/148659563/8b52c38f-e8f4-4490-9a80-ad599421c53f)

**Comment by Shellgate** [comment]
![Screenshot_۲۰۲۳-۱۰-۳۱-۰۶-۲۰-۰۶-۲۰۶_com android chrome-edit](https://github.com/MHSanaei/3x-ui/assets/128194280/4cfc2357-dfa8-4ca8-a151-5d2109fa1a8f)
 گزینه reset to default confirmation  رو زده و ذخیره کنید مشکل رفع میشه
