### ISSUE TITLE
xtls-rprx-vision-443 does not apply in the configuration

### ISSUE THREAD

**Issue by jameszeroX** [MHSanaei/3x-ui#1182]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

xtls-rprx-vision-443 does not apply in the configuration
![Screenshot_1](https://github.com/MHSanaei/3x-ui/assets/145020465/98af6381-dfc7-46f3-8c82-34430529a73b)
![Screenshot_2](https://github.com/MHSanaei/3x-ui/assets/145020465/b3247527-32c1-431e-ac18-6aea91af5d26)

### Version of 3x-ui

<details>
1.7.9
</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
yes because its for client side
