### ISSUE TITLE
Manual database update without restarting panel

### ISSUE THREAD

**Issue by ShayanMadMan** [MHSanaei/3x-ui#1183]
با سلام و ممنون بابت زحماتتون
بنده فایل x-ui.db رو به صورت دستی فولدر /etc/x-ui جایگزین میکنم اما دیتابیس جدید تا وقتی که پنل رو ریستارت نکنم اپدیت نمیشه و همون قبلی میمونه
خواهشا اگه میشه لطف کنید بگید بدون نیاز به ریستارت دستی پنل راه دیگه ای هست انجام بدم ممنون میشم

**Comment by MHSanaei** [comment]
از داخل خود پنل قسمت بک اپ و ریستور‌ میتونید انجام بدید اون قسمت خودکار پنل رو ریستارت میکنه
ولی در هر صورت پنل باید ریستارت بشه چه به صورت دستی چه خودکار

**Comment by ShayanMadMan** [comment]
> از داخل خود پنل قسمت بک اپ و ریستور‌ میتونید انجام بدید اون قسمت خودکار پنل رو ریستارت میکنه ولی در هر صورت پنل باید ریستارت بشه چه به صورت دستی چه خودکار

در صورتی که یوزر اضاف کنید پنل ریستارت نمیشه در این صورت به چه فایلی پنل دسترسی داره که دیتابیس اصلی نیست؟
و در این صورت اگه بخوایم هر ۵ دیقه اپدیت کنیم دیتابیس رو باید ریستارت کنیم و عملا کاربرا قطع میشن هر ۵ دیقه در صورتی که این اتفاق نمیوفته وقتی یوزر اضاف میکنید

**Comment by MHSanaei** [comment]
به صورت api خود xray هست که مهندس علیرضا زحمت کشیدن انجام دادن و نیازی به ریستارت کردن پنل برای اضافه یا حذف کردن یوزر نیست
و شما نباید فایل دیتابیس رو دستکاری کنید در سورت درستکاری نیاز به ریستارت هست
موفق باشید

**Comment by ShayanMadMan** [comment]
خوب بنده دارم با استفاده از Lsyncd تغییرات رو بین چند سرور مقایسه میکنم و فایل دیتابیس نهایی رو که درست حجم کم شده و تغییرات صورت گرفته شده بین سرور هارو اپدیت کرده جایگزین میکنم بجای تمام دیتابیس ها و تا اینجا اوکی هست فقط پنل باید ریستارت بشه که مشکل ایجاد کرده ولی درباره api خود xray اطلاعی ندارم نظر خودتون که این مشکل رفع بشه چی هست؟
میشه تغییرات صورت گرفته رو دونه دونه از طریق api ثبت کرد؟ و اگه کمک کنید یا توضیح بدید ممنون میشم
