### ISSUE TITLE
مشکل آپلود و اختلال در واتساپ با reality

### ISSUE THREAD

**Issue by SAEEDZZZ** [MHSanaei/3x-ui#1192]
سلام وقت بخیر دوستان مشکلی با پرتکل ریلیتی حین اپلود توی واتساپ یا اختلال تو واتساپ داخل دستگاه های آیفون دارید؟ کاربرا زیاد بهم گذارش میکنن خواستم ببسنم کسی سورسی چیزی در اختیار داره راجب این داستان یا اگر اطلاعاتی دارین در میان بزارین مرسی

**Comment by ghajar77** [comment]
من هم همین مشکل رو دارم.
فکر کنم ار http باشه.

**Comment by behnamgolds** [comment]
جایی گذرا خوندم ظاهرا آپدیت جدید آیفون مشکل ایجاد کرده برای یک سری پروکسی/وی پی ان ها ، چون آیفون ندارم ادامه شو نخوندم. آیفون از این دست مشکلات قبلا هم داشته ولی عوضش باکلاسه.

**Comment by ghajar77** [comment]
رو آیفون با برنامه v2box مشکل حل شد
