### ISSUE TITLE
سوال در مورد sniffing

### ISSUE THREAD

**Issue by shehnipoor** [MHSanaei/3x-ui#1193]
سلام
گزینه sniffing توی ساخت اینباند کسی میدونه چیکار می‌کنه؟ و اصلا این گزینه برای چی هست؟

**Comment by wulfric93** [comment]
sniffing یک قابلیت کاربردی x-ui میباشد که می تواند ترافیک ها را بر اساس protocol ها  تفکیک کند و امکان outbound مشخص برای هر کدام را داشته باشید.
