### ISSUE TITLE
io: read/write on closed pipe

### ISSUE THREAD

**Issue by radinVFX** [MHSanaei/3x-ui#1199]
سلام و خسته نباشید
من وقتی vmess + tcp + tls رو روشن میکنم
با ارور [io: read/write on closed pipe] مواجه میشم
ممنون میشم راهنمایی کنید 🙂

**Comment by misagh72** [comment]
ای پی فیلتره

**Comment by radinVFX** [comment]
ای پی رو چک کردم فیلتر نبود
حتی 2 3 تا ای پی دیگه رو هم چک کردم اما نشد

**Comment by alirahimi818** [comment]
> سلام و خسته نباشید من وقتی vmess + tcp + tls رو روشن میکنم با ارور [io: read/write on closed pipe] مواجه میشم ممنون میشم راهنمایی کنید 🙂

مقدار Flow رو هیچ یا null بزار (وقتی کلاینت رو ویرایش کنی این مقدار رو میبینی)
بعدش اگه کانفیگ رو به کاربر دادی بگو حذفش کنه و دوباره بهش کانفیگ کلاینت رو بده یا اینکه اگه ساب اسکریپشن دادی بگو که آپدیت کنه

**Comment by mechix** [comment]
داداش برای من جواب نداد
بطور طبیعی مقداری بهش داده نشده بود

**Comment by tatality-lgtm** [comment]
> سلام و خسته نباشید من وقتی vmess + tcp + tls رو روشن میکنم با ارور [io: read/write on close pipe] آسیب میشم ممنون میشم راهنمایی کنید 🙂

منم به همین صورت است اما با پروتوکل VLESS است کسی میدونه که مشکل از کجاست!؟؟
