### ISSUE TITLE
مشکل در addclient  و updateclient  در استفاده از Api

### ISSUE THREAD

**Issue by AliNajafzadeh7916** [MHSanaei/3x-ui#1214]
سلام
وقتتون بخیر
api در قسمت addclient , updateclient مشکل داره 
وقتی که درخواست بهش میزنم،و یه مقداری رو بهش میدم که به عنوان حجم براش در نظر بگیره، رنگش رو آبی میکنه که به این معنیه که نامحدوده، و خودمم چکش کردم، نامحدود در نظر میگیره و وقتی از اون مقدار رد میشه اصلا قطش نمیکنه، عدد رو اعمال میکنه و مشخص میشه، ولی در زمان چک کردنش، حسابش نمیکنه
فکر میکنم توی آپدیت جدید اینطوری شده...

![Screenshot 2023-11-11 001730](https://github.com/MHSanaei/3x-ui/assets/84715953/f5ad6a72-ac4f-4c72-b6fb-750464603c4e)

**Comment by Arman-nsb** [comment]
سلام، من از اکثر endpoint ها روی لاراول استفاده کردم، بدون مشکل کار میکنن. شما احتمال زیاد یه جای کار رو اشتباه رفته باشید.
