### ISSUE TITLE
Change the xray core to the sing-box?

### ISSUE THREAD

**Issue by GFW4Fun** [MHSanaei/3x-ui#1216]
Hi
Is it possible to change the xray core to the sing-box?

Thanks

**Comment by wulfric93** [comment]
Use this
https://github.com/sing-web/x-ui

**Comment by wulfric93** [comment]
sing-box and Xray are two completely different projects and they cannot be used interchangeably. While there may be some similarities in their functionality, they have distinctive design architectures, features, and functionality that make them distinct from each other. As such, you cannot use x-ui or any other Xray derivative products. I hope this clarifies your questions. Please let us know if you have any further inquiries.
