### ISSUE TITLE
امکان دانلود ایمیج کانتینر

### ISSUE THREAD

**Issue by aliamg1356** [MHSanaei/3x-ui#1217]
برای نصب کانتینر در میکروتیک به فایل ایمیج با پسوند tar هست  ایمج هم با داکر میشه دانلود کرد  کیتونین این فایلهای امیج رو اینجا بذارین تا بتونبم دانلود کنیم؟

**Comment by AliBelali** [comment]
توی میکروتیک قسمت تنظیمات کانتینر آدرس 
registry url
رو روی
https://ghcr.io
بذارید بعد موقع اضافه کردن کانتینر پارامتر
remote-image=mhsanaei/3x-ui:latest
تنظیم کنید دیگه خودش اتومات دانلود میکنه
یا اگه حتما میخواید آفلاین نصب کنید روی یه سیستم لینوکسی میتونید بعد از نصب نرم افزار داکر
با دستور
docker pull ghcr.io/mhsanaei/3x-ui:latest
آخرین نسخه 3x-ui رو دانلود کنید و بعد با دستور
docker save ghcr.io/mhsanaei/3x-ui > 3x-ui.tar
فایل آفلاینش رو تولید کنید
دستورات رو روی گوشی نوشتم ممکنه نگارشش نیاز به تصحیح داشته باشه یا چیزی رو جا انداخته باشم
