### ISSUE TITLE
سوال 

### ISSUE THREAD

**Issue by Gggbbhhhhhhhhh** [MHSanaei/3x-ui#1218]
سلام من اگر بخوام برای خرید پنل باهاتون صحبت کنم چجوری هست چون از گیت هاب سر در نمیارم

**Comment by wulfric93** [comment]
دوست عزیز اینجا کسی پنل نمیفروشه

**Comment by m38d1** [comment]
با سلام میتونید با ایمیل me@mehdiaskari.ir در ارتباط باشید براتون انجام بدم

**Comment by m38d1** [comment]
> سلام من اگر بخوام برای خرید پنل باهاتون صحبت کنم چجوری هست چون از گیت هاب سر در نمیارم

**Comment by m38d1** [comment]
> دوست عزیز اینجا کسی پنل نمیفروشه

با سلام میتونید با ایمیل [me@mehdiaskari.ir](mailto:me@mehdiaskari.ir) در ارتباط باشید براتون انجام بدم

**Comment by aliamg1356** [comment]
> [me@mehdiask](mailto:me@mehdiaskari.ir)

salam agar maiel budin befarmaiin email bedam ta dar khedmat basham baraye rafe moshkeletun
