### ISSUE TITLE
Direct Country Settings  کار نمیکنه

### ISSUE THREAD

**Issue by elegance666** [MHSanaei/3x-ui#1219]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

تنطیمات Direct Country Settings برای هیچ کشوری از جمله ایران کار نمیکنه، خیلی از IP ها به همین دلیل دارند فیلتر میشند.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by wulfric93** [comment]
پنل شما روی سرور ایران هست یا سرور خارج ؟

**Comment by elegance666** [comment]
سرور خارج

> پنل شما روی سرور ایران هست یا سرور خارج ؟

سرور خارجی

**Comment by wulfric93** [comment]
> > پنل شما روی سرور ایران هست یا سرور خارج ؟
> 
> سرور خارجی

روش تانل شما چیه ؟

**Comment by elegance666** [comment]
> > > پنل شما روی سرور ایران هست یا سرور خارج ؟
> > 
> > 
> > سرور خارجی
> 
> روش تانل شما چیه ؟

grpc بدون تانل

**Comment by wulfric93** [comment]
با TCP من کار کردم و تونل بوده
بدون تانل  رو ااطلاعی ندارم 
ولی اگر تانل باشی نمیشه که کار کنه

**Comment by elegance666** [comment]
تانل نیستم و کار نمیکنه

**Comment by elegance666** [comment]
چک کردم حتی Block Country Configs هم کار نمیکنه

**Comment by uzer0098** [comment]
این گزینه برای موقعی هست که شما تانل کردید و کاربرد دیگه ای نداره
