### ISSUE TITLE
مدیریت در موبایل

### ISSUE THREAD

**Issue by ghojaei1995** [MHSanaei/3x-ui#1228]
سلام 
 این پنل مثل پنل علیرضا مدیریت در موبایل بهش اضافه نمیشه؟!

**Comment by alireza0** [comment]
درود بر شما
بله اضافه میشه

**Comment by aliamg1356** [comment]
> سلام این پنل مثل پنل علیرضا مدیریت در موبایل بهش اضافه نمیشه؟!
مدیریت در موبایل چیه؟
