### ISSUE TITLE
مشکل ورژن 1.7.9

### ISSUE THREAD

**Issue by Cyrus-of-Persia** [MHSanaei/3x-ui#1233]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

با بروز رسانی از ورژن 1.7.8 به 1.7.9 پنل دیگه ران نمیشه و سرویسش متوقف میشه
![Untitled](https://github.com/MHSanaei/3x-ui/assets/67868888/5f579b35-1c21-4ae3-ae95-34e694bedc9e)

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Arman-nsb** [comment]
> important : after this update you need to click on "Reset to Default Configuration" and set your settings again

سلام، این مورد رو انجام دادید؟

**Comment by Cyrus-of-Persia** [comment]
خطای پنل بعد آپدیت این بود که محل فایل مربوط به دامنه های مستقیم رو پیدا نمی کنه.
![Screenshot 2023-11-16 180128](https://github.com/MHSanaei/3x-ui/assets/67868888/c02e105b-c2df-4ce0-8e57-2db830ae4bdb)

بعد از  "Reset to Default Configuration" مشکل حل شد. ولی اگر باز هم بخوام تو اون قسمت دامنه های مستقیم تنظیم کنم، باز هم همین خطا رو میده

**Comment by Arman-nsb** [comment]
روی سرور دستور x-ui و بعد گزینه update geo files رو امتحان کنید. ( سوالی که میپرسه رو Enter بزنید )
