### ISSUE TITLE
Free disk space is constantly decreasing.

### ISSUE THREAD

**Issue by AFord7373** [MHSanaei/3x-ui#1234]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi. I have a problem. I use 3X-UI. 3X: v1.7.8, Xray: v1.8.4
Debian 5.10.197-1 (2023-09-29) x86_64

I am a complete beginner in Linux and have encountered it for the first time. Please be understanding.

Also, the entire text was translated using a Google Translator.

**PROBLEM - Every day the free space on my VPS decreases.**

I have already written about this in one of my posts, but the advice did not help me (https://github.com/MHSanaei/3x-ui/issues/1123).

For example, on 14.10.23, 9.6% of the disk was occupied on my VPS, 11.11.23 – 15.1%, and 16.11.23 is already 16%.

I completely reinstalled the operating system on my VPS and 3X-UI 1 month ago after i had 99.9% disk.

![chrome_9lQadZ6fCj](https://github.com/MHSanaei/3x-ui/assets/147619340/0304a394-2f31-4502-93ba-c73b34627c5e)

**Here is my 3X-UI installation procedure (maybe I made a mistake in something) :**

apt install sudo

for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do sudo apt-get remove $pkg; done

sudo apt-get update
sudo apt-get install ca-certificates curl gnupg 
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg

echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
 
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

apt-get install git

git clone https://github.com/MHSanaei/3x-ui.git
cd 3x-ui
git checkout v1.7.8

docker compose up -d

Then I already connected to my server via the browser at http://MYSERVERIP:2053/panel / and from that moment the installation is over.

**Tips that I was given in my last post:**
_1. “ Just Remove access.log file at /usr/local/x-ui/access.log ”_
A; I can't do this because I don't have an x-ui (3x-ui) folder in the /usr/local/ folder
I only have a 3x-ui folder under the path /root/3x-ui, BUT there is no such file as access.log in it
(I am using Bitvise SSH Client in New SFTP window mode).
![BvSsh_TQvbcwp3Vn](https://github.com/MHSanaei/3x-ui/assets/147619340/8c581401-9f45-4afa-8368-e4964e72d8b0)
![BvSsh_RXhSvijDZR](https://github.com/MHSanaei/3x-ui/assets/147619340/19367b3d-7804-4c34-bdb7-aa59d8cf7048)
I also tried using the console, but it didn't give results (maybe I entered the command incorrectly)
![totermw_umSw45NYdX](https://github.com/MHSanaei/3x-ui/assets/147619340/e2f5165b-d382-4a55-99f0-6ef0287baa05)

_2. “ delete this section from your x-ui template :
"log": {
"access": "./access.log",
"error": "./error.log",
"loglevel": "warning"
}, ”_
I did it (after I tried to use the first tip). But it also doesn't help.
![chrome_fUuOxyu1nX](https://github.com/MHSanaei/3x-ui/assets/147619340/a8d5d9ac-3874-40a7-9ec4-b27ac65860b3)
![ApplicationFrameHost_RUnii8t13Q](https://github.com/MHSanaei/3x-ui/assets/147619340/b5d60828-17fa-471e-87ab-92f49fbf4bed)
![notepad++_YU2vEEJ3mU](https://github.com/MHSanaei/3x-ui/assets/147619340/737d0d6a-76fa-47af-8853-ce883fbfea7c)
![notepad++_kkiQuio5N4](https://github.com/MHSanaei/3x-ui/assets/147619340/a4da2160-892a-4bfb-b669-b9858c7b6685)
Please tell me how to free up disk space. Because sooner or later it will end completely.
I am also ready to provide other necessary data. The main thing is to explain what I need to do to find them

### Version of 3x-ui

<details>

```console
# 1.7.8
```

</details>

### x-ui log reports or xray log

No problems in log

**Comment by GreyFlorence** [comment]
Same problem here

**Comment by AFord7373** [comment]
> Same problem here

Try this -  sudo journalctl --vacuum-files=2
Most likely this will clear most of your disk

U can use this command to check all files size (from heaviest to lightest)
du -h / | sort -hr

How i saw my catalog was filling up soo we go to - nano /etc/systemd/journald.conf
And in the SystemMaxUse set to SystemMaxUse=400MB
