### ISSUE TITLE
محاسبه اشتباه ترافیک -جناب سنایی لطفا بخونید ممنونم

### ISSUE THREAD

**Issue by mohsens00067** [MHSanaei/3x-ui#1238]
سلام
من خیلی گشتم و سرچ کردم مخصوصا سوالات قبلی کاربران رو
من اومدم یدونه از پنل هام رو به یه سرور ایران تانل زدم
جالب اینجاست که وقتی پنل ایران زده مثلا 120 گیگ پنل خارج زده 50 گیگ
یعنی میخوام بگم داره کمتر محاسبه میکنه پنل ایکس یو آی
یه دونه vmess ساده و vless ساده ساختم
عکس هم میزارم ببینید
اولش فک کردم سایتی که سرور ایران میده دزده سرور گرفتم باهاش یه فایل 1 گیگی دانلود کردم و همون مقدار را دقیق زد

الان این مقدار مصرفی سرور خارج هست توی پنل ایک یو آی 
جمع کل: 554.66 GB
و اینم مقدار محاسبه سرور ایران :
1.17 TB

جناب سنایی لطفا کمک کنید این هزینه مازادی که داره اینجا درست میشه کمرمو شکسته
روی سرور فقط یک پنل نصبه 
![kharej](https://github.com/MHSanaei/3x-ui/assets/68667680/d7bc6bf3-1007-443c-8f58-2914670c9894)

![iran](https://github.com/MHSanaei/3x-ui/assets/68667680/30e2fc4c-e39f-46da-bcc9-b5e5998e8bf4)

**Comment by aliamg1356** [comment]
> سلام من خیلی گشتم و سرچ کردم مخصوصا سوالات قبلی کاربران رو من اومدم یدونه از پنل هام رو به یه سرور ایران تانل زدم جالب اینجاست که وقتی پنل ایران زده مثلا 120 گیگ پنل خارج زده 50 گیگ یعنی میخوام بگم داره کمتر محاسبه میکنه پنل ایکس یو آی یه دونه vmess ساده و vless ساده ساختم عکس هم میزارم ببینید اولش فک کردم سایتی که سرور ایران میده دزده سرور گرفتم باهاش یه فایل 1 گیگی دانلود کردم و همون مقدار را دقیق زد
> 
> الان این مقدار مصرفی سرور خارج هست توی پنل ایک یو آی جمع کل: 554.66 GB و اینم مقدار محاسبه سرور ایران : 1.17 TB
> 
> جناب سنایی لطفا کمک کنید این هزینه مازادی که داره اینجا درست میشه کمرمو شکسته روی سرور فقط یک پنل نصبه ![kharej](https://user-images.githubusercontent.com/68667680/283965250-d7bc6bf3-1007-443c-8f58-2914670c9894.JPG)
> 
> ![iran](https://user-images.githubusercontent.com/68667680/283965263-30e2fc4c-e39f-46da-bcc9-b5e5998e8bf4.JPG)

ماجرا بسیار واضحه
سرور ایران شما داره مجموع دانلود و آپلود رو محاسبه میکنه  در سرور خارج شما حدودا 40 گیگ دانلود و 500 گیگ آپلود  حالا این مقدار در سرور ایران شما هم دانلود و هم آپلود شده یعنی حجم دوبرابر سرور خارج شما استفاده گردیده است  یعنی حدودا 1108گیگیا 1.108ترا.اون تفاوت اندک هم در آپدیت و مصارف و دیگر مصارف پهنای باند سرور مصرف شده   شما باید از سروری استفاده کنید در ایران که مصرف دانلود رو محاسبه میکنه و آپلود رایگانه.
شما اگر با این سرور ایران فایل یک گیگی را دانلود کنید 2 گیگ مصرف حجم برای شما حساب میگردد

**Comment by mohsens00067** [comment]
> > سلام من خیلی گشتم و سرچ کردم مخصوصا سوالات قبلی کاربران رو من اومدم یدونه از پنل هام رو به یه سرور ایران تانل زدم جالب اینجاست که وقتی پنل ایران زده مثلا 120 گیگ پنل خارج زده 50 گیگ یعنی میخوام بگم داره کمتر محاسبه میکنه پنل ایکس یو آی یه دونه vmess ساده و vless ساده ساختم عکس هم میزارم ببینید اولش فک کردم سایتی که سرور ایران میده دزده سرور گرفتم باهاش یه فایل 1 گیگی دانلود کردم و همون مقدار را دقیق زد
> > الان این مقدار مصرفی سرور خارج هست توی پنل ایک یو آی جمع کل: 554.66 GB و اینم مقدار محاسبه سرور ایران : 1.17 TB
> > جناب سنایی لطفا کمک کنید این هزینه مازادی که داره اینجا درست میشه کمرمو شکسته روی سرور فقط یک پنل نصبه ![kharej](https://user-images.githubusercontent.com/68667680/283965250-d7bc6bf3-1007-443c-8f58-2914670c9894.JPG)
> > ![iran](https://user-images.githubusercontent.com/68667680/283965263-30e2fc4c-e39f-46da-bcc9-b5e5998e8bf4.JPG)
> 
> ماجرا بسیار واضحه سرور ایران شما داره مجموع دانلود و آپلود رو محاسبه میکنه در سرور خارج شما حدودا 40 گیگ دانلود و 500 گیگ آپلود حالا این مقدار در سرور ایران شما هم دانلود و هم آپلود شده یعنی حجم دوبرابر سرور خارج شما استفاده گردیده است یعنی حدودا 1108گیگیا 1.108ترا.اون تفاوت اندک هم در آپدیت و مصارف و دیگر مصارف پهنای باند سرور مصرف شده شما باید از سروری استفاده کنید در ایران که مصرف دانلود رو محاسبه میکنه و آپلود رایگانه. شما اگر با این سرور ایران فایل یک گیگی را دانلود کنید 2 گیگ مصرف حجم برای شما حساب میگردد

---------------------------------
دوست عزیز حجم کل رو من زدم توی عکس هم معلومه آپلود و دانلود سمت چپ و سمت راست کل حجم مشخص شده که 554 گیگ هست

**Comment by aliamg1356** [comment]
> > > سلام من خیلی گشتم و سرچ کردم مخصوصا سوالات قبلی کاربران رو من اومدم یدونه از پنل هام رو به یه سرور ایران تانل زدم جالب اینجاست که وقتی پنل ایران زده مثلا 120 گیگ پنل خارج زده 50 گیگ یعنی میخوام بگم داره کمتر محاسبه میکنه پنل ایکس یو آی یه دونه vmess ساده و vless ساده ساختم عکس هم میزارم ببینید اولش فک کردم سایتی که سرور ایران میده دزده سرور گرفتم باهاش یه فایل 1 گیگی دانلود کردم و همون مقدار را دقیق زد
> > > الان این مقدار مصرفی سرور خارج هست توی پنل ایک یو آی جمع کل: 554.66 GB و اینم مقدار محاسبه سرور ایران : 1.17 TB
> > > جناب سنایی لطفا کمک کنید این هزینه مازادی که داره اینجا درست میشه کمرمو شکسته روی سرور فقط یک پنل نصبه ![kharej](https://user-images.githubusercontent.com/68667680/283965250-d7bc6bf3-1007-443c-8f58-2914670c9894.JPG)
> > > ![iran](https://user-images.githubusercontent.com/68667680/283965263-30e2fc4c-e39f-46da-bcc9-b5e5998e8bf4.JPG)
> > 
> > 
> > ماجرا بسیار واضحه سرور ایران شما داره مجموع دانلود و آپلود رو محاسبه میکنه در سرور خارج شما حدودا 40 گیگ دانلود و 500 گیگ آپلود حالا این مقدار در سرور ایران شما هم دانلود و هم آپلود شده یعنی حجم دوبرابر سرور خارج شما استفاده گردیده است یعنی حدودا 1108گیگیا 1.108ترا.اون تفاوت اندک هم در آپدیت و مصارف و دیگر مصارف پهنای باند سرور مصرف شده شما باید از سروری استفاده کنید در ایران که مصرف دانلود رو محاسبه میکنه و آپلود رایگانه. شما اگر با این سرور ایران فایل یک گیگی را دانلود کنید 2 گیگ مصرف حجم برای شما حساب میگردد
> 
> دوست عزیز حجم کل رو من زدم توی عکس هم معلومه آپلود و دانلود سمت چپ و سمت راست کل حجم مشخص شده که 554 گیگ هست

این حجم تو سرور خارجه درسته؟
من چک کردم تو تانل پنل به پنل این اختلاف بسیار کمه. مثلا برای ۲۵ مگ در حد ۵ مگ. اللته سرور ایران کم زده بود.
بالا هم عرض کردم اگه حجم  بالا سرور خارج باشه پس دو برابر اون در سرور ایران مصرف میشه اگر دیتا سنتر شما مجموع آپلود و دانلود رو برای شما محاسبه کرده باشه. چون هر گیگ ورودی یا خرجی از سمت کاربر در سرور هم وارد هم خارج میشه. یعنی هر گیگ دانلود برابر است با ۱ گیگ ورودی از سمت سرور خارج و یک گیگ خرجی به سمت کاربر. مجموعا میشه دو گیگ
