### ISSUE TITLE
باگ قطع نشدن یوزرها حتی در صورت غیرفعال کردن

### ISSUE THREAD

**Issue by uzer98** [MHSanaei/3x-ui#1251]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

متاسفانه در پنل ثنایی و علیرضا اگه دستی یوزرها را غیرفعال کنید همچنان متصل باقی میمونن
حتی تو اخرین ورژن هر دو پنل این مشکل وجود داره

### Version of 3x-ui

<details>

```
اخرین ورژن
```

</details>

### x-ui log reports or xray log

<details>

```
ندارم
```

</details>

**Comment by PesareIran250** [comment]
متاسفانه دوستمون درست میگن و برای منم همینجوره
هیچ اعتباری به خاموش کردن دکمه کشویی نیست 
یوزر داشتم 1 ماه پیش خاموشش کردم اما همچنان داشته استفاده میکرده

**Comment by alireza0** [comment]
دوستان  با این روش گزارش دادن نمیشه کاری کرد. لطفا نوع تنظیم و لاگ رو حتما بفرستین.
توی تست های ما همه چیز درست جواب میده.
برای پیدا کردن باگ اطلاعات دقیق لازمه.
ممکنه یه پروتکل و یا توی یه حالت خاص مشکل باشه و گزارش دهنده باید حالت خاص رو پیدا کنه

**Comment by ali-hosini** [comment]
سلام علیرضا جان خسته نباشید
من از تانل outbound استفاده میکنم و کانفیگ xray هم دیفالت خود سرور و فقط Configure Domains Routing Strategy روی asis هست چون روی گزینه دیفالت اکثر سایت ها باز نمیشه 
و این مشکل رو به صورت های مختلفی دارم 
پورت تغییر بدم قبلی متصله
حجم کانفیگ تموم بشه متصله 
خودم غیرفعال کنم بازم متصله 
تنها راه فیکس کردنش هم ریست پنل هست اگر هم نشه ریست خود سرور 
روی نسخه 1.8.1 xray هستم و از پنل 3x-ui ورژن 1.7.8 استفاده میکنم 
روی نسخه های xray تست کردم همشون به همین صورت هستند
