### ISSUE TITLE
Problem with adding configuration to Apps like Oneclick vpn

### ISSUE THREAD

**Issue by stingy64** [MHSanaei/3x-ui#1255]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

1. I am using the last version of 3x-ui and can't add configuration to apps like **oneclick vpn**, **fairvpn** and etc. It gives `alterID not found` error in oneclick vpn.
2. I can import connection to **v2rayng**, but it doesn't work.
3. The only app I can use to import configuration correctly and seems to work is **Sagernet**.

PS: The error goes away, if i import those connection to an app like **nekoray** and then export for use in the other apps.

### Version of 3x-ui

<details>

```console
1.7.9
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by miladyv** [comment]
Onclick only support VMESS protocol, use v2rayng for android and v2box for iphone ...
