### ISSUE TITLE
دریافت کانفیگ از طریق API

### ISSUE THREAD

**Issue by hr1510** [MHSanaei/3x-ui#1256]
درود خدمت همگی؛
میخواستم بدونم چطور میتونم برای کلایت که قبلا ایجاد شده و تحویل شده ، مجددا qr نمایش داده بشه ؟
مثلا یک فرمی داریم که پس از وارد کردن Email ، اطلاعات کلاینت مورد نظر به همراه QR نمایش داده بشود.
اطلاعات رو که میتونیم با getClientTraffics دریافت کنیم لینک کانفیگ رو نمیدونم چطور دریافت کنم
https://gist.github.com/mehdikhody/9a862801a2e41f6b5fb6bbc7e1326044
متاسفانه توی کالکشن Postman هم چیزی پیدا نکردم
ممنون میشم راهنمایی بفرمایید.

**Comment by pnext2023** [comment]
من هم نیاز به این قابلیت دارم.

زمانی که با API یک کلاینت ایجاد میشه، چطور میتونیم URL کانفیگ رو از سرور دریافت کنیم؟
ظاهر الان باید به صورت دستی تنظیمات اینباند و کلاینت رو بخونیم و لینک رو خودمون ایجاد کنیم.
متاسفانه مستندی هم وجود نداره و باید با حدس و خطا این لینک رو ایجاد کرد.

**Comment by uzer0098** [comment]
فایل روبات ویزویز رو ببین
متوجه میشی

**Comment by hr1510** [comment]
> فایل روبات ویزویز رو ببین متوجه میشی
کاش شما همینجا بیشتر اشاره میکردید

**Comment by pnext2023** [comment]
بله من هم نتونستم پیداش کنم.
امکانش هست لینک اون فایل مربوطه رو بزارید لطفا؟

**Comment by uzer98** [comment]
من اگه سر در میاوردم برات میزاشتم
شما فایل های ربات ویزویز که تو گیت هاب هست بررسی کن
چون این کاری که شما میخوای تو ربات ویزویز انجام میشه
