### ISSUE TITLE
سلام اگر بشه در اپدیت جدید  سه اپشن مثل نود مرزبان به پنل اضافه بشه که بشه multi location کانفینگ زد عالی میشه 

### ISSUE THREAD

**Issue by MAsterhadi** [MHSanaei/3x-ui#1259]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MAsterhadi** [comment]
مثلا یک کانفینگ بدی و بعد با یک لینک ساب یا روی یک پروتوکل  دو تا سه تا لوکیشن  ( مثلا آلمان فنلاند و ترکیه ) استفاده کنه یه چیزی شبیه به نود مرزبان

**Comment by Amin-Najii** [comment]
کاملا موافقم .

**Comment by zifulx** [comment]
دوستان این اآپشن رو ما شخصی سازی و اضافه کردیم

**Comment by MAsterhadi** [comment]
سلام چطوری

**Comment by Amin-Najii** [comment]
> سلام چطوری
سلام ممنونم ولی اینجا جای گفتگو نیست .
