### ISSUE TITLE
تک کاربره کردن در حالت تانل

### ISSUE THREAD

**Issue by amirvp** [MHSanaei/3x-ui#1263]
سلام در حالت تانل از سرور ایران، برای تک کاربره کردن و اعمال محدودیت ip، دوستان پیشنهاد اتصال دو پنل از طریق اتصال outbound سرور ایران به inbound سرور خارج رو دادند. میشه لطفا توضیح بدید این outbound چجوری ساخته بشه و یه نمونه قرار بدین و اینکه در قسمت routing باید چکار کرد؟ 
خیلی ممنون مرسی از لطفتون

**Comment by MAsterhadi** [comment]
اینو تو تلگرامشون فیلم گذاشتن برو داخل گروه

**Comment by amirvp** [comment]
> اینو تو تلگرامشون فیلم گذاشتن برو داخل گروه

گروه تلگرامشون کجاست آدرسش؟؟ ممنون داداش

**Comment by amirvp** [comment]
چجوری عضو گروه بشم؟؟

**Comment by MAsterhadi** [comment]
توی پنل x-ui که داری  دقیقا جلو هسته x-ray زده ثنایی  بزن میایی تو گروهش
