### ISSUE TITLE
error in installing warp

### ISSUE THREAD

**Issue by niiaco** [MHSanaei/3x-ui#1280]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

during installing i have this  error : 
  [ERROR] Sorry, the reinstallation of WARP socks5 proxy (WireProxy) failed! Please try again later.    

please help  ,i tested last update , tested diffrent vps locations

### Version of 3x-ui

--

### x-ui log reports or xray log

--

**Comment by miladyv** [comment]
Use following link for instalation:

https://github.com/yonggekkk/warp-yg

**Comment by niiaco** [comment]
hi its not possible to change warp ip . all the users will ahve same ip
with this warp script

**Comment by pivotdude** [comment]
I am download original script from https://raw.githubusercontent.com/hamid-gh98/x-ui-scripts/main/install_warp_proxy.sh to file sh file. And rewrited function:
```
function step_install_warp() {
  local error_output
  error_output=$(warp w <<< $'1\n1\n'"${WP_INSTALL_PORT}"$'\n1\n' 2>&1)
  if [[ $? -ne 0 ]]; then
    STEP_STATUS=0
    echo -e "${red}${T[007]} ${T[078]}${plain}"
    echo -e "${red}${error_output}${plain}"
  else
    STEP_STATUS=1
  fi
}
```
And it`s work for me.

**Comment by MHSanaei** [comment]
Guys, you don't need to install any script for warp in the latest versions.
