### ISSUE TITLE
Failed to detect internet connection: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by unibus31** [MHSanaei/3x-ui#1283]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

While connecting with the v2rayNG in case of using 443 port i get the following error:
Failed to detect internet connection: net/http: TLS handshake timeout

Certificate is installed. Please advise what it could be?

### Version of 3x-ui

1.7.9

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by kalilovers** [comment]
hi check installation of warp and also set and check dns in server
