### ISSUE TITLE
مشکل اینستاگرام

### ISSUE THREAD

**Issue by keyvansh** [MHSanaei/3x-ui#1284]
با سلام . پنل با همه برنامه ها عالیه ولی تو اینستاگرام هی لگ میزنه . کسی به این مشکل خورده ؟

**Comment by miladyv** [comment]
Age pinge servereton ziad bashe in moshkel pish miyad, zire 1000ms bashe moshkeli nakhahad dasht, fagat momken follower ha va followingaro neshon nade ke bara hale in moshkel az protocol vmess estefade konid, ya inke instagram ro ham az WARP obor bedid ....

**Comment by kalilovers** [comment]
سلام اینجارو چک کنید 
https://github.com/MHSanaei/3x-ui/discussions/1298
توضیح دادم
