### ISSUE TITLE
مصرف بالای cpu

### ISSUE THREAD

**Issue by m484r** [MHSanaei/3x-ui#1288]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام وقت بخیر
چطوری این مصرف بالای cpu رو از بین ببرم؟
من 5 تا سرور دارم ولی فقط این یکی اینطوری شده
از طرفی رو همه کانفیگ ها ip limit گذاشته بودم که سعی کردم همشو حذف کنم و fail2ban رو هم فعال کردم
کلا تمام تاپیک ها رو خوندم و انجام دادم ولی مشکل حل نشد
حتی سرور رو هم ارتقا دادم به 16 هسته ای ولی بازم بالای 70 درصد cpu در گیر میشه و xray ری استارت میشه و کندی سرعت و قطعی پیش میاد
![1](https://github.com/MHSanaei/3x-ui/assets/123161750/882ffdb4-5540-480b-abdc-6f5ac556ef04)

### Version of 3x-ui

<details>

```console
# 1.7.9
```

</details>

### x-ui log reports or xray log

<details>

```console
# xray
```

</details>

**Comment by mohammad82mr** [comment]
اگه از cdn کلادفلر استفاده میکنی ایپیتو چنج بزن درست میشه

**Comment by m484r** [comment]
نه تانل هستش
سرور هم عوض کردم خوب نشده

**Comment by mehdikhody** [comment]
من بعد از چند روز متوجه شدم. اگر لاگ access را فعال کردی دوباره غیرفعال کن.
پنل به صورت نامحدود به فایل access.log لاگ اضافه میکنه و بعد از یکی دو روز سایز فایل به شدت زیاد میشه.

از طرفی یه باگ هست مثل اینکه پنل سعی میکنه کل فایل را ابتدا لود کنه که کل فضای ram و قدرت پردازنده رو میگیره.

```json
  "log": {
    "loglevel": "warning",
    "error": "./error.log",
    "access": "none"
  },
```

یا access را کلا نگذار یا اینطوری بذار که کلا نادیده گرفته بشه.

**Comment by MHSanaei** [comment]
اگر ای پی لیمیت فعال باشه و شما access log و fail2ban نصب نداشته باشید cpu بالا میره
داخل logsهم میتونید  warning هارو ببینید
راه حل هم اینه یا موارد لازم رو نصب و اضافه کنید یا ای پی لیمیت رو غیرفعال کنید

**Comment by mehdikhody** [comment]
> اگر ای پی لیمیت فعال باشه و شما access log و fail2ban نصب نداشته باشید cpu بالا میره داخل logsهم میتونید warning هارو ببینید راه حل هم اینه یا موارد لازم رو نصب و اضافه کنید یا ای پی لیمیت رو غیرفعال کنید

تمامی موارد نصب شده اما من همچنان این مشکل را داشتم و تصمیم گرفتم کلا از این ویژگی استفاده نکنم.
