### ISSUE TITLE
خطای لاگ

### ISSUE THREAD

**Issue by Alphfaa** [MHSanaei/3x-ui#1291]
2023/12/05 21:12:34 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email

سلام دوستان خسته نباشید.
این خطا چیه که احساس میکنم کندی سرور از این خطا نشأت گرفته مصرف cpu هم بالا رفته

**Comment by Arman-nsb** [comment]
سلام، اکانت ها باید email یکتا داشته باشن و اگر تکراری بینشون باشه این خطا رو پنل میاد.
