### ISSUE TITLE
نمایش ندادن فالوورهای اینستاگرام

### ISSUE THREAD

**Issue by miladddl12** [MHSanaei/3x-ui#1293]
دوستان ما همه ی پروتکل‌های مختلف رو تست کردیم اما نمیتونیم فالوور‌های اینستا رو مشاهده کنیم!!!
راهی هست؟

**Comment by kalilovers** [comment]
سلام 
https://github.com/MHSanaei/3x-ui/discussions/1298
اینجا توضیح دادم
