### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by alireza0** [MHSanaei/3x-ui#1300]
- [x] Expand multiDomain to externalProxy (Multi Function in one place)
  - [x] [sub] adjustment for externalProxy
  - [x] Add routing for migrating old MultiDomain to externalProxy
  - [x] Remove domainName in tls and reality
  - [x] Add periority for using externalProxy of Fallback
- [x] Add TLS for SHADOWSOCKS
- [x] [sub] URI support for External reverse proxies
- [x] Add gzip compression for panel pages
- [x] Multi path in tcp request header
- [x] Update DB WAL before backup
- [x] import-export inbound
- [x] customizable remark 
- [x] combine with xray logs

## Design
- [x] Add back to top button
- [x] Optimizing loading of script files
- [x] Optimize security in front codes
- [x] fix user-pass setting style
- [x] show id in confirm modal title
- [x] Optimized CSS
- [x] Optional pagination
- [x] [xray] show xray errors
- [x] log modal prettifier

## Bugs
- [x] fix error in deepSearch
- [x] outbound tag velidation
- [x] fix routing dns strategy
- [x] del x-ui settings in final tls/reality

**Comment by MiniKoro** [comment]
After a good night's sleep, I woke up and updated it. Thank you to the developers.

**Comment by Airbus380com** [comment]
How can i use single domain for subscription? For example currently domain was blocked by isp. And on that domian have several customers. After block changing the server and moving date base to new one and i have to use new domain. And everytime i have to renew clients subscription link. Is it possible to use a domain that isp won’t detect and just ip will be damaged. After changing ip its gonna work again and subscription domain wont damage.
