### ISSUE TITLE
دامنه فیلتر شده

### ISSUE THREAD

**Issue by mehranmhr11** [MHSanaei/3x-ui#1303]
سلام دامنه من فیلتر شده پینگ نمیده میتونم بکاپ به دامنه جدید بریزم بدون مشکل کار کنن؟

**Comment by Arman-nsb** [comment]
سلام،
تا جاییکه من اطلاع دارم اگر تو کانفیگ ها از دامنه استفاده شده باشه ( مثلا بجای آی پی دامنه رو ثبت کنید یا از tls استفاده بشه) تمام اکانت ها بلا استفاده میشه و باید کانفیگ با دامنه جدید به کاربرها بدید.

**Comment by MAsterhadi** [comment]
دامنه داداش به سرور ربطی نداره مگه اینکه ای پیت زده باشن که میتونی جایگزین کنی 
سرور جدید هم نصب کنی اپدیت میشینه روش

**Comment by mehranmhr11** [comment]
> دامنه داداش به سرور ربطی نداره مگه اینکه ای پیت زده باشن که میتونی جایگزین کنی سرور جدید هم نصب کنی اپدیت میشینه روش

الان من با آیپی تمیز پنل بیارم بالا بکاپ بریزم رو پنل در کم ترین زمان فیلتر میشه دامنه هم که فیلتره تانل که میکنم 1 روز مقاومت نمیکنه تانل هم میبندن

**Comment by MAsterhadi** [comment]
این داداش مشکل نوع کانفینگ دادنته من تو این مدت گذشته که نت داغونه 1 سال و خورده ای 3 بار فیلتر شده سرورهام روی یه سرور دا ناموس کانفینگ میدی  هر 100 یا 150 تا روی یه سرور بالا بیار هیچ مشکلی نمیخوری چندتا کار دیگه هم هست که بکنی فیلتر نشی یا کمتر فیلتر بشی  
تانل که عمرا فیلتر بشه فقط باید بدونی چکار کنی

**Comment by mehranmhr11** [comment]
> این داداش مشکل نوع کانفینگ دادنته من تو این مدت گذشته که نت داغونه 1 سال و خورده ای 3 بار فیلتر شده سرورهام روی یه سرور دا ناموس کانفینگ میدی هر 100 یا 150 تا روی یه سرور بالا بیار هیچ مشکلی نمیخوری چندتا کار دیگه هم هست که بکنی فیلتر نشی یا کمتر فیلتر بشی تانل که عمرا فیلتر بشه فقط باید بدونی چکار کنی

بنظرت مستقیم کانفیگ چی بهتره بدم به مشتریا؟

**Comment by MAsterhadi** [comment]
الان cdn خوب جواب میده
