### ISSUE TITLE
نمایش ندادن IP

### ISSUE THREAD

**Issue by amirvp** [MHSanaei/3x-ui#1304]
سلام وقت بخیر روی بعضی سرورها وقتی پنل رو نصب میکنم، داخل پنل ، توی قسمتی که میشه آی پی یوزرها رو دید،IP Log، اون قسمت همش مینویسه NO IP Record و هر چقدر زمان میگذره هم درست نمیشه در حالی که همون پنل روی سرورهای دیگه جواب میده
این مشکل روی سرورهای فالکنشتاین هتزنر و بعضی سرورهای ایران هستش

**Comment by amirvp** [comment]
چجوری میشه این مشکل رو برطرف کرد؟

**Comment by amirvp** [comment]
/usr/local/x-ui/x-ui[2303]: WARNING - access.log doesn't exist in your config.json
 
 این ارورو هم داره توی قسمت x-ui log موجود بود

**Comment by Hugsyyyy** [comment]
مشکلی در fail2ban  ایجاد نمیکنه اینکار؟؟ 

سوال دیگر برای لیمیت کردن ip بایستی حتما fail2ban  نصب بشه ؟

**Comment by mvk0078** [comment]
> در قسمت Xray Configuration مطمئن بشید که فایل access.log را در سکشن log دارید. و اگر نداشتید بصورت دستی اون لاین رو اضافه کنید. در نهایت بدینصورت باید باشه:
> 
> ```
>   "log": {
>   "loglevel": "warning",
>   "access": "./access.log",
>   "error": "./error.log"
>   },
> ```

تنظیماتی که گفتید لاگ ip فعال میشه ولی لاگ ip وارپ و ایپی های اونو نشون میده رو میندازه این مشکل رو چجوری بر طرف کنم
