### ISSUE TITLE
Sni is not save in version 2.0

### ISSUE THREAD

**Issue by alipour66m** [MHSanaei/3x-ui#1315]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Sni is not save in version 2.0

### Version of 3x-ui

Sni is not save in version 2.0

### x-ui log reports or xray log

Sni is not save in version 2.0

**Comment by Wolf6470** [comment]
درود ممنون از زحماتی که میکشید.در پروتکل grps موقعی که sni می زاریم سیو نمیشه!!

**Comment by alipour66m** [comment]
فیلد sni همیهش خالی میمونه و سیو نمیشه
این یه باگه ربطی به externalProxy نداره

**Comment by Wolf6470** [comment]
البته تو ws اینجوری نیست و سیو میشه

**Comment by alipour66m** [comment]
توی وب ساکت هم سیو نمیشه
________________________________

**Comment by alipour66m** [comment]
خیر دوست عزیز برای من حتی در ws هم سیو نمیشه
برای شما از قبل مونده
جدید بساز متوجه میشی سیو نیست

**Comment by Wolf6470** [comment]
آره حق با جنابعالی هستش یکی ساختم سیو موند ولی جدید که ساختم سیو نمیشه

**Comment by alipour66m** [comment]
> مجددا اپدیت کنید مشکل حل شده بعد اپدیت کردن حتما یکبار Ctrl+F5 رو بگیرید تا کش تخلیه بشه و به درستی sni نمایش داده بشه

آره درست شد
خسته نباشی

**Comment by miladddlxyz** [comment]
الان بدون هیچ مشکلی آپدیت کنیم؟؟
کانفیگی قطع نمیشه؟؟ رئالتی،تانل،vless,ws,tls، آی‌پی ۶ و... ؟؟
