### ISSUE TITLE
بلاک کردن پروتکل کوییک برای حل مشکل اینستاگرام و یوتوب

### ISSUE THREAD

**Issue by pulsarice** [MHSanaei/3x-ui#1316]
سلام. اخیرا دیدم که روی بعضی پروتکل‌های inbound که عبور بسته‌های QUIC رو بلاک نمی‌کنن، توی مشاهده اینستاگرام و یوتوب مشکل ایجاد شده.
البته وقتی flow روی xtls-rprx-vision باشه، خود کلاینت پروتکل QUIC رو بلاک می‌کنه و مشکلی پیش نمیاد. اما بعضی کلاینت‌ها همچنان ترافیک UDP443 رو عبور می‌دن و اختلال ایجاد می‌کنند.
پیشنهاد می‌کنم گزینه‌ای در پنل قرار داده بشه که این پروتکل رو بلاک کنه.
خودم با اضافه کردن این چند خط در ابتدای routing بعد از خط‌های مربوط به api مشکل رو حل کردم.
```
  {
    "type": "field",
    "port": "80,443",
    "network": "udp",
    "outboundTag": "blocked"
  },
```

این هم [توضیحیه](https://xtls.github.io/en/config/outbounds/vless.html#userobject) که توی داکیومنتیشن‌های xray درباره نامناسب بودن عبور پروتکل  QUIC از مسیر پروکسی هست؛ به علت اینکه دو لایه flow control ایجاد می‌کنه

> When using Xray-core's XTLS, traffic to UDP port 443 is blocked by default (generally for QUIC), so the application will use TLS instead of QUIC, and XTLS will take effect. In fact, QUIC itself is not suitable for proxying because it has its own TCP functionality. When it is transmitted as UDP traffic through the VLESS protocol, the underlying protocol is TCP, which is equivalent to two layers of TCP.

**Comment by kalilovers** [comment]
سلام ممنون از این نکته ای که اشاره کردید بهش من با روش دیگه ای حلش کردم ولی به نظرم راحت تر هست از تو سرور مسدود کنیم udp رو :
ufw deny port/udp
اوکیه به نظرتون ؟

**Comment by ahmadipiralvan** [comment]
> سلام ممنون از این نکته ای که اشاره کردید بهش من با روش دیگه ای حلش کردم ولی به نظرم راحت تر هست از تو سرور مسدود کنیم udp رو : ufw deny port/udp اوکیه به نظرتون ؟

غیرفعال کردن UDP به طور کلی در سرور پیشنهاد نمیشه و عملکرد هایی مثل DNS ممکنه از دست بره. شما می تونید تو کانفیگ xray تون روت بنویسید و محدودیت هایی رو اعمال کنید.

**Comment by meta-syfu** [comment]
> سلام. اخیرا دیدم که روی بعضی پروتکل‌های inbound که عبور بسته‌های QUIC رو بلاک نمی‌کنن، توی مشاهده اینستاگرام و یوتوب مشکل ایجاد شده. البته وقتی flow روی xtls-rprx-vision باشه، خود کلاینت پروتکل QUIC رو بلاک می‌کنه و مشکلی پیش نمیاد. اما بعضی کلاینت‌ها همچنان ترافیک UDP443 رو عبور می‌دن و اختلال ایجاد می‌کنند. پیشنهاد می‌کنم گزینه‌ای در پنل قرار داده بشه که این پروتکل رو بلاک کنه. خودم با اضافه کردن این چند خط در ابتدای routing بعد از خط‌های مربوط به api مشکل رو حل کردم.
> 
> ```
>   {
>     "type": "field",
>     "port": "80,443",
>     "network": "udp",
>     "outboundTag": "blocked"
>   },
> ```
> 
> این هم [توضیحیه](https://xtls.github.io/en/config/outbounds/vless.html#userobject) که توی داکیومنتیشن‌های xray درباره نامناسب بودن عبور پروتکل QUIC از مسیر پروکسی هست؛ به علت اینکه دو لایه flow control ایجاد می‌کنه
> 
> > When using Xray-core's XTLS, traffic to UDP port 443 is blocked by default (generally for QUIC), so the application will use TLS instead of QUIC, and XTLS will take effect. In fact, QUIC itself is not suitable for proxying because it has its own TCP functionality. When it is transmitted as UDP traffic through the VLESS protocol, the underlying protocol is TCP, which is equivalent to two layers of TCP.

موقع بلاک کردن UDP اینستاگرام لیست فالوور و فالووینگ و همچنین لیست های دیگری مثل ریلز رو نمیتونه باز کنه!
