### ISSUE TITLE
مسئله آپدیت(v2)

### ISSUE THREAD

**Issue by miladddlxyz** [MHSanaei/3x-ui#1318]
درود
قبل از آپدیت چیکار کنیم؟!
الان آپدیت کنیم برخی از کانفیگا قطع میشن؟؟‌
درسته که sni ذخيره نميشه!؟

**Comment by Arman-nsb** [comment]
من آپدیت کردم هیچ مشکلی نداشت، کانفیگ ها همه اوکی ان.

**Comment by Bagheri1401** [comment]
منم آپدیت کردم xray ,غیرفعال میشه

**Comment by Arman-nsb** [comment]
> منم آپدیت کردم xray ,غیرفعال میشه

لاگ خطارو تو صفحه داشبورد بررسی کنید، نشون میده چه عاملی باعث قطعی سرویس x-ui شده.

**Comment by ho3einAsadi** [comment]
مشکلی نداره فقط domin name حذف شده
