### ISSUE TITLE
مشکل در sni و tls

### ISSUE THREAD

**Issue by k1trader** [MHSanaei/3x-ui#1321]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

لطفا قسمت domain name هنگامی که tls روشن میکنیم رو اضافه کنید تو ورژن قبلی بود الان دیگه نمیاد در حالتgrpc

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by misagh72** [comment]
ues External Proxy

**Comment by Arman-nsb** [comment]
گزینه External Proxy رو فعال کنید. دامنه ای که قبلا در فیلد domain name وارد میکردید رو همینجا ثبت کنید بدون تغییر port، مشکل حل میشه.
