### ISSUE TITLE
(Online/Offline)عدم نمایش صحیح وضعیت کاربر

### ISSUE THREAD

**Issue by Mr-HaroldFinch** [MHSanaei/3x-ui#1322]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

متاسفانه نشان دادن وضعیت آنلاین بودن کاربر برای من کار نمیکنه و همیشه آفلاین نشون داده میشه.
کسی راهکاری برای این موضوع داره؟

نکته: من از نسخه قبلی به نسخه 2 به روزرسانی کردم.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Arman-nsb** [comment]
باید حالت auto-refresh رو فعال کنید تا بصورت زنده وضعیت کاربرها رو ببینید.
![image](https://github.com/MHSanaei/3x-ui/assets/84615037/e98343de-a7d0-495c-aa8e-470f09ba5f17)

**Comment by Mr-HaroldFinch** [comment]
مرسی از توضیح و پاسخ سریعت دوست عزیز 
البته با فعال کردن آتو-رفرش هم مشکل حل نشد.
من برای تست به صورت دستی رفرش می کردم اما همل هیج تغییر حالتی برای وضعیت کاربر وجود نداره و همیشه روی آفلاین.

**Comment by Arman-nsb** [comment]
کانفیگ رو تست کردید ببینید کلا به اینترنت وصل میشه یا نه؟

**Comment by Mr-HaroldFinch** [comment]
بله همه چیز اوکی فقط همین موضوع هست.

**Comment by Parhamkaa** [comment]
متاسفانه منم همین مشکل رو دارم

**Comment by Mr-HaroldFinch** [comment]
برای تست یه سرور جدیدبالا آوردم و مستقم نسخه جدید و نصب کردم و بک آپ که گرفته بودم ریستور کردم امات نکته جالب اینه که فقط از بین همه کاربر ها وضعیت یک کاربر و نشون میده که اونم آخرین کاربر لیست هست و الباقی کاربر ها همه رو آفلاین نشون میده.
تنظیمات همه کاربر هم مثل همه.

**Comment by Parhamkaa** [comment]
چک کردم زمانی که بک آپ میگیرم از سرور دیگه ای ریستور میکنم این مشکل پیش میاد
سرور قبلی رو ورژن قبلی X-ui هست

**Comment by Mr-HaroldFinch** [comment]
سرور قبلی و آپدیت کردم ملا نشون نمیداد ، برای همین سرور جدید نصب کردم و بکاپ نسخه 2.0.0 رو استفاده کردم اما بازم نشد و فقط یک کاربر که آخرین کاربر رو نشون میده
