### ISSUE TITLE
اضافه کردن کاربران آنلاین  در ربات تلگرام

### ISSUE THREAD

**Issue by Wolf6470** [MHSanaei/3x-ui#1323]
با درود فراوان  تشکر از آقای ثنایی و آقا علیرضای عزیز و دیگر دوستان که در این پروژه زحمت میکشند.بسیار بسیار سپاسگزارم از زحمات فراوانی که میکشید.خواهشمند است اگر امکانش هست در ربات تلگرام نمایش کاربران آنلاین 
 را شبیه پنل علیرضا اضافه نمایید.

@MHSanaei @alireza0

**Comment by ramtiny** [comment]
مگه پنل علیرضا کاربران آنلاین رو زده؟
از کدوم قسمت

**Comment by Wolf6470** [comment]
![Untitled](https://github.com/MHSanaei/3x-ui/assets/101067119/da8573f9-a700-4a29-a117-cec6a9cf4e2a)
