### ISSUE TITLE
how to receive vmess config after adding client using api? نحوه دریافت کانفیگ بعد از اضافه کردن یوزر در پنل با API

### ISSUE THREAD

**Issue by hoseininjast** [MHSanaei/3x-ui#1325]
درود
بنده از اخرین ورژن استفاده میکنم ورژن ۲.۰.۰
در گذشته هم همچین قابلیتی نبود فکر کنم از ورژن ۱.۷ به بعد رو من نصب کردم این رو پیدا نکردم
میخوام از طریق api بتوانم qr code  و vmess://confighere رو دریافت کنم
پروژه دیگه ای به اسم ویز ویز wizwiz این کار رو انجام داده
هدف من چیه : یک ربات تلگرام بنویسم که هر کاربر بتونه بیاد و کانفیگ خودش رو دریافت کنه
همچنین بتونه درخواست بده که سرورس عوض شه مثل از المان بره روی امریکا
اگر بخش اول رو راهنمایی کنید ممنون میشم این که بتونم کانفیگ یا qrcode دریافت کنم برای هر کاربر
ممنون از زحمت هایی که میکشید 
خسته نباشید

**Comment by hoseininjast** [comment]
فکر کنم باید در api => getclient این مورد اضافه بشه
یا یک api جدید بزارید که ای دی یا ایمیل بدیم و کانفیگ رو بگیریم
یا اگر روشی هست که سمت سرور خودم توی ربات تلگرام با php laravel بشه این لینک رو ساخت بگید که اونجا بسازم
بازم ممنون و خسته نباشید

**Comment by hoseininjast** [comment]
@MHSanaei لطفا این مورد رو بررسی کنید و جواب بدید
ممنون

**Comment by Hossein-Teimouri** [comment]
سلام منم به همچین وبسرویسی نیاز دارم الان وبسرویس هایی برای ساخت کلاینت جدید و ... داریم اما کانفیگ ساخته شده رو برنمیگردونه
اگر اشتباه نکنم وبسرویس اپدیت کلاینت روهم وقتی استفاده میکنید میگه این ایمیل از قبل وجود داره(انگاری میخواد که کلاینت جدید بسازه)
تعدادی از وبسرویسهایی که تست کردم
```
http://{{HOST}}:{{PORT}}/panel/api/inbounds/getClientTraffics/{email}
http://{{HOST}}:{{PORT}}/panel/api/inbounds/addClient
http://{{HOST}}:{{PORT}}/panel/api/inbounds/updateClient/{uuid}
```
