### ISSUE TITLE
تانل زدن بین دو سرور

### ISSUE THREAD

**Issue by MatinMHF** [MHSanaei/3x-ui#1326]
بعد از تانل زدن بین دو سرور باید کانفیگ سرور خارج را در نرم افزار وارد کرد و بعد از ان ای پی سرور تونل شده را بصورت دستی جای ای پی سرور اصلی جایگزاری کرد . ایا روشی وجود ندارد که پنل این کار را بصورت اتومات انجام دهد؟

**Comment by hrasoul2** [comment]
شما ایپی سرور رو پشت یه دامین بندازین و هر وقت فیلتر شد میرید ایپی دامین رو عوض میکنید و و بکاپ رو برمیگردونید تو سرور جدید اینطوری دیگه نیاز نیس برای کاربرهاتون ایپی رو عوض کنید
