### ISSUE TITLE
IP limit Status on panel | نمایش وضعیت محدودیت کاربر در پنل

### ISSUE THREAD

**Issue by kalilovers** [MHSanaei/3x-ui#1329]
سلام جناب سنایی و علیرضا خیلی ممنونیم از زحماتتون بخصوص اپدیت های عالی و همین نسخه جدید که خیلی کارو راحت کرده مثل external proxy . 

یک ویژگی کاربردی اگر امکانش هست اضافه بشه به پنل خیلی کمک کننده هستش اونم , **نمایش وضعیت محدودیت کاربر توی پنل هستش .** 

تو سرور از طریق ترمینال دستور 17 و 4 میشه دید کدوم کلاینت و کدوم ایپیش محدود شده این خیلی عالیه وقتی کسی پیگیری میشه فهمید دلیل قطعی رو و یه سری کاربرد های دیگه ولی مراجعه به ترمینال پی در پی خیلی کارو سخت میکنه . اگر بشه یه 
قسمت برا لاگ ایپی لیمیت بزارید که مثل ترمینال دقیق نشون بده خیلی عالی میشه 

لاگ خود پنل اطلاعات دقیقی نمیده و از طریقی چندان هم سریع نیست دسترسی بهش وظاهرا گرافیکی و مشخصی نداره زیاد و نمایش داده نمیشه دیتاهای قبل تر .

ممنون از لطفتون

**Comment by Masouddhojaei** [comment]
> سلام چطوریه که ایپی لیمیت برا شما کار میکنه؟

سلام ، باید کد access log رو به فایل config.json اضافه کنید و همینطور fall2ban رو هم فعال کنید.

**Comment by roozbehalamdari** [comment]
> > سلام چطوریه که ایپی لیمیت برا شما کار میکنه؟
> 
> سلام ، باید کد access log رو به فایل config.json اضافه کنید و همینطور fall2ban رو هم فعال کنید.

درود این کد رو میشه بدین من هم اضافه کنم  ؟ ممنونم

**Comment by Masouddhojaei** [comment]
ارادت
خدمت شما
"log": {
   "access": "./access.log"
}

**Comment by Masouddhojaei** [comment]
``"log": {
   "access": "./access.log"
}

**Comment by Masouddhojaei** [comment]
` "log": {
   "access": "./access.log"
}`

**Comment by Behnamskyy** [comment]
> ارادت خدمت شما "log": { "access": "./access.log" }

هرجا وارد میکنم خطا میده.دقیقا کجا وارد کنیم

**Comment by Behnamskyy** [comment]
بله دقیق اونجا وقتی کپی میکنم خطا میده

**Comment by Behnamskyy** [comment]
الان درستش کردم وارد شد file2ban هم نصب کردم
ولی کار نمیکنه محدودیت هم رو ۱ ایپی گذاشتم تستش کردم با ۲ گوشی بازهم کار نمیکنه

**Comment by milad73n** [comment]
باید با اینترنت های متفاوت وصل شن براساس دیوایس نیس براساس ایپیه

**Comment by Behnamskyy** [comment]
میدونم داداش دقیقا همینکارو کردم یکی با همراه اول یکی با وایفای
قبلنا کار میکرد الان نه
واسه شما درست شد؟کار میکنه؟

**Comment by ahmadta72** [comment]
سلام و احترام ضمن تشکر و خسته نباشید، من به تازگی مهاجرت کردم روی سنایی. جدا از قابلیتی که دوستمون درخواست کردند، شوربختانه برای من هم iplimit فعال نمی شود. کلیه مواردی که در داکیومنت اعلام شده لحاظ شده، در نسخه v2.0.1 و چندین توزیع لینوکس جهت بررسی دقیق تر تست شد که در شناسایی آی پی ها موفق می باشد اما در بن کردن و نهایتا در بخش لاگ هیچ اتفاقی نمی افتد. ممنون میشم اگر از دوستان و همچنین توسعه دهندگان عزیز که تجربه دارند مارو هم راهنمایی کنند تا بتونیم از این ویژگی استفاده کنیم.

**Comment by hrasoul2** [comment]
احتمالن برای این کار نمیکنه که شما تانل کردید و احتمالن مدل تانلتون یا پورت فورواردینگ یا ایپی تیبل هستش
تو تانل موقعی ایپی لیمیت کار میکنه که شما تانلتون پنل به پنل باشه یعنی هم تو سرور ایران پنل رو نصب کنید و یوزرهارو ازین سرور بدید و هم تو سرور خارج پنل رو نصب میکنید و اونجا یه یوزر میسازید و سرور ایران رو از طریق outband به این سرور تانل میکنید
تو مدل ایپی تیبل یا پورت فورواردینگ شما رو سرور خارج fail2ban رو نصب کردید اما چون یوزرتون همه از طریق ایپی ایران به سرور خارج وصل میشن همه رو یه ایپی میبینه و نمیتونه محدودیت رو فعال کنه
شما باید رو سرور ایران پنل نصب کنید و fail2ban رو اون نصب کنید و اینجا با ایپی اضافه وصل شه هرکی لیمیت میشه

**Comment by ahmadta72** [comment]
> احتمالن برای این کار نمیکنه که شما تانل کردید و احتمالن مدل تانلتون یا پورت فورواردینگ یا ایپی تیبل هستش تو تانل موقعی ایپی لیمیت کار میکنه که شما تانلتون پنل به پنل باشه یعنی هم تو سرور ایران پنل رو نصب کنید و یوزرهارو ازین سرور بدید و هم تو سرور خارج پنل رو نصب میکنید و اونجا یه یوزر میسازید و سرور ایران رو از طریق outband به این سرور تانل میکنید تو مدل ایپی تیبل یا پورت فورواردینگ شما رو سرور خارج fail2ban رو نصب کردید اما چون یوزرتون همه از طریق ایپی ایران به سرور خارج وصل میشن همه رو یه ایپی میبینه و نمیتونه محدودیت رو فعال کنه شما باید رو سرور ایران پنل نصب کنید و fail2ban رو اون نصب کنید و اینجا با ایپی اضافه وصل شه هرکی لیمیت میشه

مرسی بابت توضیحات » در واقع اصلا من تانل نکردم و صحبت من اتصال به صورت مستقیم هست (نه وب سوکت و نه تانل). اگر هم بخوام تانل کنم پنل رو روی سرور ایران نصب می کنم و با 6to4 تانل می زنم. از این صحبت صرف نظر می کنم. 
در حال حاضر در سرور fail2ban نصب می باشد و مورد تنظیمات xray: 
```
  "log": {
  "loglevel": "warning",
  "access": "./access.log",
  "error": "./error.log"
  },
```
 هم لحاظ شده است. » در شناسایی ip موفق می باشد اما در لیمیت بر اساس تنظیمات ناموفق.

**Comment by hrasoul2** [comment]
> > احتمالن برای این کار نمیکنه که شما تانل کردید و احتمالن مدل تانلتون یا پورت فورواردینگ یا ایپی تیبل هستش تو تانل موقعی ایپی لیمیت کار میکنه که شما تانلتون پنل به پنل باشه یعنی هم تو سرور ایران پنل رو نصب کنید و یوزرهارو ازین سرور بدید و هم تو سرور خارج پنل رو نصب میکنید و اونجا یه یوزر میسازید و سرور ایران رو از طریق outband به این سرور تانل میکنید تو مدل ایپی تیبل یا پورت فورواردینگ شما رو سرور خارج fail2ban رو نصب کردید اما چون یوزرتون همه از طریق ایپی ایران به سرور خارج وصل میشن همه رو یه ایپی میبینه و نمیتونه محدودیت رو فعال کنه شما باید رو سرور ایران پنل نصب کنید و fail2ban رو اون نصب کنید و اینجا با ایپی اضافه وصل شه هرکی لیمیت میشه
> 
> مرسی بابت توضیحات » در واقع اصلا من تانل نکردم و صحبت من اتصال به صورت مستقیم هست (نه وب سوکت و نه تانل). اگر هم بخوام تانل کنم پنل رو روی سرور ایران نصب می کنم و با 6to4 تانل می زنم. از این صحبت صرف نظر می کنم. در حال حاضر در سرور fail2ban نصب می باشد و مورد تنظیمات xray:
> 
> ```
>   "log": {
>   "loglevel": "warning",
>   "access": "./access.log",
>   "error": "./error.log"
>   },
> ```
> 
> هم لحاظ شده است. » در شناسایی ip موفق می باشد اما در لیمیت بر اساس تنظیمات ناموفق.

کدها هم درسته
نمیتونم ازینجا چیزی بگم باید به سرورتون یا فایل بکاپ از سرورتون دسترسی داشته باشم تو سرور خودم چکش کنم بگم مشکل کجاس
خاستید به تلگرامم پیام بدید 
@denras3

**Comment by arshia21** [comment]
من دقیقاً همون مشکل رو داشتم،  یک آی‌پی رو دستی مسدود کردم و بعدش کار کرد @ahmadta72 
fail2ban-client set 3x-ipl banip 172.0.0.0

**Comment by roozbehalamdari** [comment]
> من دقیقاً همون مشکل رو داشتم، یک آی‌پی رو دستی مسدود کردم و بعدش کار کرد @ahmadta72 fail2ban-client set 3x-ipl banip 172.0.0.0

سپاس از راهنماییت عرشیا جان ، یعنی من توی SSH این دستور رو وارد کنم اکی میشه ؟ 
fail2ban-client set 3x-ipl banip 172.0.0.0

**Comment by arshia21** [comment]
بله دقیقا، البته بجای 172.0.0.0 ایپی یکی از کاربرهارو وارد کنید.

**Comment by aminkiller77** [comment]
من تو پنل برام قسمت ایپی لیمیت نمایش داده نمیشه مشکل ازکجاس؟

**Comment by mobinmoji** [comment]
سلام خدمت همگی من این اورو رو اضافه می کنم سرعت اینباند هام کمتر از نصف میشه راه حلی وجود نداره که سرعتش کم نشه؟

**Comment by mobinmoji** [comment]
> سلام خدمت همگی من این اورو رو اضافه می کنم سرعت اینباند هام کمتر از نصف میشه راه حلی وجود نداره که سرعتش کم نشه؟ 
<img width="1056" alt="Screenshot 1403-03-01 at 22 32 29" src="https://github.com/MHSanaei/3x-ui/assets/126095312/22edd47d-6453-42bb-891a-6c9c7863717d">

<img width="391" alt="Screenshot 1403-03-01 at 22 32 38" src="https://github.com/MHSanaei/3x-ui/assets/126095312/900efa26-59fc-4c8e-b86a-eae92df0c9fb">

**Comment by alirezahosseiny5540-debug** [comment]
دوستان من گزینه ip limit رو در اپدیت جدید پنل پیدا نمیکنم. ممنون میشم راهنمایی کنید.
