### ISSUE TITLE
مشکل در آپدیت تجمیعی کلاینت های یک inbound

### ISSUE THREAD

**Issue by mostafapahlevani** [MHSanaei/3x-ui#1336]
با سلام . در api  مربوط به updateClient ، اگر در دیتای آپدیت بیشتر از یک کلاینت باشد  . فقط کلاینت اولی آپدیت می شود . با بررسی کد مشخص شد فقط index صفرم آرایه ارسالی آپدیت میشود . 

https://github.com/MHSanaei/3x-ui/blob/af54b34f3a4035cebecf9e614142b6ad5ac06c40/web/service/inbound.go#L585

لطفا در صورت امکان مشکل گزارش شده رو حل کنین . ممنون @MHSanaei @

**Comment by alireza0** [comment]
درود بر شما
این متد فقط برای ویرایش یک کاربر استفاده میشه و نمیتونید بیشتر بفرستید.
برای ویرایش چند کاربر باید از ویرایش اینباند استفاده کنید.

**Comment by mostafapahlevani** [comment]
> درود بر شما این متد فقط برای ویرایش یک کاربر استفاده میشه و نمیتونید بیشتر بفرستید. برای ویرایش چند کاربر باید از ویرایش اینباند استفاده کنید.

مرسی از پاسختون . ولی آبجکت ورودی که آرایه هست به نظر این مورد اینجا هم میتونه پیاده بشه .همون طوری که در api مربوط به addClient که دقیقا همین ورودی رو داره امکان ایجاد تجمعی کاربران وجود داره . اگر برای آپدیت هم اضافه بشه خیلی خیلی خیلی کمک کنندس . 

اگر بخوایم از ویرایش اینباند استفاده کنیم . باید تمام یوزرها رو بهش بدیم مجددا . چون overwrite میکنه . 


ممنون میشم این موارد رو اضافه کنین به api پنل . با تشکر از شما @alireza0

**Comment by alireza0** [comment]
این موارد درسرهاش بیشتر از سودشه.
شما میتونید چندین بار به ازای هر کاربر، دستور ویرایش رو بفرستین.
هم امنیتش بالاتره و هم راحت تره.

**Comment by mostafapahlevani** [comment]
> این موارد درسرهاش بیشتر از سودشه. شما میتونید چندین بار به ازای هر کاربر، دستور ویرایش رو بفرستین. هم امنیتش بالاتره و هم راحت تره.

اتفاقا چون تست کردم اینو . این درخواست رو مطرح کردم . اگر شما مثلا 100 درخاوست ساخت ایجاد اکانت موازی بزنین . تا 70% درخواست ها خطا میخوره . این مورد برای اپدیت و دیلیت هم هست . و اگر درخواست ها داخل حلقه بزارین و پشت سر هم بزنین (با احتساب اینکه await) بشه . بازم 30 40% از درخواست ها به مشکل میخوره . 

بهترین راه حل استفاده از همین امکان ساخت و اپدیت تجمعی هست . هم تعداد درخواست به سرور کمتره و هم سریعتر انجام میشه . 

اگر راه حلی برای این موضوع دارین . ممنون میشم راهنمایی کنین منو . چالش دارم با این موضوع . ممنون 
@alireza0
