### ISSUE TITLE
New ideas for future versions

### ISSUE THREAD

**Issue by PHPCompiler** [MHSanaei/3x-ui#1340]
سلام وقتتون بخیر خسته نباشید تشکر بابت زحماتتون فقط چند ایده دارم گفتم باهاتون به اشتراک بگذارم ،
1- در آپدیت جدید در قسمت TLS فیلد Domin Name که در نسخه های قبلی بود حذف شده است. لطفا دوباره این مورد را اضافه کنید.
2 - لینک هر سرویس از طریق Api قابل دریافت باشه.
3- برای پنل عالی شما یک کلس با php نوشتم اگر دوست داشتید با عزیزان به اشتراک بزاریم.

**Comment by Arman-nsb** [comment]
دوست عزیز مورد 1 تبدیل به External Proxy شده که هم در حالت TLS و هم غیر اون قابل استفاده هست.

**Comment by PHPCompiler** [comment]
تشکر
