### ISSUE TITLE
پنل نمایندگی در داخل پنل 

### ISSUE THREAD

**Issue by Bagheri1401** [MHSanaei/3x-ui#1341]
سلام میشه قسمت نمایندگی هم به پنل اضافه کنید هزینش هرچقدر باشه پرداخت میشه

**Comment by hoseininjast** [comment]
بله بنده هم موافقم هزینه رو پرداخت میکنیم 
میتونید یه نسخه دیگه بزارید اون رو پولی کنید
یا دونیتت کنیم که خستگیت در بره
