### ISSUE TITLE
تناقض در واحد محاسبه حجم و ترافیک

### ISSUE THREAD

**Issue by ahmadipiralvan** [MHSanaei/3x-ui#1345]
سلام
وقت بخیر و خداقوت به توسعه دهندگان پنل.

وقتی از طریق api یک کلاینت ایجاد می کنیم،
واحد حجم (محدودیت داده) رو برای اون کلاینت بر اساس GB در نظر می گیریم.
در واقع GB باید به Byte تبدیل بشه و رقم تبدیل شده به api ارسال بشه.

در کمال تعجب مشکلی در api یا پنل وجود داره.
ما حجم رو بر اساس GB محاسبه کردیم و کلاینت رو ایجاد کردیم.
اما بعدش توی پنل، حجم رو بر اساس GiB داره نشون میده!

مثلا یک کلاینت 50GB با api ایجاد کردیم اما توی پنل 46.5GB نشون میده.

در واقع مشخص نیست لیبلی که برای مشاهده حجم توی پنل خورده اشتباه هست،
یا api داره بر اساس GiB حجم رو محاسبه و در نظر میگیره.

من فرصت نکردم سورس پنل رو بازنگری کنم اما وظیفه دونستم باگ رو گزارش بدم.
چون واقعا ابهام هست در واحد محاسبه ترافیک.

سپاس فراوان

@MHSanaei @alireza0

**Comment by ahmadipiralvan** [comment]
***آپدیت**

مقداری که پنل داره نمایش میده بر حسب GiB هست
و مقداری هم که پنل به عنوان حجم و ترافیک در دیتابیس ثبت میکنه GiB هست.

بنابراین Api داره درست کار میکنه و دیتای خروجیش هم بر اساس GB هست.
اما پنل مشکل داره و بر اساس GiB داره محاسبه میکنه.

**با این اوصاف توابع مربوط به تبدیل بایت به گیگابایت Panel رو نیاز هست اصلاح بفرمایید و API مشکلی ندارد.**

برای اطمینان، ترافیک دانلود یکی از کلاینت ها مورد بررسی قرار گرفت:

![image](https://github.com/MHSanaei/3x-ui/assets/45537473/6c69b364-f240-47ac-a084-491d629f287e)

![image](https://github.com/MHSanaei/3x-ui/assets/45537473/f46cfcab-72bc-47a0-8cf7-f046ac8aa195)

![image](https://github.com/MHSanaei/3x-ui/assets/45537473/4a3ce732-1b3c-44d0-acec-bac069089083)

**Comment by ahmadipiralvan** [comment]
#bug

**Comment by Arman-nsb** [comment]
اعداد رو در 1,073,741,824 ضرب کنید ( 1024 به توان 3 )
مثلا میخواید 10 گیگابایت ترافیک کاربر باشه >
10 x (1024 ** 3) 

10 x 1,073,741,824

**Comment by ahmadipiralvan** [comment]
> اعداد رو در 1,073,741,824 ضرب کنید ( 1024 به توان 3 ) مثلا میخواید 10 گیگابایت ترافیک کاربر باشه :
> 
> 10 x (1024 ** 3) 10 x 1,073,741,824
> 
> به همین ترتیب اگر ترافیک رو از سرور فراخوانی میکنید، تقسیم بر این عدد کنید.

موضوع و مشکل دقیقا همینه.
این فرمول مربوط به GiB هست ، نه GB.
برای محاسبه بر حسب GB باید به توان 1000 برسه:

10 گیگابایت × (1000 به توان 3) = بایت
10,000,000,000 بایت / (1000 به توان 3) = گیگابایت

GB = 10,000,000,000 ÷ (1000x1000x1000)
Byte = 10 x (1000x1000x1000)

همچنین از ماشین حساب زیر می تونید کمک بگیرید:
www.dataunitconverter.com/gigabyte-to-byte/10

@MHSanaei @alireza0

**Comment by ahmadipiralvan** [comment]
> @ahmadipiralvan دوست عزیز اصطلاحات دنیای تلکام با محاسبات ریاضی یکی نیست. یک گیگابایت با یک گیگ بایت فرق داره. این استاندارد در همه نرم افزارهای حوزه شبکه یکیه.

سلام مجدد

مهندس جان نمیدونم منطق این حرفتون چی هست
محاسبات دنیای تلکام هم جزئی از ریاضیات هست.

از طرفی من وقتی میخوام ایشو باز کنم از صحت مسئله اطمینان پیدا می کنم تا وقت و انرژی شما رو نگیرم.

این موضوع رو مطمئن هستم که در اکثر پروژه های نرم افزاری مرتبط، برای محاسبه ترافیک از همین فرمول استفاده میشه.

کاربرد بیشتر GiB در محاسبه میزان فضای ذخیره سازی و Storage ها هست.

علت اصلی این موضوع اینه که به کاربر،
حجم بر اساس گیگابایت فروخته یا اختصاص داده میشه،
و به همین خاطر ترافیک نباید گیبی بایت GiB اعمال بشه.

برای اطمینان شما، یکی از پروژه های منتسب به گوگل رو بازنگری کردم و روش و فرمول تبدیل رو استخراج کردم.

```
GIGABYTE to Byte:
$data_limit = intval($access_key_data_limit) * 1000000000

Byte to GIGABYTE:
$data_transferred = round($dataTransferred / 1000000000, 2); //round in GB
```

جالبه بدونید ما الان از طریق API کاملا داریم بر اساس GB ذخیره و بازیابی می کنیم و مشکلی هم نداریم.
فقط این تاپیک ایجاد شد که شما باگ پنلتون رو رفع کنید،
و عزیزانی که از طریق پنل فروشنده هستن
(مثلا) به جای 100 گیگ ترافیک، 93 گیگ به مشتری نفروشن! و حق و ناحق نشه.

ممنون از توجه شما

@MHSanaei @alireza0

**Comment by alireza0** [comment]
گوگل تنها یکی از ارائه دهنده های خدماته و این باگ میتونه در کدهای اونها باشه.
هیچ جای دنیای تلکام به میلیارد بایت، گیگابایت گفته نمیشه.
کمی بیشتر جستجو و مطالعه کنید

**Comment by ahmadipiralvan** [comment]
> گوگل تنها یکی از ارائه دهنده های خدماته و این باگ میتونه در کدهای اونها باشه. هیچ جای دنیای تلکام به میلیارد بایت، گیگابایت گفته نمیشه. کمی بیشتر جستجو و مطالعه کنید.
> 
> اگر مشکل شما با GiB و GB ه که باید بگم این یک غلط مصطلحه که همه جا استفاده میشه. ربطی هم به دنیای ذخیره سازی و دنیای ارتباطات نداره

در واقع این باگ نیست مهندس. معیار اندازه گیری هست که متفاوته.
من GB محاسبه می کنم. شما GiB. اما آخرش همشون به Byte تبدیل میشه.

شما بسته اینترنتی هم که میخرید بر اساس GB میخرید.
با این حال می تونید خودتون GB رو تبدیل به GiB کنید و همچنان ازش استفاده کنید!
ولی فایلی که توی تلگرام یا هر جای دیگه دانلود و آپلود می کنید باز هم داره با MB محاسبه میکنه!
باید قبول کنید که ما نمی تونیم MB و GB رو از تلگرام، واتساپ، دانلود منیجر، و یا پنل های هاستینگ به این راحتی حذف کنیم و وادار به استفاده از واحد GiB کنیم.

**اصلا قبول مهندس
بیا منطقی نگاه کنیم.
اگر آگاه هستید که واحد محاسبه پنل GiB هست، چرا لیبل GB زدید؟
حرف بنده از اول همین بود که لیبل رو درست کنید. تغییر بدید تا دچار تناقض نشه.
دقیقا این Issue برای همین ایجاد شد تا این تناقض رفع بشه.**

ممنونم از وقتی که گذاشتید

**Comment by alireza0** [comment]
متاسفانه من و همه همکارانم به دید تجاری و حسابداری نگاه نمیکنیم.
اگر کسی دوست داره از پنل رایگان استفاده کنه و هزینه زحمت وسرمایه گذاریش رو بگیره، مشکلی نیست. ولی اینکه حالا ۲.۴٪ بیشتر یا کمتر بفروشه و یا مشتری GB میبینه و GiB استفاده میکنه موضوع دلچسب من نیست.
واقعیتش برای من اصلا مهم نیست! من از این شمارش، برای اعمال محدودیتی برای عدم سوء استفاده استفاده میکنم و نه بیشتر.
مفهموم باگ در سیستم حسابداری شما با مفهموم باگ در کدها متفاوته. میتونم نهایتا این موضوع رو از دید بهینه سازی و یا گرفتن غلط املایی بهش نگاه کنم.

**Comment by ahmadipiralvan** [comment]
دقیقا

هر چند شاید ما نتونیم در تغییر این غلط مصطلح در جهان تاثیر چندانی داشته باشیم
اما حداقل میشه این موضوع رو القا کرد که کیلوی بازاری با کیلوی کامپیوتری متفاوته.

واقعا جای سواله که چرا گوگل و مایکروسافت زیر بار شفافیت این موضوع نرفتن،
و این تناقض توی سرویس هاشون از جمله ویندوز مشاهده میشه.

ما هم در حد خودمون میتونیم به بهینه سازی و اصلاح این تناقض کمک کنیم.
