### ISSUE TITLE
آپدیت نسخه داکر

### ISSUE THREAD

**Issue by AliShFar** [MHSanaei/3x-ui#1346]
سلام. 
من نسخه 1.7.9 رو روی داکر نصب کردم. الان چجوری میتونم آپدیت کنم به نسخه 2 ؟

**Comment by Arman-nsb** [comment]
کانتینر و ایمیج قدیمی رو حذف کنید، بعد دستور نصب رو تو همون دایرکتوری که قبلا نصب بوده اجرا کنید. خودش ایمیج جدید رو pull میکنه و نصب میشه.

**Comment by AliShFar** [comment]
> کانتینر و ایمیج قدیمی رو حذف کنید، بعد دستور نصب رو تو همون دایرکتوری که قبلا نصب بوده اجرا کنید. خودش ایمیج جدید رو pull میکنه و نصب میشه.

خیلی ممنون
کانتینر و ایمیج قدیمی رو چجوری باید حذف کرد؟
