### ISSUE TITLE
No ip record

### ISSUE THREAD

**Issue by amirooo70** [MHSanaei/3x-ui#1349]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Dear sir
After the latest update, users' IP addresses are not being stored. Additionally, I see the error shown in attached 
![Screenshot 2023-12-13 092701](https://github.com/MHSanaei/3x-ui/assets/117886765/4fea53c4-e21f-4dcc-8283-1e489306523e)
image in the server log.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by LordDeveloper** [comment]
https://github.com/MHSanaei/3x-ui?tab=readme-ov-file#ip-limit
