### ISSUE TITLE
Custom socks outbound proxy, unable to connect

### ISSUE THREAD

**Issue by sky22333** [MHSanaei/3x-ui#1352]
Welcome
 Yes, I'm using the latest major release. Only such installations are supported.
 Yes, I'm using the supported system. Only such systems are supported.
 Yes, I have read all WIKI document,nothing can help me in my problem.
 Yes, I've searched similar issues on GitHub and didn't find any.
 Yes, I've included all information below (version, config, log, etc).

I customized a routing rule, outbound proxy. When I connect to this inbound proxy I cannot communicate.
As shown in the figure, routing rule 1 corresponds to tw outbound

IP connectivity has been checked and is normal. I deployed tw outbound via other means and can connect.

![1](https://github.com/MHSanaei/3x-ui/assets/115192496/d5f81a69-682e-4800-9ce5-2318949af807)
![2](https://github.com/MHSanaei/3x-ui/assets/115192496/6a0376cf-47e5-4cd1-abd2-ede85dccccc7)

**Comment by taotao1058** [comment]
####  It has been confirmed that it is a format issue and we hope it will be fixed as soon as possible。Thanks to the developers for their contributions



![666](https://github.com/MHSanaei/3x-ui/assets/115192496/59e31ee7-d179-47a2-a40f-f4800c1a870f)

**Comment by taotao1058** [comment]
###  The problem has been solved
