### ISSUE TITLE
نداشتن گزینه domin name 

### ISSUE THREAD

**Issue by amirneo98** [MHSanaei/3x-ui#1354]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام نمیتونیم تو اپدیت جدید از domian name استفاده کنیم😒😒😒

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by ho3einAsadi** [comment]
لطفا domin name رو برای کانفیگ های http بدون tls هم قرار بدین 
ممنون از زحمات شما

**Comment by qar4al** [comment]
درود دوست عزیز در این قسمت قرار دارد گزینه External Proxy رو فعال کنید هم به صورت TLS هم None و ساده وجود دارد 

![image](https://github.com/MHSanaei/3x-ui/assets/63839880/a1de60e0-537c-4d4f-8694-9abce156ca79)
