### ISSUE TITLE
حذف address

### ISSUE THREAD

**Issue by ma-amjadian** [MHSanaei/3x-ui#1356]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام
آقا شما بخش ادرس رو حذف کردید و باید دستی کاربرا رو ادیت کنم. واقعا جایی در پنل ندیدید بشه بخش آدرس رو اونجا مدیریت کرد؟ بدون آدرس کانفیگ‌هام کار نمی کنن.
تروخدا راهنمایی کنید‌

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by ho3einAsadi** [comment]
فک نکنم حذف کرده باشن احتمالا فراموش کردن 
ممنون میشم وقتی domin name اضافه میشه فقط برای کانفیگ های tls نباشه کانفیگ های بدون tls هم بتونن از قابلیت domin name استفاده کنن

**Comment by qar4al** [comment]
درود بر شما دوست  عزیز حذف نشده بلکه پیشرفته تر هم شده 
شما تیک External Proxy v رو فعال کنید اونجا مشاهده میکنید .

![image](https://github.com/MHSanaei/3x-ui/assets/63839880/26515bd7-cffd-4c4c-b76a-f6aeaad4bab0)

**Comment by ma-amjadian** [comment]
درود
خیلی خیلی ممنونم. حل شد
