### ISSUE TITLE
domin name

### ISSUE THREAD

**Issue by ho3einAsadi** [MHSanaei/3x-ui#1357]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

درود 
در ورژن v2.0.0 قابلیت domin name و Multi Domain وجود نداره و خیلی عالی تر میشه اگر این قابلیت زیر مجموعه tls نباشه یعنی برای هر Remark بشه domin name انتخاب کرد  
شکر خدا با بازگشت به ورژن قبلی مشکلم حل شد اما ممنون میشم این باگ رو رفع کنید♥

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by alireza0** [comment]
درود بر شما
لطفا هر بار که بروزرسانی میکنید، به موضاعات بروز شده و متن بروزرسانی دقت کنید.

**Comment by kalilovers** [comment]
> درود بر شما لطفا هر بار که بروزرسانی میکنید، به موضوعات بروز شده و متن بروزرسانی دقت کنید.

سلام خسته نباشی مهندس . اینکه میشه چند دامین اضافه کرد تو این بخش جدید تو تک کانفیگ کار نمیکنه طبیعتا یه دامین میندازه ولی مثلا بعضیا از چند دامنه برای کلاینتای یه اینباند استفاده میکنند که پخش بشه ترافیک و مدیریت راحت بشه . حالا اگه تو اینکه قسمت دوتا بزاریم و لینک ساب بدیم چطور میشه ؟ خودش تقسیم میکنه بین کلاینتا یا ...

**Comment by kalilovers** [comment]
> وقتی چند تا آدرس بذاری، به اضای هر کدوم یک کانفیگ جدا درست می‌کنه واسه یوزر.

عالیه ممنون . پس تو ساب هم برا دوتا دامین دوتا کانفیگ میده بعد اپدیت ساب

**Comment by ho3einAsadi** [comment]
سپاس فروان
