### ISSUE TITLE
Errors in log when using Russian localization

### ISSUE THREAD

**Issue by jameszeroX** [MHSanaei/3x-ui#1358]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Russian localization. When entering in "Xray Settings", errors are recorded in the log
![Screenshot_1](https://github.com/MHSanaei/3x-ui/assets/145020465/1735fbbd-baa9-4930-8e82-952793a32505)

### Version of 3x-ui

<details>

```console
2.0.1
```

</details>

### x-ui log reports or xray log

<details>

```console
2023/12/13 19:36:24 ERROR - X-UI: Failed to localize message: message "pages.xray.rules.outbound" not found in language "ru-RU"
2023/12/13 19:36:24 ERROR - X-UI: Failed to localize message: message "pages.xray.rules.outbound" not found in language "ru-RU"
2023/12/13 19:36:24 ERROR - X-UI: Failed to localize message: message "pages.xray.rules.outbound" not found in language "ru-RU"
2023/12/13 19:35:57 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2023/12/13 19:35:57 INFO - X-UI: web server run https on[::]:******
```

</details>

**Comment by neerro** [comment]
Confirm this issue. It also was in ver. 2.0.0
