### ISSUE TITLE
Can't calculate traffic

### ISSUE THREAD

**Issue by javacl** [MHSanaei/3x-ui#1360]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام پنل من ترافیک مصرفی کاربر رو حساب نمیکنه و همیشه صفر نمایش میده. چیکار میتونم انجام بدم درست بشه ؟

### Version of 3x-ui

<details>

```console
# 2.0.1
```

</details>

### x-ui log reports or xray log

<details>

```console
# 2023/12/13 22:04:43 WARNING - X-UI: get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: EOF"
2023/12/13 22:04:33 WARNING - X-UI: get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: EOF"
2023/12/13 22:04:23 WARNING - X-UI: get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: EOF"
2023/12/13 22:04:13 WARNING - X-UI: get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: EOF"
```

</details>

**Comment by javacl** [comment]
> یکبار توی بخش xray تنظیمات رو دیفالت کن و ریستارت کن، ببین فرقی می‌کنه؟

درست شد ولی وقتی warp میذارم مجدد اینجوری میشه
`[
  {
    "protocol": "freedom",
    "settings": {}
  },
  {
    "tag": "blocked",
    "protocol": "blackhole",
    "settings": {}
  },
  {
    "tag": "WARP",
    "protocol": "socks",
    "settings": {
      "servers": [
        {
          "address": "127.0.0.1",
          "port": 50000
        }
      ]
    }
  }
]`

`[
  {
    "type": "field",
    "outboundTag": "WARP",
    "domain": [
      "geosite:google",
      "geosite:spotify",
      "geosite:kaggle"
    ]
  }
]`

**Comment by kalilovers** [comment]
وارپ باید پورتش 40000 باشه مگر اینکه تغییر داده باشی تو متنت 50000 هست

**Comment by javacl** [comment]
> وارپ باید پورتش 40000 باشه مگر اینکه تغییر داده باشی تو متنت 50000 هست

پورتش پر بود تغییر دادم خودم

**Comment by javacl** [comment]
بچه ها خیلی ممنون مشکلم حل شد تنظیمات وارپ رو خوب انجام نداده بودم.

**Comment by javacl** [comment]
Done

**Comment by shahriyarg59** [comment]
از اونجایی که من خودم این مشکل داشتم، راه حل خودمم میگم!
حواستون باشه تو قسمت Routing Rules، تگ inbound (api) پاک نکرده باشید اگه شده این تیکه کد به اولینگ روتینگ رول اضافه کنید و سیو و ریستارت کنید.

```
  {
    "inboundTag": [
      "api"
    ],
    "outboundTag": "api",
    "type": "field"
  },
```

![2024-03-28_212941](https://github.com/MHSanaei/3x-ui/assets/98829981/c1f87f7d-1b56-46b2-a730-eb466bb70011)
