### ISSUE TITLE
از کار افتادن هسته بعد از آپدیت کردن

### ISSUE THREAD

**Issue by xematin** [MHSanaei/3x-ui#1364]
سلام خسته نباشید. ببخشید برای آپدیت پنل وقتی از دستور های x-ui استفاده میکنیم داخل سرور هسته پنل از کار میوفته راه حلی برای این موضوع هستش ؟

**Comment by habibnajafi** [comment]
منم همین مشکل رو دارم این خطا رومیده:

Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: ext:iran.dat:ads > infra/conf: failed to load external sites: ads from iran.dat > infra/conf: failed to load file: iran.dat > infra/conf: failed to open file: iran.dat > open /usr/local/x-ui/bin/iran.dat: no such file or directory

**Comment by MHSanaei** [comment]
important : after update +v1.7.9 you need to click on "Reset to Default Configuration" and set your settings again
