### ISSUE TITLE
مشکل وارپ در ورژن 2.0.1 

### ISSUE THREAD

**Issue by v7193m** [MHSanaei/3x-ui#1365]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

من از ورژن 1.7.9 استفاده میکردم و برای مشکل گوگل وارپ میزدم اما نه با اسکریپت وارپ. من از وایرگارد استفاده میکردم و توی قسمت outbound اینو میذاشتم:

[
  {
    "protocol": "freedom",
    "settings": {}
  },
  {
    "protocol": "wireguard",
    "settings": {
      "mtu": 1280,
      "dns": "1.1.1.1 1.0.0.1",
      "secretKey": "xxx",
      "address": [
        "172.16.0.2/32",
        "xxx/128"
      ],
      "peers": [
        {
          "publicKey": "xxx",
          "allowedIPs": [
            "0.0.0.0/0",
            "::/0"
          ],
          "endpoint": "engage.cloudflareclient.com:2408"
        }
      ]
    },
    "tag": "WARP"
  },
  {
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }
]

با اضافه کردن این کد و همچنین فعال کردن وارپ برای سایتها در list of warp domains در پنل، مشکل کاملا حل میشد. فقط باید key و ipv6 از ربات warp+ تلگرام میگرفتم و داخل کد بالا میذاشتم.
حالا بعد از آپدیت به 2.0.1 ، این روش به درستی کار نمیکنه. من بک آپ داشتم و برگشتم به پنل قبلی خودم. اما میخواستم این موضوع پیگیری کنین و مشکل رو پیدا کنین. 
ممنون از زحماتتون

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NoRRt** [comment]
منم همین مشکل دارم..

**Comment by v7193m** [comment]
> من قبلا از این روش وایرگارد استفاده می‌کردم و به شدت مصرف حافظه سرور می‌رفت بالا و کلا پایدار نبود شرایط. الان دیگه نمی‌خوام برگردم به اون روش و تست کنم روی ورژن ۲ :)) توصیه‌م اینه که از wireproxy استفاده کنی. خیلی بهتر از وایرگارد داخل xray کار می‌کنه.

خب منم مجبور شدم ازین روش استفاده کنم :)) من wireproxy داشتم، اما درست کار نمیکرد. مثلا آیکون های گوگل لود نمیشد. از image گوگل نمیشد استفاده کنی. یا حتی map و translate ! کلا سرویس های گوگل توی دیوار بود. ولی این روش که زدم، مشکل رفع شد. اما حالا توی این ورژن پنل مشکل دارم باهاش. نمیدونم دلیلش چیه

پ.ن: ولی مصرف حافظه من تغییری نکرده 🤔

**Comment by v7193m** [comment]
> خب من الان تست کردم و یه وارپ درست کردم و یه یوزر رو انداختم روش و اوکیه. اینو توی بخش advanced template وارد کردم. یبار دقیقا با همین تنظیمات و با همین private key عینا تست کن ببین مشکل از کجاست.
> 
> ```
> {
>   "protocol": "wireguard",
>   "settings": {
>   "secretKey": "mEjEaEope4DjqNX+M8QtdGCBl5HOFnzrmBYJZ5Z5tF0=",
>   "address": [
>     "172.16.0.2/32",
>     "2606:4700:110:89c6:1746:5889:7a2b:4d57/128"
>   ],
>   "peers": [
>     {
>       "endpoint": "engage.cloudflareclient.com:2408",
>       "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
>     }
>   ],
>   "mtu": 1420,
>   "workers": 2 
> },
>   "tag": "WARP"
> }
> ```

ببین من کدی که گذاشتم رو از خود x project برداشتم و دقیقا کد هموناس. الان تفاوتی که بین کد من و کد شما هست اینه که شما worker اضافه کردی که نمیدونم مال چیه و اینکه dns و allowdIP حذف شده. ولی ببین مسئله اینه که مشکل از کد نبود چون روی مثلا پنل ورژن 1.7.9 درست کار میداد. حالا بازم تست میکنم ولی بازم فکر میکنم مشکل از ی جای دیگه توی پنل باشه. خیلی ممنون

**Comment by v7193m** [comment]
خب دوستان من تست هارو انجام دادم و باید بگم مشکل از این بود :
`  {
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }`

من توی پنل قبلی، این بالایی رو هم کنار وایرگارد داشتم و درست هم بود . اما الان که داشتم تست میکردم روی پنل ورژن 2، این تیکه رو از outbound حذف کردم و درست شد!!!
حالا من نمیدونم دلیلش چیه. اگر کسی اطلاعی داره، ممنون میشم ی توضیحی بده

**Comment by v7193m** [comment]
> من از داکیومنتیشن xtls برداشتم https://xtls.github.io/en/config/outbounds/wireguard.html#outboundconfigurationobject و اگه با حذف blackhole مشکلت حل شده، احتمالا یجایی توی routing داشتی ترافیک رو بلاک می‌کردی.

روتینگ رول من اینه:
`[
  {
    "inboundTag": [
      "api"
    ],
    "outboundTag": "api",
    "type": "field"
  },
  {
    "ip": [
      "geoip:private",
      "ext:geoip_IR.dat:ir",
      "ext:geoip_IR.dat:arvancloud",
      "ext:geoip_IR.dat:derakcloud",
      "ext:geoip_IR.dat:iranserver",
      "geoip:cn",
      "geoip:ru"
    ],
    "outboundTag": "blocked",
    "type": "field"
  },
  {
    "outboundTag": "blocked",
    "protocol": [
      "bittorrent"
    ],
    "type": "field"
  },
  {
    "type": "field",
    "outboundTag": "blocked",
    "domain": [
      "ext:geosite_IR.dat:category-ads-all",
      "regexp:.*\\.ir$",
      "regexp:.*\\.xn--mgba3a4f16a$",
      "ext:geosite_IR.dat:ir",
      "geosite:cn",
      "regexp:.*\\.cn$",
      "geosite:category-gov-ru",
      "regexp:.*\\.ru$"
    ]
  },
  {
    "type": "field",
    "outboundTag": "WARP",
    "domain": [
      "geosite:meta",
      "geosite:razer",
      "geosite:google",
      "geosite:openai",
      "geosite:netflix",
      "geosite:spotify"
    ]
  }
]`

**Comment by v7193m** [comment]
> مشکلی توی روتینگت نمی‌بینم. توصیه‌م اینه که blackhole رو برگردونی و رنج ایران رو بجای بلاک کردن، بندازی روی وارپ. یا access.log رو توی تنظیمات x-ray فعال کنی و با دستور tail -f /path/access.log | grep blocked ببینی چیا دارن بلاک می‌شن بجای blocked بنویسی WARP میتونی ببینی چیا می‌رن توی وارپ. مسیرشو یادم نیست جاش نوشتم path

ممنون بابت راهنماییت
من Blackhole رو برگردوندم و ازون ور آی پی دامین هایی که بلاک کرده بودم رو درآوردم و خیلی عجیب که اوکی شد! این که گفتی آی پی هارو از وارپ بگذرون ، این کارو هم انجام دادم و کار میداد. ولی ی تست دیگه انجام دادم که مشکل رو پیدا کردم. ببین من توی پنل، به غیر از آی پی دامین های ایران، چین و روسیه هم بلاک کرده بودم. الان اومدم تست کردم، گفتم فقط از مال ایرانو بلاک کنم، تیک چین و روسیه نزدم و دیدم بلههههه، داره کار میده. فکر میکنم باگ ماجرا اینجا بود.
حسین جان بی زحمت این باگ رو روی ورژن های بعدی اوکی کن. ممنون  🙏🏻

**Comment by sofiya-i** [comment]
> > مشکلی توی روتینگت نمی‌بینم. توصیه‌م اینه که blackhole رو برگردونی و رنج ایران رو بجای بلاک کردن، بندازی روی وارپ. یا access.log رو توی تنظیمات x-ray فعال کنی و با دستور tail -f /path/access.log | grep blocked ببینی چیا دارن بلاک می‌شن بجای blocked بنویسی WARP میتونی ببینی چیا می‌رن توی وارپ. مسیرشو یادم نیست جاش نوشتم path
> 
> ممنون بابت راهنماییت من Blackhole رو برگردوندم و ازون ور آی پی دامین هایی که بلاک کرده بودم رو درآوردم و خیلی عجیب که اوکی شد! این که گفتی آی پی هارو از وارپ بگذرون ، این کارو هم انجام دادم و کار میداد. ولی ی تست دیگه انجام دادم که مشکل رو پیدا کردم. ببین من توی پنل، به غیر از آی پی دامین های ایران، چین و روسیه هم بلاک کرده بودم. الان اومدم تست کردم، گفتم فقط از مال ایرانو بلاک کنم، تیک چین و روسیه نزدم و دیدم بلههههه، داره کار میده. فکر میکنم باگ ماجرا اینجا بود. حسین جان بی زحمت این باگ رو روی ورژن های بعدی اوکی کن. ممنون 🙏🏻

سلام جناب ببخشید منم همین مشکل رو دارم warp+ تهیه کردم میخواستم ترافیک های داخلی رو فقط .ir  و بعضی دامین های خاص رو از وارپ عبور بدم ولی موقعه اعمال کردن شون  تو بخش List of WARP Domains وضعیت status پنل ارور میخوره باید چیکار کنم میشه راهنمایی کنید ؟

[
"ipinfo.io",
"iplocation.net",
"spotify.com",
"regexp:.*\\.ir$",
"ext:iran.dat:ir",
"ext:iran.dat:other",
"geosite:category-ir",
"geosite:category-gov-ir",
"geosite:category-news-ir",
"geosite:category-media-ir",
"geosite:category-social-media-ir",
"geosite:category-bank-ir",
"geosite:category-payment-ir",
"geosite:category-insurance-ir",
"geosite:category-education-ir",
"geosite:category-tech-ir",
"geosite:category-travel-ir",
"geosite:category-shopping-ir",
"geosite:category-scholar-ir",
"geosite:category-bourse-ir",
"geosite:category-forums-ir",
"geosite:category-ads",
"geosite:category-ads-all"
]
------------ 
geo files
هم از طریق پنل دانلود کردم ولی باز به همون مشکل بر میخورم!

**Comment by v7193m** [comment]
> > > مشکلی توی روتینگت نمی‌بینم. توصیه‌م اینه که blackhole رو برگردونی و رنج ایران رو بجای بلاک کردن، بندازی روی وارپ. یا access.log رو توی تنظیمات x-ray فعال کنی و با دستور tail -f /path/access.log | grep blocked ببینی چیا دارن بلاک می‌شن بجای blocked بنویسی WARP میتونی ببینی چیا می‌رن توی وارپ. مسیرشو یادم نیست جاش نوشتم path
> > 
> > 
> > ممنون بابت راهنماییت من Blackhole رو برگردوندم و ازون ور آی پی دامین هایی که بلاک کرده بودم رو درآوردم و خیلی عجیب که اوکی شد! این که گفتی آی پی هارو از وارپ بگذرون ، این کارو هم انجام دادم و کار میداد. ولی ی تست دیگه انجام دادم که مشکل رو پیدا کردم. ببین من توی پنل، به غیر از آی پی دامین های ایران، چین و روسیه هم بلاک کرده بودم. الان اومدم تست کردم، گفتم فقط از مال ایرانو بلاک کنم، تیک چین و روسیه نزدم و دیدم بلههههه، داره کار میده. فکر میکنم باگ ماجرا اینجا بود. حسین جان بی زحمت این باگ رو روی ورژن های بعدی اوکی کن. ممنون 🙏🏻
> 
> سلام جناب ببخشید منم همین مشکل رو دارم warp+ تهیه کردم میخواستم ترافیک های داخلی رو فقط .ir و بعضی دامین های خاص رو از وارپ عبور بدم ولی موقعه اعمال کردن شون تو بخش List of WARP Domains وضعیت status پنل ارور میخوره باید چیکار کنم میشه راهنمایی کنید ؟
> 
> ## [
> "ipinfo.io",
> "iplocation.net",
> "spotify.com",
> "regexp:.*\.ir$",
> "ext:iran.dat:ir",
> "ext:iran.dat:other",
> "geosite:category-ir",
> "geosite:category-gov-ir",
> "geosite:category-news-ir",
> "geosite:category-media-ir",
> "geosite:category-social-media-ir",
> "geosite:category-bank-ir",
> "geosite:category-payment-ir",
> "geosite:category-insurance-ir",
> "geosite:category-education-ir",
> "geosite:category-tech-ir",
> "geosite:category-travel-ir",
> "geosite:category-shopping-ir",
> "geosite:category-scholar-ir",
> "geosite:category-bourse-ir",
> "geosite:category-forums-ir",
> "geosite:category-ads",
> "geosite:category-ads-all"
> ]
> geo files هم از طریق پنل دانلود کردم ولی باز به همون مشکل بر میخورم!

شما wireproxy زدین یا wiregaurd ؟ الان چیزی که ما اینجا مطرح کردیم مشکل wiregaurd بود توی ورژن جدید

**Comment by sofiya-i** [comment]
> شما wireproxy زدین یا wiregaurd ؟ الان چیزی که ما اینجا مطرح کردیم مشکل wiregaurd بود توی ورژن جدید

برای من wireproxy هست مشکل رو برطرف کردم باید دو تا رول تعریف می شد و اینکه طبق گفته هاتون ( ببینی چیا دارن بلاک می‌شن بجای blocked بنویسی WARP میتونی ببینی چیا می‌رن توی وارپ }  بلاک ها رو وارپ کردم چنچ کردم وضعیت به حالت running برگشت . 
wiregaurd به چه صورته ؟ 
بهتره از wireproxy

**Comment by v7193m** [comment]
> > شما wireproxy زدین یا wiregaurd ؟ الان چیزی که ما اینجا مطرح کردیم مشکل wiregaurd بود توی ورژن جدید
> 
> برای من wireproxy هست مشکل رو برطرف کردم باید دو تا رول تعریف می شد و اینکه طبق گفته هاتون ( ببینی چیا دارن بلاک می‌شن بجای blocked بنویسی WARP میتونی ببینی چیا می‌رن توی وارپ } بلاک ها رو وارپ کردم چنچ کردم وضعیت به حالت running برگشت . wiregaurd به چه صورته ؟ بهتره از wireproxy

والا من قبلا wireproxy داشتم. اما چون دیگه درست عمل نمیکرد، مجبور شدم wiregaurd بزنم. از لحاظ اینکه کدوم بهتره، اون دوستمون گفت که wireproxy بهتره
