### ISSUE TITLE
Whatsapp

### ISSUE THREAD

**Issue by amirvp** [MHSanaei/3x-ui#1373]
سلام و ارادت
دوستان براتون پیش اومده یه کانفیگ داشته باشید با همه چی اوکی باشه ولی واتساپ رو خیلی کند باز کنه؟ یه سرور تانل شده دارم روی هتزنر 
اینستاگرام و تلگرام و همه چی رو عالی باز میکنه به جز واتساپ ، مشکل از چی میتونه باشه؟
ممنون

**Comment by cyberWar10ck** [comment]
تو ایفون اگه مشک داری v2box  رو نصب کن

**Comment by AliRahimiiii** [comment]
من با tls یا reality استفاده کردم مشکل رفع شد
