### ISSUE TITLE
Only IPV4 for outbound

### ISSUE THREAD

**Issue by amirvp** [MHSanaei/3x-ui#1375]
سلام وقت بخیر میشه پنل رو طوری تنظیم کرد که ورودی ipv6 داشته باشه ولی فقط با ipv4 به سایت ها و سرویس ها وصل بشه؟

**Comment by mer30hamid** [comment]
![image](https://github.com/MHSanaei/3x-ui/assets/1561497/0e28c35e-02a1-4858-b1af-262eca40fddb)


از قسمت Xray Configuration تنظیم Configure Strategy for Freedom Protocol رو بذار روی UseIPv4
