### ISSUE TITLE
Increased cpu usage percentage after added "access": "./access.log"

### ISSUE THREAD

**Issue by milad73n** [MHSanaei/3x-ui#1377]
### Welcome

- [x] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello and thanks for establishing and helping people to access the free internet.
I want to report a bug that causes cpu usage percentage to increased to nearly 100%.
When I added "access": "./access.log" to xray configuration that I can watch and limit ip users.

### Version of 3x-ui

<details>

```console
# v2.0.1
```

</details>

### x-ui log reports or xray log

s

**Comment by o0shahab0o** [comment]
سلام دوستان من مدتیه این مشکل رو دارم. 
من کانفیگ هام رو اهدا میکنم و این رو فقط فعال میکنم تا ببینم چند نفر به سرور متصل هستند. هدف اصلی اینه که لود سرور ها رو بتونم مدیریت کنم. این مشکل رو روی همه سرور ها نمیبینم . فقط برخی سرور ها اینجوری میشن. بعد دقت کردم روی این سرور ها تعداد ای پی ها از 200 بالاتر بره مشکل شروع میشه. مثلا تعداد ای پی روی 500 بشه دیگه سرور کار نمیکنه. حالا میرم Access log  رو که حذف میکنم به شرایط عادی بر میگرده. برای این که مطمین بشم ای پی ها درسته یه کد زدم و ip ها رو geolocate  کردم . همه ای پی ها ایران و تهران و بین همه اوپراتور ها به صورت نسبتا طبیعی پخش بودن. ضمنا ترافیک روی سرور نشون میده که بعیده این همه ای پی روی سرور متصل باشن. در کل که این شرایط خیلی با منطق جور در نمیاد. فعلا access log  رو از سرور هایی که ای پی زیاد دارن برداشتم. تا ببینم چی میشه.

**Comment by o0shahab0o** [comment]
I have deleted the access log @ /usr/local/x-ui/access.log
and it seems it works good now .

**Comment by MHSanaei** [comment]
Access log 
رو شما فقط زمانی باید داشته باشید که ای پی لیمیت روشن باشه در غیر این سورت بار اضافه روی سرور میندازه و نبودش خیلی بهتره برای همین در پیشفرش کانفیگ همون دکمه بازگشت به حالت اولیه که بزنید البته در اپدیت ۱.۷.۹ به بعد access log هم حذف میشه
و هرکی که ای پی لیمیت روشن داشته باشه ارور های لازم رو در logs میگیره

**Comment by samjj123** [comment]
منم این مشکل رو دارم سرور با cpu 2 core و ram 2 gig وقتی ایپی لیمیت فعال باشه و حدود ۱۰ کانفیگ انلاین باشن مصرف cpu لحظه ای به ۱۰۰ صد میره و دوباره بر میگرده .اگه نوتیف هشدار cpu ربات تلگرام روشن باشه هر دقیقه هشدار ۱۰۰ درصد میده 🤦‍♂️🤦‍♂️
این مشکل رو با چند تا سرور که امتحان کردم دیدم و همه اینجوری شدن و از نسخه ۱.۷.۹ به بالا اینجوری میشه 
سرورم اوبونتو ۲۲ هست

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
