### ISSUE TITLE
کار نکردن اتصال مستقیم به سایت های ایرانی

### ISSUE THREAD

**Issue by AliMajidi1** [MHSanaei/3x-ui#1382]
سلام
من از تانل دکو استفاده می کنم.
وقتی در پنل ایران گزینه های اتصال مستقیم به دامنه و ایپی های ایرانی را فعال میکنم، تاثیری نمی بینم و همچنان سایت های ایران اکسس باز نمی شوند.

**Comment by ali-cloudy** [comment]
ستون بنظرم من دکو رو بزار کنار بیا رو rtt 
Reverse tls tunnel
تست کن زمین تا آسمون فرقش میبینی هم دیتاسنتر ایرانت بهانه نداره برای بستن سرورت ک چرا پنل وی پی نصب کردی و هم نیاز ب نصب دوتا پنل و گرفتن جون و سرعت پکن هات زمانی که باید از ۳ تا گیت رد شن رو نمیکیری در اصل ۴ تا . ی بار ورودی پورت پنل ایران و چک کردن مقصد و سرور خارجی هم همینطور و باز گشت پکت هات موقعی که ب پنل ایرانت برمیگرده . دکو بد نیست ولی واقعا تو سرعت و حجم و پینگ و ... تاثیر مستقیم داره .

**Comment by ali-cloudy** [comment]
راجب پنل هم ۱.۷.۹ نصب کن چون این ورژن جدید خیلی باگ داره . فک کنم ی ماهی طول بکشه باگاش دربیاد و علیرضا جان بخواد برطرفش کنه .
