### ISSUE TITLE
Inbound "delete" API not working

### ISSUE THREAD

**Issue by vpnagency** [MHSanaei/3x-ui#1391]
### Welcome

- [x] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

api path: /panel/api/inbounds/del/{inboundId}

after calling API, I get 404 notfound

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by YuraSlobodenyuk** [comment]
Freaking moron its working why are you lying niggerman

**Comment by cmn13-86** [comment]
and
Client not being deleted:
http://{ip_server}:{port_server}/panel/api/inbounds/10/delClient/c584b57b-1eac-46e7-9bde-110217c67314
Error deleting client: 404

delete_url = f"http://{ip_server}:{port_server}/panel/api/inbounds/{inbound_id}/delClient/{client_id}"
print(delete_url)
headers = {'Accept': 'application/json'}
