### ISSUE TITLE
xray无法运行

### ISSUE THREAD

**Issue by bian2022** [MHSanaei/3x-ui#1395]
xui报错
2023/12/16 15:12:36 WARNING - X-UI: get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:20099: connect: connection refused"

xray配置文件
"inbounds": [
    {
      "tag": "api",
      "listen": "127.0.0.1",
      "port": 20099,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      }
    }
  ],

有什么解决办法吗？

**Comment by roman1gan** [comment]
The inbound api must be first in the list of routing rules
