### ISSUE TITLE
عدم نمایش لیست کاربران

### ISSUE THREAD

**Issue by AliHemmati79** [MHSanaei/3x-ui#1397]
سلام چند روزیه لیست کاربران برام نمایش داده نمیشه، با آپدیت و حذف و نصب مجدد هم مشکل برطرف نشد
بنظرتون مشکل از چی میتونه باشه؟

![1](https://github.com/MHSanaei/3x-ui/assets/99415271/1f27a0d8-5c6d-43d0-8c97-009e3f3215fb)

این قسمت باگ خورده و همش میچرخه چطور باید رفعش کرد؟

https://github.com/MHSanaei/3x-ui/assets/99415271/bc6abf55-0fe1-4deb-b9c0-8c0485176eac

**Comment by AliHemmati79** [comment]
![1](https://github.com/MHSanaei/3x-ui/assets/99415271/b6fb1175-57f2-47e9-8962-2091a48b7826)

**Comment by mohi18217** [comment]
منم همین مشکل رو خوردم . فیلتر رو روشن کنی بری رو قسمت های دیگه و برگردی میاد. اما باز همه اینباند هارو نمیاره. درصورتی که تو دیتابیس هست. لطفا رسیدگی کنید

**Comment by MHSanaei** [comment]
دیتابیس شما بگا داره باید ادیت کنید و مشکلش رو‌برطرف کنید

**Comment by AliHemmati79** [comment]
> منم همین مشکل رو خوردم . فیلتر رو روشن کنی بری رو قسمت های دیگه و برگردی میاد. اما باز همه اینباند هارو نمیاره. درصورتی که تو دیتابیس هست. لطفا رسیدگی کنید

آره برا منم ۳ اینباند آخری نشون نمیداد، بعد سه روز تلاش تونستم مشکلش پیدا کنم الان درست شده

**Comment by AliHemmati79** [comment]
> دیتابیس شما باگ داره باید ادیت کنید و مشکلش رو‌برطرف کنید

بله مشکل بر طرف شده، فقط برای ادیت دیتابیس از چه برنامه استفاده کنیم بهتره؟
من از DB Browser(SqlLite) استفاده کردم ولی اینباند هارو ادیت میکردم خطای کلید اصلی میداد و مینوشت فایل اصلی هست نمیشه ویرایش یا حذف کرد، شانسی اون اینباندی که مشکل داشت حذف شد‌.

**Comment by mohi18217** [comment]
> دیتابیس شما باگ داره باید ادیت کنید و مشکلش رو‌برطرف کنید

اصلا دیتا بیس رو کاری نکردم. فقط اپدیت کردم و چند تا اینباند دادم که external proxy دادم چون تانله دیگه نخوام دستی تغییر بدم. الان همونارو نمیاره
