### ISSUE TITLE
مشکل قطعی چند ثانیه ای کانفیگ تانل

### ISSUE THREAD

**Issue by JackyJack212** [MHSanaei/3x-ui#1402]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

من سرور ایران ای دارم که با کانفیگ vmess + tcp + http به سرور خارج به صورت پنل به پنل تانل شده و کانفیگ نهایی استفاده از تانل هم به صورت vmess + tcp + http هستش ،
اما یک هفته ای میشه که در حین استفاده از کانفیگ 10 تا 20 ثانیه اتصال قطع میشه و دوباره برقرار میشه و داخل لاگ هم اصلا مشکلی نیست و حتی پنل هم ری استارت نشده.

اقدامات متفاوتی هم روی این سرور برای بهبودش تست کردم مثل عوض کردن سرور خارج، تغییر header http و... اما مشکل برطرف نشد.
سرور ایران هم از سلامت کامل برخورداره و همچنین سرعت مناسبی ارائه میده.

لطفا راهنمایی کنید...

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by neon-bartmoss** [comment]
منم همین مشکل رو دارم 
با این تفاوت که من vless استفاده میکنم
