### ISSUE TITLE
پارس پک

### ISSUE THREAD

**Issue by mahdi-alone99** [MHSanaei/3x-ui#1404]
من می خواهم از CDN پارس پک استفاده کنم امکانش هست راهنمایی کنید؟
آیا کسی هست تا حالا استفاده کرده باشه و بدونه چطور باید از اون استفاده کنم؟
آیا مانند کلود فلر فقط بعضی از پورت ها آزاد هست یا نه؟

**Comment by imanmahdavi** [comment]
پارک پک اسمش CDN هست و برای توسعه محتوایی استفاده میشه. از پروتکل WS استفاده نمی کنه و برای استفاده از سرویس های مد نظر شما انتخاب درستی نیست.
