### ISSUE TITLE
عدم نمایش کابران و ایجاد اینباند جدید

### ISSUE THREAD

**Issue by AliHemmati79** [MHSanaei/3x-ui#1406]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام چند روزی هست که قسمت اینباند ریفرش نمیشه و فقط میچرخه، وقتی به قسمت جستجو میرم اینباند هارو نشون میده ولی کامل نه و نمیشه اینباند جدیدی ساخت برای اینباند های فعلی هم میشه تغییرات انجام داد ولی در لحظه اعمال نمیشه دوباره باید صفحه رو ریفرش کنم
 لطفا راهنمایی کنید تا مشکل پیدا کنم!!!

https://github.com/MHSanaei/3x-ui/assets/99415271/43639083-ad1f-4fe3-828b-ab74da00db62

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by mohi18217** [comment]
منم بعد اپدیت به 2 این بلا سرم اومد. چند تا اینباند رو نشون نمیده کلا. ولی تو دیتابیس هست

**Comment by AliHemmati79** [comment]
> منم بعد اپدیت به 2 این بلا سرم اومد. چند تا اینباند رو نشون نمیده کلا. ولی تو دیتابیس هست

احتمالا یکی از اینباند هایی که نشون نمیده داخلش هیچ کلاینتی وجود نداره برای من مشکلش همین بود، بعد کلی کلنجار رفتن با کمک علیرضا تونستم درستش کنم 
اگه به راهنمایی نیاز داری تلگرام بهم پیام بده: Ali_H_79
