### ISSUE TITLE
منفی شدن روزهای باقیمانده اشتراک کاربران بعد از آپدیت به نسخه ۲ در ساب

### ISSUE THREAD

**Issue by razidvb** [MHSanaei/3x-ui#1410]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

**سلام ؛ 
من از طریق ساب به کاربرهام سرویس میدم .
پس از آپدیت از ۱.۷.۹  به نسخه ۲ یا ۲.۱ 
بعد از اپدیت زدن ساب سمت کلاینتها ؛ کلیه سابهای کاربران  باقی مانده روزهای اشتراک منفی میشه و عملا کانفیگها غیر قابل استفاده میشه برای کاربران .
لطفا بررسی فرمایید** 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by ramtiny** [comment]
لطفاً بیشتر توضیح میدید؟
