### ISSUE TITLE
ساخت یک کاربر با چند کانفیگ و محاسبه مصرف مجموع کانفیگ ها 

### ISSUE THREAD

**Issue by ali-sorury** [MHSanaei/3x-ui#1411]
سلام آیا میشه یک کاربر با چند کانفیگ ساخت و مصرف ترافیک مجموعشون رو نشون بده آیا امکانشو داره

**Comment by wulfric93** [comment]
خیر این پنل و پنل علیرضا تا به حال این امکان فراهم نبوده

**Comment by MHSanaei** [comment]
خیر امکانش نیست

**Comment by peysol** [comment]
من الان این پست رو پیدا کردم، فکر می کنم با این بتونی کاری که گفتی رو انجام بدی
https://github.com/MHSanaei/3x-ui/pull/1454
