### ISSUE TITLE
دکمه ی کپی سریع کانفیگ (مخصوصا برای موبایل)

### ISSUE THREAD

**Issue by mossyasa** [MHSanaei/3x-ui#1420]
سلام و با عرض خسته نباشید.. تو اپدیت جدید برای کپی کردن کانفیگ یه کلیک اضافه تر شده تو گوشی..
تقاضا دارم هم برای ویندوز هم موبایل  دکمه ی کپی سریع کانفیگ قرار بدین اقای سنایی عزیز

**Comment by solidwar** [comment]
به نظرم حتی اگه بعد از ساختن خودش کپی بشه برامون میتونه گزینه ی خوبی باشه برای آپدیت پیش رو
