### ISSUE TITLE
Error deleting client: 404 v2.0.2

### ISSUE THREAD

**Issue by cmn13-86** [MHSanaei/3x-ui#1427]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Client not being deleted:
http://{ip_server}:{port_server}/panel/api/inbounds/10/delClient/c584b57b-1eac-46e7-9bde-110217c67314
Error deleting client: 404

delete_url = f"http://{ip_server}:{port_server}/panel/api/inbounds/{inbound_id}/delClient/{client_id}"
    print(delete_url)
    headers = {'Accept': 'application/json'}

    async with aiohttp.ClientSession() as session:
        async with session.post(delete_url, headers=headers) as response:
            if response.status == 200:
                data = await response.json()
                print(f"Client deletion response: {data}")
            else:
                print(f"Error deleting client: {response.status}")

### Version of 3x-ui

<details>

```console
3X: [v2.0.2]
```

</details>

### x-ui log reports or xray log

<details>

Xray: v1.8.6
# paste log here
```

</details>

**Comment by Arman-nsb** [comment]
Hello,
Have you sent a POST request to the login endpoint before that?
You must save the "session" cookie in the response header of /login endpoint and add it to the request header for other endpoint calls.
