### ISSUE TITLE
how to reset admin password

### ISSUE THREAD

**Issue by somehow22** [MHSanaei/3x-ui#1431]
after installation, I forgot the admin password unfortuanately... but I cannot afford to delete db and start all over again.

**Comment by Arman-nsb** [comment]
SSH into your VPS, type "x-ui" and enter 4 to reset credentials.

**Comment by danialafshari** [comment]
no need to delete anything
ssh into vps type "x-ui" and enter 7 for 7. View Current Panel Settings
and you can show username-password and panel port

**Comment by shurrman** [comment]
Latest docker version says panel is not installed, however the panel is running!
And no way to see current settings
`yourhostname:/app# x-ui
The OS release is: alpine

  3X-ui Panel Management Script
  0. Exit Script
————————————————
  1. Install
  2. Update
  3. Custom Version
  4. Uninstall
————————————————
  5. Reset Username & Password & Secret Token
  6. Reset Settings
  7. Change Port
  8. View Current Settings
————————————————
  9. Start
  10. Stop
  11. Restart
  12. Check Status
  13. Check Logs
————————————————
  14. Enable Autostart
  15. Disable Autostart
————————————————
  16. SSL Certificate Management
  17. Cloudflare SSL Certificate
  18. IP Limit Management
  19. WARP Management
————————————————
  20. Enable BBR 
  21. Update Geo Files
  22. Active Firewall and open ports
  23. Speedtest by Ookla

Panel state: Not Installed
xray state: Running

Please enter your selection [0-23]: 8

[ERR] Please install the panel first 

Press enter to return to the main menu: `

**Comment by mitsukuri** [comment]
@shurrman +1, can't reset panel credentials in Docker for the same reason. And simply copying the db from x-ui (not 3x-ui!) seems to break the credentials as well.

**Comment by mit-ax** [comment]
I also forgot my password and can view it in sqlite database, it is stored as plain text without hash
```shell
# install sqlite3
apt update -y && apt install -y sqlite3
# open it
sqlite3 ./x-ui.db
```
```sql
select * from users;
```

**Comment by VvV-OoO** [comment]
> Latest docker version says panel is not installed, however the panel is running! And no way to see current settings `yourhostname:/app# x-ui The OS release is: alpine
> 
> 3X-ui Panel Management Script 0. Exit Script ————————————————
> 
> 1. Install
> 2. Update
> 3. Custom Version
> 4. Uninstall
>    ————————————————
> 5. Reset Username & Password & Secret Token
> 6. Reset Settings
> 7. Change Port
> 8. View Current Settings
>    ————————————————
> 9. Start
> 10. Stop
> 11. Restart
> 12. Check Status
> 13. Check Logs
>     ————————————————
> 14. Enable Autostart
> 15. Disable Autostart
>     ————————————————
> 16. SSL Certificate Management
> 17. Cloudflare SSL Certificate
> 18. IP Limit Management
> 19. WARP Management
>     ————————————————
> 20. Enable BBR
> 21. Update Geo Files
> 22. Active Firewall and open ports
> 23. Speedtest by Ookla
> 
> Panel state: Not Installed xray state: Running
> 
> Please enter your selection [0-23]: 8
> 
> [ERR] Please install the panel first
> 
> Press enter to return to the main menu: `

exactly the same problem

**Comment by hrijabul622-creator** [comment]
https://github.com/MHSanaei/3x-ui/issues/1431
