### ISSUE TITLE
Sub limited

### ISSUE THREAD

**Issue by Parsam1989** [MHSanaei/3x-ui#1436]
سلام و خسته نباشید
ممنون از زحمات شما در ارتقا پنل x ui
میخواستم ی پیشنهاد بدم
در واقع توی اختلات مجبور شدم از ای پی تمیز همراه اول استفاده کنم
و به مشتری ها بدم
مشکل اینجا بود بعضی مشتری ها میخوان هم از وای فای استفاده کنن و هم همراه اول
و اینحا مجبور به دادن دوتا کانفیگ هستیم
و اگر بخوایم محدودیت حجم بذاریم امکانش نیست
تقسیم هم کنیم ممکنه یکی کمتر مصرف داشته باشه
میخواستم بگم آیا امکانش هست واسه یک سابسکرایب بشه حجم تعیین کرد
مثلا ساب تعیین میکنم Reza 
برای رضا محدودیت حجم بذارم و تاریخ یا حتی محدودیت آی پی
مثلا حجم ۳۰ گیگ
بعد هر تعداد کانکشن با ساب Reza  باشه مجموع استفاده بشه ۳۰ قطع بشن همه کانفیگ ها
آیا امکانش هست ؟

**Comment by hrasoul2** [comment]
قابلیت multi protocol که تو این ورژن دادن واسه همینه 
با ساب یکسان حجم ها همه با هم حساب میشه
دستور x-ui رو سرور بزنید گزینشو میبینید
