### ISSUE TITLE
تغییر آی پی پنل در سرور هتزنر

### ISSUE THREAD

**Issue by amirmat98** [MHSanaei/3x-ui#144]
باسلام. بعد از تغییر آی پی در سرور هتزنر، برای دسترسی به پنل باید چگونه اقدام کرد؟
پنل روی سرور فعال هست ولی ip عوض شده و امکان دسترسی نیست.

**Comment by ImanIranNejad** [comment]
عزیز شما ای پی جدیدتو بذار دقیقا جای ای پی قبلیت توی مرورگر توی کامنت بالا دوستمون قشنگ توضیح دادن که.اگه بازم دسترسی نداشتی چک کن ببین سرورت اصلا ران هست یا پینگ ای پی جدیدتو بگیر ببین بهت پینگ میده. اگه پینگ میده با وی پی ان هم چک کن پنل رو ببین میاره

**Comment by amirmat98** [comment]
درست شدش.
خیلی ممنونم
