### ISSUE TITLE
Warp problem مشکل وارپ

### ISSUE THREAD

**Issue by AminB3DA** [MHSanaei/3x-ui#1440]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽

مشکل توی نصب وارپ دارم و اون زمانی هم که نصب بود و chatGPT رو روشن میکردم سایت openai کلا بالا نمیومد

این ارور را میده

![image](https://github.com/MHSanaei/3x-ui/assets/127662487/309a0cb7-bd99-457b-9d9e-be92ead67995)

و از دستور warp u و... هم که استفاده میکنم هیچی نمینویسه
از منو خود پنل گزینه 18 را که میزنم اگر بجز نصب شماره 2 یا... بزنم میگه فایلی تو این مسیر نیست

قسمت list of warp domain هم رفته توی آپدیت آخر
ممنون میشم دقیق راهنمایی کنید

### Version of 3x-ui

<details>

```console
2.0.2
```

</details>

### x-ui log reports or xray log

<details>

```console
  [ERROR] There was an error during the installation of essential packages!
  Please check your connection or try again late
```

</details>

**Comment by feridj2020** [comment]
ufw >>disable

**Comment by AminB3DA** [comment]
فایروال هم disable کردم اما نشد. کلا سرور رو reinstall کردم اوکی شد. اما نمیدونم بازم چجوری سایتایی ک میخوام وارپ شه کاستوم کنم

**Comment by feridj2020** [comment]
به نظرم از warp رایگان استفاده نکن فقط اگه اکانت پولی داری فعال کن چون بعد یه مدت به یه ترافیک خاصی میرسه کار نمیکنه
