### ISSUE TITLE
user pass in docker

### ISSUE THREAD

**Issue by apptester23** [MHSanaei/3x-ui#1446]
How can I set user pass in docker as a volume?

**Comment by gallexy** [comment]
same problem, need to change the username/password sometimes especially when I forget the password.

**Comment by doivjpxx** [comment]
please try to input
user: admin
password: admin
I just tried it and got login into panel

**Comment by forrany** [comment]
> please try to input user: admin password: admin I just tried it and got login into panel

Yes, it works!!!

**Comment by Winand** [comment]
I'd like to change admin/admin credentials
