### ISSUE TITLE
what are the path i need to add in xtls Private Key Path, Public Key Path ?

### ISSUE THREAD

**Issue by Sineththaruna001** [MHSanaei/3x-ui#1447]
no any files like /root/private.key , /root/cert.crt in x-ui how i configure xtls 
How i need to set up xtls for vless without reality
![Screenshot 2023-12-25 172202](https://github.com/MHSanaei/3x-ui/assets/124179384/fed6a36f-ccad-4a63-914b-db1fd9753248)

**Comment by Arman-nsb** [comment]
XTLS is deprecated, Nonetheless, You should set your domain's full-chain and private key file paths.
You can use option 16 of "x-ui" menu in the terminal to generate a new certificate for your domain.

**Comment by danialafshari** [comment]
Yes exists
you must go following path:

/etc/letsencrypt/live/YourDomain/fullchain.pem
/etc/letsencrypt/live/YourDomain/privkey.pem
