### ISSUE TITLE
کمک برای استفاده از ip limit

### ISSUE THREAD

**Issue by gapochat** [MHSanaei/3x-ui#1450]
سلام 
آموزشی وجود داره یا کسی میتونه توضیح بده چه کارایی باید انجام بدم برای استفاده از این قابلیت. fail2ban نصب کردم ولی ظاهرا کار های دیگه ای هم داره

**Comment by danialafshari** [comment]
اگه قرار باشه کار کنه طبق دستور خود سنایی هست:
Note: IP Limit won't work correctly when using IP Tunnel

For versions up to v1.6.1:

IP limit is built-in into the panel.
For versions v1.7.0 and newer:

To make IP Limit work properly, you need to install fail2ban and its required files by following these steps:

Use the x-ui command inside the shell.
Select IP Limit Management.
Choose the appropriate options based on your needs.
make sure you have access.log on your Xray Configuration

  "log": {
  "loglevel": "warning",
  "access": "./access.log",
  "error": "./error.log"
  },

**Comment by gapochat** [comment]
مرسی از کمکت

> اگه قرار باشه کار کنه طبق دستور خود سنایی هست: Note: IP Limit won't work correctly when using IP Tunnel
> 
> For versions up to v1.6.1:
> 
> IP limit is built-in into the panel. For versions v1.7.0 and newer:
> 
> To make IP Limit work properly, you need to install fail2ban and its required files by following these steps:
> 
> Use the x-ui command inside the shell. Select IP Limit Management. Choose the appropriate options based on your needs. make sure you have access.log on your Xray Configuration
> 
> "log": { "loglevel": "warning", "access": "./access.log", "error": "./error.log" },



مرسی از کمکت. 
آخرین ورژن هستم. 
کد رو هم اضافه کردم به
xray setting> advanced template  > all

"log": {
    "loglevel": "warning",
    "access": "./access.log",
    "error": "./error.log"
  },

ممنون

**Comment by hrasoul2** [comment]
بستگی داره چه مدلی انجام داده باشی
اگه سرور خارج هستش مستقیم با همین کد ها باید کار کنه
و اگه سرور تانل داری اون راهکار دیگه ای داره تا ایپی لیمیت کار کنه

**Comment by salarfargithub** [comment]
مشکل IP limit رو منم دارم .
سرور تانل دارم استفاده میکنم از روش RTT (Revers tls tunnel)

**Comment by hrasoul2** [comment]
این روشی که شما تانل کردی  RTT این هم میشه که ایپی لیمیت رو روش فعال کرد
اما یکم سخت تره
ولی اگه سرور خارجتون تو سرور ایران فیلتر نیس بهتره که تانل رو به صورت پنل به پنل انجام بدید

باز اگه مشکلی بود تلگرام پیام بدید 
@denras3
