### ISSUE TITLE
سرعت پایین دانلود و آپلود در ساعات خاص

### ISSUE THREAD

**Issue by omrani77** [MHSanaei/3x-ui#1452]
سلام بچه ها . آقا من سرور وی تو ریم یه مشکلی داره . اکثر اوقات سرعتش خوبه و جوابه اما به یه ساعت های خاصی میرسه مثلا آخر شب ها سرعت خیلی پایین ( در حد 0.05 مگ ) و کمتر میرسه . مشکل کجاست ؟ راهکاری برای حلش دارید ؟

**Comment by Miladr9800** [comment]
سلام
مشکل در ای پیه نه پنل
