### ISSUE TITLE
کاهش حجم دیتابیس

### ISSUE THREAD

**Issue by m484r** [MHSanaei/3x-ui#1455]
سلام وقت بخیر
بعد از اینکه یوزرها منقضی شدن با حذف اونا حجم دیتابیس کم نمیشه و یه جورایی اون uuid ها و اطلاعاتش در دیتابیس باقی میمونه که باعث سنگینی دیتابیس میشه
راه حلی برای این مشکل هستش ؟
بنده راهکاری که الان استفاده میکنم اینه که هر ماه پنل رو کامل حذف و مجدد نصب میکنم

**Comment by Arman-nsb** [comment]
سلام،
راهکار بهترش اینه یکبار پنل رو update کنید. حین آپدیت یک مرحله database migration صورت میگیره که فیلدهای بلااستفاده رو حذف میکنه. (مهم نیست ورژن جدید اومده باشه یا نه، این فرآیند درهرصورت اجرا میشه)

**Comment by m484r** [comment]
> سلام، راهکار بهترش اینه یکبار پنل رو update کنید. حین آپدیت یک مرحله database migration صورت میگیره که فیلدهای بلااستفاده رو حذف میکنه. (مهم نیست ورژن جدید اومده باشه یا نه، این فرآیند درهرصورت اجرا میشه)



متاسفانه با اینکار هم حل نشد
