### ISSUE TITLE
ip Direct

### ISSUE THREAD

**Issue by BloOoDyMiR** [MHSanaei/3x-ui#1462]
Does anyone know how ip Direct option work ? i cant use it

**Comment by danialafshari** [comment]
برا منم کار نمیکنه وقتی وارد سایت p30downlod  شدم پایینش ip سرورم رو زد!

**Comment by rahman8521** [comment]
واسه تانل کار میکنه . سرور ایران اعمال بشه . دایرکت اوکی میشه

**Comment by BloOoDyMiR** [comment]
Dokodemo کار نمیکنه؟

**Comment by neerro** [comment]
Dokodemo works for api only as I understood correct.
