### ISSUE TITLE
[x-ui.service: failed with result exit-code]

### ISSUE THREAD

**Issue by ahmadipiralvan** [MHSanaei/3x-ui#1465]
### Description
Hi dears,
I noticed the xray core stops and restarts from time to time.
This problem is annoying and may happen many times during the day.
We need to find the problem.

> 
> سلام عزیزان
> من متوجه شدم که هسته xray هر از گاهی متوقف می شود و دوباره راه اندازی می شود.
> این مشکل آزار دهنده است و ممکن است بارها در طول روز اتفاق بیفتد.
> ما باید مشکل را پیدا کنیم.

### Version
`3X: v2.0.2 - Xray: v1.8.6`

### Logs
```
Log level: Notice

Dec 27 02:16:06 localhost systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

Dec 27 02:16:06 localhost systemd[1]: x-ui.service: Killing process 14390 (xray-linux-amd6) with signal SIGKILL.

Dec 27 02:16:06 localhost systemd[1]: x-ui.service: Failed with result 'exit-code'.

Dec 27 02:16:06 localhost systemd[1]: x-ui.service: Consumed 35min 4.172s CPU time.
```

**Comment by neerro** [comment]
Try going to Xray settings and Reset configuration by Default. It should solve the problem.

**Comment by ahmadipiralvan** [comment]
> Try going to Xray settings and Reset configuration by Default. It should solve the problem.

It's just erasing the problem, not solving the problem!

**Comment by neerro** [comment]
> I noticed the xray core stops and restarts from time to time.
> This problem is annoying and may happen many times during the day.

I have not this problem at all on no one of my instance. You have to check your instance deeply as this not the pannel issue as I can see.

**Comment by ahmadipiralvan** [comment]
> > I noticed the xray core stops and restarts from time to time.
> > This problem is annoying and may happen many times during the day.
> 
> I have not this problem at all no one of my instance. You have to check your instance deeply as this not the pannel issue as I can see.

Yes, exactly. The problem is in the xray core.
I have also reported it on xray.
This problem seems to happen in high traffic and relatively high load.
I have several servers and they all have the same problem.

**Comment by neerro** [comment]
> Yes, exactly. The problem is in the xray core.
> I have also reported it on xray.
> This problem seems to happen in high traffic and relatively high load.
> I have several servers and they all have the same problem.

I suppose you need widely explain the situation and parameters (as xray/panel/inbound type/how many users/how many inbounds on your instance etc.) the issue happens. 
Maybe you are using IP Limits option, or anything else as additional option and its setup goes to system overload.

**Comment by ahmadipiralvan** [comment]
> > Yes, exactly. The problem is in the xray core.
> > I have also reported it on xray.
> > This problem seems to happen in high traffic and relatively high load.
> > I have several servers and they all have the same problem.
> 
> I suppose you need widely explain the situation and parameters (as xray/panel/inbound type/how many users/how many inbounds on your instance etc.) the issue happens. Maybe you are using IP Limits option, or anything else as additional option and its setup goes to system overload.

Yes that's right. I don't use IP Limit. But I use Reverse.
I also have roles in routing.
Investigating this problem seems to require access to the deep log in the kernel.
