### ISSUE TITLE
عبور فقط سایت های ایرانی از وارپ در ورژن جدید

### ISSUE THREAD

**Issue by rezairp** [MHSanaei/3x-ui#1466]
سلام دوستان گرامی
توی ورژن جدید با توجه به تغییر شکل تنظیمات آیا برای اضافه کردن سایت های ایرانی به وارپ از طریق تب routing rules چجوری میشه سایت های ایرانی رو اضافه کرد؟ یا باید فقط از طریق outbound اضافه بشوند؟ ممنون میشم راهنمایی کنید

**Comment by rahman8521** [comment]
شما اول بزن ایپیا ایران بن بشن . 
بعد برید تب روتینگ . رول ایپی رو ادیت کنید . بجایه blocked بزار WARP
