### ISSUE TITLE
ایجاد لود بالانس در حالت تانل outbound پنل به پنل 

### ISSUE THREAD

**Issue by kalilovers** [MHSanaei/3x-ui#1468]
سلام وقت بخیر قبلا یه روشی بود که میشد در تانل پنل به پنل outbound از چند سرور خارج هدف استفاده کرد . الان یادم رفته اون تاپیک رو هم ندارم کسی بلده روشش رو ؟

**Comment by MAsterhadi** [comment]
https://t.me/panel3xui/65
این لینکش

**Comment by kalilovers** [comment]
> https://t.me/panel3xui/65
> این لینکش

ممنون خود تانل رو میتونم بزنم ، منظورم اینه چندتا خارج بدیم بهش ، اینو میخوام روششو

**Comment by hrasoul2** [comment]
یکم سخته...اما با reverse proxy میتونی اینکارو بکنی
البته خودت باید کد هاشو بزنی 
اگه خاستی من در خدمتم انجام بدم
@denras3

**Comment by kalilovers** [comment]
> یکم سخته...اما با reverse proxy میتونی اینکارو بکنی
> البته خودت باید کد هاشو بزنی 
> اگه خاستی من در خدمتم انجام بدم
> @denras3

با ریورس انجام دادم خودم ، کلا تانل های ریورس مناسب نیست ، برای همین میخوام تو اوتباند انجام بدم ممنون میشم راهنمایی کنی تو گیت هاب اگر میتونی

**Comment by MAsterhadi** [comment]
این باند این امکانو نداره

**Comment by kalilovers** [comment]
> این باند این امکانو نداره

اینی که دوستمون فرستاد میگه که امکانش هست ، فقط میخوام بدونم دقیقا چطور ، از بالانس استفاده میشه
