### ISSUE TITLE
در ایباند و در حالت ریلیتی امکان دادن دومین نیست

### ISSUE THREAD

**Issue by Cyrus-of-Persia** [MHSanaei/3x-ui#1471]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

در وروژن 2.02 در هنگام ساخت ایباند و در حالت ریلیتی امکان دادن دومین نیست و وقتی کانفیگ ساخته می شود، دومین پنل داخلش ایمپورت میشه.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Cyrus-of-Persia** [comment]
مشکل به این دلیل است که بعد از آپدیت به ورژن 2.02، پنل آدرس لینک سابسکریپشن را به جای آدرس دومین در همه کانفیگ های اینباند قرار می دهد و چون جا ندارد امکان تغییر به آدرس دومین دلخواه برای کانفیگ های ریلیتی نیست. یعنی نمی توان د.مین و sni دلخواه داد.

**Comment by MHSanaei** [comment]
External proxy 
استفاده کنید

**Comment by Cyrus-of-Persia** [comment]
ممنون از شما. چک می کنم
