### ISSUE TITLE
Usage of users don't update in version 2.0.2

### ISSUE THREAD

**Issue by nickmehrdad1** [MHSanaei/3x-ui#1474]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

After updating to latest version, usage of new clients that create in any inbounds don't update (their accounts working properly)
could you please help to fix this problem?

### Version of 3x-ui

<details>

```console
2.0.2
```

</details>

### x-ui log reports or xray log

<details>

```console

```

</details>

**Comment by MHSanaei** [comment]
Click on reset to default configuration
Save and restart

**Comment by nickmehrdad1** [comment]
Thanks

I did this
It happen when I route all for my inbounds traffic through warp,
I added this 

`{
        "type": "field",
        "network": "tcp",
        "outboundTag": "WARP"
      }`

and it happen again.
I used this in older versions
