### ISSUE TITLE
مشکل ذخیره نشدن ادرس ریکوست هدر 

### ISSUE THREAD

**Issue by Lion0098** [MHSanaei/3x-ui#1475]
سلام 
تو ورژن ۲ به بالا وقتی کانفینگ مدل 
Vless+tcp+heder(on)
میزنم ادرس سایتی که هدرRequest header وارد میکنم بعد از ذخیره تغییرات ذخیره نمیشه (وقتی کانفینگ ویرایش میژنی اصلا قسمت HTTP Camouflage تیکش روشن هست ولی ادرس سایت Request header پاک میشه سیو نمیشه)
برای رفع این مشکل باید چیکار کنیم هرکار کردم نشد

**Comment by MHSanaei** [comment]
Name ro host bezarid

**Comment by Lion0098** [comment]
ممنون مهندس
بابت راهنمایتون تشکر
