### ISSUE TITLE
Routing Spotify through warp in the label's settings doesn't work.

### ISSUE THREAD

**Issue by Amin2460** [MHSanaei/3x-ui#1479]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

من از طریق همون اسکریپت wireproxy رو نصب کردم، واسه بقیه سایت ها کار می‌کنه. ولی تیک گذراندن اسپاتیفای از وارپ رو توی پنل فعال میکنم، کار نمیکنه. یچیز دیگه رو تست کردم، اگه کل سرور رو از وارپ بگذرونم اسپاتیفای بدون هیچ مشکلی کار می‌کنه. پس اینجا مشکل از تنظیمات پنله که اسپاتیفای رو بصورت کامل نمیگذرونه از وارپ. لطفا بررسی کنید خیلی وقته درگیر این موضوعم

### Version of 3x-ui

2.0.2

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Shm9220** [comment]
دهن من رو هم سرویس کرده اسپاتیفایش . یه مدت کار میکرد با ربات وارپ پلاس ولی دوباره از کار افتاده در حالیکه بقیه رول های وارپ اوکی اند. یه مشکلی داره اونم اینه که مثلا من توی رول هام اومدم سایت iplocation.net رو اد کردم که ببینم وقتی از وارپ رد میشه چه ip ای میده . با این حال یبار آی پی کلودع
فلری که مربوط به وارپ کلود فلره میده یبار ip خود سرورم رو میده. عکسارو ببینید 
![Screenshot_20240322-193256_Chrome](https://github.com/MHSanaei/3x-ui/assets/130503936/8e10fe65-1e35-4c0d-bd7c-09d8d8648800)
![Uploading Screenshot_20240322-
![Screenshot_20240322-193738_Chrome](https://github.com/MHSanaei/3x-ui/assets/130503936/84978f79-d71c-44b1-b9ca-e042c9d98849)
![Screenshot_20240322-194058_Chrome](https://github.com/MHSanaei/3x-ui/assets/130503936/c80bd3c9-666d-4f53-8d86-b22b1b609f3e)
193511_Spotify.jpg…]()

**Comment by Shm9220** [comment]
دهن من رو هم سرویس کرده اسپاتیفایش . یه مدت کار میکرد با ربات وارپ پلاس ولی دوباره از کار افتاده در حالیکه بقیه رول های وارپ اوکی اند. یه مشکلی داره اونم اینه که مثلا من توی رول هام اومدم سایت iplocation.net رو اد کردم که ببینم وقتی از وارپ رد میشه چه ip ای میده . با این حال یبار آی پی کلودع
فلری که مربوط به وارپ کلود فلره میده یبار ip خود سرورم رو میده. عکسارو ببینید

**Comment by Shm9220** [comment]
![Uploading Screenshot_20240322-194058_Chrome.jpg…]()

**Comment by Shm9220** [comment]
![Uploading Screenshot_20240322-194058_Chrome.jpg…]()

**Comment by Shm9220** [comment]
![Uploading Screenshot_20240322-194058_Chrome.jpg…]()

**Comment by Shm9220** [comment]
![Uploading Screenshot_20240322-194058_Chrome.jpg…]()

**Comment by Shm9220** [comment]
![Uploading Screenshot_20240322-193738_Chrome.jpg…]()

**Comment by Shm9220** [comment]
![Screenshot_20240322-194058_Chrome](https://github.com/MHSanaei/3x-ui/assets/130503936/62f35009-330b-40de-861f-dcf0a9ec0683)
@
![Screenshot_20240322-193738_Chrome](https://github.com/MHSanaei/3x-ui/assets/130503936/19d4a8a9-2ba3-4178-93a9-ff4d46a95695)
![Screenshot_20240322-193511_Spotify](https://github.com/MHSanaei/3x-ui/assets/130503936/a2d2b2ea-1132-49d0-a3c1-9c706e07da20)
![Screenshot_20240322-193433_Spotify](https://github.com/MHSanaei/3x-ui/assets/130503936/2cd21352-7496-4950-9ed3-fe208b956d1b)
![Screenshot_20240322-193256_Chrome](https://github.com/MHSanaei/3x-ui/assets/130503936/8d41b28c-9d5d-4f4c-a312-eb256a2711b8)

**Comment by Shm9220** [comment]
منم تست کردم وقتی توی اوت باند warp رو میارم اولین گزینه همه چی درست میشه . 

![Screenshot_20240323-045516_Chrome](https://github.com/MHSanaei/3x-ui/assets/130503936/1ccbb010-5e86-4272-a71a-5f1c8ffce33e)

**Comment by pouriasharifzad** [comment]
> منم تست کردم وقتی توی اوت باند warp رو میارم اولین گزینه همه چی درست میشه .
> 
> ![Screenshot_20240323-045516_Chrome](https://github.com/MHSanaei/3x-ui/assets/130503936/1ccbb010-5e86-4272-a71a-5f1c8ffce33e)

راه حلی پیدا کردین جز وارپ سراسری؟
