### ISSUE TITLE
یک کاربر با چند کانفیگ

### ISSUE THREAD

**Issue by rbsdotnet** [MHSanaei/3x-ui#1480]
سلام
آیا امکان اینکه یک کاربر با چند کانفیگ وجود داره؟ مثل پنل مرزبان
وقتی هرکدوم از اکانت ها مورد استفاده قرار گرفت حجم از خود کاربر کم بشه

**Comment by M4mmad** [comment]
سلام
با اسکریپت زیر این امکان وجود دارد
https://github.com/M4mmad/3xui-multi-protocol

**Comment by M4mmad** [comment]
> > Привет Это возможно с помощью следующего скрипта [https://github.com/M4mmad/3xui-multi-protocol ](https://github.com/M4mmad/3xui-multi-protocol)
> 
> چگونه می توانم یک کاربر برای چندین اتصال ضبط با همان اشتراک ایجاد کنم ؟


You should create clients with same subscription ID in different inbounds on same panel.

![292690231-196f9e7e-d248-4aed-940a-2ab8f9a13d95](https://github.com/MHSanaei/3x-ui/assets/61095662/830c81e7-b865-4511-aeeb-458eba98c221)

**Comment by M4mmad** [comment]
> > > > Привет Это возможно с помощью следующего скрипта [https://github.com/M4mmad/3xui-multi-protocol ](https://github.com/M4mmad/3xui-multi-protocol)
> > > 
> > > 
> > > چگونه می توانم یک کاربر برای چندین اتصال ضبط با همان اشتراک ایجاد کنم ؟
> > 
> > 
> > You should create clients with same subscription ID in different inbounds on same panel.
> > ![292690231-196f9e7e-d248-4aed-940a-2ab8f9a13d95](https://private-user-images.githubusercontent.com/61095662/293481379-830c81e7-b865-4511-aeeb-458eba98c221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMjE3MTAsIm5iZiI6MTcwNDAyMTQxMCwicGF0aCI6Ii82MTA5NTY2Mi8yOTM0ODEzNzktODMwYzgxZTctYjg2NS00NTExLWFlZWItNDU4ZWJhOThjMjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDExMTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZWE3YjVlZWUyM2FhYTQwOWEzZWM5MjViNzc1YTk2NmU0MTczNDJmYWM2MWZhOGVkNTA5NTgzYzEwZGU5YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Q6W83mF2Gb91CxXHTag-nHLd70T9QVguUwb-XamPBI)
> 
> I meant, is there a way to create a user with the same subscription for example for 100 inbounds automatically, without creating it manually every time


No you can't do this automatically :(
