### ISSUE TITLE
I installed it but the web application does not load

### ISSUE THREAD

**Issue by talesam** [MHSanaei/3x-ui#1481]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I'm using a minimal version of Ubuntu on Oracle, Firewall open for the application port, service running but the application doesn't open, there is no error.

![image](https://github.com/MHSanaei/3x-ui/assets/981368/bd5dd836-c453-4617-9f7d-9b346fde545f)

![image](https://github.com/MHSanaei/3x-ui/assets/981368/b9713eef-d035-48f3-87e6-882d2788e0ef)

### Version of 3x-ui

<details>

```console
# Paste here
2.0.2
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
Please enter your selection [0-23]: 12
● x-ui.service - x-ui Service
     Loaded: loaded (/etc/systemd/system/x-ui.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-12-29 17:50:18 UTC; 5min ago
   Main PID: 1103 (x-ui)
      Tasks: 16 (limit: 1067)
     Memory: 25.5M
        CPU: 664ms
     CGroup: /system.slice/x-ui.service
             ├─1103 /usr/local/x-ui/x-ui
             └─1114 bin/xray-linux-amd64 -c bin/config.json

Dec 29 17:50:18 xray systemd[1]: x-ui.service: Deactivated successfully.
Dec 29 17:50:18 xray systemd[1]: Stopped x-ui Service.
Dec 29 17:50:18 xray systemd[1]: x-ui.service: Consumed 1.463s CPU time.
Dec 29 17:50:18 xray systemd[1]: Started x-ui Service.
Dec 29 17:50:18 xray x-ui[1103]: 2023/12/29 17:50:18 x-ui 2.0.2
Dec 29 17:50:18 xray /usr/local/x-ui/x-ui[1103]: INFO - web server run http on [::]:53412
Dec 29 17:50:18 xray /usr/local/x-ui/x-ui[1103]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json


Please enter your selection [0-23]: 13
Dec 29 17:42:15 xray systemd[1]: Started x-ui Service.
Dec 29 17:42:15 xray x-ui[2612]: 2023/12/29 17:42:15 x-ui 2.0.2
Dec 29 17:42:15 xray /usr/local/x-ui/x-ui[2612]: INFO - web server run http on [::]:53412
Dec 29 17:42:15 xray /usr/local/x-ui/x-ui[2612]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
Dec 29 17:44:08 xray systemd[1]: Stopping x-ui Service...
Dec 29 17:44:09 xray systemd[1]: x-ui.service: Deactivated successfully.
Dec 29 17:44:09 xray systemd[1]: Stopped x-ui Service.
-- Boot fed994c6424c45c4972bda8ddf6599f5 --
Dec 29 17:44:39 xray systemd[1]: Started x-ui Service.
Dec 29 17:44:40 xray x-ui[675]: 2023/12/29 17:44:40 x-ui 2.0.2
Dec 29 17:44:41 xray /usr/local/x-ui/x-ui[675]: INFO - web server run http on [::]:53412
Dec 29 17:44:41 xray /usr/local/x-ui/x-ui[675]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
Dec 29 17:50:18 xray systemd[1]: Stopping x-ui Service...
Dec 29 17:50:18 xray systemd[1]: x-ui.service: Deactivated successfully.
Dec 29 17:50:18 xray systemd[1]: Stopped x-ui Service.
Dec 29 17:50:18 xray systemd[1]: x-ui.service: Consumed 1.463s CPU time.
Dec 29 17:50:18 xray systemd[1]: Started x-ui Service.
Dec 29 17:50:18 xray x-ui[1103]: 2023/12/29 17:50:18 x-ui 2.0.2
Dec 29 17:50:18 xray /usr/local/x-ui/x-ui[1103]: INFO - web server run http on [::]:53412
Dec 29 17:50:18 xray /usr/local/x-ui/x-ui[1103]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
```

</details>

**Comment by talesam** [comment]
I decided, it was my "error", but I couldn't delete the topic.

**Comment by seyeddanialhasani** [comment]
what i do?
Jul 21 19:14:12 derniu systemd[1]: Started x-ui Service.
Jul 21 19:14:12 derniu x-ui[1388]: 2025/07/21 19:14:12 Starting x-ui 2.6.2
Jul 21 19:14:12 derniu /usr/local/x-ui/x-ui[1388]: INFO - Web server running >Jul 21 19:14:12 derniu /usr/local/x-ui/x-ui[1388]: INFO - XRAY: infra/conf/se>Jul 21 19:14:12 derniu /usr/local/x-ui/x-ui[1388]: WARNING - XRAY: core: Xray>Jul 21 19:15:00 derniu x-ui[1388]: 2025/07/21 19:15:00 Shutting down servers.
Jul 21 19:15:00 derniu systemd[1]: x-ui.service: Deactivated successfully.
Jul 21 19:15:49 derniu systemd[1]: Started x-ui Service.
Jul 21 19:15:49 derniu x-ui[1485]: 2025/07/21 19:15:49 Starting x-ui 2.6.2
Jul 21 19:15:49 derniu /usr/local/x-ui/x-ui[1485]: INFO - Web server running >Jul 21 19:15:49 derniu /usr/local/x-ui/x-ui[1485]: INFO - XRAY: infra/conf/se>Jul 21 19:15:50 derniu /usr/local/x-ui/x-ui[1485]: WARNING - XRAY: core: Xray>Jul 21 19:16:00 derniu x-ui[1485]: 2025/07/21 19:16:00 Shutting down servers.
Jul 21 19:16:00 derniu systemd[1]: x-ui.service: Deactivated successfully.
