### ISSUE TITLE
حل پر شدن دیسک هارد

### ISSUE THREAD

**Issue by Lion0098** [MHSanaei/3x-ui#1484]
سلام 
به جز پنل سنایی چیزی نصب نکردم هاردم 10 گیگ هست ولی بعد از یک ماه پر میشه 
چطوری فایل های که نیازی بهشون نیست پاک کنم 
یوزرامم کمه نهایتش 5 تا

**Comment by zoheirallafzadeh** [comment]
https://github.com/MHSanaei/3x-ui/issues/1123
