### ISSUE TITLE
مشکل در اجرای اپلیکیشن واتساپ ویندوز 11 با سرویس v2ray

### ISSUE THREAD

**Issue by ehsan102** [MHSanaei/3x-ui#1485]
سلام دوستان کسی می دونه چرا واتساپ ویندوز ، بارکدشو لود نمی کنه ؟
هرچقدر تنظیمات v2ray رو بالا پایین کردم لود نشد 
ولی مثلاً با windscribe لود میشه

**Comment by Arman-nsb** [comment]
با برنامه nekoray حالت tun mode روشن تست کن.

**Comment by ehsan102** [comment]
ممنون با v2rayN اون tun رو فعال کردم درست شد 
فقط یک بدی داره که کل سیستم رو vpn می کنه و اون rule هایی که توو بخش روتینگ ساخته بودم هم از کار میوفته

**Comment by Arman-nsb** [comment]
برنامه nekoray خیلی بهتره، حتما امتحانش کن. هم حالت پروکسی داره هم vpn. قوانین routing اش هم بدرستی کار میکنه.

**Comment by MAsterhadi** [comment]
ببر پشت وارپ مشکلت حل میشه

**Comment by Miladyv** [comment]
> ببر پشت وارپ مشکلت حل میشه

chetor in ro mishe anjam dad< emkanesh hast codesho bedid? mamnon
