### ISSUE TITLE
پر شدن cpu

### ISSUE THREAD

**Issue by samjj123** [MHSanaei/3x-ui#1488]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

پیرو مشکل این دوستمون https://github.com/MHSanaei/3x-ui/issues/1377#issue-2042027923  منم همین مشکل رو دارم ، سرور با cpu 2 core و ram 2 gig وقتی ایپی لیمیت فعال باشه و حدود ۱۰ کانفیگ انلاین باشن مصرف cpu لحظه ای به ۱۰۰ صد میره و دوباره بر میگرده .اگه نوتیف هشدار cpu ربات تلگرام روشن باشه هر دقیقه هشدار ۱۰۰ درصد میده 🤦‍♂️🤦‍♂️
این مشکل رو با چند تا سرور که امتحان کردم دیدم و همه اینجوری شدن و از نسخه ۱.۷.۹ به بالا اینجوری میشه
سرورم اوبونتو ۲۲ هست

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Miladr9800** [comment]
سلام
بکاب بگیرید رو سرور رو ریست کنید دوباره نصب کنید

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
