### ISSUE TITLE
ربات تلگرام روی سرورهای ایرانی

### ISSUE THREAD

**Issue by amirvp** [MHSanaei/3x-ui#1491]
سلاااام وقت همگی بخیر باشه
چجوری میشه ربات حجم تلگرام رو وقتی پنل روی سرورهای ایران نصب شده اجرا کرد؟
ممنونمم

**Comment by kalilovers** [comment]
In iran : 
Just add this to panel inbound config :
[
  {
    "listen": "127.0.0.1",
    "port": 62789,
    "protocol": "dokodemo-door",
    "settings": {
      "address": "127.0.0.1"
    },
    "tag": "api"
  },
  {
    "listen": "127.0.0.43",
    "port": 443,
    "protocol": "dokodemo-door",
    "settings": {
      "address": "149.154.167.220",
      "port": 443,
      "network": "tcp"
    },
    "tag": "telegram"
  }
]



And run this command in terminal:

echo "127.0.0.43 api.telegram.org" >> /etc/hosts

If you enabled firewall (it's better to enable)

Run this in both servers
ufw allow 443/tcp
ufw allow 62789/tcp

And other ports that uses by panel

And works fine 😎

**Comment by mohamadn69** [comment]
روی پنل کافکا این روش را تست کردم تست کردم به ربات وصل نمیشه
هرکاری کردم ربات تلگرام روی سرور کار نکرد. api  تست میزنم جواب میده ولی ربات استارت نمیشه.
/bot<>/getMe

جواب برمیگردونه ولی ربات کار نمیکنه
{"ok":true,"result":{"id":....,"is_bot":true,"first_name":"......","username":"....","can_join_groups":true,"can_read_all_group_messages":true,"supports_inline_queries":false}
خطای لاگ سرور اینه:
telegram service start run failed,NewBotAPI fail:Post "https :// api. telegram. org/bot...../ get Me": dial tcp 127 .0. 0.43: 443: connect: connection refused,tgBottoken:......

**Comment by kalilovers** [comment]
> روی پنل کافکا این روش را تست کردم تست کردم به ربات وصل نمیشه
> هرکاری کردم ربات تلگرام روی سرور کار نکرد. api  تست میزنم جواب میده ولی ربات استارت نمیشه.
> /bot<>/getMe
> 
> جواب برمیگردونه ولی ربات کار نمیکنه
> {"ok":true,"result":{"id":....,"is_bot":true,"first_name":"......","username":"....","can_join_groups":true,"can_read_all_group_messages":true,"supports_inline_queries":false}
> خطای لاگ سرور اینه:
> اینباند داخل پنل تعریف شده
> telegram service start run failed,NewBotAPI fail:Post "https :// api. telegram. org/bot...../ get Me": dial tcp 127 .0. 0.43: 443: connect: connection refused,tgBottoken:......
> یا این یکی
> اینباند داخل تنطیماته
>  telegram service start run failed,NewBotAPI fail:Post https://api.telegram.org/bot<...>/getMe": read tcp 127.0.0.1:45224->127.0.0.43:443: read: connection reset by peer,tgBottoken:....
> فایروال هم کلا غیر فعاله

روشی که نوشتم برا سنایی و علیرضا هستش ، مابقی رو اطلاعات دقیقی ندارم

**Comment by harpag40** [comment]
Something went wrong!ناموفق: invalid character ':' after top-level value
داداش این خطای چیه ؟
