### ISSUE TITLE
مسدود کردن آیپی اشتباهی!!!

### ISSUE THREAD

**Issue by mamadmjf** [MHSanaei/3x-ui#1494]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

حقیقتا به یه مشکلی خوردم که خیلی عجیبه!

کانفیگ زدم دو کاربره. 
وقتی با دو کاربر هم وصل میشی اوکیه، ولی نمیدونم چرا بعد از چند دقیقه، تلگرام دیگه کانکت نمیشه. 
توی لاگ که چک میکنم، سرور میاد آیپی تلگرام اون اکانت رو بن میکنه!
درواقع سیستم اون تلگرام رو یه آیپی جدا حساب میکنه و مسدودش میکنه (چون فکر میکنه یه کاربر جدید اضافه شده و بیشتر از دو نفر متصل شدن)
کسی میدونه راهکارش چیه

Vless + ws cdn clouflare
Extenal proxy
Tls

### Version of 3x-ui

<details>
2.0.2
```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by hrasoul2** [comment]
به احتمال زیاد به روشی که کانفیگ کردید سرورتون رو برمیگرده
اگه روی cdn کانفیگ کرده باشید
این خودش یک اتصال رو با چندتا ایپی به سرور میفرسته و ترافیک های مختلف رو با ایپی ها مختلف به کلودفلر میبره
خلاصه بهتره برای اینکه لیمیت ایپی کار کنه درست از cdn برش داری
البته من اینطوری فکر میکنم
شاید درست نباشه
