### ISSUE TITLE
حذف شدن Domain name

### ISSUE THREAD

**Issue by davoodr22** [MHSanaei/3x-ui#1497]
سلام وقت بخیر
در نسخه های قدیمی در ساخت اینباند یک Domain name وجود داشت که باعث میشد sni توی کانفیگ کاربر مخفی بمونه و نیاز نباشه خود تب sni رو در پروتکل vmess پر کنیم و یه جورایی دامنه فیلتر نمیشد به خاطر همین مورد (با توجه به تست و تجربه یک ساله که انجام دادم اینطوری بوده برا من یکی حداقل)
توی ابدیت جدید این تب حذف شده ایا امکانش هست Domain name مجدد اضافه کنید؟
پیوست شد یک عکس از  پنل قدیمی
![001](https://github.com/MHSanaei/3x-ui/assets/118099346/a1d104b2-964a-4185-8e21-c8f675e20d6a)

**Comment by rahman8521** [comment]
سلام

**Comment by davoodr22** [comment]
ممنون از راهنمایی
فقط یک سوال دیگه
این سه گزینه same-none-tls در همین بخش External Proxy دقیقا معنا و استفادشون چی میشه؟

**Comment by davoodr22** [comment]
ممنون از راهنمایی
فقط یک سوال دیگه
این سه گزینه same-none-tls در همین بخش External Proxy دقیقا معنا و استفادشون چی میشه؟

> سلام External Proxy همون کاره دامین نام رو انجام میده
