### ISSUE TITLE
 Speedtest by Ookla not work for fedora 

### ISSUE THREAD

**Issue by RooyeKhat** [MHSanaei/3x-ui#150]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi 
New option for  Speedtest by Ookla not work in fedora base 

Please enter your selection [0-20]: 20
`sudo: apt-get: command not found`

Please improve and solve for next version 

Thanks

### Version of 3x-ui

<details>

V [v1.1.4]

</details>

### x-ui log reports or xray log

<details>

</details>

**Comment by forkeer** [comment]
@MHSanaei tnx dear
Please add centos 7 too becuase other project work correctly with the 7 series version

Thanks

**Comment by forkeer** [comment]
thanks
