### ISSUE TITLE
بی ادبی و بن کردن بی مورد ادمین گروه 

### ISSUE THREAD

**Issue by Ali-ph** [MHSanaei/3x-ui#1501]
سلام وقتتون بخیر .
داخل گروه بزرگ sanaei نزدیک ۷ ماهه به همه کمک میکنم و قوانین رو رعایت میکنم . ادمین جدید نمیدونم چه خصومتی داره الکی بهم دوبار اخطار داد و من بن شدم ( تگ R داشت ) 
لطفا ادمای بدون لول و شعور رو ادمین نزارین ک الکی کسی ک اینهمه وقت گزاشته واسه کمک ب بقیه رو بن بزنه
ممنون

آیدی تلگرام خودم ک بن شده @aliph_79
و اون یکی آیدی ای ک امروز بن کردن @V2_seller

**Comment by P3YM4N3** [comment]
آیدی بنده هم به همین صورت بی مورد بلاک کردند 
@its_payman

**Comment by vahobrsti** [comment]
خیلی سخت نگیرید دوستان. مدیرش یه بچه ۱۵ ساله هست. از بچه ای ک مشقاش رو نمینویسه چ انتظاری دارید :))

**Comment by vahobrsti** [comment]
گروهه یه نقش دیگه هم برای من داشت: تقویت اعتماد ب نفس. همیشه تا یه موج فیلترینگ میومد همه شون فیلتر میشدن و من هیچوقت نشدم. با دیدن قطعی و نوب بودنشون اعتماد ب نفسم تقویت میشد. البته دیگه زده شدم :)))

**Comment by vahobrsti** [comment]
هاها‌. اینجا اگر چاره داشتی ک همه رو بن میکردی. اما اینجا گیت هاب هست. جایی ک همه میتونن آزادانه حرف بزنن. یه گروه زده. انگاری صاحب مملکته. فک میکنی ایشو رو کلوز میکنی میتونی ساکت کنی ملت رو؟ نوبی دیگه.

**Comment by MHSanaei** [comment]
جهت یاد اوری اینجا هم میشه بلاک کرد
و گروه هم دیشب حذف کردم
موفق باشید

**Comment by karen2030** [comment]
> @vahobrsti جهت یاد اوری اینجا هم میشه بلاک کرد و گروه هم دیشب حذف کردم موفق باشید

ثنایی عزیز چرا گروه رو پاک کردی ؟ 
یک موردی که باید بگم واقعا به نوبه ی خودم ازت تشکر میکنم به خاطر تمام زحماتی که میکشی عشقی ❤️
