### ISSUE TITLE
مولتی پروتکل؟

### ISSUE THREAD

**Issue by Amirmomeni82** [MHSanaei/3x-ui#1502]
سلام ثنایی جان
اولا یه تشکر ازت بکنم
ثانیا این مولتی پروتکل همونی بود که چن وقته انتظار داشتیم؟ ینی عین پنل مرزبان چندتا کانفیگ میشه داد با احتساب خودکار حجم و تاریخ؟

**Comment by hrasoul2** [comment]
بله دقیقا همونه
