### ISSUE TITLE
proxy IPv6

### ISSUE THREAD

**Issue by mvh97hg** [MHSanaei/3x-ui#1503]
How to set socks proxy to listen to ipv4 and proxy out using ipv6
1 IPv4 to multiple IPv6, rotate IPv6

**Comment by MiniKoro** [comment]
I suggest you read the official xray documentation carefully. The function you want needs to be manually modified and implemented by yourself.
You can set sendThrough in outbounds to add multiple ipv6 outbound offloads according to routing rules

**Comment by MiniKoro** [comment]
Of course, it would be best if the developers listened to you and were able to add the "sendThrough" option.
