### ISSUE TITLE
ایجاد اکسترنال پروکسی برای تانل کردن روی لینک سابسکریپشن و توضیح درباره ریورز پروکسی قرار داده شده

### ISSUE THREAD

**Issue by mobagheri** [MHSanaei/3x-ui#1507]
با سلام. مشکل بزرگی که الان باهاش مواجه هستیم، فیلتر شدن آی پی سرورها و عدم به روزرسانی لینم سابسکریپشن سرورهاست. خواهشا یک اکسترنال پروکسی جهت تانل کردن ای پی و پورت لینم سابسکریپشن قرار بدید و حداقل یک توضیح درباره گزینه جدید ریویرز پروکسی در کانال بگذارید تا همگی بتوانند از آن استفاده کنند. من هرچه سعی کردم نتوانستم تانل خودم را روی گزینه ریورز پروکسی پیاده سازی کنم....

**Comment by mobagheri** [comment]
> یه دامنه رو بذار روی کلادفلر و وصلش کن به سرورت و از پورت‌های https کلادفلر برای سابسکریپشن‌هات استفاده کن. من اینطوری مشکل رو حل کردم.

سلام وقت بخیر. من هم در حال حاضر همین کار و انجام میدم ولی بهتر و مطمئن تر است که لینک سابسکریپشن تانل بشه تا روی هیچ خطی به مشکل برنخوره چونکه به سی دی ان کلادفلیر در این وضعیت هیچ اطمینانی نیست. اگر برای سابسکریپشن یه اکسترنال پراکسی قرار داده بشه عالی میشه تا بتونیم روی ای پی و پورت دلخواه ایران تانلش کنیم. این میشه جایگزین هاست ایرانی که همه دارن ازش استفاده میکنن.

**Comment by mobagheri** [comment]
> > سلام وقت بخیر. من هم در حال حاضر همین کار و انجام میدم ولی بهتر و مطمئن تر است که لینک سابسکریپشن تانل بشه تا روی هیچ خطی به مشکل برنخوره چونکه به سی دی ان کلادفلیر در این وضعیت هیچ اطمینانی نیست. اگر برای سابسکریپشن یه اکسترنال پراکسی قرار داده بشه عالی میشه تا بتونیم روی ای پی و پورت دلخواه ایران تانلش کنیم. این میشه جایگزین هاست ایرانی که همه دارن ازش استفاده میکنن.
> 
> من یوزرهامو روی سرور ایرانم ساختم و دیگه از این مشکلات ندارم

وقت بخیر. بله این از مزایای تانل اوت باند هستش و هر روشی مزایا و معایب خاص خودش رو داره. این مشکل روی سرور خارج حل بشه به نظرم مزایای زیادی خواهد داشت. چون در اکثر تانل ها پنل روی سرور خارج سوار هست.

**Comment by mobagheri** [comment]
5

> > وقت بخیر. بله این از مزایای تانل اوت باند هستش و هر روشی مزایا و معایب خاص خودش رو داره. این مشکل روی سرور خارج حل بشه به نظرم مزایای زیادی خواهد داشت. چون در اکثر تانل ها پنل روی سرور خارج سوار هست.
> 
> تانلم هم اینباند هست #1390 کلا آی‌پی‌سرورهامو زدن و نمی‌تونم آتباند بزنم. الان سرور ایرانم همزمان ۳ تا تانل اینباند داره از ۳ تا سرور خارج.

ممنون و موفق باشید. وضعیت این تانل نسبت به سایر متودها مثل RTT و یا Chisel به چه شکل هست؟ آیا استیبل هستش؟

**Comment by mobagheri** [comment]
> راستی من اصلا اون روش‌ها رو تست نکردم. ولی این روش برای من فعلا که خیلی خوب جواب داده.

تشکر حتما تست میکنم...

**Comment by mobagheri** [comment]
> راستی من اصلا اون روش‌ها رو تست نکردم. ولی این روش برای من فعلا که خیلی خوب جواب داده.

ببخشید در این روش تانلینگ باید برای تانل کردن هر سرور خارج یک اینابند ساخته بشه؟ و آیا اینابند ساخته شده برای تانل کردن سرور خارج متفاوت از اینباندی هست که برای یوزرها ایجاد میکنیم؟ به طور مثال من یک سرور ایران دارم که میخوام با 4 سرور خارج تانلش کنم و الان در کل چند اینباند نیاز هست؟ یک اینباند برای یوزرهام و 4 اینباند برای سرورهای خارج؟

**Comment by kalilovers** [comment]
> راستی من اصلا اون روش‌ها رو تست نکردم. ولی این روش برای من فعلا که خیلی خوب جواب داده.

چه کانفیگی میدید به اوتباند خارج ؟ ینی اینباند داخلتون چی هست کانفیگش ممنون میشم شاتش رو ارسال کنید . چون تو نوع ریورس از اینباند ریلیتی با اسپیدتست که استفاده کردم همراه لودبالانس چند ساعت بعد تانل مختل شد باینکه برگشت ولی مختل میشه
