### ISSUE TITLE
ارور 504

### ISSUE THREAD

**Issue by davoodr22** [MHSanaei/3x-ui#1508]
سلام پنل سنایی جدید  رو نصب کردم روی لوکیشن هلند
وارد وبسایت زیر میشم ارور 504 یا server bad getway میگیرم
https://appleid.apple.com/
روی پنل چی نصب تا این مشکل رفع بشه؟
پروتکلی که استفاده میکنم wmess+tcp+header

**Comment by Saeedg21** [comment]
از وارپ کمک بگیر

**Comment by davoodr22** [comment]
نصب کردم وارپ رو بازم همین ارور پابرجا بود
باید دستور خاص رو موقع نصب و یا بعد نصب وارپ روی سرور وارد کنم؟

> از وارپ کمک بگیر
