### ISSUE TITLE
وبسرویس دریافت کانفیگ

### ISSUE THREAD

**Issue by Hossein-Teimouri** [MHSanaei/3x-ui#1509]
سلام وقتون بخیر دارم از وبسرویس هایی که ارائه دادید استفاده  میکنم 
با استفاده از وبسرویس
```
http://{{HOST}}:{{PORT}}/panel/api/inbounds/addClient
{
    "id": 1,
    "settings": "{\"clients\":[{\"id\":\"95e4e7bb-7796-47e7-e8a7-f4055194f776\",\"alterId\":0,\"email\":\"NewClient\",\"limitIp\":2,\"totalGB\":42949672960,\"expiryTime\":1682864675944,\"enable\":true,\"tgId\":\"\",\"subId\":\"\"}]}"
}
```
یک کاربر جدید ایجاد میکنم اما نه در رسپانس این وبسرویس نه وبسرویس های دیگر ندیدم که کانفیگ ساخته شده رو برگردونه
وبسرویس خاصی داره که توی این داکیومنت ها نیست؟ چطوری میتونم این کار رو انجام بدم

**Comment by Arman-nsb** [comment]
سرویس API کانفیگ یا لینک ساب اکانت هارو به شما نمیده، باید خودتون دستی ایجاد کنید.
