### ISSUE TITLE
تک پورت کردن

### ISSUE THREAD

**Issue by Behtash007** [MHSanaei/3x-ui#1510]
سلام چطور میتونم تک پورت کنم مثلا همه پورتهای اکانتها ۴۴۳ بذارم ، چون به کلوفلر متصل میکنم و تعداد محدودی میتوان پرت وارد کرد

**Comment by Saeedg21** [comment]
از fallback استفاده کن

هر چندتا اینباد داشته باشی با پورت های متفاوت میتونی همش رو با یک پورت ارتباط برقرار کنی

**Comment by Mehranhich** [comment]
> از fallback استفاده کن
> 
> هر چندتا اینباد داشته باشی با پورت های متفاوت میتونی همش رو با یک پورت ارتباط برقرار کنی

درود میشه درموردش توضیح بدین یا اموزشی چیزی بفرستید ک چطوری پورت های مختلف پنل رو بیاریم زیر ی پورت؟!

**Comment by amirbayat82** [comment]
روی منوی کلاینت اصلی بزن بعد add client کن

**Comment by Mehranhich** [comment]
> روی منوی کلاینت اصلی بزن بعد add client کن

ino midonam goftam shayad rahi bashe accounthayi k darim bedon taghir biyarim zir y port

**Comment by behnamgolds** [comment]
اگر پشت CDN  کلادفلر هستین از این قسمت 

>  Rules = > Origin Rules

   میتونین  شرطی قرار بدین که اگر درخواست به فلان مسیر بود (path) ، یا نام هاست و یا .... مساوی با فلان مقدار بود درخواست ها رو به پورت خاصی (Rewrite to) روی سرور شما ارسال کنه. به این ترتیب همه ی کلاینت ها میتونن  به پورت ۴۴۳  یا هر پورتی که کلادفلر ساپورت میکنه و مد نظر شماست وصل بشن و کلادفلر طبق رولی که تعریف کردین تصمیم میگیره که کدوم درخواست رو به کدوم پورت سرور شما ارسال کنه. این روش نیازی به تغییرات اینباند نداره فقط باید پورت اینباند باز و از طریق اینترنت قابل دسترسی باشه . و پورت اینباند سرور رو میتونین هر چیزی قرار بدین و لزوما نیازی نیست فقط پورت هایی که کلادفلر ساپورت میکنه باشه.

```
                                      |  path=/users   rewrite to port 8000
client request => cloudflare port 443 |  path=/others  rewrite to port 9000
                                      |  path=/alpha   rewrite to port 20001
```

به نظرم بد نیست از این قسمت برای ریدایرکت کردن درخواست هایی که از ایران "هستن" ولی شرط بالا رو "ندارن" (مسیرشون فرق داره) ریدارکت کنین مثلا به آدرس گوگل یا هر سایتی که به نظرتون کمتر شک برانگیز باشه :

>  Rules = > Redirect Rules

و همینطور تمام درخواست هایی که از خارج از ایران به آدرس شما میان رو بلاک کنین از این مسیر :
>  Security = > WAF

و توی لاگ همون قسمت میتونین ببینین چه حجم زیادی از درخواست ها از کشورهای مختلف به سرور شما ارسال و بلاک شده.

روش دیگه ای که هم با CDN  و هم بدون CDN  میتونین استفاده کنین اینه که اینباند ها رو ببرین پشت Nginx  و مشابه کاری که بالا توضیح دادم رو روی سرور خودتون راه اندازی کنین. من این روش رو انجام دادم ، تمام اینباند ها رو بایند کردم روی آی پی لوکال هاست و روی پورت های مختلف مثلا ۲۰۰۰۱ ، ۲۰۰۰۲ ، ۲۰۰۰۳  و ....  کانکشنی که به کاربرهام دادم همه روی پورت ۴۴۳ هستن. تمام درخواست ها اول به Nginx میرسن و  روی Nginx  از طریق فیلد name  یا همون نام دامنه سرور ترافیک رو پخش کردم بین اینباندها . اگر کاربرهای زیادی دارین باید دستی لینک رو براشون ادیت کنین یا اسکریپتی بنویسین یا سورس کد پنل رو تغییر بدین که لینک کانکشن رو براتون ادیت کنه. من چون کاربرهام کم هستن دستی ادیت کردم ، شاید روش آماده ای هم باشه که من خبر ندارم.

```
                                 |  name=xyz.net  redirect to 127.0.0.1:8000
client request => Nginx port 443 |  name=abc.com  redirect to 127.0.0.1:9000
                                 |  name=uvw.info redirect to 127.0.0.1:20001
```

اگر وقت و حوصله دارین روش دوم رو پیشنهاد میکنم به اضافه ی رول های ریدایرکت و سکوریتی در کلافلر که به نظرم امنیتش بالاتره چون فقط پورت ۴۴۳ روی سرور شما باز خواهد بود وبقیه پورت ها از طریق  اینترنت قابل دسترسی نخواهند بود، بقیه امنیت هم کلادفلر از طریق رول های ریدایرکت و سکوریتی تامین میشه و ضمنا چون درخواست های بی ربط به سرورتون نمیرسه میزان مصرف رم و سی پی یو هم میاد پایین.  
قدیم نرم افزار کلادفلر رو میشد روی سرور نصب کرد که یک تانل بین سرور و کلادفلر ایجاد میشد و ساب دامین ها رو میشد به مقصد تانل تعریف کرد. نمیدونم الان منتقل شده به وارپ یا کلا غیر فعال شده ، در هر صورت فعلا فرصت نکردم این کار رو بکنم. اگر باز هم مقدرو باشه میتونین اون رو هم  فعال کنین و Nginx رو هم فقط روی اون آدرس تانل بالا بیارین که باز هم امنیت و صرفه جویی در رم و سی پی یو بالاتر بره چون از این طریق پورت Nginx  هم از طریق اینترنت و مستقیما آدرس پابلیک سرورتون قابل دسترس نخواهد بود و فقط درخواست هایی که به کلادفلر رسیدن از طریق تانل میتونه به سرور شما برسه و  تمام رول های امنیتی بالا روی سرویس Nginx هم اعمال خواهد شد.
