### ISSUE TITLE
خطای نصب پنل

### ISSUE THREAD

**Issue by hamid3d** [MHSanaei/3x-ui#1511]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام موقع نصب به خطای زیر می خورم من با سرور ipv6 به همراه ubuntu 22.0.4 هستم
Failed to fetch x-ui version, it maybe due to Github API restrictions, please try it later
چه مشکلی داره من اسکریپت هم دیدم ولی خوب به خطا می خوره اگر راهنمایی بفرمایید تشکر می کنم

### Version of 3x-ui

2.02

### x-ui log reports or xray log

Failed to fetch x-ui version, it maybe due to Github API restrictions, please try it later

**Comment by jackchen666999** [comment]
Failed to fetch x-ui version, it maybe due to Github API restrictions, please try it later

**Comment by jackchen666999** [comment]
I also encountered the same problem and don't know how to solve it(Failed to fetch x-ui version, it maybe due to Github API restrictions, please try it later)
