### ISSUE TITLE
failed to load config file

### ISSUE THREAD

**Issue by Madfun71** [MHSanaei/3x-ui#1515]
سلام دوستان روی پنل سنایی بهد از این که ساب دامنه را تغییر دادم سرتیفیکیت ها را پاک کردمو وقتی ریست کردم پنل error داد و دیگه run نشد
![Screenshot 2024-01-04 230508](https://github.com/MHSanaei/3x-ui/assets/155676582/0cbc2087-9f54-4f6d-8ed6-77c936721258)
به نظرتون الان باید چه کنم

**Comment by Saeedg21** [comment]
از خود سرور برو 3-ui بزن گزینه reset setting بزن یا از خود پنل برو آدرس سرتیفیکیت هات رو پاک کن

**Comment by Madfun71** [comment]
متوجه شدم که دامنم فیلتر شده
کمتر از یک ماه هم بود که خریده بودم
اون رو چه کنم
