### ISSUE TITLE
ربات تلگرام

### ISSUE THREAD

**Issue by sajadshadmn** [MHSanaei/3x-ui#1517]
سلام
مشتری دقیقا باید چی رو در رباط تلگرام وارد کنه تا امار اکانتش رو ببینه
ممنون

**Comment by Joey-Zasa** [comment]
درود
1- توی تلگرام از طریق BotFather یه ربات ایجاد میکنی،
2- آی دی ربات رو توی پنل ثبت میکنی و قابلیت ربات رو فعال میکنی.
3- به کاربر آدرس ربات و آی دی اکانتشو میدی
4- کاربر وارد ربات که بشه بعد از استارت ربات دستور
/usage ID-Account
رو میزنه،
ربات بهش مقدار مصرف رو نشون میده.
