### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by delafrouz** [MHSanaei/3x-ui#1526]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام خسته نباشید
ما یک سرور داریم و روش پنل شما رو نصب کردیم، و فقط هم یه کانفیگ vless+grpc روش داریم. متاسفانه مموری زیادی مصرف می‌کنه و وقتی ریستارت می‌کنیم، ram usage میاد روی ۲۰٪، منتها بعد از حدود نیم ساعت دوباره تا بالای ۸۰٪ میره بالا. 
![image](https://github.com/MHSanaei/3x-ui/assets/125189279/e526ef99-d53c-4c3e-97c9-d5b182ca4d11)

روی سرور هم htop می‌گیریم و بیشترین مموری مصرفی مربوط به وارپ و xray core است:
![image](https://github.com/MHSanaei/3x-ui/assets/125189279/6c3fd6b7-f8d1-450c-aa88-1099f61e7ef7)
این هم مصرف CPU:
![image](https://github.com/MHSanaei/3x-ui/assets/125189279/3f7f0814-b139-48b6-a0e0-046101558d8e)

حدس ما اینه که یکی از لایبرری‌هایی که استفاده کردید مموری لیک داره. من نتونستم پکیج‌های مصرفی شما رو ببینم و go بلد نیستم ممنون میشم اگه کمکمون کنید حداقل لیست پکیج‌های نصبی رو بدونیم و با ورژن‌های متفاوت امتحانشون کنیم تا پیدا کنیم مموری لیک از کجاست.

### Version of 3x-ui

<details>

```console
2.0.2
```

</details>

### x-ui log reports or xray log

<details>

```console
ربطی به لاگ ندارد
```

</details>

**Comment by yarik2720** [comment]
have the same issue using only shadowsocks2022

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
