### ISSUE TITLE
 ورد پرس نصب کردم بعد پنل همش خطا میده

### ISSUE THREAD

**Issue by ddddccves** [MHSanaei/3x-ui#1527]
سلام وقت بخیر من به این مشکل خوردم ورد پرس نصب کردم سایت بالا اوردم بعد پنل رو نصب کردم  این ارور میده لطفا راهنماییم کنید:
Failed to start: app/proxyman/inbound: failed to listen TCP on 443 > transport/internet: failed to listen on address: 0.0.0.0:443 > transport/internet/tcp: failed to listen TCP on 0.0.0.0:443 > listen tcp 0.0.0.0:443: bind: address already in use
![Capture45](https://github.com/MHSanaei/3x-ui/assets/48737446/80dbdbf7-eacf-42ca-aadb-b1fa2911d07d)

**Comment by Otisist** [comment]
پورت وردپرس و یکی inbounds، باهمدیگه یکی هست (443)
پورت inbounds 443 رو به پورت دیگه تغییر بده
یا به که کمک nginx، ریورس پروکسی بساز
