### ISSUE TITLE
بن نشدن کاربر

### ISSUE THREAD

**Issue by Saeedg21** [MHSanaei/3x-ui#1533]
سلام

دوستان چرا کاربرای من با اینکه لاگ انداخته که مثلا به مدت یک ساعت بن شده میتونند کار کنند ؟

اینو مثلا خودت داشتم تست میکردم که این کاربر رو لیمیتش رو یک انتخاب کردم و با دو تا اینترنت که ای پی یکسانی ندارند متصل شدم و برای دستگاه دومی لاگ انداخت اما بن نکرد

علت از چی میتونه باشه ؟

2024/01/07 17:17:59   BAN   [Email] = 0vdoysw5  [IP] = 3X0.1X6.1X4.1X9 banned for 3600 seconds.

**Comment by feridj2020** [comment]
این مشکل منم هست دقیقا حالت tls ws vless لاگ میندازه ولی هر دو دستگاه کار میکنه .

**Comment by MHSanaei** [comment]
چون یا روی cdn هستید یا تانل 
برای همین ای پی بن میشه ولی همچنان داره با ای پی cdn یا تانل وصل میشه

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/1749#issuecomment-1925823942
