### ISSUE TITLE
How Can I Get Links?

### ISSUE THREAD

**Issue by PrivyXe** [MHSanaei/3x-ui#1539]
Hello. Thank you for doing a great job. 
How can I get the vmess, vless, shadowsocks config created when I make an email query with the API? Create a new client and receive the config created via e-mail?

Etc;

Create Client : 
```
{
    "id": 1,
    "settings": "{\"clients\":[{\"id\":\"07d5c4db-cea4-408b-bb7d-bbc277ab9569\",\"alterId\":0,\"email\":\"TestClient\",\"limitIp\":0,\"totalGB\":53687091200,\"expiryTime\":1704749318000,\"enable\":true,\"tgId\":\"\",\"subId\":\"\"}]}"
}
```

Get config;

`https://domain.port/panel/api/inbounds/getClientTraffics/TestClient `

`ss://YWVzLTEyOC1nY206TGEzWG40TGlweXBYN`

or

`vmess://ewogICJ2IjogIjIiLAogICJwcyI6ICJ0ZXN0LTgwe  `

How can I list it as follows?

Thanks

**Comment by Arman-nsb** [comment]
Hello,
No such feature is yet implemented. So, you won't be able to get config links using the API system.

**Comment by PrivyXe** [comment]
I understand, but the API is not available in the subscription section.
