### ISSUE TITLE
ریستور کردن بکاپ

### ISSUE THREAD

**Issue by csharpfarsi** [MHSanaei/3x-ui#1543]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام من بکاپ از پنل قبلی برداشتم روی سرور جدیدم ریستور میکنم ولی نمیاره مشکل از کجاس؟

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by qar4al** [comment]
با سلام دوست عزیز

**Comment by EmirHosen** [comment]
> ### Welcome
> 
>     * [x]  Yes, I'm using the latest major release. Only such installations are supported.
> 
>     * [x]  Yes, I'm using the supported system. Only such systems are supported.
> 
>     * [x]  Yes, I have read all WIKI document,nothing can help me in my problem.
> 
>     * [x]  Yes, I've searched similar issues on GitHub and didn't find any.
> 
>     * [x]  Yes, I've included all information below (version, config, log, etc).
> 
> 
> ### Description of the problem,screencshot would be good
> 
> سلام من بکاپ از پنل قبلی برداشتم روی سرور جدیدم ریستور میکنم ولی نمیاره مشکل از کجاس؟
> ### Version of 3x-ui
> ### x-ui log reports or xray log

تلگرام پیام بدین، مشکلتون رو حل کنم.
https://t.me/emirhosens
