### ISSUE TITLE
exit-code 

### ISSUE THREAD

**Issue by Alphfaa** [MHSanaei/3x-ui#1545]
آقا خسته نباشید من چند وقتیه این ارور رو دارم کلا xray رو غیر فعال میکنه مجبورم از کنسول فعالش کنم.
 
x-ui.service: Failed with result 'exit-code'.

**Comment by Bullshark21** [comment]
https://github.com/alireza0/x-ui/commit/b63f30573766db1e192820bee87d41d4c5beac18
