### ISSUE TITLE
روی سرور خصوصی نصب کردم ولی اینباند کلاینت کانکت نمیشه

### ISSUE THREAD

**Issue by hmadanigh** [MHSanaei/3x-ui#1546]
سلام، من یک سرور خصوصی دارم و روی سرور خودم نصب کردم. 
بعداز اسکن کردن QR کد از طریق اپلیکیشن اندرویدی، کانکت نمیشه و پیغام زیر را می دهد.
failed to start v2ray: infra/conf: reality: empty "reality settings"

لطفا راهنمایی کنید. من روی سرور خودم پورت 443 را باز نکردم .و از یک پورت دیگه استفاده می کنم.

**Comment by pishguy** [comment]
@hmadanigh 

شما از داکر استفاده کردید؟

**Comment by hmadanigh** [comment]
درود بر شما،ممنون از اینکه سریع پاسخ دادید.راستش رو بخواهید من یک Synology NAS دارم و اینترنت یک گیگ با IP ثابت.یک Virtual Machine روی NAS درست کردم و Ubunto Server  را روش نصب کردم.یک DDNS هم دارم که به IP ثابت اینترنتم وصل است.
من قصد بیزنس از این سرور ندارم و فقط می خواهم برای خانواده در ایران یک دسترسی امن درست کنم.یک آموزش از Youtube دیدم از لینک زیر و همه چیز درست پیش رفت، اما وقتی از طریق Application در تلفن خودم QR را اسکن می کنم در برنامه V2rayNGT ارتباط برقرار نمیشه. قسمت Log اپلیکیشن را که چک کردم دیدم پیامی را که قبلا فرستادم میده.ممنون میشم اگر کمکم کنید.

    On Wednesday, 10 January 2024 at 05:37:17 GMT, Mahdi Pishguy ***@***.***> wrote:  
 
 


@hmadanigh

شما از داکر استفاده کردید؟

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
  

|  | Virus-free.www.avg.com |
