### ISSUE TITLE
لود نشدن اینستگرام

### ISSUE THREAD

**Issue by Farhadvbs** [MHSanaei/3x-ui#1559]
سلام،تمام کانفیگ هایی که میسازم کار میکنن به خوبی فقط هیچ کدوم اینستگرام رو درست لود نمیکنن،مشکل از چی میتونه باشه؟!

**Comment by EmirHosen** [comment]
جهت بررسی بیشتر به ایدی https://t.me/emirhosens در تلگرام پیام بدین.

**Comment by niiaco** [comment]
این ربطی به پنل نداره به روتر سرور خارج شما ربط داره 
این قضیه با وارپ حل میشه ( با توجه به فیلتر شدن ایپیش مدام باید تعویضش کنید)‌
یا اینکه یه سرور بهتر تهیه کنید
