### ISSUE TITLE
Error when setting SSL certificate in web panel

### ISSUE THREAD

**Issue by d8rt8v** [MHSanaei/3x-ui#1564]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

PR_END_OF_FILE_ERROR error on connection when setting correct cert files to web-front end:

[Thu Jan 11 06:03:58 PM CET 2024] Your cert is in: /root/.acme.sh/mysubdomain.mydomain.xx_ecc/mysubdomain.mydomain.xx_.cer
[Thu Jan 11 06:03:58 PM CET 2024] Your cert key is in: /root/.acme.sh/mysubdomain.mydomain.xx__ecc/mysubdomain.mydomain.xx_.key

Does script works with subdomains or with cer format, because i've only seen .pem format in guides?

### Version of 3x-ui

<details>

```console
2.0.2
```

</details>

### x-ui log reports or xray log

<details>

```console
Jan 11 18:12:50 spooky-wall.xx.xxx-ui[728]: 2024/01/11 18:12:50 http: TLS handshake error from 88.xx.xx.xx:34466: read tcp 77.91.xx.xx:80->88.xxx.xx.xx:34466: use of closed network connection
Jan 11 18:15:34 spooky-wall.xx.xxx-ui[728]: 2024/01/11 18:15:34 http: TLS handshake error from 52.xx.xx.xx:59990: read tcp 77.91.xx.xx:80->52.xx.xx.xx:59990: use of closed network connection
Jan 11 18:15:36 spooky-wall.xx.xxx-ui[728]: 2024/01/11 18:15:36 http: TLS handshake error from 166.xx.xx.xx:46506: read tcp 7.91.xx.xx:80->166.xxx.xx.xx:46506: use of closed network connection
```

</details>

**Comment by D8mbSniper** [comment]
Seems like a similar issue https://github.com/MHSanaei/3x-ui/issues/1506

**Comment by LinU777** [comment]
Same error in log after installing cert via menu, panel not opening:
`May 14 10:09:03 zzz x-ui[349842]: 2025/05/14 10:09:03 http: TLS handshake error from xx.xx.xx.xx:59645: read tcp xx.xx.xx.xx:1038->yy.yy.yy.yy:59645: use of closed network connection`
