### ISSUE TITLE
مشکل صفر نشون دادن حجم کاربران اینباوند

### ISSUE THREAD

**Issue by farshadfaza** [MHSanaei/3x-ui#1567]
سلام اقای سنایی خسته نباشیین من کاربر پنل چینی بودم به اجبار چون قبل ساختن پنل سنایی رو چینی بودمو بخاطر مشتریا نمیتونستم ستا پنل قدیمیچ رو بیارم رو سنایی چن جایی پرسیدم برا انتقال بکاپ به سنایی تا یکی از دوستان گفتن که این کارو میتونن بکنن برام این کارو انجام دادن ولی مشکل اینجاست الان کاربرای داخل اینباوند حجمم مصرف کنن صفر نشون میده غیر فعالم بشن بازم صفر نشون میده آنلاین یا افلاین باشن صفر نشون میده ترو خدا کمکم کنین من حواسم به این قضیه نبوده تو هر این باوند سرور چهل پنجا نفر ساختم لطفا کمکم کنین حتی هزینه هم بگسن پرداخت میکنم

**Comment by pilot-code** [comment]
x-ray رو ریست کن
