### ISSUE TITLE
اضافه کردن mux و fragments در بخش اوتباند

### ISSUE THREAD

**Issue by omid-j-d** [MHSanaei/3x-ui#1575]
با سلام درصورت امکان mux و fragment را به بخش اوتباند xray اضافه نمایید

**Comment by Arman-nsb** [comment]
سلام، اگر اشتباه نکنم قابلیت mux باید توسط خود کاربر فعال بشه. اگر راهکاری داره که تو فایل config بشه این مورد رو برای تمام کاربرها (بصورت دستی) فعال کرد ممنون میشم راهنمایی کنید.

**Comment by omid-j-d** [comment]
برای این مورد چیزی نمیدونم 
ولی در کل من برای اوتباند و پنل به پنل میخواستم این کار رو انجام بدم که حتما باید توی تب advance ادیت انجام میشد

**Comment by Ilaprgg2** [comment]
> برای این مورد چیزی نمیدونم 
> ولی در کل من برای اوتباند و پنل به پنل میخواستم این کار رو انجام بدم که حتما باید توی تب advance ادیت انجام میشد 
> 
> 

خود هسته xray اپشنی برای fragment داره؟
