### ISSUE TITLE
نود

### ISSUE THREAD

**Issue by ahwazi12** [MHSanaei/3x-ui#1576]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام اگه  یه نود برای پنل بزنید خیلی خوب میشه  که میشه  سرور های دیگه رو به یک پنل وصل کرد تا مولتی  سرور بدیم بالینک ساب 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Avampiire** [comment]
سلام مهندس
این قابلیت خیلی نیازه و کاربردی لطفا در صورت امکان رو این موضوع کار کنید
سپاس

**Comment by zifulx** [comment]
دوستان این اآپشن رو ما شخصی سازی و اضافه کردیم
