### ISSUE TITLE
دریافت لینک اکانت توسط api

### ISSUE THREAD

**Issue by hasssanitman** [MHSanaei/3x-ui#1579]
دمتون گرم دوستان.
من با api یک کلاینت ایجاد میکنم، بعدش میخوام لینک کلاینتی که ساختمو بدست بیارم.  توی ریسپانس add client که نیست، api دیگه ای هم برای گرفتن لینک وجود نداره.
فقط get client هست که خب اطلاعات وضعیت و میزان مصرف کلاینت رو میده.
آیا امکانی هست که باهاش کارم راه بیافته؟

**Comment by Arman-nsb** [comment]
اگر کانفیگ vless میسازی، میتونی بصورت دستی uuid و باقی مقادیر رو برای کاربر جدیدی که میسازی جایگزین کنی، برای نمونه:

`vless://{UUID}@{PROXY_DOMAIN OR MAIN DOMAIN}:80?type=ws&path=%2F&host={HOST_HEADER OR EMPTY}&security=none#Test`

کانفیگ کاربر جدید:

`vless://ce3494e2-b84f-4037-9a10-f9c81dd43253@example.com:80?type=ws&path=%2F&host=sub.example.com&security=none#newuser`

**Comment by hasssanitman** [comment]
ممنونم آرمان
یعنی میشه خودم uuid جنریت کنم و بفرستم که کلاینتشو واسم بسازه؟!
اگه بخوام vmess هم داشته باشم چطور؟!

**Comment by Arman-nsb** [comment]
بله زمانیکه با API کاربری رو ایجاد میکنید، یدونه uuid سفارشی بهش میدید. بعد همون رو در کانفیگ بصورت دستی تنظیم میکنید.
برای کانفیگ vmess نمیشه این روش رو پیاده کرد چون بصورت رمزنگاری شده است و قابل ویرایش نیست.
