### ISSUE TITLE
[BUG] Deleting All Clients from an Inbound with API, Cause X-UI go DOWN

### ISSUE THREAD

**Issue by AliAkhgar** [MHSanaei/3x-ui#1580]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi, 
Deleting All Clients from an Inbound, Cause System to crash and NOT to load any inbounds at all.
This is not possible through Web-UI but done with API.

Steps to Reproduce:
1. Setup An Inbound in X-UI
2. Delete the Inbound Default Client Using API `/inbound/[ID]/delClient/[Client-ID]
3. After Success, Checkout Inbounds Page in Web-Panel.

### Version of 3x-ui

<details>

```
V 2.0.2
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by drno88** [comment]
Good afternoon. yes, you should always leave at least 1 client.
