### ISSUE TITLE
دسترسی به سایت ایرانی

### ISSUE THREAD

**Issue by AliHemmati79** [MHSanaei/3x-ui#1585]
سلام
از بخش بلاک ایپی رنج و دامنه ایران فعال کردم
میخوام یه سایت ایرانی دسترسی بدم بهش که فقط اون سایت بالا بیاد، چه کاری باید انجام بدم ممنون میشم راهنمایی کنید!!!

**Comment by Arman-nsb** [comment]
در بخش xray settings > routing rules دکمه Add rule رو بزنید و قسمت Domain، دامنه مدنظرتون رو بنویسید (مثال: example.com) و outband tag رو روی حالت Direct تنظیم کنید و ذخیره کنید. یکبار هم restart xray بزنید.
![image](https://github.com/MHSanaei/3x-ui/assets/84615037/22284831-4e1c-473b-a36d-d9d65ee37c8e)

_این قانونی که اضافه میکنید باید پایینتر از قانون بلاک دامنه های ایران باشه._

**Comment by AliHemmati79** [comment]
> در بخش xray settings > routing rules دکمه Add rule رو بزنید و قسمت Domain، دامنه مدنظرتون رو بنویسید (مثال: example.com) و outband tag رو روی حالت Direct تنظیم کنید و ذخیره کنید. یکبار هم restart xray بزنید. ![image](https://private-user-images.githubusercontent.com/84615037/296751771-66a264da-e79f-4b32-889a-faa0cd511a23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDAxMjgsIm5iZiI6MTcwNTMzOTgyOCwicGF0aCI6Ii84NDYxNTAzNy8yOTY3NTE3NzEtNjZhMjY0ZGEtZTc5Zi00YjMyLTg4OWEtZmFhMGNkNTExYTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE3MzAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NTdhZDg1ZmJkZDRlYjMwZDQ3MzRjOWJjNGI1ZDUxYzc1NGVhMDhmNzRkNzRlNDRjYzE1MTE5ODEyZTgzOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qf75FWsSU1UhIWUaNakEap_YwocBkXK8YshIHSG4pbE)
> 
> _این قانونی که اضافه میکنید باید پایینتر از قانون بلاک دامنه های ایران باشه._

ممنون بابت راهنمایی ولی سایت مورد نظر لود نشد!

**Comment by Arman-nsb** [comment]
خب اون rule که ایجاد میشه رو ببرید بالاتر تو جدول و مجدد تست کنید. من حقیقتا این راهکار رو به شخصه تست نکردم، فقط میدونم که روش دیگه ای نداره تو پنل.

**Comment by dadashali61** [comment]
منم همین مشکل رو دارم و سایت های ایرانی که مد نظر دارم نه بلاک میشن و نه دایرکت. ممنون میشم اگر کسی بلد باشه، راهنمایی کنه.
