### ISSUE TITLE
Please restore support for Debian 10 as there are many VPS without Debian 11 installed

### ISSUE THREAD

**Issue by lllrrr2** [MHSanaei/3x-ui#1588]
Please restore support for Debian 10 as there are many VPS without Debian 11 installed

**Comment by MHSanaei** [comment]
Just upgrade to debian 11

**Comment by lllrrr2** [comment]
> Debian10 can be used normally and no problems have been found.

New Version 2.1.0 has been restricted during installation, and Debian 10 does not allow installation.
