### ISSUE TITLE
باگ های ورژن 2.1.0 پنل

### ISSUE THREAD

**Issue by Mohammadgb0078** [MHSanaei/3x-ui#1597]
##  **تاریخ شمسی که به تازگی اومده چند تا باگ جزئی داره**

> وقتی که میخوایم تاریخ وارد کنیم توی زبان انگلیسی placeholder اینپوتی که وجود داره فارسی هست
> توی زبان انگلیسی اصلا نمیتونیم تاریخ شمسی وارد کنیم و تقویم باز نمیشه که یک روز و ساعت رو مشخص کنیم

داخل تب Overview یا به اصطلاح نمای کلی هم وضعیت هسته Xray تو زبان فارسی Running نوشته شده بجای در حال اجرا

چند تا باگ دیگه هم دیده بودم که الان به یاد نمیارم بخوام ذکر کنم

**Comment by SajjadFighter** [comment]
ربات دریافت ورودی ها رو نمیده، inbound/ و usage/ ش هم کار نمیکنه، و به کاربر هم آمار مصرف نمیده

**Comment by MHSanaei** [comment]
زبان بات تلگرام رو از فارسی به انگلیسی تغییر بدید تا فردا اپدیت میدم درست میشه

**Comment by SajjadFighter** [comment]
انگلیسی ش کردم خودم میتونم آمار بگیرم ولی کاربر همچنان میگه خطا میده، عکسش هم فرستاده
