### ISSUE TITLE
مشکل ربات تلگرام

### ISSUE THREAD

**Issue by Masouddhojaei** [MHSanaei/3x-ui#1602]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

درود وقت بخیر
ربات من هم مشکل پیدا کرده، آمار کاربر رو نشون نمیده. 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
زبان فارسی ربات تلگرام مشکل داره انگلیسی کنید فعلا تا اپدیت بعدی

**Comment by Masouddhojaei** [comment]
> زبان فارسی ربات تلگرام مشکل داره انگلیسی کنید فعلا تا اپدیت بعدی

خیلی ممنون بله درست شد ، فقط لطفا برای آپدیت بعدی تاریخ شمسی ای که اضافه کردین هم برای ربات در نظر بگیرین تا اونو نشون بده بجای میلادی

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/1633#issuecomment-1901260655
