### ISSUE TITLE
Upgrade 3x-ui after docker install

### ISSUE THREAD

**Issue by AlexZonov** [MHSanaei/3x-ui#1603]
How I can upgrade if I install panel by docker?

I try:
- git pull
- docker-compose up -d
- docker-compose restart

Version didn't changed in panel site...

**Comment by anartikov** [comment]
cd 3x-ui
docker compose down
docker compose pull 3x-ui
docker compose up -d

**Comment by AlexZonov** [comment]
Ok it's work, but if I need downgrade, how can I do it?
May be something like `docker compose pull 3x-ui 2.0.2`?

**Comment by im-ecorp** [comment]
> Ok it's work, but if I need downgrade, how can I do it? May be something like `docker compose pull 3x-ui 2.0.2`?

You can edit yaml file and replace your specific version with latest
