### ISSUE TITLE
تنظیمات request host 

### ISSUE THREAD

**Issue by airamlou** [MHSanaei/3x-ui#1604]
سلام 
برای تنظیم 
request host (host/ws host/h2 host) quic security
 
در کجای تنظیمات باید ادرس سایت رو وارد کنم 
هر چی میگردم پیدا نمیکنم
لطفا راهنمایی کنید

**Comment by Arman-nsb** [comment]
سلام، برای کانفیگی مثل vless+ws گزینه Request Header رو بزنید و مثل تصویر زیر مقدار هارو تنظیم کنید: (بجای example.com دامنه مدنظر رو قرار بدید)
![image](https://github.com/MHSanaei/3x-ui/assets/84615037/18facd0d-8504-4d52-a836-93bc326db5c8)

**Comment by airamlou** [comment]
ممنونم 
اگر ip  روی همراه اول فیلتر شده باشه میشه از این روش استفاده کرد ؟
از دامنه هایی که روی v2ray های دیگه که داره کار میکنه میشه استفاده کرد ؟

**Comment by Arman-nsb** [comment]
تو قسمت request host فقط دامنه میشه وارد کرد، آی پی ساپورت نمیشه.
دامنه ای که تو این قسمت قرار میدید باید بصورت مستقیم به آی پی سرور شما اشاره کنه یا اینکه پشت cdn کلودفلر با پراکسی روشن باشه.
این رو مدنظر داشته باش الان اوضاع فیلترینگ خیلی شدید شده و شما هر دامنه ای بذاری به احتمال زیاد زیر 1 روز فیلتر بشه.
