### ISSUE TITLE
اتصال چند کاربر همزمان

### ISSUE THREAD

**Issue by hashemim66110** [MHSanaei/3x-ui#1605]
قابلیت تک کاربره یا چند کاربره کردن اکانت چطوری فعال میشه ؟
توی نسخه ۲.۱.۰ برنامه حساب ۱ کاربره ساختم ولی ۲ تا سیستم همزمان متصل شدن.
تنظیمات خاصی باید براش انجام بشه ؟

**Comment by ramtiny** [comment]
کسی میدونه ؟
