### ISSUE TITLE
فیلتر شدن دامنه

### ISSUE THREAD

**Issue by ho3einAsadi** [MHSanaei/3x-ui#1613]
درود من چندتا سرور و پنل دارم
 یکی از پنل هام دائما فیلتر میشه سرورش فیلتر نمیشه دامنه به طور کامل با ساب دامنه ها فیلتر میشه روش اتصال من cdn کلود فلر هست که بقیه سرور هام هم همینه و اونا هیچ مشکلی ندارن 
 و دیدم این اواخر مشکل خیلی ها هست که میگن از طرف فیلترینگ چین میاد
من همه کار کردم 3 تا دامنه جدید و 4 تا دامنه قدیمی که مال 10 ماه پیش بوده عوض کردم بازم فیلتر شده
سرور رو عوض کردم 4 دیتا سنتر مختلف
روش اتصال هم تغییر دادم در هر صورت فیلتر شدم 
ممنون میشم اگه کسی اطلاعاتی داره راهنمایی کنه♥

**Comment by Arman-nsb** [comment]
هر دامنه جدیدی که ثبت بشه خصوصا دامنه های ارزون قیمت که TLD مثل click/shop/site/online/xyz , ... دارن به محض اینکه ترافیک بره سمتشون در کمتر از 24 ساعت کل دامنه فیلتر میشه.
تنها راهکار اینه از تانل یا قابلیت fragment استفاده کنید. البته تانل هم ترافیک بالا داشته باشه در امان نیست.
راهکارهای دیگه ای هم هست ولی اصلا به صرفه نیست. ترجیحا هم پابلیک نشن بهتره.

**Comment by Miladr9800** [comment]
سلام
داداش فقط اتصال از ای پی ایران رو فعال کنید و بقیه کشورها رو بلاک کنید
