### ISSUE TITLE
مشکل وارپ پنل 

### ISSUE THREAD

**Issue by kalilovers** [MHSanaei/3x-ui#1618]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام وقت بخیر یه مورد دیگه که داره متد وارپ جدید اینه که گاها از کار میوفته و باید اوتباندش رو ریست کنیم یا وروکر یک بزاریم یا mtu تغییر بدیم و... دوباره کار کنه اصلا پایدار نیستش تنظیمات پیشفرضشم اینطوری و.. 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Arman-nsb** [comment]
بله منم این مشکل رو دارم. البته زمانی این مشکل پیش میاد که یکسری قوانین مختلف تو بخش routing اضافه میکنم. در حالت عادی که فقط یه قانون برای warp بذارم این مشکل نیست.
البته تو outbound وارپ گزینه domain strategy رو روی حالت ForceIPv6IPv4 میذارم، اینطوری استیبل تر بنظر میرسه. (کپچای گوگل هم نمیاره اینطوری)

**Comment by kalilovers** [comment]
> بله منم این مشکل رو دارم. البته زمانی این مشکل پیش میاد که یکسری قوانین مختلف تو بخش routing اضافه میکنم. در حالت عادی که فقط یه قانون برای warp بذارم این مشکل نیست.
> البته تو outbound وارپ گزینه domain strategy رو روی حالت ForceIPv6IPv4 میذارم، اینطوری استیبل تر بنظر میرسه. (کپچای گوگل هم نمیاره اینطوری)

اره منم اینکارو کردم اتفاقا اوکی شد موقتا (البته تا الان اوکی بوده )
تو رول هم باید درست دسته بندی بشه ایپی ۴ بره ته ، بلاک‌ها اول بعدشم وارپ اینطوری همشون کار میکنن

**Comment by Sharevex** [comment]
دقیقا منم همین مشکل رو دارم  outbound رو هر دفعه یا باید ریست کنم ، یا یه بار حذفش کنم از نو بسازمش تا مشکل برطرف بشه ، همه رول ها هم به صورت پیشفرض هستن چیزی رو تغییر ندادم من به شخصه .

**Comment by kalilovers** [comment]
ظاهراً با فورس استراتژی هم حل نشد ، آخرش همون وارپ قدیمی رو کانفیگ کردی دستی تو پنل اوکی شد راحت شدم

**Comment by dani96102** [comment]
واسه منم بشدت اختلال و قطعی داره وارپ جدید و داخلی پنل وقتی تعداد کاربر بالا روش میاد
ولی اگر بزارمش روی یک اینباند که کاربر نداره بدون اختلال و قطعی و عالی کار میده
اما تا بزارمش روی یک اینباند که بار ترافیکی و کاربر زیاد داره بشدت اختلال و قطعی پیدا میکنه
فکر میکنم بشه اینو با آپدیت حل کرد

**Comment by Sharevex** [comment]
این مشکل همچنان هست ....

**Comment by BenyaminMoadab** [comment]
بله هست راهکاری پیدا نشد؟
