### ISSUE TITLE
لود نشدن تنظیمات ایکس ری

### ISSUE THREAD

**Issue by mohamad15516** [MHSanaei/3x-ui#1620]
نمیدونم مشکل از منه یا باگ هست اما با تغییر قوانین مسیر یابی و با این که اون کاربری که ساختم و مسیریابیش کردم چه خروجی چه ورودی وصل هست و اوکیه  اما توی تنظیمات ایکس ری نمیره و همینجور روی درحال بارگذاری میمونه ممنون میشم راهنمایی کنید
![Screenshot_20240118_104104_Firefox.jpg](https://github.com/MHSanaei/3x-ui/assets/113285931/2835f574-d0b5-478f-a766-2e53a4ddd035)

**Comment by Mohammadgb0078** [comment]
سلام برا منم دیروز این مشکل پیش اومد از اونجایی که بک اند دولوپرم رفع اش کردم بعد نیم ساعت تلگرام بهم پیام بده پنلتم بهم بده برات فیکسش بدم
https://t.me/mohammad_mahdi06

**Comment by mohamad15516** [comment]
> سلام برا منم دیروز این مشکل پیش اومد از اونجایی که بک اند دولوپرم رفع اش کردم بعد نیم ساعت تلگرام بهم پیام بده پنلتم بهم بده برات فیکسش بدم
> https://t.me/mohammad_mahdi06

ممنون ولی اگر لطف کنید و توضیح مختصر بدید خودم رفع میکنم البته با عرض پوزش

**Comment by Arman-nsb** [comment]
به سرور ssh بزن و x-ui restart رو یکبار اجرا کن. بعد کش مرورگر رو پاک کن یا حالت incognito وارد پنل شو ببین مشکل رفع میشه یا نه.

**Comment by mohamad15516** [comment]
> به سرور ssh بزن و x-ui restart رو یکبار اجرا کن. بعد کش مرورگر رو پاک کن یا حالت incognito وارد پنل شو ببین مشکل رفع میشه یا نه.

خیر نمیشه چندین بار این کار رو کردم

**Comment by Arman-nsb** [comment]
باقی صفحات پنل مثل اینباند ها براحتی باز میشه یا اونم لودینگ گیر میکنه؟

**Comment by mohamad15516** [comment]
> باقی صفحات پنل مثل اینباند ها براحتی باز میشه یا اونم لودینگ گیر میکنه؟
> 

همه به راحتی و به سرعت باز میشن فقط قسمت تنظیمات ایکس ری گیر میکنه

**Comment by Arman-nsb** [comment]
ایراد عجیبیه تابحال بهش برنخوردم. با مرورگر دیگه بازش کن و اینکه با اینترنت مختلف (vpn روشن/خاموش کن).

**Comment by mohamad15516** [comment]
> ایراد عجیبیه تابحال بهش برنخوردم. با مرورگر دیگه بازش کن و اینکه با اینترنت مختلف (vpn روشن/خاموش کن).

نمیشه احتمالا باگ هستش چون با یک سرور جدید توی قوانین مسیر یابیش رفتم و دیدم ایکس ری به ارور میخوره احتمالا باگ باشه

**Comment by Mohammadgb0078** [comment]
@Arman-nsb
آرمان تمام مسیر و راه های احتمالی رو که داری توضیح میدی تست کردم و مشکل اینه که کد فرانت اند نمیتونه بعضی از rule ها تعریف شده هسته Xray رو هندل کنه و نمایش بده برا همین همینجوری تو لودینگ میمونه! اصلا هم ربطی به وی پی ان و اینجور صحبتا نداره! (خلاصه کلام مشاوره غیرتخصصی ارائه ندید ممنون)

**Comment by Arman-nsb** [comment]
@Mohammadgb0078 
دوست عزیز بنده هیچ مشاوره ای به کسی ندادم، تمام چیزهایی که نوشتم تجربه شخصی بنده بوده. قبلتر به این مشکل برخورده بودم با همون توضیحاتی که نوشتم تونستم حلش کنم. فقط بحث اینجاس که من هیچ ایده ای نداشتم که این دوستمون rule اضافه کرده یا نه، تصویر هم ارسال نکردن از بخش xray config برای همین راهکارهایی که خودم طی کردم و مشکلم حل شده رو بهشون پیشنهاد دادم.
موفق باشید 🙌

**Comment by amerian001** [comment]
> > باقی صفحات پنل مثل اینباند ها براحتی باز میشه یا اونم لودینگ گیر میکنه؟
> 
> همه به راحتی و به سرعت باز میشن فقط قسمت تنظیمات ایکس ری گیر میکنه

من هم همین مشکلو دارم

**Comment by mohamad15516** [comment]
> > > باقی صفحات پنل مثل اینباند ها براحتی باز میشه یا اونم لودینگ گیر میکنه؟
> > 
> > همه به راحتی و به سرعت باز میشن فقط قسمت تنظیمات ایکس ری گیر میکنه
> 
> من هم همین مشکلو دارم

هیچ راهی نداره تنظیمات روتینگ یا مسیر یابیت مشکل داره و باید پاک کنی و از اول نصب کنی

**Comment by MHSanaei** [comment]
@mohamad15516 @amerian001 
برید داخل منوی x-ui سرور از اونجا راحت میشه تنظیمات رو ریست کرد
