### ISSUE TITLE
wireguard inbound functionality missing

### ISSUE THREAD

**Issue by Songxwn** [MHSanaei/3x-ui#1621]
1、Unable to generate QR code or export configuration file
2、Peer public key shared key cannot be automatically generated.

Currently xray supports generating peer keys.

**Comment by stone-w4tch3r** [comment]
It also would be cool to have option for "obfuscating" wireguard's traffic through vless/shadowsocks etc, so that manual configuration will not be needed

**Comment by Songxwn** [comment]
![image](https://github.com/MHSanaei/3x-ui/assets/21145071/62cb3490-60ca-4b51-af76-41870e04f571)
Already supports automatic key generation, which is so cool. I hope it will be better to support exporting QR.

**Comment by metya** [comment]
does anybody knows how to properly setup wireguard here? is there any guide?
