### ISSUE TITLE
ip limit just show 1 ip

### ISSUE THREAD

**Issue by mohammadrezafarihi** [MHSanaei/3x-ui#1624]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

salam
zamani ke bishtar az yek nafar be yek config vasl mishan panel faghat ip yekishon ro dakhele ip log neshon mide va ip limit amal nemikone, testi ke anjam dadam har dastgah ip motfaveti dasht vali faghat yeki ro neshon midad version haie ghabl az 2.0.0 in moshkel ro nadashtan

### Version of 3x-ui

<details>

```console
#2.1.1
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Mohammadgb0078** [comment]
اگه از آیپی لیمیت استفاده میکنید برای اون کلاینت اگه تک کاربره ست کرده باشید یک آیپی نمایش میده دو کاربره کنید اگه واقعا دو تا آیپی مختلف متصل شده باشن دو تاشو نمایش میده و مطمئن هم شید fail2ban رو نصب کردید رو سرور میزبان کلاینت و اینباند ها!

**Comment by mohammadrezafarihi** [comment]
> اگه از آیپی لیمیت استفاده میکنید برای اون کلاینت اگه تک کاربره ست کرده باشید یک آیپی نمایش میده دو کاربره کنید اگه واقعا دو تا آیپی مختلف متصل شده باشن دو تاشو نمایش میده و مطمئن هم شید fail2ban رو نصب کردید رو سرور میزبان کلاینت و اینباند ها!

داخل ورژن‌های قبل از دو اینطور بود که هرچندتا آی پی وصل میشد داخل آی پی لاگ نشون میداد ولی فقط به تعداد آی پی لیمیت مثلاً یک نفر اجازه اتصال میداد و بقیرو بلاک میکرد و افرادی که بلاک میشدن ثبت میشدن، ولی دو به به بعد فقط یکی نشون میده و عمل نمیکنه، پیش نیاز‌ها هم نصب و فعاله، الان برگردوندمش به ورژن 1.7.9 درست شده ولی دو به بعد مشکل داره
