### ISSUE TITLE
ربات تلگرام

### ISSUE THREAD

**Issue by AliHemmati79** [MHSanaei/3x-ui#1629]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام در نسخه جدید ربات وقتی دریافت آمار کاربر میزنم مینویسه پیکربندی شما یافت نشد!!!
نسخه قبلی همچین مشکلی نداشت

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by kalilovers** [comment]
اره منم همینطوریم ایشو هم زدم پاسخگو نبودن ظاهراً نسخه جدید برای حل این مورد بوده ولی بدتر از کار افتاد با انگلیسی و... هم کار نمیکنه

**Comment by Cactustory** [comment]
سلام
این مشکل رو  من هم روی  ورژن جدید دارم

**Comment by AliHemmati79** [comment]
من فعلا به نسخه 2.0.2 برگردوندم تا ببینیم کی تو نسخه های جدید این باگ برطرف میشه./

**Comment by MHSanaei** [comment]
این باگ نیست
در اپدیت جدید شما باید id number تلگرام مشتریتون رو قرار بدید یوزرنیم حذف شده
حتی اخطارش هم به فارسی نوشتیم یه ذحمت به خودتون نمیدید نوشته رو بخونید

**Comment by Cactustory** [comment]
> این باگ نیست در اپدیت جدید شما باید id number تلگرام مشتریتون رو قرار بدید یوزرنیم حذف شده حتی اخطارش هم به فارسی نوشتیم یه زحمت به خودتون نمیدید نوشته رو بخونید

زحمت دادیم و اخطار رو دیدم، ولی گیر اوردن id number مشتری کار راحتی نیست و الان باید یک کار اضافه تر انجام بدیم، لطفا این قابلیت رو برگردونید‌.
توی تغییرات هم چیزی از این تغییر نوشته نشده، به همین دلیل این به اشتباه باگ تشخیص داده شده.

**Comment by MHSanaei** [comment]
@Cactustory 
امکان نوشتن تمام تغییرات فراهم نیست اگر علاقمند هستید باید دونه دونه باز کنید و جزییات رو ببینید
https://github.com/MHSanaei/3x-ui/pull/1463
