### ISSUE TITLE
باگ اسکریپ مولتی پروتکل

### ISSUE THREAD

**Issue by PouryaDe** [MHSanaei/3x-ui#1630]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام وقت بخیر
این اسکریپ مولتی پروتکل یه باگی داره

مثلا وقتی یه کلانت در دو تا اینباند میسازیم و زمانش رو Start on Initial Use میذاریم وقتی کاربر به اینباند دوم وصل میشه، محاسبه زمان استارت میخوره ولی در اینباند اول هنوز محاسبه تاریخ اتفاق نمیوفته

بعضا هم وقتی تاریخ همون کلاینت در اینباند عوض میشه روی بقیه اینباند ها اعمال نمیشه و فقط حجم رو یکسان سازی میکنه

لطفا این مورد رو بررسی کنید

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by PouryaDe** [comment]
کلا چک کردم ظاهرا فقط حجم ها رو یکسان سازی میکنه و تاریخ انقضا رو یکسان سازی نمیکنه لطفا بررسی کنید

**Comment by MHSanaei** [comment]
@M4mmad

**Comment by MHSanaei** [comment]
داخل صفحه خودشون گزارش کنید که برطرف کنند
@M4mmad
