### ISSUE TITLE
Shadowsocks version

### ISSUE THREAD

**Issue by teuchezh** [MHSanaei/3x-ui#1632]
What's are Shadowsocks version using in latest 3x-ui version?

**Comment by teuchezh** [comment]
@MHSanaei ?

**Comment by painfull30** [comment]
2.1.1
![image](https://github.com/MHSanaei/3x-ui/assets/29792471/1b23b01d-7e5a-4a4c-b0e8-ceac084334bc)
![image](https://github.com/MHSanaei/3x-ui/assets/29792471/ffdc3465-2c3e-4813-9190-92f53cf801b0)
