### ISSUE TITLE
ربات تلگرامی

### ISSUE THREAD

**Issue by Cactustory** [MHSanaei/3x-ui#1633]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

در نسخه جدید ربات نه با uuid کار می کنه نه با Email

### Version of 3x-ui

2.11

### x-ui log reports or xray log

.

**Comment by AliHemmati79** [comment]
به نسخه 2.0.2 برگرد

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/1629#issuecomment-1901258344
بدون قرار دادن ایدی یوزر امکان دیدن نشخصاتش رو نخواهد داشت
Uuid هم حذف شده
فقط با ایمیل میتونید ببینید
/Usage email
