### ISSUE TITLE
مشکل دایرکت کردن دامنه های ایران

### ISSUE THREAD

**Issue by AlirezaVahdani** [MHSanaei/3x-ui#1637]
سلام
نمیشه قابلیتی فراهم کنید که بجای بلاک دامنه های ایران ، در حالت معمولی دایرکت کرد؟
یعنی سایت های ایرانی بدون vpn بالا بیاد (از تونل رد نشه)

**Comment by danielrad2006legend** [comment]
این قابلیت هست که دامنه های ایران رو دایرکت میکنه تو تنظیمات برید  قسمت تنظیمات مسوقیم کسور ها هست 😐

**Comment by DoctorGuidance** [comment]
> این قابلیت هست که دامنه های ایران رو دایرکت میکنه تو تنظیمات برید قسمت تنظیمات مستقیم کشور ها هست 😐

کار نمیکنه دادا.
گزینه بلاک هم برداری دایرکت ایران رو بذاری روی top هم بذاریش بازم میری سایت ایرانی ای پی سرورو میندازه. نه ای پی خود شخص.

**Comment by AlirezaVahdani** [comment]
> این قابلیت هست که دامنه های ایران رو دایرکت میکنه تو تنظیمات برید قسمت تنظیمات مستقیم کشور ها هست 😐

کار نمیکنه
حتی فقط دایرکت رو فعال کنی بازم ای پی سرور رو توی سایت های داخلی نشون میده
حتی با روتینگ که جدید اضافه شده تست کردن؛ با تغییر اولویت ها هم درست نشد

مگر اینکه تانل دکومودور استفاده کنی

**Comment by AlirezaVahdani** [comment]
فقط با دایرکت کردن توی نرم‌افزار کلاینت v2ray و اونم به وسیله فایل iran.dat میشه؛که باید جدا تنظیم کنی

من حرفم چیز دیگه ست،  میخوام از سمت سرور بشه دایرکت کرد ، تا این دردسر هارو نداشته باشیم

**Comment by AlirezaVahdani** [comment]
اگه کسی راه خلی بلده بگه؛ ممنون میشم
@MHSanaei @alireza0 
مهندسین عزیز راهی ندارید ؟ این مشکل رو چطور میشه برطرف کرد؟

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/474#issuecomment-1900364366
