### ISSUE TITLE
مشکل هنگ کردن پنل سرور ایران در تانل ریورس پنل به پنل

### ISSUE THREAD

**Issue by Rezaaesh** [MHSanaei/3x-ui#1641]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام خسته نباشین اول ازتون ممنونم که این پنل رو ساختین
خواستم یه مشکل رو بگم اگر ممکنه دلیلش رو بگید یا اگر باگ هست رسیدگی کنید
من وقتی تانل ریورس پنل به پنل میزنم تو سرور ایران بیشتر وقت هایی که پنل رو باز میکنم سرور هنگ میکنه و باید xray رو ریستارت کنم تا اتصال برقرار بشه لطفا راهنمایی کنید که دلیلش چیه
یا اگر ممکنه در پنل امکان ریست خودکار xray مثلا هر نیم ساعت رو قرار بدید ممنون

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by hosseinmf** [comment]
این مورد تایید میشه
لاگ ها و fail1ban هم غیر فعالن و مشکلی نداره
مشکلی که پیش میاد تعداد کانکشن های TCP در سرور ایران به مرور زمان افزایش پیدا میکنه  (به 30000 الی 40000 کانکشن میرسه) و باعث میشه لود پردازنده بالا بره و تنها راهش ریستارت xray هست.
سعی کردم که buffersize رو افزایش بدم، اما حل نشد. 
@MHSanaei
