### ISSUE TITLE
X-UI command doesn't work

### ISSUE THREAD

**Issue by rezafarokhi** [MHSanaei/3x-ui#1646]
https://github.com/MHSanaei/3x-ui/blob/1cd93e8751d827891712c8fcdc74b2f267eb9c31/x-ui.sh#L914

When i type x-ui in terminal it shows error below

/usr/bin/x-ui: line 914: syntax error near unexpected token `('
/usr/bin/x-ui: line 914: `            echo "\$(date +"%%Y/%%m/%%d %%H:%%M:%%S")                                                                            BAN   [Email] = <F-USER> [IP] = <ip> banned for <bantime> seconds." >> ${iplim   

i can't access to x-ui prompt from terminal
![Screenshot 2024-01-20 194855](https://github.com/MHSanaei/3x-ui/assets/6306486/05d833e0-8bff-4fbb-a6d3-f972e854aec3)

**Comment by rezafarokhi** [comment]
![Uploading Screenshot 2024-01-20 194855.png…]()

**Comment by MHSanaei** [comment]
Use install link again
