### ISSUE TITLE
 ERROR - location <Asia/Tehran> not exist, using  default location: Asia/Tehran

### ISSUE THREAD

**Issue by telvideo** [MHSanaei/3x-ui#1655]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام . خطای زیر میده موقع استارت . 

 ERROR - location <Asia/Tehran> not exist, using
 default location: Asia/Tehran

ممنون میشم راهنمایی کنید برای رفع

### Version of 3x-ui

<details>

```console

# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console


```

</details>

**Comment by javad8780** [comment]
سلام داخل روت کد های زیر رو به ترتیب وارد کنید

sudo timedatectl set-ntp no

sudo timedatectl set-timezone Asia/Tehran

sudo timedatectl set-ntp yes

و بعد کد زیر رو وارد کنین ببینین timezone تهران/اسیا شده 
sudo timedatectl

بعد وارد پنل بشین ،منو تنظیمات پنل ،پایین صفحه منطقه زمانی رو 
Asia/Tehran
وارد کنین
