### ISSUE TITLE
عدم ثبت اتوماتیک نام هدر درحالت وی‌لس و وب سوکت

### ISSUE THREAD

**Issue by farshadl** [MHSanaei/3x-ui#1658]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

زمان ساخت یک کانکشن Vless-WS با header، نام Header خالی است. در نتیجه وقتی گزینه save را می‌زنیم و مجددا کانکشن ساخته شده را باز می‌کنیم، قسمت Header خالی است
من از آخرین نسخه ۲.۱.۱ استفاده می‌کنم
### Version of 3x-ui

<details>

```console
# version 2.1.1
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Arman-nsb** [comment]
میتونید بصورت دستی عبارت "Host" رو برای request header اضافه کنید و مقدارش رو نام دامنه مدنظرتون قرار بدید.

**Comment by farshadl** [comment]
حق با شماست. ولی بهتره که این باگ درست بشه. تو نسخه‌های قبل این مشکل نبود.
ممنون از شما

**Comment by DoctorGuidance** [comment]
> میتونید بصورت دستی عبارت "Host" رو برای request header اضافه کنید و مقدارش رو نام دامنه مدنظرتون قرار بدید.

سلام
وقتی سرور ایران و خارج ریورس تونل میشن، در اینباند سرور ایران قسمت Host باید ipv6 سرور خارج زده شه؟ و در اوتباند سرور خارج قسمت addresss مقدار ipv6 ایران زده شه؟
