### ISSUE TITLE
مصرف بیش از حد رم

### ISSUE THREAD

**Issue by niiaco** [MHSanaei/3x-ui#1663]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام روی سرور پنلی که کسی بهش متصل نیست ۷۰ درصد رم توسط x-ui درحال مصرفه یعنی معادل 1.29گیگ رم
با top چک کردم فقط و فقط x-ui رو نمایش میده 
پنل رو اپدیتم کردم باز همینه!

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by DoctorGuidance** [comment]
عکس بفرست از مصرف توی htop
اون multi protocl هست که خیلی مصرف میکنه. شاید اونو نصب کردی.

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
