### ISSUE TITLE
reverse tunnel 

### ISSUE THREAD

**Issue by mahdiyarMSZ** [MHSanaei/3x-ui#1667]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

 ریورس تانل پنل به پنل باگ داره پنل مرتب ریستارت میشه داخل لاگ معلومه

### Version of 3x-ui

<details>

```console
2.1.1
```

</details>

### x-ui log reports or xray log

an 23 19:52:19 debian11 /usr/local/x-ui/x-ui[19012]: INFO - X-UI: Remove Inbound User R-man due the expire or traffic limit
Jan 23 19:52:19 debian11 /usr/local/x-ui/x-ui[19012]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
Jan 23 20:07:09 debian11 /usr/local/x-ui/x-ui[19012]: WARNING - X-UI: access.log doesn't exist in your config.json
Jan 23 20:07:19 debian11 /usr/local/x-ui/x-ui[19012]: INFO - X-UI: Remove Inbound User vida due the expire or traffic limit
Jan 23 20:07:19 debian11 /usr/local/x-ui/x-ui[19012]: INFO - X-UI: Remove Inbound User 15 last due the expire or traffic limit
Jan 23 20:07:19 debian11 /usr/local/x-ui/x-ui[19012]: INFO - X-UI: Remove Inbound User milad akbari N3 due the expire or traffic limit
Jan 23 20:07:19 debian11 /usr/local/x-ui/x-ui[19012]: INFO - X-UI: Remove Inbound User milad akbari N4 due the expire or traffic limit
Jan 23 20:07:19 debian11 /usr/local/x-ui/x-ui[19012]: INFO - X-UI: Remove Inbound User Mahna n1 due the expire or traffic limit
Jan 23 20:07:19 debian11 /usr/local/x-ui/x-ui[19012]: INFO - X-UI: Remove Inbound User R-man due the expire or traffic limit
Jan 23 20:07:19 debian11 /usr/local/x-ui/x-ui[19012]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
Jan 23 20:08:35 debian11 x-ui[19012]: panic: runtime error: slice bounds out of range [368:201]
Jan 23 20:08:35 debian11 x-ui[19012]: goroutine 6012 [running]:
Jan 23 20:08:35 debian11 x-ui[19012]: x-ui/xray.(*LogWriter).Write(0xc001382860, {0xc0013b8000?, 0x285, 0x4eb060?})
Jan 23 20:08:35 debian11 x-ui[19012]: /home/runner/work/3x-ui/3x-ui/xray/log_writer.go:35 +0x5e6
Jan 23 20:08:35 debian11 x-ui[19012]: io.copyBuffer({0x26c4d20, 0xc001382860}, {0x26c4660, 0xc0000636b0}, {0x0, 0x0, 0x0})
Jan 23 20:08:35 debian11 x-ui[19012]: /opt/hostedtoolcache/go/1.21.5/x64/src/io/io.go:432 +0x1f4
Jan 23 20:08:35 debian11 x-ui[19012]: io.Copy(...)
Jan 23 20:08:35 debian11 x-ui[19012]: /opt/hostedtoolcache/go/1.21.5/x64/src/io/io.go:389
Jan 23 20:08:35 debian11 x-ui[19012]: os/exec.(*Cmd).writerDescriptor.func1()
Jan 23 20:08:35 debian11 x-ui[19012]: /opt/hostedtoolcache/go/1.21.5/x64/src/os/exec/exec.go:560 +0x34
Jan 23 20:08:35 debian11 x-ui[19012]: os/exec.(*Cmd).Start.func2(0xc000d0a7b8?)
Jan 23 20:08:35 debian11 x-ui[19012]: /opt/hostedtoolcache/go/1.21.5/x64/src/os/exec/exec.go:717 +0x2c
Jan 23 20:08:35 debian11 x-ui[19012]: created by os/exec.(*Cmd).Start in goroutine 6039
Jan 23 20:08:35 debian11 x-ui[19012]: /opt/hostedtoolcache/go/1.21.5/x64/src/os/exec/exec.go:716 +0xa0a
Jan 23 20:08:35 debian11 systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 23 20:08:35 debian11 systemd[1]: x-ui.service: Failed with result 'exit-code'.
Jan 23 20:08:35 debian11 systemd[1]: x-ui.service: Consumed 3min 15.115s CPU time.
Jan 23 20:08:40 debian11 systemd[1]: x-ui.service: Scheduled restart job, restart counter is at 104.
Jan 23 20:08:40 debian11 systemd[1]: Stopped x-ui Service.
Jan 23 20:08:40 debian11 systemd[1]: x-ui.service: Consumed 3min 15.115s CPU time.
Jan 23 20:08:40 debian11 systemd[1]: Started x-ui Service.
Jan 23 20:08:40 debian11 x-ui[19082]: 2024/01/23 20:08:40 x-ui 2.1.1
Jan 23 20:08:40 debian11 /usr/local/x-ui/x-ui[19082]: INFO - X-UI: web server run http on [::]:8484
Jan 23 20:08:40 debian11 /usr/local/x-ui/x-ui[19082]: INFO - X-UI: Remove Inbound User vida due the expire or traffic limit
Jan 23 20:08:40 debian11 /usr/local/x-ui/x-ui[19082]: INFO - X-UI: Remove Inbound User 15 last due the expire or traffic limit
Jan 23 20:08:40 debian11 /usr/local/x-ui/x-ui[19082]: INFO - X-UI: Remove Inbound User milad akbari N3 due the expire or traffic limit
Jan 23 20:08:40 debian11 /usr/local/x-ui/x-ui[19082]: INFO - X-UI: Remove Inbound User milad akbari N4 due the expire or traffic limit
Jan 23 20:08:40 debian11 /usr/local/x-ui/x-ui[19082]: INFO - X-UI: Remove Inbound User Mahna n1 due the expire or traffic limit
Jan 23 20:08:40 debian11 /usr/local/x-ui/x-ui[19082]: INFO - X-UI: Remove Inbound User R-man due the expire or traffic limit
Jan 23 20:08:40 debian11 /usr/local/x-ui/x-ui[19082]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
Jan 23 20:25:01 debian11 x-ui[19082]: panic: runtime error: slice bounds out of range [587:572]
Jan 23 20:25:01 debian11 x-ui[19082]: goroutine 24 [running]:
Jan 23 20:25:01 debian11 x-ui[19082]: x-ui/xray.(*LogWriter).Write(0xc000d38ce0, {0xc000d60000?, 0x3af, 0xc000577680?})
Jan 23 20:25:01 debian11 x-ui[19082]: /home/runner/work/3x-ui/3x-ui/xray/log_writer.go:35 +0x5e6
Jan 23 20:25:01 debian11 x-ui[19082]: io.copyBuffer({0x26c4d20, 0xc000d38ce0}, {0x26c4660, 0xc000a50010}, {0x0, 0x0, 0x0})
Jan 23 20:25:01 debian11 x-ui[19082]: /opt/hostedtoolcache/go/1.21.5/x64/src/io/io.go:432 +0x1f4
Jan 23 20:25:01 debian11 x-ui[19082]: io.Copy(...)
Jan 23 20:25:01 debian11 x-ui[19082]: /opt/hostedtoolcache/go/1.21.5/x64/src/io/io.go:389
Jan 23 20:25:01 debian11 x-ui[19082]: os/exec.(*Cmd).writerDescriptor.func1()
Jan 23 20:25:01 debian11 x-ui[19082]: /opt/hostedtoolcache/go/1.21.5/x64/src/os/exec/exec.go:560 +0x34
Jan 23 20:25:01 debian11 x-ui[19082]: os/exec.(*Cmd).Start.func2(0xc0000a7ea0?)
Jan 23 20:25:01 debian11 x-ui[19082]: /opt/hostedtoolcache/go/1.21.5/x64/src/os/exec/exec.go:717 +0x2c
Jan 23 20:25:01 debian11 x-ui[19082]: created by os/exec.(*Cmd).Start in goroutine 8
Jan 23 20:25:01 debian11 x-ui[19082]: /opt/hostedtoolcache/go/1.21.5/x64/src/os/exec/exec.go:716 +0xa0a
Jan 23 20:25:01 debian11 systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 23 20:25:01 debian11 systemd[1]: x-ui.service: Failed with result 'exit-code'.
Jan 23 20:25:01 debian11 systemd[1]: x-ui.service: Consumed 1min 40.405s CPU time.
Jan 23 20:25:06 debian11 systemd[1]: x-ui.service: Scheduled restart job, restart counter is at 105.
Jan 23 20:25:06 debian11 systemd[1]: Stopped x-ui Service.
Jan 23 20:25:06 debian11 systemd[1]: x-ui.service: Consumed 1min 40.405s CPU time.
Jan 23 20:25:06 debian11 systemd[1]: Started x-ui Service.

**Comment by ramtiny** [comment]
میشه بگید علتش چیه ؟
Cpu هر ۷&۸ ساعت میره حدود ۱۰۰ درصد
مشکل از چیه

**Comment by MHSanaei** [comment]
مشکل در اپدیت اخر برطرف شده مشکل از log_writer بود

**Comment by ramtiny** [comment]
ممنون از زحمات
من ازین روش پنل به پنل ریورس ۲۰ روزه استفاده میکنم
امروز به دلیل نامشخصی حدود ۱۵ دقیقه کلا برام تانل قطع بود
بعدش راه افتاد
دلیلش یعنی از دیتاسنتر بود یا این‌روش تانل؟
