### ISSUE TITLE
مشکل در ربات تلگرام

### ISSUE THREAD

**Issue by Mehdioop** [MHSanaei/3x-ui#1680]
![Screenshot_20240126_032320_Termius](https://github.com/MHSanaei/3x-ui/assets/125691282/27928942-fb08-4425-9d73-b1e05176020d)

![Screenshot_20240126_025821_Chrome](https://github.com/MHSanaei/3x-ui/assets/125691282/363d1772-f985-4a77-aa3d-9a7c9d377cca)
![Screenshot_20240126_025720_Telegram](https://github.com/MHSanaei/3x-ui/assets/125691282/d0c2acc5-d893-4b83-9f22-bc6c3ccb59d9)
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

با سلام و احترام، 
به نظر ربات تلگرام در اعلام اطلاعات کانفیگ کاربران مشکل داره، به ارسال دستور get usage و /usage Email پاسخ Your configuration is not found! میده. 
آیدی عددی کاربر به درستی در پنل وارد شده و این مشکل برای همه کاربران وجود داره.
نسخه پنل: 2.1.1
نسخه xray : 1.8.7
در ضمن بعد حتی بعد از ثبت کاربر پنل ریستارت هم شده ولی اثرگذار نبوده.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by javad8780** [comment]
سلام وقت بخیر
ممنون از زحماتی که میکشید 
در مورد مشکل مطرح شده ،بنده هم همین مشکل رو دارم 
در ورژن های قبلی تست کرده بودم حتی با ایدی هم کاربرا میتونستن اطلاعات اکانتشون رو مشاهده کنن ولی در آپدیت جدید وقتی پیام این دوستمون رو دیدم تست کردم متوجه شدم بله از کار افتاده رو ایدی دیگه جواب نمیده ولی رو ایدی عددی جواب میده مشکلی نداره

البته بنده رو سرور هیچ کاری انجام ندادم فقط از پنل توکن بات و ایدی عددی مدیریت رو وارد کردم 
اطلاعات مصرف و بکاپ هم هر روز برام به بات ارسال میشه

**Comment by Mehdioop** [comment]
> سلام وقت بخیر ممنون از زحماتی که میکشید در مورد مشکل مطرح شده ،بنده هم همین مشکل رو دارم در ورژن های قبلی تست کرده بودم حتی با ایدی هم کاربرا میتونستن اطلاعات اکانتشون رو مشاهده کنن ولی در آپدیت جدید وقتی پیام این دوستمون رو دیدم تست کردم متوجه شدم بله از کار افتاده رو ایدی دیگه جواب نمیده ولی رو ایدی عددی جواب میده مشکلی نداره
> 
> البته بنده رو سرور هیچ کاری انجام ندادم فقط از پنل توکن بات و ایدی عددی مدیریت رو وارد کردم اطلاعات مصرف و بکاپ هم هر روز برام به بات ارسال میشه

درود، 
بله برای ادمین به درستی کار میکنه و میتونه اطالاعات تمام کاربر ها رو دریافت کنه و از امکانات دیگه استفاده کنه ولی برای کاربری که سطح دسترسی ادمین رو نداره اصلا جواب نمیده، هم با آیدی بدون @ تست شده هم آیدی عددی

**Comment by javad8780** [comment]
> > سلام وقت بخیر ممنون از زحماتی که میکشید در مورد مشکل مطرح شده ،بنده هم همین مشکل رو دارم در ورژن های قبلی تست کرده بودم حتی با ایدی هم کاربرا میتونستن اطلاعات اکانتشون رو مشاهده کنن ولی در آپدیت جدید وقتی پیام این دوستمون رو دیدم تست کردم متوجه شدم بله از کار افتاده رو ایدی دیگه جواب نمیده ولی رو ایدی عددی جواب میده مشکلی نداره
> > البته بنده رو سرور هیچ کاری انجام ندادم فقط از پنل توکن بات و ایدی عددی مدیریت رو وارد کردم اطلاعات مصرف و بکاپ هم هر روز برام به بات ارسال میشه
> 
> درود، بله برای ادمین به درستی کار میکنه و میتونه اطلاعات تمام کاربر ها رو دریافت کنه و از امکانات دیگه استفاده کنه ولی برای کاربری که سطح دسترسی ادمین رو نداره اصلا جواب نمیده، هم با آیدی بدون @ تست شده هم آیدی عددی

درود
برای بنده رو ایدی عددی کار میکنه 
چک کنین ایدی رو که کپی میکنید ایپیس داخلش نیوفتاده باشه 
از قسمت تنظیمات گزینه اعلان ورود رو فعال کنین و از پنل خارج بشین مجددا لاگین کنین ببینین به بات اعلان ورود میاد براتون
اگه اعلان ورود ارسال شد یعنی تنظیمات بات درسته و مشکل قسمت ایدی کاربر هست که احتمالن کارکتر اضافه میگیره

ایدی عددی رو قبل از اینکه وارد کنین داخل یه نوت بزنین ببینین اگه اسپیس افتاده پاک کنین و وقتی ایدی رو ثبت کردین تو همون صفحه ورودی ها که کاربرا رو میاره قسمت عملیات یه گزینه داره که دایره هست وسطش علامت تعجب هست رو اون بزنین بعد قسمت تلگرام ایدی رو ایدی تلگرام کاربر کلیک کنین ببینین تلگرام باز میشه و صفحه پی وی اون کاربر میاد تو تلگرام یا نه

**Comment by Mehdioop** [comment]
> > > سلام وقت بخیر ممنون از زحماتی که میکشید در مورد مشکل مطرح شده ،بنده هم همین مشکل رو دارم در ورژن های قبلی تست کرده بودم حتی با ایدی هم کاربرا میتونستن اطلاعات اکانتشون رو مشاهده کنن ولی در آپدیت جدید وقتی پیام این دوستمون رو دیدم تست کردم متوجه شدم بله از کار افتاده رو ایدی دیگه جواب نمیده ولی رو ایدی عددی جواب میده مشکلی نداره
> > > البته بنده رو سرور هیچ کاری انجام ندادم فقط از پنل توکن بات و ایدی عددی مدیریت رو وارد کردم اطلاعات مصرف و بکاپ هم هر روز برام به بات ارسال میشه
> > 
> > 
> > درود، بله برای ادمین به درستی کار میکنه و میتونه اطلاعات تمام کاربر ها رو دریافت کنه و از امکانات دیگه استفاده کنه ولی برای کاربری که سطح دسترسی ادمین رو نداره اصلا جواب نمیده، هم با آیدی بدون @ تست شده هم آیدی عددی
> 
> درود برای بنده رو ایدی عددی کار میکنه چک کنین ایدی رو که کپی میکنید اسپیس داخلش نیوفتاده باشه از قسمت تنظیمات گزینه اعلان ورود رو فعال کنین و از پنل خارج بشین مجددا لاگین کنین ببینین به بات اعلان ورود میاد براتون اگه اعلان ورود ارسال شد یعنی تنظیمات بات درسته و مشکل قسمت ایدی کاربر هست که احتمالن کارکتر اضافه میگیره
> 
> ایدی عددی رو قبل از اینکه وارد کنین داخل یه نوت بزنین ببینین اگه اسپیس افتاده پاک کنین و وقتی ایدی رو ثبت کردین تو همون صفحه ورودی ها که کاربرا رو میاره قسمت عملیات یه گزینه داره که دایره هست وسطش علامت تعجب برعکس هست رو اون بزنین بعد قسمت تلگرام ایدی رو ایدی تلگرام کاربر کلیک کنین ببینین تلگرام باز میشه و صفحه پی وی اون کاربر میاد تو تلگرام یا نه

اعلان ورود رو چک کردم و ارسال شد.
آیدی عددی رو دوباره چک کردم و هیچ اسپیس یا کاراکتر اضافه ای اول و آخر و وسطش نبود .
درباره لینک تلگرامی که تو قسمت اینفورمیشن هم قرار گرفته تست کردم و به پی وی کاربر هدایت نشد. لینکی که اونجا قرار گرفته : https://t.me/1203864614
برای کاربر های مختلف چک کردم. آیا لینکی که برای شما قرار گرفته ساختارش به همین صورته؟

**Comment by javad8780** [comment]
خیلی عجیبه دوباره تست کردم ایدی عددی که اول میده جواب نمیده !
بعد که با تلگرام کاربر میری درخواست میدی اون ایدی عددی که دوباره به کاربر میده رو وارد میکنی جواب میده !

**Comment by Mehdioop** [comment]
> > > > > سلام وقت بخیر ممنون از زحماتی که میکشید در مورد مشکل مطرح شده ،بنده هم همین مشکل رو دارم در ورژن های قبلی تست کرده بودم حتی با ایدی هم کاربرا میتونستن اطلاعات اکانتشون رو مشاهده کنن ولی در آپدیت جدید وقتی پیام این دوستمون رو دیدم تست کردم متوجه شدم بله از کار افتاده رو ایدی دیگه جواب نمیده ولی رو ایدی عددی جواب میده مشکلی نداره
> > > > > البته بنده رو سرور هیچ کاری انجام ندادم فقط از پنل توکن بات و ایدی عددی مدیریت رو وارد کردم اطلاعات مصرف و بکاپ هم هر روز برام به بات ارسال میشه
> > > > 
> > > > 
> > > > درود، بله برای ادمین به درستی کار میکنه و میتونه اطلاعات تمام کاربر ها رو دریافت کنه و از امکانات دیگه استفاده کنه ولی برای کاربری که سطح دسترسی ادمین رو نداره اصلا جواب نمیده، هم با آیدی بدون @ تست شده هم آیدی عددی
> > > 
> > > 
> > > درود برای بنده رو ایدی عددی کار میکنه چک کنین ایدی رو که کپی میکنید اسپیس داخلش نیوفتاده باشه از قسمت تنظیمات گزینه اعلان ورود رو فعال کنین و از پنل خارج بشین مجددا لاگین کنین ببینین به بات اعلان ورود میاد براتون اگه اعلان ورود ارسال شد یعنی تنظیمات بات درسته و مشکل قسمت ایدی کاربر هست که احتمالن کارکتر اضافه میگیره
> > > ایدی عددی رو قبل از اینکه وارد کنین داخل یه نوت بزنین ببینین اگه اسپیس افتاده پاک کنین و وقتی ایدی رو ثبت کردین تو همون صفحه ورودی ها که کاربرا رو میاره قسمت عملیات یه گزینه داره که دایره هست وسطش علامت تعجب برعکس هست رو اون بزنین بعد قسمت تلگرام ایدی رو ایدی تلگرام کاربر کلیک کنین ببینین تلگرام باز میشه و صفحه پی وی اون کاربر میاد تو تلگرام یا نه
> > 
> > 
> > اعلان ورود رو چک کردم و ارسال شد. آیدی عددی رو دوباره چک کردم و هیچ اسپیس یا کاراکتر اضافه ای اول و آخر و وسطش نبود . درباره لینک تلگرامی که تو قسمت اینفورمیشن هم قرار گرفته تست کردم و به پی وی کاربر هدایت نشد. لینکی که اونجا قرار گرفته : https://t.me/1203864614 برای کاربر های مختلف چک کردم. آیا لینکی که برای شما قرار گرفته ساختارش به همین صورته؟
> 
> بله ساختارش همینه ولی به پی وی کاربر میره وقتی روش کلیک میکنم به وی پی ان وصل هستین دیگه ؟ بنده الان این لینکی که دادینو تست کردم صحیح نیست و وی پی باز نمیشه اگه کاربر رو داخل تلگرام ادد دارین این مراحلی که میگم رو تست کنین وارد بات بشین با دستور /usage [ایمیل] جای ایمیل اسم کاربر که ثبت کردید رو بزنید یه سری منو میاره گزینه یکی به آخر (تنظیم کاربر تلگرام) رو بزنید بعدش انتخاب کاربر و کاربر مورد نظرتون رو انتخاب کنین و تایید کنین بعد از پنل ادیتش کنین ببینین ایدیش وارد شده یا نه و از همون قسمتی که تو پیام بالا گفتم تست کنین ببینین پی وی کاربر براتون باز میشه اگه شد یعنی اوکی هست
> 
> اینطوری با این روش دیگه نیاز هم نیست کاربرا ایدی عددی بگیرن براتون بفرستن ،خودتون میتونین توی تلگرام مخاطبو اضافه کنین بعد از بات شناسشو توی حسابش وارد کنین برای راحتی کار منو پنل و بات هم فارسی کنین

بله دقیقا همین مراحل رو از طریق ربات هم انجام دادمT شما گفتی دوباره انجام دادم و ایدی عددی که از طریق ربات و انتخاب مخاطب تنظیم کردم توی پنل هم به درستی وارد شد ولی باز هم کار ساز نبود. حتی به کلی ربات و توکن رو هم عوض کردم. درضمن دیتابیس رو به تازگی از نسخه آخر علیرضا به سنایی انتقال دادم که این مشکل پیش اومد

**Comment by javad8780** [comment]
نه بخاطر دیتابیس فکر نکنم باشه چون من از اول رو سنایی بودم و الان همین مشکل رو دارم
حس میکنم از سمت تلگرام هست چون ایدی عددی باید تهت هر شرایط توی خود تلگرام حداقل باز شه !
حالا بازم بررسی میکنم اگه به نتیجه ای رسیدم اطلاع میدم که شما هم انجام بدی

**Comment by Mehdioop** [comment]
ممنون از وقتی که گذاشتید🙏

**Comment by alimattaji** [comment]
تو نسخه جدید این مشکل پیش اومده
و تنها راه حلش اینه که بعد از اینکه کاربر مورد نظر رو با ربات ست کردیم، باید بریم تو ویرایش همون کلاینت در پنل سنایی ، و اون یه فاصله که آخر آیدی تلگرام طرف افتاده رو دستی پاک کنیم و ذخیره کنیم
در واقع در آپدیت جدید به اشتباه یک فاصله یا همون یک اسپیس در انتهای  آیدی ذخیره میشه
