### ISSUE TITLE
امکانات مورد نیاز و باگ ها (جهت بهتر شدن این پروژه)

### ISSUE THREAD

**Issue by javad8780** [MHSanaei/3x-ui#1681]
سلام و احترام

ممنون از زحماتی که برای توسعه این پروژه میکشید

**چندتا مورد هست که پیشنهاد میکنم اگه مقدور بود اضافه کنید به پنل و یه سری مشکلات هم هست که اگه ممکنه رفع بشه**

1-وقتی از منو تنظیمات ،زبان پنل رو ست میکنیم ثابت نمیمونه و موقع ورود مجدد دوباره زبان رو انگلیسی هست و باید دوباره تغییر بدیم بعد وارد بشیم ،این مورد حل بشه وقتی ست میکنیم از پنل مدیریت ،زمان ورود مجدد رو همون زبان برامون باز بشه و رو زبان فارسی اگه راستچین میشد عالی بود .

2-قسمت هدر صفحه ورودی ها توی پنل ،نمایش (دریافت/ارسال ،مصرف کل و کاربران آنلاین و ... )بصورت خودکار آنلاین نمایش داده بشه (مثل صفحه اصلی که مقدار رم و سی پی یو رو آنلاین نمایش میده )و قسمت رفرش خودکار فقط برای نمایش باکس وسط باشه تا اگه خواستیم فعالش کنیم .

3-وقتی کاربرا تاریخ یا حجمشون تمام میشه فعال میمونن و غیرفعال نمیشن (البته ارتباطشون قطع میشه مشکلی نداره) این مورد حل بشه و پس از اتمام حجم یا تاریخ غیرفعال بشن ،درواقع وقتی منقضی میشن غیرفعال هم بشن .

4-وقتی چند ورودی اضافه میکنیم برای مثال چند پورت باز میکنیم که از قابلیت ساب استفاده کنیم و کاربر همه ی اون پورت ها رو داشته باشه زمانی که کاربر حجم یا تاریخش تموم میشه ریست جواب نمیده و دوباره برمیگرده به حالت قبل و باید دونه دونه کلاینت اون کاربر ویرایش بشه و اسم Subscription که برای کاربر کلاینت در نظر گرفتیمو حذف کنیم بعد تاریخ و حجم رو ریست کنیم و دوباره اسم Subscription رو براش وارد کنیم و این مورد خیلی زمان بر و آزار دهنده هست .

5-قابلیت انتخاب یوزرهایی که میخوایم ریست یا خذف یا غیرفعال کنیم اضافه بشه (مثلا ریست ترافیک کاربران انتخاب شده یا حذف یا ...)

6-ربات تلگرام قبلا تو ورژن های قبلی وقتی یوزر تلگرام کاربر رو وارد میکردیم میتونست اطلاعات اکانتشو از بات چک کنه ولی تو ورژن جدید نه با ایدی عددی جواب میده نه یوزر ،آیدی عددی رو که وارد میکنیم فقط یبار کاربر میتونه اطلاعاتشو ببینه بعدش میزنه پیکربندی شما یافت نشد !

7-اگه پنل ریسپانسیو بود و روی موبایل هم میشد راحت باهاش کار کرد خیلی خوب میشد برای پشتیبانی و بررسی راحتتر کاربرا در هر زمان ، یا یه صفحه مدیریت برای موبایل در نظر گرفته میشد .

8-اگه یه گزینه بود موقع اضافه کردن کلاینت توو یه اینباند میشد تیک اینباند های دیگه که ساختیم رو هم زد که کاربر به اون اینباند ها هم اضافه بشه عالی میشد ،چون الان ما 4 پورت باز کردیم (چون ای پی بلاک شده و از کلود استفاده میکنیم ) و بخاطر اینکه ساب بدیم به کاربر و همه ی پورت ها یا همون اینباند ها رو داشته باشه باید بصورت جدا جدا تو هر اینباند کلاینت رو اضافه کنیم و Subscription رو یک شکل قرار بدیم تا توی Subscription این پورت یا کانفیگ ها رو برای کلاینت نمایش بده و قابل استفاده باشه براش .

9-وقتی کلاینت اضافه میشه و Subscription رو یک شکل قرار میدیم حجم همه ی اینباند های کاربر باهم ست میشه و مصرف شده یا باقی مونده رو تو همه ی اینباند ها برای کاربر درست نمایش میده با هر اینباندی که وصل بشه ولی تاریخشون ست نمیشه باهم و اگه یکی از اینباندها تاریخش تموم شه از بقیه اینباندها میتونه استفاده کنه تا تاریخ اون کلاینت تو اون اینباند هم تموم شه ،این مورد هم اگه حل بشه عالی میشه .

بقیه امکانات و موارد عالی و بی نقص هستن 

پیشاپیش ممنون از شما بابت تمام زحماتتون

**Comment by mohamad15516** [comment]
داداش دمت گرم چیز های خوبی درخواست کردی اما به نظرم غیر مفید و غیر کاربردی هستند و به جای این که اقای ثنایی وقتش رو روی این چیز ها بزاره به نظرم روی امکانات کاربردی تر و کارهایی و روشهایی که بتونه خیلی بهتر وبیشتر فیلترینگ رو دور بزنه این امکاناتی که شما فرمودید بیشتر برای فروشنده ها هست واگر شما فروشنده هستید به نظرم یکم سرکیسه رو شل کنید و پنل xmplus رو نصب کنید کلی امکاناتی که الان گفتین رو بیشتر و کاملتر داره دستتون هم بازه برای هر کاری کلان برای فروشنده ها هست این پنل ها هم خیلی ساده برای کاربری عمومی هست هرچند من از نظرات شما حمایت میکنم اما الان توی موقعیتی نیستیم که این امکانات رو اضافه کنه چون فیلترینگ خیلی شدیدتر هست و همونطور هم که خودت میدونی اخرین روش یعنی ریالتی هم یه راحتی مسدود میشه پس فرصت محدوده و خلاقیت کم

**Comment by javad8780** [comment]
> داداش دمت گرم چیز های خوبی درخواست کردی اما به نظرم غیر مفید و غیر کاربردی هستند و به جای این که اقای ثنایی وقتش رو روی این چیز ها بزاره به نظرم روی امکانات کاربردی تر و کارهایی و روشهایی که بتونه خیلی بهتر وبیشتر فیلترینگ رو دور بزنه این امکاناتی که شما فرمودید بیشتر برای فروشنده ها هست واگر شما فروشنده هستید به نظرم یکم سرکیسه رو شل کنید و پنل xmplus رو نصب کنید کلی امکاناتی که الان گفتین رو بیشتر و کاملتر داره دستتون هم بازه برای هر کاری کلان برای فروشنده ها هست این پنل ها هم خیلی ساده برای کاربری عمومی هست هرچند من از نظرات شما حمایت میکنم اما الان توی موقعیتی نیستیم که این امکانات رو اضافه کنه چون فیلترینگ خیلی شدیدتر هست و همونطور هم که خودت میدونی اخرین روش یعنی ریالتی هم یه راحتی مسدود میشه پس فرصت محدوده و خلاقیت کم

ممنون از نظرتون ولی از دید یه فروشنده این درخواست رو نکردم که بحث مالی رو میکشید وسط 
بیشتر هم باگ ها رو گفتم تا امکانات خاصی
با کمک همین دوستان فعلا به یه کانفیگ پایدار رسیدیم که داره خوب جواب میده و این باگها کمی داره کار رو دشوار میکنه 
پیشنهاد میکنم دوباره پیام بالا بنده رو بخونید شاید بد خوندید درست متوجه نشدید که فقط درخواست اضافه  کردن امکانات نیست بیشتراش باگ هست که اگه رفع بشه عالی میشه این پروژه 
بازم همینجا دوباره از زحمات این دوستان تشکر میکنم که تو این اوضاع کمک بزرگی دارن به هممون میکنن
