### ISSUE TITLE
 get xray traffic failed rpc error

### ISSUE THREAD

**Issue by darhelm** [MHSanaei/3x-ui#1684]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

X-UI: get xray traffic failed:rpc error: code = Unknown desc = app/stats/command: QueryStats only works its own stats.Manager.
X-UI: get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: read tcp 127.0.0.1:59140->127.0.0.1:62789: read: connection reset by peer"
can't track changes in bandwidth usage either
other than this there seems to be no further errors neither in the panel nor cli 

### Version of 3x-ui

<details>

```console
x-ui latest update V 2.1.1
core version V 1.8.7
```

</details>

### x-ui log reports or xray log

<details>

```console

WARNING:
X-UI: get xray traffic failed:rpc error: code = Unknown desc = app/stats/command: QueryStats only works its own stats.Manager.
 X-UI: get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: read tcp 127.0.0.1:59140->127.0.0.1:62789: read: connection reset by peer"
```

</details>

**Comment by sedsajjad313** [comment]
Same me.

**Comment by Lolsmashir** [comment]
same

**Comment by MrChimadan** [comment]
and same

**Comment by mohammadi939** [comment]
منم این ارور رو دارم ، لطفا اگه مهمه یه پاسخ بدین تا بفهمیم قضیه‌ش چیه
