### ISSUE TITLE
how to set certificates in docker mode

### ISSUE THREAD

**Issue by shahrooz1397** [MHSanaei/3x-ui#1685]
سلام من رو یه ابونتو ۲۰۱۸ با داکر نصب کردم چون پیشنیاز نسخه ۲۰ به بالا هست 
الان مسیر سرتیفیکیت هارو 
/root/certs/fullchain.pem
به این صورت میدم شناسایی نمیکنه میگه همچین پوشه وجود نداره 
چون تو محیط داکر نصب شده و به روت سیستم دسترسی نداره 
فایل های سرتیفیکیت دارم میشه بگید به کجا انتقال بدم منظورم پوشه دیتای ایمیج ایکس یو ای کجاست به کجا انتقال بدم که شناسایی کنه

**Comment by HeinzBrr** [comment]
> سلام من رو یه ابونتو ۲۰۱۸ با داکر نصب کردم چون پیشنیاز نسخه ۲۰ به بالا هست الان مسیر سرتیفیکیت هارو /root/certs/fullchain.pem به این صورت میدم شناسایی نمیکنه میگه همچین پوشه وجود نداره چون تو محیط داکر نصب شده و به روت سیستم دسترسی نداره فایل های سرتیفیکیت دارم میشه بگید به کجا انتقال بدم منظورم پوشه دیتای ایمیج ایکس یو ای کجاست به کجا انتقال بدم که شناسایی کنه

I got it like this:
cp -RL /etc/letsencrypt/live/YOUR_DOMEN/* /root/3x-ui/cert/

And fill in the panel like this:
/root/cert/fullchain.pem
/root/cert/privkey.pem

**Comment by NolPixel** [comment]
sheet,, I just cp and not using -RL flag. It's cause only copy symlink file. Anyway, thankyou @HeinzBrr
