### ISSUE TITLE
خطا در بات تلگرام

### ISSUE THREAD

**Issue by Hesam-Mahmoodi** [MHSanaei/3x-ui#1690]
### Welcome

- [x] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

خطا در بات تلگرام
`Your configuration is not found!
Please ask your admin to use your Telegram ID in your configuration(s).

Your User ID: *********`

بعد آپدیت از ورژن [2.0.1] به ورژن [v2.1.2] این اتفاق افتاد
فقط کاربری که در تنظیمات پنل ID آن را به عنوان ادمین معرفی کردم دسترسی داره و کاربر هایی دیگه خطای بالا رو میگیرن درصورتی که قبلا این طور نبود و هر کاربری با تلگرام خودش میتونست اطلاعات و حجم اکانتی که خودش داشت رو ببینه!
و با /usage هم میتونست برای کاربر های دیگه هم ببینه...

**Comment by Mehdioop** [comment]
از قابلیت multi protocol استفاده میکنید?

**Comment by Hesam-Mahmoodi** [comment]
> از قابلیت multi protocol استفاده میکنید?
خیر
جالب اینجاست که id تلگرام کاربر هم که تو تعریف اکانت میزدم هم دیگه کار نمیکنه و فقط /id که عدد هستش کار میکنه و وقتی از /usage استفاده میکنم تو این حالت دیگه خطا اولیه که بالا گفتم رو نمیده بجاش میزنه !No result
خیلی عجیبه انگار تو این چند تا آپدیت آخر قسمت بات تلگرامش خراب شده..!

**Comment by Mehdioop** [comment]
منم دقیقا همین مشکلو دارم  فکر میکردم بخاطر این اسکریپته ، پس مشکل جای دیگه ست.

**Comment by ashkan-moghadasi** [comment]
بله در نسخه فکر می کنم 2 به بعد عملا ربات با دستور getusage/ uuid درست کار نمی کنه حتی نسخه 2.0.1 هم من دارم جوا نمیده
حتی با تنظیم telegramid در کانفیگ کاربر . ربات یکی در میون با دستور getusage جواب میده

**Comment by MHSanaei** [comment]
/usage uuid 
در اپدیت ۲ به بعد از بات حذف شده بجاش فقط میتونید با ایمیل بگیرید و لازمه که چت ایدی تلگرام مشتریتون رو هم روی اون اکانت ست کرده باشید
