### ISSUE TITLE
Telegram Bot Error: Bad Request - File must be non-empty

### ISSUE THREAD

**Issue by mehdikhody** [MHSanaei/3x-ui#1703]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I have activated a Telegram bot to send backups to me every hour. Every time a backup is sent to Telegram, the following error message is recorded in the server log:

```log
ERROR - Error in uploading backup:  telego: sendDocument(): api: 400 "Bad Request: file must be non-empty"
ERROR - Error in uploading config.json:  telego: sendDocument(): api: 400 "Bad Request: file must be non-empty"
ERROR - Error in uploading backup:  telego: sendDocument(): api: 400 "Bad Request: file must be non-empty"
Error in uploading config.json:  telego: sendDocument(): api: 400 "Bad Request: file must be non-empty"
```

What should I do to resolve this error?

### Version of 3x-ui

<details>

```console
v2.1.2
```

</details>

### x-ui log reports or xray log

<details>

```console
ERROR - Error in uploading backup:  telego: sendDocument(): api: 400 "Bad Request: file must be non-empty"
ERROR - Error in uploading config.json:  telego: sendDocument(): api: 400 "Bad Request: file must be non-empty"
ERROR - Error in uploading backup:  telego: sendDocument(): api: 400 "Bad Request: file must be non-empty"
Error in uploading config.json:  telego: sendDocument(): api: 400 "Bad Request: file must be non-empty"
```

</details>

**Comment by Mahdimkkkm** [comment]
Is your problem solved? I also ran into this problem

**Comment by MHSanaei** [comment]
update to the latest version
