### ISSUE TITLE
What do the settings mean ? 

### ISSUE THREAD

**Issue by Trenobol** [MHSanaei/3x-ui#1707]
Hi!
Where can I read what each of the settings means and what it affects?

Show
xver
sniffing
eternal/transparent proxy
HTTP mask and everything inside

Do you have any FAQ?
Thanks

**Comment by mehdikhody** [comment]
https://xtls.github.io/en/config

**Comment by Birddle** [comment]
> Show
> xver

There have nothing about 'Show' or 'xver'

**Comment by MHSanaei** [comment]
@Birddle 
https://github.com/XTLS/REALITY/blob/main/README.en.md

"show": false, // Optional, if true, output debugging information
"xver": 0, // Optional, the format is the same as xver of VLESS fallbacks
