### ISSUE TITLE
warp

### ISSUE THREAD

**Issue by proxystore11** [MHSanaei/3x-ui#1708]
کسی تونسنه تو اپدیت جدید وارپ فعال کنه

**Comment by sohate** [comment]
No , I can't. Here's my post https://github.com/MHSanaei/3x-ui/issues/1706

**Comment by qar4al** [comment]
ورژن قبلی یکم کار کرد . این وژن کلا کار نمیکنه

**Comment by niiaco** [comment]
برید داخل پنل از بخش وارپ یک لایسنس وارپ رو اضافه کنید سپس add outbound زیرشو بزنید تا تنظیمات براتون فعال بشه

**Comment by sohate** [comment]
@niiaco already did. I did everything. Nothing works.

**Comment by Dwnill** [comment]
وارپ رو از طریق ssh خود پنل نصب کن شماره ۱۹ هست و بعد تو قسمت خروجی های پنل تحت وب  به صورت دستی وارد کن . به صورت پیشفرض روی پورت 127.0.0.1:40000
هست مگر اینکه پورت رو موقع نصب عوض کنی  برو تو خروجی ها add و بعد روی socks تنظیم کن ایپی و پورت مثل همونی که بالا گفتم بزن 
بعد تو بخش مسیریابی کاربر یا ورودیتو تعریف کن .....

**Comment by MHSanaei** [comment]
دوستانی که مشکل وارپ با وایرگارد پنل دارن نسخه 2.1.3 رو نصب کنند و دکمه reset to default رو بزنند و مجدد وارپ رو فعال کنند مشکلتون حل خواهد شد
