### ISSUE TITLE
Add language

### ISSUE THREAD

**Issue by lihin929** [MHSanaei/3x-ui#1710]
Can i Help add other languages?

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/tree/main/web%2Ftranslation

**Comment by lihin929** [comment]
[translate.id_ID.toml.txt](https://github.com/MHSanaei/3x-ui/files/14096467/translate.id_ID.toml.txt)
here bro, i hove you add :)

**Comment by lihin929** [comment]
> https://github.com/MHSanaei/3x-ui/tree/main/web%2Ftranslation

**Comment by MHSanaei** [comment]
Bro explain what language is this ?

**Comment by lihin929** [comment]
> Bro explain what language is this ?

Indonesia 🇮🇩

Bro

**Comment by lihin929** [comment]
> Bro explain what language is this ?

I hove your add bro

**Comment by MHSanaei** [comment]
thank you
