### ISSUE TITLE
ساعت ربات اشتباهه موقع بکاپ 

### ISSUE THREAD

**Issue by pouya13810216** [MHSanaei/3x-ui#1712]
ساعت ربات اشتباهه موقع بکاپ 
![image](https://github.com/MHSanaei/3x-ui/assets/135587031/c8243156-4192-4d79-8996-26a1b6ebbb39)

**Comment by Masouddhojaei** [comment]
درود 
باید تایم زون سرور رو به منطقه Asia/Tehran تغییر بدید به این روش
https://linuxize.com/post/how-to-set-or-change-timezone-on-ubuntu-20-04/
