### ISSUE TITLE
فعال سازی node برای اتصال چند کشور به هم

### ISSUE THREAD

**Issue by milad-ahadpour** [MHSanaei/3x-ui#1713]
مهندس تو این شرایط که حتی دیتا سنتر های داخلی هم به اختلال میخورن به نظرم node خیلی واجب و به ما کمک میکنه با یک لینک چند سرور و چند کشور رو در اختیار مشتری قرار بدیم و ارتباط استیبلی بگیریم.

**Comment by amirooo70** [comment]
میتونید هر اینباند در سرور داخلی رو به اوتباند یک سرور خارجی جدا وصل کنید و به این ترتیب چندین سرور خارجی ارائه بدید

**Comment by neerro** [comment]
> میتونید هر اینباند در سرور داخلی رو به اوتباند یک سرور خارجی جدا وصل کنید و به این ترتیب چندین سرور خارجی ارائه بدید

لطفاً، مثال‌هایی از چگونگی انجام این کار را بیان کنید.

**Comment by milad-ahadpour** [comment]
ببینید داستان اینه که ما یک پنل مادر داریم تو این روش و مهم تر از اون اینه که بقیه سرور های کشور ها از این سرور عبور میکنه و سوال اصلی اینه که اگه پنل اصلی روی ایران باشه و اون سرور هایی که بهش وصل میشه ترافیکش از سرور مادر عبور میکنه یا هر کدوم به سمت سرور خودش فرستاده میشه؟
و یک سوال دیگه اینه که میشه مثلا ۴ تا سرور بهش کانکت کرد و کانفیگی که مشتری میگیره همه سرور ها براش بیوفته ، این کار توسط subscrip انجام میشه؟
