### ISSUE TITLE
جایگذینی پنل سنایی بحای علیرضا

### ISSUE THREAD

**Issue by javadmahmoodi670** [MHSanaei/3x-ui#1717]
سلام 
من پنل علیرضا را دارم. میخوام بیام و سنایی نصب کنم. 
چیکار کنم کانفیگ یوزرهام بهم نخوره و بعد نصب سنایی(جایگذینی پنل سنایی جای علیرضا) کاربرام با همون کانفیگی که داشتن بدون مشکل وصل بشن و نیاز نباشه بهشون مجدد کانفیگ بدم. 
ممنون میشم راهنمایی کنید

**Comment by javadmahmoodi670** [comment]
الان بیام و از اینباندم کپی بگیرم و بعد تو همین سرور دستور نصب پنل سنایی روبزنم پنل نصب میشه تا بعد اینباندم رو تو پنل جدید قرار بدم؟ یا باید اول پنل علیرضا پاک کنم و بعد سنایی رو نصب کنم؟!

**Comment by Arman-nsb** [comment]
اگر فقط یه اینباند رو میخواد منتقل کنید بله ولی اگر کل دیتابیس xui رو میخواید منتقل کنید از بخش داشبورد گزینه بکاپ رو استفاده کنید تا همه چی رو منتقل کنه براتون. ( حتی تنظیمات xray و یوزرنیم پسورد ادمینی پنل )

![image](https://github.com/MHSanaei/3x-ui/assets/84615037/72789b83-c387-4c42-b1f2-3d80773ab105)

**Comment by javadmahmoodi670** [comment]
> اگر فقط یه اینباند رو میخواد منتقل کنید بله ولی اگر کل دیتابیس xui رو میخواید منتقل کنید از بخش داشبورد گزینه بکاپ رو استفاده کنید تا همه چی رو منتقل کنه براتون. ( حتی تنظیمات xray و یوزرنیم پسورد ادمینی پنل )
> 
> 
> 
> ![image](https://github.com/MHSanaei/3x-ui/assets/84615037/72789b83-c387-4c42-b1f2-3d80773ab105)
> 
> بعد از اینکه پنل سنایی رو نصب کردید، گزینه restore رو بزنید و فول بکاپی که از پنل علیرضا خروجی گرفتین رو بهش بدید. ( ترجیحا تنظیمات xray رو یکبار ریست به پیشفرض کنید و مجدد ست کنید تا تداخل احتمالی رخ نده بین 2 پنل )
> 
> 

ممنون. اینجوری دیگه نیاز نیست به کاربرام چیزی بدم برای اتصال و با همون کانفیگی که داشتن وصل میشن. درسته؟

**Comment by Arman-nsb** [comment]
بله درصورتی که روی سرور فعلی راه اندازی بشه و تغییر آی پی رخ نده کاربرها اتصالشون عین قبل کار میکنه.
