### ISSUE TITLE
در تانل پنل به پنل ، دسترسی به سایت های ایرانی مسدود نمیشه

### ISSUE THREAD

**Issue by GithubUN89** [MHSanaei/3x-ui#1720]
سلام 
دو سرور ایران و خارج رو بصورت معکوس ، پنل به پنل کردم ، اما بعد از فعال کردن مسدود کردن سایت های ایرانی ، دسترسی به سایت های ایرانی مسدود نمیشه 

لطفاً رفعش کنید 
ممنون

**Comment by neon-bartmoss** [comment]
منم این مشکل رو دارم 
هم در سرور ایران و هم خارج دسترسی به سایت های ایرانی رو بستم ولی کار نمیکنه

**Comment by MHSanaei** [comment]
سلام یکبار دکمه reset to default رو بزنید و مجدد تنظیمات مورد نظرتون رو فعال کنید

**Comment by ahmadipiralvan** [comment]
> سلام یکبار دکمه reset to default رو بزنید و مجدد تنظیمات مورد نظرتون رو فعال کنید

سلام مهندس
ظاهرا تو نسخه جدید geoip برای routing به مشکل خورده.
آی پی های ایرانی رو شناسایی نمیکنه.

**Comment by ahmadipiralvan** [comment]
> سلام دو سرور ایران و خارج رو بصورت معکوس ، پنل به پنل کردم ، اما بعد از فعال کردن مسدود کردن سایت های ایرانی ، دسترسی به سایت های ایرانی مسدود نمیشه
> 
> لطفاً رفعش کنید ممنون

هر دو پارامتر IP و Domain رو فعال کنید. مشکل حل میشه. یه تغییر ریز تو Xray اعمال شده.
