### ISSUE TITLE
عدم امکان وارد کردن headr request برای WS

### ISSUE THREAD

**Issue by shobeirak** [MHSanaei/3x-ui#1722]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

در هنگام ایجاد کانفیگ با ws امکان وارد کردن headr reques وجود ندارد

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Arman-nsb** [comment]
طبق تصویر میتونید با زدن علامت + جلوی request header و تنظیم مقدار Host این مورد رو پیاده سازی کنید:
![image](https://github.com/MHSanaei/3x-ui/assets/84615037/1daea992-b8b0-4400-9584-805237d80a1f)
