### ISSUE TITLE
عدم نمایش کاربران آنلاین در هنگام استفاده از وارپ

### ISSUE THREAD

**Issue by RAfrwrk** [MHSanaei/3x-ui#1727]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

با سلام و خسته نباشید ممنون از زحماتتون
وقتی وارپ رو در قسمت روتینگ در اولویت اول قرار می دهیم کاربران آنلاین در پنل نمایش داده نمی شوند دلیل آن هم این است که برای خواندن اطلاعات کاربر در فرآیند مسیریابی است (Routing) و این باید در قسمت قبل از مسیریابی (PreRouting)باشد و همچنین مشکل این عزیز هم برای پنل به پنل ریوس با پکت خوانی در مرحله PreRouting  حل می شود.
تانل ریورس - مشکل یوتوب - اسپاتیفای - چت جی پی تی - پابجی #1724

ممنون از زحمات بی پایان شما عزیزان

### Version of 3x-ui

<details>

```console
# 2.1.2

```

</details>

### x-ui log reports or xray log

<details>

```console


</details>

**Comment by RAfrwrk** [comment]
با تغییر در ترتیب روتینگ خروجی در قسمت xray پنل، پنل حجم اکانت ها را هم حساب نمی کند

**Comment by MHSanaei** [comment]
اولویت اهمیت داره
