### ISSUE TITLE
حذف وارپ

### ISSUE THREAD

**Issue by piuma1** [MHSanaei/3x-ui#1730]
سلام. من میخوام وارپ رو حذف کنم ب طوری که وقتی روی گزینه warp تو بخش outbound می زنم بتونم دوباره create رو ببینم اما هر کاری میکنم یازم همون وارپ ساخته شده میاد

**Comment by MHSanaei** [comment]
Reset to default

**Comment by piuma1** [comment]
زدم ولی متاسفانه اونجایی که باید گزینه create بیاد نمیاد و وارپ همچنان ساخته شده نشون میده. با همون access token و  key هایی که گرفته بود

**Comment by piuma1** [comment]
بک آپ رو منتقل کردم به یه سرور دیگه و دوباره reset to default زدم ولی بازم create نمیاد
