### ISSUE TITLE
حذف نشدن وارپ بعد از reset to default

### ISSUE THREAD

**Issue by piuma1** [MHSanaei/3x-ui#1731]
سلام. من بعد از اینکه پنل رو ریست کردم ولی بازم وقتی warp رو میزنم دکمه create نمیاد و همون تنظیمات قبل مثل access token  و key هایی که گرفته بود برمیگرده. بک آپ ریستور رو سرور جدید کردم هم مشکل حل نشد.

**Comment by piuma1** [comment]
مشکلی که توش گیر کردم اینه که براش  premium key گرفتم و حالا میخوام از بدون پرمیوم استفاده کنم ولی تنظیماتش مونده و نمیتونم از نسخه free استفاده کنم. create هم نمیاد که دوباره یکی جدید بگیرم

**Comment by Arman-nsb** [comment]
شما میتونی از این ربات تلگرامی که لایسنس وارپ+ میده استفاده کنی:
https://t.me/generatewarpplusbot
حتما از لایسنس وارپ+ استفاده کن، سرعت و کیفیت بهتری داره. نیازی به حذف چیزی هم نیست فقط قسمت outbounds گزینه warp رو بزن و لایسنسی که از ربات میگیری رو وارد کن.
