### ISSUE TITLE
1 [Warning] [2657169757] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp 188.114.96.3:12171: i/o timeout dial tcp: lookup ux.*****.ir: operation was canceled] > common/retry: all retry attempts failed

### ISSUE THREAD

**Issue by Mr-persian** [MHSanaei/3x-ui#1732]
2024/02/02 18:50:04 [Warning] [3180605360] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp 188.114.97.3:12171: i/o timeout] > common/retry: all retry attempts failed
2024/02/02 18:50:04 [Warning] [3734704463] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp 188.114.97.3:12171: i/o timeout] > common/retry: all retry attempts failed
2024/02/02 18:50:28 127.0.0.1:8094 accepted //a.nel.cloudflare.com:443 [http -> proxy]
2024/02/02 18:50:51 127.0.0.1:8098 accepted //github.com:443 [http -> proxy]
2024/02/02 18:51:00 127.0.0.1:8102 accepted //clients4.google.com:443 [http -> proxy]
4روزه دارم دنبال حل این میگردم ولی نتونستن حل کنم.وقتی از توی کلادفلر میام dns zone رو میزارم رو حالت proxied دیگه هیچ سایتی باز نمیضشه و همین پیام ها رو تکرار میکنه

**Comment by MahdiMb55** [comment]
منم همین مشکل رو دارم
حتی وقتی از پورت هایی که کلودفلر ساپورت میکنه هم استفاده میکنم بازم مشکل داره و وصل نمیشه
