### ISSUE TITLE
  روش تانل معکوس (reverse tunnel)  با استفاده از tls کار نمی کند

### ISSUE THREAD

**Issue by Cyrus-of-Persia** [MHSanaei/3x-ui#1733]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

طبق آموزش اخیر یوتیوب ایمان آقاپور، روش تانل معکوس رو انجام دادم فقط با این تفاوت که در رور داخل، inbound پنل و یوزر رو هر از دامنه با و بدون cdn روشن کلودفلر برای فعالسازی tls استفاده کردم ولی نتونستم متصل بشم. روی هیچ نتی کار نکرد. نوع protocol رو روی vless و trojan گذاشتم و transmission رو هم روی ws و هم روی tcp گذاشتم ولی هیچ کدوم کار نکردن.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by hrasoul2** [comment]
مشکل دقیقا همینه که تروجان رو سرور ایران به شدت مشکل داره
بهتره همون tcp بزارید یا grpc
و اینکه ایپی یا دامنه بزارید تفاوتی نداره

**Comment by Cyrus-of-Persia** [comment]
سلام ببه همگی دوستان. این مشکل هنوز برطرف نشده؟

**Comment by Cyrus-of-Persia** [comment]
> مشکل دقیقا همینه که تروجان رو سرور ایران به شدت مشکل داره بهتره همون tcp بزارید یا grpc و اینکه ایپی یا دامنه بزارید تفاوتی نداره

روی vless هم جواب نمیده. تو توضیحاتم گفتم
