### ISSUE TITLE
فعال کردن ربات روی سرور ایران

### ISSUE THREAD

**Issue by xvonvpn** [MHSanaei/3x-ui#1735]
سلام
من پنلم روی سرور ایران هست
میخواستم ربات رو فعال کنم روشی وجود داره که بشه ربات رو فعال کرد؟

**Comment by Masouddhojaei** [comment]
درود وقت بخیر
باید یک اینباند socks توی پنل ایران بسازید و ارتباطش رو با سرور خارج برقرار کنید اگه ریورس تانل پنل به پنل هستین، بعد قسمت تنظیمات بات پنل ایران باید آدرس پروکسی رو به فرمتی که خودش نوشته اضافه کنید، توجه کنید که از آیپی 127.0.0.1 استفاده کنید.

**Comment by mohamadn69** [comment]
ربات روی سرور ایران فعال کردم و پروکسی دادم ایم خطا میاد مشکل چیه؟

ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"

**Comment by surbiks** [comment]
This happens when 2 different clients send `getUpdates` method to Telegram servers for one bot token.
make sure you're not running the panel more than once simultaneously, or your bot token is not used elsewhere.

**Comment by xvonvpn** [comment]
جواب نمیده این روش برای من روش بهتری ندارید و یا نمیتونید از قسمت و کار هایی که میگید عکس بدید شاید یه چیزیو اشتبا زدم

**Comment by mohamadn69** [comment]
ایین روش را امتحان کن
https://github.com/alireza0/x-ui/issues/252#issuecomment-1560894478
من جواب گرفتم خیلی خوب کار میکنه
