### ISSUE TITLE
آیا امکان انتقال کاربر از یک پنل به پنل دیگه هست؟ یا کل تنظیمات هم باید رستور بشه؟

### ISSUE THREAD

**Issue by ramtiny** [MHSanaei/3x-ui#1737]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

ایا امکانش هست فقط از خود اینباند بشه بکاپ گرفت و رستور کرد؟
متاسفانه بکاپ از کل تنظیمات و اینباند و همه چی میگیره
اگه بخواییم فقط از یوزرها بکاپ بگیریم یا از یه پنل به پنل دیگه انتقال بدیم راه حل چیست ؟

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Dwnill** [comment]
میتونی از یک اینباند خروجی بگیری ولی به این شرط که تو کد های خروجیش ایمیل ها یکی نباشه و پرتوکل تداخل نداشته باشه و مهم تر از همه پورت اینباند هست .
یعنی اگه تو پنل A  یه اینباند داری vmess باشه پورت 443 با چند تا ایمیل 
تو پنل B اگه اینباند داشته باشی اونم vmess باشه پورتش یکی باشه خطا میده و ایمیل های هم اسم 
باید دستی تغیر بدی هم ایمیل ها رو هم پورت رو 

![Screenshot 2024-02-03 232222](https://github.com/MHSanaei/3x-ui/assets/40546776/392fa151-6d08-499e-a6e7-27148c93b768)

**Comment by ramtiny** [comment]
ممنون ولی دقیق متوجه نشدم
