### ISSUE TITLE
مشکل Log IP در ورژن جدید

### ISSUE THREAD

**Issue by qar4al** [MHSanaei/3x-ui#1738]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

توی آپدیت جدید مشکل نمایش لاگ ها بجای IP کاربر . IP سایت ها و برنامه ها رو میاره 

![image](https://github.com/MHSanaei/3x-ui/assets/63839880/b75a6bf1-e212-4bad-9c6b-93a432584354)

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
یه تغییراتی داده شد به نسخه اخر مجدد اپدیت کنید

**Comment by qar4al** [comment]
اپدید شد چند بار تست شد باز مشکل پا برجاست

**Comment by qar4al** [comment]
![image](https://github.com/MHSanaei/3x-ui/assets/63839880/ea3ac9b3-113f-454a-94cd-7ae4df3fb0f4)

**Comment by MHSanaei** [comment]
تایم اپدیت رو میتونید اینجا ببینید
https://github.com/MHSanaei/3x-ui/releases/tag/v2.1.3
مجدد اپدیت کنید که تغییرات اعمال شه
