### ISSUE TITLE
Wrong Date On Inbounds Table

### ISSUE THREAD

**Issue by Arman-nsb** [MHSanaei/3x-ui#1739]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

As seen in the image below, the duration date for clients is not correct and should be 31 days.
![image](https://github.com/MHSanaei/3x-ui/assets/84615037/1030e96d-6e78-4016-aa12-02d64fd89a9e)

### Version of 3x-ui

-

### x-ui log reports or xray log

-

**Comment by MHSanaei** [comment]
https://www.daysuntil.net/march-03-2024
