### ISSUE TITLE
no dns log

### ISSUE THREAD

**Issue by StayAway32** [MHSanaei/3x-ui#1745]
greetings again and thanks in advance
with no dns log the issue of ipv6 users showing their destination as their ip is gone

but now there is no ip record at all for those connecting via ipv6
im pretty sure my setup configuration is fine and done

it shows that the user is online but it simply say ( NO IP RECORD )
is there going to be a fix for this or is it my side ?

**Comment by StayAway32** [comment]
the thing is that im certain without showing the ip there be no log and with no log there be no fail2ban or ip tables ....

**Comment by MHSanaei** [comment]
It's your side , and panel doesn't capture any ipv6 
About your problem its your access log
Just go to xray configs/general/ access log
Set the path 
Save and restart
