### ISSUE TITLE
اطلاعات آخرین هندشیک (باید افزوده شود) - Info of latest handshake (have to be added)

### ISSUE THREAD

**Issue by neerro** [MHSanaei/3x-ui#1746]
سپاس از زحمات شما. یک پیشنهاد مهم دارم که زندگی بسیاری از افراد را هنگام تعامل با پنل عالی شما ساده‌تر خواهد کرد. خواهش می‌کنم این گزینه را حتماً مورد بررسی قرار دهید.

سازماندهی نهان اطلاعات درباره زمان آخرین هندشیک بین مشتری و سرور بسیار مهم و ضروری است. این قبلاً در پنل Hiddify پیاده‌سازی شده و در Wireguard نیز وجود دارد. این اطلاعات بسیار حیاتی هستند چرا که مثلاً در پنل ما 100-150 مشتری وجود دارد و برخی از آن‌ها دیگر از خدمات استفاده نمی‌کنند. دانستن اینکه این مشتریان کدامند به ما این امکان را می‌دهد که منابع را آزاد کرده و جا برای مشتریان جدیدی که واقعاً از سرویس استفاده می‌کنند، فراهم کنیم. به عنوان مثال، هنگام نگه داشتن موس بر روی برچسب "آفلاین" در ستون آنلاین، مفید خواهد بود که ببینیم کی آخرین بار مشتری از اتصال استفاده کرده است، تا بتوانیم اطمینان حاصل کرده و از مشتریان غیرفعال خود راحتانه حذف کرده و جای خالی را آزاد کنیم. در حال حاضر این اطلاعات در دسترس نیست و این کمبود بسیار حس می‌شود.

Thank you for your efforts. I have an important suggestion that would simplify the lives of many when interacting with your excellent panel. I kindly ask you to consider this option.

It is very important and necessary to add information about the last handshake time between the client and server. This is already implemented in the Hiddify panel and is present in Wireguard. This information is crucial because, for example, we have 100-150 clients in the panel, and some of them have stopped using the service. Knowing who these clients are would allow us to free up resources and accommodate new users who will actively use the service. For instance, when hovering over the "Offline" label in the online column, it would be helpful to see when the client last used the connection, enabling us to confidently remove inactive clients and free up slots. Currently, this information is unavailable, and it is sorely missed.

**Comment by neerro** [comment]
Was added before - #1078

**Comment by qar4al** [comment]
برای مشاهده اخرین ساعت انلاین بودن باید کدوم گزینه رو زد ؟

**Comment by neerro** [comment]
> برای مشاهده اخرین ساعت انلاین بودن باید کدوم گزینه رو زد ؟

متاسفانه تا کنون این امکان قابل مشاهده نیست؛ در حال حاضر این ویژگی در پنل وجود ندارد. من به توسعه‌دهنده محترم پنل توصیه می‌کنم که این ویژگی را اضافه کند، زیرا این اطلاعات کافی استفاده می‌شود تا بفهمیم کدام کاربران به مدت طولانی از خدمات استفاده نکرده‌اند.
