### ISSUE TITLE
IP limit not working in vless+ws+tls 

### ISSUE THREAD

**Issue by feridj2020** [MHSanaei/3x-ui#1749]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

با سلام خدمت همه مهندسین که زحمات زیادی میکشن تشکر و قدردانی میکنم . آی پی لیمیت با حالت ws-tls-vless کلادفلر کار نمیکنه در صورتی که لاگ میندازه بن هم میکنه ولی همچنان کار میکنه هر چند تا دستگاه باشه .اگه این مشکل رو حل کنین واقعا عالی میشه ...

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
شرمنده ای پی لیمیت فقط روی مستقیم جواب میده نه کلادفلر و نه تانل (تانل اوتباند و ریورس البته جوابه )

**Comment by feridj2020** [comment]
ممنون مهندس ولی اخه آی پی خود یوزر که اپراتور همراه اوله می افته تو قسمت ip log . ولی تو حالت grpc بله درسته واسه کلادفلر می افته و کار هم نمیکنه .
