### ISSUE TITLE
سوال درباره اضافه کردن کاربر جدید

### ISSUE THREAD

**Issue by guyane** [MHSanaei/3x-ui#1750]
سلام من یک پنل تحت وب دارم . که با استفاده از پنل  داخل /etc/x-ui/x-ui.db  کاربر جدید اضافه می کنم ...  اما بعد از اضافه کردن کاربر  حتما باید یک مرتبه دستور x-ui restart اجرا بشه  (که باعث قطع لحظه ای میشه)  امکان داره راهنمایی کنید  چطور بدون قطی این مشکل را رفع کنم

**Comment by Arman-nsb** [comment]
از سیستم API خود پنل استفاده کنید برای اضافه کردن یوزر جدید، نیازی به ریستارت هم نداره.

**Comment by guyane** [comment]
> از سیستم API خود پنل استفاده کنید برای اضافه کردن یوزر جدید، نیازی به ریستارت هم نداره

درود آرمان عزیز Doc خاصی در این باره هست ؟

**Comment by Arman-nsb** [comment]
https://github.com/MHSanaei/3x-ui?tab=readme-ov-file#api-routes
