### ISSUE TITLE
Doesn't show the server name in the subscription

### ISSUE THREAD

**Issue by Fox-llc** [MHSanaei/3x-ui#1751]
![Screenshot_2024-02-05-01-57-56-41_dd661fbf574bc01712a840b6c315ea7e.jpg](https://github.com/MHSanaei/3x-ui/assets/123845684/5e8f6c9b-9904-465c-ac80-ccc40590de40)

**Comment by neerro** [comment]
This is not the reason for the panel issue. It works perfectly with other well-functioning apps. 
You can definitely close this question, as nobody can say why it has so. 
You should ask the Hiddify app developers. about it
