### ISSUE TITLE
Missing flow option when first creating a client

### ISSUE THREAD

**Issue by Birddle** [MHSanaei/3x-ui#1754]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

There is no flow option in 'client' in 'Add inbounds'.
<img width="549" alt="image" src="https://github.com/MHSanaei/3x-ui/assets/86408260/3b44a789-4ea1-4c32-a40f-406a41d78792">
However, the flow option exists in the Edit Client After Creation option.
<img width="529" alt="image" src="https://github.com/MHSanaei/3x-ui/assets/86408260/a4c41f76-1abd-4dae-a759-ed142718e9f2">

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
you need to select on one of the security first like tls - reality - xtls 
then you can see the flow 

![Screenshot 2024-02-05 121908](https://github.com/MHSanaei/3x-ui/assets/33454419/941ae067-29d7-47f2-ba3d-45a96faec785)

**Comment by Birddle** [comment]
@MHSanaei It can connect normally when ‘listen IP’ left empty. But when it's configured as another one of my subdomains (non-panel access domain) it can't connect. What kind of problem is this?
