### ISSUE TITLE
برطرف کردن ارور در لاگ پنل

### ISSUE THREAD

**Issue by nimaftf** [MHSanaei/3x-ui#1757]
ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance

در قسمت لوگ پنل هر ثانیه یک ارور با متن فوق رو دریافت میکنم. (برای کانفیگ ها از تونل کلود فلر استفاده میکنم).

ممنون میشم راهنمایی بفرمایید .سپاس فراوان

**Comment by MHSanaei** [comment]
توکن بات شما در یه سرور دیگه هم داره استفاده میشه 
هر توکن فقط یک سرور
