### ISSUE TITLE
IPLog 

### ISSUE THREAD

**Issue by foadskr** [MHSanaei/3x-ui#1758]
سلام 
ممنون از لطف و زحمت هایی که تا این لحظه کشیدید سوالی داشتم 
قسمت IPLog تو پنل برای هر کاربر دیر عمل میکنه و ip هایی که به کانفیگ وصل میشن رو سریع نشون نمیده بعضی وقتا کلا نشون نمیده
لطفا راهنمایی کنید ممنون
(من از IP limiting استفاده نمیکنم)

**Comment by MHSanaei** [comment]
باید مسیر رو برای access log گذاشته باشید!( داخل xray config هست) و یوزری که وصل میشه به پراکسی 10 ثانیه طول میکشه که ای پی اون داخل پنل نمایش داده بشه

**Comment by foadskr** [comment]
مسیر access log رو چک کردم درست هست ولی یوزری که به پراکسی وصل میشه تو پنل در IPlog یوزر  نمایش داده نمیشه
(بالای 10 ثانیه هم صبر کردم)
