### ISSUE TITLE
Unable to listen to IPv4, only able to listen to IPv6, resulting in web inability to use

### ISSUE THREAD

**Issue by KanLai** [MHSanaei/3x-ui#1760]

**Comment by xuqiang-idotools** [comment]
add ports config in the docker-compose.yml is ok:

---
 version: "3"
 
 services:
   3x-ui:
     image: ghcr.io/mhsanaei/3x-ui:latest
     container_name: 3x-ui
     hostname: yourhostname
     ports:
       - "2053:2053"
     volumes:
       - $PWD/db/:/etc/x-ui/
       - $PWD/cert/:/root/cert/
     environment:
       XRAY_VMESS_AEAD_FORCED: "false"
     tty: true
     network_mode: bridge
     restart: unless-stopped

**Comment by RootSir** [comment]
> add ports config in the docker-compose.yml is ok:
> 
> version: "3"
> 
> services: 3x-ui: image: ghcr.io/mhsanaei/3x-ui:latest container_name: 3x-ui hostname: yourhostname ports: - "2053:2053" volumes: - $PWD/db/:/etc/x-ui/ - $PWD/cert/:/root/cert/ environment: XRAY_VMESS_AEAD_FORCED: "false" tty: true network_mode: bridge restart: unless-stopped

Is there any way to solve this quetion without using docker?

**Comment by SuperMonkeyC1** [comment]
I seem to have encountered this problem as well, I deployed it using scripts, and there are public network ipv6 and ipv4 on my vps, it only listens to ipv6 addresses, not ipv4 addresses

root@arm203-9:/usr/local/x-ui# systemctl status x-ui
● x-ui.service - x-ui Service
     Loaded: loaded (/etc/systemd/system/x-ui.service; enabled; preset: enabled)
     Active: active (running) since Thu 2025-02-27 01:27:54 UTC; 22min ago
   Main PID: 983 (x-ui)
      Tasks: 19 (limit: 21450)
     Memory: 112.7M (peak: 137.9M)
        CPU: 1.905s
     CGroup: /system.slice/x-ui.service
             ├─ 983 /usr/local/x-ui/x-ui
             └─1285 bin/xray-linux-arm64 -c bin/config.json

Feb 27 01:27:54 arm203-9 systemd[1]: Started x-ui.service - x-ui Service.
Feb 27 01:27:57 arm203-9 x-ui[983]: 2025/02/27 01:27:57 Starting x-ui 2.5.3
Feb 27 01:27:57 arm203-9 /usr/local/x-ui/x-ui[983]: INFO - Web server running HTTP on [::]:12345
root@arm203-9:/usr/local/x-ui#
