### ISSUE TITLE
Logs button in the overview tab not working

### ISSUE THREAD

**Issue by Arman-nsb** [MHSanaei/3x-ui#1763]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![image](https://github.com/MHSanaei/3x-ui/assets/84615037/45c72596-5a1e-4971-aea1-8b437cf44df5)
Since the release of v2.1.3, the Logs button has not been functioning properly. It throws console errors, which can be seen in the image provided.

(Sometimes a few refreshes may fix the issue, but it persists.)

### Version of 3x-ui

2.1.3

### x-ui log reports or xray log

-

**Comment by MHSanaei** [comment]
thanks for report
