### ISSUE TITLE
 xray issue - failed to send data over gRPC tunnel 

### ISSUE THREAD

**Issue by StayAway32** [MHSanaei/3x-ui#1764]
greetings again
regards to new update every tab in panel log is filled with followings :

app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to write A response payload > transport/internet/grpc/encoding: failed to send data over gRPC tunnel > rpc error: code = Canceled desc = context canceled

which i suspect means that client closed the connection earlier than the response was send back to them

can it be related to the fact that there is no longer ( error": "./error.log", ) and so it now defaults to sending these into the panel log on every tab ( debug , info , warning etc ... )
and would adding error.log solve the issue ?

thanks in advance

**Comment by MHSanaei** [comment]
Add "error": "./error.log" is not solving the issue, but you are not seeing this error anymore.
its xray problem they need to fix it 
https://github.com/XTLS/Xray-core/issues/880
https://github.com/XTLS/Xray-core/issues/2359
