### ISSUE TITLE
warp routing blocking chat gpt website

### ISSUE THREAD

**Issue by selfishtom** [MHSanaei/3x-ui#1766]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

i go Warp Routing 
and active ChatGPT toggle
and click on save
and click on restart xray
but "chat.openai.com" going block and don't open.
please fix it asap. because it was very usefull.
thanks for understanding.

i have to say my config is Vless + Reality

### Version of 3x-ui

<details>

version 3X-UI [v2.1.3], Xray v1.8.7

</details>

### x-ui log reports or xray log

<details>

i think don't need logs
just try it on base 22.04 ubo linux and you will see this
</details>

**Comment by faridRezvani** [comment]
to solve your problem You need to make some changes on the warp.
According to the picture below, enter outbands settings and do steps one and two and start editing.
<img width="936" alt="Screenshot 2024-02-09 203123" src="https://github.com/MHSanaei/3x-ui/assets/10058552/9923cfc9-c67a-4c7e-95b9-04bac60e87fd">


According to the picture below, select the ForceIPv6v4 value for Domain Strategy. After that, save the settings and restart the panel once.
<img width="932" alt="Screenshot 2024-02-09 203721" src="https://github.com/MHSanaei/3x-ui/assets/10058552/15eecbde-28d5-41f9-98e7-c3a1061fb10d">

**Comment by selfishtom** [comment]
> to solve your problem You need to make some changes on the warp. According to the picture below, enter outbands settings and do steps one and two and start editing. <img alt="Screenshot 2024-02-09 203123" width="936" src="https://private-user-images.githubusercontent.com/10058552/303724866-9923cfc9-c67a-4c7e-95b9-04bac60e87fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MDQ4NzQsIm5iZiI6MTcwNzUwNDU3NCwicGF0aCI6Ii8xMDA1ODU1Mi8zMDM3MjQ4NjYtOTkyM2NmYzktYzY3YS00YzdlLTk1YjktMDRiYWM2MGU4N2ZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDE4NDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMDI5NTlkNTkzMTFkZjg2YWQ0ODRkY2QwZTQ0MWVmMjUzNmVmZjYxYjQ1MTZiM2I1ZTBlYjdiMjhkNDZmMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GeNysXIy6n5POsSMhWXr9p39U7j9hSdoSNg5R51S9Hg">
> 
> According to the picture below, select the ForceIPv6v4 value for Domain Strategy. After that, save the settings and restart the panel once. <img alt="Screenshot 2024-02-09 203721" width="932" src="https://private-user-images.githubusercontent.com/10058552/303724904-15eecbde-28d5-41f9-98e7-c3a1061fb10d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MDQ4NzQsIm5iZiI6MTcwNzUwNDU3NCwicGF0aCI6Ii8xMDA1ODU1Mi8zMDM3MjQ5MDQtMTVlZWNiZGUtMjhkNS00MWY5LTk4ZTctYzNhMTA2MWZiMTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDE4NDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhODZmNzhmZjAyOGI4NzlmNWRhZDA4ZDFkMjJjMDhlNjBkNWU3ZDI2NGM3NzFmM2I0NzljYzcyZTExMGQyMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IT9jmE7ZS8f3Pd8oAMlTbttwnDzuZ1_lezokCZl8YxM">

ok i'll try this

**Comment by wc7086** [comment]
> to solve your problem You need to make some changes on the warp. According to the picture below, enter outbands settings and do steps one and two and start editing. 
> 
> According to the picture below, select the ForceIPv6v4 value for Domain Strategy. After that, save the settings and restart the panel once. 

It doesn't work for me.
