### ISSUE TITLE
مشکل نشان ندادن حجم مصرفی کاربر و انلاینی بعد از تانل

### ISSUE THREAD

**Issue by rezareza220** [MHSanaei/3x-ui#1773]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام
مشکلی که دارم اینه که حجم مصرفی کاربر نشان داده نمیشه یعنیوهمیشه صفر هست. این مشکل بعد از تانل شدن ایجاد میشه
از طریق outbound  تانل شده
![Screenshot_20240207_105748_Chrome](https://github.com/MHSanaei/3x-ui/assets/138994105/a25b438a-0a81-4fbb-b84c-00833a4687d5)

### Version of 3x-ui

<details>

```console
# Paste here
```2.1.3

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```2024/02/07 11:06:30 WARNING - XRAY: [1679268984] app/dispatcher: non existing outTag: blocked
2024/02/07 11:06:25 WARNING - X-UI: Access log doesn't exist in your Xray Configs
2024/02/07 11:06:25 WARNING - X-UI: fail2ban is not installed. IP limiting may not work properly.
2024/02/07 11:06:21 WARNING - X-UI: get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: EOF"
2024/02/07 11:06:20 WARNING - XRAY: [1640838414] app/dispatcher: non existing outTag: blocked
2024/02/07 11:06:15 WARNING - X-UI: Access log doesn't exist in your Xray Configs
2024/02/07 11:06:15 WARNING - X-UI: fail2ban is not installed. IP limiting may not work properly.
2024/02/07 11:06:11 WARNING - X-UI: get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: EOF"
2024/02/07 11:06:10 WARNING - XRAY: [1321922855] app/dispatcher: non existing outTag: blocked
2024/02/07 11:06:05 WARNING - X-UI: Access log doesn't exist in your Xray Configs
2024/02/07 11:06:05 WARNING - X-UI: fail2ban is 

</details>

**Comment by abbasshams** [comment]
منم این مشکل داشتم 
دلیلش حذف کردن Ruting Rule - api بود
اضافه ش کردم اوکی شد
![image](https://github.com/MHSanaei/3x-ui/assets/20367622/bbbf1f05-b3a9-46a8-a07b-3c35f1f6aecf)
