### ISSUE TITLE
راه اندازی فرگمنت روی پنل

### ISSUE THREAD

**Issue by sMnzz** [MHSanaei/3x-ui#1778]
سلام و خسته نباشی.
ذیذم توی بخش اوتبانذ گزینه فرگمنت هم اضافه شده. ولی من هرکار کردم و هرجور مسیریابی که انجام دادم نمیشه.
الان به صورت دستی روی همون پنل دارم از فرگمنت استفاده میکنم. ولی انتقالش به اطرافیان خیلی سخته. اگه میشه یه راهنمایی در مورد اینکه تنظیمات اوتباند و مسیریابی رو چجوری برای فرگمنت استفاده کنیم بگید.
ممنون

**Comment by csharpfarsi** [comment]
سلام ممکنه فرگمنت رو طوری اضافه کنید که با تخصیص دادن ایپی تمیز به جای qr code بتونیم کد جیسون فرگمنت رو کپی کنیم؟
