### ISSUE TITLE
ip limit

### ISSUE THREAD

**Issue by m0hammadhossein** [MHSanaei/3x-ui#1779]
سلام میخواستم بدونم چطور میشه محدودیت تعداد آیپی متصل رو وقتی داریم از تانل استفاده می کنیم حل کرد. چون طبیعتا همه از طریق سرور تانل شده متصل میشن فقط یه ایپی میفته. تو dokodemo-door  همچین امکانی ندیدم که بشه محدودیت گذاشت

**Comment by MHSanaei** [comment]
باید روش تانل زدنتون رو عوض کنید
اوتباند بزنید یا ریورس

**Comment by m0hammadhossein** [comment]
از اوتباند استفاده کردم.اما آیا اگر کا کانفیگ های زیادی داشته باشیم درسته همش رو یه اوتباند بره؟
نمیشه چند تا اوتباند زد که تقسیم بندی شه
حتی اینکارو کردم ولی همه ترافیک میره رو‌یه اوتباند

**Comment by Alfred00282** [comment]
سلام میخام محدودیت کاربر بیارم روی سرور روشم cdn راهنمارو خوندم لاگ اکسس و ای پی لیمیت نصبه بقیه رو نفهمیدم xreal ip نمیدونم کجاست
