### ISSUE TITLE
مشکل با همراه اول وبسوکت

### ISSUE THREAD

**Issue by Mo3tafakhodsetan** [MHSanaei/3x-ui#1781]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام خسته نباشید دوستان 
پنل من الان ۳ روزه با همراه اول مشکل پیدا کرده از پروکسی کلودفلر استفاده میکنم ایرانسل خوبه ولی همراه اول خیلی اختلال داره 
راه حلی میدونید ارائه بدید 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Aminz77** [comment]
دامنه ت محدود شده رو همراه
