### ISSUE TITLE
API - How to get url conf?

### ISSUE THREAD

**Issue by CryZFix** [MHSanaei/3x-ui#1783]
Is there any way to get url configurations after creating a client via API /addClient, at least some information that could be used to buildings the url and generate qrcode?

`ss://Y2h...paUFc@server_ip:server_port?type=tcp#xConSS-123312`

**Comment by Puremag1c** [comment]
Up same question!

**Comment by a-poluyanov** [comment]
Up same question!

**Comment by Puremag1c** [comment]
> Up same question!
i dont know how to generate VMESS link, but for VLESS its just a URI with parameters, that u can find in VLESS inbound

But for VMESS question is still actual

**Comment by a-poluyanov** [comment]
I know how to generate a VLESS link for your user. There is simple logic that I know. I also know a solution for VMES. If you need it, please like or write to me personally, I will be happy to help.

> > Up same question!
> > i dont know how to generate VMESS link, but for VLESS its just a URI with parameters, that u can find in VLESS inbound
> 
> But for VMESS question is still actual

**Comment by Tim-oxa** [comment]
> > I know how to generate a VLESS link for your user. There is simple logic that I know. I also know a solution for VMES. If you need it, please like or write to me personally, I will be happy to help. In general, you can create a link for all protocols automatically, I generate the link in my python code and it works.
> > > > Up same question!
> > > > i dont know how to generate VMESS link, but for VLESS its just a URI with parameters, that u can find in VLESS inbound
> > > 
> > > 
> > > But for VMESS question is still actual
> 
> How to write to you? you have no contacts =)

Did you manage to find the answer?

**Comment by MAY4VFX** [comment]
> I know how to generate a VLESS link for your user. There is simple logic that I know. I also know a solution for VMES. If you need it, please like or write to me personally, I will be happy to help. In general, you can create a link for all protocols automatically, I generate the link in my python code and it works.
> 
> > > Up same question!
> > > i dont know how to generate VMESS link, but for VLESS its just a URI with parameters, that u can find in VLESS inbound
> > 
> > 
> > But for VMESS question is still actual

please share this with us!

**Comment by Puremag1c** [comment]
> > > I know how to generate a VLESS link for your user. There is simple logic that I know. I also know a solution for VMES. If you need it, please like or write to me personally, I will be happy to help. In general, you can create a link for all protocols automatically, I generate the link in my python code and it works.
> > > > > Up same question!
> > > > > i dont know how to generate VMESS link, but for VLESS its just a URI with parameters, that u can find in VLESS inbound
> > > > 
> > > > 
> > > > But for VMESS question is still actual
> > 
> > 
> > How to write to you? you have no contacts =)
> 
> Did you manage to find the answer?

no i use only vless
