### ISSUE TITLE
ساب لینک چند سرور و لکیشن مختلف با یک لینک به راحتی با پنل ثنایی

### ISSUE THREAD

**Issue by arash1959** [MHSanaei/3x-ui#1793]
سلام مهندس میخواستم بدونم امکان  لینک  دادن چند سرور مختلف با یک ساب لینک رو خودتون اضافه کردید یا من اتفاقی کشف کردم

**Comment by Avampiire** [comment]
سلام دوست عزیز دقیقا رو دوتا پنل جداگانه چگونه با یک ساب لینک دست یوزر نهایی میدین یه توضیح لطفا بدین؟

**Comment by arash1959** [comment]
سلام  چند مرحله ساده داره اینجا نمیشه توضیح داد خواستید بدون چشم داشتی توضیح میدم  مهندس استقبالی نکرد بهتره پابلیک نشه

**Comment by uzer0098** [comment]
طرف یه خالی بست
راست میگی آموزش بده

**Comment by arash1959** [comment]
به این دوستمون که فرستادم طرز کار رو خواستن انجام بدن شما هم خواستی هزینش رو میگیرم برات انجام میدم یا به خودت یاد میدم  همه خالی بند نیستن باور کن خیلی سادست این کار

**Comment by uzer98** [comment]
جالبه
شما برای این پنلی که استفاده میکنی هزینه پرداخت کردی که الان  برای این روشی که ادعا میکنی هزینه میخوای

**Comment by arash1959** [comment]
شما دقت کنی میبینی که نوشتم بدون چشم داشت بچه دوساله نیستم که نوشتی طرف خالی بست اگه راست میگی یاد بده اگه بحث ثابت کردن باشه پول وقتم رو میگیرم والا که اگه کسی بلد باشه با اینکه خیلی راحته امروز فردا پابلیک میکنم  فقط خواستم بدونم کسی هم کرده این کارو  تو گروه ثنایی احتمالا بزارم طرز کار رو
