### ISSUE TITLE
نشان ندادن وضعیت آنلاینی کاربران

### ISSUE THREAD

**Issue by rbayaat** [MHSanaei/3x-ui#1795]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

این مشکل رو قبلا نداشتم ولی امروز دیدم با اینکه متصل هستم توی پنل Offline نشون داده میشه
همچنین حجم مصرفی هم تغییر نمیکنه
سرور تانل هست ولی قبلا این مشکل نبود

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by mohamadn69** [comment]
پنل را به اخرین نسخه ارتقا بده و تنظیمات ایکس ری را از داخل پنل  reset default کن
