### ISSUE TITLE
مشکل بالا رفتن CPU   در اوت باند کردن

### ISSUE THREAD

**Issue by qar4al** [MHSanaei/3x-ui#1796]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

امروز متوجه شدم که یه اوت باند درست کردم و تو بخش رول ها یه رول ایجاد کردم که ترافیک به سمت خارج هدایت بشه بعد از این کار CPU روی 100% رفت
اینباد روی سرور ایران وب سوکت بود و اوت باند به سرور خارج TCP-http

![image](https://github.com/MHSanaei/3x-ui/assets/63839880/19d1dc28-ed37-45b1-a845-a862f5d7ac3c)

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
Logs ro bezan 
Download kon
Bezar inja

**Comment by qar4al** [comment]
مشکل پیدا شد . وقتی عدد IP Limit رو 1 میزارم  هم IP نمیاره هم CPU 100% میشه . IP Limit رو عددشو 0 کردم و Xray رو ری استارت کردم مشکل حل شد

**Comment by qar4al** [comment]
[x-ui.log](https://github.com/MHSanaei/3x-ui/files/14232521/x-ui.log)
لاگ دانلود شده خدمت شما

**Comment by qar4al** [comment]
لاگ خدمت شما .
[x-ui.log](https://github.com/MHSanaei/3x-ui/files/14232531/x-ui.log)

**Comment by MHSanaei** [comment]
دوست عزیز شما ای پی لیمیت فعال دارید ولی fail2ban نصب نکردید
برید داخل منوی سرور و گزینه های لازم رو بزنید و نصب کنید
