### ISSUE TITLE
مشکل بالا رفتن CPU با IP Limit

### ISSUE THREAD

**Issue by qar4al** [MHSanaei/3x-ui#1799]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

مشکل بالا رفتن CPU با وجود نصب fail2ban  هنوز مشکل پابرجاس . 
IP نمایش داده نمیشود و CPU  روی 100%

![Screenshot 2024-02-11 194951](https://github.com/MHSanaei/3x-ui/assets/63839880/a98a6322-4bab-4281-91f8-59ecb141f1ba)

![Screenshot 2024-02-11 194958](https://github.com/MHSanaei/3x-ui/assets/63839880/89b5aa27-55f4-41d4-8d14-92a1a3d50ed8)

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
مجدد لاگ رو چک کنید

**Comment by qar4al** [comment]
مشکل با حذف و نصب مجدد رفع شد . با تشکر
