### ISSUE TITLE
قطع نشدن مصرف کاربر بعد تمام شدن حجم یا تاریخ

### ISSUE THREAD

**Issue by mokhtarabdi** [MHSanaei/3x-ui#1800]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام من الان متوجه شدم مصرف کاربر های من بعد تمام شدن حجم یا تاریخ تمام نمیشه مجبور شدم خودم متوقفش کنم میشه بگین چطوری درستش کنم ؟؟ قبلا این طوری نبود این ورژن آخر فکر کنم اختلال داره

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Avampiire** [comment]
سلام بله من هم رو ورژن 2.1.3 این مشکل دارم!!

**Comment by m0hammadhossein** [comment]
دقیقا .حتما باید یه بار قطع کنن اتصالو تا دیگه نتونن وصل شن استفاده کنن

**Comment by Parsam1989** [comment]
سلام همین مشکل هست نسخه ها قبل هم تست کردم مشکل داره 
در حالت عادی قطع میشه
ولی اگر فرگمنت بهش بدی تاریخ هم نداشته باشه وصل میشه
وقتی هم یک بار وصل شه کانفیگ معمولی هم دیکه وصل میشه بدون تاریخ و حجم
