### ISSUE TITLE
I cant add words in xray Config

### ISSUE THREAD

**Issue by AmirMehrdadi** [MHSanaei/3x-ui#1803]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

i cant add this in my xray config
"log": {
"loglevel": "warning",
"access": "./access.log",
"error": "./error.log"
},

can you help me ?

### Version of 3x-ui

3X-UI [v2.1.2]

### x-ui log reports or xray log

WARNING - X-UI: access.log doesn't exist in your config.json

**Comment by neerro** [comment]
Whats wrong why didn't?

**Comment by MHSanaei** [comment]
Just install latest version then you can add that easily with button
