### ISSUE TITLE
X-UI increases 99%  CPU Load

### ISSUE THREAD

**Issue by Mrkoopaei** [MHSanaei/3x-ui#1806]
### Welcome

- [x] Yes, I'm using the latest major release. Only such installations are supported.
- [x] Yes, I'm using the supported system. Only such systems are supported.
- [x] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

hi everyone
X-UI version 2.1.3 increases 99% CPU Load. does anyone have this issue?

thanks

### Version of 3x-ui

* X-UI Version 2.1.3

### x-ui log reports or xray log

* 99% CPU Load issue

**Comment by RAfrwrk** [comment]
این مشکل برای من هم هستش سرور من وقتی xray داره پروسس میشه به صورت وحشتناکی cpu استفاده میکنه

**Comment by MHSanaei** [comment]
please don't open any issue without logs 
download your logs and upload it here
thanks

**Comment by YahYaTNT** [comment]
سلام

برای منم چنین مشکلی هست

بعد از آپدیت پنل به نسخه 2.1.3
پنل مصرف cpu خیلی زیادی داره

انگاری که هنگ میکنه و مشکل داره

توی عکس ضمیمه هم مشخصه

دوباره دانگرید کردم به 2.1.2
بهتره اوضاع

![x-ui](https://github.com/MHSanaei/3x-ui/assets/94187458/ed1f81d1-d2af-4b9f-9c0d-154aa8d3b507)

**Comment by MHSanaei** [comment]
لاگ رو ضمیمه کنید در غیر این صورت issue باز نکنید
