### ISSUE TITLE
بهبود subscription

### ISSUE THREAD

**Issue by Behzadwow** [MHSanaei/3x-ui#181]
سلام
ممنون برای فعال سازی subscription.
بعضی از inbound هایی که ما میسازیم که برای تانل یا cdn استفاده کنیم معمولا گزینه tls را خاموش میزاریم. و کانفیگ که export میکنیم اول وارد client خود می کنیم و بعد address را تغییر می دهیم. ولی  با export یا subscription همان address پنل رو به صورت خودکار در قسمت address کاربر قرار میده.
برای این که بشه از subscription بهتر استفاده کرد لطفا
1- باکس domain را بدون فعال کردن tls درتنضیمات inbound نشان دهد تا بتوانیم custom address خود را برای کاربر قرار دهیم. در غیر این صورت استفاده از subscription برای inbound های فاقد tls با custom address بی فایده می باشد.
2- باکس host اضافه شود و همچنان بدون فعال کردن tls درتنضیمات inbound نشان دهد.
3- در روش freedom/rahgozar ما بدون فعال کردن tls باید قسمت های sni , alpn, domain, utls, allow insecure را برای کاربر پر کنیم. اگر این گزینه ها بدون فعال کردم tls در inbound قابل تغییر نباشد، استفاده از  subscription در روش freedom/rahgozar بی فایده می باشد.

ممنون از تغیرات بسیار عالی تا الان

**Comment by seingod** [comment]
سلام یه باگ دیگه ای هم که این بخش داره اینه که اگه ادرس پنل رو تغییر بدیم به مثلا
Https://example.com/panel/
سابسکرایب ها توی پنل درست نمایش داده نمیشن
و بهتره این متود جوری باشه که بتونیم در چندتا سرور ازش استفاده کنیم و یا بهینه سازی بشه برای استفاده در ای پی آی
باید بشه لینک های سابسکرایب رو شخصی سازی کرد تا بتونیم تنظیمات مورد نیازمون رو بهش اضافه کنیم
 چون مثلا توی nekoray وقتی کانفیگ پنل رو وارد میکنم همیشه tls فعاله و کانکشن کار نمیکنه و باید دستی اف بشه

**Comment by godcracker7921** [comment]
داداش سابسکرایب نیاورده ک؟ کجا فعال میشه
