### ISSUE TITLE
ضعیف شدن سرعت اینترنت

### ISSUE THREAD

**Issue by alrz-usfi** [MHSanaei/3x-ui#1814]
دوستان تقریبا یکی دو هفتس سرعت من با این تنظیمات به شدت کم شده:
tls و دامین پشت کلودفلر، vless و ws
تنها کانفیگی که جوابگو هست همینه اونم سرعتش به شدت افت پیدا کرده.
راه حلی دارید؟

**Comment by Alij13a** [comment]
دقیقا همین مشکل برای من هم وجود دارد.
کسی اگر راه حلی داره لطفا بگه.

باتشکر

**Comment by alrz-usfi** [comment]
> ریورس بزنید با استفاده از خود پنل. از آی‌پی خارج مستقیم به آی‌پی داخل. من از reality استفاده می‌کنم براش. اگر نشد، سرور ایران رو بذارید پشت کلادفلر، کانفیگ کلادفلر سرور ایران رو بذارید توی outbound سرور خارج برای ریورس زدن. توی این روش هم از ws+tls استفاده می‌کنم. اینطوری فیلترینگ ایران می‌بینه که درخواست داره از سمت کلادفلر میاد.

ممنون از توضیحاتتون دوست عزیز
ولی من شنیدم توی ریورس استفاده از ریلیتی فیلتر میکنه سرور رو
