### ISSUE TITLE
هک شدن سرور توسط یکی از یوزرها 

### ISSUE THREAD

**Issue by morteza229866** [MHSanaei/3x-ui#1817]
سلام وقت به خیر من یه سرور دارم که روش یوزر دارم به مشتری میدم یکی از یوزرا با ای پی که سرور روش هست و به فیلتر وصل هست کار هک انجام میده و هر چند روز از سایت هیتزنر برام پیام میاد که از سرور شما حمله دریافت شده 80 یوزر هستن نمیدونم کدومشون داره این کار رو میکنه کسی میتونه بهم بگه چطور میتونم ببینم کدوم یوزر داره اینو انجام میده

**Comment by YahYaTNT** [comment]
اگر منظورتون از پیام سایت هتزنر
ابیوز دیتاسنتره که گزارشش رو اینجا بزارید که موضوع ابیوز مشخص و راه حلی ارائه شه

**Comment by MHSanaei** [comment]
راه حل خاصی برای پیدا کردن اون کاربر وجود نداره

**Comment by morteza229866** [comment]
> اگر منظورتون از پیام سایت هتزنر ابیوز دیتاسنتره که گزارشش رو اینجا بزارید که موضوع ابیوز مشخص و راه حلی ارائه شه

We have indications that there was an attack from your server.
Please take all necessary measures to avoid this in the future and to solve the issue.

We also request that you send a short response to us. This response should contain information about how this could have happened and what you intend to do about it.
In the event that the following steps are not completed successfully, your server can be blocked at any time after the 2024-02-16 12:22:24 +0100.

TIME (UTC)          SRC        SRC-PORT -> DST          DST-PORT SIZE PROT
> ----------------------------------------------------------------------------
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.2 16658  166 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.3 16658  166 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.4 16658  166 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.5 16658  166 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.6 16658  166 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.7 16658  166 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.8 16658  166 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.9 16658  166 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.10 16658  166 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.11 16658  166 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.12 16658  166 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.13 16658  166 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.14 16658  166 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.15 16658  166 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.16 16658  166 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.17 16658  166 UDP
> 2024-02-14 09:37:32  91.107.150.159 56981 ->  102.228.161.18  5564  302 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.18 16658  166 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.19 16658  166 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.20 16658  166 UDP
> 2024-02-14 09:37:31  91.107.150.159 44469 ->  102.228.161.21 16658  166 UDP

**Comment by YahYaTNT** [comment]
طبق لاگ فایروال ظاهرا کاربر نت اسکن انجام داده
کاری که هتزنر بهش حساسه
شما چند تا کار میتونی انجام بدی که تا حدودی جلوی مشکل رو بگیرین

اینکه پورت های udp  خروجی رو روی فایروال ببندین(بجز پورت 53 و 443)

و یا اینکه تنظیمات access log رو در پنل تنظیم کنین
  "log": {
    "error": "./error.log",
    "access": "./access.log",
    "loglevel": "warning"
  },
که فعالیت کاربر ها رو بتونین بررسی کنین
که در صورت تکرار و ابیوز مجدد
با سرچ توی فایل access log بتونین کاربری رو که نت اسکن یا پورت اسکن و ... انجام داده شناسایی و حذف کنین

**Comment by morteza229866** [comment]
> طبق لاگ فایروال ظاهرا کاربر نت اسکن انجام داده کاری که هتزنر بهش حساسه شما چند تا کار میتونی انجام بدی که تا حدودی جلوی مشکل رو بگیرین
> 
> اینکه پورت های udp خروجی رو روی فایروال ببندین(بجز پورت 53 و 443)
> 
> و یا اینکه تنظیمات access log رو در پنل تنظیم کنین "log": { "error": "./error.log", "access": "./access.log", "loglevel": "warning" }, که فعالیت کاربر ها رو بتونین بررسی کنین که در صورت تکرار و ابیوز مجدد با سرچ توی فایل access log بتونین کاربری رو که نت اسکن یا پورت اسکن و ... انجام داده شناسایی و حذف کنین


خواستم تشکر کنم از شما دوست عزیز که به پیام من جواب دادی مرسی از محبت شما .
میشه من زیاد تو این کار وارد نیستم  میشه دستور بستن پورت udp   رو بنویسید  و چطور همه رو با هم ببندم چون زیادن  یا منظورتون اونایی که رو سرور فعالن 

و گفتید میشه از طریق دستور که دادید log  رو مشاهده کنم  منظورتون  اون کود رو در پنل ثنایی بزن اگه نمیشه یه زاهنمایی بکنید کدوم قسمتش دقیقا وارد کنم اگه عکس بگیرد ممنون میشم

**Comment by YahYaTNT** [comment]
در مورد فایروال سرچ بزنین
با بستن پورت های udp عمده مشکل حل میشه

درمورد لاگ
ن هر 1 دیقه نیست
توی پنل من لاگ ها میمونه

لیست آی پی و پورتی که در ابیوز دیتاسنتر میاد رو داخل این فایل چک میکنی
مشخص میشه توسط کدوم یوزر انجام شده

**Comment by morteza229866** [comment]
> در مورد فایروال سرچ بزنین با بستن پورت های udp عمده مشکل حل میشه
> 
> درمورد لاگ ن هر 1 دیقه نیست توی پنل من لاگ ها میمونه
> 
> لیست آی پی و پورتی که در ابیوز دیتاسنتر میاد رو داخل این فایل چک میکنی مشخص میشه توسط کدوم یوزر انجام شده

شما هم پنل ثتایی اخرین نسخه رو نصب کردید چون برا من log  پاک میشه هر یک دقیه انگار رفرش میشه البته شما میگید تو پنل من از طریق سرور میرم  به پوشه user تا access.log رو بتونم باز کنم چطور میتونم با شما در تماس باشم. ای دی تلگرام دارید
