### ISSUE TITLE
مقدار ترافیک ایران

### ISSUE THREAD

**Issue by alrz-usfi** [MHSanaei/3x-ui#1820]
دوستان راهنمایی می‌کنید که ترافیک سرور ایران باید چقدر باشه تا فیلتر نشه؟

**Comment by Amin-Najii** [comment]
سلام وفتت بخیر سوالتون خیلی کلیه 
بستگی به 
ترافیکتون - حساسیت دیتاسنتر - نوع انجام کار و ... داره 
در کل اگر نیاز داشتید تو تلگرام میتونید پیام بدید ‌:
@amin_naji

**Comment by alrz-usfi** [comment]
> سلام وفتت بخیر سوالتون خیلی کلیه بستگی به ترافیکتون - حساسیت دیتاسنتر - نوع انجام کار و ... داره در کل اگر نیاز داشتید تو تلگرام میتونید پیام بدید ‌: @amin_naji

منظورم برای تانل معکوس هست. روی ابر آروان خریدم
