### ISSUE TITLE
آیا بعد از تانل کردن محدودیت کاربر کار میکنه؟

### ISSUE THREAD

**Issue by elegance666** [MHSanaei/3x-ui#1823]
درود، 
این سوال که بعد از تانل کردن **محدودیت یوزر** هنوز کار میکنه یا نه؟ ذهن منو خیلی مشغول کرده، چون همه یوزرها آی پیشون میشه یکی توی سرور خارجی.
و اگر کار نکنه دیگه نمیشه نامحدود داد به کسی

سپاسگذارم

**Comment by MHSanaei** [comment]
مدل تانلتون رو عوض کنید به پنل به پنل مثل اوتباند یا ریورس بله کار میکنه

**Comment by elegance666** [comment]
> مدل تانلتون رو عوض کنید به پنل به پنل مثل اوتباند یا ریورس بله کار میکنه

الان dokomodo هستش، با خود پنلreverse باید اضافه کنم، درسته؟

اگر بخوام  reverse کنم یوزرها باید سرور خارجی تعریف بشند یا ایرانی؟

**Comment by MHSanaei** [comment]
یوزرهای باید داخل ایران باشن
