### ISSUE TITLE
Observatory object can't be added (to use leastPing strategy for balancer)

### ISSUE THREAD

**Issue by pulsarice** [MHSanaei/3x-ui#1826]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Xray has a feature (borrowed from v2ray project) to ping outbounds in a set interval and use the best one via balancer routing rules.
I have tested it locally and it works. (by manually editing config.json and running xray)
It needs ObservatoryObject to be added to config.json. but when I add this to xray config in 3x-ui, it's not added to "/usr/local/x-ui/bin/config.json", therefore this feature does not work.
Please fix this 

observatory settings in config.json:
```
{
    "log": {},
    "api": {},
    "dns": {},
    "routing": {},
    "policy": {},
    "inbounds": [],
    "outbounds": [],
    "transport": {},
    "stats": {},
    "reverse": {},
    "fakedns": [],
    "observatory": {}
}
```
The format of observatory is like this:

```
  "observatory": {
    "subjectSelector": [
          "server1",
          "server2"
    ],
    "probeURL": "https://www.google.com/generate_204",
    "probeInterval": "1m"
  }
```

and the balancer will be like this:

```
  "routing": {
    "balancers": [
      {
        "tag": "balancer",
        "selector": [
          "server1",
          "server2"
        ],
        "strategy": {
          "type": "leastPing"
        }
      }
    ],
    "rules": []
  }
```

@MHSanaei @alireza0

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by ErfanTech** [comment]
Which version of xray-core are you using?
Please also consider the new update that is merged to xray recently.
https://github.com/XTLS/Xray-core/commit/fa5d7a255b95215916d93bf371aaea55ea758381

**Comment by ErfanTech** [comment]
are you using it for a simple outbound tunnel or reverse tunnel?
