### ISSUE TITLE
Bugs in the newest update

### ISSUE THREAD

**Issue by GoldExynos** [MHSanaei/3x-ui#183]

**Comment by Angize** [comment]
اره دقیقا لینک ها هم با وجود اینکه http camouflage فعاله ولی اشتباه نشون داده میشه
یا هدر تنظیم میکنی هم تو لینک نمایش داده نمیشه

ممنون بابت زحماتی که دولوپر این سورس کد میکشن عالی واقعا جای تشکر داره💖

**Comment by Angize** [comment]
یه باگ دیگه ای پیدا کردم 
موقعی که Start After Use رو فعال میشه 

برای بار اول همچین اروری تو xray نشون داده میشه
![Uploading IMG_20230410_125525_429.jpg…]()

**Comment by Angize** [comment]
![Uploading IMG_20230410_125525_429.jpg…]()

**Comment by Angize** [comment]
Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: VLESS settings: please add/set "decryption":"none" to every settings

این باگه هنوز رفع نشده مهندس
اینم یه چک کنی
