### ISSUE TITLE
Error run on archlinux docker

### ISSUE THREAD

**Issue by rayzpham** [MHSanaei/3x-ui#1837]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Currently, I use docker to run project but it maybe error by OS release of v2.1.3

![image](https://github.com/MHSanaei/3x-ui/assets/51695872/3c156495-b0b5-4416-ae65-749d38d27be3)
I tried `apk update` and `apk install curl` but it still error
![image](https://github.com/MHSanaei/3x-ui/assets/51695872/0e4dd530-1705-44df-b9f9-242e27706872)

### Version of 3x-ui

<details>

```console
v2.1.3
```

</details>

### x-ui log reports or xray log

<details>

```console
yourhostname:/app# x-ui
The OS release is: alpine

  3X-ui Panel Management Script
  0. Exit Script
————————————————
  1. Install
  2. Update
  3. Custom Version
  4. Uninstall
————————————————
  5. Reset Username & Password & Secret Token
  6. Reset Settings
  7. Change Port
  8. View Current Settings
————————————————
  9. Start
  10. Stop
  11. Restart
  12. Check Status
  13. Check Logs
————————————————
  14. Enable Autostart
  15. Disable Autostart
————————————————
  16. SSL Certificate Management
  17. Cloudflare SSL Certificate
  18. IP Limit Management
  19. WARP Management
————————————————
  20. Enable BBR
  21. Update Geo Files
  22. Active Firewall and open ports
  23. Speedtest by Ookla

Panel state: Not Installed
xray state: Running

Please enter your selection [0-23]: 1
The OS release is: alpine
arch: arm64
Failed to check the OS version, please contact the author!
```

</details>

**Comment by amirimatin** [comment]
Run bellow coomand
 apk --no-cache --update add   build-base   gcc   openssl   curl   socat   wget   unzip
