### ISSUE TITLE
ip limit problem- مشکل محدودیت آی پی 

### ISSUE THREAD

**Issue by r0zbeh** [MHSanaei/3x-ui#1840]
سلام من تمام مراحل رو طی کردم هم از گزینه شماره 18 نصب کردم هم لاگ فایل رو ست کردم و مستقیم هم به سرور خارج متصل هستم دقیقا همین مشکل رو دارم و ip هر دو دستگاه در باکس نوشته میشه و کانفیگ هم غیر فعال نمیشه در صورتی که من محدودیت رو روی 1 ip گذاشتم
کانفیگ های تست شده :
1-vless-tcp-tls
2-vless-ws-tls
د رضمن فایل لاگ هر چن ثانیه یه بار کلا پاک میشه و محتویاتش خالی میشه و دوباره نوشته میشه این درسته؟

**Comment by r0zbeh** [comment]
کسی جوابی نداره؟

**Comment by amirhr098** [comment]
از طریق ssh برید و لاگ fail2ban و آیپی های فیلتر شده رو ببینید. همینطور زمان ban کردن ip رو چک کنید.

**Comment by r0zbeh** [comment]
![ban problem](https://github.com/MHSanaei/3x-ui/assets/25858679/de2559cb-fd73-4286-a5bf-9112a2e911df)
لاگ خالیه اصلا ثبت نمیشه !! کسی میدونه مشکل از کجاست ؟ در تصویر مشخصه من محدودیت رو 1 گذاشتم ولی 2 تا یوزر وصلن !! لاگ هم خالیه !

**Comment by r0zbeh** [comment]
اصلا کسی هست این قابلیت براش کار کنه؟

**Comment by r0zbeh** [comment]
???????

**Comment by MHSanaei** [comment]
وقتی شما بیشتر از 10 ثانیه همزمان متصل باشین وارد پروسه بلاک کردن 
اون ip log مهم نیست چرا که یک ثانیه هم اگر وصل باشین اونجا ای پی میاد

**Comment by r0zbeh** [comment]
بله درسته  ، سورس رو مطالعه کردم باید 4 بار لاک بشه ولی برای جلوگیری از خطا منطقه با یه تغییر کوچیک راحت الان رو کلادفلر پیادش 
 کردم اوکیه یعنی پشت پروکسی هم جوابه !  ممنون
