### ISSUE TITLE
مشکل در گرفتن خروجی QR-cod 

### ISSUE THREAD

**Issue by hadi-rahmati** [MHSanaei/3x-ui#1843]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

در پروتکل تروجان روی xtls متاسفانه خزوجی QR-cod نمیسازه
ورژن Xray 1.7.5
ورژن 3X-UI 2.1.3

مشکل دیگه هم که وجود داره وقتی Xray ورژن میارم بالا تر ارور زیر میده 

Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: Please use VLESS flow "xtls-rprx-vision" with TLS or REALITY.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
سلام به خاطر اینکه در ورژن بالاتر از ۱.۷.۵ xtls از ایکس ری حذف شده
