### ISSUE TITLE
 How to use WARP

### ISSUE THREAD

**Issue by 404gods** [MHSanaei/3x-ui#1844]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I would like to inquire about the specific usage of Warp because I only see configurations for Google + Netflix + Spotify + OpenAI in the panel. How can I set up custom access to websites through Warp, such as reddit.com? Thank you.

### Version of 3x-ui

<details>

```console
# Paste here
```
2.1.3
</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
Edit warp rule and add your domains
Save and restart

**Comment by MolodoGvardeets** [comment]
Try to replace MTU 1420 to 1280
