### ISSUE TITLE
نشان ندادن ip ها

### ISSUE THREAD

**Issue by ali90500** [MHSanaei/3x-ui#1846]
سلام وقت به خیر من پنل رو روی سرور ایران نصب کردم و کامل تنظیمات ip limit رو هم انجام دادم اما در لاگ ip ها نوشته نمیشه و نوشته میشه no ip

**Comment by amirhr098** [comment]
اول از درحال اجرا بودن fail2ban روی سرورتون مطمئن شید. بعد در قسمت X-Ray config برید و در بخش Advanced همون قسمت اول رو به صورت زیر تغییر بدید درست میشه.
"log": {
  "access": "./access.log",
  "dnsLog": false,
  "loglevel": "warning"
  },

**Comment by ali90500** [comment]
![Uploading 1.png…]()

**Comment by ali90500** [comment]
![1](https://github.com/MHSanaei/3x-ui/assets/127780080/8b01e9ff-9d93-46b0-acb9-2c7a392c6d07)
![2](https://github.com/MHSanaei/3x-ui/assets/127780080/71ce23a3-640c-40dc-af10-a1bfdd8a41b2)
![3](https://github.com/MHSanaei/3x-ui/assets/127780080/d6a6c4c0-c224-451e-a50a-226ec67f6ac7)
همشو انجام دادم ولی بازم نشون نمیده

**Comment by amirhr098** [comment]
وقتی از ip tunnel استفاده میکنید این قابلیت کار نمیکنه.
میتونید از reverse استفاده کنید.
آپدیت هم کنید پنل رو :)

**Comment by ali90500** [comment]
از ریورس پنل به پنل استفاده میکنم و پنل به آخرین نسخه آپدیت هستش

> وقتی از ip tunnel استفاده میکنید این قابلیت کار نمیکنه. میتونید از reverse استفاده کنید. آپدیت هم کنید پنل رو :)
