### ISSUE TITLE
چند اینباند برای هر کاربر

### ISSUE THREAD

**Issue by xmohammad1** [MHSanaei/3x-ui#1850]
سلام وقت بخیر
ایا میشه مثلا دوتا اینباد داریم یکی vless tcp یکی vless ws وقتی یک کاربر میسازی اجازه دسترسی کاربر به هر دو رو بده و داخل لینک سابسکریپشن هم بیاد اینباند های کاربر
منظورم تقریبا یه چیزی تو مایه های پنل های دیگه مثل مرزبان و هیدیفای که هر کاربر میتونه همزمان چندین اینباد داخل لیستش داشته باشه

**Comment by MrOtto94** [comment]
بله 
میتونید قسمت سابکریبشن رو یکسان بزارید تا کاربر بتونه چند اینباند داشته باشه ولی مدیریت حجم ندارید

**Comment by MrOtto94** [comment]
بله 
میتونید قسمت سابکریبشن رو یکسان بزارید تا کاربر بتونه چند اینباند داشته باشه ولی مدیریت حجم ندارید

**Comment by xmohammad1** [comment]
نه خوب اون مدیریت حجمم خیلی مهمه

**Comment by vahid68-vpn** [comment]
سلام چرا از قبل داخل گروه بودم الان زدم روی گروه میزنه گروه خصوصی است و بعد گروه ها پاک شد الان من میخوام وارد گروه بشم باید چیکار کنم؟
