### ISSUE TITLE
فیلتر شدن دامنه در کمتر از 1 روز

### ISSUE THREAD

**Issue by Alij13a** [MHSanaei/3x-ui#1855]
سلام
راه حل برای حل مشکل فیلترینگ دامین ها چیه؟
روزی 2 بار دامنه هامون داره فیلتر میشه!

لطفا اگر راه حلی دارید بگید.

با تشکر

**Comment by amirhr098** [comment]
از دامنه های قدیمی استفاده کنید. یا از دامنه هایی که قبلا یک بار ثبت شده و منقضی شدن. از سایت هایی که auction دارن میتونین خریداری کنین. خیلی کمک میکنه بهتون. حتما هم tls استفاده کنید.
