### ISSUE TITLE
سرعت بسیار پایین

### ISSUE THREAD

**Issue by Alij13a** [MHSanaei/3x-ui#1856]
سلام
برای مشکل سرعت خیلی پایین کانکشن ها چه راه حل پیشنهاد میدید؟
تا 1 ماه پیش عالی بود ولی الان سرعت خیییلی خیلی اومده پایین...!

باتشکر

**Comment by Miladr9800** [comment]
با چک هاست تست کنید که ایپی کثیف نباشه
