### ISSUE TITLE
مسدود سازی تبلغیات

### ISSUE THREAD

**Issue by xmanirani** [MHSanaei/3x-ui#1857]
سلام وقت بخیر 
یه سوال داشتم 
همون جور که میدانید تو پنل یه مسدود سازی تبلیغات هست 
وی مشکل اینه بعضی وقتا کار میکنه بعضی وقتا نه 
مشکل از چیه بعضی وقتا تبلیغات حذف میشه بعضی وقتا نه؟؟

تنظیمات تانل از طریق Xray هستش

**Comment by behzadti** [comment]
باری من یوتیوب تبلیغات میزاره این مشکلم سر آپدیت های جدید اومده قبلا این مشکل رو نداشتم
