### ISSUE TITLE
یک کاربر در چندین اینباد

### ISSUE THREAD

**Issue by xmohammad1** [MHSanaei/3x-ui#1859]
سلام وقت بخیر, ممنون از پنل خوبتون
یه چیزی که بنظرم خیلی کمبودش حس میشه اینکه هر کاربری که میسازیم بتونه همزمان چندین اینباند داشته باشه و خوب قطعا محاسبه حجم هم اهمیت زیادی داره بنظرم یکی از ضعف های بزرگ x-ui در مقابل پنل های دیگس
این مورد رو اضافه کنید خیلی خوب میشه ممنون

**Comment by GoldenVDS** [comment]
اره خدایی اکانتینگ جدا باشه کاربر با حجم و تاریخ ساخته بشه بعد بهش پرمیشن بدیم به کدون انباند ها دسترسی داشته باشه خیلی عالی میشه
