### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by voono** [MHSanaei/3x-ui#186]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Issue with REST API "get all inbounds" -> "/xui/API/inbounds/"
I have tried the same request on alireza0's x-ui and it works but on this x-ui it returns "404PageNotFound"

### Version of 3x-ui

v1.1.5

### x-ui log reports or xray log

"404PageNotFound"

**Comment by mostafa9112** [comment]
Make sure ufing lastest ver
send request with GET
and run it on toy browser like this:
http://server.com:PORT/xui/API/inbounds/

**Comment by younesatesh** [comment]
Hello and good time my xui/API/inbounds
I clicked, but it shows 404 not found
