### ISSUE TITLE
1. RAY: [2354365848] app/proxyman/inbound: connection end 2. X-UI: add inbound traffic failed:database is locked

### ISSUE THREAD

**Issue by RT1477** [MHSanaei/3x-ui#1860]
Hello!
Thanks for your work!
I have two questions:
1. WARNING - XRAY: [2354365848] app/proxyman/inbound: connection ends > proxy/vless/inbound: 31cb905c-95f5-4f64-a849-ff4edd6db3be is not able to use "". Note that the pure TLS proxy has certain TLS in TLS characters.
2. WARNING - X-UI: add inbound traffic failed:database is locked

Should I do something about this?

**Comment by jameszeroX** [comment]
The same problem. 3x-ui v2.2.1, Ubuntu 20
`2024/03/06 12:53:32 WARNING - X-UI: add inbound traffic failed:database is locked
2024/03/06 10:56:48 WARNING - X-UI: add outbound traffic failed:database is locked
2024/03/06 10:56:43 WARNING - X-UI: add inbound traffic failed:database is locked
2024/03/05 21:04:48 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json`
