### ISSUE TITLE
CPU Usage over 90 percent

### ISSUE THREAD

**Issue by Sharevex** [MHSanaei/3x-ui#1863]
### Welcome

- [x] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Dear Mr.Sanaei , I've been using dokomodor tunneling system recently and unfortuanately , with 3 cored cpu , over 90 percent of the CPU is being used with only aboout 20 inbounds and 100-150 users 

I tried different methods to solve the problem but apparently it's a Bug within the Panel , I would really appreciate if the problem gets solved in the next Update . 

Also , when the CPU is being used aboutj 99 percent the Panel suddenly shuts down and shows a nginx default page.

Here is a photo of the panel :

![image](https://github.com/MHSanaei/3x-ui/assets/60724506/51812996-2879-4a78-b9cd-c64ade099f70)

Thanks for your Help .

### Version of 3x-ui

<details>

```console
v2.1.3
```

</details>

### x-ui log reports or xray log

<details>

```console
2024/02/21 09:40:29 WARNING - XRAY: core: Xray 1.8.7 started
2024/02/21 09:40:28 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/02/21 09:40:28 INFO - X-UI: web server run http on[::]:2086
```

</details>

**Comment by GoldenVDS** [comment]
> ### Welcome
> 
>     * [x]  Yes, I'm using the latest major release. Only such installations are supported.
> 
>     * [x]  Yes, I'm using the supported system. Only such systems are supported.
> 
>     * [x]  Yes, I have read all WIKI document,nothing can help me in my problem.
> 
>     * [x]  Yes, I've searched similar issues on GitHub and didn't find any.
> 
>     * [x]  Yes, I've included all information below (version, config, log, etc).
> 
> 
> ### Description of the problem,screencshot would be good
> 
> Dear Mr.Sanaei , I've been using dokomodor tunneling system recently and unfortuanately , with 3 cored cpu , over 90 percent of the CPU is being used with only aboout 20 inbounds and 100-150 users
> 
> I tried different methods to solve the problem but apparently it's a Bug within the Panel , I would really appreciate if the problem gets solved in the next Update .
> 
> Also , when the CPU is being used aboutj 99 percent the Panel suddenly shuts down and shows a nginx default page.
> 
> Here is a photo of the panel :
> 
> ![image](https://private-user-images.githubusercontent.com/60724506/306583351-51812996-2879-4a78-b9cd-c64ade099f70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MDc2NDQsIm5iZiI6MTcwODcwNzM0NCwicGF0aCI6Ii82MDcyNDUwNi8zMDY1ODMzNTEtNTE4MTI5OTYtMjg3OS00YTc4LWI5Y2QtYzY0YWRlMDk5ZjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDE2NTU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYzEyY2M3YWEyZTc0MDdiOGE5NDIwYzM0NDM3ZWU3NzkwOTEwNTU2MTk2NjQ2YWNmNjU4N2ZhYzE3ZTg4ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rnw3sIB8vcE2yW20E956LV01ku1jsNCQU6i2zRJgnOg)
> 
> Thanks for your Help .
> ### Version of 3x-ui
> ### x-ui log reports or xray log

I also have this problem and I saw that even with the test server on which I activated only one user, this happens 4 times a day

**Comment by MEM-917** [comment]
Sometimes when the log files get big enough this happens.  Make sure that the "access.log" and "error.log" aren't so big.
And, be sure to check the log files in the "/var/log " directive with "3xipl-" prefixes.
