### ISSUE TITLE
Change IP address on outgoing connections in 3X-UI

### ISSUE THREAD

**Issue by bwgit824** [MHSanaei/3x-ui#1866]
### Welcome

- [x] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Good evening.

I want the 3X-UI panel to set its IP address on outgoing connections to some domains, but for all other domains real IP address of the user remains

How can I do this?

I am using 3X-UI v1.7.9 / Xray: v1.8.4 (there are no such settings in latest versions).

I tried to add my domains to Panel Settings -> Array Configuration -> Manual Lists -> List of Direct Domains, but it doesn't work - the panel IP is assigned to the outgoing connection.

Config is like this:

      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "https://2ip.ru",
          "2ip.ru"
        ]
      },

### Version of 3x-ui

<details>

3X-UI v1.7.9 / Xray: v1.8.4

</details>

### x-ui log reports or xray log

<details>

      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "https://2ip.ru",
          "2ip.ru"
        ]
      },

</details>

**Comment by bwgit824** [comment]
Also I tried to use last (2.1.3) version. I added tag "direct" in Xray configs -> Outbounds:

    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "AsIs"
      }
    }

Then I added rule in Xray configs -> Routing Rules:

      {
        "type": "field",
        "domain": [
          "2ip.ru"
        ],
        "outboundTag": "direct"
      }

Dont working :(

**Comment by bwgit824** [comment]
Is this posible?

**Comment by Alijm05** [comment]
> Is this posible?

i'm not sure if i fully understand what you're trying to do/achieve, but if you mean that you wanna use direct connections for some inbounds, so i think its possible via the external proxy option from the inbound's section "try edit or by creating a new one, there will be the option i mentioned"...

i have a similar issue which is, im trying to achieve this with fallback...etc

regards. JM
