### ISSUE TITLE
پورت پیش فرض ورود به پنل از داکر

### ISSUE THREAD

**Issue by PouriyaKhalaj** [MHSanaei/3x-ui#1869]
سلام وقت بخیر
کسی اطلاع داره چطور میشه رو Docker پنل اورد بالا؟
البته من رو خود اوبونتو با پورت 2053 بالا اوردم میخوام رو داکر ببرمش یا یکی دیگه رو Docker توهمون سرور بیارم بالا
ممنون میشم از کسایی که تجربه دارن راهنمایی کنن🙏🏼

**Comment by Arman-nsb** [comment]
```
docker run -itd \
   -e XRAY_VMESS_AEAD_FORCED=false \
   -p 2053:2053 \
   -p 2096:2096 \
   -p 8080:8080 \
   -v $PWD/db/:/etc/x-ui/ \
   -v $PWD/cert/:/root/cert/ \
   --restart=unless-stopped \
   --name x-ui \
   ghcr.io/mhsanaei/3x-ui:latest
```

You have to open ports.

Panel Port: 2053
Sub Port: 2096
Example Inbound Port: 8080
