### ISSUE TITLE
عوض کردن متد اضافه کردن فرگمنت به سابسکریپشن و اضافه کردن گزینه Mux

### ISSUE THREAD

**Issue by farid220** [MHSanaei/3x-ui#1882]
با سلام

اول از همه میخواستم از همه زحماتتون بابت پنل خوبتون و آپدیت جدیدتون  تشکر کنم.

یه پیشنهادی بابت متد اضافه کردن فرگمنت به سابسکریپشن داشتم که مربوط به جدیدترین آپدیت 2.2.0 میشه.
در این آپدیت قسمتی جدیدی به اسم json اضافه شده که تنظیمات بخش فرگمنت فقط از اونجا قابل دسترسی هست. و ممکنه همه خروجی های کانفیگ فرگمنت نخواد و بخاطر همین توصیه میکنم به جای یه کانفیگ گلوبال, تنظیمات رو در قسمت اینباند قرار بدین اینجوری قابل تعریف هست اینباندی فرگمنت میخواد یا نه. در این حالت فعلی همه کانفیگ ها یا فرگمنت دارن یا ندارن.
در ضمن ممنون میشدم آپشنی واسه تنظیم فعال یا غیرفعال کردن و یا اندازه Mux هم قرار بدین.

**Comment by GoldenVDS** [comment]
> با سلام
> 
> اول از همه میخواستم از همه زحماتتون بابت پنل خوبتون و آپدیت جدیدتون تشکر کنم.
> 
> یه پیشنهادی بابت متد اضافه کردن فرگمنت به سابسکریپشن داشتم که مربوط به جدیدترین آپدیت 2.2.0 میشه. در این آپدیت قسمتی جدیدی به اسم json اضافه شده که تنظیمات بخش فرگمنت فقط از اونجا قابل دسترسی هست. و ممکنه همه خروجی های کانفیگ فرگمنت نخواد و بخاطر همین توصیه میکنم به جای یه کانفیگ گلوبال, تنظیمات رو در قسمت اینباند قرار بدین اینجوری قابل تعریف هست اینباندی فرگمنت میخواد یا نه. در این حالت فعلی همه کانفیگ ها یا فرگمنت دارن یا ندارن. در ضمن ممنون میشدم آپشنی واسه تنظیم فعال یا غیرفعال کردن و یا اندازه Mux هم قرار بدین.

دیگه اگر سروری دامنه فیلتر داشته باشه که مسلم هست همه اینباند ها فرگمت میخواهند.
درضمن حتی سرور فیلتر نباشه برای حفظ دامنه این قابلیت میتونه راهگشا باشه.

**Comment by vahid6889** [comment]
من هم نظرم اینه که به صورت گلوبال نباشه و برای هر اینباند بشه فرگمنت رو تنظیم کرد و اینکه طوری باشه که کانفیگ فرگمنت کاستوم بشه وارد و تنظیم کرد و اینطوری دیگه ماکس هم میشه بهش اضافه کرد
