### ISSUE TITLE
اضافه کردن باکس توضیحات در قسمت تعریف و ویرایش اکانت ها

### ISSUE THREAD

**Issue by Hesam-Mahmoodi** [MHSanaei/3x-ui#1884]
با سلام به توسعه دهندگان عزیز 
لطفا در قسمت تعریف اکانت جدید (Add Client) و ویرایش آن باکس توضیحات قرار دهید برای یاداشت کردن و توضیحات مخصوص آن اکانت برای اینکه  بعد ها با مراجعه به همین اکانت بتونیم توضیحات خاص همین اکانت رو ببینیم و بخونیم.

ممنون

**Comment by Miladr9800** [comment]
واقعا نیازه
