### ISSUE TITLE
nginx reverse proxy for web ui (external https to internal http)

### ISSUE THREAD

**Issue by Lavshyak** [MHSanaei/3x-ui#1886]
I wanna send requests to https://mydomain.com/xui and get the 3x-ui.
Now i can get 3x-ui at http://mydomain.com:2053 only.

I tried that:
```
server { #for test (works)
    listen [::]:4859;
    location / { return 200 'OK'; }
}

server {
        listen 443 ssl;
 
        ssl_certificate     /etc/letsencrypt/live/mydomen.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/mydomen.com/privkey.pem; # managed by Certbot
 
        server_name mydomen.com;
        
        location /test { proxy_pass http://localhost:4859; } # https://mydomen.com/test works

        location /xui { #for 3x-ui. does not work
                proxy_pass http://localhost:2053;
        }
}
```

but nothing happens. just no response.
how to do it properly? is it possible?

**Comment by MEM-917** [comment]
First of all, you need to set a name for the panel as a subdirectory.  Be sure to conclude it with "/". Lets say, you choose the name "AnArbitraryName". Your panel should look like this:
![image](https://github.com/MHSanaei/3x-ui/assets/133103062/3a0c04e6-28d2-4f72-8dc4-e81064d2d034)

Next, in the nginx you have to create a subdirectory for this name. Just replace the port number with your dedicated port which the panel listens to.

	location ^~ /AnArbitraryName/ {
		proxy_set_header	Host			$host;
		proxy_set_header	X-Real-IP		$remote_addr;
		proxy_set_header	X-Forwarded-For		$proxy_add_x_forwarded_for;
		proxy_pass		http://localhost:00000/AnArbitraryName/;
	}

Now, you have a secured panel with a dedicated directive and IP registration.

**Comment by Lavshyak** [comment]
> First of all, you need to set a name for the panel as a subdirectory. 

but I can connect to web ui via http://mydomain.com:2053 without panel name. so why "http://localhost:00000" in the nginx config is not enough?

And it means, that i need to send login and password via http to set a name for the panel as a subdirectory, it is security risks.

**Comment by MEM-917** [comment]
Because of nginx and panel's internal mechanism. You can easily achieve what you were seeking the the above method.
If you want to know more, this link is something that would be worth your while.

https://www.digitalocean.com/community/tutorials/nginx-location-directive
