### ISSUE TITLE
محدودیت دیوایس بجای ای پی لیمیت

### ISSUE THREAD

**Issue by mehdi2004usa** [MHSanaei/3x-ui#1887]
سلام و خسته نباشید
اگر ممکن باشه بجای ای پی لیمیت در پنل دیوایس لیمیت جایگزین بشه و از طریق مک ادرس دیوایسی که متصل میشه  مک ادرسش توی سرور ذخیره بشه و  یک یا چند دیوایس رو دسترسی بدیم. البته اگر اینکار شدنی باشه
سپاس

**Comment by TaraRostami** [comment]
Hello
Unfortunately, this cannot be done.
