### ISSUE TITLE
بلاک کردن آی پی

### ISSUE THREAD

**Issue by mohamadsohani** [MHSanaei/3x-ui#1894]
سلام 
مدتیه برای من نوتیفیکیشن تلگرام برای لاگین به پنل از یک آی پی خاص که مربوط به چین هست میاد ، مدام با یوزر های مختلف سعی در لاگین کردن به پنل من رو داره ، چطوری میتونم اون ای پی خاص رو بلاک کنم ؟ تو فایروال اوبونتو این کارو کردم اما چطوری میتونم بلاکش کنم نتونه حتی صفحه لاگین پنل منو رو باز کنه ؟
ممنونم ازتون

**Comment by Arman-nsb** [comment]
پیشنهاد میکنم مسیر عمومی رو از حالت پیشفرض در قسمت تنظیمات پنل تغییر بدید. یه مسیر پیچیده بذارید اینجوری دیگه اصلا صفحه لاگین رو نمیبینه که بخواد وارد بشه.
اگر دامنه پنل پشت cdn هست از قسمت waf میتونید آی پی رو بلاک کنید.

**Comment by mohamadsohani** [comment]
> پیشنهاد میکنم مسیر عمومی رو از حالت پیشفرض در قسمت تنظیمات پنل تغییر بدید. یه مسیر پیچیده بذارید اینجوری دیگه اصلا صفحه لاگین رو نمیبینه که بخواد وارد بشه. اگر دامنه پنل پشت cdn هست از قسمت waf میتونید آی پی رو بلاک کنید.

ممنونم از پاسختون، بله پشت کلود فلر گذاشتم

**Comment by mohamadsohani** [comment]
> پیشنهاد میکنم مسیر عمومی رو از حالت پیشفرض در قسمت تنظیمات پنل تغییر بدید. یه مسیر پیچیده بذارید اینجوری دیگه اصلا صفحه لاگین رو نمیبینه که بخواد وارد بشه. اگر دامنه پنل پشت cdn هست از قسمت waf میتونید آی پی رو بلاک کنید.

اون قسمت waf رو اد کردم اما بازم سعی میکنه با زورهای مختلق وصل بشه
اون قسمتی که فرمودید از حالت پیشفرض نغییر بدم کجا باید انجام بدم ؟ ممنون میشم راهنماییم کنید ، من خیلی نسبت به پنل وارد نیستم
ممنونم ازتون

**Comment by Arman-nsb** [comment]
Panel Settings > General Tab > URI Path
این مورد درحالت پیشفرض " / " هست میتونید به یه مسیر دلخواه تغییرش بدین مثلا: /secure-login/
بعد برای ورود باید این قسمت رو به انتهای آدرس قبل اضافه کنید تا صفحه ورود رو ببینید.

**Comment by mohamadsohani** [comment]
> Panel Settings > General Tab > URI Path
> 
> این مورد درحالت پیشفرض " / " هست میتونید به یه مسیر دلخواه تغییرش بدین مثلا: /secure-login/ بعد برای ورود باید این قسمت رو به انتهای آدرس قبل اضافه کنید تا صفحه ورود رو ببینید.

ممنونم ازتون
