### ISSUE TITLE
This connection is not secure | TLS | MHSanaei/3x-ui v2.1.3 | Local access

### ISSUE THREAD

**Issue by R3D-PLAN3T** [MHSanaei/3x-ui#1895]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام،
بعد از آپدیت به ورژن جدید ۲.۱.۳ این پیغام عدم وجود TLS بالای صفحه میاد که نمی‌شه دی‌اکتیوش هم کرد. 
برای کسی مثل من که از پشت سرور (آی‌پی داخلی) به پنل وصل می‌شه و پنل از بیرون از شبکه قابل دسترس نیستش، این پیغام آزاردهنده هستش. متأسفانه با هر رفرش هم دوباره ظاهر می‌شه. 
![Bildschirmfoto 2024-02-24 um 10 12 38](https://github.com/MHSanaei/3x-ui/assets/45637723/820376bc-84af-431e-871e-98be51e94f64)

### Version of 3x-ui

MHSanaei/3x-ui v2.1.3

### x-ui log reports or xray log

...

**Comment by MHSanaei** [comment]
برای دامنه خودتون cert بگیرید و داخل پنل قرار بدید

**Comment by R3D-PLAN3T** [comment]
دامنه cert داره از Let's Encrypt ولی من با IP داخلی 10.10.x.x وصل می‌شم به پنل

**Comment by R3D-PLAN3T** [comment]
@MHSanaei 
لطف می‌کنید اگر در نسخه‌ی بعدی امکان ignore کردن این پیغام رو قرار بدید.
