### ISSUE TITLE
اضافه کردن امکان انتخاب دامنه برای برای کانفیگ فرگمنت

### ISSUE THREAD

**Issue by meta-syfu** [MHSanaei/3x-ui#1896]
سلام ممنون بابت اضافه کردن فرگمنت.
اشکالی که داره اینه که وقتی کاربری با یک سابسکریبشن به چندتا کانفیگ دسترسی داره در فرگمنت کردن تمام کانفیگ و اکسترنال دامنه هارو هم در فایل json فرگمنت اضافه میکنه و این این امکان رو نمیده که دامنه مخصوص برای فرگمنت یا cdn رو براش مشخص کرد. لطفا این امکان رو اضافه کنین که انتخاب کنیم چه دامنه ای برای فرگمنت بزنیم. خیلی ممنونم ازتون

**Comment by H2mz** [comment]
Security Alert
Certain configurations have been identified as susceptible to attacks, prompting immediate action to reinforce security protocols and safeguard against potential security breaches.
- Subscription URI Path
- JSON URI Path


اتصال همراه اول و ایرانسل بعد اپدیت جدید قطع شده
