### ISSUE TITLE
مشکل ورود به گروه

### ISSUE THREAD

**Issue by vahid68-vpn** [MHSanaei/3x-ui#1898]
سلام خسته نباشید من داخل گروهتون بودم الان اومدم دیدم زده گروه خصوصی است و نشد وارد بشم و تمام گروه های شما برام پاک شد الان من چطور باید به گروه دسترسی داشته باشم ممنون میشم راهنماییم کنید

**Comment by MHSanaei** [comment]
گروه چند وقت پیش حذف شد

**Comment by vahid68-vpn** [comment]
اگه امکانش هست یک گروه بزنید خیلی به درد میخوره و از مشکلات و امکانات با خبر میشیم ممنون
