### ISSUE TITLE
Changing peer name for wireguard

### ISSUE THREAD

**Issue by Deniom3** [MHSanaei/3x-ui#1899]
Thanks for adding the ability to manage wireguard connections. 
I propose to add the ability to set a name for each wireguard peer connection for ease of use.

**Comment by ampetelin** [comment]
It would be really useful

**Comment by codemistake** [comment]
@MHSanaei could you please tell me how to use this feature if it is implemented?

**Comment by azharkov78** [comment]
> [@MHSanaei](https://github.com/MHSanaei) could you please tell me how to use this feature if it is implemented?

This is very useful if the wireguard is configured on the router to track the state or reconfigure after client reset
It is also easier to delete a client by its name
Also some statistics are needed: last handshake and traffic
