### ISSUE TITLE
Reality

### ISSUE THREAD

**Issue by Wolf6470** [MHSanaei/3x-ui#190]
درود و ممنون از ساپورت خوبتون.یک سوال داشتم اینکه در ریلیتی از چه پورت هایی می توانیم استفاده کنیم

**Comment by MHSanaei** [comment]
فکر نمیکنم محدودیتی در پورت ها وجود داشته باشه

**Comment by taha-ghadirian** [comment]
سلام. فعلا از همه پورت های باز روی سرور میتونید استفاده کنید.

**Comment by Wolf6470** [comment]
آخه من با ۸۴۴۳ ساختم جواب نداد.راستی اون قسمتش بعد آدرس گیت پورت ۴۴۳ گذاشته اون رو هم باید تغییر بدیم؟

**Comment by MHSanaei** [comment]
باید ای پی تمیز داشته باشید 
اون قسمت 443 که کنار dest نوشته رو عوض نکنید
