### ISSUE TITLE
روش reverse proxy url برای لینک subscription 

### ISSUE THREAD

**Issue by Masouddhojaei** [MHSanaei/3x-ui#1900]
درود وقت بخیر
این گزینه reverse proxy url در بخش ساب رو چطور باید استفاده کنیم؟ با آیپی فیلتر خارج میشه از این گزینه برای تانل زدن لینک ساب به سرور ایران استفاده کرد؟

**Comment by meta-syfu** [comment]
با nginx reverse proxy میتونی بزنی و استفاده کنی
