### ISSUE TITLE
Advanced Xray Configuration - Manual code - Duplication & repetition bug

### ISSUE THREAD

**Issue by Phoenix-999** [MHSanaei/3x-ui#1904]
Testing the v2.2.0 version of the 3x-ui panel, I noticed that when the user adds _(Copy & Past)_ a **custom Xray Configuration** to the advanced section on the panel, the code gets duplicated and repeated twice automatically.

Additionally, clicking on the section selects all the text and doesn't allow you to manually select a specific part in the code or delete/paste manually.

![Screenshot 2024-02-25 at 08 22 55](https://github.com/MHSanaei/3x-ui/assets/127796122/15d9c104-b760-41fe-a906-ddb0fe938477)

### Version of 3x-ui

![Screenshot 2024-02-25 at 08 25 44](https://github.com/MHSanaei/3x-ui/assets/127796122/afa33383-9117-492b-9e1b-9cdf991908de)

**Comment by MHSanaei** [comment]
Yes sorry about that I just fixed maybe today I released a new version with ultra-dark mode
