### ISSUE TITLE
Installing older versions

### ISSUE THREAD

**Issue by Trenobol** [MHSanaei/3x-ui#1910]
New versions 3x require Debian 11-12
How can I install older versions (2.0.2 and older) on the server with Debian 10 ?

I've tried
bash <(curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh) v2.0.2 
bash <(curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh) v1.7.0

I copied the version archive to the server and ran it
But it still requires Debian 11-12

**Comment by amirhr098** [comment]
You can't install it on Debian 10 anymore. But if you don't have a choice you can clone this repository and edit the 'install.sh' file, line 58, and change "11" to "10". After that you can 'curl' using your colned file link and install the version you need.
