### ISSUE TITLE
خطا در تنظیمات ایکسری

### ISSUE THREAD

**Issue by farshadfaza** [MHSanaei/3x-ui#1912]
سلام امروز من سعی کرد وارد تنظیمات اکس ری بشم و چن گزینه رو فعال کنم ولی بعد وارد شدن به تنظیمات با این خطا روبرو میشمو نمیتونم چیزیو فعال کنم
![IMG_20240225_183552_272](https://github.com/MHSanaei/3x-ui/assets/25201154/f00f9f77-943b-4722-a7db-34747b400dc7)
![IMG_20240225_183547_632](https://github.com/MHSanaei/3x-ui/assets/25201154/7fc18566-e6e7-4797-b162-ae839a9d1302)

**Comment by MHSanaei** [comment]
توی متن اپدیت توضیح داده شده بعد از اپدیت دکمه "Reset to Default" رو بزنید

**Comment by farshadfaza** [comment]
اینم یه ویدیو دیگه کامل تر

https://github.com/MHSanaei/3x-ui/assets/25201154/50528be1-56b3-4348-b7c8-4aa6ce25b522

**Comment by farshadfaza** [comment]
من ریست سیتینگ تو ترمینالم زدم یه بار کلا حذف کردم دوباره نصب کردم پنلو رو یه سرور دیگه نصب کردم بکاپو ریختم همینجوریه

**Comment by MHSanaei** [comment]
مثل اینکه دیتابیس شما مشکل خورده باید دستی ویرایش کنید با کمک این برنامه 
https://sqlitebrowser.org/

**Comment by farshadfaza** [comment]
چیکارش کنم ایمیلی ایدی چیزی دارین بدین اطلاعات سرور بدم خدمتتون یا برای اقا علیرضا ایمیل کنم؟

**Comment by farshadfaza** [comment]
چیو باید تغییر بدم الان برنامه رم نصب کردم بکاپم انداختم لیست اکانت ها هم هست

**Comment by farshadfaza** [comment]
همچیو نگا کردم حتی یه پنل رو یه سرور دیگه نصب کردم تنظیمات اکس ری اونو تو تنظیمات اکسری اون با برنامه دیتا بیس گذاشتم نشد باز
