### ISSUE TITLE
ارتقای ربات پنل

### ISSUE THREAD

**Issue by softmaj7** [MHSanaei/3x-ui#1916]
با سلام و خسته نباشید
اینقدر امکانات پنل عالی و کامل تر شده حس خوبی بهمون میده با پنل کار کنیم دمتون گرم 🙏
لطفا اگه براتون مقدوره یه ربات دیفالت واسه پنل تعریف کنید که باهاش بتونیم یوزر و کانفیگ بسازیم و کاربران رو مشاهده کنیم. واقعا پنل به این عالی جای هالی رباتش حس میشه. هر طور شما صلاح بدونید و ممنون بخاطر زحمت هاتون.
همیشه موفق باشید🌹

**Comment by matinalma** [comment]
ارور موقعه تانل از سرور خارج به ایران
موقعه تانل کردن کانفیگ کار نمیکنه
