### ISSUE TITLE
کار نکردن dokodemo-door

### ISSUE THREAD

**Issue by xmohammad1** [MHSanaei/3x-ui#1917]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام خسته نباشید
پروتوکل dokodemo-door تو نسخه 2.1.3 کار میکنه ولی وقتی اخرین ورژن نصب میکنم (2.2.0) دیگه کار نمیکنه

### Version of 3x-ui

<details>

```console
2.2.0
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by usamirali** [comment]
درود 
دقیقا همین مشکل رو دارم اتصال به خارج درست برقرار نمیشه تو نسخه قبل خیلی خوب بود تو این نسخه پینگ و اتصال به شدت کند هست

**Comment by usamirali** [comment]
یه مشکل دیگه داخل قسمت xray هر متنی که کپی یا پیست میکنیم دوبار اعمال میشه یعنی متن دوبار پیس میشه

**Comment by MHSanaei** [comment]
مشکل از سمت خودتون هست با تشکر
