### ISSUE TITLE
Ip limit dont work in reality

### ISSUE THREAD

**Issue by DarkZo0m** [MHSanaei/3x-ui#192]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Moshkel Inke IP Limit Dakhel Reality Kar nemikone!

### Version of 3x-ui

1.2.0

### x-ui log reports or xray log

-

**Comment by MHSanaei** [comment]
مشکلی نداره

**Comment by DarkZo0m** [comment]
من الان دارم تست میکنم و روی هر دو تا کلاینت برخلاف پروتکلای دیگه کار میکنه فقطم مشکل از reality ه
