### ISSUE TITLE
تغییر رنگ بک گراند تیره

### ISSUE THREAD

**Issue by madar54** [MHSanaei/3x-ui#1920]
با تشکر از جناب سنایی و دیگر بزرگان این عرصه چنانچه رنگ بک گراند تیره در ورژن جدید به رنگ نرم‌افزارهای شرکت ادوبی تغییر پیدا کند بسیار جذاب‌تر خواهد بود
![Screenshot 2024-02-26 125009](https://github.com/MHSanaei/3x-ui/assets/153379079/345a7098-98b8-4d94-a638-b2df8ec87b81)

**Comment by TaraRostami** [comment]
😕
![Screenshot 2024-02-28 074843](https://github.com/MHSanaei/3x-ui/assets/132676256/b0d66f38-dea1-4728-b9c3-c48cc8f5098a)

**Comment by madar54** [comment]
بسیار عالی و زیبا همچنین تشکر از  شما مقایسه کنید با ورژن تیره و تفاوت را  احساس می‌کنید.
حال چگونه می‌توان این بک گراند را تعویض کرد آیا باید جناب سنایی تغییرات را ایجاد کند یا کاربر هم می‌تواند این کار را انجام دهد? 
![12](https://github.com/MHSanaei/3x-ui/assets/153379079/0edc11de-a85a-47c3-8dd0-27507986a978)
