### ISSUE TITLE
Security Warning

### ISSUE THREAD

**Issue by piglushkin** [MHSanaei/3x-ui#1921]
This connection is not secure. Please refrain from entering sensitive information until TLS is activated for data protection.
![2024-02-26_14-06-41](https://github.com/MHSanaei/3x-ui/assets/161313657/52b57acc-e882-4279-9b39-bab67be66ec4)

Good afternoon, what is the FOOD safety error, how can I fix it?

**Comment by Masouddhojaei** [comment]
اگه روشی باشه این وارنینگ رو غیرفعال کنیم هم خیلی بهتره
چون وقتی SSL فعال میکنیم برای restore کردن دیتابیس به مشکل میخوریم واسه همین بدون SSL کار میکنن بعضیا.

**Comment by piglushkin** [comment]
Как это напоминание отключить?

пн, 26 февр. 2024 г. в 16:07, Masouddhojaei ***@***.***>:

**Comment by piglushkin** [comment]
Will it interfere with work somehow? How can I disable this reminder?

**Comment by AsunaYukky** [comment]
@Avaisov @piglushkin
Thats cause you use http connection to webpanel, not https. 
If you have domain connected to server you just need to create ssl certificate from letsencrypt using 3x-iu bash menu. If you do not have a domain (use only ip address) -  you can create self-signed certificate. I wrote an instruction in wiki, how to do this.  https://github.com/MHSanaei/3x-ui/wiki/How-to-create-self%E2%80%90signed-SSL-certificate-for-3X%E2%80%90UI-webpanel-(also-if-you-don't-use-domains)

**Comment by muradurm** [comment]
I would like to disable this warning. I don't need https because the http port is not accessible from outside, it's blocked by firewall.
