### ISSUE TITLE
vps with only 20 open ports

### ISSUE THREAD

**Issue by sayrelax** [MHSanaei/3x-ui#1923]
I have a vps server with only 20 open ports (e.g. 11000-11019) and one ssh (e.g. 11020) (vps over nat). therefore, I cannot connect to the 3xui panel after installation, port 2053 is not available for my VPS. could you add the ability to select free ports taking into account the range open during installation as requested when installing warp?

**Comment by Hmdrf** [comment]
you ca easly type x-ui in command line aftar that press 7 and change the port
