### ISSUE TITLE
قطع ارتباط در روش ریورس پنل تو پنل

### ISSUE THREAD

**Issue by iamsam55** [MHSanaei/3x-ui#1927]
وقتی تونلی با روش ریورس پنل تو پنل میزنم ارتباط سرور ها بعد از یه مدت قطع میشه و ترافیک رد بدل نیمشه باید حتما سرور خارج رو عوض کنم تا دوباره ارتباط برقرار بشه

**Comment by amirhr098** [comment]
دقیق تر توضیح بدین.

**Comment by iamsam55** [comment]
> دقیق تر توضیح بدین.
ببینید من دارم داخل سرور ایران یه اینباند  مثلا  پورت 1010 میسازه بعد تو قسمت ریورس پنل ایران یه پرتال میسازم ترافیک اینباند های که یوز دارم رو میفرستم به این تک اینباند  1010 توی خارج ( حالا مهم نیست سرور فیلتر باشه یا نه ) یه outbound اضافه میکنم که کانفیگش همون کانفیگ پورت 1010 ایرانه حالا میام تو قسمت ریورس سرو خارج یه bridge   میسازم این outbound رو وصل میکنم به outbound freedom سرور خارج ترافیک به راحتی رد میشه ولی مشکل اینه یهو انتقال ترافیک قطع میشه باید حتما سرور خارج رو عوض کنم تا دوباره راه بیوفته

**Comment by amirhr098** [comment]
@MHSanaei 
این مشکل تو ریورس خیلی پیش میاد که قطع بشه. تا جایی که من بررسی کردم وقتی xray سرور ایران ریست میشه دوباره متصل میشه. و توی لاگ هم هیچی نیست.
وقتی قطع میشه توی v2rayn این ارور رو میده:
wsasend: An established connection was aborted by the software in your host machine.
