### ISSUE TITLE
get 404 in xui/API/inbounds/list

### ISSUE THREAD

**Issue by mostafa9112** [MHSanaei/3x-ui#193]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

hi this path return 404 page not found:

xui/API/inbounds/list

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
سلام بله این قسمت رو تازه دیدم توی pull req که چند روز پیش فرستادن دقت نکردم به جای get دوستمون post گذاشته بود امروز تصحیح کردم ولی انشالا برای اپدیت بعدی میتونید استفاده کنید
