### ISSUE TITLE
Security Alert This connection is not secure. Please avoid entering sensitive information until TLS is activated for data protection. What is it and how to fix it?

### ISSUE THREAD

**Issue by Avaisov** [MHSanaei/3x-ui#1932]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Security Alert This connection is not secure. Please avoid entering sensitive information until TLS is activated for data protection. What is it and how to fix it? 
<img width="1676" alt="Снимок экрана 2024-02-27 в 15 53 09" src="https://github.com/MHSanaei/3x-ui/assets/120126001/6de30c96-b267-4f87-848e-9029f2c43910">

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Avaisov** [comment]
@AsunaYukky Thanks a lot for the answer and instructions, I will try. Can you tell me if the lack of a certificate has a strong impact on security and performance?

**Comment by AsunaYukky** [comment]
@Avaisov  when you use http connection to webpanel - your traffic is not encoding, and everybody between you and server can see all the data, that you put in fields (like login - pass), and all  the data, that webpanel gives to you (like qr codes, subscription,  etc..). https solves this problem.

**Comment by AsunaYukky** [comment]
@Avaisov 
Wrong way man. You wrote /us/... , but must be /usr/... at Public key field

**Comment by Avaisov** [comment]
@AsunaYukky Yes thank you, now I have this screen
<img width="1457" alt="Снимок экрана 2024-02-28 в 13 08 15" src="https://github.com/MHSanaei/3x-ui/assets/120126001/bf5d28f7-1a8d-4964-9854-77943c11b200">

**Comment by Avaisov** [comment]
I'm sorry, everything is working fine. Thank you very much!

**Comment by AsunaYukky** [comment]
@Avaisov it tells that you have default configuration at "URI path" field . Just change it to something additional, like /mysuperpanel/ =),
