### ISSUE TITLE
Text editor in "xray config">"advanced" is broken

### ISSUE THREAD

**Issue by AminX97** [MHSanaei/3x-ui#1933]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

text editor in "advanced" page doesn't work properly for some reason. when i press enter, two new lines will be created with no indentation. Also, copy and paste dont work.

### Version of 3x-ui

<details>

```console
version 2.2.0
```

</details>

### x-ui log reports or xray log

<details>

```console
```

</details>

**Comment by MHSanaei** [comment]
its fixed now - wait for 2.2.1 update
