### ISSUE TITLE
باگ ربات تلگرام لطفا سریعا مورد برسی بشه

### ISSUE THREAD

**Issue by ghojaei1995** [MHSanaei/3x-ui#1934]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

در آپدیت جدید بات تلگرام به مشکل خورده ، آمار و اطلاعات 
برخی کاربران رو نه با آیدی عددی نه با آیدی تلگرامی و نه با کامند /usage بهشون نمیده و میگه پیکربندی یافت نشد، فقط اطلاعات رو به ادمین میده.
لطفا این موضوع رو سریعا حل بفرمایید

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
تست شد مشکلی وجود نداره
