### ISSUE TITLE
کامنت گذاشتن در یوتیوب

### ISSUE THREAD

**Issue by mahdigh73** [MHSanaei/3x-ui#1935]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام خدمت همگی
من با کانفیگ v2ray نمیتونم توی یوتیوب واسه کسی کامنت بزارم ممنون میشم بگید مشکل از کجاست.
اخرین ورزن سنایی رو استفاده میکنم ، vless ws tls با تونل reverse

### Version of 3x-ui

latest

### x-ui log reports or xray log

latest

**Comment by amirhr098** [comment]
اول از همه برین داخل محیط Inspect و در تب network وقتی که سعی میکنید یک کامنت بذارید یه درخواست به لینکی که پایین گذاشتم ارسال میشه. ببینید response که برمیگرده از این درخواست چیه.

"https://www.youtube.com/youtubei/v1/comment/create_comment?prettyPrint=false"
