### ISSUE TITLE
subscription reality bug

### ISSUE THREAD

**Issue by Behzadwow** [MHSanaei/3x-ui#194]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

در نسخه 1.2.0 subscription فیلد های reality کپی نمی شود.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Mostapha22** [comment]
آقا چجوری میشه لینک سابسکرایپ ساخت

**Comment by MHSanaei** [comment]
درسته، اپدیت بعد سعی میکنم درستش کنم

**Comment by itmahdi** [comment]
> آقا چجوری میشه لینک سابسکرایپ ساخت

وقتی کانفیگت رو ساختی داخل پنل برو قسمت + کنار یوزرت علامت مداد رو بزن تا edit client واست باز بشه توی پنجره ای که باز میشه برات subscription رو میبینی یه اسم دلخواه بهش بده 
سیو کن بعد گزینه کنار مداد detail رو بزن لینکتو نمایش میده

**Comment by rafiee** [comment]
واقعا هنر نزذ ایراینیان و است و بس. 
واقعا پنل بی نظیری دارید. ممنون از زحمات شما.
فقط یک سری مشکل و یک پیشنهاد داشتم.
اول اینکه لینک سابسکریپشن برای من کار نمی کنه و وقتی اطلاعات رو میاره به صورت clash_custom  و یه سری اطلاع اشتباه میاره. هم تو گوشی و هم تو ویندوز این مشکل هست.
پیشنهاد هم اینه ای کاش میشد مثل پنل مرزبان، برای یک کاربر چند کانفیگ رو در یک لینک تحویل داد.  من برای اینکار میام دو تا کانفیگ مختلف می سازم برای یک کاربر، ولی مشکل اینه باید اسم کاربر در هر کانفیگ متفاوت باشه.
بازم ممنون از زحمات شما

**Comment by MHSanaei** [comment]
#225

**Comment by rafiee** [comment]
من به جدیدترین ورژن 1.2.2 آپدیت کردم. اما همچنان لینک subscription  اطلاعات رو درست وارد نمی کنه و به نام custon  و clas_custom  وارد میشه
