### ISSUE TITLE
After command docker exec -i 3x-ui x-ui  got  panel state: not installed

### ISSUE THREAD

**Issue by sayrelax** [MHSanaei/3x-ui#1944]
Hi
After command "docker exec -i 3x-ui x-ui"  got  "panel state: not installed" so can not change any settings. Could Please someone explane how to fix

3x-ui installed with docker

**Comment by lbx-ai** [comment]
I also encountered this situation

**Comment by lbx-ai** [comment]
how to fix it?

**Comment by smbrine** [comment]
> how to fix it?

I guess we just have to wait until they update a docker image or one can theoretically create a custom docker image
