### ISSUE TITLE
Why isn't the usage statistics updating for clients on my VPN?

### ISSUE THREAD

**Issue by DenisM1303** [MHSanaei/3x-ui#1945]
I have 4 clients, and the traffic usage information only updates at the beginning of usage. The statistics were updated up to 1 GB, and then it doesn't refresh. It shows that one of my clients has used 1.60 GB, but this is not updated statistics. He has already downloaded more than 5 GB, and the same goes for all clients. How can I update the statistics?

How can I limit the number of simultaneously connected devices to one VLESS key? Can this be done in 3x-UI? Thanks to everyone!
![1](https://github.com/MHSanaei/3x-ui/assets/126622119/2b48ea7d-e210-4530-ac9a-6fc9c899185d)

**Comment by DenisM1303** [comment]
> vless协议上统计流量有点问题，建议你用vmess，两者没有区别。

问题是，我需要 vless - reality
你不知道如何将连接设备的数量限制在一个客户端？

**Comment by OuOumm** [comment]
> > vless协议上统计流量有点问题，建议你用vmess，两者没有区别。
> 
> 问题是，我需要 vless - reality 你不知道如何将连接设备的数量限制在一个客户端？

emm，IP连接数改成1就行了，然后你需要的话，就没办法了，反正vless统计流量确实有问题，建议用vmess
