### ISSUE TITLE
WARP routing for Microsoft

### ISSUE THREAD

**Issue by pooyafo** [MHSanaei/3x-ui#1946]
When we attempt to access Microsoft services such as the Store or Windows Update using our VPN server, the connection is dropped by Microsoft. It would be extremely helpful if you could include Microsoft IPs in WARP routing, as you have done for other companies such as Google, Meta, Apple, etc.

**Comment by Farhanadabi** [comment]
I have added manually but still when trying to search something facing with this page :

![Screenshot 2024-05-16 194338](https://github.com/MHSanaei/3x-ui/assets/103530406/463ca0dc-ed3d-4c23-a3f7-5746a93b8a8b)

**edited json**
![Screenshot 2024-05-16 194202](https://github.com/MHSanaei/3x-ui/assets/103530406/145fe8b7-dd2f-4cfb-991b-033edd97226c)
