### ISSUE TITLE
طریقه آپدیت کردن

### ISSUE THREAD

**Issue by mobinmoji** [MHSanaei/3x-ui#1948]
سلام به شما یه سوال داشتم من x-ui ورژن ۲.۲.۰ دارم وقتی از طریق شل میزنم اپدیت بشه (مسیر رو به رو رو میرم  shell -> x-ui-> number 2-> y-> n) ولی وقتی داخل پنلم میشم هنوز میزنه ورژن من ۲.۲.۰ هستش کجای کار رو اشتباه میرم

**Comment by MHSanaei** [comment]
بعد از ۲ فقط کافیه همش اینتر بزنید کار دیگه ای لازم نیست نسخه اخر نصب میشه راحت
