### ISSUE TITLE
No site icon with https connection

### ISSUE THREAD

**Issue by dorian6996** [MHSanaei/3x-ui#1949]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

If i open my panel with out ssl certs, it shows 3x-ui icon on address panel, when adding a certificate, the icon is not displayed, only the first letter of my domain/IP address as on sites with out favicon. Are there ways to return the icon to how it works with http? Cert generated from 3x-ui concole, if it matter. Thanks

### Version of 3x-ui

v2.2.1

### x-ui log reports or xray log

empty

**Comment by MHSanaei** [comment]
we remove favicon after v2.2.0
