### ISSUE TITLE
why copy my code while didn't credit me?

### ISSUE THREAD

**Issue by FranzKafkaYu** [MHSanaei/3x-ui#195]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

copy my code again,this is not the first time.
Last time you copied my code and I point it out,this time again.But you didn't credit me, it's not good.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
And you know that's why I am unwilling to release my code now.

**Comment by FranzKafkaYu** [comment]
this commit :https://github.com/MHSanaei/3x-ui/commit/abb79bd97889e6e75fcd5a3a23e737c993906ffb

**Comment by FranzKafkaYu** [comment]
Next time I have to considering make more complicated obfuscation

**Comment by FranzKafkaYu** [comment]
if you didn't make any action,I have to reported to github and announce this situation publicly.

**Comment by FranzKafkaYu** [comment]
> hi franzkafka I'm glad to meet you again sorry about that but maybe you forgot your license is gpl3.0 so we can copy everything anyway i just add your name to last release [here](https://github.com/MHSanaei/3x-ui/releases/tag/v1.2.0) i hope you like it enjoy

That's OK, anyway copy other's code WITHOUT any credit is not good.I hope you know what I mean here. IT'S not about LICENSE, It's about all of our efforts for this Project.

**Comment by mostafa9112** [comment]
> > hi franzkafka I'm glad to meet you again sorry about that but maybe you forgot your license is gpl3.0 so we can copy everything anyway i just add your name to last release [here](https://github.com/MHSanaei/3x-ui/releases/tag/v1.2.0) i hope you like it enjoy
> 
> That's OK, anyway copy other's code WITHOUT any credit is not good.I hope you know what I mean here. IT'S not about the LICENSE, It's about all of our efforts for this Project.

Isn't your code free?
Is donation mandatory?
That's when you update late!
