### ISSUE TITLE
many unknown ports opened

### ISSUE THREAD

**Issue by qiangweihewu** [MHSanaei/3x-ui#1951]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi there!
I am confused why there are so many unknown ports opened that I didn't set on the pannel. Here are the snapshots which clearly shows that the ports are not quite match to each other.
Looking forward to your reply! Thanks!
![image](https://github.com/MHSanaei/3x-ui/assets/91766951/4684ff92-f72f-4bbe-a3ea-ab8a6eea2d58)
![image](https://github.com/MHSanaei/3x-ui/assets/91766951/ba68a12b-dffe-48dd-8825-c515d928a0c3)

### Version of 3x-ui

<details>
x-ui 2.2.1
```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
![Screenshot_20240229_201730_Chrome.jpg](https://github.com/MHSanaei/3x-ui/assets/33454419/450baf9e-3568-4153-9a1b-02b8fb0b9f35)

These are the ports you have not remark
