### ISSUE TITLE
games

### ISSUE THREAD

**Issue by karen2030** [MHSanaei/3x-ui#1967]
میخواستم بدونم بهترین کانفیگ برای بازی چی بذاریم که پینگ پایین تری داشته باشه و اگر نمیشه چه راهی رو پیشنهاد میدین ؟

**Comment by MHSanaei** [comment]
سرورهای نزدیک به ایران پینگ کمتری دارند 
استفاده از dns هایی که هست مثل shecan.ir

**Comment by karen2030** [comment]
مورد بعدی اگر خودمون رو سروری که داریم DOH راه بندازی در پینگ و سرعت تاثیری داره و همینطور پروتکلی که استفاده میکنیم چطور به اونم بستگی داره ؟
