### ISSUE TITLE
کار نکردن ربات تلگرام با 2 ورژن اخیر

### ISSUE THREAD

**Issue by hunter-xyz** [MHSanaei/3x-ui#1969]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

مهندس sanayi عزیز امیدوارم این تاپیک رو بخونی 

با 2 ورژن اخری که اپدیت دادی یعنی 2.2.1 و 2.2.0 یه مشکلی برای ربات تلگرام بوجود اومده که اگر اکانت جدیدی رو بخوای واسش ربات فعال کنی که میری مثل همیشه آیدی تلگرام رو براش ثبت میکنی ولی کاربر وقتی get usage میزنه این پیام میاد : 
Your configuration is not found!
Please ask your admin to use your Telegram ID in your configuration(s).

Your User ID:xxxxxxxxxx

جالبه اکانت هایی که تا قبل از اپدیت پنل معرفی شدن به ربات همگی بدرستی کار میکنن فقط جدید ها کار نمیکنند !!

ورژن رو دانگرید کردم به 2.1.3 یا 2.1.2 دقیق یادم نیست یکی از اینها دوباره تست کردم دیدم هنوزم مشکل پا بر جاست که به ذهنم رسید برم با ربات remove telegram user رو بزنم و از نو معرفی کنم که امتحان کردم اوکی شد و امار رو با درخواست کاربر ارسال میکرد 

سرور رو اپدیت کردم دوباره به ورژن اخر 2.2.1 بعد get usage زدم باز امار ارسال نشد !  یه بار remove user زدم دوباره معرفی کردم بی فایده بود 

لطفا این مورد رو بررسی کنید 

( ضمنا اگر ورژن xray هر چیزی بالاتر از 1.8.1 باشه مدام xray ری استارت میشه مخصوصا 1.8.8 برای همین من گذاشتم روی 1.8.1 و مشکلی ندارم دیگه )

ممنون 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
قبلا گفتم باید چت ایدی رو وارد کنید نه ایدی تلگرام  از اپدیت ورژن 2 فکر کنم 
موفق باشید

**Comment by hunter-xyz** [comment]
مهندس عزیز من دارم از بات یوزر معرفی میکنم مثل همیشه ولی با توجه به اینکه ID میگیره اکانت مشتری ولی باز وقتی get usage میزنی میگه ثبت نشده 

خب کجای کار من اشتباهه ؟

**Comment by hunter-xyz** [comment]
الان مجدد تست کردم درست شد و کار میکنه !!! البته یه بار اپدیت زدم ولی ورژن تغییر نکرده ، نمیدونم کاری کردی یا نه مهندس ولی مشکل رفع شد 

دوستانی که مشکل داشتن برن روی اکانتی که Telegram ID زدن اول پاک کنن سیو کنن بعد دوباره ادیت اکانت بزنن و ID رو وارد کنن و سیو 

درست میشه اینطوری من 2 نفر که مشکل داشتن رو اینطوری الان زدم اوکی شدن 

![image](https://github.com/MHSanaei/3x-ui/assets/142353771/45af8642-dbdb-4e77-a575-0fa692d26917)

**Comment by hunter-xyz** [comment]
علت دقیق این مشکل را فهمیدم وقتی با ربات کاربر تلگرام را برای اکانت معرفی میکنید در انتهای ایدی یک Space میوفته اگر برید اکانت رو از پنل باز کنید برای ویرایش میبینید بعد از اخرین عدد یک فاصله وارد شده ! و همین باعث این مشکل شده و منم الان اتفاقی لاگ سرور رو دیدم و فهمیدم مشکل میتونه این باشه 

لاگ سرور :

![image](https://github.com/MHSanaei/3x-ui/assets/142353771/8afb8404-d34a-4322-8bec-70fdc9aa5f52)


حتی در همین عکس که من مارک دارش کردم مشخصه انتهاش فاصله داره !

خلاصه علت فقط همین بود !

**Comment by hunter-xyz** [comment]
اخه میدونید بد بختی کجاست 

اینجاست که اگر بتونه اینو حل کنه یه مشکل جدید و بد تر ایجاد میکنه روی سرور 

من دیگه تصمیم گرفتم اپدیت نکنک همش اپدیت میاد همش یه مشکل حل میشه یه مشکل بد تر و جدید اضافه میشه 

این مشکل خیلی مشکل خوبی هست مشکلی ندارم باهاش
