### ISSUE TITLE
مشکلات پنل سنایی

### ISSUE THREAD

**Issue by Miladr9800** [MHSanaei/3x-ui#1973]
سلام.
مشکل یک؟ من ۵پنل دارم و برای هر پنل یک ربات تلگرام معرفی کردم و همه ربات ها روی یک ایدی تلگرام(یک شماره تلگرام) ساخته شدن ، و اما فایل بکاپ که ربات تلگرام میفرسته فقط برای پنل اولیه

**Comment by Miladr9800** [comment]
مشکل دو: زمان اپدیت خودکار سابسکریشن کلا کار نمیکنه باید دستی بروز کنید

**Comment by madar54** [comment]
در مورد سوال اولت برای هر پنل باید از باد فادر یک ربات جدید درست کنی و آن را داخل پنل وارد کنی اگر تمام پنل‌ها فقط دارای یک �ات باشند این مشکل پیش می‌آید پس در داخل ربات بادفادر برای هر پنل یک ربات جدید بساز و آن را وارد کن آیدی تلگرام یا آی‌دی چت مهم نیست برای همه یکی باشد اشکال ندارد

**Comment by Miladr9800** [comment]
ممنونم از پاسخ گویی ولی از فایل بکاب که میفرسته تا حالا استفاده کردی؟
همشون بکاب یک پنل هستن
