### ISSUE TITLE
Can you add a function to limit speed and limit the number of devices?

### ISSUE THREAD

**Issue by AK47-Plusone** [MHSanaei/3x-ui#1975]
Can you add a function to limit speed and limit the number of devices?

**Comment by RoninAngle1** [comment]
Hi , the number of devices is available, It is called "IP limit" in users section in inbound tab

**Comment by me21** [comment]
Could you please share a screenshot? I can't find it in v2.2.6 of the panel.
The command line script requires fail2ban to be installed, right? Is it hidden from the GUI when fail2ban is not present?

**Comment by me21** [comment]
@AK47-Plusone it seems there is no field to set the IP limit in the GUI - should I open a separate issue for that?

**Comment by myxeni64b** [comment]
Hi
Try this -> https://github.com/myxeni64b/xui-bw-guard
