### ISSUE TITLE
Sub domain

### ISSUE THREAD

**Issue by Sysop0098** [MHSanaei/3x-ui#1978]
سلام 
من یه دامنه.ir دارم رو کلودفلر 
با ای پی مستقیم بدون مشکل به پنل وصل میشم
ولی همین ای پی پشت ساب دامنه با پروکسی خاموش به پنل وصل نمیشه
با پروکسی روشن وصل میشه
با دامنه خارجی.com بدون مشکل بدون پروکسی وصل میشم 
خیلی کلنجار رفتم نشد
تمام رولهای پنل رو چک کردم نشد ک نشد.

**Comment by Miladr9800** [comment]
تنظیمات پنل-پیکربندی-نام دامنه رو اضافه کنید (با حروف کوچک)

**Comment by Sysop0098** [comment]
> تنظیمات پنل-پیکربندی-نام دامنه رو اضافه کنید (با حروف کوچک)

متاسفانه نشد
اقای صنایی ربطی به دامنه های ir نداره ممکنه بلاک باشه 
تو پنل چیزیو مسدود نکردم نه دامنه نه ای پی

**Comment by madar54** [comment]
من این مشکلو داشتم البته نه با دامنه آی آر احتمالاً جدیداً دامنه رو فیلتر می‌کنند تا آی‌پیو برای همینه که به این مشکل برخوردی دامنت فیلتر شده
