### ISSUE TITLE
قطع شدن ارتباط کانفیگ بعد از گذشت مدت زمان نامعلوم

### ISSUE THREAD

**Issue by iranandroid** [MHSanaei/3x-ui#1979]
سلام و وقت بخیر
من ی سرور با ip تمیز دارم و روش پنل رو نصب کردم
وقتی inbound تعریف میکنم و با کلاینت v2rayng بهش متصل میشم بعد از گذشت چند ثانیه اتصال قطع میشه و باید یکبار اتصال رو قطع و وصل کنم تا مجدد فعال بشه و باز بعد از چند ثانیه دوباره قطع میشه
تا حالا کسی چنین مشکلی داشته؟
راه حلی براش وجود داره؟
ممنون میشم اساتید راهنمایی کنن

**Comment by Arman-nsb** [comment]
سلام، دوست عزیز log خطاها رو از طریق پنل چک کن ببین علتش چیه.
