### ISSUE TITLE
مشاهده کلاینت ها یه اینباند با اسکرول کردن

### ISSUE THREAD

**Issue by mohsenrahmani145** [MHSanaei/3x-ui#1995]
سلام وقت بخیر خسته نباشید
خواستم یه پیشنهادی بدم برای اپدیت های بعدی x-ui
مشکلی که تمام x-ui ها دارند اینه که وقتی تعداد کلاینت های یه اینباند زیاد میشه به شدت کند میشه و روی + کنار اینباند میزنی با تاخیر کاربر هارو نشون میده
به نظرم واسه رفع این مشکل روی + زدیم تمام کلاینت هارو لود نکنه مثلا 10 تا لود کنه با اسکرول کردن به سمت پایین 10 تا دیگه لود کنه مثلا کامنت های اینستاگرام

**Comment by Blaster-777** [comment]
اره واقعا یکی از رو مخ ترین مشکلات پنل همین هست. 50 تا کلاینت بیشتر بشه اصلا دیگه نمیشه باهاش کار کرد

**Comment by MHSanaei** [comment]
این ویژگی 5ماه پیش اضافه شد
داخل تنظیمات به اسم Pagination Size 
موفق باشید
