### ISSUE TITLE
مشکل در محاسبه حجم اپلود و دانلود ، با حجم ورود و خروجی و حجم واقعی متفاوت هست .

### ISSUE THREAD

**Issue by hadiearn** [MHSanaei/3x-ui#2001]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام
مشکلی که هست حجم دانلود و اپلود کاملا متفاوت با حجم ورود و خروجی هست و درست محاسبه نمیشه . 
و وقتی تانل میزنیم حجم دانلود و اپلود سرور ایران هم کاملا برابر حجم ورودی و خروجی سیستم حساب میشه .
تصویر رو مشاهده کنیدهر دو برای یک سرور و پنل هست  ..
مقایسه حجم دانلود با حجم خروجی سیستم . 
![Screenshot 2024-03-09 110123](https://github.com/MHSanaei/3x-ui/assets/162785310/41827e8a-fd79-46c8-88b6-02edf576a6a0)
![Screenshot 2024-03-09 110136](https://github.com/MHSanaei/3x-ui/assets/162785310/eb7e6e2f-ba02-4ff3-90c2-4fa66203f758)

### Version of 3x-ui

  3X-UI: [v2.2.1]

### x-ui log reports or xray log

  3X-UI: [v2.2.1]

**Comment by madar54** [comment]
این مقدار مصرف از زمانی است که سیستم تو ری استارت کردی اگر ری استارت نکنی درست نمایش داده می‌شود و اگر می‌خواهی دقیق‌تر ببینی باید به گزینه
![Uploading 1.PNG…]()

**Comment by madar54** [comment]
من هم متوجه این مشکل شده‌ام مقدار مصرفی در پنل ایکس یو آی با مقدار مصرفی در سرور مجازی دو مقدار متفاوت است لطفاً جناب سنایی بررسی فرمایند
