### ISSUE TITLE
پاک کردن تعدادی کانفیگ به صورت یک‌جا

### ISSUE THREAD

**Issue by AerEbi** [MHSanaei/3x-ui#2002]
سلام؛

خواستم مثل همیشه تعدادی ( Add Bulk ) بسازم. این سری رنج عددی اشتباه شد و حدود 1000 تا کانفیگ ساخته شد. وقتی می‌خوام اون پروتکل رو باز کنم تا کانفیگا رو پاک کنم خطا میده و باز نمی‌شه.
راهی هست بشه جور دیگه کانفیگا رو پاک کرد؟

وقتی روی + اون پروتکل می‌زنم پیامی که می‌ده اینه:
![Screenshot 2024-03-09 125613](https://github.com/MHSanaei/3x-ui/assets/108983260/23a5b03e-b4d4-47e8-b993-84b201024d37)

ممنون می‌شم راهنمایی کنید.

**Comment by AerEbi** [comment]
با فایرفاکس اینباند رو باز کردم ولی تو سیستم رم خیلی مصرف می‌کنه.
راهی هست بشه تعدادی پاک کرد ( رنج بدم )؟ چون کانفیگا رو مشخص شده ساختم. نمونه: a101-a500
از طریق فایل بکاپ می‌شه پاک کرد؟ یا روش دیگه‌ای براش باشه؟

**Comment by madar54** [comment]
اگه آیدی‌هات متفاوت است مثلاً آیدی ۱ تا ۱۰۰۰ ساختی اون رو کاریش نمیشه کرد باید دستی پاک کنی ولی اگه همه رو توی یک این باند ساختی مثلاً با پورت ۲۰۵۰ شما هزار تا کانفیگ ساختی در اون صورت می‌تونی کل این باند رو پاک کنی....

یا اگه بکاپ قبل از این جریانو داری تو تلگرامت اون بکاپو دانلود کن مثلاً بکاپ دو هفته پیش اون رو  بریز رو پنلت
