### ISSUE TITLE
غیر فعال نشدن کاربر بعد از پایان حجم یا زمان

### ISSUE THREAD

**Issue by rafatidev** [MHSanaei/3x-ui#2003]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام
بعد از پایان حجم و زمان کلاینت کاربر همچنان Enable  است در حالی که Depleted شده و زمان یا حجمش تموم شده
<img width="1344" alt="Screenshot 2024-03-09 151255" src="https://github.com/MHSanaei/3x-ui/assets/128087177/c5543f06-02a7-4e16-92ba-1694a2c1cb07">

### Version of 3x-ui

<details>

```console
v2.2.1
```

</details>

### x-ui log reports or xray log

<details>

```console
```

</details>

**Comment by rahman8521** [comment]
خیلی وقته این مشکل وجود داره . انگار نمیخواد فیکس بشه !!!

**Comment by rafatidev** [comment]
مشکلش با ریست شدن پنل حل میشه
برای تست میتونی یه کانفیگ مثلا 10 مگ درست کنی بعد با دانلود منیجر یه فایل 1 گیگ دانلود کنی میبینی که همینجوری به دانلود ادامه میده
ولی وسط دانلود یکبار پنل رو ریست کنی کلا کانکشنت قطع میشه
باید وقتی زمان یا حجم تموم میشه پنل ریست بشه که البته اینم خودش چالشه چون اینجور اونی که تیو اینستا داشت ویدئو میدید قطع میشه و باید ویدئو رو از اول ببینه
