### ISSUE TITLE
cant use warp

### ISSUE THREAD

**Issue by pouriasharifzad** [MHSanaei/3x-ui#2007]
سلام وبسایت sofascore.com رو با هر آ پی تست میکنم بلاک هست
میخوام از وارپ استفاده کنم اما هر جوری رول اد میکنم توی تنظیمات روتینگ عمل نمیکنه
این وبسایت از سی دی ان کلادفلر استفاده میکنه نمیدونم ربطی داشته باشه یا نه

**Comment by Shm9220** [comment]
اره منم اد کردم به وارپ نیاورد . فقط وقتی کل ترافیک از وارپ رد میشه میاره

**Comment by mehrdadghadam** [comment]
برای منم همینه
