### ISSUE TITLE
درخواست اضافه کردن قابلیت مسدود کردن محتوای پورنوگرافی به پنل وی پی ان در یک اینباند جداگانه را دارم ممنون میشم راهنمایی کنید

### ISSUE THREAD

**Issue by sajjadvn** [MHSanaei/3x-ui#2009]

**Comment by Dwnill** [comment]
تو بخش تنظیمات ایکس ری صفحه اول مسدود سازی محتوای بزرگ سال اصلا هست کافیه فعالش کنی

**Comment by Dwnill** [comment]
![Screenshot 2024-03-12 140015](https://github.com/MHSanaei/3x-ui/assets/40546776/2b0d0e37-ef40-4628-95fe-f9b1629fac18)

خب میتونه بعدش بیاد ادیت کنه کدوم اینباند شاملش بشه👌
