### ISSUE TITLE
3x-ui v2.2.5 mux issue

### ISSUE THREAD

**Issue by HamedX2Z** [MHSanaei/3x-ui#2015]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

در قسمت outbounds وقتی mux رو فعال میکنم بعد از سیو کردن دوباره به حالت خاموش بر میگرده و باید بازم با اینکه میزنه خاموشه اون رو خاموش روشن کنم تا کانفیگ ها دوباره فعال بشن

### Version of 3x-ui

<details>

```console
v2.2.5
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
نسخه اخر رو مجدد نصب کنید مشکل رفع شد

**Comment by HamedX2Z** [comment]
با سلام و عرض خسته نباشید به نسخه اخر اپدیت شد ولی مشکل همچنان وجود داره

**Comment by HamedX2Z** [comment]
> نسخه اخر رو مجدد نصب کنید مشکل رفع شد


با سلام و عرض خسته نباشید به نسخه اخر اپدیت شد ولی مشکل همچنان وجود داره

**Comment by MHSanaei** [comment]
Ctrl+f5

**Comment by HamedX2Z** [comment]
> Ctrl+f5

یه بار دیگه هم اپدیت کردم و عرضتون رو انجام دادم ولی همچنان بعد سیو کردن و ریست کردن پنل تنظیمات mux به حالت خاموش برمیگرده

**Comment by MHSanaei** [comment]
مشکل از سمت ما حل شده سمت خودتون رو بررسی کنید
موفق باشید
