### ISSUE TITLE
کار نکردن هیچ کدوم از کانفیگ ها با همراه اول

### ISSUE THREAD

**Issue by OnlyRad** [MHSanaei/3x-ui#2016]
خیلی ساده بخوام توضیح بدم اینجوری میشه که؛
کانفیگی وقتی ساخته میشه با تمامی اپراتورها بدون مشکل کار میکنه به جز همراه اول که خیلی مشکل رو مخی هستش اگر درموردش چیزی میدونید لطفا کمک کنید خیلی نیازمه…

**Comment by HamedX2Z** [comment]
از فرگمنت استفاده کن احتمالا جواب بگیری اینطوری

**Comment by OnlyRad** [comment]
پورت پنل رو عوض کردم برطرف شد
