### ISSUE TITLE
کار نکردن آپدیت سابسکریبشن در آپدیت 2.2.5

### ISSUE THREAD

**Issue by abaqqal** [MHSanaei/3x-ui#2017]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

آپدیتی که الان داده شده رو نصب کردم ولی سابسکریبشن از کار افتاد.

### Version of 3x-ui

<details>

```console
# 2.2.5
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
به دلیل تغییرات زیاد و موارد جدید اضافه شده
باید یکبار اینباندهارو اپدیت بزنید یعنی ادیت بزنید و سپس اپدیت مشکل خواهد شد موفق باشید
