### ISSUE TITLE
2.2.5 leastload balancing crash panel

### ISSUE THREAD

**Issue by jahlib** [MHSanaei/3x-ui#2018]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

updating to 2.2.5 and set leastload get an error and panel restart looping.

### Version of 3x-ui

2.2.5

### x-ui log reports or xray log

<details>

```console
Mar 12 02:04:33  /usr/local/x-ui/x-ui[493]: WARNING - Access log is set to 'none', check your Xray Configs
Mar 12 02:04:43 /usr/local/x-ui/x-ui[493]: WARNING - Access log is set to 'none', check your Xray Configs
Mar 12 02:04:48 /usr/local/x-ui/x-ui[493]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
Mar 12 02:04:48 /usr/local/x-ui/x-ui[493]: WARNING - XRAY: core: Xray 1.8.9 started
Mar 12 02:04:51 /usr/local/x-ui/x-ui[493]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
Mar 12 02:04:51 /usr/local/x-ui/x-ui[493]: WARNING - XRAY: core: Xray 1.8.9 started
Mar 12 02:04:53 /usr/local/x-ui/x-ui[493]: WARNING - Access log is set to 'none', check your Xray Configs
Mar 12 02:04:54 /usr/local/x-ui/x-ui[493]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
Mar 12 02:04:54 /usr/local/x-ui/x-ui[493]: WARNING - XRAY: core: Xray 1.8.9 started
Mar 12 02:05:03 /usr/local/x-ui/x-ui[493]: WARNING - Access log is set to 'none', check your Xray Configs
```

</details>

**Comment by MHSanaei** [comment]
your error is about your access log 
WARNING - Access log is set to 'none', check your Xray Configs
set a path for access log

**Comment by jahlib** [comment]
yes, it is, but i have set a path for access log. But the issue is about leastLoad balancing. After enabling clients disconnecting and "xray state: Not Running"

**Comment by jahlib** [comment]
changing back to Random or RoundRobin fix clients connection

**Comment by MHSanaei** [comment]
Please check the error when xray stopped

**Comment by jahlib** [comment]
just this error in popup - github.com/xtls/xray-core/app/dispatcher/default.go:239 +0x40b

and logs:
Mar 13 00:25:36 server /usr/local/x-ui/x-ui[14987]: WARNING - X-UI: get xray traffic failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:62789: connect: connection refused"
Mar 13 00:25:41 server /usr/local/x-ui/x-ui[14987]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
Mar 13 00:26:01 server /usr/local/x-ui/x-ui[14987]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
Mar 13 00:26:04 server /usr/local/x-ui/x-ui[14987]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
Mar 13 00:26:06 server /usr/local/x-ui/x-ui[14987]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
Mar 13 00:26:16 server /usr/local/x-ui/x-ui[14987]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
Mar 13 00:26:18 server /usr/local/x-ui/x-ui[14987]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
Mar 13 00:26:23 server /usr/local/x-ui/x-ui[14987]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
Mar 13 00:26:25 server /usr/local/x-ui/x-ui[14987]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
Mar 13 00:26:27 server /usr/local/x-ui/x-ui[14987]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
