### ISSUE TITLE
حجم

### ISSUE THREAD

**Issue by mojiw2fm** [MHSanaei/3x-ui#202]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام داداش خسته نباشی چرا حجم نمیندازه ورژن جدید؟؟

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
تست شد مشکلی نداره 
یوزرها خودتون رو چک کنید تکراری نداشته باشید 
لاگ هارو بررسی کنید اروری شبیه به این نداشته باشید 

AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email

**Comment by mojiw2fm** [comment]
دقیقا یه اروری شبیه به همین دارم ، حل مشکل کجاست تشکر
