### ISSUE TITLE
Subscription Json link not working

### ISSUE THREAD

**Issue by HamedX2Z** [MHSanaei/3x-ui#2020]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

با سلام لینک Subscription Json بعد از اپدیت 2.2.5 از کار افتاده و کانکت نمیشه راه حلی براش هست؟

### Version of 3x-ui

<details>

```console
v2.2.5
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by HamedX2Z** [comment]
> آره دقیقا منم همین مشکل رو دارم. سابسکریشن کار میکنه ولی برای json از کار افتاد.

اره برا منم همینطوری شده اینباند هارو هم اپدیت کردم 1 بار ولی بازم کار نمیکنه

**Comment by abaqqal** [comment]
> > آره دقیقا منم همین مشکل رو دارم. سابسکریشن کار میکنه ولی برای json از کار افتاد.
> 
> اره برا منم همینطوری شده اینباند هارو هم اپدیت کردم 1 بار ولی بازم کار نمیکنه

ip limite برای شما کار میکنه؟

**Comment by HamedX2Z** [comment]
> > > آره دقیقا منم همین مشکل رو دارم. سابسکریشن کار میکنه ولی برای json از کار افتاد.
> > 
> > 
> > اره برا منم همینطوری شده اینباند هارو هم اپدیت کردم 1 بار ولی بازم کار نمیکنه
> 
> ip limite برای شما کار میکنه؟

اره اون مشکلی نداره

**Comment by abaqqal** [comment]
> > > > آره دقیقا منم همین مشکل رو دارم. سابسکریشن کار میکنه ولی برای json از کار افتاد.
> > > 
> > > 
> > > اره برا منم همینطوری شده اینباند هارو هم اپدیت کردم 1 بار ولی بازم کار نمیکنه
> > 
> > 
> > ip limite برای شما کار میکنه؟
> 
> اره اون مشکلی نداره

از cdn استفاده نکردین؟
