### ISSUE TITLE
کار نکردن ip limit

### ISSUE THREAD

**Issue by abaqqal** [MHSanaei/3x-ui#2021]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

وقتی از cdn کلاد فیلر استفاده میشه ip limit درست عمل نمیکنه.
access log ست شده
fail2ban هم نصب شده

### Version of 3x-ui

<details>

```console
# 2.2.5
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by abaqqal** [comment]
> ایپی لیمیت تنهای برای کانکشن های مستقیم به درستی عمل میکنه و در حالت هایی که با تانل یا CDN استفاده میشود کاربردی نمیباشد.

سلام ولی قبلا تو ورژن های قبلی کار میکرد ولی تو این ورژن ها دیگه جواب نمیده.
کاری نمیشه کرد؟

**Comment by Kup1ng** [comment]
چطور ممکنه با cdn ایپی لیمیت کار کنه وقتی کل کاربر های تو دارن با اون ایپی تمیز کلودفلر خاص به سرورت وصل میشن
