### ISSUE TITLE
 ورژن 2.2.5 IP LOG اپدیت جدید مشکل

### ISSUE THREAD

**Issue by qar4al** [MHSanaei/3x-ui#2024]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

روی چند تا سرور بعد از اپدیت تست کردم لاگ IP نمایش داده نمیشه 

![image](https://github.com/MHSanaei/3x-ui/assets/63839880/8916f23b-bcc2-4fcb-95cf-4bbfbc18302f)
![image](https://github.com/MHSanaei/3x-ui/assets/63839880/ed89b57d-0f49-45bc-b339-750c0c7cadd1)

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Kup1ng** [comment]
داخل بخش xray setting برو و log access را بزار روی true

**Comment by qar4al** [comment]
![image](https://github.com/MHSanaei/3x-ui/assets/63839880/94dc0740-0351-4d2e-8966-9ed135958726)
![image](https://github.com/MHSanaei/3x-ui/assets/63839880/4dcaf123-957c-4cd2-aeae-817648174bad)
این تنظیمات درسته ولی بازم نمیاره

**Comment by RezgoolGit** [comment]
https://github.com/MHSanaei/3x-ui#ip-limit

نصب fail2ban از طریق فرمان x-ui
To make IP Limit work properly, you need to install fail2ban and its required files by following these steps:

Use the x-ui command inside the shell.
Select IP Limit Management.
Choose the appropriate options based on your needs.
make sure you have ./access.log on your Xray Configuration after v2.1.3 we have an option for it

  "log": {
    "access": "./access.log",
    "dnsLog": false,
    "loglevel": "warning"
  },

**Comment by qar4al** [comment]
اصلا از ip limit استفاده نمیکنم فقط مشکل نمایش ip log داره هر کاری کردم هم درست نشد
