### ISSUE TITLE
get config & fragment in api

### ISSUE THREAD

**Issue by mostafa9112** [MHSanaei/3x-ui#2027]
سلام کاش یه قابلیت اضافه بشه که از طریق api بشه با ارسال ایمیل یا آیدی کلاینت بصورت مستقیم کانفیگ و جیسون فرگمنت رو دریافت کرد
دیگه پنل هیچی کم ندار
خسته هم نباشید

**Comment by Dwnill** [comment]
از بخش تنظیمات   پنل > قسمت sub > قسمت json  میتونی فرگمنت رو تنظیم کنی به کاربر لینک ساب جیسون بدی بجا ساب معمولی روی اپ های v2ray ,streisand ساپورت میکنه .

**Comment by mostafa9112** [comment]
میدونم اما میخوام کانفیگ رو از خود پنل بگیرم تو بات به کاربر نشون بدم و کاربر نباید ساب پنل رو ببینه و ساب ربات رو فقط میبینه
