### ISSUE TITLE
"Xray Configs" tab shows just a white page after upgrading to v2.2.5

### ISSUE THREAD

**Issue by Joviall** [MHSanaei/3x-ui#2028]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello and thank you for this nifty tool, it's a life savor.
I recently upgraded two of my servers to v2.2.5, did a full restart on both servers, still "Xray Configs" tab on both panels shows just a blank white page. Just to note, after the upgrade I didn't change any of my configurations and used my previous config on both servers.
thanks in advance

### Version of 3x-ui

2.2.5

### x-ui log reports or xray log

2024/03/12 07:47:37 WARNING - XRAY: core: Xray 1.8.9 started
2024/03/12 07:47:36 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/12 07:47:36 INFO - X-UI: web server run https on[::]:XXX

**Comment by Kup1ng** [comment]
ctrl + F5 بزن درست میشه

**Comment by Joviall** [comment]
Tried that already, didn't work. That's why I posted the issue here
Thanks for the reply btw

**Comment by MHSanaei** [comment]
i just fix it reinstall the panel 
sorry about that

**Comment by Joviall** [comment]
Can I preserve my settings and configurations while doing a reinstall?
Or should I have to reinstall from scratch to solve the issue?
Thanks again
