### ISSUE TITLE
record not found while updating user traffic

### ISSUE THREAD

**Issue by sepano** [MHSanaei/3x-ui#203]
پنل ترافیک مربوط به یوزر ها رو صفر نشون میده و لاگ رو که نگاه می کنم تعداد زیادی رکورد مشابه این توی لاگ هست
Apr 11 13:22:17 sanaei x-ui[115]: 2023/04/11 13:22:17 WARNING - record not found vcen.love@xray.com
Apr 11 13:22:17 sanaei x-ui[115]: 2023/04/11 13:22:17 WARNING - record not found Dxo8.love@xray.com
Apr 11 13:22:17 sanaei x-ui[115]: 2023/04/11 13:22:17 WARNING - record not found rEfq.love@xray.com
Apr 11 13:22:17 sanaei x-ui[115]: 2023/04/11 13:22:17 WARNING - record not found qIpm.love@xray.com
Apr 11 13:22:17 sanaei x-ui[115]: 2023/04/11 13:22:17 WARNING - record not found xQdN.love@xray.com
Apr 11 13:22:17 sanaei x-ui[115]: 2023/04/11 13:22:17 WARNING - record not found iun8.love@xray.com
Apr 11 13:22:17 sanaei x-ui[115]: 2023/04/11 13:22:17 WARNING - record not found U3000_Mohamad
Apr 11 13:22:17 sanaei x-ui[115]: 2023/04/11 13:22:17 WARNING - record not found OfaR.love@xray.com
Apr 11 13:22:17 sanaei x-ui[115]: 2023/04/11 13:22:17 WARNING - record not found aHgp.love@xray.com
Apr 11 13:22:17 sanaei x-ui[115]: 2023/04/11 13:22:17 WARNING - record not found O75k.love@xray.com
Apr 11 13:22:17 sanaei x-ui[115]: 2023/04/11 13:22:17 WARNING - record not found Vw9S.love@xray.com
Apr 11 13:22:17 sanaei x-ui[115]: 2023/04/11 13:22:17 WARNING - record not found gnre.love@xray.com
Apr 11 13:22:17 sanaei x-ui[115]: 2023/04/11 13:22:17 WARNING - record not found nc2n.love@xray.com

AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email

**Comment by MHSanaei** [comment]
@sepano @enlink110 
back to version 1.2.0 please and tell me the result 
v1.2.0 is the latest now

**Comment by enlink110** [comment]
Dear @MHSanaei 
Thank you 
i downgraded to 1.2.0 and still the same issue, i force to remove all the users in the screenshot (still have an error on logs)
and finally panel starts to count traffic

**Comment by sepano** [comment]
من ورژن رو به ۱.۲.۰ برگردوندم 
ولی چیزی تغییر نکرد

**Comment by MHSanaei** [comment]
تمام یوزر های یکه داخل لاگ ارور record not found دارند رو حذف کنید 2باره بسازید

**Comment by enlink110** [comment]
Thanks bro

**Comment by AghaFarokh** [comment]
آیا میشه بدون حذف و مجدد ساختنشون درست کرد این مشکلو ؟
اصلا از کجا شروع میشه این مشکل ؟ چی میشه که اینجوری میشه ؟
من نمیتونم این همه یوزرو پاک کنم دوباره بسازم
من کلا با Api میسازم یوزر هارو 
تازه دیدم این مشکلو
