### ISSUE TITLE
در ورژن 2.2.5 لینک ساب از کار میوفته

### ISSUE THREAD

**Issue by mehrdadrzy** [MHSanaei/3x-ui#2031]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

درود ، بعد از آپدیت از نسخه 2.2.1 به 2.2.5 تمامی لینک های ساب از دسترس خارج میشه و امکان استفاده نیست و بعد از دانگرید درست میشه مجددا

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
به خاطر تغییراتی هست که داشتیم باید اینباند هارو اپدیت کنید یعنی اینباند رو ادیت بزنید و روی دکمه اپدیت رو کلیک کنید
