### ISSUE TITLE
مشکل در ساخت کاربر

### ISSUE THREAD

**Issue by gechindir** [MHSanaei/3x-ui#2036]
سلام

از دوستان کسی میدونه چطوری میشه این ارور رو رفع کرد؟
Something went wrong! Failed: sql: Scan error on column index 0, name "JSON_EXTRACT(client.value, '$.email')": converting NULL to string is unsupported

**Comment by DoctorGuidance** [comment]
سلام
یکی از کانفیگ هایی که ساخته شده احتمالا مشکل داره. اونو باید حذف کنی یجوری.

**Comment by DoctorGuidance** [comment]
با نرم افزار database.net pro باید بکاپت بندازی توش قسمت inbounds کلیک راست کن بزن edit
![image](https://github.com/MHSanaei/3x-ui/assets/12963915/7f007482-2c71-4ad8-9d96-83e722d09103)
بعد سمت راست اون اینباندی که کلاینت مشکل دار توش هست قسمت settingsش رو دوتا کلیک کن کل متن داخلش که شامل کلاینت هات هست رو بردار توی notepad بذار یه کلاینت مشکل دار توش هست مثلا ایمیل نداره یا یه نقصی داره حذفش کن دوباره بذار جای قبلی سیو کن
![image](https://github.com/MHSanaei/3x-ui/assets/12963915/4eaaed75-b1c0-411c-a807-f2f3c177d953)

بعد بکاپه رو ریستور کن.
