### ISSUE TITLE
after update to v2.2.5 from 2.2.1 - xray dont start

### ISSUE THREAD

**Issue by alexdatur** [MHSanaei/3x-ui#2038]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

after update to [v2.2.5](https://github.com/MHSanaei/3x-ui/releases/tag/v2.2.5) - xray dont start - Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: Failed to build TLS config. > infra/conf: failed to parse certificate > open /public.key: no such file or directory

### Version of 3x-ui

<details>

```console
# 2.2.5
```

</details>

### x-ui log reports or xray log

<details>

```console
# 2024/03/12 18:14:58 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/12 18:14:56 WARNING - X-UI: Access log is set to 'none', check your Xray Configs
2024/03/12 18:14:56 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/12 18:14:54 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/12 18:14:52 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/12 18:14:50 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/12 18:14:48 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/12 18:14:46 WARNING - X-UI: Access log is set to 'none', check your Xray Configs
2024/03/12 18:14:46 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/12 18:14:44 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/12 18:14:42 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/12 18:14:40 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/12 18:14:38 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/12 18:14:36 WARNING - X-UI: Access log is set to 'none', check your Xray Configs
2024/03/12 18:14:36 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/12 18:14:34 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/12 18:14:32 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/12 18:14:30 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/12 18:14:28 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/12 18:14:26 WARNING - X-UI: Access log is set to 'none', check your Xray Configs
2024/03/12 18:14:26 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
```

</details>

**Comment by alexdatur** [comment]
An error occurred while running Xray Логи

Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: Failed to build TLS config. > infra/conf: failed to parse certificate > open /public.key: no such file or directory


Pease, help!

**Comment by alexdatur** [comment]
I change access log but it not helps. Still - 
An error occurred while running Xray Логи

Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: Failed to build TLS config. > infra/conf: failed to parse certificate > open /public.key: no such file or directory

Cant understand for what certificate it asks. i changed noting just repull latest container.

**Comment by MHSanaei** [comment]
/public.key: no such file or directory

**Comment by alexdatur** [comment]
But i didnt change enything in config, just upgrade. Cant find for what certificate it asks.

**Comment by MHSanaei** [comment]
just get a new one with x-ui terminal and replace it with your old path

**Comment by alexdatur** [comment]
> just get a new one with x-ui terminal and replace it with your old path

how i can do whis?
