### ISSUE TITLE
مشکل سرعت و پینگ بعد از آپدیت

### ISSUE THREAD

**Issue by Alireza78na** [MHSanaei/3x-ui#2039]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

من نسخه ی 2.2.5 رو نصب کردم.
متاسفانه کلا کیفیت اتصال ضعیف شده ، سرعت و پینگ هی بالا و پایین میشه
با برگشت به نسخه ی قبل مشکل حل شد.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by xpersian** [comment]
حتی تو این نسخه 

> ### Welcome
> * [x]  Yes, I'm using the latest major release. Only such installations are supported.
> * [x]  Yes, I'm using the supported system. Only such systems are supported.
> * [x]  Yes, I have read all WIKI document,nothing can help me in my problem.
> * [x]  Yes, I've searched similar issues on GitHub and didn't find any.
> * [x]  Yes, I've included all information below (version, config, log, etc).
> 
> ### Description of the problem,screencshot would be good
> من نسخه ی 2.2.5 رو نصب کردم. متاسفانه کلا کیفیت اتصال ضعیف شده ، سرعت و پینگ هی بالا و پایین میشه با برگشت به نسخه ی قبل مشکل حل شد.
> 
> ### Version of 3x-ui
> ```
> # Paste here
> ```
> 
> ### x-ui log reports or xray log
> ```
> # paste log here
> ```

حتی تو این نسخه لینک سابسکریپشن هم کار نمیکنه و کانفیگ رو دریافت نمیکنه

**Comment by javad8780** [comment]
دقیقا بنده هم همین مشکل رو دارم کانفیگ ها رو نمیشه دریافت کرد 
قسمت بات تلگرام هم که از چندتا اپدیت قبل کلن از کار افتاده

> حتی تو این نسخه
> 
> > ### Welcome
> > 
> > * [x]   Yes, I'm using the latest major release. Only such installations are supported.
> > * [x]   Yes, I'm using the supported system. Only such systems are supported.
> > * [x]   Yes, I have read all WIKI document,nothing can help me in my problem.
> > * [x]   Yes, I've searched similar issues on GitHub and didn't find any.
> > * [x]   Yes, I've included all information below (version, config, log, etc).
> > 
> > ### Description of the problem,screencshot would be good
> > من نسخه ی 2.2.5 رو نصب کردم. متاسفانه کلا کیفیت اتصال ضعیف شده ، سرعت و پینگ هی بالا و پایین میشه با برگشت به نسخه ی قبل مشکل حل شد.
> > ### Version of 3x-ui
> > ```
> > # Paste here
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### x-ui log reports or xray log
> > ```
> > # paste log here
> > ```
> 
> حتی تو این نسخه لینک سابسکریپشن هم کار نمیکنه و کانفیگ رو دریافت نمیکنه

**Comment by Alireza78na** [comment]
> دقیقا بنده هم همین مشکل رو دارم کانفیگ ها رو نمیشه دریافت کرد قسمت بات تلگرام هم که از چندتا اپدیت قبل کلن از کار افتاده
> 
> > حتی تو این نسخه
> > > ### Welcome
> > > 
> > > * [x]    Yes, I'm using the latest major release. Only such installations are supported.
> > > * [x]    Yes, I'm using the supported system. Only such systems are supported.
> > > * [x]    Yes, I have read all WIKI document,nothing can help me in my problem.
> > > * [x]    Yes, I've searched similar issues on GitHub and didn't find any.
> > > * [x]    Yes, I've included all information below (version, config, log, etc).
> > > 
> > > ### Description of the problem,screencshot would be good
> > > من نسخه ی 2.2.5 رو نصب کردم. متاسفانه کلا کیفیت اتصال ضعیف شده ، سرعت و پینگ هی بالا و پایین میشه با برگشت به نسخه ی قبل مشکل حل شد.
> > > ### Version of 3x-ui
> > > ```
> > > # Paste here
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### x-ui log reports or xray log
> > > ```
> > > # paste log here
> > > ```
> > 
> > 
> > حتی تو این نسخه لینک سابسکریپشن هم کار نمیکنه و کانفیگ رو دریافت نمیکنه

واسه حل این مشکل ، قبل تر گفتن که بعد از آپدیت یکبار Inbound رو ویرایش کنید و ذخیره کنید ، مشکل حل میشه.
تست کردم ،سابسکریپشن  اوکی شد

**Comment by javad8780** [comment]
> > دقیقا بنده هم همین مشکل رو دارم کانفیگ ها رو نمیشه دریافت کرد قسمت بات تلگرام هم که از چندتا اپدیت قبل کلن از کار افتاده
> > > حتی تو این نسخه
> > > > ### Welcome
> > > > 
> > > > * [x]     Yes, I'm using the latest major release. Only such installations are supported.
> > > > * [x]     Yes, I'm using the supported system. Only such systems are supported.
> > > > * [x]     Yes, I have read all WIKI document,nothing can help me in my problem.
> > > > * [x]     Yes, I've searched similar issues on GitHub and didn't find any.
> > > > * [x]     Yes, I've included all information below (version, config, log, etc).
> > > > 
> > > > ### Description of the problem,screencshot would be good
> > > > من نسخه ی 2.2.5 رو نصب کردم. متاسفانه کلا کیفیت اتصال ضعیف شده ، سرعت و پینگ هی بالا و پایین میشه با برگشت به نسخه ی قبل مشکل حل شد.
> > > > ### Version of 3x-ui
> > > > ```
> > > > # Paste here
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ### x-ui log reports or xray log
> > > > ```
> > > > # paste log here
> > > > ```
> > > 
> > > 
> > > حتی تو این نسخه لینک سابسکریپشن هم کار نمیکنه و کانفیگ رو دریافت نمیکنه
> 
> واسه حل این مشکل ، قبل تر گفتن که بعد از آپدیت یکبار Inbound رو ویرایش کنید و ذخیره کنید ، مشکل حل میشه. تست کردم ،سابسکریپشن اوکی شد

بله تست کردم اوکی شده

**Comment by Sasha21332133** [comment]
میشه بفرمایید چه تغییری توی اینباند بایستی ایجاد کنیم و بعد ذخیره کنیم تا مشکل ساب حل شه؟

**Comment by Sasha21332133** [comment]
> > دقیقا بنده هم همین مشکل رو دارم کانفیگ ها رو نمیشه دریافت کرد قسمت بات تلگرام هم که از چندتا اپدیت قبل کلن از کار افتاده
> > > حتی تو این نسخه
> > > > ### Welcome
> > > > 
> > > > * [x]     Yes, I'm using the latest major release. Only such installations are supported.
> > > > * [x]     Yes, I'm using the supported system. Only such systems are supported.
> > > > * [x]     Yes, I have read all WIKI document,nothing can help me in my problem.
> > > > * [x]     Yes, I've searched similar issues on GitHub and didn't find any.
> > > > * [x]     Yes, I've included all information below (version, config, log, etc).
> > > > 
> > > > ### Description of the problem,screencshot would be good
> > > > من نسخه ی 2.2.5 رو نصب کردم. متاسفانه کلا کیفیت اتصال ضعیف شده ، سرعت و پینگ هی بالا و پایین میشه با برگشت به نسخه ی قبل مشکل حل شد.
> > > > ### Version of 3x-ui
> > > > ```
> > > > # Paste here
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ### x-ui log reports or xray log
> > > > ```
> > > > # paste log here
> > > > ```
> > > 
> > > 
> > > حتی تو این نسخه لینک سابسکریپشن هم کار نمیکنه و کانفیگ رو دریافت نمیکنه
> 
> واسه حل این مشکل ، قبل تر گفتن که بعد از آپدیت یکبار Inbound رو ویرایش کنید و ذخیره کنید ، مشکل حل میشه. تست کردم ،سابسکریپشن اوکی شد

میشه بفرمایید چه تغییری توی اینباند بایستی ایجاد کنیم و بعد ذخیره کنیم تا مشکل ساب حل شه؟

**Comment by MHSanaei** [comment]
@Sasha21332133 
هیچ تغییری فقط باز کنید و اپدیت کنید

**Comment by Sasha21332133** [comment]
> @Sasha21332133 هیچ تغییری فقط باز کنید و اپدیت کنید

با درود خدمت شما جناب سنایی
وقتی تغییری ایجاد نشه چیزی برای ذخیره ندارد
من الان ارور http 500 می گیرم موقع آپدیت لینک اشتراک

**Comment by Sasha21332133** [comment]
![Screenshot_۲۰۲۴۰۳۱۲_۲۳۵۰۰۷_Samsung Internet](https://github.com/MHSanaei/3x-ui/assets/126942917/4889b3fc-8d29-468d-89c2-025a5fb88d83)

**Comment by MHSanaei** [comment]
@Sasha21332133 
روی اینباندتون ویرایش بزنید و دکمه اپدیت رو بزنید نه داخل تنظیمات

**Comment by Sasha21332133** [comment]
> @Sasha21332133 روی اینباندتون ویرایش بزنید و دکمه اپدیت رو بزنید نه داخل تنظیمات

بینهایت ممنون از راهنمایی تون 
حل شد ❤️
