### ISSUE TITLE
Automatically Remove Outbound Rule from Load Balancer on Deletion

### ISSUE THREAD

**Issue by jahlib** [MHSanaei/3x-ui#2042]
Currently, when an outbound rule is deleted, it remains associated with any load balancers it was previously added to. This can lead to inconsistencies and potential issues with the load balancer configuration.
I propose that when an outbound rule is deleted, it should also be automatically removed from any load balancers it was previously associated with.

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/commit/c74efa1d432146a0a9630f71320fe446c7b191eb

**Comment by jahlib** [comment]
panel 2.2.6 xray 1.8.9, when outbound was deleted it still stay in balancer selectors
