### ISSUE TITLE
مشکل لینک های سابسکریبشن

### ISSUE THREAD

**Issue by MatinDehghanian** [MHSanaei/3x-ui#2045]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

لینک های سابسکریبشن عادی یه صفحه سفیده ریسالتش

### Version of 3x-ui

<details>

```console
# v2.2.6
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

### راه حل موقتی

نسخه پنل رو به ورژن 2.2.1 برگردونید

`x-ui`
`3 (custom version)`
`2.2.1`

**Comment by roozbehalamdari** [comment]
درود ، لطفا مشکل لینک های ساب اسکریپشن های عادی رو حل کنید ، هر کاری میکنیم حل نمیشه ! ( خیلی از یوزر ها به مشکل خوردن !
همش این صفحه میاد : 
![image](https://github.com/MHSanaei/3x-ui/assets/131817501/19c83c46-0956-443c-9019-8f3187464601)

**Comment by rooshanak** [comment]
تمام کانفیگ ها رو بدون تغییر چیزی ادیت و ذخیره کنید

**Comment by roozbehalamdari** [comment]
این کار رو هم کردم نشد متاسفانه و یه چیز عجیب دیگه اینکه مثلا توی اینباند هام یوزر جدید میسازم کلا لینک ساب معمولیش جواب نمیده دیگه ، هرچی هم که میزارم یا تغییر میدم فایده نداره !

راستی من فقط دیشب دیدم اینطوریه اومدم از کلودفلیر یه ssl ۱۵ ساله گرفتم و پنلم الان با سرتیفیکیتی که توی ssh هست ست شده ولی توی تنظیمات ساب اسکریپشنم رو سرتیفیکیت کلودفلیر که گرفتم ست کردم ( این کارم برای این کردم چون هرکاری کردم نشد با ssh سرتیفیکیتش رو تمدید کنم یا جدید بگیرم )

**Comment by Dwnill** [comment]
دقیقا منم همین مشکل رو دارم

**Comment by roozbehalamdari** [comment]
> دقیقا منم همین مشکل رو دارم

لطفا اگر راهی پیدا مردی به منم بگو بدطور گیرم

**Comment by MatinDehghanian** [comment]
دوستان راه حل موقتی که براش پیدا کردم.
پنل رو به ورژن 2.2.1 برگردونین

`x-ui
3(custom version)
2.2.1`

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/2017#issuecomment-1989627680

**Comment by roozbehalamdari** [comment]
> [#2017 (comment)](https://github.com/MHSanaei/3x-ui/issues/2017#issuecomment-1989627680)

دمت گرم حل شد 😍♥️
