### ISSUE TITLE
How to disable log rotate\limit

### ISSUE THREAD

**Issue by ALCUler** [MHSanaei/3x-ui#2046]
Hello.

After v2.2.0(?), the access.log file is in rotation (or time-limited). How can I return the ability to write endlessly to access.log? No any settings to do this not available in panel.

Thanks in advance.

**Comment by xsenrain** [comment]
+1

**Comment by MHSanaei** [comment]
use https://github.com/alireza0/x-ui your access log won't be clear

**Comment by ALCUler** [comment]
Why not give the ability to customize the storage depth? Maybe I don’t fully understand the principled position on the issue?
