### ISSUE TITLE
Subscription ios issues

### ISSUE THREAD

**Issue by farhadsaberi** [MHSanaei/3x-ui#2048]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi,
The subscription link in the iOS app is having issues. Apps like Striesand don't import at all, but it's supported in the V2rayng and there are no issues. The subscription link is JSON-based and 64base.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by abaqqal** [comment]
سلام
عزیز مشکلی نداره. تنظیمات پنل خودتون رو بررسی کنین

**Comment by farhadsaberi** [comment]
چطوری ربطش به پنل داره؟ همون کانفیگ رو روی ساب غیر از پنل کار میکنه.
برنامه v2rayng هم کار میکنه. فقط روی ios کار نمیکنه.

**Comment by Leon1999Z** [comment]
IOS apps mostly accept HTTPS subscription
so you should add certificate via private & public key path in sub on panel setting
