### ISSUE TITLE
مشکل نمایش IP Log در ورژن 2.2.6

### ISSUE THREAD

**Issue by qar4al** [MHSanaei/3x-ui#2049]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

بعد از اپدیت به ورژن 2.2.5 و بعد به ورژن 2.2.6 مشکل نمایش IP LOG به وجود امده . حتی برای اطمینان روی سرور جدید نصب کردم باز مشکل پا برجا بود و تنظیمات LOG هم درست بود و توی گزارشگیری لاگ ها هیچ خطایی نبود. لطفا مشکل نمایش ip log  را بطرف نمایید 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by qar4al** [comment]
تنظیمات Xray برسی شده و درست هست برای مسدود کردن کاربر fail2ban رو نصب نکردم فقط مشکل مشاهده IP هست حتی رو سرور جدید

**Comment by MHSanaei** [comment]
باید iplimit فعال باشه که لیست ای پی هارو نمایش بده

**Comment by qar4al** [comment]
سپاس مشکل حل شد
