### ISSUE TITLE
کدام پروتوکل ها بیشتر کار میکنه؟!

### ISSUE THREAD

**Issue by vedved3007** [MHSanaei/3x-ui#205]
reality رو هیچکدام کار نمیکنه! :-(

**Comment by MHSanaei** [comment]
باید ای پی تمیز داشته باشید 
ذر حال حاضر روی این 3 مورد میتونید بزنید
vless tcp 
vless http
vless grpc

**Comment by vedved3007** [comment]
هم آیپی تمیز هست هم دامین ولی ریالیتی رو هیچ کدوم برام  کار نکرد
