### ISSUE TITLE
Subscription update

### ISSUE THREAD

**Issue by dev-ehsan-babaei** [MHSanaei/3x-ui#2051]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

After upgrading to version 2.2.6 subscription is not working and returns error 500. Although JSON subscription link works perfectly, the issue is only about /sub/ path not /json/

Also it apears that only subscriptions which contain multiple configs have this issue. For instance:

1 config subscription:
  both /sub/ and /json/ work good.

multiple config sub:
  /json/ works good but /sub/ returns error 500.

### Version of 3x-ui

<details>

```console
version 2.2.6
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Barnikle** [comment]
بعد آپدیت به نسخه ۲.۲.۶ این مشکل برای منم هست 
لطفا اگه میشه راهنمایی کنین

**Comment by MHSanaei** [comment]
click on your inbound and edit it then without any changes just press on update 
done

**Comment by dev-ehsan-babaei** [comment]
Worked perfectly! thanks.
