### ISSUE TITLE
عدم امکان ارسال کلید ها برای ساخت وایرگارد در  وب سرویس ( ناقص بودن وب سرویس )

### ISSUE THREAD

**Issue by iamirh7** [MHSanaei/3x-ui#2058]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

برای ساخت وایرگارد توسط api  و ارسال کلید ها به پنل ، مشکل دارم

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by newman222** [comment]
بله ما هم به همین مشکل خوردیم

**Comment by newman222** [comment]
any Update for this Issue ?
