### ISSUE TITLE
ارور سرتیفیکیت در پنل

### ISSUE THREAD

**Issue by Alireza78na** [MHSanaei/3x-ui#2059]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام
من به طور مداوم این ارور رو روی log ها میبینم :
x-ui[699]: 2024/03/14 08:32:27 http: TLS handshake error from 127.0.0.1:45776: remote error: tls: unknown certificate

درحالی که سرتیفیکیت من فقط برای پنل هست ( اینباند بدون Cert و sub  فعال نیست ) ، اما این ارور رو بعد از آپدیت به نسخه ی 2.2.5 و 2.2.6 دریافت میکنم و متاسفانه باعث میشه کانفیگ مرتب قطع شه و پینگ شدیدا بالا و پایین میشه ( چون فقط بعد از آپدیت اینجوری شده و از سالم بودن موارد دیگه اطمینان دارم )

سرتیفیکت رو هم یا Letsencrypt گرفتم و پنل هم بدون مشکل با TLS بالا میاد.

### Version of 3x-ui

version: 2.2.6 & 2.2.5

### x-ui log reports or xray log

Mar 14 08:04:12 D2 x-ui[699]: 2024/03/14 08:04:12 http: TLS handshake error from 127.0.0.1:47394: remote error: tls: unknown certificate
Mar 14 08:04:12 D2 x-ui[699]: 2024/03/14 08:04:12 http: TLS handshake error from 127.0.0.1:47408: remote error: tls: unknown certificate
Mar 14 08:04:12 D2 x-ui[699]: 2024/03/14 08:04:12 http: TLS handshake error from 127.0.0.1:47416: remote error: tls: unknown certificate
Mar 14 08:04:12 D2 x-ui[699]: 2024/03/14 08:04:12 http: TLS handshake error from 127.0.0.1:47430: remote error: tls: unknown certificate
Mar 14 08:04:14 D2 x-ui[699]: 2024/03/14 08:04:14 http: TLS handshake error from 127.0.0.1:47440: remote error: tls: unknown certificate

another Server:
Mar 14 07:58:30 Kids x-ui[706]: 2024/03/14 07:58:30 http: TLS handshake error from 216.218.206.67:16016: read tcp 65.109.215.199:443->216.218.206.67:16016: read: connection reset by peer
Mar 14 07:58:31 Kids x-ui[706]: 2024/03/14 07:58:31 http: TLS handshake error from 216.218.206.67:16024: read tcp 65.109.215.199:443->216.218.206.67:16024: read: connection reset by peer
Mar 14 07:58:31 Kids x-ui[706]: 2024/03/14 07:58:31 http: TLS handshake error from 216.218.206.67:16030: read tcp 65.109.215.199:443->216.218.206.67:16030: read: connection reset by peer
Mar 14 07:58:31 Kids x-ui[706]: 2024/03/14 07:58:31 http: TLS handshake error from 216.218.206.67:16038: read tcp 65.109.215.199:443->216.218.206.67:16038: read: connection reset by peer
Mar 14 07:58:32 Kids x-ui[706]: 2024/03/14 07:58:32 http: TLS handshake error from 216.218.206.67:16044: read tcp 65.109.215.199:443->216.218.206.67:16044: read: connection reset by peer
Mar 14 07:58:32 Kids x-ui[706]: 2024/03/14 07:58:32 http: TLS handshake error from 216.218.206.67:16054: tls: client offered only unsupported versions: [302 301]
Mar 14 07:58:32 Kids x-ui[706]: 2024/03/14 07:58:32 http: TLS handshake error from 216.218.206.67:16056: read tcp 65.109.215.199:443->216.218.206.67:16056: read: connection reset by peer
Mar 14 07:58:33 Kids x-ui[706]: 2024/03/14 07:58:33 http: TLS handshake error from 216.218.206.67:16064: read tcp 65.109.215.199:443->216.218.206.67:16064: read: connection reset by peer
Mar 14 07:58:33 Kids x-ui[706]: 2024/03/14 07:58:33 http: TLS handshake error from 216.218.206.67:16078: read tcp 65.109.215.199:443->216.218.206.67:16078: read: connection reset by peer
Mar 14 07:58:33 Kids x-ui[706]: 2024/03/14 07:58:33 http: TLS handshake error from 216.218.206.67:16082: read tcp 65.109.215.199:443->216.218.206.67:16082: read: connection reset by peer

**Comment by Alphfaa** [comment]
منم همین مشکل رو دارم
