### ISSUE TITLE
XTLS

### ISSUE THREAD

**Issue by hamed0mh** [MHSanaei/3x-ui#206]
زمانی که یوزری با XTLS ثبت میکنی ذخیره میکنه و کار هم میده ولی دوباره که روی همون یوزر میخوای ادیت کنی . XTLS و آدرس هاشو پاک میکنه 
.
 نمیدونم باگه یا یجایی اشتباه میکنم

**Comment by MHSanaei** [comment]
حل شد
 [xtls bug fix](https://github.com/MHSanaei/3x-ui/commit/54946e725e835a291f9c8e226788cd8a166e190b)
