### ISSUE TITLE
无法从Google play上下载应用

### ISSUE THREAD

**Issue by Iyiren** [MHSanaei/3x-ui#2065]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

我用界面搭建了两种方式代理，都无法从Google play上下载和更新应用，一直在等待中。清除过Google应用缓存，还是没用。代理访问外网是正常的。
<img width="1098" alt="461132af66a87fabeb1edf4dd7219b9" src="https://github.com/MHSanaei/3x-ui/assets/8311092/5b28f28d-e29c-4466-8c74-f10f93b2ee43">
<img width="914" alt="ca6eabb973916e62d4b7d7a039772ce" src="https://github.com/MHSanaei/3x-ui/assets/8311092/d377e330-9414-4bab-b1bb-656319ce416f">
![72718bc42b30e18bf76bfb90504c3cf](https://github.com/MHSanaei/3x-ui/assets/8311092/e41818b3-3233-4552-a3af-f1aa5d4d14bb)

### Version of 3x-ui

<details>

```console
The OS release is: debian

  3X-ui Panel Management Script
  0. Exit Script
————————————————
  1. Install
  2. Update
  3. Custom Version
  4. Uninstall
————————————————
  5. Reset Username & Password & Secret Token
  6. Reset Settings
  7. Change Port
  8. View Current Settings
————————————————
  9. Start
  10. Stop
  11. Restart
  12. Check Status
  13. Check Logs
————————————————
  14. Enable Autostart
  15. Disable Autostart
————————————————
  16. SSL Certificate Management
  17. Cloudflare SSL Certificate
  18. IP Limit Management
  19. WARP Management
  20. Firewall Management
————————————————
  21. Enable BBR
  22. Update Geo Files
  23. Speedtest by Ookla

Panel state: Running
Start automatically: Yes
xray state: Running

```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Moiudev** [comment]
换个 IP 试试。

**Comment by livingfree2023** [comment]
全局试试，或者把负责download的程序加入代理列表

**Comment by Iyiren** [comment]
> 全局试试，或者把负责download的程序加入代理列表，还有一种可能是你的google全家桶需要更新了

用的v2rayN，小米手机，Google play安装的最新版

**Comment by Iyiren** [comment]
> 全局试试，或者把负责download的程序加入代理列表，还有一种可能是你的google全家桶需要更新了

估计只能换IP试试了

**Comment by Iyiren** [comment]
> 全局试试，或者把负责download的程序加入代理列表，还有一种可能是你的google全家桶需要更新了

在v2rayN里勾选绕过局域网和大陆地址可以了。。。
