### ISSUE TITLE
Public key none

### ISSUE THREAD

**Issue by DarkZo0m** [MHSanaei/3x-ui#207]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've included all information below (version, config, log, etc).
- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### Description of the problem,screencshot would be good

![image](https://user-images.githubusercontent.com/59771519/231194004-daadb513-a50b-4c5f-ba3c-fb4e463bd21c.png)

بعد از تغییر public key به صورت دستی اون خالی میشه و داخل config ثبت نمیشه در صورتی که من خودم به صورت دستی داخل لینک ها میزارم کار میکنه

### Version of 3x-ui

-

### x-ui log reports or xray log

-

**Comment by mohsen3218** [comment]
منم همین مشکل رو دارم با این تفاوت ک وقتیvless tcp xtls رو فعال میکنم اصلا تنظیمات مربوط به کانفیگ نمیمونه و حذف میشه هی
