### ISSUE TITLE
مشکل در آپلود در بکاپ و ریستور

### ISSUE THREAD

**Issue by afshin1404** [MHSanaei/3x-ui#2071]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

پنلی با ورژن 1.7.8 دارم و وقتی بکاپ اون رو توی آخرین ورژن آپلود میکنم xray error میخوره. راهکاری دارین؟ 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
سلام 
لطفا اروری که نشون میده همینجا بفرستید

**Comment by afshin1404** [comment]
بکاپ دیتابیس از پنل ورژن  1.7.8 هست و مثلا در نسخه ی جدید 2.2.6 که میزنم بارگزاری میشه. ولی از حالت running خارج میشه و x-ray رو مینوسه error

**Comment by MHSanaei** [comment]
اینو گفتین روی ارور کلیک کنید مشکلش رو مینویسه کپی کنید اینجا بزارید

**Comment by afshin1404** [comment]
یه سرور جدید ایجاد کردم و نام بکاپ رو از ساب نیم به x-ui.db تغییر دادم و بارگزاری کردم که ارور رو نشون بده براتون عکس بگیرم برطرف شد و ران شد. احتمالا دفعه های قبل بخاطر ساب نیم اینجوری میشد. چند بار بکاپ گرفته بودم. جدیدا به اسم های x-ui(1).db و.... ذخیره بود ک بارگزاری میکردم و ارور میخوردم

**Comment by afshin1404** [comment]
Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: ext:iran.dat:ir > infra/conf: failed to load external sites: ir from iran.dat > infra/conf: failed to load file: iran.dat > infra/conf: failed to open file: iran.dat > open /usr/local/x-ui/bin/iran.dat: no such file or directory

**Comment by afshin1404** [comment]
این ارور رو در آپدیت پنل به ورژن جدید قسمت xray نشون میده

**Comment by afshin1404** [comment]
ورژن قبلی 1.7.8 بوده وقتی آپدیت میکنم از ران خارج میشه و این ارور میاد

**Comment by MHSanaei** [comment]
برید داخل xray config و دکمه reset to default رو بزنید
