### ISSUE TITLE
ip limit

### ISSUE THREAD

**Issue by roozbehsat** [MHSanaei/3x-ui#2075]
چرا ip limit تو آپدیت جدید کار نمیکنه؟ میشه راهنمایی کنین چه جوری فعالش کنیم؟

**Comment by qar4al** [comment]
باید Fail2ban  رو نصب کنید هم لاگ ip نمایش داده میشه هم بن میکنه

**Comment by roozbehsat** [comment]
نصب کردم fail2ban رو ولی کار نمیکنه
