### ISSUE TITLE
CPU 100% Not access.log and IPLimit

### ISSUE THREAD

**Issue by Puremag1c** [MHSanaei/3x-ui#2077]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

<img width="914" alt="Screenshot 2024-03-16 at 01 49 01" src="https://github.com/MHSanaei/3x-ui/assets/45509847/eaed2eac-40a0-4c0d-aebc-9af9a12f7fac">

 loading CPU to MAX 100%

1 inbound, 1 connection. No bot.
access.log - clean

Starts at a random time, lasts for several hours and then stops loading the processor and returns to normal operation

### Version of 3x-ui

<details>

```console
2.1.3
```

</details>

### x-ui log reports or xray log

<details>

```console

2024/03/15 18:32:28 WARNING - X-UI: get xray traffic failed:rpc error: code = Canceled desc = grpc: the client connection is closing
2024/03/15 18:32:28 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 18:32:16 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 18:31:58 WARNING - X-UI: get xray traffic failed:rpc error: code = Canceled desc = grpc: the client connection is closing
2024/03/15 18:31:58 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 18:31:47 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 18:31:29 WARNING - X-UI: get xray traffic failed:rpc error: code = Canceled desc = grpc: the client connection is closing
2024/03/15 18:31:29 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 18:31:11 WARNING - X-UI: get xray traffic failed:rpc error: code = Canceled desc = grpc: the client connection is closing
2024/03/15 18:31:11 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 18:30:37 WARNING - X-UI: get xray traffic failed:rpc error: code = Canceled desc = grpc: the client connection is closing
2024/03/15 18:30:09 WARNING - X-UI: get xray traffic failed:rpc error: code = Canceled desc = grpc: the client connection is closing
2024/03/15 18:30:09 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 18:29:57 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

</details>

**Comment by Puremag1c** [comment]
Another Node

`2024/03/15 19:25:24 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:25:15 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:25:06 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:24:54 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:24:44 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:24:35 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:24:24 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:24:14 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:24:06 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:23:53 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:23:43 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:23:34 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:23:24 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:23:14 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:23:07 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:22:57 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:22:50 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:22:44 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:22:38 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:22:33 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:22:28 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }`

**Comment by Puremag1c** [comment]
And Third...

<details>

```console
2024/03/15 19:30:16 WARNING - X-UI: get xray traffic failed:rpc error: code = Canceled desc = grpc: the client connection is closing
2024/03/15 19:30:16 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 19:30:12 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:30:01 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 19:29:49 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 19:29:47 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:29:40 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:29:31 WARNING - X-UI: get xray traffic failed:rpc error: code = Canceled desc = grpc: the client connection is closing
2024/03/15 19:29:31 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 19:29:21 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 19:29:11 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 19:28:50 WARNING - X-UI: get xray traffic failed:rpc error: code = Canceled desc = grpc: the client connection is closing
2024/03/15 19:28:50 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 19:28:40 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 19:28:39 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:28:30 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 19:28:19 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 19:28:09 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 19:27:51 WARNING - X-UI: get xray traffic failed:rpc error: code = Canceled desc = grpc: the client connection is closing
2024/03/15 19:27:51 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 19:27:39 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 19:27:38 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:27:28 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 19:27:24 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:27:11 WARNING - X-UI: get xray traffic failed:rpc error: code = Canceled desc = grpc: the client connection is closing
2024/03/15 19:27:11 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 19:27:06 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
2024/03/15 19:26:51 WARNING - X-UI: get xray traffic failed:rpc error: code = Canceled desc = grpc: the client connection is closing
2024/03/15 19:26:51 WARNING - X-UI: get xray traffic failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024/03/15 19:26:35 DEBUG - X-UI: wrong data &{0 0 0 0 0 false 0 [] 0 }
```

</details>

**Comment by MHSanaei** [comment]
just check your logs on the panel (first page)

**Comment by MHSanaei** [comment]
check your rules

**Comment by Puremag1c** [comment]
> check your rules

What rules? all servers have the same configuration. some of them do not have such a problem, some of them have failures as in the example above, randomly


<img width="891" alt="Screenshot 2024-03-16 at 03 50 53" src="https://github.com/MHSanaei/3x-ui/assets/45509847/7c25fa2b-7553-4b46-a7f7-de8b098e0512">
<img width="1377" alt="Screenshot 2024-03-16 at 03 50 39" src="https://github.com/MHSanaei/3x-ui/assets/45509847/25c00378-c67c-46aa-a5ce-a42652fe2097">

**Comment by MHSanaei** [comment]
use "reset to default" button on xray configs/basics

**Comment by Puremag1c** [comment]
Thank you
