### ISSUE TITLE
IP Limit

### ISSUE THREAD

**Issue by DaMitraCo** [MHSanaei/3x-ui#2079]
درود خدمت علیرضای گل

عذر میخوام مزاحم شدم

چرا گزینه ی آی پی لیمیت توی قسمت ساخت کلاینت در آپدیت جدیدتون غیب شده و نیست؟
به جای دیگه ای انتقالش دادید؟

ممنون میشم پاسخ بدید🖤

**Comment by MHSanaei** [comment]
در xray config برای access l مسیر رو انتخاب کنید سیو و ریستارت بعد از اون گزینه ای پی لیمیت نمایش داده میشه 
نصب fail2ban فراموش نشه
