### ISSUE TITLE
مشکل در سابسکریشن

### ISSUE THREAD

**Issue by mehdi2004usa** [MHSanaei/3x-ui#2081]
سلام وخسته نباشید
لینک سابسکریشن در اپدیت جدید از کار افتاده و دیگه کار نمیکنه.ایا برای بقیه دوستان هم همین مشکل بوجود اومده یا نه؟اگه راهی برای برطرف کردنش وجود داره ممنون میشم راهنماییم کنید.سپاس

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/2017#issuecomment-1989627680
