### ISSUE TITLE
نصب نشدن x-ui

### ISSUE THREAD

**Issue by RFFAITHH** [MHSanaei/3x-ui#2082]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

انگار لینک کامندش سرورش مشکل پیدا کرده و نصب نمیکنه اینجوری گیر میکنه
--2024-03-16 17:21:31--  https://raw.githubusercontent.com/MHSanaei/3x-ui/main/x-ui.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by BaseBlank** [comment]
It seems to be an IPv6 issue.
