### ISSUE TITLE
غیرفعال کردن تسک ذخیره کردن آیپی کاربران

### ISSUE THREAD

**Issue by ali-sedaghi** [MHSanaei/3x-ui#209]
سلام خسته نباشید.
طبق بررسی‌هایی که کردم هر 10 ثانیه محتوای درون فایل access.log خونده میشه تا IPهای کاربران ذخیره بشه. این Job که هر 10 ثانیه اجرا میشه باعث میشه که RAM، CPU و دیسک درگیری زیادی داشته باشه در حالی که اصلا ادمین نخواد محدودیت IP برای کلاینت‌ها در نظر بگیره.
با ست کردن loglevel روی none و حتی پاک کردن فیلد access هم دوباره این Job هر 10 ثانیه اجرا میشه و اخطار زیر رو میده:
Apr 11 19:19:23 panel x-ui[32393]: 2023/04/11 19:19:23 WARNING - xray log not init in config.json

وجود امکان غیرفعال کردن این Job درون پنل برای کسانی که سرور ضعیفی دارند بسیار مفید خواهد بود.

**Comment by MHSanaei** [comment]
این خطا وقتی میاد که کانفیگ xray رو تغییر داده باشید و     "access": "./access.log" رو حذف کرده باشید 
لطفا کانفیگ رو از [این قسمت کپی](https://raw.githubusercontent.com/MHSanaei/3x-ui/main/media/enable-traffic.txt) کنید و قرار بدید

**Comment by MHSanaei** [comment]
میتونید پنل علیرضا رو نصب کنید limitip نداره درنتیجه هر ده ثانیه لاگ چک نمیکنه
