### ISSUE TITLE
عدم رد کردن کل ترافیک از وارپ در ورژن جدید سنایی v2.2.6 

### ISSUE THREAD

**Issue by faridRezvani** [MHSanaei/3x-ui#2092]
[طبق مستندات آموزشی در این ریپازیتوری](https://github.com/MHSanaei/3x-ui/wiki/Common-questions-and-problems#11---%D8%A8%D8%B9%D8%B6%DB%8C-%D8%B3%D8%A7%DB%8C%D8%AA%D8%A7-%D8%A8%D8%B1%D8%A7%D9%85-%D8%A8%D8%A7%D8%B2-%D9%86%D9%85%DB%8C%D8%B4%D9%87-%D9%88%D8%A7%D8%B1%D9%BE-%DA%86%DB%8C%D9%87-%DA%86%D8%AC%D9%88%D8%B1%DB%8C-%D9%81%D8%B9%D8%A7%D9%84%D8%B4-%DA%A9%D9%86%D9%85-%DA%86%D8%AC%D9%88%D8%B1%DB%8C-%DA%A9%D9%84-%D8%AA%D8%B1%D8%A7%D9%81%DB%8C%DA%A9-%D8%B1%D9%88-%D8%A7%D8%B2-%D9%88%D8%A7%D8%B1%D9%BE-%D8%B1%D8%AF-%DA%A9%D9%86%D9%85)  برای رد کردن کل ترافیک از وارپ ، کد route وارپ را در ستون Advanced به شکل زیر تغییر دادم.

      {
        "type": "field",
        "outboundTag": "warp",
        "network": "tcp,udp"
      },

ولی متاسفانه کار نمیکند.
تکه کد زیر را هم تست کردم ولی همچنان کل ترافیک من از روی وارپ عبور نمی کند. دوستان ممنون می شوم کسی میتواند من را راهنمایی کند.

```
{
   "type":"field",
   "outboundTag":"WARP",
   "domain":[
      "regexp:.*"
   ],
   "ip":[
      "0.0.0.0/0"
   ]
}
```

**Comment by Shm9220** [comment]
توی outbound سرورت اونی که نوشته وارپ رو وقتی بیاری اولین ردیف همش از وارپ رد میشه
