### ISSUE TITLE
کار نکردن بات تلگرام روی سرور ایران socks5  

### ISSUE THREAD

**Issue by elegance666** [MHSanaei/3x-ui#2093]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

من socks5 رو یک سرور خارجی نصب کردم و تنظیمات SOCKS Proxy هم پر کردم ولی از سرور ایران پیامی ارسال نمیشه به تلگرام

حتی وقتی تو سرور ایران این دستور میزنم
`
 curl -v -x socks5://user:pass@xxx.xxx.xxx.xxx:1080 https://web.telegram.org`

 چون سایت تلگرام فیلتره، این پیام میده:
`SOCKS5 connect to IPv4 10.10.34.36:443 (locally resolved)`

ولی سایت‌های دیگه باز میکنه

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by mohammadreza1997** [comment]
اگر ریورس تانل کردید توی تنظیمات xray تیک اینباند پروکسی تلگرام رو بزنید و روی همون سرور ایران پروکسی بسازید اینجوری وصل میشه راهنمایی بیشتر خواستید  تلگرام در خدمتم @lvlr7

**Comment by MoSi8160** [comment]
سلام . منم همچین مشکلی دارم . تونستی مشکلت رو حل کنی ؟
