### ISSUE TITLE
باز نشدن سایت هایی مثل یوتیوب هنگام فعال کردن وارپ

### ISSUE THREAD

**Issue by m0hammadhossein** [MHSanaei/3x-ui#2096]
سلام.وقتی وارپ رو تو قسمت خروجی ها اضافه میکنم و یکی از ورودی ها رو بهش وصل میکنم که کل ترافیکش ازون وارپ بگذره موقع بازکردن سایت هایی مثل یوتیوب یا ردیت و... هنگ میکنه همونطور میمونه باز نمیکنه

**Comment by gachineh** [comment]
از تنظیمات xray برو DNS اضافه کن
1.1.1.1
8.8.4.4
سربرگ بیسیک زیرشاخه وارپ  تیک گوگل رو بزن
