### ISSUE TITLE
WARP stops working sometimes

### ISSUE THREAD

**Issue by DmB-Ekb** [MHSanaei/3x-ui#2107]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

From time to time the WARP does not work.
Accesses to websites routed through WARP are timeouted.
At the same time the panel log shows an error "ERROR - XRAY: peer(bmXO…fgyo)" every five seconds.
After restarting the Xray kernel everything works, then sometimes it stops working again.

### Version of 3x-ui

<details>

```console
2.2.6
```

</details>

### x-ui log reports or xray log

<details>

```console
2024/03/18 14:28:54 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/18 14:28:51 ERROR - XRAY: peer(bmXO…fgyo) - Failed to send handshake initiation: write udp [::]:42111->[2606:4700:d0::a29f:c001]:2408: sendto: cannot assign requested address
2024/03/18 14:28:45 ERROR - XRAY: peer(bmXO…fgyo) - Failed to send handshake initiation: write udp [::]:42111->[2606:4700:d0::a29f:c001]:2408: sendto: cannot assign requested address
2024/03/18 14:28:40 ERROR - XRAY: peer(bmXO…fgyo) - Failed to send handshake initiation: write udp [::]:42111->[2606:4700:d0::a29f:c001]:2408: sendto: cannot assign requested address
2024/03/18 14:28:35 ERROR - XRAY: peer(bmXO…fgyo) - Failed to send handshake initiation: write udp [::]:42111->[2606:4700:d0::a29f:c001]:2408: sendto: cannot assign requested address
2024/03/18 14:28:30 ERROR - XRAY: peer(bmXO…fgyo) - Failed to send handshake initiation: write udp [::]:42111->[2606:4700:d0::a29f:c001]:2408: sendto: cannot assign requested address
2024/03/18 14:28:25 ERROR - XRAY: peer(bmXO…fgyo) - Failed to send handshake initiation: write udp [::]:42111->[2606:4700:d0::a29f:c001]:2408: sendto: cannot assign requested address
2024/03/18 14:28:19 ERROR - XRAY: peer(bmXO…fgyo) - Failed to send handshake initiation: write udp [::]:42111->[2606:4700:d0::a29f:c001]:2408: sendto: cannot assign requested address
2024/03/18 14:28:14 ERROR - XRAY: peer(bmXO…fgyo) - Failed to send handshake initiation: write udp [::]:42111->[2606:4700:d0::a29f:c001]:2408: sendto: cannot assign requested address
2024/03/18 14:28:09 ERROR - XRAY: peer(bmXO…fgyo) - Failed to send handshake initiation: write udp [::]:42111->[2606:4700:d0::a29f:c001]:2408: sendto: cannot assign requested address
2024/03/18 14:28:04 ERROR - XRAY: peer(bmXO…fgyo) - Failed to send handshake initiation: write udp [::]:42111->[2606:4700:d0::a29f:c001]:2408: sendto: cannot assign requested address
2024/03/18 14:27:59 ERROR - XRAY: peer(bmXO…fgyo) - Failed to send handshake initiation: write udp [::]:42111->[2606:4700:d0::a29f:c001]:2408: sendto: cannot assign requested address
2024/03/18 14:27:54 ERROR - XRAY: peer(bmXO…fgyo) - Failed to send handshake initiation: write udp [::]:42111->[2606:4700:d0::a29f:c001]:2408: sendto: cannot assign requested address
```

</details>

**Comment by jahlib** [comment]
https://github.com/TheyCallMeSecond/WARP-Endpoint-IP

hey, i dont know if this help, but try to change warp cf endpoint address, this rep help you to choose better address for you server

**Comment by MHSanaei** [comment]
Just install the latest version then click on reset to default and set your settings again

**Comment by DyosDV** [comment]
I deleted the ipv6 address, after that the errors disappeared

**Comment by DmB-Ekb** [comment]
> I deleted the ipv6 address, after that the errors disappeared

Thanks, are you talking about this setting?
![IPv6](https://github.com/MHSanaei/3x-ui/assets/101321528/b58e1043-ac3d-4303-9c0b-8e3ae648140f)
