### ISSUE TITLE
trafic

### ISSUE THREAD

**Issue by maltima** [MHSanaei/3x-ui#211]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

اپدیت کردم ترافیک نشون نمیده

### Version of 3x-ui

<details>

```console
1.2.1
```

</details>

### x-ui log reports or xray log

<details>

```console
Apr 11 17:48:41 ubuntu-2gb-nbg1-1 x-ui[1417874]: 2023/04/11 17:48:41 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email

```

</details>

**Comment by MHSanaei** [comment]
قبل این لاگی که گذاشتید اسم یه یوزر رو نشون میده اون یوزر رو حذف کنید و مجدد بسازید مشکلتون حل میشه
