### ISSUE TITLE
Access to clients using virtual IP address

### ISSUE THREAD

**Issue by Sarevok93219** [MHSanaei/3x-ui#2115]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello. In process of working. Clients have access to internal subnet of server. But I also need to have access to client (their subnets) . Using NekoBox in Windows, it configure virtual IP such as 172.19.0.2. But server doesn't have any connection (even ping) on such address. How can I configure it and give access to clients from server using secure traffic? 

### Version of 3x-ui

1.8.7

### x-ui log reports or xray log

2024/03/22 15:35:13 INFO - X-UI: user1login success
2024/03/22 15:35:13 INFO - X-UI: ctrlops-admin login success, Ip Address: 172.150.88.1
2024/03/22 15:35:11 INFO - X-UI: user1logout
2024/03/22 13:56:31 WARNING - XRAY: core: Xray 1.8.7 started
2024/03/22 13:56:31 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/22 13:56:19 WARNING - XRAY: core: Xray 1.8.7 started
2024/03/22 13:56:19 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/22 13:55:01 WARNING - XRAY: core: Xray 1.8.7 started
2024/03/22 13:55:01 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/22 13:54:49 WARNING - XRAY: core: Xray 1.8.7 started
2024/03/22 13:54:49 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/22 13:48:12 WARNING - XRAY: core: Xray 1.8.7 started
2024/03/22 13:48:12 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/22 13:48:12 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/22 13:48:10 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/22 13:48:06 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/22 13:48:04 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/22 13:48:00 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/22 13:47:58 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/22 13:47:56 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/03/22 13:47:54 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json

**Comment by netandreus** [comment]
@MHSanaei How can I access the networks behind the wiregurad client from a virtual machine with 3x-ui server?
