### ISSUE TITLE
مشکل عدم کارکرد کانفیگ json

### ISSUE THREAD

**Issue by Erfanmv** [MHSanaei/3x-ui#2116]
سلام
لینک ساب جیسون در ورژن ۲.۲.۱ به درستی کار میکرد.
با اپدیت جدید متاسفانه اررور unknown configuration از سمت نرم افزار کلاینت دریافت میکنم
طبق توضیحات در بخش مشکلات با اضافه کردن authority مشکل دریافت حل شد ولی همچنان متصل نمیشه
کانفیگ فعلی هم که در حال استفاده هستم reality grpc هستش.
ایا راه حلی برای حل مشکل از سمت ما هستش یا باگ این ورژن هستش ؟

**Comment by rajaeem** [comment]
ظاهرا باگ هست اول و آخر کانفیگ کاراکترِ براکت اضافه وجود داره.
![Screenshot 2024-03-23 025849](https://github.com/MHSanaei/3x-ui/assets/29551782/f309dc66-d8b3-4770-b7b1-348b72a8273c)

**Comment by MHSanaei** [comment]
برنامه کلاینت باید اپدیت باشه و از ویژگی جدید پشتیبانی کنه
