### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by DevNima-PG** [MHSanaei/3x-ui#212]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام، از نسخه های اولیه که ریلیز شده تا الان یه مشکل کوچیکی هست که فیکس نشده! اونم مشکل سی پی یو هستش، من از نسخه .1.2.0 استفاده میکنم الان در حال حاضر، و این مشکل رو داریم:
![cpu](https://user-images.githubusercontent.com/85389307/231251806-4ddfd655-3360-44f5-919b-ed05d9ef1e90.png)

ممنون میشم فیکس کنین 💙 پنل و امکاناتش عالیه
بعد راستی یک باگ هم هست تو بخش لینک ساب، اگه شما پث پنل رو از دیفالت / تغییر بدید به مثلا:
/test
لینک ساب هم باید پشتش /test باشه وگرنه نات فوند میده، فک کنم این مورد رو حواستون نبوده 💙 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
