### ISSUE TITLE
مشکل رد نشدن اپلیکیشن spotify از warp

### ISSUE THREAD

**Issue by Obeid1375** [MHSanaei/3x-ui#2121]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

خسته نباشید.

من از ورپ پنل استفاده میکنم و وقتی تیک ورپ اسپاتیفای روشن میکنم سایت و برنامه ویندوز اوکی میشن اما برنامه اندرویدش اوکی نمیشه.
مگه اینکه ورپو از حالت دامنه خاص خارج میکنم و سراری میشه و اپ اسپاتیفای روی اندروید کار میکنه.
فک کنم دامنه و سرور های اپ اسپاتیفای توی فایل geosite قرار ندارند و از ورپ عبور نمیکنه.

ممنون میشم بررسی کنید.

### Version of 3x-ui

2.2.6

### x-ui log reports or xray log

no log

**Comment by Shm9220** [comment]
فک کنم انگار توی اپدیتای جدید این مشکل به وجود اومده برا منم اینطوری شده ورژنمم مثل شماس

**Comment by Obeid1375** [comment]
> فک کنم انگار توی اپدیتای جدید این مشکل به وجود اومده برا منم اینطوری شده ورژنمم مثل شماس

توی نسخه 2.2.0 هم همینه

**Comment by Shm9220** [comment]
اره الان دانگرید کردم برا منم فرقی نکرد

**Comment by Shm9220** [comment]
اگه راهی غیر گذروندن همه ترافیک از وارپ پیدا کردی بگو اینجا

**Comment by Shm9220** [comment]
geosite هارو هم اپدیت کردم فرق نکرد

**Comment by Obeid1375** [comment]
> اگه راهی غیر گذروندن همه ترافیک از وارپ پیدا کردی بگو اینجا

باشه.

باید یطوری آیپی و دامنه سرورشو پیدا کرد دستی اد کنیم.

**Comment by Shm9220** [comment]
ممکنه ثابت نباشه. وگرنه که باید مثلا با spotify.com کار کنه که برا من کار نکرد. عجیب اونکه برا خیلیا داره کار میکنه بدون مشکل . نمیفمم مشکل کجاست . یکی دو روزه اسیرم کرده

**Comment by Obeid1375** [comment]
> ممکنه ثابت نباشه. وگرنه که باید مثلا با spotify.com کار کنه که برا من کار نکرد. عجیب اونکه برا خیلیا داره کار میکنه بدون مشکل . نمیفمم مشکل کجاست . یکی دو روزه اسیرم کرده

کلا هیمنه بعد یه مدت تشخیص وی پی ان میده میبنده آیپی سرورتو.
اینارو تست کن.

tospotify.com,spotilocal.com,spotifycdn.net,spotify.com,spotifycdn.com,spoti.fi,scdn.co,pscdn.co

**Comment by Shm9220** [comment]
آخه وارپ برا همین میزنیم که ای پی سرورو نبینه دیگه نمیدونم چجوری وارپ هم به فنا میره

**Comment by Shm9220** [comment]
#735

**Comment by Obeid1375** [comment]
> #735

ممنون ولی خودمم همینو گفتم روی all کار میده بخوای بزاری روی سایت های خاص کار نمیده 😁

**Comment by Shm9220** [comment]
کامنت یکی به اخرش رو بخون

**Comment by Shm9220** [comment]
فعال کرم رو اپ درست شد . حالا سوال پیش میاد که رو نپستر داره یا نه ؟ یا نمیشه از سمت سرور اینو انجام داد

**Comment by Shm9220** [comment]
توی اپدیت جدید 2.2.6 این تب اضافه شده . فک کنم ازینجا بشه ولی در حال حاضر بلد نیسمش 
![Screenshot_20240324-025258_Gallery](https://github.com/MHSanaei/3x-ui/assets/130503936/0be8426f-6dca-4e80-9c7c-8f24a6bf2773)

**Comment by pouriasharifzad** [comment]
> توی اپدیت جدید 2.2.6 این تب اضافه شده . فک کنم ازینجا بشه ولی در حال حاضر بلد نیسمش ![Screenshot_20240324-025258_Gallery](https://github.com/MHSanaei/3x-ui/assets/130503936/0be8426f-6dca-4e80-9c7c-8f24a6bf2773)

راه حل قطعی پیدا کردین؟
