### ISSUE TITLE
مشکل گیر و اختلال در اینستاگرام

### ISSUE THREAD

**Issue by Behtash007** [MHSanaei/3x-ui#2123]
سلام دوستان 
راه حلی برای مشکل اینستاگرام داریم 
خیلی گیر و لک داره ، کلیپ و عکسها باز نمیشن یا کند هستش 
ای پی سرور پشت کلود فلر بردم ، سرعت در جاهای دیگه خوب هستش ولی در اینستاگرام مشکل دارم

**Comment by faridRezvani** [comment]
آیا وارپ را از منوی تنظیمات فعال کردی؟
آیا وقتی وارپ روشنه این مشکل را داری؟
![sss](https://github.com/MHSanaei/3x-ui/assets/10058552/8d1fa135-206d-49e4-94ba-65f59e3c64c5)

**Comment by Behtash007** [comment]
> آیا وارپ را از منوی تنظیمات فعال کردی؟ آیا وقتی وارپ روشنه این مشکل را داری؟ ![sss](https://private-user-images.githubusercontent.com/10058552/316267756-8d1fa135-206d-49e4-94ba-65f59e3c64c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjc1NDUsIm5iZiI6MTcxMTIyNzI0NSwicGF0aCI6Ii8xMDA1ODU1Mi8zMTYyNjc3NTYtOGQxZmExMzUtMjA2ZC00OWU0LTk0YmEtNjVmNTllM2M2NGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIwNTQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYjYxMTE2ZTUxYWYxNWRjOTMyZmZmMDE5OTJiOTAyNzhlNzk2NmJlMTNmZjI1NDc3NzI2ZWY2NDQzOWNlZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.041MFDgI-cIzyBLHzFw75BRs3n4X3ka2QUI2RKJMtEY)

با وارپ بدتر میشه ، کلا باز نمیکنه

**Comment by Arman-nsb** [comment]
برای وارپ کلید warp plus بگیر ( واسه این مورد ربات تلگرام داریم: warpplusbot). اگر سرورت از ipv6 ساپورت میکنه تو تنظیمات outbound مربوط به وارپ، گزینه DomainStrategy رو بذار روی حالت ForceIPv6IPv4 و ذخیره ریستارت بزن یبار روی xray .

**Comment by mohamadm0meni** [comment]
> برای وارپ کلید warp plus بگیر ( واسه این مورد ربات تلگرام داریم: warpplusbot). اگر سرورت از ipv6 ساپورت میکنه تو تنظیمات outbound مربوط به وارپ، گزینه DomainStrategy رو بذار روی حالت ForceIPv6IPv4 و ذخیره ریستارت بزن یبار روی xray .

بعد از گرفتن واپ پلاس چگونه آن را روی سرور اعمال کنیم که فقط روی سایت های که خودمون میخواهیم ست بشه نه روی کل سرور

**Comment by Arman-nsb** [comment]
@mohamadm0meni 
باید از تنظیمات ایکس ری > بخش قوانین مسیریابی استفاده کنی و دامنه های مقصد رو به خروجی warp متصل کنی. اینجوری درخواست ها برای دامنه های مدنظرت از وارپ عبور میکنن. نمونه:
![image](https://github.com/MHSanaei/3x-ui/assets/84615037/2013f0dc-58ab-4fff-8144-75597fd39bae)

**Comment by mohamadm0meni** [comment]
> @mohamadm0meni 
> 
> باید از تنظیمات ایکس ری > بخش قوانین مسیریابی استفاده کنی و دامنه های مقصد رو به خروجی وارپ متصل کنی. اینجوری درخواست ها برای دامنه های مدنظرت از وارپ عبور میکنن. نمونه:
> 
> ![image](https://github.com/MHSanaei/3x-ui/assets/84615037/2013f0dc-58ab-4fff-8144-75597fd39bae)
> 

درسته نحوه اعمال آن رو روی سایت هایی که میخواهیم رو میدونم نحوه اعمال وارپ پلاس به جای وارپ معمولی رو میخوام بدونم چطوری هست

**Comment by mohamadm0meni** [comment]
> @mohamadm0meni 
> 
> کلید لایسنس وارپ پلاس رو وارد کنید، خودش فعال میشه: ( ذخیره و ریستارت ایکس ری فراموش نشه )
> 
> ![image](https://github.com/MHSanaei/3x-ui/assets/84615037/54ff19fc-61e3-449a-b235-d555bb2b5f67)
> 

ممنونم ازت
من رفته بودم از توی قسمت advance تغییرات رو دادم
به غیر از private key شون mtu هم فرق داشت پابلیک کی هاشونم یکسان بود.

**Comment by mehrdadghadam** [comment]
من برای اسپاتیفای انجام دادم نمیشه
ولی وقتی رو کل سرور وارپو میزنم میشه
مشکلی از کجاس؟
