### ISSUE TITLE
سابسکرایب

### ISSUE THREAD

**Issue by Xiaonunche** [MHSanaei/3x-ui#213]
ای کاش می تونستید داخل پنل یه قابلیت اضافه کنید که لینک سابسکرایب داشته باشیم. یا بشه فایل ساب رو تو پنل آپلود کنیم و از اونجا به اشتراک بذاریم . متشکرم

**Comment by MHSanaei** [comment]
قابلیت ساب چند روز پیش اضافه شد (از کد های پنل مهندس علیرضا برداشته شد)
