### ISSUE TITLE
مشکل آپلود خیلی زیاد سرور

### ISSUE THREAD

**Issue by feridj2020** [MHSanaei/3x-ui#2135]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام و درود ..اخیرا به مشکلی برخورد کردم روی همه سرورهام اینطوره که آپلود به صورت مدام بالاس و باعث میشه ۳۰ترابایت مصرف شه و ابیوز شم ..نت اسکن بسته شده فایروال فعال حتی تی ال اس هم فعال کردم باز همون داستانه ..سرور هرتزنره و سرویس از نوع cdn کلادفلر
![Untitled](https://github.com/MHSanaei/3x-ui/assets/121224327/e8593938-3787-46e1-b61d-69e0c0460d8b)

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Mahdimkkkm** [comment]
> بگرد ببین کجا و یا کی مصرف میکنه

پنل برام نمیاره و گوگل خطای ERR_CONNECTION_RESET میده چیکار باید بکنم ممنون میشم راهنمایی کنید در ضمن پنل رو اپدیت کردم روی نسخه پایین تر هم تست کردم ریستارت هم کردم اما جواب نداد

**Comment by feridj2020** [comment]
> بگرد ببین کجا و یا کی مصرف میکنه

گشتم همه نرمال هستن..جالب اینجاس چند تا سروره چندتاشونم همین داستانه اونایی که روی هرتزنر هستن. ovh مشکلی نیست
