### ISSUE TITLE
hi, I can't login with username and password

### ISSUE THREAD

**Issue by MicroMatrixOrg** [MHSanaei/3x-ui#2138]
hi
i have the same issue with username and password

_Originally posted by @David-Azaani in https://github.com/MHSanaei/3x-ui/issues/1143#issuecomment-1873377659_

**Comment by MHSanaei** [comment]
Install the latest version and on the x-ui terminal reset your password.

**Comment by MicroMatrixOrg** [comment]
I found this BUG, which was caused by the fact that Secret login had been opened and then closed

**Comment by MicroMatrixOrg** [comment]
> Install the latest version and on the x-ui terminal reset your password.

I found this BUG, which was caused by the fact that Secret login had been opened and then closed

**Comment by MHSanaei** [comment]
Has been fixed on v2.2.6

**Comment by MicroMatrixOrg** [comment]
![image](https://github.com/MHSanaei/3x-ui/assets/21361701/dc405a34-3710-4fef-b265-ded0539dee75)
I get the bug in v2.2.6。I build the web with docker compose。

**Comment by MicroMatrixOrg** [comment]
> Has been fixed on v2.2.6

foget about it.It is work now.
