### ISSUE TITLE
نداشتن قابلیت محدود کردن تعداد ایپی متصل

### ISSUE THREAD

**Issue by Mo3tafakhodsetan** [MHSanaei/3x-ui#2139]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام وقت بخیر
تو پنل جدید امکان انتخاب تعداد ایپی همزمان برای اتصال به یوزر فراهم نیست 
چجوری میشه این قابلیت رو فعال کرد دوباره ؟

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
برید داخل xray config و برای access log مسیر انتخاب کنید و سپس save and restart بعد از اون iplimit نمایش داده میشه
