### ISSUE TITLE
مشکل تک کاربره کردن یوزرها در تانل شده

### ISSUE THREAD

**Issue by hadi13651987** [MHSanaei/3x-ui#2143]
سلام خسته نباشید
البته نمیدونم امکان پذیر باشه یا نه پیشنهادی که داشتم برای تک کاربره کردن اکانت ها در پنل تانل شده این هست اکانت هایی که به صورت subscration روی دستگاه ها اضافه شدند امکانی در پنل باشد که در اولین اتصال device id روی همان اکانت به صورت اتومات اضافه بشود که دستگاه دوم قابلیت اتصال نداشته باشد
ممنون

**Comment by era1382** [comment]
سلام اگه امکانش باشه قابلیت limit device connected بزارین خیلی خوب میشه، اینجوری مشکل تک کاربره کردن تونل حل میشه
