### ISSUE TITLE
"start after first use" In API Requests

### ISSUE THREAD

**Issue by ppsimn** [MHSanaei/3x-ui#2145]
سلام وقت بخیر. 
لطفا راهنمایی بفرمایید ایا امکانش هست که در هنگام ساخت کلاینت با API متصل به پنل،
زمان باقیمانده رو به صورت start after first use که در پنل هم موجوده، وارد ریکوئست کنیم؟ 
اگر امکانش هست، بفرمایید پارامتر settings در ریکوئست POST /addClient چطور باید نوشته بشه/ تغییر پیدا کنه.

در حال حاضر نمیتونم چیزی جز میلی ثانیه زمان باقیمانده در داکیومنت ها پیدا کنم.
این پارامتر هایی هست که در حال حاضر استفاده میکنم: (nodeJS)
``` 
let _exptime = client.days * 86400000 + Date.now();
...

let _settings = {
	"clients": [{ "id": _randomUUID, "alterId": 0, "email": client.email, "totalGB": _bytes, "expiryTime": _exptime, "enable": true, "tgId": "", "subId": "" }],
};
```

**Comment by Iliyanewcomer** [comment]
درود.
تایم مورد نظرتون رو بر اساس {ثانیه * 1000} - در expiryTime بنویسید برای مثال هفت روز:
7*24*60*60*1000 = 604800000
رو بصورت منفی بنویسید:
-604800000

**Comment by ppsimn** [comment]
متشکرم
