### ISSUE TITLE
 Disabled نمایش اشتباه تعداد یوزر 

### ISSUE THREAD

**Issue by Shm9220** [MHSanaei/3x-ui#215]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام من از پنل اسدی اپدیت کردم به پنل شما و یوزرا رو با بک اپ اوردم روش . توی ورژن 1.1.5 تعداد یوزر های غیرفعال رو درست نشون میداد. ولی با اپدیت به 1.2.0 داره یوزرایی که خیلی وقت پیش حذف کردمم حساب میکنه توش
![Uploading Screenshot_20230411-230957_Chrome.jpg…]()

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
سلام بله چون پنل های قدیمی وقتی یوزری حذف میشه از داخل دیتابیس کامل حذف نمیشه و باقی میمونه

**Comment by Shm9220** [comment]
تو ورژن 1.1.4 خودتون ولی درست نشون میداد چرا

**Comment by Shm9220** [comment]
و چطوری میشه حلش کرد

**Comment by MHSanaei** [comment]
با اسم اون یوزر 2باره اکانت بسازید و سپس حذف کنید (تست نشده نمیدونم جواب بده یا نه)
یا دیتابیس رو به کمک برنامه هایی که هست ویرایش کنید
