### ISSUE TITLE
updating trojan client by api doesnt work

### ISSUE THREAD

**Issue by zifulx** [MHSanaei/3x-ui#2150]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

as you said we used password as client id for updating trojan client by api but it doesnt work,i will appreciate that if you help me to solve this problem...

i will share you the log for more information.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

{
"success": false,
"msg": "Something went wrong! Failed: empty client ID\n",
"obj": null
}

**Comment by Iliyanewcomer** [comment]
Hi bro

ur link must be like this:
http://ip:port/panel/inbound/updateClient/KGYpI7kbtV
