### ISSUE TITLE
windows server release

### ISSUE THREAD

**Issue by mmdjvdad** [MHSanaei/3x-ui#2153]
سلام مهندس یه ریلیز برای ویندوز سرور بدین. دوتا نسخه تو گیتهاب هست ورژنشون پایینه و اپدیت نمیشن

**Comment by MHSanaei** [comment]
باشه فعلا درگیر جابجایی هستم بعدا اضافه میکنم

**Comment by mmdjvdad** [comment]
تشکر بسیار عالی

**Comment by MHSanaei** [comment]
Done
