### ISSUE TITLE
Adding the Observatory for using LeastPing

### ISSUE THREAD

**Issue by amirooo70** [MHSanaei/3x-ui#2157]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

درود. برای استفاده از قابلیت leastping در balancer لازمه که حتما از Observatory استفاده بشه. این مورد به صورت خودکار به کانفیگ اضافه نمیشه و باید به صورت دستی اضافه کنیم. لطفا به صورت خودکار این قابلیت رو اضافه کنید. به عنوان مثال:

"observatory": {
    "subjectSelector": [
          "server1",
          "server2"
    ],
    "probeURL": "https://www.google.com/generate_204",
    "probeInterval": "1m"
}

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
بله برای اپدیت بعدی اضافه میشه
