### ISSUE TITLE
ubuntu > docker easy installation > issue:  Panel state: Not Installed

### ISSUE THREAD

**Issue by nimabbz** [MHSanaei/3x-ui#2159]
Hi
I'm using the latest version on 3x-ui Sanaei, but there are some errors even the proxy works fine.
====================================
  0. Exit Script
————————————————
  1. Install
  2. Update
  3. Custom Version
  4. Uninstall
————————————————
  5. Reset Username & Password & Secret Token
  6. Reset Settings
  7. Change Port
  8. View Current Settings
————————————————
  9. Start
  10. Stop
  11. Restart
  12. Check Status
  13. Check Logs
————————————————
  14. Enable Autostart
  15. Disable Autostart
————————————————
  16. SSL Certificate Management
  17. Cloudflare SSL Certificate
  18. IP Limit Management
  19. WARP Management
  20. Firewall Management
————————————————
  21. Enable BBR
  22. Update Geo Files
  23. Speedtest by Ookla

**Panel state: Not Installed**
**xray state: Running**

Please enter your selection [0-23]: 21
        1. Enable BBR
        2. Disable BBR
        0. Back to Main Menu
Choose an option: 1
**Unsupported operating system. Please check the script and install the necessary packages manually.**
========================
I'm using on ubuntu 20.04 vmServer Hetzner and setup panel via docker. I can use the proxy and panel works, but I cannot use menu options. It tells: **Panel state: Not Installed**

Is there any updated version of docker easy installation?

Regards

### Version of 3x-ui

<details>

```console
#3X-UI: [v2.2.6](https://github.com/MHSanaei/3x-ui/releases) [@Panel3xui](https://t.me/panel3xui)
```

</details>

### x-ui log reports or xray log

<details>

```console
there is no access to run this command
```
 
</details>

**Comment by mmdjvdad** [comment]
داداش تو داکر نصب کردی رو خود سرور که نصب نکردی میخوای دستورات بزنی.
