### ISSUE TITLE
نمایش مقدار ترافیک مصرفی در پنل سنایی

### ISSUE THREAD

**Issue by madar54** [MHSanaei/3x-ui#2160]
![Uploading Screenshot 2024-03-29 210328.png…]()
با سلام به بزرگان پنل سنایی ر پنل سنایی دو گزینه وجود دارد که مقدار مصرفی پهنای باند را نشان می‌دهد و این دو با هم اختلاف زیادی دارند اگر مقدور است توضیح دهید کدام گزینه مقدار صحیح را نشان می‌دهد با تشکر

**Comment by madar54** [comment]
![Uploading Screenshot 2024-03-29 210328.png…]()

**Comment by madar54** [comment]
![Screenshot 2024-03-29 210403](https://github.com/MHSanaei/3x-ui/assets/153379079/acdf7947-7a79-4aef-b3c3-91d08f25ed1c)

**Comment by madar54** [comment]
![Screenshot 2024-03-29 210328](https://github.com/MHSanaei/3x-ui/assets/153379079/fefa6051-da05-4e4e-ae44-03650fe2753d)

**Comment by faridRezvani** [comment]
عکس اول داخل منوی inbounds  مقدار ارسال و دریافت و مصرف کاربران از v2ray هست.
عکس دوم مقدار پهنای باند خود سیستم عامل هست. مثلا اگه سیستم عاملت را آپدیت کین . به طبع حجم عظیمی داده دانلود میشه و این مقدار.
با هر بار ری استارت کردن سیستم عامل مقدار صفر می شود
