### ISSUE TITLE
xray state: Not Running

### ISSUE THREAD

**Issue by Vlaadislove** [MHSanaei/3x-ui#2161]
Tell me who has encountered the problem, I don’t know how to run xray. OS Debian
![Снимокк](https://github.com/MHSanaei/3x-ui/assets/112594694/e4c8c9a0-7cb2-4261-9480-8dab989e459a)

**Comment by HamedX2Z** [comment]
شماره 9 رو وارد کن و enter بزن تا xray ران شه اگر بازم نشد پنل رو چک کن تا ببین ارور داره یا نه
