### ISSUE TITLE
عدم تغییر میزان دانلود و اپلود یوزر ها در پنل

### ISSUE THREAD

**Issue by javadmahmoodi670** [MHSanaei/3x-ui#217]
سلام وقت بخیر 
متاسفانه در ورژن اخر میزان مصرف یوزر ها مانند دانلود و اپلود درست کار نمیکنه و بعد گذشت زمان زیاد مقدار kb تغییر میکنه درصورتی که چند گیگ مصرف داشته. 
ایا میزان واقعی مصرف حجم ذخیره شده یا خیر؟

**Comment by MHSanaei** [comment]
#203
