### ISSUE TITLE
Installation panel error

### ISSUE THREAD

**Issue by RookieAssociator** [MHSanaei/3x-ui#2171]
![Snipaste_2024-03-31_15-40-54](https://github.com/MHSanaei/3x-ui/assets/96603803/63e2df9a-15e9-490d-8925-0aff028f2e8f)

**Comment by MHSanaei** [comment]
What is your OS?

**Comment by RookieAssociator** [comment]
> What is your OS?

Oracle

**Comment by RookieAssociator** [comment]
> 你的操作系统是什么？
Now the problem has been solved. I can just use the arm installation package. Thank you for your help.

**Comment by RookieAssociator** [comment]
![Snipaste_2024-03-31_18-20-43](https://github.com/MHSanaei/3x-ui/assets/96603803/b6997f82-7a2c-4dfb-ba60-b8d6dc0a3973)

**Comment by RookieAssociator** [comment]
Is the oracle linux system not supported yet?

**Comment by MHSanaei** [comment]
Recommended OS
Ubuntu 20.04+
Debian 11+
CentOS 8+
Fedora 36+
Arch Linux
Manjaro
Armbian
AlmaLinux 9+
Rockylinux 9+

**Comment by RookieAssociator** [comment]
Okay, I know

**Comment by MHSanaei** [comment]
I will add it later.
