### ISSUE TITLE
رفع مشکل

### ISSUE THREAD

**Issue by amirzare021** [MHSanaei/3x-ui#2175]
سلام وقتتون بخیر
قبلا داخل تلگرام یه گروه داشتین که همه میتونستند سوالاشونو بپرسند برای رفع مشکل هرکس دانشی در مورد اون سوال داشت کمک میکرد یا اگر کسی نمیتونست جواب بده خود ادمین ها کمک میکرند

الان دیگه همچین گروهی ندارین؟

**Comment by MHSanaei** [comment]
سلام خیر
