### ISSUE TITLE
windows version

### ISSUE THREAD

**Issue by mmdjvdad** [MHSanaei/3x-ui#2177]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

مهندس اصلا اجرا نمیشه نه روی سرور نه روی پی سی خودم. با تنظیمات کامپبیلیتی هم اجرا نشد.

### Version of 3x-ui

2.2.7

### x-ui log reports or xray log

no log

**Comment by mmdjvdad** [comment]
![Screenshot 2024-04-01 183719](https://github.com/MHSanaei/3x-ui/assets/122828400/122c44db-d2b2-47f5-ada6-512de731d4a9)

**Comment by MHSanaei** [comment]
فقط کافیه روش کلیک کنید

**Comment by mmdjvdad** [comment]
داداش....   D:
باز نمیشه اصلا یه لحظه یه صفحه سیاه cmd میاد و سریع میره. با پاورشل باز کردم این ایراد رو گرفت. روی سرور و روی کامپیوتر خودم هم تست کردم جفتش همینطوره. با تغییر تایم زون هم تغییری نکرد

**Comment by mmdjvdad** [comment]
> فقط کافیه روش کلیک کنید

تغییری باید تو تنظیمات تایم زون بدیم؟ ساعت تابستانی بزاریم؟ ریجن عوض کنیم؟ من همشو انجام دادم باز هم بدون تغییر.

**Comment by MHSanaei** [comment]
ساعت تهران
