### ISSUE TITLE
پنل cpu بالا، قطع و اتصال پی در پی

### ISSUE THREAD

**Issue by chakkal9877** [MHSanaei/3x-ui#2180]
سلام وقت بخیر
من اصلا قسمت آیپی لیمیت رو ندارم داخل پنلم
مورد بعدی که، کلا یوزری ندارم خودم دارم استفاده میکنم،یوزرا محدود 10 15 تا درست شده ولی وصل نیست کسی، منتهی چند روزیه سرور کلا cpu میره بالا بیخودی
قطع و وصل میشه از چیه؟

**Comment by chakkal9877** [comment]
![Uploading image.png…]()
ایپی لیمیت نیست 
از چیه؟

**Comment by MHSanaei** [comment]
برید قسمت xray config و برای access log مسیر تعيين کنید بعد از اون iplimit  نمایش داده میشه

**Comment by chakkal9877** [comment]
> برید قسمت xray config و برای access log مسیر تعيين کنید بعد از اون iplimit نمایش داده میشه


ممنون ازتون، من اومدم پنل رو به نسخه  پایینتر اوردم دیدم اوکیه هست، اول فکر کردم اشتباه نصب کردمش، دوباره پنلو آپدیت کردم این مسئله اساسی نیست.
دو سه روزی بود که کانفیگ ها 1 مین وصل میشدن، بعدش cpu پنل میرفت بالا 80 کلا قفل میشد بالا، 2 مین کانفیگا قطع بودن دوباره این چرخه ادامه داشت، نمییدونم از چی بود بخاطر چی بوده....
من مجبور شدم کلا سرورو حذف کنم...
فعلا دیگه بالا نیاوردم
ولی میشه راهنمایی کنید که مشکل از چیه که همش قطع و وصل میشه؟
سرور آلمان هتزنر یک هسته ای بود، فقط پنلو آوردم بالا
3 تا اینباند داشت یکی کلادفلر؛ یکی ریلتی یکی هم تانل؛ و روی دامنه nginx زده بودم دامنه پنلو بزنین میرفت صفحه خوشامد گویی nginx
خیلی وقت بود مشکلی نداشت و اوکی بود ولی منتهی این اواخر زیاد قطعی داشت
بات تلگرامی پنل هم زده بودم بهش...
این مشخصات پنل بود خدمتتون عرض کردم
