### ISSUE TITLE
Balancer Strategy not work and not shows

### ISSUE THREAD

**Issue by jahlib** [MHSanaei/3x-ui#2187]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

The Least Load and Least Ping strategies are not functioning at all in the load balancers. Additionally, after the latest update, these strategies are not even displayed when selected in the strategy column. When either of these strategies is chosen, traffic ceases to pass through the load balancer, resulting in clients losing their connection.

![Снимок экрана от 2024-04-02 10-17-11](https://github.com/MHSanaei/3x-ui/assets/60108339/e042df6b-8a9d-4920-b7fb-ab0e3e83257d)
![Снимок экрана от 2024-04-02 10-17-04](https://github.com/MHSanaei/3x-ui/assets/60108339/e418184e-57f6-4e2c-90d7-6ce48b855b2f)

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MatinHQ** [comment]
Did you find any solution for that?
