### ISSUE TITLE
محدودیت ای پی

### ISSUE THREAD

**Issue by hossiit** [MHSanaei/3x-ui#2188]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام ip limit کار نمیکنه x-ui نصب کردم و لاگ اکسسز دادم لاگ میزنه ای پی نمایش میده اما مسدود نمیکنه
همه کاربر ها این مشکل دارن ممنون میشم رفع کنید

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by hossiit** [comment]
سلام خیلی وقت کار نمیکنه مشکل از شما نیست

**Comment by MHSanaei** [comment]
مشکلی وجود ندارد
