### ISSUE TITLE
از کار افتادن سابسکریپشن درآپدیت جدید

### ISSUE THREAD

**Issue by mohammadrew1365** [MHSanaei/3x-ui#2191]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

با سلام من وقتی آپدیت کردم پنلوبه نسخه 2.6.7 سابسکریپشن از کار افتاد و دیگه ساب کار نیمکرد مجبور شدم پنل برگردونم به نسخه قبلی لطفا این ایراد برطرف کنید !!!!!معکوس عمل میکنید به جای رفع ایرادا قابلیتای قبل از کار میندازید !!

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
اینباند رو یکبار اپدیت کنید مشکل شما حل خواهد شد ساب مشکلی نداره 
بیشتر هم روی خودتون کار کنید تا بتونید درست صحبت کنید
موفق باشید

**Comment by mohammadrew1365** [comment]
به به بلاخره خوندین و جواب دادین یه سوال آقا حسین یا علیرضا از کجا باید اینباند ریست کنم میشه بگید من یه پیشنهاد دادم برای  اینکه بشه چند تا sni توی یک اینباند داشت مثل الان که چند آدرسه کردین توی اکسترنال پروکسی این خیلی میتونه کمک کنه به کاربرا خیلی ممنونم ازتون که پاسخ میدین
