### ISSUE TITLE
Windows version not working

### ISSUE THREAD

**Issue by mmdjvdad** [MHSanaei/3x-ui#2192]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام مهندس ورژن ویندوزی اجرا نمیشه. دیروز تا الان در حال تست روی سیستم های مختلف هستم و جواب نگرفتم. اجرا میشه و یه صفحه cmd میاد و سریع بسته میشه. پیش نیازی داره که باید نصب کنم؟ vcredist, nfw, go اینا رو تکمیل دارم و پورتش هم باز کردم.
os windows 11 pro, windows server 2022, windows server 2019, win 10 pro.

### Version of 3x-ui

2.2.7

### x-ui log reports or xray log

(0x7ff6c6224ee0,0xc00097da20)
2024/04/02 13:07:23 x-ui 2.2.7
(0x7ff6c6224ee0,0xc00097ddc0)
2024/04/02 13:07:23 ERROR - location <Asia/Tehran> not exist, using default location: Asia/Tehran
2024/04/02 13:07:23 unknown time zone Asia/Tehran

**Comment by mmdjvdad** [comment]
درست شد go رو آپدیت کردم

**Comment by MHSanaei** [comment]
نیازی به go نداره مشکل از time zone هست که روی تهرانه

**Comment by silenceleaf** [comment]
I have the same issue

**Comment by mmdjvdad** [comment]
> I have the same issue

Update go language
