### ISSUE TITLE
  قابلیت چند کانفیگ برای هر یوزر  

### ISSUE THREAD

**Issue by mohammadreza1997** [MHSanaei/3x-ui#2194]
**Is your feature request related to a problem? 
جلوگیری از سردرگمی برای ساخت یوزر و اینباند های متعدد برای هر نفر 
هر اینباند با نام مشخص و تک پورت : چند کاربر » هر کاربر : چند پروتوکل اتصال با uuid یکسان » یک لینک سابسکریشن برای هر کاربر

**Describe the solution you'd like**

یک اینباند با یک پورت و هر یوزر چند کانفیگ 
مانند پنل sui یا مرزبان  یک یوزر ساخته بشه و چند کانفیگ ساخته میشه برای هر نفر اما زیر مجموعه یک اینباند که هر اینباند یک پورت به هر یوزر اختصاص بده 

**Additional context**
یک کانفیگ اطلاعات روی هر لینک سابسکریشن قرار بگیره و روز و حجم رو نمایش بده بجای نمایش روی هر اکانت + یک کانفیگ اطلاعات برای نمایش یک پیام متغیر خوش آمد گویی و ... با قابلیت تنظیم پیام دلخواه یا ثابت...
یا
یک صفحه وب با پورت جداگانه از پورت پنل برای نمایش گرافیکی مقدار روز حجم یا پیام دلخواه یا متغیر برای هر کاربر

ممنون میشم این قابلیت اجرا بشه تا پنل مرتب تری داشته باشیم.
چون درخواست خیلیاست ممنون میشم اقدام کنید اقای سنایی عزیز حد اقل از جناب علیرضا کمک بگیرید ♥️

**Comment by Sia7ash** [comment]
دقیقا این یکی از بزرگترین خواسته ها از روز اول روی پنل سنایی هست
ممنون میشم اگه اضافه بشه
