### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by castell0riz0n** [MHSanaei/3x-ui#2196]
Hello, I’ve noticed the recent release of a Windows distribution on this GitHub repository. Could you please provide more details or documentation regarding the Windows version included in this distribution?

**Comment by mmdjvdad** [comment]
here is what I've found in several days working with 3x-ui windows version and x-ui windows from somebody else
3xui.exe file should run in a windows server VPS. should put the 3xui.exe file and xray.exe file in firewall to allow the connection and you should open the ports in firewall. 3xui.exe file should be open all time and you should put it in startup folder. I've couldn't find any way to run x-ui command to edit the xray and change any thing. there is no way to install Fail2ban for user connection control. fake and original certificates can be used for configs (not panel) but you should do ( Allow insecure = on) in configs but somehow you should get certs yourself.

**Comment by castell0riz0n** [comment]
Thanks for your detailed description

 For those who don't know how to run the Windows distro
 Install the Go v1.22 or later in your Windows VPS
 Copy the files to a safe Folder in your Windows
Run 3x-ui.exe as administrator

Create an IIS website and set the directory of the site to the safe 3x-ui.exe folder. add binding name for example ui.yourdomain.com

Download and run win-acme in your Windows server and follow the steps to get a certificate for your domain for free.

Install these IIS modules: URL-Rewrite and ARR (Application request routing v3)

Restart IIS using iisreset in the Windows CMD and then open IIS manager. find and click on your xui site that was created previously and open the URL Rewrite of the selected application. click on add a new rule and then add a new reverse proxy rule. In the opened dialog enter localhost:2053 and check Enable SSL offloading and press the OK button.

Now open your domain (https://ui.yourdomain.com) in another device and everything is working.

please keep in mind if you restart your windows you should run 3x-ui.exe again manually. so add this file to the startup of Windows to solve this problem

in my tests, if you enable the access.log file x-ray will crash and you should restart 3x-ui.exe
if you use Win-Acme to generate an SSL certificate you don't need a certificate file to add to your panel

**Comment by silenceleaf** [comment]
I got the following error when run on windows:

`
(0x7ff695188820,0xc000a03ae0)
2024/05/23 20:26:28 x-ui 2.3.3
(0x7ff695188820,0xc000a03c60)
2024/05/23 20:26:28 ERROR - location <Asia/Tehran> not exist, using default location: Asia/Tehran
2024/05/23 20:26:28 unknown time zone Asia/Tehran
`

**Comment by mmdjvdad** [comment]
> I got the following error when run on windows:
> 
> ```
> (0x7ff695188820,0xc000a03ae0)
> 2024/05/23 20:26:28 x-ui 2.3.3
> (0x7ff695188820,0xc000a03c60)
> 2024/05/23 20:26:28 ERROR - location <Asia/Tehran> not exist, using default location: Asia/Tehran
> 2024/05/23 20:26:28 unknown time zone Asia/Tehran
> ```

Install go language in windows server. V 1.23 or later
