### ISSUE TITLE
some small bugs

### ISSUE THREAD

**Issue by echo-333** [MHSanaei/3x-ui#220]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

مشکل در کار کردن start after first use
نشان دادن تمام اکانت های پاک شده در قسمت اکانت های غیر فعال در بالای صفحه
این توضیح رو هم بدم که دیتابیش از پنل اسدی کپی شده

### Version of 3x-ui

version 1.21

### x-ui log reports or xray log

@

**Comment by MHSanaei** [comment]
راه حل ساده و درستش اینه که با برنامه https://sqlitebrowser.org/ دیتابیس رو ویرایش کنید و یوزر هایی رو که داخل پنل نیستن ولی در دیتایس هستن رو حذف کنید
