### ISSUE TITLE
ارور 403 گوگل

### ISSUE THREAD

**Issue by hunter-xyz** [MHSanaei/3x-ui#2201]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

درود و تشکر از جناب مهندس عزیز

در مورد پنل یه مشکلی دارم لطفا محبت بفرمایید راهنمایی یا در صورت وجود ایراد از پنل رفع عیب بفرمایید 
پنل رو نصب میکنم همه چیز دیفالت و یه کانفیگ میسازم بهش وصل میشم براحتی میتونم یوتیوب و ... را باز کنم ولی گوگل باز میشه هر چیزی بزنی سرچ کنی ارور 403 میاد یا مخصوصا ai.google باز نمیشه و ارور 403 را میده :
![image](https://github.com/MHSanaei/3x-ui/assets/142353771/b078568e-3d8b-4692-9ce9-9255b2f3123b)

حالا میرم تگ ipv4 برای گوگل رو فعال میکنم : 
![image](https://github.com/MHSanaei/3x-ui/assets/142353771/09cd4567-9c96-4b60-b61a-413a3c4b8432)

حالا سرچ گوگل درست میشه ولی ai.google همچنان مشکل داره و اگر این باز نشه زمانی که ریکاوری اکانت بخوای استفاده کنی و کدی که روی گوشی ارسال میشه که ببین و بزنی برای ریکاوری ، اون کد نمیاد روی گوشی ...

حالا میرم همین تگ رو خاموش میکنم و توی قسمت کد های پنل فقط میزنم google.com : 

![image](https://github.com/MHSanaei/3x-ui/assets/142353771/17639422-4e77-4c04-aaa3-2219b583f33c)

الان سرچ گوگل اوکی هست و محتوا میاره و 403 نمیده و همچنین ai هم کار میکنه براحتی 

ولی یوتیوب بعضی وقتها که ترافیک نا متعارف از ip سرور شناسایی میکنه یه کپچا میاره که ببینه ربات هستی یا نه اون نمیاد که تیک بزنی رد بشی ویدیو بیاد ...  که مجبور شدم خط بعدی هم بزارم که این مشکل هم رفع شد خوشبختانه 

ولی تقاضا دارم این مورد رو بررسی کنید که چه چیزی تو geoip:google هست که وقتی این رو بزاریم تو تگ ipv4 سایت ai.google کار نمیکنه و ارور 403 میده ... 

ضمنا از طریق ربات اگر کاربری به اکانت معرفی کنیم ایدی تلگرام رو وارد اکانت میکنه ولی یک کاراکتر اسپیس میندازه ته شماره و برای همین ربات برای کاربر کار نمیکنه تا دستی بری اون فاصله رو پاک کنی تا درست بشه .

سپاس از محبت شما مرد بزرگ

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by hunter-xyz** [comment]
سپاس بابت اپدیت جدید 2.2.8
 مشکل ربات تلگرام رفع شد ولی مشکل ai.google هنوز برطرف نشده با روشن کردن ipv4 routing  و باید خاموش باشه و دستی google.com رو تو تگ مربوطه بزنم

**Comment by MHSanaei** [comment]
این مورد به پنل مربوط نمیشه
