### ISSUE TITLE
Add TOTP 2FA Option

### ISSUE THREAD

**Issue by Defenderdeath** [MHSanaei/3x-ui#2202]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to add 2FA option to my 3x-ui web panel. TOTP (Google Authenticator or any other app will be much more useful, than token.

**Describe the solution you'd like**
Please add option to enable 2FA on web panel using any TOTP app (Google Authenticator, Authy, Apple iCloud Keychain, 1Password, etc).

**Describe alternatives you've considered**
SMS 2FA is not very secure, secret token is not very useful.

**Additional context**
No.

**Comment by obervinov** [comment]
Hi!
Is this feature already available? How can I configure it?
I can't find it in the user interface settings.
