### ISSUE TITLE
مسدود کردن ایپی و دامنه های ایران

### ISSUE THREAD

**Issue by biggod01** [MHSanaei/3x-ui#2203]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام خوبین شما خدا قوت
جدیدا سایت هایی مثل اپارات اسیاتک و چند سایت دیگه از لیست سایت های ایرانی خارج شدن و با وجود اینکه تیک مسدود کردن رو فعال میکنیم باز کماکان باز میشن
فکر مینم تغییراتی در سرور هاشون ایجاد کردن که در لیست ایپی های بلاک ما نباشن
لطفا بخش مسدود کردن کشور هارو اپدیت کنید

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
تست شد اپارات در لیست بلاک موجود هست و مشکلی در رابطه با بلاک نشدن وجود ندارد
در صورتی که مشکل دارید لطفا نسخه اخر رو نصب کنید سپس یکبار دکمه reset to default  رو بزنید که تنظیمات قدیمی شما حذف شود سپس مجدد تنظيمات رو انجام بدید( به هیچ عنوان از لیست های قدیمی و متفرقه داخل تنظیمات ادونس قرار ندید)

**Comment by biggod01** [comment]
انجام دادم reset to default هم انجام دادم مجدد ست کردم اوکی نشد
![image](https://github.com/MHSanaei/3x-ui/assets/165535721/47520c94-fbdf-46b1-8c6b-498acf6d4164)
