### ISSUE TITLE
Error 500 in subscription after update to 2.2.8

### ISSUE THREAD

**Issue by zoheirkabuli** [MHSanaei/3x-ui#2204]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

After updating to version 2.2.8, a 500 error is displayed when receiving a subscription
![Screenshot 2024-04-03 004015](https://github.com/MHSanaei/3x-ui/assets/56550780/13c33460-6438-4a46-84d1-b61421722e87)

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by meta-syfu** [comment]
json is OK but subscription goes error even by reverse proxy

**Comment by Parsam1989** [comment]
برای من هم با بروزرسانی اینباند و حتی تغییر آدرس های ساب و استفاده بدون دامنه هم مشکل حل نشده

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/2184#issuecomment-2030799607
