### ISSUE TITLE
قطع ارتباط در نسخه های 2.2.7 و 2.2.8

### ISSUE THREAD

**Issue by ma-amjadian** [MHSanaei/3x-ui#2205]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

بعد از آپدیت به نسخه 2.2.7 و 2.2.8 ارتباط قطع می‌شه. پیام EOF در v2ray دریافت می‌کنم.
توضیح شاید لازم: از تانل معکوس استفاده می‌کنم.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Arman-nsb** [comment]
مشکل از ورژن xray-core 1.8.10 هست. تو پنل این ورژن رو به 1.8.9 تغییر بده مشکل حل میشه.
