### ISSUE TITLE
tls handshake error

### ISSUE THREAD

**Issue by Alphfaa** [MHSanaei/3x-ui#2206]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

tls handshake error from آی پی فلان
اساتید محترم.
خیلی وقته این مشکلو دارم باعث میشه کانکشن زود زود قطع بشه اگه راهنمایی کنید ممنون میشم.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by mamrezu** [comment]
منم این مشکلو دارم، من از تونل استفاده میکنم . Vless tls ws,
