### ISSUE TITLE
کار نکردن دریافت آمار کاربر+مشکل بالانسر 

### ISSUE THREAD

**Issue by kalilovers** [MHSanaei/3x-ui#2210]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام و خسته نباشید

دوتا مورد وجود داره توی ورژن جدید 
مورد اول / دریافت آمار کاربر کار نمیکنه و با وجود ثبت آیدی عددی پیام پیکربندی شما یافت نشد رو میده .

مورد دوم / با اینکه دوتا از اوتباند هارو برای بالانسر تعیین کردم و رولی ساختم که اینباند ها از بالانسر رد بشه اما همچنان مابقی اوتباند هاهم (که داخل بالانسر فعال نشده) استفاده میشن (الگورتیم راند رابین) 

### Version of 3x-ui

<details>
2.2.8
```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
مشکلی مشاهده نشد

**Comment by kalilovers** [comment]
> مشکلی مشاهده نشد

درود 
در خصوص ربات ::

![photo_2024-04-03_11-03-09](https://github.com/MHSanaei/3x-ui/assets/30160766/2a62d46b-9531-423c-b1ca-cb41657ead6d)
![photo_2024-04-03_11-03-08](https://github.com/MHSanaei/3x-ui/assets/30160766/0fa9c22a-2d5b-4011-8379-3995e3d72750)

بعد از اپدیت به اخرین نسخه .

در خصوص بالانسر هم تو نسخه جدید که مشکل تگ بالانسر حل شد بعد تغییر نام بالانسر و اوتباند ها موردی که گفتم حل شد فقط ربات مشکلش داره

**Comment by MHSanaei** [comment]
مشکل از سمت شماست بات مشکلی ندارد
![Screenshot_20240403_113333_Telegram.jpg](https://github.com/MHSanaei/3x-ui/assets/33454419/e0c055e4-1071-402a-af53-a3915082956f)
