### ISSUE TITLE
چگونه می‌توان آیدی این باندها را دوباره ریست کرد

### ISSUE THREAD

**Issue by madar54** [MHSanaei/3x-ui#2213]
با سلام مجدد خدمت بزرگان عرصه پنل سنایی متاسفانه ما هر سوالی داریم کسی جوابگوی ما نیست لا به چه دلیل جواب نمی‌دهید یا وقت ندارید یا به کاربران اهمیت نمی‌دهید
![id](https://github.com/MHSanaei/3x-ui/assets/153379079/b395c99f-2b03-4108-b276-e1f374a1ae18)

**Comment by armia84** [comment]
> با سلام مجدد خدمت بزرگان عرصه پنل سنایی متاسفانه ما هر سوالی داریم کسی جوابگوی ما نیست لا به چه دلیل جواب نمی‌دهید یا وقت ندارید یا به کاربران اهمیت نمی‌دهید
> ![id](https://github.com/MHSanaei/3x-ui/assets/153379079/b395c99f-2b03-4108-b276-e1f374a1ae18)
> 

سلام
یکی از راهاش اینه که
میتونید با نرم افزار های ویرایش دیتابیس مثل DB Browser ویندوز و SQLite اندروید این کار رو انجام بدید… اول با یکی از نرم افزار های مرتبط وارد فایل x-ui.db بشید و تیبل inbounds رو انتخاب کنید
بعدش میتونید مقدار id رو تغییر بدید
![Screenshot_20240403_141243_Sqlite Master Pro2.jpg](https://github.com/MHSanaei/3x-ui/assets/146179986/dc81180f-fd51-4b8a-aea2-1778929589f8)

راه دومش اینه که از اینباندتون خروجی بگیرید و وارد پنل جدیدش کنید (یا پنل فعلی رو حذف و نصب کنید)
![20240403_141918.jpg](https://github.com/MHSanaei/3x-ui/assets/146179986/91653ee2-01c1-421f-aba8-e47bd9a208f6)

**Comment by madar54** [comment]
با سلام مجدد راه دومی که فرمودید از پنل خروجی بگیرم و دوباره وارد کنم این کار را انجام دادم ولی دوباره این باندهای قبلی در پنل ست گردید  پنل را نیست حذف و نصب مجدد کردم ولی باز هم این باندهای قبلی موجود می‌باشد

**Comment by armia84** [comment]
> با سلام مجدد راه دومی که فرمودید از پنل خروجی بگیرم و دوباره وارد کنم این کار را انجام دادم ولی دوباره این باندهای قبلی در پنل ست گردید  پنل را نیز حذف و نصب مجدد کردم ولی باز هم این باندهای قبلی موجود می‌باشد

درود
بله درست میگید من دقت نکرده بودم ولی بازم قابل ویرایش هست
میتونید روش اول رو انجام بدید

یا اینکه در روش دوم خروجی‌تون رو ویرایش کنید
![Screenshot_20240403_164533_Chrome.jpg](https://github.com/MHSanaei/3x-ui/assets/146179986/f79a1a0e-d100-4b5c-a57f-8beed13e0fd5)

همین قسمت id رو میتونید تغییر بدید
طبق این فکر کنم نیازی به حذف و نصب پنل نیست
ولی حتما اینباند رو بعد از کپی کردن، حذف کنید
چون پورت و آیدی مشابه باعث ارور میشه
