### ISSUE TITLE
ربات تلگرام Get Usage

### ISSUE THREAD

**Issue by armia84** [MHSanaei/3x-ui#2214]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

تو آخرین ورژن (2.2.8) وقتی کاربرا رو Get Usage ربات پنل کلیک میکنن ربات جواب میده که آیدیتون داخل پنل ثبت نشده! در صورتی که آیدی به درستی وارد شده ولی انگار ربات، به آیدی کلاینت دسترسی نداره

### Version of 3x-ui

2.2.8

### x-ui log reports or xray log

Your configuration is not found!
Please ask your admin to use your Telegram ID in your configuration(s).

Your User ID: xxxxxxxxxx

**Comment by promise601** [comment]
سلام
دقیقا درست هست و متاسفانه کاربرها امکان مشاهده صورت وضعیت کانکشن خودشون رو ندارند. در صورت امکان این مورد را بررسی بفرمایید. با تشکر

**Comment by MHSanaei** [comment]
نسخه اخر رو مجدد نصب کنید

**Comment by armia84** [comment]
> نسخه اخر رو مجدد نصب کنید

سلام ممنون بابت زحمتتون ولی متاسفانه همچناین همین مشکل وجود داره

**Comment by promise601** [comment]
> نسخه اخر رو مجدد نصب کنید

سلام - مجدد بروز رسانی انجام شد - ولی مشکل همچنان پا برجاست
