### ISSUE TITLE
Custom parameter for queries like streisand and v2box

### ISSUE THREAD

**Issue by bjerfan** [MHSanaei/3x-ui#2215]
Fragment lately have been real popular, on android and v2rayNG subscription link works fine and everything works well, but on iOS, subscription links either as normal or json dont work well, Applications like streisand or v2box have added custom query in link for different properties to be added on the config, for example, for fragment on streisand you have to add "vless://id@ip:port?security=tls&...&fragment=50-150,50-150,tlshello#Name" example for fragment query (fragment=length,interval,packet). But for example v2box has a different query it goes by "fragment=packets,lenght,interval" and there is more properties that can be changed only from link and custom queries. Having an option for custom queries and adding different parameters to subscription link is really helpful for the community.  And another thing needed to be said, Sub link (normal sub not json) isnt working after 2.2.7, SubJSON is working fine but normal sub is not working <3 Thanks for you time

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/2184#issuecomment-2030799607
