### ISSUE TITLE
مشکل از کار افتادن  کانفیگ ها  برای کاربرهای قبلی  

### ISSUE THREAD

**Issue by mohammadrew1365** [MHSanaei/3x-ui#2218]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام درود و عرض خسته نباشید مشکل ساب حل شده ولی کانفیگ ها برای خیلی از یوزرها از کار افتاده اینکه بخواهی ریست کنی هر اینباند و مجدد کانفیگ به کاربرها بدیم واقعا برای کسایی که تعداد کاربر بالا دارند واقعا سخته لطفا این مشکل حل کنید که نیاز به ری استارت اینباندها و یا دادن کانفیگ جدید یا ساب به کاربرا نباشه من از روی ناچاری برگشتم به نسخه قبلیم  

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
تغییرات جدید در هر پروتکل نیاز به اپدیت اون اینباند هست راه دیگه ای هم نیست 
موفق باشید
