### ISSUE TITLE
Wireguard 127.0.0.1:62789: connect: connection refused

### ISSUE THREAD

**Issue by newman222** [MHSanaei/3x-ui#2219]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

درود

سرویس وایگارد رو راه اندازی کردیم
تقریبا 300 تا یوزر جمع کردیم
یه باگی که وجود امده اینه که بعد از ریستارت یه ارور عجیبی توی پنل می افته به این شرح : 
2024/04/02 17:28:14 WARNING - X-UI: get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:62789: connect: connection refused"

اپگرید و دانگرید کردم نشد

حتی بکاپ گرفتم و روی یک پنل دیگه ریستور کردم باز همین ارور میده

تنها شانسی که آوردم این بود یه اسنپ شات داشتم ریستور کردم و دونه دونه مجدد inbund ها رو ایمپورت کردم
مجدد سرور ریبوت کردم و این ارور دوباره اومد

### Version of 3x-ui

<details>

```console
# 2.2.6
# 2.2.7
# 2.2.8

```

</details>

### x-ui log reports or xray log

<details>

```console
# 2024/04/02 17:28:14 WARNING - X-UI: get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:62789: connect: connection refused"
2024/04/02 17:28:04 WARNING - X-UI: get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:62789: connect: connection refused"
2024/04/02 17:27:54 WARNING - X-UI: get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:62789: connect: connection refused"
2024/04/02 17:27:44 WARNING - X-UI: get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:62789: connect: connection refused"
2024/04/02 17:27:38 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/04/02 17:27:37 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/04/02 17:27:34 WARNING - X-UI: get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:62789: connect: connection refused"
2024/04/02 17:27:24 WARNING - X-UI: get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:62789: connect: connection refused"
2024/04/02 17:27:14 WARNING - X-UI: get xray traffic failed:rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:62789: connect: connection refused"
```

</details>

**Comment by armia84** [comment]
سلام
تو تنظیمات xray بخش Advanced تگ inbound مقدار آیپی لوکال 127.0.0.1 رو به آیپی 0.0.0.0 تغییر بدید احتمالا مشکل حل شه
