### ISSUE TITLE
ذخیره فعالیت های کلاینت ها

### ISSUE THREAD

**Issue by mohamadn69** [MHSanaei/3x-ui#2220]
سلام بابت زحمت هایی که میکشید ممنونم. من از پنل شما برای استفاده کارکنان سازمان استفاده میکنم. بخاطر برخی مسائل باید لاگ استفاده کاربرام را ذخیره کنم. فایل access.log n حدود 17 کیلو بایت که میشه پاک میشه . امکانش هست فایل بصورت روزانه یا جای دیگه مثلا لاگ سرور ذخیره بشه؟

**Comment by MHSanaei** [comment]
You can use v2.2.1 or switch to alireza0/x-ui panel
