### ISSUE TITLE
پابرجا بودن مشکل ربات

### ISSUE THREAD

**Issue by StayAway32** [MHSanaei/3x-ui#2221]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Telegram Get Usage
سلام و خسته نباشید
حتی بعد از آپدیت امروز بعد از ظهر باز هم مشکل Not Found ‌پابرجا هست و حل نشده اگر ممکنه بررسی کنید با تشکر

### Version of 3x-ui

2.2.8

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
مشکلی مشاهده نشد
