### ISSUE TITLE
Trojan + XTLS/REALITY

### ISSUE THREAD

**Issue by NativitY996** [MHSanaei/3x-ui#223]
**با درود** و خسته نباشید خدمت شما و تشکر از زحمات شما در جهت بهبود پنل

   از آنجایی که پروتکل **تروجان/Trojan** در بیشتر کلاینت‌ها (**Clash**, OneClick and Others) بخوبی پشتیبانی میشه و عملکرد خوبی هم در دور زدن فیلتر داره و به نظر میاد ترکیب اون میتونه با **REALITY** بهترشم کنه، در صورت تمایل و امکان، این ویژگی به پنل اضافه بشه.

- for exm:
https://github.com/qist/xray-ui/releases/tag/1.8.1

**Comment by misagh72** [comment]
https://github.com/MHSanaei/3x-ui/pull/214
