### ISSUE TITLE
مشکل ارور null هنگام وارد کردن QR از طریق گالری

### ISSUE THREAD

**Issue by dani96102** [MHSanaei/3x-ui#2249]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

با سلام
متاسفانه در آپدیت های جدید شکل QR های خروجی تغییر کرده و جوری شده که هنگامی که ازش عکس گرفته میشه و میخوایم از طریق گالری اون وارد برنامه کنیم ارور null میده و اون نمیخونه
هنگام اسکن با دوربین اما مشکلی نداره و فقط از هنگام وارد کردن عکس از طریق گالری این مشکل پیش اومده
قبلا همچین اشکالی وجود نداشت
البته من تمام نوع کانفیگ هارا تست نکردم اما برای ریلیتی یا ws که دارم این مشکل پیش اومده
حالا نمیدونم مشکل از طریق پنل قابل حله یا مشکل به هسته ایکس ری مربوط میشه
اما خب در اپدیت های جدید پنل این مشکل ایجاد شده.
من همیشه از اخرین ورژن و تغییرات استفاده میکنم
![Screenshot_20240510_040201_v2rayNG](https://github.com/MHSanaei/3x-ui/assets/68426583/323233bf-4c83-4d8c-8011-b559f4077ccb)

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
تست شد مشکلی مشاهده نشد
