### ISSUE TITLE
غیر فعال شدن ساب‌اسکریپشن بعد از اپدیت

### ISSUE THREAD

**Issue by vR3za** [MHSanaei/3x-ui#2252]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام وقت بخیر
فکر میکنم از ورژن  2.6.6 به بعد لینک های ساب اسکریپشن دیگه کار نمیکنه این مشکل منه یا بقیه هم همینطوری هستند ؟ 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
سلام
لطفا اینباند مد نظر رو بدون هیچ تغییری اپدیت کنید
یعنی دکمه ادیت رو بزنید و اپدیت کنید مشکل شما حل خواهد شد

**Comment by asghar61** [comment]
سلام . همچنان این مشکل هست . لینک ساب اوکی میشه منتهی تو v2rayng سرویس استارت نمیشه

**Comment by MHSanaei** [comment]
@asghar61
 معمولا وقتی ورژن برنامه پایین هست این اتفاق میفته
نسخه اخر رو‌نصب کنید و سپس ساب رو اپدیت کنید

**Comment by asghar61** [comment]
نسخه آخر نصب شده - همه گزینه ها آپدیته . ولی کانفیگ جیسون خود پنل کار نمیکنه یا در مواردی اصلا اضافه نمیشه - تو گوشی خودم درسته گوشی مشتری اینجوریه . ساب معمولی درسته فقط جیسون اینجوریه

**Comment by MHSanaei** [comment]
مشکل از سمت مشتری شما هست نه پنل
