### ISSUE TITLE
رد نشدن ترافیک برنامه تیک تاک از وارپ

### ISSUE THREAD

**Issue by softmaj7** [MHSanaei/3x-ui#2254]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

**درود خدمت همه دوستان
بصورت دستی تیک تاک رو اضافه میکنم از وارپ رد نمیشه و حتی تیو اینباند اضافه میکنم بازم برنامه تیک تاک کار نمیکنه
میدونم خیلیامون از این مشکل اذیتیم اگه کسی راه حلی داره لطفا دریغ نکنه
ممنون میشم راهنمایی کنید** 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by armia84** [comment]
سلام
من نمیدونم شما چجوری واردش کردید و واسه تیک تاک و یا چند سایت وارپ نزدم فقط
ولی قطعا geosite همیشه کامل نیست و ممکنه ی سری از دامنه ها رو شامل نشه

واسه اینکه بتونید از وارپ ردش کنید بهتره کل ترافیک و یا فقط کل دامنه ها رو با استفاده از
regexp:.*
از وارپ عبور بدید

**Comment by mohamadm0meni** [comment]
> ### Welcome
> * [x]  Yes, I'm using the latest major release. Only such installations are supported.
> * [x]  Yes, I'm using the supported system. Only such systems are supported.
> * [x]  Yes, I have read all WIKI document,nothing can help me in my problem.
> * [x]  Yes, I've searched similar issues on GitHub and didn't find any.
> * [x]  Yes, I've included all information below (version, config, log, etc).
> 
> ### Description of the problem,screencshot would be good
> **درود خدمت همه دوستان بصورت دستی تیک تاک رو اضافه میکنم از وارپ رد نمیشه و حتی تیو اینباند اضافه میکنم بازم برنامه تیک تاک کار نمیکنه میدونم خیلیامون از این مشکل اذیتیم اگه کسی راه حلی داره لطفا دریغ نکنه ممنون میشم راهنمایی کنید**
> 
> ### Version of 3x-ui
> ### x-ui log reports or xray log

سلام دوست عزیز این مشکل به خاطر سیاست برنامه v2rayng هست و ای پی شما رو هنگام استفاده از تیک تاک تغییر نمیدهد چون تیک تاک و v2rayng هر دو برای کشور چین هستند حتی داخل issue خود برنامه v2rayng نگا کنید به وضوح مشخص است و این مشکل همگانی است برای رفع مشکل از برنامه ای غیر از v2rayng مانند nekobox  یا نپسترنت استفاده کنید
