### ISSUE TITLE
تست شد مشکلی مشاهده نشد

### ISSUE THREAD

**Issue by dani96102** [MHSanaei/3x-ui#2255]
تست شد مشکلی مشاهده نشد

_Originally posted by @MHSanaei in https://github.com/MHSanaei/3x-ui/issues/2249#issuecomment-2104779597_
            
من لینک کانفیگ و عکس QR واستون میفرستم لطفا چک بفرمایید تا بفهمیم مشکل چیه...چون هیچ مشکلی برای اسکن با دوربین وجود نداره اما وقتی از طریق گالری میخوایم وارد کنیم QR رو ارور میده...من با برنامه  v2box چک کردم مشکلی نداشت اما داخل برنامه های v2ray روی اندروید و کامپیوتر مشکل داره. مسئله رو با گیت هاب سازنده برنامه ها و هسته مطرح کردم درخواست کردن نمونه واسشون بفرستم برای شما هم میفرستم لطفا چک بفرمایید که مشکل پیدا بشه🙏🏻
من دوتا پنل دارم و هردوتاش کانفیگاش همین مشکل داخل خوندن QR ها از طریق گالری داره و همچی هم ریست کردم اما باز مشکل حل نشد

vless://ff0951ee-6ddd-4d56-b2a7-52848139dfc2@us.vpnetpro.com:2030?type=grpc&serviceName=&authority=&security=reality&pbk=sHEjew9Cl7YL7f2PWVPNFQoL8Skh4uJEwYJVvXqlDgA&fp=firefox&sni=discord.com&sid=1d73b7a5&spx=%2F#QR-Test-ecqo6qcp

![Screenshot_20240511_164954_Firefox](https://user-images.githubusercontent.com/68426583/329785468-7ada972e-52c0-4f86-b99a-bba26efe8d39.jpg)

**Comment by dani96102** [comment]
![Screenshot_20240511_164954_Firefox](https://github.com/MHSanaei/3x-ui/assets/68426583/64e0ab06-451f-46b4-9a44-fc4ac2342a75)

**Comment by MHSanaei** [comment]
مشکل از سمت برنامه v2rayng هست شما اگر تم پنل رو عوض کنید ساده باشه شناسایی میکنه ولی مود دارکش رو ساپورت نمیکنه
موفق باشید
