### ISSUE TITLE
مشکل اتصال به پنل(x-ui)

### ISSUE THREAD

**Issue by Daviid19976** [MHSanaei/3x-ui#2257]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام خسته نباشید 
از سرور های هتزنر استفاده میکنم
زمانی که از سرور (falkenstein و nuremberg و helsinki ) برای راه اندازی پنل استفاده میکنم بعد از پیدا کردن ip تمیز و چک تمامی موارد شروع به نصب پنل میکنم . 
جالبی این مورد اینجا هست من کاملا به سرور متصل هستم و تمامی کار های سرور رو انجام دادم بدون استفاده از وی پی ان . 
ولی بعد نصب کامل پنل زمانی که میخوام وارد پنل بشم پنل رو نمیاره و حتما باید از وی پی ان استفاده کنم .
ولی از سرور های usa استفاده کردم هیچ مشکلی نداشت و بدون وی پی ان وارد پنل میشد .
به نظر شما مشکل کجا هست؟
اگر ای پی فیلتر باشه حتی اجازه نمیده من به سرور وصل بشم . یا داخل پینگ سی ام دی تایم اوت میده .
به نظرتون مشکل کجا هست ؟ 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by soheylshorg** [comment]
سلام!

با توجه به تست های اخیری که انجام دادم این موضوع به درخواست های httpمربوط میشود اوپراتورها درخواست های httpرو مسدود کردن و وقتی شما پنل رو به صورت http باز میکنی درخواست که به سمت سرور ارسال میشه بین راه از طریق اوپراتور مد نظر در ایران مسدود و توسط فایروال پاسخی دریافت نمیکند به همین دلیل ایپی تمیز هست ssh  میخوره اما پاسخی دریافت نمیکند
