### ISSUE TITLE
نشان دادن حجم و زمان مصرفی به یوزر

### ISSUE THREAD

**Issue by aidiin1366** [MHSanaei/3x-ui#226]
سلام وقت بخیر 
با تشکر فراوان از پنل بسیار زیبا و کارآمد شما 
من یه سوال داشتم 
چطور میتونیم به یوزر ها حجم و زمان مصرفی رو داخل خود برنامه مثل v2rayng نشان بدیم ؟

**Comment by aidiin1366** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/130555626/231428483-5b6d5871-5f64-47b8-a35b-12111704623f.jpg)
![photo_۲۰۲۳-۰۴-۱۱_۱۲-۵۹-۲۵](https://user-images.githubusercontent.com/130555626/231428509-90cf0f99-74c0-4ea0-af1b-76cb39cc385b.jpg)

من داخل دوتا برنامه این مورد رو دیدم

**Comment by MHSanaei** [comment]
این امکان وجود نداره مگر اینکه دستی روی لینک های یوزر قسمت remark اسم و حجم رو تعریف کنی که کار جالبی نیست پیشنهاد میشه از بات تلگرام استفاده کنید و تلگرام یوزر هارو به پنل اضافه کنید که راحت بتونن حجم مصرف شده رو تماشا کنند
