### ISSUE TITLE
 مشکل در لینک اشتراک با ارور 500

### ISSUE THREAD

**Issue by rafiee** [MHSanaei/3x-ui#2260]
با سلام
لینک اشتراک این ارور را نشون میده. SSL  از کلودفلر گرفته شده و تنظیمات در پنل اعمال شده:
Update subscription starts
import_sub->Start getting subscriptions
import_sub->Response status code does not indicate success: 500 (Internal Server Error).
import_sub->The remote server returned an error: (500) Internal Server Error.
import_sub->The remote server returned an error: (500) Internal Server Error.
import_sub->Invalid subscription content

علتش چیه ؟

**Comment by amirsadeghi1** [comment]
Edit that inbound and update without any changes,if not fixed share your config link without domain.
