### ISSUE TITLE
راه حلی برای تک کاربره کردن تونل شده

### ISSUE THREAD

**Issue by era1382** [MHSanaei/3x-ui#2261]
سلام اگه امکانش باشه قابلیت limit device connected بزارین خیلی خوب میشه، اینجوری مشکل تک کاربره کردن تونل حل میشه

_Originally posted by @era1382 in https://github.com/MHSanaei/3x-ui/issues/2143#issuecomment-2115785327_

**Comment by lambdaxyzt** [comment]
خب روی ایران تک کاربره کنین نه روی خارج
 به نظرم به ایران به خارج نگید تونل بهتره چون کل کار vpn چه خارج چه ایران تونله

**Comment by armia84** [comment]
کلا از طریق تونل آیپی فوروارد نمیشه محدودیت آیپی برای کانفیگ گذاشت
تنها راهش تونل های پنل به پنل هست (بجز دکودمو دور چون اونم آیپی فوروارده)

**Comment by lambdaxyzt** [comment]
چرا میشه ولی نمیدونم ایران به خارج رو با چه ابزاری میفرستید یه چیزی هست به نام proxy protocol که آپشنش سمت xray باید کانفیگ بشه و سمت ایران هم باید proxy protocol رو ساپورت کنه که بفرسته

**Comment by lambdaxyzt** [comment]
به Reverse TLS Tunnel هم پیام دادم ولی نفهمید مثل اینکه که پیاده سازی کنه

**Comment by armia84** [comment]
تونل از طریق xray انجام بشه، آیپی لیمیت هم بدون مشکل کار میکنه

**Comment by MHSanaei** [comment]
برای موضوع تکراری issue باز نکنید
راه حل پنل به ‌پنل 
یوزر روی سرور ایران ساخته بشه
و تانل از نوع outbound روی سرور ایران قرار بگیره
