### ISSUE TITLE
Telegram Bot

### ISSUE THREAD

**Issue by ExAsfh** [MHSanaei/3x-ui#2265]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

در پیدا کردن کارکتر های دو حرفی مشکل وجود داره

### Version of 3x-ui

2.3.1

### x-ui log reports or xray log

زمانی که میخوام میخواهم /usage را استفاده کنم در کارکتر های دو حرفی مشکل دارد
مثلا وقتی جستجو میکنم حسین سنایی فقط دنبال کلمه حسین میگرده و کلمه سنایی رو برسی نمی کنه 
قبل
![Ghabl](https://github.com/MHSanaei/3x-ui/assets/120527387/9253ba13-af38-4b6a-8d16-ce398159764b)
بعد
![Bad](https://github.com/MHSanaei/3x-ui/assets/120527387/471d4a89-0003-4b82-b7e9-0305ec8d8663)

**Comment by MHSanaei** [comment]
فاصله یا همون space نباید داخل ایمیل باشد
موفق باشید
