### ISSUE TITLE
عدم مسدود سازی تبلیغات یوتیوب 

### ISSUE THREAD

**Issue by behzadti** [MHSanaei/3x-ui#2266]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

الان چند وقتیه تبلیغات یوتیوب با اینکه تو تمام پنل ها Block Ads انجام دادم ولی برای همه پنلهام این مشکل هست که تبلیغات یوتیوب برام نمایش داده میشه. 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/1165#issuecomment-2118981678
