### ISSUE TITLE
عمل نکردن گزینه ها در xray setting

### ISSUE THREAD

**Issue by kharchng** [MHSanaei/3x-ui#2267]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

فقط تو بخش xray settings لامپ ها کار نمیکنند و انگار فقل شدن و نمیشه تغییرشون داد-مثلا میخوام ایپی ایران رو بلاک کنم ولی فعال نمیشه و حتی کزینه ها ی فعال هم غیر فعال نمیشن

### Version of 3x-ui

<details>

```console
# 2.3.1
```

</details>

### x-ui log reports or xray log

<details>

```console
# no need log
```

</details>

**Comment by MHSanaei** [comment]
دکمه reset to default رو یکبار بزنید
