### ISSUE TITLE
نمیشه ورژن دلخواه رو نصب کرد 

### ISSUE THREAD

**Issue by hunter-xyz** [MHSanaei/3x-ui#2268]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

این دستور رو میزنم :
 bash <(curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh) 2.3.0
بعد همچین خطایی میده : 
Download x-ui 2.3.0 failed,please check the version exists

ولی اگر نصب کنی ورژن اخر رو و بعد کاستوم ورژن بزنی نصب میشه ولی ربات ورژن 2.3.0 رو نصب نمیکنه و ربات 2.3.1 انگار نصب هست چون :

ولی متاسفانه ورژن اخر رباتش خرابه استعلام که میگیری هر بار تازه سازی میزنی هی عوض میشه تمدید میزنی 0 میکنی همرو ولی عمل نمیکنه تازه سازی میزنی همرو 0 نشون میده یه بار دیگه تازه سازی میزنی یهو اطلاعات قبل از ریست رو میاره بعد میری رو وب پنل چک میکنی میبینی با اینکه با ربات مثلا تمدید کردی یا حجم زدی یا ریست کردی ولی در عمل روی سرور اعمال نکرده 

ممنون میشم راهنمایی بفرمایید

![image](https://github.com/MHSanaei/3x-ui/assets/142353771/454ea7d8-2028-4bcf-b51f-b323a391cbe0)

https://github.com/MHSanaei/3x-ui/assets/142353771/754625fd-8762-45e4-978a-ba3e98166a57

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by hunter-xyz** [comment]
مشکل رو با ریبیلد سرور حل کردم ولی اون مشکل رو رفع کنید که کاستوم ورژن بشه نصب کرد یه موقع واجب میشه لنگ میمونیم مرسی

**Comment by MHSanaei** [comment]
https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh) v2.3.1

شما v رو قرار ندادید

**Comment by hunter-xyz** [comment]
بله درسته ولی من رفتم از راهنمای خودتون نگاه کردم تا جایی که یادمه و دقت هم کردم v نداشت الان فکر میکنم اصلاحش کردین

به هر حال ممنون از محبت شما مهندس عزیز
