### ISSUE TITLE
Hello, I have set up a routing rule that cannot link to a network with outbound rules

### ISSUE THREAD

**Issue by water2022** [MHSanaei/3x-ui#2269]
Hello, I have set up a routing rule that cannot link to a network with outbound rules
![image](https://github.com/MHSanaei/3x-ui/assets/97374665/f19d7845-ca46-4780-b2d3-bf17edb42c00)
![image](https://github.com/MHSanaei/3x-ui/assets/97374665/620c1ade-d626-4e14-b236-0a3e5d38d15e)
![image](https://github.com/MHSanaei/3x-ui/assets/97374665/7cb9a51f-0b03-449d-bc9c-ec5bde3eaa5c)
![image](https://github.com/MHSanaei/3x-ui/assets/97374665/b61c0d08-7c15-4836-94b9-e2b63be6cdd6)

**Comment by arash88** [comment]
Your Outbound's ID in database (x-ui.db) has another value. Look at Inbound tag in your picture, you need to find the right name from DB.
These fields should be auto-complete of some sort @MHSanaei jan.
