### ISSUE TITLE
grpc reality outband failed

### ISSUE THREAD

**Issue by amirzare021** [MHSanaei/3x-ui#2270]
با سلام و خسته نباشید
من میخوام اوتبند اضافه کنم با کانفیگ vless grpc reality ولی ارور میده
Failed to start: main: failed to load config files: [bin/config.json] > infra/conf/serial: failed to decode config: bin/config.json > infra/conf/serial: failed to read config file at line 1434 char 25 > json: cannot unmarshal string into Go struct field GRPCConfig.outbounds.streamSettings.grpcSettings.multiMode of type bool

باید چیکارش کنم؟

**Comment by seriiix** [comment]
[Here is the fix](https://github.com/MHSanaei/3x-ui/pull/2348)

@MHSanaei
