### ISSUE TITLE
Fail2Ban Installation bug and launching error on Ubuntu 24

### ISSUE THREAD

**Issue by GoldExynos** [MHSanaei/3x-ui#2271]

**Comment by edi900310** [comment]
منم مشکل مشابهی دارم تو عکس پیغام خطا رو گذاشتم
![photo_2024-05-24_04-56-43](https://github.com/MHSanaei/3x-ui/assets/163480277/bba60532-bf1b-45a0-82c7-f84ffba54e8c)

**Comment by naserchaman2138** [comment]
علت

 Fail2Ban به دلیل یک مشکل شناخته شده با پایتون 3.12 ناسازگار است:


Resolution

As a workaround, install pyasynchat:

    Connect to the server via [SSH]
    Install PIP (Package Installer for Python):

1-apt install python3-pip

Install pyasynchat package:

2-python3 -m pip install pyasynchat --break-system-packages

Start Fail2ban service

3-systemctl start fail2ban

**Comment by j-isreal** [comment]
> علت
> 
> Fail2Ban به دلیل یک مشکل شناخته شده با پایتون 3.12 ناسازگار است:
> 
> Resolution
> 
> As a workaround, install pyasynchat:
> 
> ```
> Connect to the server via [SSH]
> Install PIP (Package Installer for Python):
> ```
> 
> 1-apt install python3-pip
> 
> Install pyasynchat package:
> 
> 2-python3 -m pip install pyasynchat --break-system-packages
> 
> Start Fail2ban service
> 
> 3-systemctl start fail2ban

This worked perfectly!  Thank you!

**Comment by naserchaman2138** [comment]
عزیزی

**Comment by Behnamskyy** [comment]
![Screenshot 2024-06-06 231638](https://github.com/MHSanaei/3x-ui/assets/148554892/27599964-edb2-46fe-863d-5126487f751d)

همه دسورات را اجرا کردم اما باز این خطار ومیده
