### ISSUE TITLE
Restarting XRay via Telegram bot

### ISSUE THREAD

**Issue by pr3ci0u5** [MHSanaei/3x-ui#2272]
**Is your feature request related to a problem? Please describe.**
Sometimes XRay just stops working properly, I still don't know why because there's nothing in the logs and it looks like it's just ignoring all incoming packets so I can't connect to any website. A simple restart of XRay always helps in these cases. But I have to go to the Panel, log in, restart. Too many moves for one simple action.

**Describe the solution you'd like**
It would be great if you could add Restart XRay functionality directly to the Telegram Bot

**Describe alternatives you've considered**
I have seen that it is implemented in Marzban's Telegram bot. This feature is very useful, I think

**Additional context**
No additional context

Sent from my iPohne

**Comment by najahiiii** [comment]
working on it.
