### ISSUE TITLE
wireguard tunnel on 6to4 tunnel 

### ISSUE THREAD

**Issue by Hugsyyyy** [MHSanaei/3x-ui#2274]
من با یک تانل 6to4 سرور ایرانمو وصل کردم به میکروتیک و سپس با ایجاد وایرگارد در میکروتیک و ساختن outbount تانل با وایرگار با ipv6 لوکال 6to4 
این outbound را وصل کردن به میکروتیک اما مشکل mtu دارم و بعضی از سایت ها باز نمی شود

**Comment by arash88** [comment]
هم در اینترفیس وایرگارد میکروتیک و هم اوتباند mtu رو بذار 1200.
