### ISSUE TITLE
error in tcp inbound

### ISSUE THREAD

**Issue by mobinmoji** [MHSanaei/3x-ui#2275]
سلام خدمت همگی من از پنل ثنایی استفاده می کنم و وقتی از اینباند مادر و فرزند (مادر tcp و فرزند وب سوکت) حجم مصرفیم روی سرور دو برابر میشه و وقتی از tcp خالی استفاده می کنم به محض این که گزینه proxu کلودفلر رو روشن میکنم سرورم از کار میوفته کسی میتونه کمکی بهم بکنه؟ من سه تا سرور از سه تا ارائه دهنده مختلف و سه تا مکان مختلف استفاده می کنم ولی برای هر سه تا این مشکل رو دارم

**Comment by MHSanaei** [comment]
توصیه میشه چند کلیپ اموزشی در یوتیوب تماشا کنید

**Comment by mobinmoji** [comment]
ممنونم از راهنماییتون من از کلیپ های اقای اقاپور یادگرفتم ساخت این نوع پنل رو ممنون میشم بهم راهنمایی کنید کدوم کلیپ هارو باید ببینم ؟
ببخشید میدونم سرتون خیلی شلوغ و همین که جواب میدیدن نهایت لطف رو در حق من میکنید ولی این رو پرسیدم چون خیلی دنبال راه حلش گشتم ولی نتونستم پیدا کنم راه حلش رو 
بازم ممنون از وقتی که میزارید 


> توصیه میشه چند کلیپ اموزشی در یوتیوب تماشا کنید
