### ISSUE TITLE
از کار افتادن بعضی کاربر ها که قبلا راحت وصل بودن

### ISSUE THREAD

**Issue by mobinmoji** [MHSanaei/3x-ui#2276]
سلام خدمت همگی من سه تا سرور دارم از جاهای مختلف از دو سه روز پیش که رئیسی مرد یهو بدون هیچ دلیلی چند تا از کار برام از ارائه دهنده خدمات تلفن و وای فای مختلف از کار افتادن و دیگه به همون سرور وصل نشدن و باید یه سرور جدید بهشون بدم به نظرتون میشه کاری کرد که مثل قبل ادامه بدن ؟ ایا مشکل از سرورام یا از ارائه دهنده های اینترنت ؟

**Comment by MHSanaei** [comment]
سلام 
جای این سوال اینجا نیست 
موفق باشید

**Comment by mobinmoji** [comment]
ببخشید ولی نمیدونستم کجا میتونم بپرسم اینو برای همین پرسیدم ممنون میشم راهنمایی کنید کجا باید بپرسم
ممنون

**Comment by MHSanaei** [comment]
گروه های تلگرامی

**Comment by mobinmoji** [comment]
> سلام جای این سوال اینجا نیست موفق باشید


ببخشید اگه سوال بدی پرسیدم یا بد جایی پرسیدم ولی چون نمیدونستم باید کجا بپرسم اینجا پرسیدم ممنون میشم اگر لطف کنید یه راهنمایی کنید که این سوالم رو از کجا میتونم بپرسم؟
بازم ممنون از محبتتون و همچنین عذر میخوام اگه بی ادبی کردم

**Comment by mobinmoji** [comment]
> گروه های تلگرامی

ممنون خیلی لطف کردین
