### ISSUE TITLE
QR code is blank

### ISSUE THREAD

**Issue by Ganzolino** [MHSanaei/3x-ui#2279]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

In mozilla Firefox 106.0 , when i call QR-code of users? i have blank squere.
![2024-05-22_114449](https://github.com/MHSanaei/3x-ui/assets/100689638/2d1681dc-d26f-42bb-bf8a-4faf361f71d5)
12

### Version of 3x-ui

<details>

```console
v2.3.1
```

</details>

### x-ui log reports or xray log

<details>

```console
2024/05/22 11:27:07 INFO - X-UI: user1login success
2024/05/22 11:27:06 INFO - X-UI: GanZ login success, Ip Address: 213.108.---.---
2024/05/22 11:26:53 INFO - X-UI: user1logout
2024/05/22 11:26:28 INFO - X-UI: user1login success
2024/05/22 11:26:27 INFO - X-UI: GanZ login success, Ip Address: 213.108.---.---
2024/05/22 11:26:00 INFO - X-UI: user1logout
2024/05/22 11:25:09 INFO - X-UI: user1login success
2024/05/22 11:25:09 INFO - X-UI: GanZ login success, Ip Address: 213.108.---.---
2024/05/22 11:12:01 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/05/22 11:10:45 INFO - X-UI: sub server run http on[::]:2096
2024/05/22 11:10:45 INFO - X-UI: Starting Telegram receiver ...
2024/05/22 11:10:45 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/05/22 11:10:45 INFO - X-UI: Tg notify enabled,run at @weekly
2024/05/22 11:10:45 INFO - X-UI: web server run http on[::]:65500
```

</details>

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/2184#issuecomment-2030799607

**Comment by Ganzolino** [comment]
This is problem only in the Firefox. In the chrome all ok. If I click on the clear square, link copy in the clipboard. Just not image QR-Code.

**Comment by MHSanaei** [comment]
Update your Firefox to the latest version.
I test everything on Firefox; there is no problem.

**Comment by Ganzolino** [comment]
THX update help for me
