### ISSUE TITLE
I don't know which machine the CPU is occupying

### ISSUE THREAD

**Issue by o02** [MHSanaei/3x-ui#228]
![微信截图_20230412200732](https://user-images.githubusercontent.com/38731893/231452550-eef4bfe2-01b9-4b82-a701-5952526ee759.png)
Hope to add IP address or host name for easy positioning

**Comment by MHSanaei** [comment]
@alireza0 :D

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
