### ISSUE TITLE
لیمیت سرعت روی کلاینت یا اینباند

### ISSUE THREAD

**Issue by PouryaDe** [MHSanaei/3x-ui#2281]
Please add Client or inbound Speed Limit 
thanks

**Comment by saeidit1** [comment]
Please add Client or inbound Speed Limit

**Comment by saeidit1** [comment]
قابلیت لیمیت سرعت برای هر کاربر (کلاینت) اضافه کنید
ممنون

**Comment by MHSanaei** [comment]
you need to ask them for this feature
https://github.com/XTLS/Xray-core

**Comment by myxeni64b** [comment]
Hi
Try this -> https://github.com/myxeni64b/xui-bw-guard
