### ISSUE TITLE
Docker update error

### ISSUE THREAD

**Issue by anartikov** [MHSanaei/3x-ui#2282]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![Снимок экрана 2024-05-22 220010](https://github.com/MHSanaei/3x-ui/assets/50944927/a03847ee-fe7e-4ef8-8e23-c5ca1644482a)

### Version of 3x-ui

2.3.1

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by zhouxingwork** [comment]
it's ok. just ignore the waring.

**Comment by anartikov** [comment]
> it's ok. just ignore the warning.

However, the version is not updated to 2.3.3.

**Comment by MHSanaei** [comment]
> cd 3x-ui
>  docker compose down
>  docker compose pull 3x-ui
>  docker compose up -d
