### ISSUE TITLE
Xray crashing with wireguard

### ISSUE THREAD

**Issue by devintly** [MHSanaei/3x-ui#2283]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

xray keep crashing with wireguard confing outbound (i'm using it with warp+)
on 2.3.1 all working fine

### Version of 3x-ui

2.3.3

### x-ui log reports or xray log

golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/device.go:322 +0x44c

**Comment by MHSanaei** [comment]
change your xray version to v1.8.11

**Comment by devintly** [comment]
> change your xray version to v1.8.11

Thanks!
