### ISSUE TITLE
github.com/xtls/xray-core/app/dispatcher/default.go:240 +0x3dc

### ISSUE THREAD

**Issue by Alireza78na** [MHSanaei/3x-ui#2285]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

i got this error after updating panel from 2.3.1 to 2.3.3:
github.com/xtls/xray-core/app/dispatcher/default.go:240 +0x3dc

it fixed after change the xray core version to 1.8.11

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
xray new version bug
