### ISSUE TITLE
مشکل با ارتباط با مخزن github

### ISSUE THREAD

**Issue by mohammadlth** [MHSanaei/3x-ui#2287]
سلام رفقا
من میخوام رو ی سرور ایرانی نصب کنم اما ارور خطای دسترسی میگیرم

Failed to fetch x-ui version, it maybe due to Github API restrictions, please try it later

نمیدونم دقیقا مشکلش چیه نیم سرور ها هم چک کردم و تغییر دادم. !

**Comment by MHSanaei** [comment]
راه حل ساده اینه که فایل نصبی رو دستی دانلود کنید و به صورت ftp به سرور انتقال بدید و دستور نصب دستی رو بزنید
