### ISSUE TITLE
WS Over Cloudflare CDN not working at xray 1.8.10+.

### ISSUE THREAD

**Issue by deepsm0ke** [MHSanaei/3x-ui#2289]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

When I set it to version 1.8.10+,the data from cloudflare is rejected (I put the Server's IP to connect directly in ws config address, it was successfuly connected),I had changed the cloudflare panel settings, nothing happend.
and, once it is empty Host without header Or once with header with empty host or pair them together... didn't work.

Can You Help Plz. Thx

Config : vless ws over cdn , Port 80

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by arash88** [comment]
Try importing this inbound, it should work:

`{
  "id": 19,
  "userId": 0,
  "up": 2035996200,
  "down": 211877840219,
  "total": 0,
  "remark": "vl-cf",
  "enable": true,
  "expiryTime": 0,
  "listen": "",
  "port": 8443,
  "protocol": "vless",
  "settings": "{\n  \"clients\": [\n    {\n      \"email\": \"krjn1vjm\",\n      \"enable\": true,\n      \"expiryTime\": 0,\n      \"flow\": \"\",\n      \"id\": \"bd097c5b-2b7e-455c-9e42-07eb274e146e\",\n      \"limitIp\": 0,\n      \"reset\": 0,\n      \"subId\": \"bmn3uzlo5mzw6dmk\",\n      \"tgId\": \"\",\n      \"totalGB\": 0\n    }\n  ],\n  \"decryption\": \"none\",\n  \"fallbacks\": []\n}",
  "streamSettings": "{\n  \"network\": \"ws\",\n  \"security\": \"none\",\n  \"externalProxy\": [\n    {\n      \"forceTls\": \"same\",\n      \"dest\": \"zula.ir\",\n      \"port\": 443,\n      \"remark\": \"\"\n    }\n  ],\n  \"wsSettings\": {\n    \"acceptProxyProtocol\": false,\n    \"path\": \"/vw2\",\n    \"headers\": {}\n  }\n}",
  "tag": "inbound-9443",
  "sniffing": "{\n  \"enabled\": true,\n  \"destOverride\": [\n    \"http\",\n    \"tls\",\n    \"quic\",\n    \"fakedns\"\n  ]\n}",
  "clientStats": [
    {
      "id": 19,
      "inboundId": 19,
      "enable": true,
      "email": "krjn1vjm",
      "up": 1951725145,
      "down": 211897149900,
      "expiryTime": 0,
      "total": 0,
      "reset": 0
    }
  ]
}`

**Comment by deepsm0ke** [comment]
> Try importing this inbound, it should work:
> 
> `{ "id": 19, "userId": 0, "up": 2035996200, "down": 211877840219, "total": 0, "remark": "vl-cf", "enable": true, "expiryTime": 0, "listen": "", "port": 8443, "protocol": "vless", "settings": "{\n \"clients\": [\n {\n \"email\": \"krjn1vjm\",\n \"enable\": true,\n \"expiryTime\": 0,\n \"flow\": \"\",\n \"id\": \"bd097c5b-2b7e-455c-9e42-07eb274e146e\",\n \"limitIp\": 0,\n \"reset\": 0,\n \"subId\": \"bmn3uzlo5mzw6dmk\",\n \"tgId\": \"\",\n \"totalGB\": 0\n }\n ],\n \"decryption\": \"none\",\n \"fallbacks\": []\n}", "streamSettings": "{\n \"network\": \"ws\",\n \"security\": \"none\",\n \"externalProxy\": [\n {\n \"forceTls\": \"same\",\n \"dest\": \"zula.ir\",\n \"port\": 443,\n \"remark\": \"\"\n }\n ],\n \"wsSettings\": {\n \"acceptProxyProtocol\": false,\n \"path\": \"/vw2\",\n \"headers\": {}\n }\n}", "tag": "inbound-8443", "sniffing": "{\n \"enabled\": true,\n \"destOverride\": [\n \"http\",\n \"tls\",\n \"quic\",\n \"fakedns\"\n ]\n}", "clientStats": [ { "id": 19, "inboundId": 19, "enable": true, "email": "krjn1vjm", "up": 1951725145, "down": 211897149900, "expiryTime": 0, "total": 0, "reset": 0 } ] }`

so how my client connect to my sv without host or header?

**Comment by arash88** [comment]
> so how my client connect to my sv without host or header?

It's just the server-side inbound. In your client-seide configuration both SNI and Host parameters should contain your Cloudflare subdomain. Routing in Cloudflare is based on the SNI value.

**Comment by hhhmoe** [comment]
I meet a wired problem such that vless+tls+ws works on v2rayN (at Windows) but fails at Shadowrocket (at ios). log from shadowrocket is 404 not found.
