### ISSUE TITLE
تبدیل دیتابیس پنل های دیگه 

### ISSUE THREAD

**Issue by NaWeeDBHR** [MHSanaei/3x-ui#2291]
اگر این امکان وجود داشت که بشه دیتابیس پنل های دیگه مثلا کافکا رو اپلود کرد و خودکار تبدیل بشه به دیتابیس دیفالت 
ینی بتونیم راحت از بقیه پنل ها بیاییم روی این پنل

**Comment by MHSanaei** [comment]
مشکلی در این رابطه وجود ندارد
