### ISSUE TITLE
面板设置希望增加-代理设置

### ISSUE THREAD

**Issue by wuai1024** [MHSanaei/3x-ui#2296]
在国内的中间跳转节点机器上部署的3x-ui，无法连接到github 下载 `xray-core` 来更新版本。

<img width="1672" alt="image" src="https://github.com/MHSanaei/3x-ui/assets/13379708/db8c07fb-40a0-44ee-a6b6-1ecfb9987749">

希望能在`面板设置`上增加一个代理设置选项，可以让下载 `xray-core` 来使用这个代理设置更新。

**Comment by wuai1024** [comment]
<img width="407" alt="image" src="https://github.com/MHSanaei/3x-ui/assets/13379708/35150022-8557-4bd2-8beb-91a68b0bc2f0">

<img width="402" alt="image" src="https://github.com/MHSanaei/3x-ui/assets/13379708/08a61769-3079-451c-999d-34865c3deaaf">

就会这样一直转圈，然后超时失败。

**Comment by arash88** [comment]
Github's network which xray-core binaries are hosted is now blocked in China, you may download and replace it manually until another mirror for them become available in 3x-ui's install/update bash script.

**Comment by wuai1024** [comment]
这个和`xray-core`无关，可以在面板上加一个  http代理或者sockets代理。
