### ISSUE TITLE
流量可以定期自动重置（data usage can be automatically reset periodically）

### ISSUE THREAD

**Issue by yuze66** [MHSanaei/3x-ui#2302]
请在入站规则中的客户端配置选项添加设置，数据使用量可以定期自动重置
Please add a setting in the client configuration option in the inbound rule so that data usage can be automatically reset periodically

**Comment by anbell2** [comment]
我也挺想要这功能的，小机的流量是每月清零的。而且有的小机清零日期不是1号，是购机那天。
