### ISSUE TITLE
No successful connection after about one hour (2700 users on a single panel)

### ISSUE THREAD

**Issue by xxamr** [MHSanaei/3x-ui#2306]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi There
I Have about 2700 Accounts on one Inbound.
Recently after about one hour, users can not connect and I should restart the X-Ray Service.
What is the problem behind this misfunction?
Is there any limitation on number of accounts in a single panel?

### Version of 3x-ui

3X-UI: [v2.3.3](https://github.com/MHSanaei/3x-ui/releases) [@XrayUI](https://t.me/XrayUI)
Uptime: Xray: 3h OS: 7d 13h
Xray: Running Stop Restart v1.8.11
Manage: Logs Config Backup & Restore
System Load: 
0.03 | 0.05 | 0.07
Usage: RAM: 59.02 MB Threads: 18
 IPv4
 IPv6
 TCP: 595
 UDP: 110

### x-ui log reports or xray log

2024/05/25 07:32:52 WARNING - X-UI: Update Failed: read tcp 65.109.190.161:3306->2.187.121.163:60398: read: connection timed out
2024/05/25 07:17:01 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2709 due the expire or traffic limit
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2706 due the expire or traffic limit
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2703 due the expire or traffic limit
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2698 due the expire or traffic limit
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2694 due the expire or traffic limit
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2693 due the expire or traffic limit
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2692 due the expire or traffic limit
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2690 due the expire or traffic limit
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2689 due the expire or traffic limit
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2684 due the expire or traffic limit
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2682 due the expire or traffic limit
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2681 due the expire or traffic limit
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2679 due the expire or traffic limit
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2677 due the expire or traffic limit
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2675 due the expire or traffic limit
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2674 due the expire or traffic limit
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2670 due the expire or traffic limit
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2664 due the expire or traffic limit
2024/05/25 07:17:01 INFO - X-UI: Remove Inbound User B2661 due the expire or traffic limit

**Comment by arash88** [comment]
Send _htop_ results before and after the problems begin.
