### ISSUE TITLE
مسیر دیتابیس پنل 

### ISSUE THREAD

**Issue by SAEEDZZZ** [MHSanaei/3x-ui#2307]
سلام اگر بخوام داخل یه سرور دیگه پنل بیارم بالا ولی بکاپ یوزر هارو از فایل بکاپی که روی سرور دیگه ای هست مدام از اون لود کنه چیکار باید کنم

**Comment by SAEEDZZZ** [comment]
لودبالانس میخوام انجام بدم

**Comment by shayangha** [comment]
باید ی سینکر بنویسید که عنوان جاب دیتابیس رو سینک کنه با دیتابیس سرور اول و بعد از ریستور xray ریست شه
راه دیگه ای فکر نکنم باشه
