### ISSUE TITLE
Windows version can't start

### ISSUE THREAD

**Issue by silenceleaf** [MHSanaei/3x-ui#2309]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

(0x7ff67f869c80,0xc000b83790)
2024/05/25 15:46:30 x-ui 2.3.4
(0x7ff67f869c80,0xc000b83890)
2024/05/25 15:46:30 ERROR - location <Asia/Tehran> not exist, using default location: Asia/Tehran
2024/05/25 15:46:30 unknown time zone Asia/Tehran

### Version of 3x-ui

<details>

```console
(0x7ff67f869c80,0xc000b83790)
2024/05/25 15:46:30 x-ui 2.3.4
(0x7ff67f869c80,0xc000b83890)
2024/05/25 15:46:30 ERROR - location <Asia/Tehran> not exist, using default location: Asia/Tehran
2024/05/25 15:46:30 unknown time zone Asia/Tehran
```

</details>

### x-ui log reports or xray log

<details>

```console
(0x7ff67f869c80,0xc000b83790)
2024/05/25 15:46:30 x-ui 2.3.4
(0x7ff67f869c80,0xc000b83890)
2024/05/25 15:46:30 ERROR - location <Asia/Tehran> not exist, using default location: Asia/Tehran
2024/05/25 15:46:30 unknown time zone Asia/Tehran
```

</details>

**Comment by MHSanaei** [comment]
Install go version
