### ISSUE TITLE
Web base path

### ISSUE THREAD

**Issue by hootansadafi** [MHSanaei/3x-ui#2311]
قبلا که میخواستم پنل بسازم بدون مشکل کار میکردم اما الان بعد از مشخص کردن پورت میگه web base path بده من نمیدونم این چیه و چی بزنم.
خالی گذاشتمش اما پنل بالا نمیاد باید چیکار کنم و چه مقداری وارد کنم تا کار کنه و بعد هم چطور وارد پنلم بشم؟

**Comment by Padixix** [comment]
منظور آدرسیه که میخوای پنل توش نصب بشه
میتونی بزنی
/etc/panel

**Comment by NIKA5050** [comment]
> منظور آدرسیه که میخوای پنل توش نصب بشه میتونی بزنی /etc/panel

من مشابه پورت پنل وارد میکنم مثلا 443 پورت پنله اینم میزنم 443 مشکلی رخ نمیده ؟ بازم منم نفهمیدم دقیقا چیه ؟؟!!

**Comment by MHSanaei** [comment]
Ip:port/webbasepath/panel/

**Comment by hadee16** [comment]
> Ip:port/webbasepath/panel/

سلام . بازم نفهمیدم این یعنی چی . یکم توضیح بدید با ذکر مثال


ممنون

**Comment by MHSanaei** [comment]
Webbasepath: hasan
Ip:port/hasan/panel

**Comment by aminrad11** [comment]
مال من هم مشکل داره هر کاری میکنم پنلم بالا نمی یاد

**Comment by aminrad11** [comment]
هر جوری میزنم ای پی وارد میکنم پنلم بالا نمیاد

**Comment by aminrad11** [comment]
من ای پی خودم رو به صورت مثلا به صورت زیر وارد کردم
38.50.62.39:2053/amin/panel

ولی هر کاری می کنم پنلم بالا نمیاد
