### ISSUE TITLE
address

### ISSUE THREAD

**Issue by amiredmond9082** [MHSanaei/3x-ui#2312]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

درود وقت بخیر
سپاس از زحماتتون
یه موردی رو در این اپدیت جدید بهش برخوردم که ادرس اینباند رو میاد از ادرس پنل برمیداره، اپدیت های قبلی اینطور نبود و مشکلی نداشت و خب الان این مورد برای اونایی که از cdn استفاده میکنن دچار مشکله
لطفا راهنماییم میکنیم که چجوری حلش کنم
یا اینکه باگه و رفع میشه ؟

### Version of 3x-ui

<details>

```console
# 2.3.4
```

</details>

**Comment by Arman-nsb** [comment]
سلام، دوست عزیز از ویژگی external proxy در تنظیمات اینباند استفاده کنید و آدرس آی پی یا نام دامنه مدنظرتون رو قرار بدید.

**Comment by amiredmond9082** [comment]
> سلام، دوست عزیز از ویژگی external proxy در تنظیمات اینباند استفاده کنید و آدرس آی پی یا نام دامنه مدنظرتون رو قرار بدید.

سپاس از لطفت 
حل شد
