### ISSUE TITLE
اضافه کردن روز و حجم

### ISSUE THREAD

**Issue by nightday1243** [MHSanaei/3x-ui#2313]
درود شب و روزتون بخیر باشه 
اگه امکانش باشه یه ویژگی اضافه کنید که به صورت دسته ای بشه برای همه کاربر های یک پورت حجم یا زمان اضافه کرد 
با تشکر

**Comment by behzadti** [comment]
بله به عنوان هدیه در مناسبتهای خاص پیشنهاد خوبیه
