### ISSUE TITLE
v1.8.13 版本WireGuard不能连接

### ISSUE THREAD

**Issue by wlrsx** [MHSanaei/3x-ui#2315]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

切换到 v1.8.10 版本，WireGuard马上可以使用了。
在 v1.8.13 版本中看 xRay 日志也没有什么错误：
2024/05/26 16:05:50 [Debug] Routine: decryption worker 1 - started
2024/05/26 16:05:50 [Debug] Routine: handshake worker 1 - started
2024/05/26 16:05:50 [Debug] Routine: TUN reader - started
2024/05/26 16:05:50 [Debug] Routine: event worker - started
2024/05/26 16:05:50 [Debug] Interface up requested
2024/05/26 16:05:50 [Debug] Routine: receive incoming Open - started
2024/05/26 16:05:50 [Debug] peer(re5U…cWh4) - Routine: sequential sender - started
2024/05/26 16:05:50 [Debug] peer(re5U…cWh4) - Routine: sequential receiver - started
2024/05/26 16:05:53 [Debug] [2020597055] proxy/dokodemo: processing connection from: 127.0.0.1:56252
2024/05/26 16:05:53 [Info] [2020597055] proxy/dokodemo: received request for 127.0.0.1:56252
2024/05/26 16:05:53 [Info] [2020597055] app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]
2024/05/26 16:05:53 [Debug] [2260315604] proxy/dokodemo: processing connection from: 127.0.0.1:56258
2024/05/26 16:05:53 [Info] [2260315604] proxy/dokodemo: received request for 127.0.0.1:56258
2024/05/26 16:05:53 [Info] [2260315604] app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]
2024/05/26 16:05:53 [Debug] [1837608917] proxy/dokodemo: processing connection from: 127.0.0.1:56260
2024/05/26 16:05:53 [Info] [1837608917] proxy/dokodemo: received request for 127.0.0.1:56260
2024/05/26 16:05:53 [Info] [1837608917] app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]
2024/05/26 16:05:55 [Debug] app/log: Logger started
2024/05/26 16:05:55 [Debug] app/stats: create new counter inbound>>>api>>>traffic>>>uplink
2024/05/26 16:05:55 [Debug] app/stats: create new counter inbound>>>api>>>traffic>>>downlink
2024/05/26 16:05:55 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:62789
2024/05/26 16:05:55 [Debug] UAPI: Updating private key
2024/05/26 16:05:55 [Debug] UAPI: Updating listen port
2024/05/26 16:05:55 [Debug] peer(re5U…cWh4) - UAPI: Created
2024/05/26 16:05:55 [Debug] peer(re5U…cWh4) - UAPI: Adding allowedip
2024/05/26 16:05:55 [Debug] UDP bind has been updated
2024/05/26 16:05:55 [Debug] peer(re5U…cWh4) - Starting
2024/05/26 16:05:55 [Debug] Interface state was Down, requested Up, now Up
2024/05/26 16:05:55 [Debug] app/stats: create new counter inbound>>>inbound-31933>>>traffic>>>uplink
2024/05/26 16:05:55 [Debug] app/stats: create new counter inbound>>>inbound-31933>>>traffic>>>downlink
2024/05/26 16:05:55 [Debug] app/stats: create new counter outbound>>>direct>>>traffic>>>uplink
2024/05/26 16:05:55 [Debug] app/stats: create new counter outbound>>>direct>>>traffic>>>downlink
2024/05/26 16:05:55 [Debug] app/stats: create new counter outbound>>>blocked>>>traffic>>>uplink
2024/05/26 16:05:55 [Debug] Routine: encryption worker 1 - started
2024/05/26 16:05:55 [Debug] Routine: decryption worker 1 - started
2024/05/26 16:05:55 [Debug] Routine: handshake worker 1 - started
2024/05/26 16:05:55 [Debug] Routine: TUN reader - started
2024/05/26 16:05:55 [Debug] Routine: event worker - started
2024/05/26 16:05:55 [Debug] Interface up requested
2024/05/26 16:05:55 [Debug] Routine: receive incoming Open - started
2024/05/26 16:05:55 [Debug] peer(re5U…cWh4) - Routine: sequential sender - started
2024/05/26 16:05:55 [Debug] peer(re5U…cWh4) - Routine: sequential receiver - started
2024/05/26 16:06:00 [Debug] app/log: Logger started
2024/05/26 16:06:00 [Debug] app/stats: create new counter inbound>>>api>>>traffic>>>uplink
2024/05/26 16:06:00 [Debug] app/stats: create new counter inbound>>>api>>>traffic>>>downlink
2024/05/26 16:06:00 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:62789
2024/05/26 16:06:00 [Debug] UAPI: Updating private key
2024/05/26 16:06:00 [Debug] UAPI: Updating listen port
2024/05/26 16:06:00 [Debug] peer(re5U…cWh4) - UAPI: Created
2024/05/26 16:06:00 [Debug] peer(re5U…cWh4) - UAPI: Adding allowedip
2024/05/26 16:06:00 [Debug] UDP bind has been updated
2024/05/26 16:06:00 [Debug] peer(re5U…cWh4) - Starting
2024/05/26 16:06:00 [Debug] Interface state was Down, requested Up, now Up
2024/05/26 16:06:00 [Debug] app/stats: create new counter inbound>>>inbound-31933>>>traffic>>>uplink
2024/05/26 16:06:00 [Debug] app/stats: create new counter inbound>>>inbound-31933>>>traffic>>>downlink
2024/05/26 16:06:00 [Debug] app/stats: create new counter outbound>>>direct>>>traffic>>>uplink
2024/05/26 16:06:00 [Debug] app/stats: create new counter outbound>>>direct>>>traffic>>>downlink
2024/05/26 16:06:00 [Debug] app/stats: create new counter outbound>>>blocked>>>traffic>>>uplink
2024/05/26 16:06:00 [Debug] Routine: encryption worker 1 - started
2024/05/26 16:06:00 [Debug] Routine: decryption worker 1 - started
2024/05/26 16:06:00 [Debug] Routine: handshake worker 1 - started
2024/05/26 16:06:00 [Debug] Routine: TUN reader - started
2024/05/26 16:06:00 [Debug] Routine: event worker - started
2024/05/26 16:06:00 [Debug] Interface up requested
2024/05/26 16:06:00 [Debug] Routine: receive incoming Open - started
2024/05/26 16:06:00 [Debug] peer(re5U…cWh4) - Routine: sequential sender - started
2024/05/26 16:06:00 [Debug] peer(re5U…cWh4) - Routine: sequential receiver - started
2024/05/26 16:06:03 [Debug] [683010136] proxy/dokodemo: processing connection from: 127.0.0.1:53036
2024/05/26 16:06:03 [Info] [683010136] proxy/dokodemo: received request for 127.0.0.1:53036
2024/05/26 16:06:03 [Info] [683010136] app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]
2024/05/26 16:06:03 [Info] [683010136] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport request > read tcp 127.0.0.1:62789->127.0.0.1:53036: read: connection reset by peer
2024/05/26 16:06:03 [Debug] [2546876127] proxy/dokodemo: processing connection from: 127.0.0.1:53050
2024/05/26 16:06:03 [Info] [2546876127] proxy/dokodemo: received request for 127.0.0.1:53050
2024/05/26 16:06:03 [Info] [2546876127] app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]
2024/05/26 16:06:03 [Info] [2546876127] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport request > read tcp 127.0.0.1:62789->127.0.0.1:53050: read: connection reset by peer
2024/05/26 16:06:03 [Debug] [2461346473] proxy/dokodemo: processing connection from: 127.0.0.1:53066
2024/05/26 16:06:03 [Info] [2461346473] proxy/dokodemo: received request for 127.0.0.1:53066
2024/05/26 16:06:03 [Info] [2461346473] app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by hesoyam1123** [comment]
have the same trouble after upgrading to 2.3.4
after deleting wireguard inbount trouble fixed but i need exactly that wireguard inbound

**Comment by MHSanaei** [comment]
If you have any problems with WireGuard, change the Xray core version, not the panel.
