### ISSUE TITLE
گزینه IP Limit کلا حذف شده

### ISSUE THREAD

**Issue by AmirV5010** [MHSanaei/3x-ui#2317]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام دوستان وقت بخیر.
گزینه ip limit اصلا نیست توی قسمت اینباند و add client. سرور و x-ui رو ریستارت کردم بازم نیومد
ببخشید اگه سوال مبتدی هست ولی گشتم توی تاپیک ها جوابمو پیدا نکردم.
سپاس

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
برای access log مسیر تعیین کنید و fail2ban رو نصب کنید گزینه iplimit  نمایش داده خواهد شد

**Comment by naymintun800** [comment]
I'm sorry.. In Iogs I see the Ip is getting banned "2024/06/15 17:41:14   BAN   [Email] = 8i1lsoed  [IP] = 37.111.14.97 banned for 1800 seconds." But I can still access the vpn with that ip.
