### ISSUE TITLE
API for Panel and Xray Settings

### ISSUE THREAD

**Issue by mehdikhody** [MHSanaei/3x-ui#2318]
**Is your feature request related to a problem? Please describe.**
Currently, the only automation available is for installing the panel, creating an inbound, and setting up SSL for our domain. However, we need to manually log into our panel to set the private and public key paths or manually change our Xray configurations.

**Describe the solution you'd like**
Provide a way to change these settings via a REST API or through the console using the x-ui command. This will allow developers to install and configure settings automatically.

**Describe alternatives you've considered**
At the moment, everything is done manually.

**Additional context**
This feature will be beneficial for scaling infrastructure without wasting time on repetitive configurations and settings.

**Comment by Iliyanewcomer** [comment]
send post request to "/panel/setting/all" path to see panel settings

for change 
Developer tools => Network tab
