### ISSUE TITLE
تکمیل داکیومنت

### ISSUE THREAD

**Issue by behzadti** [MHSanaei/3x-ui#2320]
سلام
با تشکر از همه ی توسعه دهنده ها اگه ممکن باشه یه داکیومنت کامل واسه امکانات پنل بزارین خیلی از امکانات اضافه شده که هیچ توضیح و داکیومنتی نیس براش مث sockopt , Disable System Root , Session Resumption , One Time Loading , Usage Option , Metadata Only , Route Only 
اگه از توسعه دهندگان یا دوستان کسی توضیحی داره واسشون مطمئنا سوال من نه بلکه سوال خیلی از کلاینت ها هست

**Comment by TheLordOfTheKings** [comment]
داکیومنت ها اینجاست به زبان چینی:
https://xtls.github.io/
