### ISSUE TITLE
Wireguard Problem

### ISSUE THREAD

**Issue by soheilabedi1** [MHSanaei/3x-ui#2323]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام وقت بخیر خسته نباشید
تو پروتکل وایرگارد ، در تلگرام مشکل آپلود و دانلود هست روی ویتوری تست شد کاملا اوکی بود و چندین روش تانل تست شد هیچجوره اوکی نشد مشکل از پنله حتی میکروتیک هم تست شد کاملا اوکی بود ولی در پنل xui مشکلی هست که در پروتکل وایرگارد مشکل اپلود و دانلود هست نسبت به ویتوری ضعیف عمل میکنه سرعت در حد کیلوبایت هست به مگابایت نمیرسه اصلا سرعت دانلود سرعت اپلود هم بدک نیست فقط بگیر نگیر داره چند مگ اپلود میشه در حد چند ثانیه گیر میکنه مجدد ادامه میده حتی دیتاسنتر خارج و ایران هردو عوض شده و مجدد تست شدن مجدد همون مشکل رو داشتن درحالی که روی میکروتیک این مشکل نبود اصلا تست شد حتی بیزحمت در اپدیت های جدید این مشکل رو حل کنید خیلی ممنونم خسته نباشید همگی تشکر از اقا حسین و علیرضا

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
If you have any problems  with your wireguard just change your xray version

**Comment by soheilabedi1** [comment]
ورژن ایکس ری به 1.8.13 آپدیت شد و قطعی برای یوزرها ایجاد کرد و مجبور به
آپدیت به ورژن 1.8.11 شدم و همچنان مشکل ضعیفی آپلود و دانلود تلگرام با
پروتکل وایگارد xui باپرجاست لازم به ذکر است تانلی که برقرار شده تانل پنل به
پنل ریورس خود پنل xui هست که در قسمت xray setting گزینه Reverse میباشد لطفا
کمکی بکنید این مشکل رو حل کنیم یا در آپدیت بعدی خودتون مشکل رو حل کنید چون
من از دوستان هم پرسیدم این مشکل رو دارن اکثرا روی وایرگارد ایکس یو آی با
تشکر از تمامی دست اندرکاران این پنل
