### ISSUE TITLE
آپدیت نشدن لینک ساب بعد از آپدیت پنل

### ISSUE THREAD

**Issue by asghar61** [MHSanaei/3x-ui#2326]
سلام لینک ساب پنل بعد آپدیت کار نمیکته
ایند باند رو هم ادیت زدم بازم نشد
این ایراد رو میگیره
![subscribelink](https://github.com/MHSanaei/3x-ui/assets/158515560/d7427da7-4605-47f9-822c-19f15a168e54)

Access to sub*************.*** was deniedYou don't have the user rights to view this page.
HTTP ERROR 403

**Comment by asghar61** [comment]
خودم درستش کردم- پورت رو تقیر دادم به 2053 درست شد

**Comment by kingofcs20** [comment]
برای منی که فقط با پورت 443 دارم ساب میدم کسی راه حلی داری ؟؟ چرا باید روی پورت 443 خطا بده بعد از آپدیت ؟؟؟

**Comment by kingofcs20** [comment]
از v2.3.3 فکر میکنم اینجوری شد

**Comment by asghar61** [comment]
یکبار باید پورت رو عوض کتین

**Comment by kingofcs20** [comment]
نه عزیزم ، ببرم پورتی غیر از 443 درست میشه ولی من باید با 443 کار کنم روی worker هست ساب اصلی ، یه باگه این که روی 443 داره 403 میده

**Comment by asghar61** [comment]
من که به ناچار گذاشتم رو 2053 . علیرضا جان تو آپدیت جدید لطفا این مشکل رو
حل کنین بعلاوه اینکه قسمت پکت فرگمنت رو بشه دستی تعقیر داد . الان فقط از
پیش تعیین شده مقادیر داره .
