### ISSUE TITLE
How to delete a config in 2.3.4 ?

### ISSUE THREAD

**Issue by Trenobol** [MHSanaei/3x-ui#2328]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![1717014090112](https://github.com/MHSanaei/3x-ui/assets/118353130/2997187e-b9b1-4534-acb7-6b2835fa5d3d)
![1717014095846](https://github.com/MHSanaei/3x-ui/assets/118353130/b241f989-eed4-4c60-b167-62a4198a027e)

There is no delete window in 2.3.4
In 2.0.2 It is there

### Version of 3x-ui

2.3.4

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
You will see the delete button when there is more than one client in an inbound
