### ISSUE TITLE
ساب جیسون

### ISSUE THREAD

**Issue by soli2413** [MHSanaei/3x-ui#2330]
سلام.ساب جیسون رو فعال کردم و کار هم میکنه.با فیلترشکن سایتهای ایران رو هم باز میکنه(با فعالسازی گزینه دایرکت کانکشن) ولی بعضی سایتها رو باز نمیکنه باید فیلترشکن رو خاموش کنم.update geo رو هم زدم

**Comment by MHSanaei** [comment]
Geosite
 خیلی کامل نیست که لیست تمام سایت ها داخلش باشه بهتره خودتون لیست کاستوم وارد کنید

**Comment by soli2413** [comment]
> Geosite خیلی کامل نیست که لیست تمام سایت ها داخلش باشه بهتره خودتون لیست کاستوم وارد کنید

لیست رو چجوری باید وارد کنیم؟
