### ISSUE TITLE
مشکل کم نشدن حجم و تاریخ اکانت

### ISSUE THREAD

**Issue by Mrdebest071** [MHSanaei/3x-ui#2335]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام من روی پنلم چند روزه اکانت های انلاین رو نمیزنه و حتی حجم و زمان هم از اکانت ها کم نمیشن
لطفا یه راهی بگید انجام بدم
حتی بکاپ هم گرفتم کلا سرور رو هم عوض کردم دوباره درست نشده

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Sami4387** [comment]
منم همین مشکلو دارم نه انلاینی ها رو نشون نه حجم مصرفی روی 0 بایت میمونه کل اکانتای حجمی به صورت نامحدود استفاده میشه

**Comment by MHSanaei** [comment]
دکمه reset to default رو بزنید تنظیمات رو اشتباه تغییر داده اید
