### ISSUE TITLE
نصب نشدن file 2ban

### ISSUE THREAD

**Issue by Behnamskyy** [MHSanaei/3x-ui#2336]
![Screenshot 2024-06-01 155132](https://github.com/MHSanaei/3x-ui/assets/148554892/18db1016-cd90-4600-b73d-d4a2fb6e8a46)

با سلام و خسته نباشید
وقتی file2ban نصب میکنم این ارور رو میده و نصب نمیشه
سیستمم اوبنتو 22 هست قبلا 20 بود راحت نصب میشد
بنظر شما دلیل چیه و راه حلش رو اگر لطف کنید ممنون میشم

**Comment by Shellgate** [comment]
مشکلی مشابه این در ابونتو 24 بر خوردم بعد از به روز رسانی از 23 به 24 از کار افتاد و سرویس اجرا نمیشه

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/2271#issuecomment-2143960750
