### ISSUE TITLE
Fallback (vles-tls) does not interact with the nginx server.

### ISSUE THREAD

**Issue by anvar68** [MHSanaei/3x-ui#2342]
Going to the address https://xxxxxxx.freemyip.com/ in the browser ends with the error message PR_END_OF_FILE_ERROR.
Nginx server - 127.0.0.1:8080
сonfig.json - fallbacks block:
"fallbacks": [
 {
 "alpn": "",
 "dest": "@vless-ws",
 "name": "",
 "path": "/vlws",
 "xver": 0
 },
 {
 "alpn": "",
 "dest": "8080",
 "name": "",
 "path": "",
 "xver": 0
 }
 ]
What settings are missing?

With similar settings, pure xray - https://github.com/XTLS/Xray-install works correctly.

P.S. Sorry for my English - machine translation.

**Comment by alireza0** [comment]
Sorry, but it is also wrong!
In inbound with fallback you should not enable proxy_protocol.

You should disable it here and enable it in inbound which listens on `@vless-ws` socket.

The xVer is very important if you want to pass the header. Just set it to 1 for both fallback options.

**Comment by anvar68** [comment]
"You should disable it here and enable it in inbound which listens on @vless-ws socket."

How can this be done, and where is this setting located? In the settings, inbound proxy_protocol is not mentioned anywhere else.

**Comment by alireza0** [comment]
Check the example [here](https://github.com/XTLS/Xray-examples/blob/main/All-in-One-fallbacks-Nginx/server.json)

**Comment by anvar68** [comment]
Thank you, I have already seen this page and have not been able to configure it yet. That's why I asked the question here.

Initially the question was different.
In the ngnix - xtls working bundle (installed from https://github.com/XTLS/Xray-install) fallback worked.
Without changing ngnix settings, xtls was replaced with 3x-ui and fallback stopped working.
It turns out that the 3X-ui panel lacks the ability to configure correctly.

Okay, I'll look into it further.

**Comment by anvar68** [comment]
Settings
[VLESS-TCP-TLS](https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-TLS)
[VLESS-TCP-TLS-proxy protocol](https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-TLS-proxy%20protocol)
I do not work

**Comment by alireza0** [comment]
If it doesn't work, you did not follow the whole configuration.
You should have two inbounds:
1. Fallback: Vless TCP+TLS with only fallbacks on configuration. (DONT USE PROXY PROTOCOL HERE)
2. Child: Vleaa/Vmees/Trojan/Shadowsocks (WITHOUT TLS) tcp/ws/httpupgrade and ENABLED PROXY PROTOCOL - with same path as you defined in fallback config in 1st inbound.

Then client will use first inbound port to connect and fallback will pass it to 2nd inbound. TLS will be handled by 1st inbound.

For other fallbacks that you want to handle it by nginx, you can use following config:
In x-ui's fallback inbound:
![image](https://github.com/MHSanaei/3x-ui/assets/12573084/d4b14d31-bb7c-43be-ac18-7df51aa1e1c9)

In nginx you can answer requests by a json. Configuration could be like this:
```
server {
        listen 127.0.0.1:1001 proxy_protocol;
        listen 127.0.0.1:1002 http2 proxy_protocol;

        server_name  _;

        root    /var/www/html;
        real_ip_header proxy_protocol;
        set_real_ip_from 127.0.0.1;

        location / {
            default_type application/json;
            return 200 '{"code":"1", "message": "404 Not Found"}';
        }
}
```

**Comment by EryX0** [comment]
> If it doesn't work, you did not follow the whole configuration. You should have two inbounds:
> 
> 1. Fallback: Vless TCP+TLS with only fallbacks on configuration. (DONT USE PROXY PROTOCOL HERE)
> 2. Child: Vleaa/Vmees/Trojan/Shadowsocks (WITHOUT TLS) tcp/ws/httpupgrade and ENABLED PROXY PROTOCOL - with same path as you defined in fallback config in 1st inbound.

thanks for the detailed explanation, could this method be used to give a user with 1 uuid, multiple inbounds ? for example Cloudflare CDN, tunnel?
trying to achieve this : 
 if user uses whichever of these configurations, its volume should be subtracted unified with other configurations.

**Comment by alireza0** [comment]
In this structure it is not possible yet to have one client in several inbounds. But using `external proxy` configuration you can define several server Name/IP and port which points to a same inbound at the end. Then you can use other proxies like CF to create multiple links

**Comment by EryX0** [comment]
> In this structure it is not possible yet to have one client in several inbounds. But using `external proxy` configuration you can define several server Name/IP and port which points to a same inbound at the end. Then you can use other proxies like CF to create multiple links

but we can't give out multiple connection configs with various protocols to users right?
for example if we create the inbound as Vless ws (or HttpUpgrade), we can't give out tcp reality or tcp tunnel configuration to users? we only can use cf as external proxy CDN to give out the vless ws configuration with multiple IPs.
