### ISSUE TITLE
شناسایی نشدن ipv6 سرور 

### ISSUE THREAD

**Issue by mramir-pc** [MHSanaei/3x-ui#2346]
### Welcome

- [ ] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

ای پی۶ در پنل نمایش داده نمی شود و کانفیگ ها هم کار نمیکنه 

ای پی دیفالت خود سرور است 
یکی دو نسخه پنل رو تست زدم 
نسخه های لینوکس Deb10 و ubuntu20,22 رو هم تست کردم 
روی هتزنر این مشکلو ندارم 
دستور ip a هم میگیرم ای پی۶ رو میگه داخل سرور 
نسخه amd64

![photo_2024-06-03_20-04-00](https://github.com/MHSanaei/3x-ui/assets/74339795/9aa3ed5d-fe60-4aaa-8585-9536096895a0)

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
پنل از این سایت برای نمایش ipv6 استفاده میکند
https://api6.ipify.org
