### ISSUE TITLE
The inbound protocol of Wireguard cannot connect at all??? Hope to find a problem

### ISSUE THREAD

**Issue by lovesweet1984** [MHSanaei/3x-ui#2351]
The inbound protocol of Wireguard cannot connect at all??? Hope to find a problem~

**Comment by gunjack5** [comment]
I confirm. Wireguard does not connect

**Comment by lovesweet1984** [comment]
That's right. I can't connect to Wireguard here either What exactly is the situation? I hope to recover as soon as possible

**Comment by S4N-HOLO** [comment]
after some little research I can say, that after inbound adding (wg) on peer there're no wg instances or Ifaces at all. 
I can see config only in web gui.

**Comment by Set27** [comment]
https://github.com/MHSanaei/3x-ui/commit/713285457fedcf1b0f4f6f75db399d2dd042e802#commitcomment-142865287
