### ISSUE TITLE
اضافه کردن اپشن برای بک اپ

### ISSUE THREAD

**Issue by nightday1243** [MHSanaei/3x-ui#2357]
درود شب و روزتون بخیر باشه
یه پیشنهاد داشتم در صورت امکان اگه بشه اجراش کرد خیلی عالی میشه
برای بخش بک اپ یه بخشی اضافی کنید که بشه فقط یک پورت به همراه کاربراش رو از یه پنل به یه پنل دیگه انتقال داد بدون اینکه نیاز باشه بک اپ کلی گرفته بشه
یا 
اینطوری باشه همون پورت رو روی یه پنل دیگه اضافه کنیم و فقط کاربر ها به همراه اشتراک و بقیه چیزاشون رو به صورت دسته جمعی به اون پنل انتقال بدیم
با تشکر

**Comment by vR3za** [comment]
همین الان این قابلیت وجود داره 

1. روی Inbound مورد نظر 3 نقطه رو بزنید گزینه Export inbound رو بزنید 
2. داخل سرور هدف/جدید به صفحه Inbound ها بیاید و دکمه General Actions رو بزنید و گزینه Import an Inbound رو انتخاب کنید 
3. محتوا که از سرور قبلی کپی کردین رو وارد کنید و تمام.

**Comment by nightday1243** [comment]
دمت گرم خیلی ممنون
