### ISSUE TITLE
can not install on arm64(ampere) server

### ISSUE THREAD

**Issue by omid650** [MHSanaei/3x-ui#236]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام روی سرور های arm64(ampere) نصب نمیشه ، پنل علیرضا نصب میشه ولی 3x-ui نصب نمیشه ، چند بار هم تست کردم
این هم از ترمینال:

root@ubuntu-4gb-fsn1-3:~# bash <(curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh)
The OS release is: ubuntu
arch: arm64
Running...
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.68.0-1ubuntu2.18).
tar is already the newest version (1.30+dfsg-7ubuntu0.20.04.3).
wget is already the newest version (1.20.3-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Got x-ui latest version: v1.2.2, beginning the installation...
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2023-04-12 14:35:45--  https://github.com/MHSanaei/3x-ui/releases/download/v1.2.2/x-ui-linux-arm64.tar.gz
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-12 14:35:45 ERROR 404: Not Found.

Downloading x-ui failed, please be sure that your server can access Github

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
bale man arm64 ro hazf kardam az panel alireza estefade konid

**Comment by MHSanaei** [comment]
اوکی

**Comment by MHSanaei** [comment]
به نسخه اخر اضافه شد arm64

**Comment by omid650** [comment]
خیلی لطف کردید 
واقعا ممنون از زحماتی که می کشید
