### ISSUE TITLE
Xray reported an error

### ISSUE THREAD

**Issue by duxngkun** [MHSanaei/3x-ui#2366]
### Welcome

- [ ] Yes, I'm using the latest major release. Only such installations are supported.
- [ ] Yes, I'm using the supported system. Only such systems are supported.
- [ ] Yes, I have read all WIKI document,nothing can help me in my problem.
- [ ] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Xray reported an error so I couldn't use it. I reset the VPS and tried again, but when I added the client it gave me the error again while adding it manually!

### Version of 3x-ui

<details>

```console
Failed to start: main: failed to load config files: [bin/config.json] > encoding/hex: invalid byte: U+002D '-'
```

</details>

### x-ui log reports or xray log

<details>

```console
Jun 06 18:45:04 ubuntu-22-04-64bit-1-1-20 /usr/local/x-ui/x-ui[1809]: INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
Jun 06 18:45:04 ubuntu-22-04-64bit-1-1-20 /usr/local/x-ui/x-ui[1809]: ERROR - Failure in running xray-core:  exit status 23
```

</details>

**Comment by SteeledOlaf** [comment]
same thing, reinstalled the whole panel, it worked for like 10 minutes.
`2024/06/06 12:53:40 ERROR - X-UI: Failure in running xray-core: exit status 23
2024/06/06 12:53:40 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json`
also 3X-UI reports this
`Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: invalid field rule > infra/conf: neither outboundTag nor balancerTag is specified in routing rule`

**Comment by duxngkun** [comment]
> same thing, reinstalled the whole panel, it worked for like 10 minutes.
> 
> > ERROR - X-UI: Failure in running xray-core: exit status 23
> > INFO - XRAY: infra/conf/serial: Reading config: bin/config.j
> 
> also 3X-UI reports this
> 
> ```
> Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: invalid field rule > infra/conf: neither outboundTag nor balancerTag is specified in routing rule
> ```
> 
> i'm using latest version (2.3.4), i think it might have happened after "apt update && apt upgrade" command, maybe this clue will help.

`Failed to start: main: failed to load config files: [bin/config.json] > encoding/hex: invalid byte: U+002D '-'`

My xray says this, so what can I do to fix it?

**Comment by SteeledOlaf** [comment]
UPD

It works again just fine, just had to reinstall the whole panel and click "Reset to default" button.
![Снимок экрана 2024-06-07 162441](https://github.com/MHSanaei/3x-ui/assets/162361179/2dcf7fbd-eae8-49f6-9182-6d338d2b00c2)

**Comment by mohsenjokar** [comment]
Just delete last inbound, especially on port 443
