### ISSUE TITLE
Add New Inbounds vs Add Clients

### ISSUE THREAD

**Issue by mecrayavcin** [MHSanaei/3x-ui#2367]
Are there any difference between **adding add new inbounds on different ports** and **adding clients to a single account**?
Speed vs? Pros and Cons?

If you use proxified settings in Cloudflare, you can only use some spesific ports for it.
https://developers.cloudflare.com/fundamentals/reference/network-ports/
As you see, you can use only:

443
2053
2083
2087
2096
8443 

for https support. So if you want to create many accounts, you need more ports so you need to upgrade Cloudflare account.
I thought, i can only create 1 account on 443 with multiple clients.

Does this cause speed issues or any other problems? or should i create each account with different ports?

Thanks

**Comment by xeefei** [comment]
It is recommended that you create different ports for each different account to prevent one port from being blocked and all accounts being unable to access the Internet.
