### ISSUE TITLE
google 403 error

### ISSUE THREAD

**Issue by xshelll** [MHSanaei/3x-ui#237]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I got 403 Error when i tried to get google.com.

### Version of 3x-ui

<details>

```console
v1.2.2
```

</details>

### x-ui log reports or xray log

<details>

```console
Apr 12 14:34:59 ubuntu-2gb-fsn1-3 systemd[1]: Started x-ui Service.
Apr 12 14:34:59 ubuntu-2gb-fsn1-3 x-ui[11424]: 2023/04/12 14:34:59 x-ui 1.2.2
Apr 12 14:34:59 ubuntu-2gb-fsn1-3 x-ui[11424]: 2023/04/12 14:34:59 INFO - web server run http on [::]:2053
Apr 12 14:37:06 ubuntu-2gb-fsn1-3 x-ui[11424]: 2023/04/12 14:37:06 INFO - xshell login success,Ip Address:89.163.212.69
Apr 12 14:37:07 ubuntu-2gb-fsn1-3 x-ui[11424]: 2023/04/12 14:37:07 INFO - user 1 login success
Apr 12 14:38:56 ubuntu-2gb-fsn1-3 x-ui[11424]: 2023/04/12 14:38:56 WARNING - stop server err: multierr: close tcp [::]:2053: use of closed network connection |
Apr 12 14:38:56 ubuntu-2gb-fsn1-3 x-ui[11424]: 2023/04/12 14:38:56 INFO - web server run https on [::]:2053
Apr 12 14:38:59 ubuntu-2gb-fsn1-3 x-ui[11424]: 2023/04/12 14:38:59 http: TLS handshake error from 89.163.212.69:41712: read tcp 91.107.163.246:2053->89.163.212.69:41712: use of closed network connection
Apr 12 14:39:01 ubuntu-2gb-fsn1-3 x-ui[11424]: 2023/04/12 14:39:01 http: TLS handshake error from 89.163.212.69:41732: remote error: tls: unknown certificate
Apr 12 14:39:28 ubuntu-2gb-fsn1-3 x-ui[11424]: 2023/04/12 14:39:28 INFO - xshell login success,Ip Address:89.163.212.69
Apr 12 14:39:28 ubuntu-2gb-fsn1-3 x-ui[11424]: 2023/04/12 14:39:28 INFO - user 1 login success
Apr 12 14:39:30 ubuntu-2gb-fsn1-3 x-ui[11424]: 2023/04/12 14:39:30 http: TLS handshake error from 89.163.212.69:41724: EOF
Apr 12 14:51:31 ubuntu-2gb-fsn1-3 x-ui[11424]: 2023/04/12 14:51:31 WARNING - Add ToFail:  Port already exists: 49314
Apr 12 14:52:51 ubuntu-2gb-fsn1-3 x-ui[11424]: 2023/04/12 14:52:51 WARNING - Add ToFail:  Port already exists: 29141
Apr 12 14:53:44 ubuntu-2gb-fsn1-3 x-ui[11424]: 2023/04/12 14:53:44 WARNING - reza2
Apr 12 14:53:47 ubuntu-2gb-fsn1-3 x-ui[11424]: 2023/04/12 14:53:47 WARNING - xa40i2066
Apr 12 14:53:56 ubuntu-2gb-fsn1-3 x-ui[11424]: 2023/04/12 14:53:56 WARNING - client ip job err: unexpected end of JSON input
Apr 12 14:53:56 ubuntu-2gb-fsn1-3 x-ui[11424]: 2023/04/12 14:53:56 WARNING - xray log not init in config.json
Apr 12 15:34:47 ubuntu-2gb-fsn1-3 systemd[1]: Stopping x-ui Service...
Apr 12 15:34:47 ubuntu-2gb-fsn1-3 systemd[1]: x-ui.service: Deactivated successfully.
Apr 12 15:34:47 ubuntu-2gb-fsn1-3 systemd[1]: Stopped x-ui Service.
Apr 12 15:34:47 ubuntu-2gb-fsn1-3 systemd[1]: x-ui.service: Consumed 1min 25.783s CPU time.
-- Boot f6cf479029e940d08612400edd5b3ba5 --
Apr 12 15:35:03 ubuntu-2gb-fsn1-3 systemd[1]: Started x-ui Service.
Apr 12 15:35:03 ubuntu-2gb-fsn1-3 x-ui[578]: 2023/04/12 15:35:03 x-ui 1.2.2
Apr 12 15:35:03 ubuntu-2gb-fsn1-3 x-ui[578]: 2023/04/12 15:35:03 INFO - web server run https on [::]:2053

```

</details>

**Comment by itmahdi** [comment]
برای حل ارور ۴۰۳ اسکریپت wrap رو نصب کنید مشکلتون حل میشه

**Comment by m0000hamad** [comment]
> 

سلام دوست عزیز من سرچ کردم چیز جالبی دستم نیومد.میشه بیزحمت راهنمایی کنید لینک سایت چیزی که خودتون استفاده کردید برای نصب وارپ.ممنون میشم

**Comment by itmahdi** [comment]
> > 
> 
> سلام دوست عزیز من سرچ کردم چیز جالبی دستم نیومد.میشه بیزحمت راهنمایی کنید لینک سایت چیزی که خودتون استفاده کردید برای نصب وارپ.ممنون میشم

از این لینک ریپازیتوری استفاده کن کامل توضیح داده فقط دقت کن لینکی که داخلش برای اسکریپت قرار داده از آخرش [option] [license ] رو پاک کن

https://github.com/Musixal/Marzban-Tools/tree/main/WARP

**Comment by castell0riz0n** [comment]
> > > 
> > 
> > 
> > سلام دوست عزیز من سرچ کردم چیز جالبی دستم نیومد.میشه بیزحمت راهنمایی کنید لینک سایت چیزی که خودتون استفاده کردید برای نصب وارپ.ممنون میشم
> 
> از این لینک ریپازیتوری استفاده کن کامل توضیح داده فقط دقت کن لینکی که داخلش برای اسکریپت قرار داده از آخرش [option] [license ] رو پاک کن
> 
> https://github.com/Musixal/Marzban-Tools/tree/main/WARP

طبق آموزش مرزبان
بعد از اجرای دستور echo $(curl -s ifconfig.me) خطای Your client does not have permission to get URL دریافت میشه
