### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by MahdiMadhani** [MHSanaei/3x-ui#2371]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام چند ماه هست از ورژن v1.7.9 استفاده میکنم و از تانل ReverseTlsTunnel استفاده کردم و اوکی بود 
امروز از تانل رت هول استفاده کردیم با تعداد ۳۰۰ پورت و  از پورت  ۴۴۳  هم استفاده کردم
بعد از چند ساعت خطا داد
خروجی دستور dmesg 
 Out of memory: Killed process 10888 (xray-linux-amd6) total-vm:1803052kB, anon-rss:598196kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:1304kB oom_score_adj:0

### Version of 3x-ui

<details>

```console
# Paste here
```
v1.7.9

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```
 Out of memory: Killed process 10888 (xray-linux-amd6) total-vm:1803052kB, anon-rss:598196kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:1304kB oom_score_adj:0
</details>

**Comment by MHSanaei** [comment]
فقط مشکلات مربوط به نسخه اخر بررسی خواهند شد

**Comment by MahdiMadhani** [comment]
> فقط مشکلات مربوط به نسخه اخر بررسی خواهند شد

ایا به ورژن ارتباط دارد؟
