### ISSUE TITLE
اسپاتیفای با وارپ و تانل

### ISSUE THREAD

**Issue by elegance666** [MHSanaei/3x-ui#2375]
من هر کاری میکنم اسپاتیفای برنامش وصل نمیشه با وارپ،
میخواستم بدونم تنظیمات وارپ باید رو سرو ایران که با Routing rule وصل هست  به سرور خارجی باید انجام بشه، یا روی سرور خارجی؟

البته الان رو هر دو وارپ گذاشتم ولی باز هم تو برنامه اسپاتیفای میزنه آفلاین هستی...

**Comment by xQuantoM** [comment]
منم همین مشکل دارم راه حلی پیدا کردید لطفا همینجا بگید

**Comment by lvlehr4d** [comment]
من مشکل رو حل کردم این هم از روتینگ رولم
![Screenshot (16)](https://github.com/MHSanaei/3x-ui/assets/155431487/497e6236-041f-464f-b308-eec10dc6f318)

و حتما داخل تنظیمات Advanced

**Comment by xQuantoM** [comment]
app.spotify وقتی اضافه میکنم این ارور میگیرم
![image](https://github.com/MHSanaei/3x-ui/assets/78085908/c9cd59ed-2580-45af-8afe-68cff54307d8)

**Comment by Dneeel** [comment]
> و حتما داخل تنظیمات Advanced "app.spotify" "spotify" رو هم اضافه کنید

میتونم ازتون خواهش کنم که جزئیات دقیق تری از تنظیماتی که برای اسپاتیفای ست کردید و مراحلی که در کل برای اسپاتیفای انجام دادید بگید ؟ یا اگه امکانش هست جایی با شما در ارتباط باشم البته اگه مقدوره
