### ISSUE TITLE
تک کاربره کردن تانل معکوس و مشکل عجیب

### ISSUE THREAD

**Issue by alrz-usfi** [MHSanaei/3x-ui#2380]
وقت بخیر دوستان
میشه لطفا راهنمایی کنید سروری که از طریق تانل معکوس (reverse) راه اندازی شده رو چطور میشه تک کاربره کرد؟
کاربرهای من روی سرور ایران هستند و fail2ban نصب هست.
مشکل عجیبی که وجود داره اینه که کلا نمیشه تعداد ای پی رو وارد کرد و همچنین برای بعضی از کاربرها ip log وجود داره و برای بعضی دیگه نه. در صورتی که هر دو کاربر برای یک اینباند هستند:

![Screenshot (469)](https://github.com/MHSanaei/3x-ui/assets/143879175/64fb08e8-8bad-4a1b-a4f9-e959b495b618)
![Screenshot (468)](https://github.com/MHSanaei/3x-ui/assets/143879175/d0fc8565-cbc2-4616-b87e-966a1fa8b4c2)

**Comment by MHSanaei** [comment]
You need to set a path for the access log.
