### ISSUE TITLE
Issue with Instagram Music

### ISSUE THREAD

**Issue by Abyssking** [MHSanaei/3x-ui#2383]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hey there,
I got some kind of issue with 3x-ui on instagram music, there is issue to reach instagram.com/reels/audio/* and i tried too many ways, there is no diffrences between gost tunneling or nginx proxy pass, anyway there is no info about that, even my vps herself open instagram musics well, but there is no way to reach, and bpb response me well about that.

I am developer myself, but i am not dare to get you source for reworking on that. <3
Anyway thank you for your usefull respository

### Version of 3x-ui

<details>

```console
3x-ui version 2.3.5v
```

</details>

### x-ui log reports or xray log

<details>

```console
3x-ui version 2.3.5v
error while upgrading proxy
```

</details>

**Comment by vR3za** [comment]
If possible, please use a different server to test and observe the results. I encountered the same issue with the German server in the Hetzner data center, but the problem was resolved by switching to the French server and a different data center.
