### ISSUE TITLE
چطوری میشه ترافیک یوزرهارو محدود به چند سایت کرد؟

### ISSUE THREAD

**Issue by Kingraptorr** [MHSanaei/3x-ui#2384]
چطوری میشه ترافیک یوزرهارو محدود به چند سایت کرد؟
یعنی مثلا 10 تا URL رو بتونن ببینن و بجز اونا هیچ URL دیگه ای رو نتونن باز کنن؟

**Comment by Alireza78na** [comment]
یه Rule بزارن و سایتای مورد نظرتو توش اضافه کن
یه Rule دیگه پایینش بزار و تمام ترافیک رو مسدود کن.

بسته به سایتای مد نظرت ممکنه مشکلاتی هم به وجود بیاره این کار.

**Comment by Kingraptorr** [comment]
@Alireza78na 
میشه لطف کنی رول اول رو برام اینجا بنویسی با یک سری URL فرضی
حقیقتا من زیاد آشنا نیستم با نحوه نگارش رول ها
