### ISSUE TITLE
غیر فعال شدن کانفیگ ها همزمان با Expire شدن

### ISSUE THREAD

**Issue by Alireza78na** [MHSanaei/3x-ui#2386]
عرض سلام و خسته نباشید

**مشکل:**
یه مشکلی که الان پنل داره اینه که وقتی یه کانفیگ منقضی میشه ( حجم یا زمان ) وضعیتش به Ended تغییر میکنه و با اینکه Xray و یا کلا سرور Restart میشه اما همچنان کاربران با کانفیگ های منقضی شده میتونن متصل بشن ( چون وضعیت کلیشون همچنان فعاله ) ، حتی نشون میده که آنلاین هستن!

**راه حل:**
با توجه به تست هایی که کردم ، وقتی وضعیت کانفیگ از حالت فعال به غیرفعال تغییر میکنه ( به صورت دستی ) دیگه کانفیگ متصل نمیشه.
من issue قبلی رو خوندم و تا جایی که میدونم این مورد بررسی نشده بود.
بنابراین اگر همزمان با تغییر وضعیت کانفیگ بعد از منقضی شدن به Ended ، پنل کانفیگ رو Disable هم کنه این مشکل به طور کامل برای همه حل میشه.

با تشکر از شما.

**Comment by amirpars** [comment]
این مورد وقتی اتفاق میاد که تغییراتی مثل حذف یک کلاینت توسط api انجام بگیره(به طور مثال پنل به ربات متصل باشه و این فرایند توسط ربات انجام بشه) متاسفانه علارقم اینکه چندین گزارش این مدلی انجام شده هیچ فیکسی تا به الان انجام نشده و اکثرا این مشکل رو دارن

**Comment by onyx133** [comment]
آقا یه فیکسی واسه این بدید. هرچی یوزر داریم که منقضی شده الان میبینم خیلی ایزی وصلن :)
