### ISSUE TITLE
ارسال خودکار لاگ fail2ban

### ISSUE THREAD

**Issue by MaMMaD1999** [MHSanaei/3x-ui#2387]
درود، از یه آپدیتی به بعد دیگه ربات تلگرام موقع ارسال بکاپ دیتابیس دیگه لاگ لیست افراد بن شده رو ارسال نمیکنه، چطور میشه اینو دوباره دستی خودم فعال کنم؟

**Comment by MHSanaei** [comment]
از اون قسمت جدا شده میتونید با زدن دکمه get ban logs لیست مورد نظر رو بگیرید
