### ISSUE TITLE
دیتابیس مورد استفاده پنل سنایی چیست؟.

### ISSUE THREAD

**Issue by radinVFX** [MHSanaei/3x-ui#2389]
درود،
بنده قصد اتصال سایت جنگو به پنل رو داشتم و میخواستم بدونم پنل سنایی از چه دیتابیسی استفاده میکند و دیتا تمام کاربر های ساخته شده، داخل table زیر قرار دارد؟
x-ui.db/client_traffics table

**Comment by vR3za** [comment]
از Sqlite استفاده میکنه (زبان Go)

فایل/مسیر دیتابیس در 
/etc/x-ui/x-ui.db
هستش

برای برقراری ارتباط بین سرور و برنامه خودتون میتوانید از API که معرفی شده در صفحه معرفی Github استفاده کنید.

**Comment by radinVFX** [comment]
تشکر فراوان 🌹
