### ISSUE TITLE
reCAPTCHA گوگل

### ISSUE THREAD

**Issue by Shm9220** [MHSanaei/3x-ui#239]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

موقع سرچ گوگل به مشکل recaptcha میخورم . تو تنظیمات x-ui دیدم گزینه حل مشکلش رو گذاشتین ولی مراحل و جوابای بعدیشم رو نمیدونم چی باید زد 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
گزینه 19 Fixing Google reCAPTCHA رو میزنید بعد زبان رو انتخاب میکنید و بعد در صفحه منوی بعدی گزینه 12 
Install WireGuard and Cloudflare WARP tool Wgcf, enable IPv4 or IPv6, avoid Google reCAPTCHA
بعد از این گزینه چندبار باید y بزنید و بعد از شما میخواید بین ipv6 ia ipv4 یکی رو انتخاب کنید که 1 فکر کنم بود میشد ipv6 و بعدش نصب تموم میشه مشکل شما حل خواهد شد

**Comment by arminkazimi** [comment]
سلام من پنل شما رو به تازگی نصب کردم. این گزینه دیگه داخل منو نیست. و مشکل reCAPTCHA رو دارم. چطور میتونم حلش کنم؟
