### ISSUE TITLE
Telegram Bot

### ISSUE THREAD

**Issue by power0matin** [MHSanaei/3x-ui#2390]
برای Backup پنل ایران روی تلگرام راهکاری دارید؟
میخوام مثل پنل خارج روی بات برام لاگ روزانه بفرسته
پروکسی تو خود پنل خارج هم درست کردم گزاشتم ولی کار نمیکنه

**Comment by power0matin** [comment]
توضیح دادم که از socks5 ای که با کمک پنل خودتون ساختم رو از داخل تلگرام کپی کردم و وارد پنل میکنم ، ولی همچنان کار نمیکنه

**Comment by MHSanaei** [comment]
فرمت تلگرام با پنل فرق دارد 
به همون شکلی که داخل کادر نوشته شده وارد کنید
