### ISSUE TITLE
پیشنهاد برای قسمت بات تلگرام

### ISSUE THREAD

**Issue by elegance666** [MHSanaei/3x-ui#2396]
همانطور که میدونید socks5 رو تمام سرورها بستن و روی بیشتر از ۱۰ کشور مختلف آزمایش کردم ولی وصل نمیشه، حتی سعی کردم با تغییر فایل hosts دامین api.telegram.org رو بفرستم رو سرور خودم که اونم به خاطر فیلتر بودن دامنه نشد!
به نظرم فقط یک فیلد تو قسمت تلگرام بزارید که بشه تعریف کرد اطلاعات تموم شدن اکانت ها به api.telegram.org فرستاده بشه یا دامنه دیگه...
یا اینکه تو api بخشی باشه بشه خوند اکانت هایی رو که دارند تموم میشند....

**Comment by MHSanaei** [comment]
ساکس بسته نشده اگر درست انجام بدید کار میکنه
به هرحال میتونید این روش رو هم انجام بدید که مهندس علیرضا توضیح دادن
https://github.com/alireza0/x-ui/issues/252
