### ISSUE TITLE
کدام ورژن اوبونتو بهتر است؟

### ISSUE THREAD

**Issue by MahdiMadhani** [MHSanaei/3x-ui#2397]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

ما چهارتا سرور با تنظیمات یکسان داریم دوتا از سرور ها Ubuntu 20.04 64bit نصب هستن و دوتا دیگه Ubuntu 22.04 64bit برای دوتا سرور با ورژن Ubuntu 20  کلا اوکی هستش
 ولی دوتا سرور با ورژن Ubuntu 22 قطع میشه و باید پنل حذف و دوباره نص کنیم یا سرورحذف و دوباره نصب کنم 

### Version of 3x-ui

 v1.6.0
 v1.6.1
v1.7.9

### x-ui log reports or xray log

Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.4 linux/amd64)

A unified platform for anti-censorship.

2024/06/12 10:03:37 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: app/proxyman/inbound: failed to listen TCP on 34658 > transport/internet: failed to listen on address: 0.0.0.0:34658 > transport/internet/tcp: failed to listen TCP on 0.0.0.0:34658 > listen tcp 0.0.0.0:34658: bind: address already in use

 ERROR - Failure in running xray-core:  exit status 255

Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.4 linux/amd64)

A unified platform for anti-censorship.

2024/06/13 08:57:31 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: app/proxyman/inbound: failed to listen TCP on 34382 > transport/internet: failed to listen on address: 0.0.0.0:34382 > transport/internet/tcp: failed to listen TCP on 0.0.0.0:34382 > listen tcp 0.0.0.0:34382: bind: address already in use

Jun 13 09:10:03 localhost /usr/local/x-ui/x-ui[1113]: WARNING - stop server err: multierr: close tcp [::]:2097: use of closed network connection |
Jun 13 09:10:03 localhost /usr/local/x-ui/x-ui[1113]: INFO - web server run http on [::]:2097
Jun 13 09:10:04 localhost x-ui[2024]: 2024/06/13 09:10:04 x-ui 1.7.9
Jun 13 09:10:04 localhost /usr/local/x-ui/x-ui[2024]: INFO - web server run http on [::]:2097
Jun 13 09:10:59 localhost /usr/local/x-ui/x-ui[2024]: WARNING - stop server err: multierr: close tcp [::]:2097: use of closed network connection |

code = Unavailable desc = connection error: desc = "error reading server preface: read tcp 127.0.0.1:52834->127.0.0.1:62789: read: connection reset by peer"

Xray 1.8.4 (Xray, Penetrates Everything.) Custom (go1.21.0 linux/amd64)

A unified platform for anti-censorship.

2024/06/13 09:43:21 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: app/proxyman/inbound: failed to listen TCP on 59050 > transport/internet: failed to listen on address: 0.0.0.0:59050 > transport/internet/tcp: failed to listen TCP on 0.0.0.0:59050 > listen tcp 0.0.0.0:59050: bind: address already in use

**Comment by MHSanaei** [comment]
لطفا هیچگونه issue در رابطه با نسخه های قدیمی پنل باز نکنید بررسی نخواهند شد
