### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by Wolf6470** [MHSanaei/3x-ui#240]
درود و وقت بخیر.چگونه می توانیم روبات تلگرام پنل را راه اندازی کنیم

**Comment by M4hbod** [comment]
از قسمت تنظیمات پنل توی TG Reminder Related Settings سوییچ اولین گزینه رو بزنید بعد با کمک BotFather یه بات بسازید و توکنش رو توی فیلد اول قرار بدید و با کمک بات userinfobot ایدی عددی تلگرام خودتون رو پیدا کنید و داخل فیلد دوم قرار بدید.

**Comment by Wolf6470** [comment]
برا اینکه آپدیت رو بده چیکار کنیم
