### ISSUE TITLE
update from  v1.7.9 to v2.1.2

### ISSUE THREAD

**Issue by MahdiMadhani** [MHSanaei/3x-ui#2400]
در ورژن ۱.۷.۹ ابتدا خطای زیر نمایش داده شده 

Xray 1.8.4 (Xray, Penetrates Everything.) Custom (go1.21.0 linux/amd64)

A unified platform for anti-censorship.

2024/06/14 03:08:34 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: app/proxyman/inbound: failed to listen TCP on 55386 > transport/internet: failed to listen on address: 0.0.0.0:55386 > transport/internet/tcp: failed to listen TCP on 0.0.0.0:55386 > listen tcp 0.0.0.0:55386: bind: address already in use

 stop server err: multierr: close tcp [::]:2097: use of closed network connection |

و امروز به ورژن ۲.۱.۲ تغییر دادیم

کانفیگ های ما   با v1.7.9 ساختیم والان بروزرسانی کریدم داخل x-ui و   3. Custom Version را انتخاب و بعد     ورژن 2.1.2 را زدیم 
الان خروجی قسمت لاگ
Jun 14 12:04:50 srv8593592042 /usr/local/x-ui/x-ui[8394]: WARNING - XRAY: [2397262885] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to write A response payload > write tcp 127.0.0.1:14495->127.0.0.1:49812: write: broken pipe
Jun 14 12:04:50 srv8593592042 /usr/local/x-ui/x-ui[8394]: WARNING - XRAY: [1913494702] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to write A response payload > write tcp 127.0.0.1:37695->127.0.0.1:33468: write: broken pipe
Jun 14 12:04:50 srv8593592042 /usr/local/x-ui/x-ui[8394]: WARNING - XRAY: [4041334556] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to write A response payload > write tcp 127.0.0.1:37695->127.0.0.1:38166: write: broken pipe
Jun 14 12:04:50 srv8593592042 /usr/local/x-ui/x-ui[8394]: WARNING - XRAY: [3533354095] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to write A response payload > write tcp 127.0.0.1:14495->127.0.0.1:49796: write: broken pipe

**Comment by MHSanaei** [comment]
مشکلات مربوط به ورژن اخر بررسی خواهند شد

**Comment by MahdiMadhani** [comment]
بازگشتم به ورژن v1.7.9 
لطفا اگه امکانش هست مشکل این خطا را بفرمایید تا وقتی(مشکلات مربوط به ورژن اخر بررسی خواهند شد)

Xray 1.8.4 (Xray, Penetrates Everything.) Custom (go1.21.0 linux/amd64)

A unified platform for anti-censorship.

2024/06/14 03:08:34 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: app/proxyman/inbound: failed to listen TCP on 55386 > transport/internet: failed to listen on address: 0.0.0.0:55386 > transport/internet/tcp: failed to listen TCP on 0.0.0.0:55386 > listen tcp 0.0.0.0:55386: bind: address already in use

**Comment by MHSanaei** [comment]
متوجه منظور بنده نشدید 
در issue قبلی هم عرض کردم فقط مشکلات نسخه اخر بررسی خواهند شد یعنی شما باید نسخه اخر رو نصب کنید و لاگ اون نسخه رو ارسال کنید

این موردی هم که گفتید در مورد تگ اینباند هست که در قسمت rules استفاده‌ میشه
