### ISSUE TITLE
Ip limit is not limiting.😟

### ISSUE THREAD

**Issue by naymintun800** [MHSanaei/3x-ui#2401]
I'm sorry if this is a stoopid question and I've search in the thread up and down can't seem to find a solution for this. I'm not a dev. I've installed fail2ban and I have added ./access.log to xray configuration but for some reason IP limit function is not working properly. I can still use two of my phone that has the same Configuration at the same time. Help me out here...😵‍💫
![Screenshot 2024-06-14 215122](https://github.com/MHSanaei/3x-ui/assets/44871250/50c4363e-c73c-4773-9b25-afbb9842e1cc)

**Comment by MHSanaei** [comment]
Yes, they can use it at the same time for at least 30 seconds, then the second one will be banned with fail2ban.
You can change the ban time in the bash menu.

**Comment by naymintun800** [comment]
I very sure fail2ban is not banning the ip because I've been connected to the same config with 3 different devices for the past 12 hours and nobody is getting banned.

**Comment by MHSanaei** [comment]
Different devices with the same IP address don't get banned.

**Comment by naymintun800** [comment]
I'm sorry.. In Iogs I see the Ip is getting banned "2024/06/15 17:41:14 BAN [Email] = 8i1lsoed [IP] = 37.111.14.97 banned for 1800 seconds." But I can still access the vpn with that ip. And is not the same IP this time.
