### ISSUE TITLE
Subscription 

### ISSUE THREAD

**Issue by mohmd5210** [MHSanaei/3x-ui#2402]
سابسکرایب کانفیگ های من بعد از نسخه 2.2.1 به مشکل میخورن و بالا نمیان! مگر اینکه کانفیگ جدید بسازم!
تا نسخه 2.2.1 هیچ مشکلی وجود نداره

**Comment by MHSanaei** [comment]
قبلا اعلام کردیم اینباند خودتون رو یکبار اپدیت کنید
یعنی ادیت بزنید و بدون تغییر ذخیره کنید
