### ISSUE TITLE
ورژن اخر  Failed to start

### ISSUE THREAD

**Issue by MahdiMadhani** [MHSanaei/3x-ui#2403]
ورژن اخر نصب کردم خطای زیر رو داد
Failed to start: app/proxyman/inbound: failed to listen TCP on 55012 > transport/internet: failed to listen on address: 0.0.0.0:55012 > transport/internet/tcp: failed to listen TCP on 0.0.0.0:55012 > listen tcp 0.0.0.0:55012: bind: address already in use

برای ورژن های v1.6.0 وv2.1.2و v1.7.9  همین خطا هستش
https://github.com/MHSanaei/3x-ui/issues/2400
https://github.com/MHSanaei/3x-ui/issues/2397
Failed to start: app/proxyman/inbound: failed to listen TCP on 55386 > transport/internet: failed to listen on address: 0.0.0.0:55386 > transport/internet/tcp: failed to listen TCP on 0.0.0.0:55386 > listen tcp 0.0.0.0:55386: bind: address already in use

 stop server err: multierr: close tcp [::]:2097: use of closed network connection |

**Comment by MHSanaei** [comment]
خطای پورت تکراری

**Comment by MahdiMadhani** [comment]
برای پورت 55386 فقط یکی ثبت شده
[Uploading config.json…]()

**Comment by MHSanaei** [comment]
برید داخل xray configs دکمه reset to default  رو بزنید

**Comment by MahdiMadhani** [comment]
دیروز انجام دادم ولی دوباره بعد از چند ساعت همون خطا رو داد
فکر کنم تعداد پورت ها زیاد هستش این مشکل پیش میاد
ی سرور دیگه دارم تک پورت هستش و ۱۰۰ تا کانفیگ داخل همون پورت دارم و اوکی هستش.
برای همین سرور که مشکل داره به نظرتون میشه ی پورت بسازم و داخل همون پورت تعدادی کانفیگ بسازم و پورت هر کاربر رو هدایت کنیم به ی کانفیگ
