### ISSUE TITLE
سیو نشدن تنظیمات در بخش xray configs در آخرین نسخه

### ISSUE THREAD

**Issue by Izaanaami** [MHSanaei/3x-ui#2404]
هیچ outbound یا routing rule ای سیو نمیشه تو آخرین نسخه. حتی به صورت دستی هم که از بخش advanced اضافه میکنم بازم فایده ای نداره. کلا دکمه ی سیو روشن نمیشه و هیچی به صفحه اضافه نمیشه

 - 3X-UI Version : 2.3.5

**Comment by MHSanaei** [comment]
تا زمانی ک متن وارد شده درست نباشه دکمه سیو روشن نخواهد شد
