### ISSUE TITLE
نرم‌افزار"وی تو ری" بدون گزینه اشتراک گذاری  

### ISSUE THREAD

**Issue by madar54** [MHSanaei/3x-ui#2405]
از جناب سنایی و دیگر بزرگان این عرصه خواهشمندیم چنانچه توانایی ساخت یک اپلیکیشن مشابه v2ray را به مشتریان بدهند که هیچگونه گزینه اشتراک گذاری برای اشتراک کانفیگ نداشته باشد.زیرا دوستان کانفیگ‌ها را از طریق پیامک و اپلیکیشن‌های ایرانی به دوستان و رفقا و دیگران به اشتراک می‌گذارند و این باعث می‌شود آن کانفیگ به لیست سیاه فیلترینگ برود و آی پی و دامنه فیلتر شود لطفاً همچین اپلیکیشنی را طراحی بفرمایید که بسیار مهم و حیاتی است و نظر بقیه دوستان نیز می‌باشد با تشکر
![Screenshot 2024-06-15 140937](https://github.com/MHSanaei/3x-ui/assets/153379079/57399691-b613-47e8-8572-39c6dff0c30e)

**Comment by lvlehr4d** [comment]
بهترین راه برای کنترل این قضیه اینه که از دوتا سرور ایران و خارج استفاده کنی و اینکه حجم دانلود محدود کنی مثلا هر کار بر 10G
به دوستان هم بدهند دوباره پولشو میدن:)

**Comment by madar54** [comment]
من از دو تا سرور استفاده می‌کنم و تانل کردم ولی باز هم به صورت پیامکیبه
یکدیگر می‌دهند و باعث می‌شود آی‌پی فیلتر شود

‫‪lvlehr4d‬‏ ***@***.***‬‏> در تاریخ شنبه ۱۵ ژوئن ۲۰۲۴ ساعت
۱۸:۲۲ نوشت:‬

**Comment by lvlehr4d** [comment]
کدوم سرورت ایران یا خارج فیلتر میشه؟
این مورد هارو انجام بدی سالی 1 بار فیلتر میشی
1- تانل معکوس استفاده کن 
2- از CDN ایرانی اصلا استفاده نکن

**Comment by madar54** [comment]
بحث سر اینه که کانفیگو به اشتراک نذارن از طریق پیامک و نرم‌افزارهای اجتماعی روبیکا و ایتا و غیره وگرنه من حاضرم مجانی بهشون بدم پولم نگیرم فقط این کارو نکنن با پیامک کانفیگو به همدیگه ندن مشکل اینجاست جناب سنایی می‌گوید تک کاربره کردن پنل‌ها زمانی که دو سرور به هم تانل بشوند به خوبی کار نمی‌کند حالا شاید در ورژن جدید این مشکل را برطرف کرده است من در جریان نیستم

**Comment by lvlehr4d** [comment]
بلخره چجوری میخوای برای کاربرت کانفیگ بفرستی؟؟؟

**Comment by madar54** [comment]
سی دی ان کلودفلر استفاده می‌کنم سرور هلند به سرور ایران تانل کرده‌ام.....نوع تانل هم تانل معکوس نیست از یک تانل دیگر استفاده می‌کنم تقریباً خیلی قدیمی است.

**Comment by madar54** [comment]
فدای تو بشم کاربر میاد در مغازه کانفیگ بهش میدم داخل گوشیش تشریف می‌بره اگه کاربر از راه دور کانفیگ احتیاج داشته باشه هم ربات تلگرامی دارم هم توسط جیمیل م توسط گوگل درایو و هم توسط یک وب سایت شخصی برای او ارسال می‌کنم

**Comment by madar54** [comment]
من خودم کارمند مخابرات بودم و دوستانیم در مخابرات دارم یقاً تمام کانفیگ‌هایی که توسط پیامک ارسال می‌شوند در لیست زرد قرار می‌گیرند و بعد از چند روز آی‌پی آن سرور فیلتر می‌شود به طور کلی تمام کانفیگ‌های ویتوری برای آن ربات تعریف شده است که اگر چنین پیامکی ارسال گردید جزئیات آن به دست آمده و بعد از ارسال به لیست زرد و بررسی مجدد به لیست قرمز می‌رود و در آنجا جزئیات استخراج و سرور فیلتر می‌شود بعضی مواقع دامنه هم فیلتر می‌شود این را خودم نمی‌گویم دوستانم که در مخابرات هستند برایم توضیح داده‌اند
