### ISSUE TITLE
Malicious warp script

### ISSUE THREAD

**Issue by nullamix** [MHSanaei/3x-ui#2406]
The suggested script to install Warp (https://gitlab.com/fscarmen/warp) is malicious.
Because after installing it, ddos attacked a server in China from my server side. I checked that the server was not hacked; my only doubt is this script.

**Comment by MHSanaei** [comment]
Sorry, I forgot to remove that.
You don’t need to install it.
I'll remove it later

**Comment by nullamix** [comment]
thanks
