### ISSUE TITLE
Id inbound 

### ISSUE THREAD

**Issue by Hugsyyyy** [MHSanaei/3x-ui#2415]
چجوری id inbound  رو عوض کنیم ؟ برای ربات ویزویز به مشکل خورده وقتی اینباند بجای ۱ مثلا از ۵ شروع شده ، چون اینباند های ۱ تا ۴ رو پاک کردم

**Comment by vR3za** [comment]
سلام وقت بخیر 

امکانش وجود نداره ، اگرم دست تغییر بدین ، این ایدی های داخل دیتابیس به هم لینک هستند خراب میشه 
بهترین کار 

ابتدا از Inbound هاتون خروجی بگیرید 
بعد پنل 3x-ui رو مجددا نصب کنید و Inbound ها رو وارد کنید به سرور .
بعد از نصب پنل در صفحه Inbounds دکمه General Actions رو بزنید و Inbound هایی که از قبل خروجی گرفته بودین رو وارد کنید.
