### ISSUE TITLE
کار نکردن وایرگارد در هسته 1.8.13

### ISSUE THREAD

**Issue by meta-syfu** [MHSanaei/3x-ui#2418]
**Describe the bug**
سلام و خداقوت. در نسخه جدید این هسته در پنل هر کانفیگ وایرگاردی ک داشتم از کار افتادن و فقط با برگرداندن به نسخه 1.8.11 فقط  کار میکنه. آیا شماهاهم این مشکل رو دارین یا فقط در پنل من هس؟ حتی کانفیگ جدید هم ساختم ولی فایده نداشت.

 - 3X-UI Version : 2.3.5
 - Xray Version : 1.8.13

**Comment by MHSanaei** [comment]
باید این موضوع رو به xray گزارش کنید
