### ISSUE TITLE
تغیراتی اساسی برای ربات تلگرام

### ISSUE THREAD

**Issue by meysam31** [MHSanaei/3x-ui#2420]
سلام اقای ثنایی 
امکانش هست تیک و یا گزینه ای بذارید که حتما دریافت اطلاعات اکانت با ایدی تلگرام نباشه ؟ 
این کار را یکم مشکل کرده و اگر بتونیم این مورد را خودمون تعیین کنیم خیلی بهتره 
🙏

**Comment by MHSanaei** [comment]
خیر
