### ISSUE TITLE
پنل برای ادمین ها

### ISSUE THREAD

**Issue by overkill5205** [MHSanaei/3x-ui#2423]
سلام و وقت بخیر 
امیدوارم خوب باشی

سنایی عزیز اگه امکانش باشه برات لطفا قابلیت جدید رو اضافه کن که ادمین اصلی بتونه ادمین مدیریت یا فروش اضافه کنه و فقط دسترسی یک اینباند خاص یا یک قسمت خاص رو بهش بده 

این مورد بسیار مورد توجه هستش که اگه پسورد اصلی و یوزر اصلی به ادمین ها داده بشه پنل عموما دیگه امنیتی نخواهد داشت 

تشکر از زحماتت

**Comment by MHSanaei** [comment]
سلام دوست عزیز 
این پنل برای استفاده شخصی به صورت پیشرفته هست اگر برای فروش و مدیریت در نظر دارید پنل های دیگه مثل مرزبان رو استفاده کنید 
موفق باشید
