### ISSUE TITLE
XTLS

### ISSUE THREAD

**Issue by oghyanoos** [MHSanaei/3x-ui#243]
سلام
تو ورژن آخر با vless + tcp + xtls اکانت میسازم بعد دوباره ادیت میزنم میبینم اطلاعات پاک شده ، اونایی که با فلش نشون دادم دوباره خالی میشن، آیا مسیر رو کلا دارم اشتباه میرم؟ چطور میشه با xtls  یوزر ساخت. ممنون
Xray: v1.7.5 
3x-ui: v1.2.1

<img width="422" alt="Screenshot 2023-04-13 015039" src="https://user-images.githubusercontent.com/128707614/231598870-522d3c4e-8108-4de0-b408-959baae1c395.png">

**Comment by MHSanaei** [comment]
ببر ورژن ۱.۲.۲ مشکل حل شده
