### ISSUE TITLE
access.log 

### ISSUE THREAD

**Issue by Philipname** [MHSanaei/3x-ui#244]
سلام مجدد من فایل access.log  پیدا کردم. ولی مشکل اینه هر چند ثانیه کلیر میشه!
برای بحث IP limit  کاربردی هست و نیازه که مثلا برای یه روز داشته باشیم.
ممنون میشم بررسی کنید. با تشکر

**Comment by MHSanaei** [comment]
چیو بررسی کنم از ویژگی های ای پی لیمیت هست که این لاگ رو بررسی کنه و هر ده ثانیه پاک کنه

**Comment by Philipname** [comment]
خب من کل اون access.log نیاز دارم. و میخوام تحلیلش کنم. 
ولی الان کلا فقط ۱۰ ثانیه قبل و داریم.
میخواستم یه ویژگی اضافه بشه ، که بتونیم انتخاب کنیم که هر ۱۰ ثانیه پاک بشه یا نشه.
یعنی پیش فرض پاک بشه اگر ما نیاز داشتیم انتخاب کنیم که پاک نشه.

**Comment by MHSanaei** [comment]
میتونید یه لاگ دیگه بسازید با اسم متفاوت که دیگه هر ده ثانیه پاک نشه
داخل قسمت xray config در تنظیمات پنل

**Comment by Philipname** [comment]
متاسفانه بازم پاک میشه!!

**Comment by Philipname** [comment]
😐😐
