### ISSUE TITLE
the question is about the file ./access.log

### ISSUE THREAD

**Issue by KoPobkaTopta** [MHSanaei/3x-ui#2449]
Why the file is ./access.log being cleared automatically? I tried to search everything in 3x folders, but I didn't find anything.Maybe I'm not that experienced, but you can't tell me how to remove the auto-cleaning or change the cleaning time.

**Comment by MHSanaei** [comment]
because we need to clear it for iplimit 
you can uninstall your fail2ban so the access log won't be clear anymore for a day
if you need it for more than a day you can use alireza panel

**Comment by KoPobkaTopta** [comment]
> because we need to clear it for iplimit you can uninstall your fail2ban so the access log won't be clear anymore for a day if you need it for more than a day you can use alireza panel

Thank you very much! Then what is ipilimit for?I thought he was only making a limit on 1 key.But I never guessed that he would be cleaning
