### ISSUE TITLE
expire and data usage issue !

### ISSUE THREAD

**Issue by khoyboy20** [MHSanaei/3x-ui#245]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام . روی نسخه جدید بخش تاریخ و حجم درست کار نمیکنه 
دو مورد متفاوت ، در مورد اول تاریخ ثبت شده ولی حجم مصرفی 0 مونده و مورد دوم حجم مصرف شده ولی تاریخ ثبت نشده : 

https://ibb.co/MZqNbCN
https://ibb.co/gvJqtbh

این تصاویر هم برای نمونه

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by khoyboy20** [comment]
logs:

2023/04/13 06:58:42 WARNING - record not found  HZB 1
 2023/04/13 06:58:42 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email

**Comment by MHSanaei** [comment]
نسخه اخر رو نصب کنید و
این یوزر رو پاک کنید مشکلتون حل میشه
record not found HZB 1

**Comment by alisorena1993** [comment]
برای منم مشکل مصرف حجم هست ورژن 1.2.2 نصبه و حتی یوزر های جدید هم مشکل دارن

**Comment by AghaFarokh** [comment]
آقای ثنایی
من با API میزنم همچیو و چون باید کدم رو عوض کنم و نرسیدم نمیتونم ورژنی جدیدتر از 1.1.4 نصب کنم فعلا
و یه عالمه یوزر دارم که مصرفشون صفره
نمیتونمم پاک کنم از نو بسازم همچیم بهم میریزه چون باید کلی دیتا توی دیتابیس خودمم عوض کنم
بمن بگو چیکار کنم تو این وضعیت
تا اینجا صفر بوده اشکال نداره از اینجا به بعدو حساب کنه
اصلا یه توضیحی بده این مشکل از کجا میاد
ممنونتم
