### ISSUE TITLE
nginx reverse

### ISSUE THREAD

**Issue by okaya0x** [MHSanaei/3x-ui#2450]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - 3X-UI Version : 2.3.12
 - Xray Version : 1.8.23

**Additional context**

nginx.conf
location ^~ /demo {
            if ($scheme = http) {
        return 301 https://$host$request_uri;
    }
        proxy_set_header        Host                    $host;
        proxy_set_header        X-Real-IP           $remote_addr;
        proxy_set_header        X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_pass              http://127.0.0.1:1234/demo;

When I just click the restart panel button, the nginx reverse proxy port will jump from 443 to 1234. Clicking other buttons on the browser is normal.

**Comment by cqdjbb** [comment]
It seems that this problem exists in all versions after 2.3.8. I thought it would be fixed in later versions. I update it every time a new version is released, but the problem seems to exist all the time.

**Comment by MHSanaei** [comment]
download the file from here 
https://github.com/MHSanaei/3x-ui/actions/runs/10299018506
then unzip it and upload it to your server then use this code to install it 
```
ARCH=$(uname -m)
case "${ARCH}" in
  x86_64 | x64 | amd64) XUI_ARCH="amd64" ;;
  i*86 | x86) XUI_ARCH="386" ;;
  armv8* | armv8 | arm64 | aarch64) XUI_ARCH="arm64" ;;
  armv7* | armv7) XUI_ARCH="armv7" ;;
  armv6* | armv6) XUI_ARCH="armv6" ;;
  armv5* | armv5) XUI_ARCH="armv5" ;;
  s390x) echo 's390x' ;;
  *) XUI_ARCH="amd64" ;;
esac

cd /root/
rm -rf x-ui/ /usr/local/x-ui/ /usr/bin/x-ui
tar zxvf x-ui-linux-${XUI_ARCH}.tar.gz
chmod +x x-ui/x-ui x-ui/bin/xray-linux-* x-ui/x-ui.sh
cp x-ui/x-ui.sh /usr/bin/x-ui
cp -f x-ui/x-ui.service /etc/systemd/system/
mv x-ui/ /usr/local/
systemctl daemon-reload
systemctl enable x-ui
systemctl restart x-ui
```

**Comment by MHSanaei** [comment]
If you install that file correctly it should work well

**Comment by okaya0x** [comment]
> If you install that file correctly it should work well

Follow your prompts to update the files
sha1sum 815fc410a61ebf05f026f016827b46723ea21d65  /usr/local/x-ui/x-ui
https://github.com/alireza0/x-ui no problem

**Comment by MHSanaei** [comment]
I changed it to alireza code 
try download this 
https://github.com/MHSanaei/3x-ui/actions/runs/10305209970
then unzip it and upload tar.gz to your root with FTP then use that code

**Comment by okaya0x** [comment]
> I changed it to alireza code try download this https://github.com/MHSanaei/3x-ui/actions/runs/10305209970 then unzip it and upload tar.gz to your root with FTP then use that code

The problem still exists. If I replace the binary file in /usr/local/x-ui with the binary file of alireza link https://github.com/alireza0/x-ui/releases/download/1.8.5/x-ui-linux-amd64.tar.gz, there is no problem.

**Comment by vahiidsharifi-code** [comment]
سلام تو ورژن جدید در قسمت xray config دکمه reverse وجود ندارد چطور میتونم فعالش کنم ؟
