### ISSUE TITLE
After upgrading from 2.3.8 to the latest version, the web backend panel is inaccessible

### ISSUE THREAD

**Issue by cqdjbb** [MHSanaei/3x-ui#2451]
**Describe the bug**
After upgrading to the latest version, the original web backend access interface prompts that there is no permission (403 error). It was completely normal before 2.3.8, but it cannot be accessed in later versions

**Version (please complete the following information):**
 - 3X-UI Version : 2.3.8
 - Xray Version : 1.8.16

**Additional context**
Nginx has been installed on the vps, and the background and xray traffic are forwarded through nginx. The configuration is as follows

![1](https://github.com/user-attachments/assets/3c8b8203-3cab-4a7f-aa8b-208e7b85ff85)
![2](https://github.com/user-attachments/assets/310cf3b6-7626-43ef-b9fe-03cfcd8418f0)

**Comment by MHSanaei** [comment]
#2450
