### ISSUE TITLE
can i set the cert file and key in VM 

### ISSUE THREAD

**Issue by DFanso** [MHSanaei/3x-ui#2453]
im try to automate the installing process of this panel and I want to set the key and cert using VM command can I do that and where should I edit

**Comment by DFanso** [comment]
add also is there anything to restore a backup in command line or script or something

**Comment by MHSanaei** [comment]
You can easily restore your database from the panel (first page).
You can also set your private and public certificates in the settings.

**Comment by DFanso** [comment]
no i want to do it from a shell script after installing,

**Comment by MHSanaei** [comment]
so use ftp to upload your database here
/etc/x-ui/x-ui.db

**Comment by DFanso** [comment]
what about pannel settings , i want to change the cerficiate path

**Comment by MHSanaei** [comment]
We don't have that option sorry

**Comment by DFanso** [comment]
i create an automation bro , use the api to change the settings , https://github.com/DFanso/x-ui-automation
