### ISSUE TITLE
docker-compose.yaml安装不需要在文件中指定端口吗？docker ps 我都查不到用的哪个端口？不知道该放行哪个端口后才能在web端登录

### ISSUE THREAD

**Issue by zorn-zhao** [MHSanaei/3x-ui#2455]
1、将代码克隆到本地
2、cd /3x-ui
3、vim docker-compose.yaml
      hostname: racknerd-f98faa
4、docker-compose up -d 
5、docker-compose ps 返回3x-ui     ghcr.io/mhsanaei/3x-ui:latest   "/app/DockerEntrypoi…"   3x-ui     5 minutes ago   Up 5 minutes  
6、都不知道用的哪个端口

**Comment by okaya0x** [comment]
netstat -lntp |grep x-ui
