### ISSUE TITLE
(Sub, QRcode, URL) Problem for Trojan Reality

### ISSUE THREAD

**Issue by NativitY996** [MHSanaei/3x-ui#246]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

با درود و خسته نباشید خدمت شما و تمامی دوستان که باعث بهبود پنل تا امروز شدید و تشکر بابت اضافه شدن **Trojan Reality**

   باگی در آخرین پنل وجود داره که باعث میشه لینک sub or url or qrcode به درستی کار نکنند و بعد از قرار دادنشون در کلاینت‌ها قسمت **publickey** و **shortid** کپی نشن و باید دستی وارد بشن، ممنون میشم اگر این مشکل رو هم رفع کنید.

با تشکر مجدد از تلاش‌های بی‌وقفه و شبانه روزی شما

### Version of 3x-ui

last ver: 1.2.2

### x-ui log reports or xray log

no need to

**Comment by MHSanaei** [comment]
من چندین بار این قسمت رو چک کردم مشکلی وجود نداره در نسخه اخر ۱.۲.۲
