### ISSUE TITLE
telegram bot usage bug

### ISSUE THREAD

**Issue by Ahmedeisa25** [MHSanaei/3x-ui#2466]
/usage command works only on admin account 

**Expected behavior**

 - 3X-UI: [v2.3.12]
 - Xray Version : v1.8.23
on admin side 
![image](https://github.com/user-attachments/assets/d72af90e-42be-442d-82a7-f636628ac8fb)
on useres side
![image](https://github.com/user-attachments/assets/62441d0c-5fb2-4b68-a988-f8a6914a6bdb)

**Comment by MHSanaei** [comment]
Set that user ID for your client on the panel.
There are no bugs.
