### ISSUE TITLE
عدم تطابق حجم مصرفی داخل پنل و سرور

### ISSUE THREAD

**Issue by ramin9659** [MHSanaei/3x-ui#2467]
وقتی از روش تانل استفاده می کنم دیتای مصرفی داخل پنل که مجموع استفاده کاربران است کمتر از آنچه است که شماره ترافیک مرکز ارائه دهنده سرور نشان می دهد مثلا 1 ترابایت مرکز ارائه خدمات سرور را داخل پنل 700 گیگ نشان می دهد.
توقع داریم اختلاف فاحشی بین دو این عدد نباشد.نه اینکه اصلا اختلاف نباشد.

**Comment by MHSanaei** [comment]
نحوه محاسبه ترافیک در سرور و پنل متفاوت است. برخی از سرویس‌دهندگان سرور ترافیک را شامل سربار پروتکل‌ها و ترافیک داخلی نیز می‌کنند، در حالی که پنل تنها ترافیک خالص انتقال داده‌ها را محاسبه کند.
ترافیک اضافی مثل حملات DDoS یا اسکن پورت و از این دست موارد در سرور ثبت میشود اما پنل آن‌ها را به‌عنوان ترافیک کاربران در نظر نمیگیرد.
