### ISSUE TITLE
قطع شدن ناگهانی

### ISSUE THREAD

**Issue by armanempier** [MHSanaei/3x-ui#2468]
سلام وقت بخیر
من یه مشکلی دارم سرورا خیلی خوب کار میکنن ولی یهویی قطع میشن باید یکبار هسته xray ریستارت کنم تا مجدد فعال بشن و کار کنن و دیتا رد کنن.
کسی میدونه مشکل از چی میتونه باشه ؟؟ ممنون میشم راهنمایی کنید

**Comment by MHSanaei** [comment]
لطفا issue بدون لاگ و اطلاعات کامل باز نکنید
