### ISSUE TITLE
Longer retention logs

### ISSUE THREAD

**Issue by KoPobkaTopta** [MHSanaei/3x-ui#2469]
I'm not comfortable when ./access.log is cleared during the day. And I simply cannot predict when he will be cleansed again. I would like to see in the 3x-ui a choice of how long it takes to clear the logs or turn them off altogether. Of course, I could make a script that would, say, save logs to another location every 10 hours and then take them away from there. But I would like to see such a function in the panel. So as not to bother with it

**Comment by MHSanaei** [comment]
i'll think about it
