### ISSUE TITLE
مشکل Sesseion 

### ISSUE THREAD

**Issue by qar4al** [MHSanaei/3x-ui#2473]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - 3X-UI Version : [e.g. 2.3.5]
 - Xray Version : [e.g. 1.8.13]

**Additional context**

در ورژن V2.3.12
مشکل سشن همچنان پا برجا هست و هر بار برای ورود به پنل باید لاگین کنیم لطفا باگ رو برسی کنید با تشکر

**Comment by MHSanaei** [comment]
تایم رو بالا ببرید از داخل تنظیمات
