### ISSUE TITLE
گزارش باگ در ساخت یوزر 

### ISSUE THREAD

**Issue by maghsoudivip** [MHSanaei/3x-ui#2475]
سلام وقت بخیر 
خیلی خلاصه بگم این مشکل در پنل ثنایی و علیرضا وجود دارد 
هنگام ساخت یوزر با ID تکراری یوزر ساخته می شود مانند فیلد ایمیل ارور نمیده 
این می تونه مشکلات بزرگی به وجود بیاره مثلا یوزر حذف شده اما زمانی که ID همان یوزر حذف شده یوزر جدید ساخته می شود کاربر مجدد می تواند متصل شود و مشکل بعد محاسبه حجم چند وقتی بود یه مشکلی داشتم که یوزر که به هیچ کس نداده بودم حجم می انداختند 
لطفا یه فکری برای این مشکل کنید 
باتشکر از توجه شما

**Comment by MHSanaei** [comment]
ایدی هایی که ساخته میشن امکان تکراری بودن برای انها وجود ندارد مگر خود ادمین به عمد اینکار رو انجام بدهد
موفق باشید

**Comment by maghsoudivip** [comment]
ممنون از توضیحاتتون 
ولی اگر ارور بده بنظرم می تونه خیلی کمک‌ کنه چون الان اکثر ربات های متصل به پنل xui این باگ رو دارند یوزر با ID تکراری می سازند 
البته می دونم این مشکل پنل اصلا محسوب نمیشه ولی اگر این مورد هم مثل ایمیل تکراری ارور بده خیلی عالی میشه 
بازم ممنون از شما 
موفق باشید 🌹🙏
