### ISSUE TITLE
پیشنهاد بهبود 

### ISSUE THREAD

**Issue by maghsoudivip** [MHSanaei/3x-ui#2476]
سلام وقت بخیر 
1-لطفا یه قابلیت اضافه کنید زمانی که میزان مصرف رم مثلا 90 درصد رسید هسته xray به صورت خودکار ری استارت شود 
2-الان مشکلی که وجود دارد با warp پس از گذشت یه مدت زمان نا مشخص ارتباط وارپ با پنل قطع می شود برای حل این مشکل دو تا راهکار وجود دارد ری استارت هسته xray و یا تعویض خودکار لایسنس وارپ مثلا هر دو ساعت
 می دونم میشه با یه سری دستورات در ترمینال این مشکل رو حل کرد ولی اگر به خود پنل اضافه بشن می تونه عملکرد بهتری داشته باشد 
باتشکر از توجه شما

**Comment by MHSanaei** [comment]
سلام ممنون از پیشنهادت
