### ISSUE TITLE
Inbounds ID management

### ISSUE THREAD

**Issue by iloveayumi2006** [MHSanaei/3x-ui#2478]
I would like to edit ID and sort inbounds in Inbounds UI.
Is it possible to consider adding changing inbounds ID number and sort them manually?
Thanks.

**Comment by MHSanaei** [comment]
No sorry

**Comment by King-Of-Knights** [comment]
@iloveayumi2006 Hi, I met the same issues as you and I found another way to handle this. The config files is in `/etc/x-ui/x-ui.db`, download it and you could modify ID value by [DB Browser](https://sqlitebrowser.org/) , sign in x-ui panel overview, finally use Backup & Restore in Manage Tab to update your ID information
