### ISSUE TITLE
لاگین نشدن پنل پس از ریبوت سرور

### ISSUE THREAD

**Issue by s4deghm** [MHSanaei/3x-ui#248]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام 
در نسخه 1.2.2 پس از ریبوت سرور امکان لاگین به پنل از طریق وب نمی باشد و حتما باید x-ui restart  و دستی بزنم در زمان لاگین خطای زیر را نشان می دهد
Error: Request failed with status code 500
این مشکل را از نسخه 1.1.4 مشاهده کردم سیستم عامل debian 11.6 استفاده میکنم

### Version of 3x-ui

<details>

```console
# Paste here
```
v 1.2.2
Error: Request failed with status code 500
</details>

### x-ui log reports or xray log

<details>

```console
# paste log here

Apr 13 12:15:35 V2RAY-USA x-ui[1681]: 2023/04/13 12:15:35 INFO - user 1 login success
Apr 13 12:15:37 V2RAY-USA x-ui[1681]: 2023/04/13 12:15:37 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Apr 13 12:15:37 V2RAY-USA x-ui[1681]: 2023/04/13 12:15:37 Failed to get updates, retrying in 3 seconds...
Apr 13 12:15:43 V2RAY-USA x-ui[1681]: 2023/04/13 12:15:43 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

```

</details>

**Comment by sinaexx** [comment]
Sep 30 13:48:09 srv5959413497 systemd[1]: x-ui.service: Scheduled restart job, restart counter is at 3.
Sep 30 13:48:09 srv5959413497 systemd[1]: Stopped x-ui Service.
Sep 30 13:48:09 srv5959413497 systemd[1]: Started x-ui Service.
Sep 30 13:48:09 srv5959413497 x-ui[152290]: 2023/09/30 13:48:09 x-ui 1.7.8
Sep 30 13:48:09 srv5959413497 /usr/local/x-ui/x-ui[152290]: INFO - web server run https on [::]:12468
Sep 30 13:48:09 srv5959413497 /usr/local/x-ui/x-ui[152290]: WARNING - start xray failed: Failed to generate xray configuration file: json: error calling MarshalJSON for type json_util.RawMessage: invalid ch>
Sep 30 13:48:19 srv5959413497 /usr/local/x-ui/x-ui[152290]: WARNING - Something went wrong: open bin/config.json: no such file or directory
Sep 30 13:48:19 srv5959413497 /usr/local/x-ui/x-ui[152290]: WARNING - Something went wrong: unexpected end of JSON input
Sep 30 13:48:19 srv5959413497 /usr/local/x-ui/x-ui[152290]: WARNING - access.log doesn't exist in your config.json

**Comment by sinaexx** [comment]
اومدو رباط نصب کنم سرورا اینجوری شد چه کار کنم

**Comment by s4deghm** [comment]
تنظیمات را برگردون به حالت قبل اگر پنل بالا نمیاد میتونی فایل دیتابیس و ادیت کنید.

**Comment by sinaexx** [comment]
پنل با اینترنت همراه اول بالا نمیاد
