### ISSUE TITLE
مصرف بالای رم

### ISSUE THREAD

**Issue by Fatifan** [MHSanaei/3x-ui#2480]
متاسفانه زمانی که از اسکریپت وارپ در کنار پنل استفاده میشود بعد از گذشت کمتر از ۲۴ ساعت مصرف رم بسیار بالا میرود و باید سرور ریبوت شود. راهکاری برای این مشکل وجود دارد؟

**Comment by MHSanaei** [comment]
فقط بعضی ترافیک هارو از وارپ رد کنید نه همه

**Comment by Fatifan** [comment]
ناچارا ترافیک اینستا و گوگل از وارپ رد میشه و کل ترافیک از وارپ رد نمیشه، اما بعد ۲۴ ساعت حتی در زمانی که هیچکس به سرور متصل نیست حداقل ۵۰ درصد از رم توسط وارپ اشغال شده
