### ISSUE TITLE
مشکل انلاین نشون دادن دو پنل جدا روی یک سرور

### ISSUE THREAD

**Issue by qar4al** [MHSanaei/3x-ui#2481]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - 3X-UI Version : [e.g. 2.3.5]
 - Xray Version : [e.g. 1.8.13]

**Additional context**
این مشکل خیلی وقته هست دو پنل جدا روی یک سرور هست هر از گاهی انلاین ها رو نشون میده بعد دوباره نشون نمیده بعد از چندین بار رفرش باز نشون میده باز میره روی هر دو پنل اینجوری . ایا راهکاری هست ؟

**Comment by MHSanaei** [comment]
متوجه منظور شما نشدم
ولی به هرحال صبر کنید به زودی xray این قابلیت انلاین رو اضافه میکنه مشکل شما هم حل میشه
