### ISSUE TITLE
IP Limit does not see the ip address

### ISSUE THREAD

**Issue by egasvegas1109** [MHSanaei/3x-ui#2482]
Hello, I use gRPC transport and proxy traffic through cloudflare. Fali2ban and IP Limit don't see the client's ip address, so it doesn't work. Please tell me what can be done in this case?

Here is the nginx setup

```
	location /myLocation {
		if ($content_type !~ "application/grpc") {
			return 404;
		}

		client_max_body_size 0;
		client_body_buffer_size 512k;
		grpc_set_header X-Real-IP $remote_addr;
		client_body_timeout 52w;
		grpc_read_timeout 52w;
		grpc_pass grpc://127.0.0.1:1823;
	}
```

**Comment by MHSanaei** [comment]
Of course, it won't see the client IP address with this Nginx config.
You need to use `set_real_ip_from` on your Nginx config with all your CDN IP addresses, then you can see your clients' IP addresses.
If you don't know how to do it so don't use it. 🤷
