### ISSUE TITLE
IP Limit

### ISSUE THREAD

**Issue by Maqsoodi** [MHSanaei/3x-ui#2483]
سلام وقت بخیر 
جناب ثنایی یه سوال فنی آیا در آپدیت های آخر پنل  IP Limit کلا حذف کردید ؟  چون مثل قبل قسمتی برای محدود کردن تعداد اتصال همزمان در بخش ساخت یوزر وجود ندارد اما در قسمت لاگ پنل انگار هنوز IP Limit وجود دارد  
امکانش هست یه توضیح کوچیک بدید جریان چیه هر جا سرچ کردم چیزی در این رابطه پیدا نکردم

<img width="983" alt="Screenshot 2024-08-11 101238" src="https://github.com/user-attachments/assets/63c40206-3360-4082-aadc-9276e3fa658b">

**Comment by armia84** [comment]
سلام
آیپی fail2ban رو نصب کنید تو لاگ خودش نوشته که نصب نیست

**Comment by MHSanaei** [comment]
خیر حذف نشده باید fail2ban نصب باشه و مسیر برای access log گذاشته باشید
