### ISSUE TITLE
سیو نشدن log in پنل

### ISSUE THREAD

**Issue by armia84** [MHSanaei/3x-ui#2484]
سلام
تو آپدیت جدید وقتی وارد پنل میشیم و بعد از مدتی دوباره میخوایم به پنل دسترسی داشته باشیم باید مجددا یوزرنیم و پسورد رو وارد کنیم، یعنی به صورت خودکار بعد از ی مدت خودکار خودش لاگ اوت میشه

Session Duration هم رو 0 تنظیم شده
مقدار رو هم تغییر دادم ولی تاثیری نداشت

راهی هست که مثل قبل تو همون حالت که وارد میشدیم بمونه؟

**Comment by MHSanaei** [comment]
در صورتی که مقدار session صفر باشه بعد از یک ساعت لاگ اوت میشین در صورت نیاز مقدار مورد نظرتون رو به دقیقه وارد کنید
