### ISSUE TITLE
api bug.

### ISSUE THREAD

**Issue by AliMajidi1** [MHSanaei/3x-ui#2485]
**Describe the bug**
addClient api route return 404. but it was ok in 2.3.11 version.

**Version (please complete the following information):**
 - 3X-UI Version : 2.3.12 or 2.3.13
 - Xray Version : 1.8.23

**Comment by MHSanaei** [comment]
در ۲ ورژن اخر هیچ تغییری در api داده نشده حتی یک pr باز هم داریم در این مورد که اگر موردی بود اونجا مشخص میشد

**Comment by AliMajidi1** [comment]
بله منم دیدیم که تغییراتی در ریلیز در مورد api ذکر نشده.
با این حال به محض آپدیت ریسپانس ۴۰۴ میگیرم ولی بعد از دانگرید به 2.3.11 درست میشه.
