### ISSUE TITLE
Restarting the panel when activating the disabled user

### ISSUE THREAD

**Issue by sssagsag** [MHSanaei/3x-ui#2486]
hello and thanks for x-ui panel there is a problem in the xui panel that has been there for a long time.
When a user is in disabled or depleted status and we activate it, the panel and xraycore will be restarted, and if the server traffic is high, it will cause the xraycore to be in stop status for about 15 seconds.
please fix this problem

![mhsana](https://github.com/user-attachments/assets/440c4211-08c7-42ca-b924-8a32c027d9aa)

**Comment by MHSanaei** [comment]
Please explain more and share your syslog here.
Do you have any bots to activate, deactivate, create, or delete your clients?

**Comment by ssmetall** [comment]
> Please explain more and share your syslog here. Do you have any bots to activate, deactivate, create, or delete your clients?

It is not a problem to create and change  a user  status is enable, when a user is disabled and we change it to enable, the panel will be restarted.
I have a bot, but it's not a bot issue, change it manually in the panel
![mh1](https://github.com/user-attachments/assets/c26dccff-6978-4a13-867d-30b61010c59c)
![mh2](https://github.com/user-attachments/assets/3824cecb-c17f-466e-8da3-cad96ad8cd0d)

2024/07/30 15:40:00 DEBUG - X-UI: Client edited by api:mat
2024/07/30 15:40:00 DEBUG - X-UI: Error in deleting client by api:rpc error: code = Unknown desc = proxy/vless: User mat not found.

**Comment by ssmetall** [comment]
Also, Alireza's panel has exactly the same problem
https://github.com/user-attachments/assets/5bbcbd0f-83fb-4c47-b3c8-7153647c6587
