### ISSUE TITLE
کند شدن سرعت v2ray به صورت ناگهانی

### ISSUE THREAD

**Issue by arshiyakashani** [MHSanaei/3x-ui#2487]
سرعت به صورت عجیبی کند شده مشکل نمیدونم چیه لاگ رو چک کردم این ارور رو داده نمیدونم چطوری درستش کنم

 - 3X-UI Version 2.3.12
 - Xray Version : 1.8.23

لاگ
2024/08/11 19:37:27 ERROR - X-UI: Failure in running xray-core:exit status 23
2024/08/11 19:37:27 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/08/11 19:37:25 ERROR - X-UI: Failure in running xray-core:exit status 23
2024/08/11 19:37:25 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/08/11 19:37:23 ERROR - X-UI: Failure in running xray-core:exit status 23
2024/08/11 19:37:23 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/08/11 19:37:21 ERROR - X-UI: Failure in running xray-core:exit status 23
2024/08/11 19:37:21 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/08/11 19:37:19 ERROR - X-UI: Failure in running xray-core:exit status 23
2024/08/11 19:37:19 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/08/11 19:37:17 ERROR - X-UI: Failure in running xray-core:exit status 23
2024/08/11 19:37:17 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/08/11 19:37:15 ERROR - X-UI: Failure in running xray-core:exit status 23
2024/08/11 19:37:15 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/08/11 19:37:13 ERROR - X-UI: Failure in running xray-core:exit status 23
2024/08/11 19:37:13 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json
2024/08/11 19:37:11 ERROR - X-UI: Failure in running xray-core:exit status 23
2024/08/11 19:37:11 INFO - XRAY: infra/conf/serial: Reading config: bin/config.json

**Comment by MHSanaei** [comment]
مشکل از سرور خودتونه
