### ISSUE TITLE
مشکل در محدودیت آی پی

### ISSUE THREAD

**Issue by ALIEB75** [MHSanaei/3x-ui#2489]
**Describe the bug**
هنگام محدودیت گذاری آی پی ٬ در پنجره آی پی لاگ هیج آی پی ثبت نمیشود.
**Expected behavior**
 با خطای
 : no ip record 
مواجه میشوم . در حالی که کاربر آنلاین است.

**Screenshots**
![Screenshot 2024-08-12 031133](https://github.com/user-attachments/assets/6b2bedfe-1ded-4efc-89e9-217f64b03025)

**Version :**
 - 3X-UI Version : 2.3.9
 - Xray Version : 1.8.19

**Comment by MHSanaei** [comment]
Issue faqat baraie noskhe akhar baz konid
