### ISSUE TITLE
clients show delated user but not show lists of user online

### ISSUE THREAD

**Issue by Tili1420** [MHSanaei/3x-ui#250]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام و ارادت
توی بخش کلاینت که تازه اضافه شده فقط لیست دپلیت شده ها رو میاره .اون یوزرهایی که حذف شده اند قبلا رو میاره و هیچ کاربردی نداره.
لطفا لیست یوزرهای فعال رو قرار بدید و اونایی که غیر فعال شده اند نه اونایی که حذف شده اند
با تشکر

### Version of 3x-ui

1.2.2

### x-ui log reports or xray log

![20230413-01-48-58-PM](https://user-images.githubusercontent.com/122120996/231715835-67cd7f1e-8c9f-4752-be39-bdfaa4d29c32.jpg)

**Comment by Tili1420** [comment]
سلام و ارادت
توی بخش کلاینت که تازه اضافه شده فقط لیست دپلیت شده ها رو میاره .اون یوزرهایی که حذف شده اند قبلا رو میاره و هیچ کاربردی نداره.
لطفا لیست یوزرهای فعال رو قرار بدید و اونایی که غیر فعال شده اند نه اونایی که حذف شده اند
با تشکر

**Comment by MHSanaei** [comment]
به خاطر اینه دیتابیس شما قدیمیه بهترین راه حل اینه دیتابیس رو با برنامه های موجود ویرایش کنید و اکانت های قدیمی حذف شده رو پاک کنید
