### ISSUE TITLE
IP limit function can not work correctly

### ISSUE THREAD

**Issue by yuki-216** [MHSanaei/3x-ui#2513]
**Describe the bug**
The IP log feature only supports IPv4 addresses and does not record IPv6 addresses, which results in the IP limit function not working correctly.

**Expected behavior**
IPv6 addresses should also be recorded to ensure that the IP limit function operates effectively.

**Screenshots**
![image](https://github.com/user-attachments/assets/55e70ed6-f2cc-4cb8-bff3-5ec59dfe53bc)
![image](https://github.com/user-attachments/assets/08b76401-38f4-40ca-98aa-d4f57a23c272)

**Version (please complete the following information):**
 - 3X-UI Version : [e.g. 2.3.14]
 - Xray Version : [e.g. 1.8.24]

**Additional context**

**Comment by MHSanaei** [comment]
I know that

**Comment by yuki-216** [comment]
已收到（自动回复）

**Comment by NIKA5050** [comment]
> I know that for now it only supports IPv4.

درود بر شما

ایا قابلیت ip limit همچنان روی تانل بین دو سرور امکان پذیر نیست و راهی وجود نداره ؟

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/commit/2001d96148b04e00d53593ad20951f6d07cd0cea
you need to wait for new version
