### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by BobiDikson** [MHSanaei/3x-ui#2514]
My domain has expired. Now I can't get into the control panel. I deleted the domain in the database file, but after that the panel does not start. Is there any option to restore it? Or do I just have to reinstall it?

**Comment by MHSanaei** [comment]
Use reset settings on x-ui terminal

**Comment by BobiDikson** [comment]
After reset settings. I can't get into the panel
This site cannot provide a secure connection. Site 94.*.*.6 sent an invalid response. ERR_SSL_PROTOCOL_ERROR

**Comment by MHSanaei** [comment]
Use http

**Comment by BobiDikson** [comment]
@MHSanaei Access to * denied You do not have permission to view this page.
HTTP ERROR 403

**Comment by MHSanaei** [comment]
Check you current setting on your server

**Comment by BobiDikson** [comment]
@MHSanaei in the panel settings it was specified "listen domain" and now there is no access

**Comment by BobiDikson** [comment]
is it possible to somehow remove "listen ip" and "listen domain"?

**Comment by MHSanaei** [comment]
As I said, reset the settings on the X-UI terminal on your server.
Another way is to edit your database.

**Comment by BobiDikson** [comment]
I reset the settings on the X-UI terminal, but nothing changed. When editing the x-ui.db database on the /3x-ui/db/ path, Docker breaks. Maybe there is an editor for editing?

**Comment by MHSanaei** [comment]
https://sqlitebrowser.org/
