### ISSUE TITLE
v2.3.14 dublicate username crash xray

### ISSUE THREAD

**Issue by xmohammad1** [MHSanaei/3x-ui#2517]
hi there
if we add a user with name ali for example and another with name Ali xray will crash

**Comment by xmohammad1** [comment]
![image](https://github.com/user-attachments/assets/f6466447-797d-4fba-9021-e1339636136a)

**Comment by MHSanaei** [comment]
you can't have to user with same name, and don't use space as well

**Comment by MHSanaei** [comment]
you can't have two users with the same name, and don't use space as well

**Comment by xmohammad1** [comment]
i know

**Comment by xmohammad1** [comment]
you dont let we submit two user with same name like two ali but if one ali and other Ali panel will let it
