### ISSUE TITLE
pls dont allow add two user with same name

### ISSUE THREAD

**Issue by xmohammad1** [MHSanaei/3x-ui#2518]
hi there
panel dont let we add two user with same name like two ali but if one ali and other Ali panel will let it but result will crash xray

**Comment by MHSanaei** [comment]
as I said you can't have two users with the same name like 
Ali but you can have 
Ali and Ali123

**Comment by xmohammad1** [comment]
dude im not idiot i know what you say

**Comment by xmohammad1** [comment]
in panel you just prevent creating same names which is good , but problem is if with create same name and just capslock a letter panel will let us create user but result is crashing xray
so pls prevent creating same name with caps or without , thanks in advance
im not only one use my panel i have some admins , some times they forgot

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/commit/b4baf35ed8a14b58f9db6dde6a33b36d6095bcc1

**Comment by MHSanaei** [comment]
wait for next update

**Comment by xmohammad1** [comment]
thanks alot
