### ISSUE TITLE
Custom favicon

### ISSUE THREAD

**Issue by ssstroke** [MHSanaei/3x-ui#2519]
**Is your feature request related to a problem? Please describe.**
I'm running multiple servers running 3x-ui, so I may, sometimes, open the wrong panel when I have multiple admin panels opened in the browser.

**Describe the solution you'd like**
Additional setting in the admin panel that lets you upload custom image that will be used as a favicon for the panel. I think it is also worth adding the option to just set the favicon to the flag of desired country (since, I think, is the most common use case for this kind of feature).

**Describe alternatives you've considered**
N/A

**Additional context**
![Screenshot 2024-09-05 140104](https://github.com/user-attachments/assets/7047e1f5-2aee-4563-85d3-50a873241c2a)
Imagine the convenience of having a country flags here.

**Comment by MHSanaei** [comment]
we remove the favicon for security reasons
