### ISSUE TITLE
Logout Issue When Navigating to Inbounds in 3x-ui

### ISSUE THREAD

**Issue by MimSadBe** [MHSanaei/3x-ui#2521]
### Describe the bug

When I log in to the 3x-ui panel and navigate to the "Inbounds" section, the system automatically logs me out without any error message or warning. This happens consistently every time I click on the "Inbounds" tab.

### Version
3X-UI Version: 2.3.15
Xray Version: 1.8.24

### Additional context
This issue occurs regardless of the browser used (tested on Chrome and Firefox). I have cleared the cache and cookies, but the problem persists. The issue also affects multiple user accounts on the system.
Additionally, I suspect this bug might be related to the configuration where I filled the "URI Path" field in the panel settings with /blog/bank/.

**Comment by MHSanaei** [comment]
I can't find any issue everything works well, 
and it's better to remove your / on your URI Path and set something random and long to improve the security
