### ISSUE TITLE
Wireguard, Interface update .

### ISSUE THREAD

**Issue by AntonioDVZ** [MHSanaei/3x-ui#2523]
Good day. Your work is very useful! I would like to see the Wireguard interface manage all users, like when configuring Vless!
![wireguard](https://github.com/user-attachments/assets/c01ab403-2e23-4fd4-98d4-8f78fdfaa463)

**Comment by AntonioDVZ** [comment]
And also tell me how to get rid of advertising on YouTube using the x-ui panel?

**Comment by AntonioDVZ** [comment]
Where are wireguard&server part configs stored?

**Comment by MHSanaei** [comment]
We can't have a wireguard client interface, and also you can't block YouTube adv with panel

**Comment by centuriononon** [comment]
> We can't have a wireguard client interface, and also you can't block YouTube adv with panel

Hi! How do I add WireGuard peers dynamically? There is only option to update whole inbound which requires specifying all the peers at once. If I have many of them, then it's very risky to delete some of them by accident, and also it's additional network cost to always send the list.

Is there a way, or a planned enhancement to add/delete peers individually?
