### ISSUE TITLE
Inbound Port 443 + Nginx How to? 

### ISSUE THREAD

**Issue by skaneprime** [MHSanaei/3x-ui#2524]
Hey there! I'm using Nginx on my machine but to mask as a "website" I need to use port 443 for in inbound. How I can solve this problem? 

Is there a way to align both Inbound's 443 usage and Nginx? 

![image](https://github.com/user-attachments/assets/e54f3e99-cf8c-4251-b2c6-0187f4a76e8d)

**Comment by MHSanaei** [comment]
External proxy

**Comment by skaneprime** [comment]
Can you elaborate more please? I would really appreciate a more detailed solution to this
