### ISSUE TITLE
کارنکردن vmessدر cdn

### ISSUE THREAD

**Issue by aliamg1356** [MHSanaei/3x-ui#2531]
با درود
متوجه مشکل عجیبی در هسته xray شدم
اینکه وقتی از پزوتکل vmess و از cdnاستفاده میشود باید هسته xray1.8.9تنظیم شود و بالاتر از اون اتصال برقرار نمیشود
برای اتصال دو پنل با روش ریورس پنل به پنل با cdnاین مشکل نمایان میشود و بدون cdnاتصال برقرار میشود

**Comment by MHSanaei** [comment]
اگر هسته مشکلی هم داشته باشه باید به xray گزارش بدید کمکی از من برنمیاد
