### ISSUE TITLE
Inbound can't support client when the encryption is 2022-blake3-chacha20-poly1305

### ISSUE THREAD

**Issue by ssrshz** [MHSanaei/3x-ui#2532]
when the encryption is 2022-blake3-aes-256-gcm or chacha20-poly1305, client is alway available

![image](https://github.com/user-attachments/assets/1f0f19ed-c801-4d2f-86f8-e9e7704595f6)

but when the encryption is 2022-blake3-chacha20-poly1305, the client go away

![image](https://github.com/user-attachments/assets/5f83037f-48f4-45f2-9cd9-af8781453b6d)

**Comment by MHSanaei** [comment]
Because they don't support clients.
