### ISSUE TITLE
Can I possibly use second IP?

### ISSUE THREAD

**Issue by Zero0Main** [MHSanaei/3x-ui#2539]
Hello friend!)
I have two Ipv4 on my server. Can I possibly use both of them to make my connection security even better?

Maybe I can use one ip for getting requests from client and second to send these requests to the server, than back to the client.
Like: client -> ipv4-1 -> ipv4-2 -> server -> ipv4-2 - client

Or maybe first ip can get requests from client, send it to the server, than get reply and forward that reply to the second ip which will send it back to the client? 
client -> ipv4-1 -> server -> ipv4-1 -> ipv4-2 -> client

So is it possible to make this scheme work through panel?
Thanks for help!

**Comment by bigbugcc** [comment]
This does not conform to existing TCP/IP communication standards and cannot be implemented.

**Comment by MHSanaei** [comment]
No, you can't do this. Or, I don't know of any way to do it. Ask the Xray community.
