### ISSUE TITLE
The "x-ui" command does not work in the docker container

### ISSUE THREAD

**Issue by ankkk** [MHSanaei/3x-ui#2540]
**Describe the bug**
In the docker container, i try to use the "x-ui" command, but I get the message: "Your operating system is not supported by this script".

**Expected behavior**
The control menu should be displayed.

**Screenshots**
<img width="568" alt="image" src="https://github.com/user-attachments/assets/aab749c8-b2c3-4975-9206-54a5fa3fc336">

**Version (please complete the following information):**
 - 3X-UI Version : v2.3.15
 - Xray Version : v1.8.24

**Additional context**
arch: x86_64

```bash
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```

**Comment by MHSanaei** [comment]
It doesn't work on docker, use bash install for x-ui terminal
