### ISSUE TITLE
Docker build problem on Windows

### ISSUE THREAD

**Issue by diat01** [MHSanaei/3x-ui#2541]
Can anyone help me?

Command:

docker buildx build .

Error:

#15 [builder 6/6] RUN ./DockerInit.sh "amd64"
#15 0.499 /bin/sh: ./DockerInit.sh: not found
#15 ERROR: process "/bin/sh -c ./DockerInit.sh \"$TARGETARCH\"" did not complete successfully: exit code: 127
------
 > [builder 6/6] RUN ./DockerInit.sh "amd64":
0.499 /bin/sh: ./DockerInit.sh: not found
------
Dockerfile:19
--------------------
  17 |     ENV CGO_CFLAGS="-D_LARGEFILE64_SOURCE"
  18 |     RUN go build -o build/x-ui main.go
  19 | >>> RUN ./DockerInit.sh "$TARGETARCH"
  20 |
  21 |     # ========================================================
--------------------
ERROR: failed to solve: process "/bin/sh -c ./DockerInit.sh \"$TARGETARCH\"" did not complete successfully: exit code: 127

**Comment by MHSanaei** [comment]
We don't have a Docker build for Windows, but there is a release file for Windows that you can use.

**Comment by diat01** [comment]
Hello again,

What I want to do is I want to Dockerise the project and upload it to services like Google Cloud. Is it only possible to Dockerise it on a Linux system? Do you have any idea?
