### ISSUE TITLE
Subscription json

### ISSUE THREAD

**Issue by aspdotnet1** [MHSanaei/3x-ui#2545]
سلام ، لطفا اگه امکانش هس روتینگ های دلخواه رو به ساب جیسون اضاف کنین، مثلا سرویس های اپل رو دایرکت کنیم ، این مورد توی streisand کاربرد داره ، چونکه وقتی سرویس های اپل دایرکت نباشن ، نوتیف واتساپ و ... نمیاد

**Comment by MHSanaei** [comment]
سلام باشه این مورد رو در نظر میگیرم
