### ISSUE TITLE
باز نشدن پنل

### ISSUE THREAD

**Issue by amirzare021** [MHSanaei/3x-ui#2547]
با سلام و خسته نباشید خدمت شما جناب مهندس
من متاسفانه به یه مشکلی برخوردم که وقتی میزنم لاگین برای پنل یه ده دقیقه ای میچرخه تا لاگین بشه و هیچ لاگی هم برای ارور نداره
وقتی لاگ رو باز میکنی و یوزر پسورد رو میزنی میزنه لاگین کرده یوزر ولی اینور همینجوری داره میچرخه
![image](https://github.com/user-attachments/assets/7a59ac34-da1d-4b5b-9f94-caae1a68f09f)

**Comment by MHSanaei** [comment]
سلام اخرین نسخه پنل رو نصب کنید، اگر باز هم مشکل وجود داشت سرورتون رو اپدیت و ریبوت کنید

**Comment by amirzare021** [comment]
سلام مجدد
انجام شد ولی بازم فرقی نکرد
الان کلا باز نمیکنه همینجوری داره میچرخه

**Comment by MHSanaei** [comment]
پس مشکل از سرور شماست

**Comment by amirzare021** [comment]
باید کجاشو چک و برطرف کنم؟

**Comment by MHSanaei** [comment]
ایدی تلگرامتو بزار

**Comment by amirzare021** [comment]
mamvip_support
