### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by Arman-nsb** [MHSanaei/3x-ui#2548]
**Describe the bug**
Since the latest release, we cannot edit old users with uppercase letters(emails). could you revert this addition?

**Expected behavior**
we should be able to edit old users without getting errors caused by the new email validation process.

**Screenshots**
-

**Version (please complete the following information):**
Latest release 2.4.0

**Additional context**

**Comment by Arman-nsb** [comment]
EDIT: also please add @ to the valid characters. all of my users have @gmail at the end of their email .

**Comment by MHSanaei** [comment]
I know you can't do that; you need to change their email.
Good luck.
