### ISSUE TITLE
Does Direct Country RU work?

### ISSUE THREAD

**Issue by flockentanz** [MHSanaei/3x-ui#2549]
Hello @MHSanaei !
Thank you very much for this great repo!
I'm trying to set it up on my VPS. I installed it through bash command in readme, entered the panel, everything is working fine except one moment. In Xray Configs -> Basics -> Direct Country I'm trying to set Direct Connection to Russia IPs and Domains, but it has no effect on my traffic. The options are saving ok, I can see them after restarting Xray and panel, and also in advanced settings:
```
"routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      },
      {
        "type": "field",
        "outboundTag": "IPv4",
        "domain": [
          "geosite:google",
          "geosite:netflix"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:category-gov-ru",
          "regexp:.*\\.ru$"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:ru"
        ]
      }
    ]
  }
```

But then I'm trying to get my ip (with enabled VPN) through RU sites, like https://2ip.ru/ or https://www.reg.ru/web-tools/myip I'm still getting my VPN server's ip.
On the other hand, then I use routing rules on client side everything works fine, and "get my ip" sites show me my local ip.
Maybe I'm doing something wrong?

**Comment by MHSanaei** [comment]
![Screenshot_20240909_211910_Chrome.jpg](https://github.com/user-attachments/assets/d6a8f25a-4776-42f0-9136-0367c92a7e24)
