### ISSUE TITLE
subscription JSON cause V2rayNG to crash

### ISSUE THREAD

**Issue by ShahabSL** [MHSanaei/3x-ui#2551]
**Describe the bug**
in version 2.3.10 the json sub in outbound section looks like this:
"outbounds": [
      {
        "protocol": "vless",
        "tag": "proxy",
        "streamSettings": {
          "network": "tcp",
          "realitySettings": {
            "fingerprint": "chrome",
            "publicKey": "XXXXXXX",
            "serverName": "XXXXXXXX",
            "shortId": "XXXXX8fa05c",
            "show": false,
            "spiderX": "/9iXXXXXXRCPhn5j46cR7"
          }

but in 2.3.15 is like this:

"outbounds": [
      {
        "protocol": "vless",
        "tag": "proxy",
        "streamSettings": {
          "network": "tcp",
          "realitySettings": {
            "fingerprint": "chrome",
            "publicKey": "XXXXXXXXXXXX",
            "serverName": [
              "XXXXXXXXXXXX"
            ],
            "shortId": [
              "XXXXXXXXXXX"
            ],
            "show": false,
            "spiderX": "/hiXXXXXXeGsvrDSrA"
          }
          
          
 As you can see you give the client servername and short id as a array in comparison to past which it was a single value
  "serverName": [
              "XXXXXXXXXXXX"
            ],
            
  old:
   "serverName": "XXXXXXXX",

and this cause this particular config to cause crash in V2rayNG:
[
  {
    "dns": {
      "queryStrategy": "UseIP",
      "servers": [
        {
          "address": "8.8.8.8",
          "skipFallback": false
        }
      ],
      "tag": "dns_out"
    },
    "inbounds": [
      {
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "destOverride": [
            "http",
            "tls",
            "fakedns"
          ],
          "enabled": true
        },
        "tag": "socks"
      },
      {
        "port": 10809,
        "protocol": "http",
        "settings": {
          "userLevel": 8
        },
        "tag": "http"
      }
    ],
    "log": {
      "loglevel": "warning"
    },
    "outbounds": [
      {
        "protocol": "vless",
        "tag": "proxy",
        "streamSettings": {
          "network": "tcp",
          "realitySettings": {
            "fingerprint": "chrome",
            "publicKey": "HkACBCXXXXXXXXXXXXXXXXXTAmt0HZMMDk",
            "serverName": [
              "XXXXXXXXXXXXXXXXXXXXX"
            ],
            "shortId": [
              "66XXXXXXXXXXXXXXf09"
            ],
            "show": false,
            "spiderX": "/hie2XXXXXXXXXXXSrA"
          },
          "security": "reality",
          "sockopt": {
            "dialerProxy": "fragment",
            "tcpKeepAliveIdle": 100,
            "tcpMptcp": true,
            "tcpNoDelay": true
          },
          "tcpSettings": {
            "header": {
              "type": "none"
            }
          }
        },
        "settings": {
          "vnext": [
            {
              "address": "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
              "port": 443,
              "users": [
                {
                  "encryption": "none",
                  "flow": "xtls-rprx-vision",
                  "id": "XXXXXXXXXXXXXXXXXXXXX8071074af",
                  "level": 8
                }
              ]
            }
          ]
        }
      },
      {
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "tag": "direct"
      },
      {
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "tag": "block"
      },
      {
        "tag": "fragment",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "AsIs",
          "fragment": {
            "packets": "1-3",
            "length": "20-40",
            "interval": "4-8"
          }
        },
        "streamSettings": {
          "sockopt": {
            "tcpKeepAliveIdle": 100,
            "tcpNoDelay": true
          }
        }
      }
    ],
    "policy": {
      "levels": {
        "8": {
          "connIdle": 300,
          "downlinkOnly": 1,
          "handshake": 4,
          "uplinkOnly": 1
        }
      },
      "system": {
        "statsOutboundDownlink": true,
        "statsOutboundUplink": true
      }
    },
    "remarks": "XXXXXXXXXXXXXXXXXXXL1",
    "routing": {
      "domainStrategy": "AsIs",
      "rules": [
        {
          "network": "tcp,udp",
          "outboundTag": "proxy",
          "type": "field"
        }
      ]
    },
    "stats": {}

and in the old one it was:

 {
    "dns": {
      "queryStrategy": "UseIP",
      "servers": [
        {
          "address": "8.8.8.8",
          "skipFallback": false
        }
      ],
      "tag": "dns_out"
    },
    "inbounds": [
      {
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "destOverride": [
            "http",
            "tls",
            "fakedns"
          ],
          "enabled": true
        },
        "tag": "socks"
      },
      {
        "port": 10809,
        "protocol": "http",
        "settings": {
          "userLevel": 8
        },
        "tag": "http"
      }
    ],
    "log": {
      "loglevel": "warning"
    },
    "outbounds": [
      {
        "protocol": "vless",
        "tag": "proxy",
        "streamSettings": {
          "network": "tcp",
          "realitySettings": {
            "fingerprint": "chrome",
            "publicKey": "Ec_6aXXXXXXXXXXXXXXXvNpgZrDY",
            "serverName": "yoXXXXXXXXXXXXXXXXXX",
            "shortId": "XXXXXXXXXXXXXX",
            "show": false,
            "spiderX": "/9icRCPhxXXXXXXXXXXXXX"
          },
          "security": "reality",
          "sockopt": {
            "dialerProxy": "fragment",
            "tcpKeepAliveIdle": 100,
            "tcpMptcp": true,
            "tcpNoDelay": true
          },
          "tcpSettings": {
            "header": {
              "type": "none"
            }
          }
        },
        "settings": {
          "vnext": [
            {
              "address": "XXXXXXXXXXXXXXXXXXXXXX",
              "port": 443,
              "users": [
                {
                  "encryption": "none",
                  "flow": "xtls-rprx-vision",
                  "id": "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
                  "level": 8
                }
              ]
            }
          ]
        }
      },
      {
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "tag": "direct"
      },
      {
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "tag": "block"
      },
      {
        "tag": "fragment",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "AsIs",
          "fragment": {
            "packets": "1-3",
            "length": "20-40",
            "interval": "4-8"
          }
        },
        "streamSettings": {
          "sockopt": {
            "tcpKeepAliveIdle": 100,
            "tcpNoDelay": true
          }
        }
      }
    ],
    "policy": {
      "levels": {
        "8": {
          "connIdle": 300,
          "downlinkOnly": 1,
          "handshake": 4,
          "uplinkOnly": 1
        }
      },
      "system": {
        "statsOutboundDownlink": true,
        "statsOutboundUplink": true
      }
    },
    "remarks": "XXXXXXXXXXXX",
    "routing": {
      "domainStrategy": "AsIs",
      "rules": [
        {
          "network": "tcp,udp",
          "outboundTag": "proxy",
          "type": "field"
        }
      ]
    },
    "stats": {}

and it cause no crash or ignore in updating subscription

**Expected behavior**
it should not cause v2rayNG in mobile to crash and v2rayN on pc to ignore this config, it's a reality config by the way.

**Screenshots**
cannot send one but when you use it on android it gets ignored, if you import it in android manually it will cause app to crash, in pc it got ignored.

**Version (please complete the following information):**
 - 3X-UI Version new(has bug) : [2.3.15]
 - 3X-UI Version old(without bug) : [2.3.10]
 - Xray Version : 1.8.24]

بازم ممنون :))

**Comment by MHSanaei** [comment]
Try latest version
