### ISSUE TITLE
Why removing automatic warp installation from the script?

### ISSUE THREAD

**Issue by dev-kamran2001** [MHSanaei/3x-ui#2552]
This panel suffered 2 major mistakes so far in my opinion, one is the very recent removal of warp script and second is matching the registered tgid in the panel to Telegram usernames in order to give the user access to their clients statistics by the Bot which doesn't make any sense because many users don't set Username and they want to see their data usage whenever they want (I don't use newer panel versions because of this feature).

Some people including me still using versions older than 2.1.0, which we need to manually install WARP by the script provided in readme (which is also removed ignoring older panels, wonderful) or using the good automatic installer built into the script that got removed 12 hours ago.

For WARP, I understand that you need to giveup support to older panel versions to be able to better focus and work on new features, but removing the automatic warp installer script AND the instructions from readme on how to install WARP manually for old panels is straight up **f u** to older users not only giving up support.

**Comment by MHSanaei** [comment]
I understand the concerns regarding the recent changes, sticking to older versions isn’t a sustainable approach. By staying on outdated panel, users miss out on important updates, optimizations, and security improvements. The goal is to provide a better experience in the long term, and this means focusing on new features and ensuring smoother functionality.

While the removal of the WARP installer and instructions may seem inconvenient, it's important to streamline support for current versions. Keeping the panel updated ensures you're getting the best performance and staying aligned with future developments. I encourage you to move on to the latest version to benefit from these advancements.

**Comment by MHSanaei** [comment]
Regarding Telegram, if you try the latest version, you'll see how easy it is. You only need your Telegram chat ID, not username. You can obtain that with your bot using the "set Telegram user" option in a second.
