### ISSUE TITLE
اضافه کردن Uppercase و @ به بخش Email Verification

### ISSUE THREAD

**Issue by Alireza78na** [MHSanaei/3x-ui#2553]
عرض سلام و خسته نباشید

توی آپدیت جدید متوجه شدم که پنل برای بخش Email از Uppercase و کاراکتر @ پشتیبانی نمیکنه.
با توجه به اینکه این محدودیت توی ورژن های قبلی وجود نداشت ، همه ی Email مربوط به همه ی کانفیگ ها دارای Uppercase و @ هستن که باعث شده مشکلات خیلی زیادی به وجود بیاد.

بنابراین لطفا این موارد رو هم توی بخش Email Verification مجاز کنید تا بتونیم از آخرین نسخه ی پنل استفاده کنیم.
با تشکر از زحماتتون.

نسخه ی مورد استفاده: 2.4.0
آخرین نسخه بدون مشکل:
2.3.15

**Comment by MHSanaei** [comment]
این تغییر عمدا صورت گرفته و ایمیل در اصل یوزرنیم هست که در پنل استفاده میشود و نیازی هم به @ ندارد
موارد مجاز
a-z 0-9 -_.

**Comment by mohsenmalekii** [comment]
سلام در اپدیت جدید دیگه ایمیل فارسی نمیشه گذاشت اینم عمدا انجام شده ؟

**Comment by MHSanaei** [comment]
بله
