### ISSUE TITLE
After modifying the outbound rules, restarting results in an error.

### ISSUE THREAD

**Issue by MiniKoro** [MHSanaei/3x-ui#2556]
**Describe the bug**
After modifying the outbound rules, restarting results in an error.The modification was made to the Strategy in the original direct outbound rule. After modifying and saving, restarting prompts an error, and the xray kernel fails to start successfully.When examining the final configuration, you'll find that timeout and redirect are empty strings. After manually deleting these, it can start normally.

**Expected behavior**
After updating the configuration and restarting, no error occurs, and the kernel starts normally.

**Screenshots**
![image](https://github.com/user-attachments/assets/4c323e97-f8cc-4b7c-909b-ec8f8adfab85)
![1725952420435](https://github.com/user-attachments/assets/80aec217-c72c-4035-84d3-4c6d7a9e31fa)
![image](https://github.com/user-attachments/assets/28230f00-2c71-4b11-a0de-d7b0deaed6fe)

**Version (please complete the following information):**
 - 3X-UI Version : 2.4.0
 - Xray Version : v24.9.7

**Comment by MHSanaei** [comment]
Timeout should not be empty
