### ISSUE TITLE
ثبت نشدن ترافیک در Reality+grpc

### ISSUE THREAD

**Issue by nasiriscript** [MHSanaei/3x-ui#256]
سلام Reality+grpc برای من ترافیک رو ثبت نمی کنه داخل پنل و رو صفر میمونه میشه یه بررسی کنید؟

**Comment by MHSanaei** [comment]
قسمت لاگ پنل رو بررسی کنید 
اگر یوزری record not found داشت حذف کنید
بعد پنل رو ریستارت کنید مجدد بررسی کنید
لطفا issue رو با جزییات بیشتر باز کنید
