### ISSUE TITLE
لود نشدن یوزرها

### ISSUE THREAD

**Issue by OghabTeam** [MHSanaei/3x-ui#257]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

آقا جون مادرت این مشکلشو حل کن نسخه 1.0.8 رو نصب میکنم اوکی هست قشنگ همه یوزرها رو میاره بیشتر از هزار تا یوزر وجود داره.. اما از این نسخه به بعد رو که نصب میکنم از یوزر سومی به بعد رو نشون نمیده اصلا!! اگه تلگرام دارید بدید بیام پیوی دیتابیس رو بدم چک کنید شاید مشکل از دیتابیس باشه..!؟

![image_2023-04-13_16-18-25](https://user-images.githubusercontent.com/34192561/231753533-ff447238-b27d-4753-a3a7-f434f7aa30c0.png)

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
https://t.me/MHSanaei1
