### ISSUE TITLE
بردن reality پشت CDN

### ISSUE THREAD

**Issue by ashaghal** [MHSanaei/3x-ui#258]
### Welcome

- [X] Yes, I'm using the supported system. Only such systems are supported.
- [x] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام، آیا امکان بردن کانفیگ های reality  پشت کلادفلر وجود داره؟
در حال حاضر کانفیگ های دیگه و خود پنل پشت cdn هستن، اما کانفیگ های reality ( هر سه حالت tcp،grpc،trojan) پشت cdn وصل نمیشن

### Version of 3x-ui

1.2.2

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
خیر این کار ممکن نیست
