### ISSUE TITLE
اضافه شدن قابلیت حذف کلاینت های غیر فعال شده با یک کلیک

### ISSUE THREAD

**Issue by hosseinpv1379** [MHSanaei/3x-ui#259]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MHSanaei** [comment]
اگر اپدیت اخر v1.2.3 رو نصب کنید کلاینت های حذف شده ای که در پنل نمایش داده نمیشوند و فقط در دیتابیس هستند به صورت خودکار حذف خواهند شد
