### ISSUE TITLE
حذف امکانات مهم در ربات تلگرام!

### ISSUE THREAD

**Issue by megasoheilsh** [MHSanaei/3x-ui#260]
سلام ، در نسخه های جدید امکانات قبلی ربات مثل نمایش به اتمام رسیدن کاربران و پیغام ترافیک مصرفی حذف شده !

**Comment by MHSanaei** [comment]
چیزی حذف نشده 
چک کنید که داخل تنظیمات پنل chatid تلگرامتون رو درست زده باشید
