### ISSUE TITLE
infinity account was Depleted

### ISSUE THREAD

**Issue by mojvat** [MHSanaei/3x-ui#274]
.تو آخرین نسخه اکانت های نامحدود زمانی به صورت خودکار غیر فعال می شه و تاریخ 1970-1-1 3:30:10  در باکس تاریخ ثبت می شه

![Screenshot 2023-04-25 130227](https://user-images.githubusercontent.com/48915791/234235923-df0e29c8-678f-40dd-aac6-7d67882396a9.png)

**Comment by pouyaa82** [comment]
منم همین مشکل رو دارم

**Comment by MHSanaei** [comment]
نسخه اخر رو نصب کنید این باگ رفع شده 1.3.1

**Comment by mojvat** [comment]
من نسخه 1.3.1  هم نصب کردم کماکان این مشکل پابرجا است و کاربری که تاریخ انقضا براش تعریف نکنیم بعد از یک یا دو دقیقه  غیر فعال می شه

**Comment by mojvat** [comment]
در نسخه 1.3.2 مشکل حل شد. ممنونم
