### ISSUE TITLE
Delete All Depleted Users Together

### ISSUE THREAD

**Issue by arianaminiss** [MHSanaei/3x-ui#275]
سلام توی زمانی که مثلا روی سروری 200 تا یوزر باشه و به یک باره نیاز باشه 50 تا کاربر که حجمشون مثلا تموم شده رو حذف کنیم باید دونه دونه روی گزینه حذفشون کلیک بشه که این کار هم باعث میشه بار ها دیتابیس رفرش بشه و همه کاربر ها هی قطع بشن هم خیلی زمان بر هست اگه دکمه ای قرار داده بشه که همه depleted یوزر ها باهم حذف بشن عالی میشه

**Comment by MHSanaei** [comment]
نسخه اخر رو نصب کنید این ویژگی اضافه شده
