### ISSUE TITLE
محاسبه یکسان حجم کاربران در چند inbound متفاوت

### ISSUE THREAD

**Issue by s43id** [MHSanaei/3x-ui#278]
سلام ممنونم از زحماتی که تا به حال کشیدی برای ارتقا پنل فوق العادت

یه درخواستی دارم و فکر میکنم تنها چیزی که کم داره این پنل همینه

خیلی وقتا افراد از اینترنت های مختلفی استفاده میکنن و ما مجبور میشیم برای هر اینترنتی که دارن یه کانفیگ جدا بسازیم
این کانفیگ یکیش ممکنه مستقیم وصل باشه
یکیش ممکنه پشت CDN باشه

و به فرض مثال کاربر ما ۷۰ گیگ حجم داره
در حال حاضر راهی جز دستی چک کردن وجود نداره که ببینی میزان مصرف هر دو کانفیگ اگه از ۷۰ رد شده کانفیگ شخص رو خاموش کنی

خواهشی که داشتم اینه راهی اضافه کنی تا میزان مصرف کاربر روی پروتکل های مختلفی که داره به صورت یکسانی محاسبه بشه

این اپشن توی پنل مرزبان و هدیفای وجود داره و فقط x-ui هستش که این ویژگی فوق العاده رو نداره

**Comment by SAliAhadzadeh** [comment]
اگه بتونی اد کنی عالی میشه

**Comment by peymanch** [comment]
این قابلیت بسیار کاربردی هست که بتونی چندتا کانفیگ رو با یک ایمیل یکسان اختصاص بدید و مجموع حجم ترافیک مصرفی چند کانفیگ را حساب کنه
