### ISSUE TITLE
نصب چند پنل سنایی بر روی یک سرور

### ISSUE THREAD

**Issue by sepehrEslami81** [MHSanaei/3x-ui#280]
سلام.
اگر بخواهیم چند پنل بر روی یک سرور نصب بکنیم باید چکار کنیم؟
همچنین چرا داکر براش ارائه نکردین؟

**Comment by MHSanaei** [comment]
سلام دلیلی که میخاید چند پنل روی یک سرور داشته باشید چی هست؟
نه من علاقه ای به داکر ندارم

**Comment by SAliAhadzadeh** [comment]
مثلا یکیشونو بدم به دوستم
نمیخوام همین اصلی رو داشته باشه
یا مثلا بتونم یه یوزی نیم و پسورد جدید تعریف کنم که اون از اون یوزر پس استفاده کنه
هروقتم نخواستم حذفش کنم

**Comment by blackofxx** [comment]
این سوال منم هست، اگه سازنده پنل این سوال رو جواب بدن ممنون میشم

> سلام دلیلی که میخاید چند پنل روی یک سرور داشته باشید چی هست؟ نه من علاقه ای به داکر ندارم

**Comment by blackofxx** [comment]
> سلام. اگر بخواهیم چند پنل بر روی یک سرور نصب بکنیم باید چکار کنیم؟ همچنین چرا داکر براش ارائه نکردین؟

این سوال منم هست، اگه سازنده پنل این سوال رو جواب بدن ممنون میشم

**Comment by aliwxw** [comment]
سلام پنل نصب کردم اما هنگام وارد شدن به صفحه پنل باز نمیشه مشکل از کجاست

**Comment by hassanghasempour** [comment]
سلام.مهندس واقعا جا داره از طرف یک ملت تشکر منم ازتون. دو مورد  که چندوقتی هست مارو درگیر کرده و فکر کنم خواسته همه هست. یکی اینکه وقتی سرور تانل هست گزینه لیمیت کار نمیکنه و تعیین تعدادکاربری معنی نداره و عمل نمیکنه و از پنل ما سواستفاده میشه بشدت و کافیه به یکی از کانفیگهای ما دست پیدا کنن .شدیدا سو استفاده میکنن و متحمل هزینه های زیادی شدیم از این بابت. و دومین مورد اینکه سی پی یو پنل روی برخی از سرورها درگیر میشه و روی صد میاد. تقاضا دارم بر روی اپدیت جدید مارو از این مسائل نجات بدید. دعا گوی شما هستیم

**Comment by asoMansoury** [comment]
سلام

امکانش هست دستوراتی که موقع ساختن اکانت پشت دکه ها کال میکنید رو مستندات بدید که کسایی که لازم داشتن برن و پنل خودشون بنویسن
مثلا الان من میخوام یه پنل جدید شروع کنم منتهی دستورات مربوط به v2ray رو ندارم

**Comment by bahmanaraz** [comment]
سلام عرض ادب و خسته نباشید
ببخشید من سرورم ایران هستش و به هیچ عنوان به بات تلگرام وصل نمیشم چه دربات تلگرام پنل ویزویز چه بات خود پنل سنایی
قبلا یک آموزشی بود در گیت هاب که توسط اون آموزش با سرور ایران متصل میشدم ولی الان هر چقدر میگردم پیدا نمیکنم
ممنون میشم راهنمایی بفرمایید واقعا نیاز دارم 
با تشکر

**Comment by Sami4387** [comment]
پنل خوبیه فقط کاش قابلیت نمایش انلاین و افلاین رو بهش اضافه کنید خیلی خوب میشه

**Comment by aminkiller77** [comment]
سلام من پنل رو نصب کردم اما بازی ها باهاش بالا نمیاد مثل کلش اف کنلز چجوری میتونم این مشکل رو برطرف کنم ؟

**Comment by zendesher** [comment]
سلام و تشکر . پنل چینی دارم پنل شما رو میتونم بدون از دست دادن یوزرها جایگزین کنم؟ راهنمایی لطفا

**Comment by Ammargh89** [comment]
سلام دمتون گرم بابت کار خوبتون
من یسوال داشتم اگر راهنمایی کنید ممنون میشم 
یه vps ویندوزی گرفتم برای یه اکانت که باید حتما ip آمریکا باشه،الان مشکلم اینه که خیلی لگ تصویر داره 
حالا سوالم اینه من میتونم این vps سروری رو تبدیل به وی پی ن کنم؟ آیا برنامه شما قابلیت نصب روی ویندوز سرور داره؟
اگر این قابلیت نداره چه پیشنهاد دیگه ای دارید بتونم از همین  سرور استفاده کنم (هزینه زیاد بابتش داد و امکان کنسل کردن هم نیست)

**Comment by mtnyt13-debug** [comment]
پنل نصب کردم ولی باز نمیشه میزنم لینکش رو

**Comment by mahdi10812** [comment]
درود بر شما
وقتتون بخیر
با اینکه ip را در کلودفلر پشت ساب دامنه بردم اما همچنان پنل بدوم vpn باز نمیشود
یک باگ هم پیدا کردم که وقتی اینباند میسازم در بخش آدرس بارها تلاش کردم ip بزنم اما متاسفانه در لینک کانفیک ساب دامنه در بخش آدرس نوشته میشه که در کانفیگ های reality باید حتما ip نوشته بشه تا کار کنه
