### ISSUE TITLE
Shadowsocks TLS settings

### ISSUE THREAD

**Issue by possessed1911** [MHSanaei/3x-ui#283]
Currently TLS settings are missing from Shadowsocks inbound settings:
![image](https://user-images.githubusercontent.com/24365712/234480954-be605a52-afde-41b5-a8dd-57b0b47a06cb.png)
v2rayN has TLS settings for SS, so I modified my x-ui.db to include json TLS settings into SS inbound and it worked for me. As i can only connect though WS/TLS/CDN, it must be useful for others too.

**Comment by MHSanaei** [comment]
update to last version
