### ISSUE TITLE
Make the UI Invisible

### ISSUE THREAD

**Issue by mozilla-firefox** [MHSanaei/3x-ui#287]
سلام
برای اینکه کسی نتونه بفهمه پنل پروکسی روی سرور ما نصب هست، path و پورت پنل رو عوض میکنیم
اما با اینکه path عوض میشه از روش favicon میشه فهمید پنل پروکسی رو سرور ما نصب هست
![image](https://user-images.githubusercontent.com/41063376/234649400-4b677155-7fe5-4cb4-9e12-b6ef5d67fd53.png)
همچنین اگر بشه بجای اون ارور 404 یه ارور 3xx بزاریم و ریدایرکت کنیم به پورت 443 خیلی بهتر میشه
میدونم با ریورس پروکسی مشکل میتونه حل بشه-
اما استفاده از پنل بدون ریورس پروکسی هم مزایای خودش رو داره و خوبه که مشکل حل بشه
تشکر

**Comment by MHSanaei** [comment]
اینکار رو میتونید در nginx انجام بدید(یه صفحه فیک بالا بیارید) 
مهندس علیرضا قبلا روشش رو توضیح داده

**Comment by alireza0** [comment]
متوجه نمیشم! شما از پورت پنل صحبت میکنید و این پورت به کاربرها ربطی نداره!
مگر اینکه بیان sub بگیرن.
تعداد زیاد کاربر ها هم خیلی بهتر توسط nginx مدیریت میشن.

در ضمن یکی از درخواست های شما هم استفاده از فشرده سازی بود که nginx به صورت پیش فرض انجام میده.
اینجوری هم از امکانات استفاده میکنین و هم میتونین /sub رو روی یه دامنه دیگه بیارید بالا که اصلا آیکون نداشته باشه
```
server {
       listen       80;
        server_name  sub.example.com;
        location / {
                proxy_pass http://panel.example.com:54321/sub/;
        }
 }
```

**Comment by vooroojak0097** [comment]
دوستان این ارور مربوط به چی میشه ؟
panel Failed to start, Probably because it takes longer than two seconds to 
start, Please check the log information later

**Comment by alireza0** [comment]
دوست عزیز
قرار نیست ما برای درخواست شما کل مقررات وب و روش کار مرورگرها رو عوض کنیم.
فایل favicon همونطور که گفتم، به صورت استاندارد در هر مرورگر، از ریشه وبسایت خونده میشه و cache میشه.
ما هیچ کد خاصی براش ننوشتیم و نمیتونیم استثنا کنیم.

**Comment by alireza0** [comment]
همیشه اضافه یا کم کردن آپشن های ظاهری برای ما دردسر بوده. هم وقت زیادی گرفته و هم هرکسی یه جوری دلش میخواد.
سعی من این بوده که به ساده ترین روش ممکن امکانات رو اضافه کنم و کاری که راه حل ساده دیگه ای داره رو برای همه اجبار نکنم.
بهترین راه همیشه کاملترین راه نیست. این پنل از نظر ظاهری و ساختاری کلی اشتباه اصولی داره.
بهتر و بدتر بودن یه ویژگی رو (به شخصه برای من) بیشتر سودش برای جامعه و ارزش زمانی که براش میذارم مشخص میکنه.

دستور شما با کمی تغییر انجام میشه. یه ساده سازی هم کنارش انجام دادم.
با این روش دیگه نمیشه همه جا آیکون رو دید. امیدوارم کسی نیاد اصرار کنه که آیکون روی لینک ساب رو لازم داشتم.

در ضمن درجریان باشید، فقط کسانی که بهشون آدرس ساب رو میدین از دامنه و IP  و پورت پنل شما مطلع هستند. معمولا هم سودی نداره توی مرورگر بازش کنن!
درکل برای امنیت پنل هم بهتره این پورت و ساب رو جدا کنید.
