### ISSUE TITLE
چند سوال درباره ی پنل

### ISSUE THREAD

**Issue by SAliAhadzadeh** [MHSanaei/3x-ui#289]
سلام
خسته نباشی
واقعا دمت گرم عالی
میگم نمیشه اپشنی اضاف کنی که برای هر ایمیلی که ایجاد میکنیم یک ساپسکریپشن بسازه و یا بتونیم از یک ایمیل در چند سرور استفاده کنیم؟
و ربات یه قسمتش درست کار نمیکنه
Your configuration is not found!
Please ask your Admin to use your telegram username in your configuration(s).

Your username: 
یوزر رو اد کردم ولی میگه اد نیس
اپدیتم کردم پنل رو
ولی هنوز مشکل حل نشده.

**Comment by SAliAhadzadeh** [comment]
و چطور میشه ایکون 3x رو کاستومایز کرد؟

**Comment by MHSanaei** [comment]
ایدی تلگرام رو بدون @ قرار بدید
