### ISSUE TITLE
تک کاربره کردن و ip limit

### ISSUE THREAD

**Issue by mmdh-ir** [MHSanaei/3x-ui#290]
سلام وقت بخیر 
راهی برای محدود کردن آیپی برای وقتی که از تانل استفاده میکنیم وجود داره؟
چون قاعدتا وقتی تانل هست آیپی سرور ایران میفته نه آیپی شخصی که متصل شده

**Comment by mehdikhody** [comment]
باید پنل X-UI را روی سرور ایران نصب کنید و کاربران را داخل آن اضافه کنید.
همچنین یک پنل X-UI هم باید روی سرور خارج نصب کنید. سپس یک inbound با هر پرتوکلی (پیشنهاد میکنم تروجان با پورت 443) و نامحدود روی سرور خارج ایجاد کنید و در تنظیمات Xray پنل ایران، یک Outbound به آن inbound که در سرور خارج دارید، بسازید.

**Comment by amirvp** [comment]
> باید پنل X-UI را روی سرور ایران نصب کنید و کاربران را داخل آن اضافه کنید. همچنین یک پنل X-UI هم باید روی سرور خارج نصب کنید. سپس یک inbound با هر پرتوکلی (پیشنهاد میکنم تروجان با پورت 443) و نامحدود روی سرور خارج ایجاد کنید و در تنظیمات Xray پنل ایران، یک Outbound به آن inbound که در سرور خارج دارید، بسازید.


میشه خواهش کنم این رو بیشتر توضیح بدین؟ چطور باید این outbound و inbound ها ساخته بشن؟
