### ISSUE TITLE
اتصال و لاگین با وبسرویس

### ISSUE THREAD

**Issue by unknownssassss** [MHSanaei/3x-ui#291]
سلام
وقتی که به ادرس حالا
domain.com:2096/sub/login
درخواست میزنم و یوزرنیم و پسورد رو میفرستم ی متن جیسون بهم میده ک ساکسس بوده کوکی و ... ست شده
ولی موقع درخواست های دیگه مثل
domain.com:2096/sub/list
یا... خطای 404 بهم برمیگردونه
اشتباهم کجاست؟چیو اشتباه میزنم
ادرس رو هم به صورتای مختلف وارد میکنم ولی بازم ب ارور برمیخورم
domain.com:2096/sub/list
domain.com:2096/sub/xui/API/list
domain.com:2096/sub/xui/API/inbounds/list
کلا در هر صورت ارور 404 میگیرم
چیکار کنم؟

**Comment by MHSanaei** [comment]
/panel/api/inbounds
more info
https://github.com/MHSanaei/3x-ui#api-routes

**Comment by nsa14** [comment]
سلام 
منم دقیقا همین مشکل رو دارم میشه لطفا بیشتر راهنمایی کنید کجارو باید تغییر بدم

*** یه باگ مهم:***
روی ورژن ١.٧.۶ اکانت ساخته میشه ولی کار نمیکنهههههه اصلا کانفیگ ساخته شده
