### ISSUE TITLE
User IP Limit

### ISSUE THREAD

**Issue by qar4al** [MHSanaei/3x-ui#293]
در مورد ip limit روش یکم کار کنید چون همزمان که چند کاربر متصل میشن عملا کار نمیکنه و اون لیمیت که مقدارشو 1 میزاریم به نوعی این وسط هیچه و همه ip های متصل رو رد میکنه لطفا روی این مورد کار کنید سپاس از زحماتتون 🙏🙏🌹🌹

**Comment by peymanch** [comment]
دقیقا منم تست کردم اصلا" کار نمیکنه!

**Comment by nasiriscript** [comment]
از کلادفلر استفاده میکنید؟

**Comment by peymanch** [comment]
نه Reality آی پی مستقیم

**Comment by nasiriscript** [comment]
> نه Reality آی پی مستقیم

آره کار نمیکنه

**Comment by rafatidev** [comment]
منم استفاده کردم ولی کار نمیکنه حتی توی لاگ جلوی آی پی لیمیت هم دقیقا آیپی هایی که متصل شدن رو با کاما نشون میده در حالی که آی پی لیمیت روی 1 هستش.

**Comment by armansoheili** [comment]
متاسفانه نمادین هستش اصلا کار نمیکنه امیدوارم زودتر حل بشه خیلی مهمه
