### ISSUE TITLE
Add Quic and disable udp outbound

### ISSUE THREAD

**Issue by DarkZo0m** [MHSanaei/3x-ui#299]
سلام اگر امکانش باشه داخل کانفیگ های reality این دو آپشن رو اضافه کنید

![20230428_204357.jpg](https://user-images.githubusercontent.com/59771519/235211675-96157a6f-dd11-407c-acfa-d303d851166d.jpg)

![20230428_204448.jpg](https://user-images.githubusercontent.com/59771519/235211726-36e84894-b160-4d6f-9058-7df29e69e5f5.jpg)

**Comment by nasiriscript** [comment]
اون بلاک رو خودت داخل تنظیمات میتونی وارد کنی
