### ISSUE TITLE
Request to include Postman Collection in README.md

### ISSUE THREAD

**Issue by mehdikhody** [MHSanaei/3x-ui#303]
Dear @MHSanaei,

I would like to express my gratitude for your hard work and dedication in inspiring others to contribute to the X-UI project. In light of this, I have prepared a Postman Collection to help others gain a better understanding of the API, as there is currently no documentation available.

I kindly request that you include this collection in the README.me file so that it is easily accessible to everyone. This will enable users to have a better grasp of the API and understand what parameters they need to send to the backend server.

Please find the link to the Postman Collection here: [Postman Collection](https://gist.github.com/mehdikhody/9a862801a2e41f6b5fb6bbc7e1326044)

Relatable issues: #186 and #255.

Thank you for your attention to this matter.

Best regards,

@Mehdikhody.

**Comment by MHSanaei** [comment]
Dear mehdi,

Thank you for your kind words of appreciation and for sharing the Postman Collection you have prepared to help others understand the API for the 3X project. We appreciate your dedication and hard work in inspiring others to contribute to the project.

Regarding your request to include the Postman Collection in the README.me file, I would like to confirm whether you have tested the API using this collection yourself? This is an important step to ensure that the documentation is accurate and complete before it is shared with others. Once you have tested it, please let us know, and we will be happy to include it in the README.me file for everyone's benefit.

We would also like to thank you for bringing any issues or queries related to this matter to our attention through the GitHub issues #186 and #255. We will address these issues promptly and keep you informed of any updates.

Once again, we appreciate your contribution to the 3X project and your willingness to help others learn and contribute. Please feel free to contact us if you have any further suggestions or contributions.

Best regards,

MHSanaei

**Comment by mehdikhody** [comment]
I have conducted comprehensive testing on the routes, parameters, and responses that the XUI server may necessitate or return. Additionally, I have made necessary updates to the Postman collection file to reflect these examples. By utilizing this collection, developers can effortlessly examine the anticipated responses without the need to connect an actual XUI server to Postman.

<img width="890" alt="2023-04-29 (4)" src="https://user-images.githubusercontent.com/22590626/235311914-92862897-7e53-4b88-8777-b6bc082494ee.png">

**Comment by mehdikhody** [comment]
**📚 Announcement: Updated Documentation:**
Attention, developers! 🌟 We've heard your questions and have crafted a comprehensive documentation covering everything you need to know about our Postman collection and the MHSanaei panel API. This detailed guide tackles authentication, inbounds management (listing, details retrieval, updates, deletions), client operations (retrieval, updates, deletions, traffic resets), and much more! 🚀

To delve into the documentation and unlock all the details, click on the link below:
🔗 [Read Documentation](https://documenter.getpostman.com/view/16802678/2s9YkgD5jm)

### Fork collection
[<img src="https://run.pstmn.io/button.svg" alt="Run In Postman" style="width: 128px; height: 32px;">](https://god.gw.postman.com/run-collection/16802678-1a4c9270-ac77-40ed-959a-7aa56dc4a415?action=collection%2Ffork&source=rip_markdown&collection-url=entityId%3D16802678-1a4c9270-ac77-40ed-959a-7aa56dc4a415%26entityType%3Dcollection%26workspaceId%3D2cd38c01-c851-4a15-a972-f181c23359d9)

Happy exploring! 📖✨

**Comment by AsunaYukky** [comment]
Hi team.
I make some changes at previous postman collection.
Add variables for http or https connection type and alternative panel uri. 
Link to collection
[https://www.postman.com/asunayukky/workspace/public/collection/31597454-5231292b-a994-4daf-a9d8-33a91543ca30?action=share&source=copy-link&creator=31597454](url)
