### ISSUE TITLE
نحوه اتصال ربات خودساخته به پنل

### ISSUE THREAD

**Issue by Bestsenator** [MHSanaei/3x-ui#304]
سلام وقتت بخیر
چطوری میشه به پنل وصل بشم و اطلاعات یه کانفیگ رو بر اساس برای مثال لینک کانفیگ واکشی بکنم
من یه ربات نوشتم و میخوام خودم پنلش رو شخصی سازی بکنم

**Comment by mehdikhody** [comment]
#303
