### ISSUE TITLE
راهنمایی برای بلاک کردن برخی شبکه های اجتماعی

### ISSUE THREAD

**Issue by lostsoul6** [MHSanaei/3x-ui#305]
سلام عزیزان وقت بخیر .
بنا به دلایلی میخوام روی یکی از سرورهای خودم ، دسترسی به سایت یوتیوب و شبکه های اجتماعی مانند تلگرام ، اینستاگرام ، توییتر و غیره رو ببندم . توی پنل 3X-UI دیدم یه آپشن برای محدود کردن سایت های پورن بود که وقتی فعالش کردم ، کانفیگ زیر رو به xray اضافه کرد :

`{
        "type": "field",
        "outboundTag": "blocked",
        "domain": [
          "geosite:category-porn"
        ]
      }
    ]
  },`

حالا سوالم اینه چطور میتونم مثل همین ، یک رول بنویسم که سایت هایی مانند یوتیوب و شبکه های اجتماعی مطرح رو بلاک کنه روی یکی از سرورام .

ممنون میشم اگر راهنمایی کنید .

**Comment by nasiriscript** [comment]
domain:youtube.com

**Comment by lostsoul6** [comment]
> domain:youtube.com

مسئله اینجاست که آدرس سرورهایی که ویدیوهای یوتیوب روش هست روی خیلی دامنه های دیگه هست . اونا رو چی کار کنم و چطوری به دست بیارم ؟ برای شبکه های اجتماعی چی ؟

**Comment by nasiriscript** [comment]
فکر نکنم راهی باشه، بعضی از سایت ها مثل category-porn یا netflix از قبل تعریف شده اند.

**Comment by lostsoul6** [comment]
ببخشید میشه ترافیک به یک رنج آی پی رو بست ؟ مثلا اگر رنج آی پی تلگرام رو داشته باشیم ؟

91.105.192.0/23
91.108.4.0/22
91.108.8.0/22
91.108.12.0/22
91.108.16.0/22
91.108.20.0/22
91.108.56.0/23
91.108.58.0/23
95.161.64.0/20
149.154.160.0/21
149.154.168.0/22
149.154.172.0/22
185.76.151.0/24
2001:67c:4e8::/48
2001:b28:f23c::/48
2001:b28:f23d::/48
2001:b28:f23f::/48
2a0a:f280:203::/48

فرمت بلاک کردن رنج آی پی چطور هست؟

**Comment by alirezax5** [comment]
> geosite


> 


geosite:youtube
geosite:whatsapp
geosite:telegram
geosite:instagram

برای مشاهده لیستشون به : https://github.com/v2fly/domain-list-community/tree/master/data سر بزن

**Comment by lostsoul6** [comment]
واتس اپ نداره توی لیست . در مورد تلگرام هم اپش مسدود نمیشه فقط سایتش رو میبنده یعنی با اپش عادی میشه کار کرد . باید رنج آی پی های تلگرام رو ببندم . شما میدونید فرمتش چطوری هست برای بستن رنج آی پی ؟

**Comment by alirezax5** [comment]
> واتس اپ نداره توی لیست . در مورد تلگرام هم اپش مسدود نمیشه فقط سایتش رو میبنده یعنی با اپش عادی میشه کار کرد . باید رنج آی پی های تلگرام رو ببندم . شما میدونید فرمتش چطوری هست برای بستن رنج آی پی ؟

واتس اپ داره ، چون تعداد فایلاش بالاست همشو نمایش نمیده

و رنج آیپی هم داخل قانون
"ip":[ "0.0.0.0/24"]
میزارید
