### ISSUE TITLE
نحوه دسترسی به سرور برای chat gpt

### ISSUE THREAD

**Issue by Bestsenator** [MHSanaei/3x-ui#311]
سلام وقتتون بخیر
دسترسی به chatgpt با کانفیگی که هست بالا نمیاد
چطوری کانفیگ رو ادیت بزنم تا بشه chatgpt رو هم بیاره بالا ؟؟

**Comment by MHSanaei** [comment]
https://t.me/panel3xuiGroup/1/69068

**Comment by Bestsenator** [comment]
مشکلی که داره اینه که من توی پنلم install warp نمیبینم

**Comment by MHSanaei** [comment]
پنلتون رو اپدیت کنید با x-ui و گزینه 2
یا لینک bash رو اجرا کنید 
bash <(curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh)

**Comment by Bestsenator** [comment]
چطوری از کانفیگ ها که بک اپ گرفتن دوباره بذارم داخلش؟
