### ISSUE TITLE
QR code bug

### ISSUE THREAD

**Issue by Incognito-Coder** [MHSanaei/3x-ui#317]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi,when trying to import or scan QR codes generated by panel,client returns `null` error.

### Version of 3x-ui

<details>

```console
v1.3.4
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by esmaeilifardi** [comment]
در تم شب لبه بارکدها حذف میشه لذا خطای اسکن در گوشی میده
