### ISSUE TITLE
نصب چند  x-ui روی یک سرور بطور همزمان

### ISSUE THREAD

**Issue by Akbar2750** [MHSanaei/3x-ui#320]
سلام - از اونجاییکه وقتی تعداد یوزرهای یک دامنه زیاد میشه، سیستم فیلترینگ سریعتر آی پی مربوطه را شناسایی می کند ،و اون رو فیلتر میکنه، اگر امکان این باشه که روی فقط یک سرور **بطور همزمان** چندتا دامنه با IPهای مستقل داشته باشیم که روی هر یک بتوان پنل مستقلی نصب کرد ، در اینصورت با استفاده از فقط یک سرور می توان تعداد کانفیگ های کمتری را در هر IP  تعریف کرد تا لو رفتن آی پی سخت تر بشه.
آیا این امکان را میشه بوجود آورد؟
ممنون

**Comment by alireza0** [comment]
متونید این قابلیت رو بدون نصب چند سرور انجام بدید.
اجرای چند x-ui  به سرعت هم لطمه میزنه.

برای اینکار توی بخش Listen IP برای هر سرویس، میتونید یکی از IP  های سرور رو استفاده کنید.
اگر هم بخواید میتونید برای هر سروریس خروجی متفاوتی رو ایجاد کنید

**Comment by Akbar2750** [comment]
> متونید این قابلیت رو بدون نصب چند سرور انجام بدید. اجرای چند x-ui به سرعت هم لطمه میزنه.
> 
> برای اینکار توی بخش Listen IP برای هر سرویس، میتونید یکی از IP های سرور رو استفاده کنید. اگر هم بخواید میتونید برای هر سرویس، خروجی متفاوتی رو ایجاد کنید

ممنون از پاسخ تون
متوجه منظورتون از خروجی برای هر سرویس نشدم. اگر امکان داره میشه لطف کنید و راجع به خروجی سرویس بیشتر راهنمایی کنید.

**Comment by alireza0** [comment]
تنظیم دامنه و IP توی پنل DNS سرویس دهنده شما تنظیم میشه. بسته به امکانات اونجا میتونید هر طوری که بخواید تنظیم کنید.
اگر منظورتون certificate بود، بله به ازای هر دامینی میتونید گواهی جدایی درخواست بدید.

برای اینکه بتونید خروجی ها رو جدا کنید بهتره در مورد Routing و Outbound ها توی xray-core مطالعه کنید.
این نمونه روتینگ برای شما:
```
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "inboundTag": "inbound-443",
        "outboundTag": "server1"
      },
      {
        "type": "field",
        "inboundTag": "inbound-2053",
        "outboundTag": "server2"
      },
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      }
    ]
  },
```
[اینجا](https://github.com/MHSanaei/3x-ui/issues/151#issuecomment-1496043139) به صورت نمونه توضیح دادم که چطور میتونین خروجی رو تنظیم کنید و تگ بزنید.
منابع اصلی:
https://xtls.github.io/config/outbound.html#outboundobject
https://xtls.github.io/config/routing.html
