### ISSUE TITLE
Panel's Api

### ISSUE THREAD

**Issue by DevNima-PG** [MHSanaei/3x-ui#322]
سلام خسته نباشید ❤️ میخواستم از API پنل استفاده کنم یه مشکلی تو ایمپورت کردن جیسون خوردم و خودم دست ب کار شدم و از روش ریکوعست ساختم زدم به سرور. اما مشکلی پیش اومده که بخاطر نبودن داکیومنت کلی واسه API نتونستم تنهایی رفعش کنم.
خوشحال میشدم کمک میکردید. پایین عکسش رو درج میکنم.

![Screenshot 2023-05-03 133944](https://user-images.githubusercontent.com/85389307/235876679-00024220-6a82-4de2-847a-5b0170f357bc.png)

## ارورش یه جورایی مشخصه اما چطور میشه موقع ریکوعست زدن آبجکت فرستاد چیزی مثل ستینگز رو!!؟

**Comment by alireza0** [comment]
درود
نحوه فرستادن اشتباهه. فیلد settings باید text باشه:
```
{
  "id": 5,
  "settings": '{
    "clients:" : [
        {
          ...
        }
     ]
  }'
}
```
