### ISSUE TITLE
چطور میشه کانفیگها رو به سرور جدید منتقل کرد؟

### ISSUE THREAD

**Issue by pmgithub67** [MHSanaei/3x-ui#326]
فایل بکاپ که توی بات تلگرام فرستاده میشه رو به چه آدرسی در سرور جدید منتقل کرد؟ همین دو فایل رو انتقال بدیم کفایت میکنه؟

**Comment by pmgithub67** [comment]
> > فایل بکاپ که توی بات تلگرام فرستاده میشه رو به چه آدرسی در سرور جدید منتقل کرد؟ همین دو فایل رو انتقال بدیم کفایت میکنه؟
> 
> دوتا فایل رو باید منتقل کنی یکی دیتا بیس (db) و یکی هم config.json اگه آدرس (domain) عوض شده باشه باید فایل dbرو با مثلا db browser ادیت کنی و ادرس پنل و فایل های certificate رو تغییر بدی و جایگزین کنی

من فایل دیتا بیس رو جابجا میکنم، و سپس ری استارت پنل رو میزن، ولی هیچ کانفیگی اضافه نمیشه.
در مورد فایل config.json هم نمیدونم باید به چه آدرسی انتقال بدم.
مشکل اضافه نشدن کانفیگ هاست

**Comment by Aronablade** [comment]
بعد از انتقال فایل دیتابیس ، میری داخل پنل جدیدت که نصب کردی ریستارت پنل میزنی ، بعد میری تو ssh و x-ui رو مینویسی تا منوش بازی بشه ، گزینه ۱۰ ریستارت x-ui رو‌ میزنی اگه بدون error نداد یعنی همه چیز درسته و میری صفحه رو رفرش میکنی و کانفیگها میاد

**Comment by pmgithub67** [comment]
ممنون از راهنمایی دوستان. بعد جابجایی فایل x-ui.db از داخل خود پنل ری استارت زدم و سپس رفتم توی هتزنر و سرور رو یکبار خاموش و روشن کردم و تمام.

**Comment by Aronablade** [comment]
> ممنون از راهنمایی دوستان. بعد جابجایی فایل x-ui.db از داخل خود پنل ری استارت زدم و سپس رفتم توی هتزنر و سرور رو یکبار خاموش و روشن کردم و تمام.

با روشن خاموش کردن سرور درواقع عملا xray رو دوباره اجرا میکنید ، همین کار رو بدون خاموش کردن سرور و با رفتن به ssh و تایپ x-ui و تایپ ۱۰ میتونید xray رو‌ ریستارت کنید و حل میشه

**Comment by arisalehi** [comment]
سلام.
منم فایل db رو بردم در فولدر x-ui گذاشتم. فایل config.json هم در local/x-ui/bin .

بعد x-ui restart رو زدم. ولی پنل بالا نیوومد.

ارور زیر رو بهم داد : به نظرتون مشکل از چیه؟؟؟

![Capturessssss](https://user-images.githubusercontent.com/70378764/236683982-b0d9708e-0c77-4276-9350-9bc7ed95fc3a.JPG)

**Comment by pmgithub67** [comment]
> سلام. منم فایل db رو بردم در فولدر x-ui گذاشتم. فایل config.json هم در local/x-ui/bin .
> 
> بعد x-ui restart رو زدم. ولی پنل بالا نیوومد.
> 
> ارور زیر رو بهم داد : به نظرتون مشکل از چیه؟؟؟
> 
> ![Capturessssss](https://user-images.githubusercontent.com/70378764/236683982-b0d9708e-0c77-4276-9350-9bc7ed95fc3a.JPG)

برای منم از طریق دستور ریستارت خطا میداد، ولی از داخل پنل ریستارت با موفقیت انجام میشد و برای اینکه کانفیگ ها رو نشون بده نیاز بود که یکبار سرور رو از داخل هتزنر خاموش و روشن کنم. برای من اینجوری جواب داد.
