### ISSUE TITLE
Bug in UpdateClient Method API

### ISSUE THREAD

**Issue by PouryaDe** [MHSanaei/3x-ui#334]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام وقتتون بخیر
در متد آپدیت کلاینت `"/updateClient/:clientId"` وقتی یه uuid رو آپدیت میکنم میره اولین کلاینت رو ادیت میزنه!
لطفا این مورد رو بررسی کنید

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by yasinabbasiiii** [comment]
دقیقا این مشکل وجود دارد، کسی راه حلی پیدا نکرد!
