### ISSUE TITLE
IP limit problem

### ISSUE THREAD

**Issue by mohammadrezafarihi** [MHSanaei/3x-ui#338]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

ip limit dosnt work, it is an important feature, please solve it or if you have any solution write for me thanks

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by peymanch** [comment]
دقیقا برای منم روی reality کار نمیده ای کاش مشکلش حل میشد

**Comment by RezaSalaari** [comment]
سلام منم این مشکلو دارم و ایپی لیمیت کار نمیکنه!!
