### ISSUE TITLE
مشکل nekoray

### ISSUE THREAD

**Issue by htzserv** [MHSanaei/3x-ui#344]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

vless://53c87f82-d0f0-42ab-971e-885ff17f8df4@xxxxx:10263?type=tcp&path=%2F&host=snapp.ir&headerType=http#02141-M10

vless://5b037b2b-438e-44c6-b68c-308d65ae3f79@xxxxx:32657?security=&type=tcp&headerType=http&host=snapp.ir#0122%20

لینکایی که اکسپورت میشن از سرور هایی ک تی ال اس روش فعال نیست
رو نکوری جواب نمیده
چون تو لینک خروجی سکیوریتی ای ست نمیشه
در نتیجه اتوماتیک تی ال اس فعال میکنه براش

لینک بالا لینک اول لینک پنل ثناییه

دومی کافکا

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
مشکل از سمت nekoray هست چرا که حالت دیفالت این برنامه tls نیاز دارد و شما از tls استفاده نکرده اید
