### ISSUE TITLE
mandeh hajm va etebar karbar dar sub

### ISSUE THREAD

**Issue by solidwar** [MHSanaei/3x-ui#345]
tazegi ba panneli ashna shodam keh dar remark(name) karbar agar dastoor  {DATA_USAGE} / {DATA_LIMIT} : {DAYS_LEFT}  vared konim . karbar ba har bar update link sub etelate serversh ro mitooneh bbineh 
aya emkan in ghabeliyat dar pannel shoma ham vojood darad? agar nist! ezafeh mikonid. mamnoon

**Comment by Alireza-WP** [comment]
salam , momkene esme paneli ke in ghabeliat ro dare benvisid? kheyli donbalesh gashtam peyda nakardam.

**Comment by ishark2022** [comment]
marzban

**Comment by X-Oracle** [comment]
I already requested this in https://github.com/alireza0/x-ui/issues/376 but no response so far .

**Comment by MHSanaei** [comment]
در نسخه 1.7.1 اضافه شد
