### ISSUE TITLE
مشکل Depleted شدن یوزر

### ISSUE THREAD

**Issue by aliwebto** [MHSanaei/3x-ui#350]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام
من از طریق api تاریخ انقضا کاربر رو ویرایش میکنم 
یعنی inbound رو میگیرم - تغییرات رو اعمال میکنم - inbound رو آپدیت میکنم 

ولی تاریخ انقضا جدید که لحاظ میکنم اعمال نمیشه و یوزر Depleted میشه 
![image](https://user-images.githubusercontent.com/70484690/236587770-ecfac721-0c7f-4ba8-96bd-36d932b663a1.png)

### Version of 3x-ui

<details>

```console
1.3.4
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
باید برای اون یوزر یکبار ریست ترافیک اعمال بشه
