### ISSUE TITLE
Error 404 if user UUID is missing for any action

### ISSUE THREAD

**Issue by hamidabbaasi** [MHSanaei/3x-ui#352]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام

اگر uuid یکی از یوزرها پاک بشه و این تغییر اعمال بشه دیگه هیچ راهی برای درست کردن ش وجود نداره مگر تغییر دستی توی فایل دیتابیس، نه حذف میشه و نه ویرایش و برای هر اقدامی روی این یوزر خطای 404 داده میشه و خب کل یوزرها هم از کار میفته چون یک خطا توی فایل config.json وجود داره.

احتمالا بخاطر این هست که سعی میکنه براساس uuid یوزر رو پیدا کنه و تغییر رو اعمال کنه. من پیشنهادم این هست که اگر uuid معتبر نیست تغییر ذخیره نشه (نه اینکه فقط خالی نبودن چک بشه بلکه معتبر بودن هم چک بشه) و یک دکمه برای تولید uuid وجود داشته بشه مثل دکمه ای که برای ایمیل وجود داره.

ممنون

### Version of 3x-ui

<details>

```console
v 1.3.4
```

</details>

### x-ui log reports or xray log

<details>

```console
# I did not save any logs
```

</details>

**Comment by MHSanaei** [comment]
[random UUID](https://github.com/MHSanaei/3x-ui/commit/e64a9eeee6619b08cb9d00c4c7cc9bb23a68a60c)
