### ISSUE TITLE
Telegrom Bot in Iran side server

### ISSUE THREAD

**Issue by pulsarice** [MHSanaei/3x-ui#354]
Hi
Telegram Bot on the Iran side server is not working due to censorship.
Is it possible to make x-ui access Telegram's API via a specific outbound instead of Freedom (direct)?

**Comment by mohamad-d** [comment]
Hi
Because telegram is faltered in iran 😐

**Comment by ezioadf2** [comment]
it could be possible, add a new features request
developer can redirect telegram request to xray core where outboud target is primary  server out side of GFW

**Comment by old-joker** [comment]
please add feature to add mtproxy in telegram bot setting
