### ISSUE TITLE
یافتن  فایلهای ssl

### ISSUE THREAD

**Issue by kaazemi1** [MHSanaei/3x-ui#355]
من زیاد وارد نیستم. روی VPS‌ اجازه ثبت ssl با استفاده از منوی x-ui را نداد. بهمین دلیل با توضیحاتی که داده شده دستی آن را نصب کردم. الان ادرس فایل key و cer‌ مربوط به دومین را چگونه می توانم بیابم

**Comment by M4hbod** [comment]
اگه با certbot گرفتید توی این لوکیشنه
/etc/letsencrypt/live/example.com

**Comment by Ferixy** [comment]
سلام. طبق توضحاتی که ارائه دادید ، احتمالا با سرت بات برای دامنه تون سرتفیکیت گرفتید.
وقتی سرتیفیکت میگیرید به شما دوتا فایل ارائه داده میشه. یدونه پرایوت کی و یدونه پابلک کی
آدرس پابلیک کی و پرایوت کی شما روی سرورتون به ترتیب اینطوری هستش:
/etc/letsencrypt/live/آدرس دامنه شما/fullchain.pem
/etc/letsencrypt/live/آدرس دامنه شما/privkey.pem
لطفا حواستون باشه که تو آدرس حتما دامنه خودتونو بزنید (اگر اس اس رو فقط برای ساب دامینتون گرفتید پس حواستون باشه دامنه رو با ساب دامین بزنید داخل آدرس.)
طبق عکسی که ارائه دادم هم میتونید آدرس هارو تو تنظیمات پنلتون وارد کنید
![photo_2023-05-07_14-39-02](https://user-images.githubusercontent.com/77561374/236674112-618d4242-b28c-40c7-91be-174a1740e921.jpg)

**Comment by kaazemi1** [comment]
> 

متشکرم از توضیحات کامل اتان.. بله با certbot درخواست ssl دادم. اما داخل فولدر 
/etc/letsencrypt
که میرم دیگه فولدر live را نمی بینم. 
در VPS برای استفاده از certbot‌ مجددا دستورات  ssl ‌را وارد کردم. اولا باید حتما با sudo وارد کنم و دوم اینکه ایراد زیر را نوشت:
Problem binding to port 80: Could not bind to IPv4 or IPv6.

**Comment by kaazemi1** [comment]
> اگه با certbot گرفتید توی این لوکیشنه /etc/letsencrypt/live/example.com

متشکرم همانطور که در بالا نوشتم فولدر live را مشاهده نکردم. دستورات برای اجرا شدن باید با sudo  باشد و اینکه ایراد پورت 80 را گرفت

**Comment by M4hbod** [comment]
> > اگه با certbot گرفتید توی این لوکیشنه /etc/letsencrypt/live/example.com
> 
> متشکرم همانطور که در بالا نوشتم فولدر live را مشاهده نکردم. دستورات برای اجرا شدن باید با sudo باشد و اینکه ایراد پورت 80 را گرفت

با این دستور چک کنید ببینید پورت 80 توسط چه پروسه ای داره استفاده میشه
sudo ss -tlpn | grep :80

**Comment by Ferixy** [comment]
> > 
> 
> متشکرم از توضیحات کامل اتان.. بله با certbot درخواست ssl دادم. اما داخل فولدر 
> /etc/letsencrypt
> که میرم دیگه فولدر live را نمی بینم. 
> در VPS برای استفاده از certbot‌ مجددا دستورات  ssl ‌را وارد کردم. اولا باید حتما با sudo وارد کنم و دوم اینکه ایراد زیر را نوشت:
> Problem binding to port 80: Could not bind to IPv4 or IPv6.

بنظر میاد پورت پنلتونو روی ۸۰ تنظیم کردید و این قضیه مشکل ساز هست. پورت پنل رو از طریق تنظیمات عوض کنید و دوباره تلاش کنید.
