### ISSUE TITLE
Another source to detect Iran IP range

### ISSUE THREAD

**Issue by mmrabbani** [MHSanaei/3x-ui#358]
فایل geoip استفاده شده در پروژه xray لیست مناسبی برای IP Range های ایران ندارد.
سایت زیر لیست مناسب‌تری دارد
https://www.ip2location.com
پروژه زیر لیست IP های ایران از سایت ip2location را استفاده کرده و به صورت فایل DAT مناسب برای xray درآورده است.
https://github.com/us254/geoip
پیشنهاد می‌کنم در زمان بلاک کردن ip های ایران در پنل، علاوه بر لیست دیفالت geoip، از این لیست هم استفاده شود

**Comment by mfoolady** [comment]
این کاملتزین منبعی هست که تا الان دیدم
https://github.com/bootmortis/iran-hosted-domains

**Comment by mmrabbani** [comment]
> این کاملترین منبعی هست که تا الان دیدم
> https://github.com/bootmortis/iran-hosted-domains

این منبعی که شما ذکر کردید برای دامین هست که در حال حاضر پیاده سازی شده است. چیزی که من نوشتم در مورد ip های ایران است
