### ISSUE TITLE
مشکل در ربات

### ISSUE THREAD

**Issue by Morghak963** [MHSanaei/3x-ui#361]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام مهندس خسته نباشید
تشکر بابت آپدیت جدیدتون
به یک باگ برخورد کردم ، وقتی ایمیل کاربر رو داخل ربات تلگرامی میزنم که مشخصات رو ببینم ، بعد از اینکه رویت شد و میخام مجدد تغییرات رو ببینم ، گزینه refresh رو انتخاب می‌کنم که دو اتفاق میفته، اول از همه اینکه اطلاعات کاربر رفرش میشه که این خوبه ،اما اتفاق دوم اینکه با هربار زدن دکمه refresh  ربات یک پیام no results  رو ارسال میکنه که آزار دهندست

در صورت امکان ممنون میشم بررسی بفرمایید.

### Version of 3x-ui

1.4.0

### x-ui log reports or xray log

.

**Comment by MHSanaei** [comment]
موردی مشاهده نشد
