### ISSUE TITLE
به مشکل خوردن بعضی از سایت ها بعد از نصب وارپ

### ISSUE THREAD

**Issue by pattmatti** [MHSanaei/3x-ui#365]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام دوست عزیز 
بنده وارپ رو نصب کردم برای رفع مشکل اسپاتیفای ولی بعد از نصب وارپ یک سری از سایت ها دیگه بالا نمیاد
مثل فلت ایکون فریپیک ایپی اینفو
امکانش هست که راهی بزارین برای اضافه کردن سایت های دلخواه برای وارپ 
یا اگر راه حلی میدنین برای این مشکل بگین 
ارور فوربیدن یو ار ال میده این سایت هایی که گفتم 
بازم ممنون از امکانات خوبی که اضافه کردین

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
میتونید دستی سایت مورد نظرتون رو اضافه کنید در قسمت manual list
