### ISSUE TITLE
error in config file: list not found in geosite.dat: CATEGORY-RU-GOV

### ISSUE THREAD

**Issue by mehduo** [MHSanaei/3x-ui#374]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi:
after updating to 1.4.1 Xray stops functioning and shows this error log:
Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.3 linux/amd64)

A unified platform for anti-censorship.

2023/05/08 08:29:49 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:category-ru-gov > infra/conf: failed to load geosite: CATEGORY-RU-GOV > infra/conf: list not found in geosite.dat: CATEGORY-RU-GOV

of course, after enabling connection to Russian IP ranges and counties you can fix it.

and thanks a lot for such a nice and well-functioning panel.

### Version of 3x-ui

<details>

```console
1.4.1
```

</details>

### x-ui log reports or xray log

<details>

```console
Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.3 linux/amd64)

A unified platform for anti-censorship.

2023/05/08 08:29:49 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:category-ru-gov > infra/conf: failed to load geosite: CATEGORY-RU-GOV > infra/conf: list not found in geosite.dat: CATEGORY-RU-GOV
```

</details>

**Comment by MHSanaei** [comment]
[domain-list-community (category update)](https://github.com/MHSanaei/3x-ui/commit/37ab8f42e956e04f41bca1a616739689a817a74c)
