### ISSUE TITLE
removed list of inbound after update to 1.4.1

### ISSUE THREAD

**Issue by Saber88607** [MHSanaei/3x-ui#376]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

im updated from 1.3.3 to 1.4.1
and all of my inbound disapear but still working
how they come back?

### Version of 3x-ui

1.4.1

### x-ui log reports or xray log

-- Logs begin at Fri 2023-04-28 10:48:16 UTC, end at Mon 2023-05-08 11:02:29 UTC. --
May 08 07:45:32 Family x-ui[2502]: 2023/05/08 07:45:32 http: TLS handshake error from 172.71.102.106:49196: remote error: tls: bad certificate
May 08 07:57:11 Family x-ui[2502]: 2023/05/08 07:57:11 http: TLS handshake error from 167.248.133.127:39356: read tcp 10.1.1.4:8443->167.248.133.127:39356: use of closed network connection
May 08 07:57:12 Family x-ui[2502]: 2023/05/08 07:57:12 http: TLS handshake error from 167.248.133.127:45000: EOF
May 08 08:11:34 Family x-ui[2502]: 2023/05/08 08:11:34 http: TLS handshake error from 45.79.167.182:61000: EOF
May 08 09:04:00 Family x-ui[2502]: 2023/05/08 09:04:00 http: TLS handshake error from 107.170.243.10:34840: read tcp 10.1.1.4:8443->107.170.243.10:34840: use of closed network connection
May 08 10:11:18 Family x-ui[2502]: 2023/05/08 10:11:18 http: TLS handshake error from 45.56.96.201:61000: EOF
May 08 10:40:06 Family x-ui[2502]: 2023/05/08 10:40:06 http: TLS handshake error from 194.165.16.72:65399: tls: first record does not look like a TLS handshake
May 08 10:46:05 Family x-ui[2502]: 2023/05/08 10:46:05 http: TLS handshake error from 107.170.238.10:41180: tls: client used the legacy version field to negotiate TLS 1.3
May 08 10:51:26 Family systemd[1]: Stopping x-ui Service...
May 08 10:51:26 Family systemd[1]: x-ui.service: Killing process 1183633 (xray-linux-amd6) with signal SIGKILL.
May 08 10:51:26 Family systemd[1]: x-ui.service: Succeeded.
May 08 10:51:26 Family systemd[1]: Stopped x-ui Service.
May 08 10:51:34 Family systemd[1]: Started x-ui Service.
May 08 10:51:34 Family x-ui[3494940]: 2023/05/08 10:51:34 x-ui 1.4.1
May 08 10:51:34 Family x-ui[3494940]: 2023/05/08 10:51:34 INFO - web server run https on [::]:8443
May 08 10:53:15 Family x-ui[3494940]: 2023/05/08 10:53:15 WARNING - stop server err: multierr: close tcp [::]:8443: use of closed network connection |
May 08 10:53:16 Family x-ui[3494940]: 2023/05/08 10:53:16 INFO - web server run https on [::]:8443
May 08 11:02:03 Family x-ui[3494940]: 2023/05/08 11:02:03 http: TLS handshake error from 20.4.59.184:43998: EOF
May 08 11:02:29 Family x-ui[3494940]: 2023/05/08 11:02:29 WARNING - stop server err: multierr: close tcp [::]:8443: use of closed network connection |
May 08 11:02:29 Family x-ui[3494940]: 2023/05/08 11:02:29 INFO - web server run https on [::]:8443

**Comment by MHSanaei** [comment]
back to 1.3.4 
remove all shadowsocks inbound 
then update to last version
