### ISSUE TITLE
Xray Status Error Version 1.4.1

### ISSUE THREAD

**Issue by Nima786** [MHSanaei/3x-ui#379]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Getting **Xray Status Error** after installing on a fresh ubuntu server, I did not test to upgrade my current server to this version but I assume that wood brings the same issue.

### Version of 3x-ui

<details>

```console
# Paste here
```1.4.1 

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```error

</details>

**Comment by mahdisalehivand** [comment]
Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.3 linux/amd64)

A unified platform for anti-censorship.

2023/05/08 13:45:12 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:category-ru-gov > infra/conf: failed to load geosite: CATEGORY-RU-GOV > infra/conf: list not found in geosite.dat: CATEGORY-RU-GOV


ارور بعد نصب آپدیت مربوط به دامین ایران چین و روسیه

**Comment by MHSanaei** [comment]
[domain-list-community (category update)](https://github.com/MHSanaei/3x-ui/commit/37ab8f42e956e04f41bca1a616739689a817a74c)

**Comment by mahdisalehivand** [comment]
Russia domains when enable x-ray error
