### ISSUE TITLE
How to bypass Iran domains/ips from being proxied using panel

### ISSUE THREAD

**Issue by Arezz6** [MHSanaei/3x-ui#380]
as the title says, I've no clue how to do so, I'd appreciate any help <3

**Comment by Arezz6** [comment]
I don't exactly understand what u mean, I want to block all Iran domains/IPs from being accessed by user and meanwhile making them use the user's actual IP and not the server IP. (Making requests go directly and not being affected by VPN)
I know it's possible using in-app options such as "Proxy per app" and stuff like that; but I want to do it using the panel, so they won't have to do so.

**Comment by MHSanaei** [comment]
you can find block iran ip and domain here  
settings/xray configuration/basic

**Comment by Arezz6** [comment]
You didn't get what I meant..

**Comment by MHSanaei** [comment]
if you want to direct Iran IP or domain you have to do it on your client app

**Comment by Arezz6** [comment]
I see, thought there is a way to do it using the panel. thx.
