### ISSUE TITLE
اشتراک

### ISSUE THREAD

**Issue by alisorena1993** [MHSanaei/3x-ui#386]
لطفا درصورت امکان، امکان ایجاد لینک اشتراکی با کانفیگ های دلخواه فراهم کنید. مثلا با ایجاد یک کاربر بتونیم به همه کانفیگ ها یا بخشی از اونها دسترسی داشته باشیم و نیازی نباشه برای یک کاربر چندین کلاینت بسیازیم تا بتونه از چنتا کانفیگ استفاده کنه. ممنون

**Comment by AminB3DA** [comment]
درضمن اگر بشه اسم صفحات رو کاستوم کرد عالی میشه. مثلا تو آدرس بار ننویسه xui inbound و... اسامی رو کاستوم کنیم چون جدیدا این اسامی رو فیلتر میکنن حتی اگر دامنه فیلتر نباشه. برای مثال:  https://damane.xx:2053/panel/karbaran

**Comment by MHSanaei** [comment]
https://t.me/c/1939905425/1/89657

**Comment by alisorena1993** [comment]
داداش ممبرم کن نمیتونم جوین بدم (https://t.me/alisorena1993)

**Comment by alisorena1993** [comment]
داداش منظورم از اشتراک اون سابسکریپشن نیست اونا میدونم خیلی هم عالیه. میگم ینی یه کاربر بسازیم خودش به همه کانفیگا دسترسی داشته باشه یچی مثل هیدیفای
