### ISSUE TITLE
سوال منباب مودیفای ربات تلگرام

### ISSUE THREAD

**Issue by SmileDs** [MHSanaei/3x-ui#390]
سلام، وقت شما بخیر و خسته نباشید
ربات تلگرام که روی پنل هستش بسیار عالی و کارآمد هست، فقط اینکه یک سوال آیا خودمون میتونیم تنظیمات ربات رو از فایل توی سرور تغییر بدیم؟
به عنوان مثال وقتی /usage ID میگیریم خودش به صورت پیشفرض انگلیسی برمیگردونه مصرف را میشه متن انگلیسیشو تغییر داد به متن دلخواه فارسی و آیا میشه توسط این ربات کانفیگ بسازیم بدون اینکه وارد پنل بشیم از طریق url؟

با تشکر از شما ( اگر رفرنسی منباب آموزش این امور هست ممنون میشم قرار بدید )

**Comment by igoris76** [comment]
Also interested in this question

**Comment by MHSanaei** [comment]
از داخل سرور نه
باید گیت هاب رو فورک بزنید بعد ترجمه کنید بعد فایل release بسازد و روی سرورتون نصب کنید
