### ISSUE TITLE
مشکل کندی

### ISSUE THREAD

**Issue by AmirAAAL** [MHSanaei/3x-ui#391]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام.
چطور می توان مشکلی کندی را رفع کرد؟ چندین سرور تانل تست کردم مشکل رفع نشد!
اما در پنل چینی همچین مشکلی نیست فقط این پنل این مشکل را دارد
ممنون میشم راهنمایی کنید.

### Version of 3x-ui

<details>

```console
Last version / Xray 1.7.5
```

</details>

### x-ui log reports or xray log

No

**Comment by mmdh-ir** [comment]
من هم همین مشکل رو دارم 👍

**Comment by mmdh-ir** [comment]
روی پیسی سرعت اکیه و عالیه ولی رو همه ی برنامه های موبایلی مشکل برام وجود اومده به تازگی
