### ISSUE TITLE
عدم اتصال همراه اول با reality

### ISSUE THREAD

**Issue by AmirPY82** [MHSanaei/3x-ui#393]
سلام
با پروتکل vless + reality از طریق همراه اول اتصال انجام نمیشه و ارور fail to detect internet connection: net/http: TLS handshake timeout رو میده ولی با ایرانسل و وایفای اوکیه، باید چکار کرد؟

**Comment by misagh72** [comment]
ادرس سایت مورد استفاده رو عوض کنید

**Comment by roozbehsat** [comment]
منم همین مشکل رو دارم با چندین سایت هم چک کردم.

**Comment by AmirPY82** [comment]
> ادرس سایت مورد استفاده رو عوض کنید
امکانش هست چندتا سایت با tls 1.3 فعال بفرستید؟

**Comment by roozbehsat** [comment]
کلا grpc رو همراه اول مشکل داره...

**Comment by AmirPY82** [comment]
راه حلی نداره این مشکل؟

**Comment by roozbehsat** [comment]
من که زیر و رو کردم و راه حلی پیدا نکردم. انگار از دیروز عصر کلا همراه اول grpc رو بسته. تنها راه tcp هست که اونم خیلی قطع و وصلی داره و سرعتش هم داغونه رو همراه اول...

**Comment by AmirPY82** [comment]
من خودم همش با tcp بودم و اوکی بود تا دیروز که اینجوری شده

**Comment by AmirPY82** [comment]
الان با tcp رو ایرانسل و وایفای هیچ مشکلی نداره ولی همراه سرویس کرده

**Comment by roozbehsat** [comment]
من که راه حلی پیدا نکردم. اگر شما پیدا کردی اطلاع رسانی کن. یک جایی خوندم که h2 جواب میده ولی من جواب نگرفتم. راستش درست بلد نیستم کانفیگ کنم h2  رو.....

**Comment by masoudimo** [comment]
درود دوستان ، راهکاری پیدا نشد؟ ریالیتی منم دیروز بعد از هزار ویرایش تی ال اس دست و پا شکسته راه افتاده ولی تعریفی نداره

**Comment by yashtinimohammad** [comment]
با وجود تست sni های متفاوت ولی متسفانه پینگ نوسان زیاد و اپلود 0  در همراه

**Comment by elegance666** [comment]
من azure دارم فقط روی اون خوب کار میکنه reality با همراه اول، بیستا سرور دیگه امتحان کردم، اصلا نمیشه
