### ISSUE TITLE
عدم اتصال به chat gpt با نت ایرانسل حتی با warp

### ISSUE THREAD

**Issue by Bestsenator** [MHSanaei/3x-ui#394]
سلام وقتت بخیر
من پنل رو اپدیت کردم، warp رو هم نصب کردم
ولی مشکلی که داره برای نت ایرانسل هنوزم که هنوزه وارد چت جی پی تی نمیشه
میشه راهنماییم کنی ؟

**Comment by Bestsenator** [comment]
آره

**Comment by MHSanaei** [comment]
https://t.me/panel3xuiGroup/1/69068

**Comment by Bestsenator** [comment]
انجامش دادم ولی متاسفانه بازم مشکل داره

**Comment by misagh72** [comment]
توی تلکرام بپرسید جواب میدن

**Comment by RealCuf** [comment]
طبق چیزی که خودم روی رایتل و ایرانسل تست کردم روی نکوری حالت System Proxy چت جی پی تی باز میشه و روی V2rayNG داخل تنظیمات تو بخش VPN Setting با فعال کردن Enable local DNS و Enable fake DNS این مشکل رفع میشه
