### ISSUE TITLE
مشکل غیرفعال شدن Xray Core بعد از ساخت اکانت با پورت 443

### ISSUE THREAD

**Issue by p3dram** [MHSanaei/3x-ui#396]
سلام و خسته نباشید.
در ابتدا تشکر بابت پنل فوق العاده خوبتون. خواستم ببینم راهی هست که با انجام تغییرات بشه از پورت 443 روی پنل استفاده کرد برای ساخت اکانت؟ متاسفانه بعد از ساخت اکانت با این پورت xray core از کار می‌افته و عملا هیچ کاری نمیشه کرد

**Comment by hosseinabaiyani** [comment]
بخاطر این هست که روی سرورت پورت 443 توسط اپ دیگه ای در حال استفاده ست

**Comment by p3dram** [comment]
سلام. با تشکر از هر دو عزیز. این کار رو انجام دادم و 443 در لیست نیست.
آخرین بار که اکانت با پورت 443 ساختم به مدت 24 ساعت کار کرد بدون مشکل ولی بعد از اون xray core از کار افتاد. بر اساس تجربه قبلی اون اکانت رو حذف کردم و xray core دوباره استارت شد و شروع به کار کرد

**Comment by MEM-917** [comment]
خواهش. لاگ x-ui و سیستمی رو چک کنین تا ببین مشکل از کجا نشات میگیره. تو خود صفحه اول پنل  هست یا میتونین با دستور journalctl -f -u x-ui بصورت آنلاین رصد کنین فعل و انفعلات x-ui رو. برای چک کردن لاگ سیستمی هم به قسمت /var/log/ برین و syslog و ufw رو بررسی کنین(اگه نصبه)

**Comment by p3dram** [comment]
> من یبار موقع ساختن ریلیتی روی پورت ۴۴۳ یه اشتباه کرده بودم توی dest یادم رفته بود دونقطه ۴۴۳ رو بذارم. اینطوری xray دیگه استارت نمی‌شد و ارور می‌داد. _(اون دو تا ۴۴۳ به هم ربطی ندارن. یعنی دومی کارش چیز دیگه‌ست)_ با خوندن لاگ xray متوجه شدم قضیه چیه. توی صفحه اصلی x-ui جلوی Xray Status اگه یه علامت سؤال هست، موس رو روش نگه داری بهت ارور مربوطه رو نشون می‌ده.

دستت درد نکنه نکته مهمی بود و بررسی می‌کنم الان

**Comment by p3dram** [comment]
> خواهش. لاگ x-ui و سیستمی رو چک کنین تا ببین مشکل از کجا نشات میگیره. تو خود صفحه اول پنل هست یا میتونین با دستور journalctl -f -u x-ui بصورت آنلاین رصد کنین فعل و انفعلات x-ui رو. برای چک کردن لاگ سیستمی هم به قسمت /var/log/ برین و syslog و ufw رو بررسی کنین(اگه نصبه)

توی لاگ‌ها یه دوری زدم و هیچ ارور مشخصی مربوط به این داستان پیدا نکردم. هیچ چیزی هم از پورت 443 استفاده نمی‌کنه!

**Comment by MEM-917** [comment]
جناب پدرام، لطف میکنین از صفحه اکانتتاتون اسکرین بدین؟
من همین الان از نسخه 1.4.1پنل استفاده میکنم و مشکلی ندارم، نه خود پورت نه پورت های مابقی که ریورس پراکسی شدن روی 443. باس تنظیمات اکانتتون یا کانکشنتون بهم ریخته باشه که باس از همون پنل درستش کنین

**Comment by ketetefid** [comment]
در آخرین ورژن موجود x-ui هر زمان یک اکانت جدید با استفاده از xtls درست بشه، xray-core از کار میفته و ربطی به پورت نداره. احتمالا این قضیه بخاطر عدم وجود xtls-rprx-vision در کنار xtls و استفاده ی پیشفرض از xtls-rprx-direct/origin  باشه که در ورژن های جدید xray منسوخ/حذف شده.

**Comment by lordtrader2020** [comment]
سلام من یه مشکل دارم ولی از پورت 443 استفاده نکردم 
![Screenshot (8)](https://github.com/MHSanaei/3x-ui/assets/142753231/535dca22-02b9-4b07-8e52-30f5a0a37b80)

**Comment by lordtrader2020** [comment]
سلام  مشکل ارور با حذف اخرین کاتفیگ که درست کرده بودم درست شد ولی نفهمیدم چرا و چه چیزی تو اون کافیگ مشکل داشت

**Comment by lordtrader2020** [comment]
> سلام مشکل ارور با حذف اخرین کاتفیگ که درست کرده بودم درست شد ولی نفهمیدم چرا و چه چیزی تو اون کافیگ مشکل داشت

یه سوال کار بر میتونه باعث لز کار افتادن xray-core بشه وسرور از کار بیفته

**Comment by Fareygar** [comment]
سلام و عرض ادب . اولا که واقعا خسته نباشید و کلی تشکر بابت ساخت این پنل ... دمتون گرم . ببشخید یه سوال داشتم میخواستم من ایپی های ایران رو روی سرور ببندم برای همین از این آموزش "https://github.com/iranxray/hope/blob/main/routing.md" استفاده کردم . الان هسته xray ظاهرا از کار افتاده کسی میتونه راهنمایی کنه چه کاری باید انجام بدم ؟
![image](https://github.com/MHSanaei/3x-ui/assets/143070585/6851e970-a0da-4166-9707-37a70b877c93)

**Comment by lordtrader2020** [comment]
سلام احتمالا باید دوباره پنل رو نصب کنید و دقت کنید کد هارو درست وارد کرده اید چون کم زیاد شدن حتا یک کاراکتر باعث ازکارافتادن پنل میشود

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
