### ISSUE TITLE
VLEES + TCP + NginX(Reverse Proxy)

### ISSUE THREAD

**Issue by MEM-917** [MHSanaei/3x-ui#398]
سلام و خسته نباشید. از دوستان عزیز کسی هست که بتونه از روی پنل جناب ثنایی(یا هر پنلی که وجود داره) پروتکل TCP رو لینک کنه به NginX و از طریق انجین‌ایکس سرتیفیکت ها  کانکشن رو آپگرید کنه. این روش برای WebSocket و gRPC جوابه ولی من به شخصه نتونستم با پنل این روش رو پیدا کنم. ممنون میشم کسی هست راهنمایی کنه

**Comment by lostsoul6** [comment]
درود وقت بخیر . این پیام رو داشتم میخوندم گفتم یه سوال از شما بپرسم . منظورتون این هست که شما دارید از nginx استفاده میکنید که سرتیفیکیت های یک دامنه هدف رو بگیرید و از این سرتیفیکیت ها برای دور زدن فیلترینگ بر مبنای TLS استفاده کنید ؟ اگر درست متوجه شدم میشه منبع آموزشی برای این قضیه ارائه بدید ؟ تشکر

**Comment by MEM-917** [comment]
بله عزیز. الان من خودم سرور شخصی دارم و فقط برا مصرف خونواده و دوستانه و محض چکش کاری کلا هیچ پپورتی جز 80 و 443 باز نیست. همه داده ها میاد به NginX و اونجا پردازش میشه و از اونجا به x-ui تحویل داده میشه. این وسط شما میتونین کانکشن رو امن کنین(TLS) بدین یا نه. اگه اینو میخواین من نمیدونم وب چه چیزایی داره ولی سوال خاصی دارین بپرسین در حد توان جواب میدم

**Comment by MEM-917** [comment]
با تشکر از جناب ثنایی عزیز بابت کار فوق العادشون که این پنل رو ساختند. این سوال/مشکل من با آزمون و خطا حل شد و روی ایرانسل و آسیاتک که تست کردم بهترین نتیجه رو داد و حتا پینگ ها از حالت اینترنت داخلی/بدون فیلترشکن بهتر شد ولی تو همراه اول سرعت خیلی کمه و پینگ تناوب داره. من خودم جایی ندیدم آموزش این روش رو و اگه تست های تکمیلی جواب داد و تونستم بهینه کنم تو قسمت بحث و فحص میذارم روشش رو.
درضمن مشخصات پنل و ایکس ری اینا بود 3x-ui: [v1.4.1]  Xray: v1.7.5

**Comment by MJamshidnejad** [comment]
> با تشکر از جناب ثنایی عزیز بابت کار فوق العادشون که این پنل رو ساختند. این سوال/مشکل من با آزمون و خطا حل شد و روی ایرانسل و آسیاتک که تست کردم بهترین نتیجه رو داد و حتا پینگ ها از حالت اینترنت داخلی/بدون فیلترشکن بهتر شد ولی تو همراه اول سرعت خیلی کمه و پینگ تناوب داره. من خودم جایی ندیدم آموزش این روش رو و اگه تست های تکمیلی جواب داد و تونستم بهینه کنم تو قسمت بحث و فحص میذارم روشش رو. درضمن مشخصات پنل و ایکس ری اینا بود 3x-ui: [v1.4.1] Xray: v1.7.5

Have you reached to you desired goal?

**Comment by MEM-917** [comment]
> Have you reached to you desired goal?

Yes and no. Yes, I can create a separate TCP inbound and connect it via nginx or better yet, haproxy. It works like a charm for almost all the ISPs but MCI doesn't work.
If you want to implant it you can do it by these steps:

- buy and configure an fqdn.
- create an https front end in haproxy for binding port 443.
- assign a specific subdomain for your TCP connection. Whether it's a reality protocol or a simple tcp one.
- for censorship-circumvention reasons(risk-aversion of getting identified by DPI) I usually go by the "www" subdomain.
- build a backend for this subdomain(s) and point it to the inbound.
- if you want to use TCP-tls you can do it in two methods:
  1. terminate tls in haproxy and send it to the non-certificated inbound
  2. send it as it is to inbound with the specified certificate
- if you're using Reality; just proxy it as it is to inbound which the destination is just as your server's HTTPS port(i.e. 443) and the server name is your specified subdomain. Something like this:

![inbound](https://github.com/MHSanaei/3x-ui/assets/133103062/c346dde8-f21d-4c80-8f35-2b88a87f6270)

Congratz. you did it.
The problem is MCI and the routing of Iran's internet. For servers in which, Islamic Republic has optimized routes, the connection is as good as it gets(i.g. Germany, Netherlands as I've tested) but for other conditions, you have two choices:
creating a [default] backend and assigning it with a working SNI. this method doesn't work in MCI
tunneling wich works in all ISPs

at last, DO NOT use domestic CDN services

P.N.: These are some of my test results with the above configuration in MTN:

**Without VPN:**
![MTN w o](https://github.com/MHSanaei/3x-ui/assets/133103062/aef90ab7-83e5-4189-ae02-b868870fb698)

**With VPN:**
![MTN w](https://github.com/MHSanaei/3x-ui/assets/133103062/889a797c-4011-4e45-99e5-e319b5367d60)

**Comment by MJamshidnejad** [comment]
> via nginx or better yet, haproxy. 

Thanks for your help @MEM-917.  But, how is haproxy better than nginx? Do you have any example of that? It's new to me.
