### ISSUE TITLE
Google ReCapcha

### ISSUE THREAD

**Issue by Fatifan** [MHSanaei/3x-ui#404]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

متاسفانه حتی با نصب و فعال کردن warp روی پنل باز هم مشکل کپچای گوگل حل نشد و گوگل آیپی سرور رو می‌بینه 
مشکل حتی با غیر فعال کردن ipv6 هم همچنان پابرجاست

### Version of 3x-ui

<details>

```console
1.4.1
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by TaraRostami** [comment]
> ### Welcome
> * [x]  Yes, I'm using the latest major release. Only such installations are supported.
> * [x]  Yes, I'm using the supported system. Only such systems are supported.
> * [x]  Yes, I have read all WIKI document,nothing can help me in my problem.
> * [x]  Yes, I've searched similar issues on GitHub and didn't find any.
> * [x]  Yes, I've included all information below (version, config, log, etc).
> 
> ### Description of the problem,screencshot would be good
> متاسفانه حتی با نصب و فعال کردن warp روی پنل باز هم مشکل کپچای گوگل حل نشد و گوگل آیپی سرور رو می‌بینه مشکل حتی با غیر فعال کردن ipv6 هم همچنان پابرجاست
> 
> ### Version of 3x-ui
> ```
> 1.4.1
> ```
> 
> ### x-ui log reports or xray log
> ```
> # paste log here
> ```

سلام ، توزیع و ورژن لینوکس سرورتون چی هست ؟

**Comment by TaraRostami** [comment]
> متاسفانه حتی با نصب و فعال کردن warp روی پنل باز هم مشکل کپچای گوگل حل نشد و گوگل آیپی سرور رو می‌بینه مشکل حتی با غیر فعال کردن ipv6 هم همچنان پابرجاست

سلام ، توزیع و ورژن لینوکس سرورتون چی هست ؟

**Comment by Fatifan** [comment]
> > متاسفانه حتی با نصب و فعال کردن warp روی پنل باز هم مشکل کپچای گوگل حل نشد و گوگل آیپی سرور رو می‌بینه مشکل حتی با غیر فعال کردن ipv6 هم همچنان پابرجاست
> 
> سلام ، توزیع و ورژن لینوکس سرورتون چی هست ؟

Ubuntu 20.04 LTS

**Comment by TaraRostami** [comment]
> Ubuntu 20.04 LTS
پیشنهادم اینه یک سرور دیبان 11 یا اوبونتو 22 راه اندازی کنید و از همون اول گزینه IPv6 رو غیرفعال کنید که سرور فقط با IPv4 ساخته بشه _"بعدا اگه لازم داشتید میتونید IPv6 رو هم اضافه کنید"_

و بعد روی سرور با آی پی جدید مجدد کانفیگتون رو انجام بدید و کش مرورگر رو هم کاملا پاک کنید بعد تست کنید
نیازی هم نیست همون اول WARP رو فعال کنید

**Comment by TaraRostami** [comment]
> Ubuntu 20.04 LTS

پیشنهادم اینه یک سرور دیبان 11 یا اوبونتو 22 راه اندازی کنید و از همون اول گزینه IPv6 رو غیرفعال کنید که سرور فقط با IPv4 ساخته بشه _"بعدا اگه لازم داشتید میتونید IPv6 رو هم اضافه کنید"_

و بعد روی سرور با آی پی جدید مجدد کانفیگتون رو انجام بدید و کش مرورگر رو هم کاملا پاک کنید بعد تست کنید
نیازی هم نیست همون اول WARP رو فعال کنید
