### ISSUE TITLE
باگ درصد CPU ربات تلگرام

### ISSUE THREAD

**Issue by Mammad3861** [MHSanaei/3x-ui#405]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

توی پنل بعد از ست ربات تلگرام و قرار دادن درصد اخطار مصرف cpu گاها پیامهای اشتباهی میاد که درصد انتخاب شدت صفره و الان داری مثلا ۹% از سی پی یو استفاده میکنی! کسی مشکل مشابه داره؟
![IMG_20230511_061811](https://github.com/MHSanaei/3x-ui/assets/108564287/f721a4bb-8ac9-4f3b-acbc-208cf03de7b9)

### Version of 3x-ui

<details>

```console
V1.4.0
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
CPU percentage alert threshold
مقدارش رو از 0 که گذاشتید به درصد ی که میخاید بیشتر از اون نمایش بده تغییر بدید
