### ISSUE TITLE
这个有中文版吗

### ISSUE THREAD

**Issue by Junhai01** [MHSanaei/3x-ui#409]

**Comment by TaraRostami** [comment]
你好
是的，在登录页面选择中文即可
![Screenshot 2023-05-11 114829](https://github.com/MHSanaei/3x-ui/assets/132676256/b82c0c90-f81e-4f3e-9a41-cef15ae17800)

**Comment by TaraRostami** [comment]
> _No description provided._

你好
是的，在登录页面选择中文即可
![Screenshot 2023-05-11 114829](https://github.com/MHSanaei/3x-ui/assets/132676256/b82c0c90-f81e-4f3e-9a41-cef15ae17800)
