### ISSUE TITLE
باز نشدن ستینگ پنل

### ISSUE THREAD

**Issue by masoudkeramatloo** [MHSanaei/3x-ui#410]
درود
مشکلی که هست اینه که پنل، قسمت سیستم و اینبوند وارد میشه. ولی نمیشه توی ستینگ وارد شد.

نمیدونم مشکل داره پنل یا مشکل از قسمت منه

راهنمایی میخوام

**Comment by TaraRostami** [comment]
سلام پنل رو آپدیت کنید و Ctrl + F5 بزنید تا پنل رفرش شه احتمالا مشکلتون حل میشه

**Comment by TaraRostami** [comment]
> درود مشکلی که هست اینه که پنل، قسمت سیستم و اینبوند وارد میشه. ولی نمیشه توی ستینگ وارد شد.
> 
> نمیدونم مشکل داره پنل یا مشکل از قسمت منه
> 
> راهنمایی میخوام

سلام ، پنل رو آپدیت کنید و بعد Ctrl + F5 بزنید تا پنل رفرش بشه احتمالا مشکلتون حل میشه

**Comment by arianemun** [comment]
من هم به این مشکل برخوردم، مشکل من این بود که نمیتونیت map بزنه روی inbound ها و این مورد برای inbound های shadowsocks که قبل اپدیت ساخته بودم بود و همینطور vmess بدون client که این inbound هارو پاک کردم درست شد ( در لاگ هم میگفت config.js init نشده )

**Comment by masoudkeramatloo** [comment]
مرسی از جواباتون. مثل اینکه سرور روی های وب مشکل داشت. روی مخابرات اوکی بود. بالا میومد
فقط باید الان برم سر وقت کارای دیگش ک بتونم کامل و امن راه اندازیش کنم
