### ISSUE TITLE
مشکل انقضا کاربر

### ISSUE THREAD

**Issue by aliwebto** [MHSanaei/3x-ui#412]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام
پنل یوزر ها رو خود به خود depleted میکنه و کار نمیکنن 
در صورتی که من با api تاریخ پایان اشتراکشون رو تغییر دادم
یه نمونه اش رو میزارم
(
                    [email] => m.kol2@m.kol.com
                    [enable] => 1
                    [expiryTime] => 1686397693000
                    [flow] => 
                    [id] => 5be18f8b-d86f-4137-afaa-616d0efe7ffa
                    [limitIp] => 0
                    [subId] => 
                    [tgId] => 
                    [totalGB] => 53687091200
)
![image](https://github.com/MHSanaei/3x-ui/assets/70484690/344be079-2ecc-4556-9ff2-a6eae2b48605)

برای حل این مشکل هم هی لازم میشه وارد پنل x-ui بشم و یوزر رو یه بار غیر فعال و مجدد فعال کنم

### Version of 3x-ui

<details>

```console
1.3.4
```

</details>

### x-ui log reports or xray log

<details>

```console
May 11 11:48:40 aliwebto x-ui[82861]: 2023/05/11 11:48:40 INFO - Remove Inbound User m.kol2@m.kol.com due the expire or traffic limit
```

</details>

**Comment by MHSanaei** [comment]
سلام با توجه به کانفیگی که شما دادید و چک کردم تایم شما الان هم تاریخش رفته
وقتی هم دستی یا به هرحال با بات تایم رو عوض کنید باید یکبار ریست کنید
![Screenshot_2023-05-11-15-47-41-97_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/MHSanaei/3x-ui/assets/33454419/eb3461ef-876c-49c4-82a8-86405a35057b)
