### ISSUE TITLE
لاگ با ارور webhook! و آپدیت نشدن نرم افزار روی سرور

### ISSUE THREAD

**Issue by Mammad3861** [MHSanaei/3x-ui#414]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

این لاگ رو میگیرم و روی این سرور مثل بقیه سرور ها اتومات آپدیت نمیشه x-ui
رو سرور هم سعی کردم طبق لاگ deletewebhook و webhook رو بزنم ولی اصلا نمیشناسه
الان سه ورژنه همچین مشکلیو دارم! مربوط به پنله یا سرور؟

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
May 12 04:57:26 . x-ui[663]: 2023/05/12 04:57:26 Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
May 12 04:57:26 . x-ui[663]: 2023/05/12 04:57:26 Failed to get updates, retrying in 3 seconds...
```

</details>

**Comment by MHSanaei** [comment]
https://api.telegram.org/bot<token>/setWebhook?url=
به جای <token> توکن بات خودتون رو قرار بدید و داخل مرورگر خودتون بزنید که webhook از روی توکن شما برداشته بشه
