### ISSUE TITLE
change panel URL address using SSH

### ISSUE THREAD

**Issue by nickali2** [MHSanaei/3x-ui#418]
how can I change panel URL address using SSH? I changed it from panel and I can't login again. x-ui stopped and cannot start again. I have to change the URL again.

**Comment by md9786** [comment]
you can change port to the panel with the command x-ui in your ubunto server if your server is not runnig and restarting it through the x-ui menu doesn't work try the option that says reset panel settings that's what have worked for me in the past.
![Uploading Screenshot 2023-05-12 191955.png…]()
