### ISSUE TITLE
کار نکردن  حذف کاربران منقضی

### ISSUE THREAD

**Issue by esmaeilch81** [MHSanaei/3x-ui#424]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام من 700 تا یوزر دارم 500 تاش منقضی شده میخوام بزنم همه رو حذف کنه ما به جای این که کاربران رو حذف کنه ترافیک اونا رو ریست میکنه از آخرین ورژن هم استفاذه میکنم.

### Version of 3x-ui

<details>

```console
# v1.4.1
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
General Actions/Delete depleted clients
