### ISSUE TITLE
باگ در Subscription

### ISSUE THREAD

**Issue by mfoolady** [MHSanaei/3x-ui#435]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

من یک کانکشن ریلیتی میسازم وقتی مستقیم کانفیگ رو ایمپورت میکنم کار میکنه ولی همون کانفیگ وقتی با لینک ساب ایمپورت میشه کار نمیکنه

![Screenshot 2023-05-14 122721](https://github.com/MHSanaei/3x-ui/assets/59839339/dfc4e352-f704-4898-a755-bb20ac4d430a)

### Version of 3x-ui

<details>

```console
1.4.6
```

</details>

### x-ui log reports or xray log

<details>

```console
May 12 14:00:03 ubuntu-2gb-nbg1-Hiddify x-ui[621]: 2023/05/12 14:00:03 http: TLS handshake error from 94.102.61.27:57046: read tcp 5.76.180.100:2053->94.102.61.27:57046: use of closed network connection
May 12 19:16:04 ubuntu-2gb-nbg1-Hiddify x-ui[621]: 2023/05/12 19:16:04 http: TLS handshake error from 77.237.169.105:10831: EOF
May 12 19:16:04 ubuntu-2gb-nbg1-Hiddify x-ui[621]: 2023/05/12 19:16:04 http: TLS handshake error from 77.237.169.105:10829: EOF
May 12 19:20:49 ubuntu-2gb-nbg1-Hiddify x-ui[621]: 2023/05/12 19:20:49 http: TLS handshake error from 77.237.169.105:11303: EOF
May 12 19:20:51 ubuntu-2gb-nbg1-Hiddify x-ui[621]: 2023/05/12 19:20:51 http: TLS handshake error from 77.237.169.105:11435: EOF
May 13 10:01:23 ubuntu-2gb-nbg1-Hiddify x-ui[621]: 2023/05/13 10:01:23 http: TLS handshake error from 162.142.125.226:45054: EOF
May 14 05:44:09 ubuntu-2gb-nbg1-Hiddify x-ui[621]: 2023/05/14 05:44:09 http: TLS handshake error from 167.248.133.50:36340: EOF
May 14 09:36:36 ubuntu-2gb-nbg1-Hiddify systemd[1]: Stopping x-ui Service...
May 14 09:36:36 ubuntu-2gb-nbg1-Hiddify systemd[1]: x-ui.service: Deactivated successfully.
May 14 09:36:36 ubuntu-2gb-nbg1-Hiddify systemd[1]: Stopped x-ui Service.
May 14 09:36:36 ubuntu-2gb-nbg1-Hiddify systemd[1]: x-ui.service: Consumed 1h 28min 22.741s CPU time.
May 14 09:36:49 ubuntu-2gb-nbg1-Hiddify systemd[1]: Started x-ui Service.
May 14 09:36:49 ubuntu-2gb-nbg1-Hiddify x-ui[1475330]: 2023/05/14 09:36:49 x-ui 1.4.6
May 14 09:36:49 ubuntu-2gb-nbg1-Hiddify x-ui[1475330]: 2023/05/14 09:36:49 INFO - web server run https on [::]:2053
May 14 12:09:04 ubuntu-2gb-nbg1-Hiddify x-ui[1475330]: 2023/05/14 12:09:04 WARNING - AddClientTraffic update data  empty slice found
May 14 12:12:35 ubuntu-2gb-nbg1-Hiddify x-ui[1475330]: 2023/05/14 12:12:35 WARNING - xui-m5
May 14 12:13:31 ubuntu-2gb-nbg1-Hiddify x-ui[1475330]: 2023/05/14 12:13:31 WARNING - qv23og6k
May 14 12:16:43 ubuntu-2gb-nbg1-Hiddify x-ui[1475330]: 2023/05/14 12:16:43 WARNING - 7e66kp71
May 14 12:17:29 ubuntu-2gb-nbg1-Hiddify x-ui[1475330]: 2023/05/14 12:17:29 WARNING - client ip job err: invalid character 't' after top-level value
May 14 12:17:29 ubuntu-2gb-nbg1-Hiddify x-ui[1475330]: 2023/05/14 12:17:29 WARNING - client ip job err: truncate : no such file or directory
```

</details>

**Comment by mfoolady** [comment]
با کمی بررسی بیشتر متوجه شدم که وقتی با لینک ساب کانفیگ ایمپورت میشه مقادیر shortId , publickey همراه کانفیگ نیست و خالیه ولی وقتی مستقیم ایمپورت میکنم مقادیر هستند

**Comment by Fcorpion** [comment]
Subscription link does not working at all

**Comment by mfoolady** [comment]
worked for me with other configs

**Comment by mfoolady** [comment]
> Subscription link does not working at all

worked for me with other configs

**Comment by MHSanaei** [comment]
https://t.me/c/1939905425/1/89657

**Comment by Fcorpion** [comment]
> https://t.me/c/1939905425/1/89657

![11](https://github.com/MHSanaei/3x-ui/assets/86823240/f79c7057-7fb2-4e12-9784-e8f1ad6ed43f)

**Comment by Fcorpion** [comment]
> https://t.me/c/1939905425/1/89657

The problem appears when you use GRPC config, the page dose not load and also subscription dose not work.

**Comment by MHSanaei** [comment]
use the latest version and update your inbound
