### ISSUE TITLE
تغییر warp

### ISSUE THREAD

**Issue by alisorena1993** [MHSanaei/3x-ui#439]
درحال حاضر لاگین اینستاگرام با این وارپ ک توی اسکریپت هست سازگار نیست و ریدایرکت میده ولی من دستی warp-go زدم اوکی شد ولی نمیدونم اونا چجوری به عنوان پروکسی استفاده کنم ک رم کمتری استفاده کنه. اگه بتونید اسکریپت وارپ رو عوض کنید و از warp-go استفاده کنین خیلی عالی میشه. ممنون

**Comment by MHSanaei** [comment]
warp-go socks5 nadare
