### ISSUE TITLE
Failed to start: app/proxyman/inbound

### ISSUE THREAD

**Issue by o02** [MHSanaei/3x-ui#440]
My VPS installation in China prompts this every time
Failed to start: app/proxyman/inbound: failed to listen TCP on 62789 > transport/internet: failed to listen on address: 127.0.0.1:62789 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:62789 > listen tcp 127.0.0.1:62789: bind: cannot assign requested address

**Comment by Bogdan-Torkhov** [comment]
@o02 how you fixed issue?
