### ISSUE TITLE
محدود نشدن تعداد کاربر

### ISSUE THREAD

**Issue by asghhm** [MHSanaei/3x-ui#442]
زمانی که یک کلاینت جدید با محدودیت کاربر میسازم هر تعداد کلاینتی میتونن بهش وصل بشن

**Comment by Kiya55** [comment]
اون مال وقتیه که مستقیم وصل بشن به سرور یعنی تانل یا ورکر یا ریلیتی یا ایپی تمیزی چیزی نباشه

**Comment by asghhm** [comment]
یعنی زمانی که از تانل استفاده کنیم با هیچ روشی امکان محدود کردن کاربر وجود نداره؟

**Comment by Kiya6955** [comment]
> 
حتی تانلم نمیشه
فقط فقط مستقیم میشه لیمیت گزاشت

**Comment by asghhm** [comment]
خیلی ممنون از توضیحاتت پس با این حساب امکان مدیریت کاربر وجود نداره

**Comment by mehdikhody** [comment]
> یعنی زمانی که از تانل استفاده کنیم با هیچ روشی امکان محدود کردن کاربر وجود نداره؟

باید یک پنل هم داخل سرور ایران نصب کنید و کاربران را اونجا مدیریت کنید.
و برای تانل هم از تانل پنل به پنل استفاده کنید.

**Comment by MHSanaei** [comment]
[bug fix - limit ip](https://github.com/MHSanaei/3x-ui/commit/2223a21cfcd7173aae9c38558ce5865ebbd27097)

**Comment by Kiya6955** [comment]
دمت گرمه پسر

> [bug fix - limit ip](https://github.com/MHSanaei/3x-ui/commit/2223a21cfcd7173aae9c38558ce5865ebbd27097)
