### ISSUE TITLE
اضافه کردن naive proxy 

### ISSUE THREAD

**Issue by DoctorsPlague** [MHSanaei/3x-ui#443]
سلام
با عرض خسته نباشید خدمت جنابعالی
درخواست داشتم که پروتوکل naive proxy رو به پنلتون اضافه کنید. در حال حاضر پنل Trojan panel از این پروتوکل پشتیبانی میکنه ولی این پنل باگ زیادی داره و زبان فارسی و انگلیسی رو پشتیبانی نمیکنه. از طرفی نمیشه دامنه و ip ایران رو در این پنل بست و اگر حتی هسته xray رو خودمون تغییر بدیم باز روی کانکشن naive اعمال نمیشه که این میتونه دلیل تفاوت هسته های این دو باشه. لطفا این پروتوکل رو با قابلیت شخصی سازی اضافه کنید.
با تشکر و احترام فراوان

**Comment by misagh72** [comment]
این پنل فقط از هسته xray استفاده میکنه برای همین نمیشه چیز دیگه اضاف کرد پس بهتره از همون پنل Trojan panel استفاده کنید

**Comment by DoctorsPlague** [comment]
با تشکر از پاسخگویی
امکانش نیست که چند تا هسته کنار هم کار کنن؟
چون خود پنل trojan go هم هسته xray داره هم naive و هم trojan go رو
اگر بشه قابلیتش رو اضافه کرد خیلی خوب میشه

**Comment by misagh72** [comment]
این پنل فورک یک پنل دیگه هست اضافه کردن یک کور دیگه قطعا دشوار خواهد بود 
حالا تصمیمش با سازنده این پنل خواهد بود

**Comment by DoctorsPlague** [comment]
قطعا اگر این هسته ها اضافه بشه دست بالا رو خواهد داشت نسبت به پنل های دیگه
