### ISSUE TITLE
Could you please add an automatic reset feature for node traffic

### ISSUE THREAD

**Issue by znlsl** [MHSanaei/3x-ui#446]
Hello, thank you for your contribution!
Could you please add an automatic reset feature for node traffic?
Add a switch to control whether the function is enabled: on the 1st day of each month, automatically reset the allocated traffic for clients and the total traffic used by users. For example, if a user has a monthly limit of 500GB, the traffic limit will be automatically reset to 500GB on the 1st day, and the total traffic used by the user will be reset to 0. Thank you!

**Comment by ceozero** [comment]
+1
