### ISSUE TITLE
No Data When Upgrade

### ISSUE THREAD

**Issue by RooyeKhat** [MHSanaei/3x-ui#448]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi
When i upgraded as  v1.3.4 to any verision when i go to inbounds i cant see any client 

Thanks

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
look like you have shadowsocks inbound remove it then update to latest version
