### ISSUE TITLE
بالا رفتن cpu

### ISSUE THREAD

**Issue by fk6989** [MHSanaei/3x-ui#449]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام. من مدتی هست از این پنل استفاده میکنم. ربات تلگرام رو فعال کردم اگر cpu بیشتر از ۷۰ شد بهم نوتیفیکیشن بده. در طول روز بارها(حداقل ۱۰ بار) نوتیفیکیشن برای cpu  بالای ۷۰ درصد دریافت میکنم. معمولا بین ۸۵ تا ۹۹ درصد. توی پنل هم سیپیو همیشه بالای ۵۰ درصده درحالیکه با پنل دیکه هیچوقت به ۳۰ نمیرسه. 
سرور با کلاینت کمی داره کار میکنه. خام بوده و چیز دیکه ای روش نیست. اوبونتو آخرین ورژن. سیپیو رو به ۲ هسته افزایش دادم اما تغییری نکرد. امکانش هست خود بات تلگرام باعث افرایش سیپیو بشه؟ روی سرور مشابه با پنل اسدی(که خیلی وقته اپدیت نشده) همچین مشکلی ندارم. لطفا بررسی کنید. 

### Version of 3x-ui

<details>

```console
# 1.4.6
```

</details>

### x-ui log reports or xray log

<details>

```console
# ui[783]: 2023/05/15 20:30:44 INFO - Stop Telegram receiver ...
```

</details>

**Comment by sadegh1210** [comment]
رو سرور من فقط 5تا کلاینته و در طول روز چندین بار پیام برای من ارسال میشه ک cpu رفته بالا.
چجوری حل کنیم این موضوع رو ؟

**Comment by Amirziplin** [comment]
> رو سرور من فقط 5تا کلاینته و در طول روز چندین بار پیام برای من ارسال میشه ک cpu رفته بالا. چجوری حل کنیم این موضوع رو

اون هشدار cpu  رو خاموش کن ، زیاد مهم نیست ، تو  کنترل پنل سایتی که ازش سرورگرفتی مقدار واقعی رو نشون میده

**Comment by parvizdl** [comment]
نه آقا این مشکل جدی داره ، با هر کی حرف میزنم همینجوری شده . الان سرور و پاک کردم دوباره اینجوری شده . از توی هتزنر هم نشون میده سی پی یو رو 98 درصده و من الان منابع رو زیاد هم کردم اوکی نشده الان 4 هسته دارم با 8 گیگ

**Comment by Amirziplin** [comment]
> نه آقا این مشکل جدی داره ، با هر کی حرف میزنم همینجوری شده . الان سرور و پاک کردم دوباره اینجوری شده . از توی هتزنر هم نشون میده سی پی یو رو 98 درصده و من الان منابع رو زیاد هم کردم اوکی نشده الان 4 هسته دارم با 8 گیگ

من کلا ربات تلگرام رو غیر فعال  کردم درست شد ولی چند روز یبار اورلود میکنه

**Comment by parvizdl** [comment]
از دیروز ربات خاموشه

**Comment by MHSanaei** [comment]
نسخه ۱.۶.۰ به عنوان نسخه اخر در نظر گرفته شد فعلا از همون استفاده کنید

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
