### ISSUE TITLE
ای پی لیمیت

### ISSUE THREAD

**Issue by starqom** [MHSanaei/3x-ui#455]
سلام ممنون از پنل خوبی که ارائه کردید ، اما ای پی لیمیت کار نمیکنه وقتی روی ۱ تنظیم میکنم برای هر کاربر ، همزمان با ۳ گوشی ، و ۳ نت مختلف میتونم به یه اکانت متصل بشم
این باگ قابل رفع هست ؟
اصلا نحوه کارکرد این قسمت به چه صورته؟
ممنونم

**Comment by starqom** [comment]
لازم به ذکر است که من از ریالیتی استفاده میکنم
ایا امکانش هست روی ریالیتی تنظیم کرد که فقط یه نفر وصل بشه

**Comment by mehdikhody** [comment]
آیا از تانل استفاده میکنید ؟

**Comment by starqom** [comment]
v2ray
بدون تانل و پروتکل tcp با ریالیتی

**Comment by UltimateABC** [comment]
کلا IP Limit هیچ وقت برا من کار نکرده

**Comment by BehnamSaedi** [comment]
من هم بدون تانل  vless و پروتکل tcp با ریالیتی دارم IP Limit کار نمی کنه عملا رو چندتا دیوایس با آی پی ها مختلف کار میکنه

**Comment by MHSanaei** [comment]
[bug fix - limit ip](https://github.com/MHSanaei/3x-ui/commit/2223a21cfcd7173aae9c38558ce5865ebbd27097)

**Comment by starqom** [comment]
تست میکنم خبرشو میدم

**Comment by starqom** [comment]
متاسفانه همچنان روی ریالیتی و تی سی پی مشکل دارد و الان بنده با سه تا گوشی و اینترنت مختلف روی یک یوزر وصلم
