### ISSUE TITLE
traffic

### ISSUE THREAD

**Issue by mrv0rtex** [MHSanaei/3x-ui#46]
سلام
احرین اپدیت حجم یوزرها رو بصورت تکی و جدا حساب نمیکنه و روی یوزر مادر فقط اضافه میکنه و بقیه صفر باقی میمونن

**Comment by RezaBaratiy** [comment]
در ضمن الان که تست کردم ترافیک برای کابرها جداگانه محاسبه شد مشکلی نداشت

**Comment by RezaBaratiy** [comment]
> > سلام
> > کاربر جدید هم نمیشه ادد کرد
> 
> روی دکمه actions بزنید و add clients حتی میتونید به تعداد یوزر اضافه کنید در قسمت add bulk

سلام دوست عزیز این گذینرو نمیبینم یعنی اون بعلاوه سبزه اصلا برام نمیاد.البته من فایل دیتابیسشو از پنل قبلی کپی کردم چون اون سرور مشکل پیدا کرده بود
