### ISSUE TITLE
عدم نمایش InBound 

### ISSUE THREAD

**Issue by 9390067696** [MHSanaei/3x-ui#460]
سلام وقت بخیر
پنل ما حدود 70 تا اینباند داشت یهو تعدادش شد 7 عدد
درحالی که کاربرا وصلن و دارن استفاده میکنن ولی اینباند هاشون نشون داده نمیشه
چیکار باید بکنیم؟

**Comment by MHSanaei** [comment]
سلام کدوم ورژن از پنل رو دارید استفاده میکنید؟

**Comment by 9390067696** [comment]
bash <(curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh) v1.0.9
این ورژن بود
امشب اپدیت کردم به جدید
باز هم نمایش نمیده
جدید هم که میسازم ارور CreateFail: malformed JSON  میده

**Comment by MHSanaei** [comment]
باید دیتابیس ادیت کنید و اخرین اینباندی ک در پنل نمایش میده یکی بعد از اون رو داخل دیتابیس حذف کنید
تغییرات رو سیو کنید و در پنل قرار بدید

**Comment by 9390067696** [comment]
درود بر مهندس عزیز
تشکر از لطفتون
حل شد با راه حلی که فرمودید
ویرایش با نرم افزار DB Browser For sqlLite انجام شد
اینجا نوشتم که اگر دوستی دچار چنین مشکلی شد بتونه حل کنه

**Comment by MHSanaei** [comment]
این مشکل در ورژن قدیمی هست که خیلی وقته رفع شده ولی همچنان دوستان علاقمند به استفاده از نسخه های باگ دار دارند :D 
استقامت شما در اپدیت نکردن ستودنیه
