### ISSUE TITLE
کار نکردن Direct

### ISSUE THREAD

**Issue by saeednajafi22** [MHSanaei/3x-ui#461]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام و تشکر از زحمات شما
یک مشکل داشتم
در قسمت Direct Country Configs
گزینه Direct connection to Iran IP ranges
و Direct connection to Iran domains 
رو فعال کرده‌ام، اما ظاهرا کار نمیکند.
به عنوان مثال به سایت ba24.ir و tamin.ir رفتم و هر دو از طریق پروکسی وارد می‌شود و اجازه دسترسی به محتوای سایت نمی‌دهد

### Version of 3x-ui

<details>

```console
# x-ui 1.5.0
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by mmrabbani** [comment]
سلام
هسته xray دستورات direct را در سمت سرور در نظر نمی‌گیرد وفقط به proxy و block توجه میکند. direct را فقط در سمت کلاینت در نظر میگیرد. به نظر می آید باید direct را در پنل حذف کنید، اگرچه آرزو داشتم که میشد این تغییر را در سمت سرور مدیریت کرد

**Comment by MHSanaei** [comment]
قسمت دایرکتی که در پنل اضافه شده برای زمانی هست که شما تانل دارید و 2 سرور استفاده میکنید نه زمانی که یک سرور و مستقیم وصل هستید 
موفق باشید

**Comment by mmrabbani** [comment]
ممنون از توضیحاتتون. عالی می‌شود اگر این موضوع در پنل مشخص باشد که دیگران مثل ما اشتباه نکنند.
