### ISSUE TITLE
از کار افتادن پنل بعد از آپدیت از ورژن ۱.۴.۶ به ۱.۵

### ISSUE THREAD

**Issue by farshadl** [MHSanaei/3x-ui#463]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

بعد از  آپدیت از ورژن ۱.۴.۶ به ۱.۵، دیگه پنلم بالا نمیاد!

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
لطفا بدون دادن جزییات لازم issue باز نکنید
