### ISSUE TITLE
family protection config in version 1.5

### ISSUE THREAD

**Issue by mmrabbani** [MHSanaei/3x-ui#466]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

In version 1.5, family protection is based only DNS and the panel doesn't block "category-porn" anymore (as it did in previous versions).
Please have dual mechanism (DNS and domain list) to increase efficiency.

### Version of 3x-ui

<details>

```console
1.5
```

</details>

### x-ui log reports or xray log

.

**Comment by MHSanaei** [comment]
first click on reset to default then set what you need 
save then reboot

**Comment by mmrabbani** [comment]
I have done so. Blocking by domain list is not added to syntax. It seems there is a bug
