### ISSUE TITLE
به روز نشدن مصرف کاربر

### ISSUE THREAD

**Issue by mohamad-mvm** [MHSanaei/3x-ui#469]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

با سلام
خسته نباشید
من آخرین ورژن رو دارم ولی مقدار مصرف یوزرهام  0 مونده و با مصرف اصلا عوض نمیشه.
ابتدای نصب درست بود ، فقط بعد از یکی دو بار ریست کردن ترافیک این موضوع پیش اومد.
یوزرها صفر هستند ولی inbound اصلی حجم رو نمایش میده.

ممنون از شما

### Version of 3x-ui

<details>

```console
# 1.5.0
```

</details>

### x-ui log reports or xray log

May 18 07:03:04 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:03:04 WARNING - xray log not init in config.json
May 18 07:03:14 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:03:14 WARNING - xray log not init in config.json
May 18 07:03:24 ubuntu-GERMAN2 x
[x-ui.log](https://github.com/MHSanaei/3x-ui/files/11505265/x-ui.log)
-ui[7081]: 2023/05/18 07:03:24 WARNING - xray log not init in config.json
May 18 07:03:34 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:03:34 WARNING - xray log not init in config.json
May 18 07:03:44 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:03:44 WARNING - xray log not init in config.json
May 18 07:03:54 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:03:54 WARNING - xray log not init in config.json
May 18 07:04:04 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:04:04 WARNING - xray log not init in config.json
May 18 07:04:14 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:04:14 WARNING - xray log not init in config.json
May 18 07:04:24 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:04:24 WARNING - xray log not init in config.json
May 18 07:04:34 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:04:34 WARNING - xray log not init in config.json
May 18 07:04:44 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:04:44 WARNING - xray log not init in config.json
May 18 07:04:54 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:04:54 WARNING - xray log not init in config.json
May 18 07:05:04 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:05:04 WARNING - xray log not init in config.json
May 18 07:05:14 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:05:14 WARNING - xray log not init in config.json
May 18 07:05:24 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:05:24 WARNING - xray log not init in config.json
May 18 07:05:34 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:05:34 WARNING - xray log not init in config.json
May 18 07:05:44 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:05:44 WARNING - xray log not init in config.json
May 18 07:05:54 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:05:54 WARNING - xray log not init in config.json
May 18 07:06:04 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:06:04 WARNING - xray log not init in config.json
May 18 07:06:14 ubuntu-GERMAN2 x-ui[7081]: 2023/05/18 07:06:14 WARNING - xray log not init in config.json
[x-ui.log](https://github.com/MHSanaei/3x-ui/files/11505264/x-ui.log)

**Comment by MHSanaei** [comment]
برید داخل تنظیمات و دکمه reset to default رو بزنید
بعدش دکمه سیو و ریبوت رو بزنید

**Comment by mohamad-mvm** [comment]
ممنونم از شما
حل شد
