### ISSUE TITLE
couldn't add cert as text anymore in new update

### ISSUE THREAD

**Issue by ahmadTD** [MHSanaei/3x-ui#472]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I can't add cert for inbound as text anymore after update to 1.5.0

![Screenshot from 2023-05-18 17-25-13](https://github.com/MHSanaei/3x-ui/assets/46419352/0614e21d-f52e-48a3-a534-bb93ed5f2c04)

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
i know that I'll fix it next update
