### ISSUE TITLE
کار نکردن آپشن دیرکت در آخرین آپدیت

### ISSUE THREAD

**Issue by fk6989** [MHSanaei/3x-ui#474]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

من آیپی ها و دامین های ایران رو روی حالت direct  گذاشتم ولی همچنان با آیپی اصلی سرور وارد سایتهای داخلی میشه. با سایت تامین اجتماعی تست کردم. حالت بلاک رو هم برای ایران برداشتم که فقط direct کار کنه.

### Version of 3x-ui

<details>

```console
# 
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by arian2240** [comment]
دقیقا برای منم این مشکلو داره

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/521#issuecomment-1588261510

**Comment by AlirezaVahdani** [comment]
> [#521 (comment)](https://github.com/MHSanaei/3x-ui/issues/521#issuecomment-1588261510)

نمیشه قابلیتی فراهم کنید که بجای بلاک دامنه های ایران ، در حالت معمولی دایرکت کرد؟
یعنی سایت های ایرانی بدون vpn بالا بیاد (از تونل رد نشه)

**Comment by AlirezaVahdani** [comment]
ممنون از توضیحاتتون❤️👌
