### ISSUE TITLE
هم زیستی با ایکس-یوآی

### ISSUE THREAD

**Issue by HosseinMohammadii** [MHSanaei/3x-ui#486]
سلام و خدا قوت
یه مشکلی که هست اینه که من روی یه سرور چندتا پنل دارم. مرزبان و ایکس یوآی اصلی
و وقتی میخوام پنل ۳ایکس یوآی رو نصب کنم گویا بعضی مسیرا مثلا اسکریپت مدیریت با اون اصلیه یکیه و این مشکل درست میکنه. داکر قرار داده شده هم این مشکلو حل نکرد برای من.
به نظرم جا داره که بشه کانفیگ های بیشتری کاستوم کرد و اورد توی کانتینر جدا یا بعضی مسیر هارو جدا و کاستوم کرد برای نصب روی هاست.

(اسما رو فارسی نوشتم چون متن بهم میریخت. دمتون گرم زحمت میکشید)

**Comment by hamid-gh98** [comment]
> من روی یه سرور چندتا پنل دارم. مرزبان و ایکس یوآی اصلی
> و وقتی میخوام پنل ۳ایکس یوآی رو نصب کنم گویا بعضی مسیرا مثلا اسکریپت مدیریت با اون اصلیه یکیه و این مشکل درست میکنه. داکر قرار داده شده هم این مشکلو حل نکرد برای من.

درود،
میتونین از از موارد زیر استفاده کنید تا پوشه `db` و پوشه `bin` مسیرشون رو تغییر بدین، برای فایل `3x-ui` هم میتونین دستی بسازید یا در داکر میتونین همه اینها رو انجام بدین
[Env Variables](https://github.com/MHSanaei/3x-ui#environment-variables)


برای مثال: این رو برای پنل 3x-ui میتونین انجام بدین و پنل چینی هم به همون صورت قبل
```sh
XUI_BIN_FOLDER="/app1/bin" XUI_DB_FOLDER="/app1/db" /app1/3x-ui

XUI_BIN_FOLDER="/app2/bin" XUI_DB_FOLDER="/app2/db" /app2/3x-ui
```

**Comment by HosseinMohammadii** [comment]
ممنونم
برای جدا کردن پورت ۴۴۳ راهی دارید؟
مثلا من دوتا پنل دارم روی یه سرور
یکی دامین۱ برای 3xui که کانفیگا روی پورت داخلی ۹۰۰۰ و یکی دامین۲ برای پنل مرزبان که کانفیگا روی پورت داخلی ۹۰۹۰ سرو میشن. و میخوام جفتشون از بیرون روی پورت ۴۴۳ قابل دسترسی باشن.
با nginx میشه هندلش کرد؟ مثلا هر نوع کانکشنی از دامین۱ (tcp, ws, grpc) بره روی ۹۰۰۰ و از دامین۲ بره روی ۹۰۹۰

**Comment by hamid-gh98** [comment]
> مثلا من دوتا پنل دارم روی یه سرور
> یکی دامین۱ برای 3xui که کانفیگا روی پورت داخلی ۹۰۰۰ و یکی دامین۲ برای پنل مرزبان که کانفیگا روی پورت داخلی ۹۰۹۰ سرو میشن. و میخوام جفتشون از بیرون روی پورت ۴۴۳ قابل دسترسی باشن.
> با nginx میشه هندلش کرد؟ مثلا هر نوع کانکشنی از دامین۱ (tcp, ws, grpc) بره روی ۹۰۰۰ و از دامین۲ بره روی ۹۰۹۰

بله میتونید از nginx استفاده کنید. 
اگر دوتا دامین دارین و دوتا پورت میتونین از یه کانفیگ شبیه این انجام بدین ولی بهتره از گوگل سرچ کنید که چطور باید باشه. چون برای هر پروتکل فرق میکنه

میتونین یه نگاه هم به این نمونه ها بندازین: [Examples](https://github.com/XTLS/Xray-examples)

نمونش اینطور میشه:
```nginx
# for second panel on port 9000
server {
    listen 443;
    server_name domain1.com;

    # TCP
    location /PATH1 {
        proxy_pass tcp://localhost:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # WS
    location /PATH2 {
        if ($http_upgrade != "websocket") {
            return 404;
        }
        proxy_pass http://localhost:9000;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 52w;
    }

    # GRPC
    location /PATH3 {
        grpc_pass grpc://localhost:9000;
    }
}

# for second panel on port 9090
server {
    listen 443;
    server_name domain2.com;

    # TCP
    location /PATH1 {
        proxy_pass tcp://localhost:9090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # WS
    location /PATH2 {
        if ($http_upgrade != "websocket") {
            return 404;
        }
        proxy_pass http://localhost:9090;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 52w;
    }
}
```
