### ISSUE TITLE
مشکل در warp

### ISSUE THREAD

**Issue by iamfarhad** [MHSanaei/3x-ui#488]
سلام

وقت بخیر 

من warp رو نصب کردم اما زمانی که wgcf trace میگیرم وضعیتش رو off نشون میده و ترافیک که از 40000 رد میشه با warp نیست

**Comment by hamid-gh98** [comment]
درود،
شما اگر میخواید که چک کنید باید سایتی که trace میگیرید هم به وارپ اضافه کنید بعد تست بگیری.
مثلا در پنل در قسمت وارپ این رو اضاف کنید `geosite:cloudflare` بعد وارد لینک زیر بشید برای trace
[trace](https://cloudflare.com/cdn-cgi/trace)

**Comment by iamfarhad** [comment]
ممنون

مشکلم حل شد
