### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ItsElw** [MHSanaei/3x-ui#49]
سلام و وقت بخیر

من یه مشکل خیلی عجیب برام پیش اومد

روی ایکس یوایم ۷۰ تا کاربر داشتم

یه نفر حجمش تموم شده بود،گفت تمدید کن
من اسمشو سرچ زدم فعالش کردم کاربرای پنلم شد ۳۲تا

یعنی تقریبا ۴۰ نفر حذف شدن

اون ۴۰ نفر الان وصلن ولی تو پنل دیده نمیشن،حتی بکاپ گرفتم بردم روی یک سرور دیگه ولی ارور داد

راه حلی دارید برای این باگ؟

**Comment by netAtiran** [comment]
سلام من چند روزه کلا اذیت میکنه کانفینگ Vmess 
میسازم بعد اجرا نمیکنه تو برنامه v2rayng مینویسه EOF لطفاً راهنمایی کنید

**Comment by Ikowsh** [comment]
مشکل eof به دلیل خاموش بودن خودکار تنظیم ساعت منطقه گوشیه

**Comment by Elhwm** [comment]
> از کدوم ورژن استفاده میکنید؟ x-ui status رو داخل سرور بزنید

راسیتش ورژن دقیقشو نمیدونم،یا ۱.۰۸ یا ۱.۰.۷،راهی برای فهمیدن دقیق ورژن هست؟
وضعیت ایکس ری رانینگ هست،و حتی کاربرای حذف شده هم هنوز متصلن ولی توی پنل نمایش داده نمیشن،انگار این باگ مربوط به فرانت انده

راهی هست که من اطلاعات کاربرای حذف شده(تاریخ انقضا و حجم)رو دربیارم؟مثلا این اطلاعات توی کدوم فایل ذخیره میشن؟با تشکر

**Comment by Elhwm** [comment]
> > > از کدوم ورژن استفاده میکنید؟ x-ui status رو داخل سرور بزنید
> > 
> > 
> > راسیتش ورژن دقیقشو نمیدونم،یا ۱.۰۸ یا ۱.۰.۷،راهی برای فهمیدن دقیق ورژن هست؟
> > وضعیت ایکس ری رانینگ هست،و حتی کاربرای حذف شده هم هنوز متصلن ولی توی پنل نمایش داده نمیشن،انگار این باگ مربوط به فرانت انده
> > راهی هست که من اطلاعات کاربرای حذف شده(تاریخ انقضا و حجم)رو دربیارم؟مثلا این اطلاعات توی کدوم فایل ذخیره میشن؟با تشکر
> 
> این باگه خیلی بد توی ورژن های قدیمی بود که سریع با اپدیت حل شد ورژن پنل رو میتونید با این دستور بفهمید x-ui status ia x-ui log یوزر های شما در حال حاضر یا داخل دیتابیس هستند یا فایل کانفیگ که در این مسیر میتونید پیدا کنید /etc/x-ui/x-ui.db /usr/local/x-ui/bin/config.json

متاسفانه داخل فایل کانفیگ فقط تعداد محدودی از یوزرا وجود داشتن و فایل دیتابیس رو هم با وی اس کد باز کردم انچنان خوانا نبود

**Comment by ali90500** [comment]
سلام وقت به خیر
منم همین مشکل برام پیش اومد دقیقا
به تازگی این پنل رو نصب کرده بودم
اول وقتی حجم رو تمدید کردم کلا اون یوزر دیگه نشون داده نمیشد و بعد از اون دیگه هرچی یوزر میسازم داخل پنل اضافه نمیشه یعنی داخل فایل دیتابیس میره اما توی پنل نیست، هرکارم کردم درست نشد حتی پنل چینی x-ui رو هم نصب کردم بازم فرقی نکرد دیگه نمیشه یوزر ساخت روی اون دیتابیس، کاری میشه کرد؟
