### ISSUE TITLE
اضافه کردن توضیحات

### ISSUE THREAD

**Issue by MosaIssei** [MHSanaei/3x-ui#492]
سلام
ممنون میشم برای کاربر ها یک قسمتی درست کنید که توضیحات هر کاربر رو اونجا ذخیره کنیم و با سرچ هم بتونیم پیدا کنیم
بعضی از کاربر ها نمی‌خوان اسمشون تو کانفیگ باشه وقتی میخوای تشخیص شون بدی خیلی سخته

**Comment by peymanch** [comment]
بله فیلد Description به هر client اضافه بشه عالی میشه
