### ISSUE TITLE
ربات تلگرام

### ISSUE THREAD

**Issue by sadegh1210** [MHSanaei/3x-ui#493]
وقت بخیر
ربات تلگرام بروی پنلی ک رو سرور ایرانه کار نمیده.
البته طبیعی هم هست چون تلگرام فیلتر بروی سرور های ایران.
راه حلی برای حل این موضوع ندارید ک بشه یجوری تلگرامه هم پروکسیش کرد؟

**Comment by MHSanaei** [comment]
https://github.com/alireza0/x-ui/issues/252#issuecomment-1518355423

**Comment by mohamadn69** [comment]
سلام ربات را روی سرور ایران فعال کردم این خطا داخل لاگ میاد
ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
