### ISSUE TITLE
API Curl Problem

### ISSUE THREAD

**Issue by peymanch** [MHSanaei/3x-ui#495]
سلام وقت بخیر
من وقتی با کرل میخوام لاگین کنم به API این پیغام رو میگیرم لطف می کنید منو راهنمایی کنید؟

curl -X POST -H "Content-Type: application/json" -d '{"username":"admin","password":"MyPassword"}' https://MyDomain.cf:2096/login

{"success":false,"msg":"数据格式错误","obj":null}

**Comment by hamid-gh98** [comment]
درود،
میتونین از این فرمت استفاده کنید

```sh
curl -L -X POST "http://localhost:2053/login" \
-H "Accept-Language: en-US" \
-H "Content-Type: application/x-www-form-urlencoded" \
-d "username=admin&password=admin"
```

**Comment by peymanch** [comment]
ممنون دوست عزیز لطف می کنید دستور GET /list را هم بفرستید

**Comment by hamid-gh98** [comment]
اگر از این ورژن یا بالاتر از `v1.4.6`:
```sh
curl -L -X GET 'http://localhost:2053/panel/api/inbounds/list' \
-H 'Accept-Language: en-US' \
-H 'Cookie: session={{SESSION_COOKIE}}'
```
اگر از ورژن پایین تر استفاده میکنید:
بخش آدرس رو تغییر بدین به `'http://localhost:2053/xui/API/inbounds/list'`

قسمت `{{SESSION_COOKIE}}` هم باید به کوکی که از `login` گرفتین، ست کنید
