### ISSUE TITLE
TLS/XTLS Not Work

### ISSUE THREAD

**Issue by PixesApp** [MHSanaei/3x-ui#50]
Hello dear developer. I use the software you created individually, but with the last update, vmess, vless and trojan that I created as tls and xtls do not work. What is the problem ? Thanks

**Comment by alireza0** [comment]
Hello @VPNCI ,
Could you please send us more information about your tls/xtls configuration ?
There is a known bug that we are not sure if it is related to this problem.

P.S. Could you please test them by setting ALPN to `none` ?

**Comment by wilbernight** [comment]
It does not work for me with the same problem, XTLS only works with previous configurations and any new XTLS will not work with this configuration.


`{
  "log": {
    "loglevel": "warning", 
    "access": "./access.log"
  },
 
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private",
          "geoip:ir"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}`

**Comment by VPNCI** [comment]
![Screenshot_2023-03-22-13-31-29-699_com android chrome-edit](https://user-images.githubusercontent.com/82672037/226877263-c89a1da6-0894-448f-b86b-b9fa08481b18.jpg)
![Screenshot_2023-03-22-13-34-37-119_com server auditor ssh client-edit](https://user-images.githubusercontent.com/82672037/226877281-c69ec3f2-af05-41f0-85cc-c8fa37bdf64c.jpg)

Normal TLS or xtls settings that I always create.  After the last update, when I try to connect, I get a timeout warning.  Shadowsocks works fine as it doesn't want TLS.

**Comment by alireza0** [comment]
@VPNCI Thank youfor providing this data.
But I need next page of your screenshot which contains more `tlsSettings`

**Comment by VPNCI** [comment]
Of course

![Uploading IMG_20230322_134245.jpg…]()

**Comment by VPNCI** [comment]
Of course

![IMG_20230322_134245](https://user-images.githubusercontent.com/82672037/226879541-a4a11ae9-d641-47ca-8e65-347aaa1020c1.jpg)

**Comment by alireza0** [comment]
> Of course
> 
> ![IMG_20230322_134245](https://user-images.githubusercontent.com/82672037/226879541-a4a11ae9-d641-47ca-8e65-347aaa1020c1.jpg)

Not this one actually. But in file `/usr/loca/x-ui/bin/config.json`

**Comment by VPNCI** [comment]
Trojan TLS settings

{
      "listen": null,
      "port": 443,
      "protocol": "trojan",
      "settings": {
        "clients": [
          {
            "email": "m9szcvl38v",
            "expiryTime": "",
            "flow": "",
            "limitIp": 0,
            "password": "03PlHRa7iG",
            "totalGB": 0
          }
        ],
        "fallbacks": []
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "serverName": "xxxx.com",
          "minVersion": "1.2",
          "maxVersion": "1.3",
          "cipherSuites": ""
          "certificates": [
            {
              "certificateFile": "/etc/letsencrypt/live/xxx.com/fullchain.pem>
              "keyFile": "/etc/letsencrypt/live/xxx.xom/privkey.pem"
            }
          ],
            "alpn": [
            ""
          ],
          "settings": [
            {
              "allowInsecure": false,
              "fingerprint": "",
              "serverName": "xxx.com"
            }
          ]
        },
        "tcpSettings": {
          "header": {
            "type": "none"
          },
          "acceptProxyProtocol": false
        }
      },
      "tag": "inbound-443",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },`

**Comment by alireza0** [comment]
به نظر میاد مشکل فقط alpn بوده.
میتونید روی h2 بذارید و نتیجه تست رو بفرستید ؟

**Comment by alireza0** [comment]
It seems the problem is in ALPN only!
Could you please set it to "h2" only and test if it works ?

**Comment by VPNCI** [comment]
> It seems the problem is in ALPN only! Could you please set it to "h2" only and test if it works ?

Hello again.  I tried ALPN h2 connection failed.  I also tried http/1.1 and failed. If you want, I can send you panel and server information.  Do you have a Telegram address?

**Comment by alireza0** [comment]
Please send an email to me
