### ISSUE TITLE
نحوه استفاده از کانفیگ ها در فلاتر

### ISSUE THREAD

**Issue by Bestsenator** [MHSanaei/3x-ui#501]
سلام وقتتون بخیر
میتونین منو راهنمایی کنید که چطوری میتونم کانفیگ های تولیدی رو روی اپ فلاتری پیاده سازی بکنم ؟
یه سری پکیج مثل libv2ray , flutter_v2ray بود که چک کردم منسوخ شده بود

**Comment by mehdikhody** [comment]
باید هسته v2ray که همان xray است را داخل برنامه قرار دهید.
برای پیگربندی یک inbound با پروتکل HTTP یا SOCKS و یک outbound با پروتکل دلخواه به سمت سرور خود ایجاد کنید.
سپس برنامه v2ray را با استفاده از پیگربندی که ایجاد کردین راه اندازی کنید.

در آخر هم تنظیمات پروکسی گوشی را برای اتصال به inbound ایجاد شده داخل گوشی تنظیم کنید.

برای این کار از مستندات اندروید استفاده کنید.
https://developer.android.com/guide/topics/connectivity/vpn

**Comment by soheylfarzane** [comment]
منم دقیقا همین مورد رو لازم دارم هیچ کسی نیست که بتونه کمک کنه که بشه خیلی ساده کاربر کد vmess رو بزنه و مبشه متصل بشه ؟

**Comment by javadmahmoodi670** [comment]
منم خیلی تحقیق کردم برای فلاتر ولی به نتیجه نرسیدم برای انجام همچین کاری.

**Comment by soheylfarzane** [comment]
یه مورد تو یوتیوب دیدم پیام دادم بهش گفت ۸۰۰۰ دلار 😐

**Comment by soheylfarzane** [comment]
> منم خیلی تحقیق کردم برای فلاتر ولی به نتیجه نرسیدم برای انجام همچین کاری. 

یه مورد تو یوتیوب دیدم پیام دادم گفت ۸۰۰۰ دلار 😐
