### ISSUE TITLE
I am unable to open the settings interface of the panel. Clicking on settings will leave it blank

### ISSUE THREAD

**Issue by 759071793** [MHSanaei/3x-ui#504]
I am unable to open the settings interface of the panel. Clicking on settings will leave it blank

**Comment by 759071793** [comment]
`Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at getCookie (common.js?1.5.0:73:25)
    at getLang (langs.js:25:16)
    at settings:582:19`

**Comment by 759071793** [comment]
its ok

**Comment by yoman88111** [comment]
What was the uissue? Have the same problem.
