### ISSUE TITLE
ip limit کارنکردن 

### ISSUE THREAD

**Issue by md9786** [MHSanaei/3x-ui#508]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام خسته نباشید 
من هرچی تست انجام دادم ip limit کار نمیکنه و با این که لیمیت 1 کاربر گذاشتم باز هر چند کاربر میتونن وصل بشن و استفاده کنن.

![image](https://github.com/MHSanaei/3x-ui/assets/66461507/4c2f1ce1-5cc7-4238-8d6d-7c91beb98d05)

### Version of 3x-ui

<details>

```console
1.5.0

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by mehdikhody** [comment]
تانل کردی ؟

**Comment by md9786** [comment]
> تانل کردی ؟
با تانل ک کلا 1 آیپی نشون میده نه تانل نیست

**Comment by jenaze** [comment]
از آخرین ورژن ubunto 22 استفاده کن

**Comment by md9786** [comment]
> از ubunto 22 استفاده کن

رو 22.10 ام
