### ISSUE TITLE
Email addresses under different protocols cannot be the same

### ISSUE THREAD

**Issue by rplover** [MHSanaei/3x-ui#510]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Email addresses under different protocols cannot be the same

### Version of 3x-ui

<details>

```console
# V1.5.0
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
yes email must be unique for each protocol and client
