### ISSUE TITLE
users disconnect

### ISSUE THREAD

**Issue by seingod** [MHSanaei/3x-ui#512]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello
After I add a user using the API, the clients that are connected are disconnected and the client must be restarted to connect again.
Can this problem be solved?
I now create and edit users in advance so that they don't get disconnected

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by hamid-gh98** [comment]
I think [this commit](https://github.com/MHSanaei/3x-ui/commit/70f250dfe1e24249a4cc8102e3fef65959dfb15a) would fix your problem (it uses the xray api), and it will be available in the next release.
