### ISSUE TITLE
اشکال در اتصال مستقیم به سایت های داخلی

### ISSUE THREAD

**Issue by soheylfarzane** [MHSanaei/3x-ui#513]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

متاسفانه برای اتصال مستقیم عملکرد مشکل داره
زمانی که اتصال به مساقیم به سایت یا دامنه رو قعال میکنمیم کار نمیکنه
برای مثال bmi.ir با اینکه ثبتش کردم تو پنل همچنان باز نمیشه سایتش

### Version of 3x-ui

<details>

1.6.0

</details>

### x-ui log reports or xray log

<details>

</details>

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/461#issuecomment-1552061034

**Comment by soheylfarzane** [comment]
حل شده این مورد ؟
