### ISSUE TITLE
Expire Notification Telegram Bot

### ISSUE THREAD

**Issue by Amirziplin** [MHSanaei/3x-ui#515]
لطفا در صورت امکان  هشدار اتمام تاریخ  و حجم کابر از طریق ربات تلگرام (مثلا 1 روز قبل از پایان تاریخ، به کاربر پیام بده) رو اضافه کنید.

**Comment by echo-333** [comment]
همین آپشن اگر حتی فقط به ادمین هم پیام بده خیلی عالی میشه
