### ISSUE TITLE
How to migrate x-ui to 3x-ui program which have lots of user configs.

### ISSUE THREAD

**Issue by Amos-Dan** [MHSanaei/3x-ui#517]
I have used x-ui program for a while.
Now I want migrate x-ui to 3x-ui. But I found the x-ui.db is different from 3x-ui.
So I wounder if there is an easy way to migrate x-ui to 3x-ui
The x-ui program address is show below.
https://github.com/FranzKafkaYu/x-ui/

**Comment by MHSanaei** [comment]
just install our panel on your server we have auto-migrated on install.sh

**Comment by Amos-Dan** [comment]
wow, Thank you so much for your reply
