### ISSUE TITLE
Listening IP Problem with the Same Port

### ISSUE THREAD

**Issue by amintn** [MHSanaei/3x-ui#520]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

وقت بخیر
توی پنل وقتی از Listening IP استفاده می‌کنیم و یک Inbound روی یک پورت خاصی می‌سازیم، دیگه امکان ساخت یک Inbound جدید با یک آی‌پی جدید روی همان پورت را نداریم و خطای CreateFail: Port already exists میگیریم.
این در حالیه که توی xray این قابلیت وجود داره و اگر مثلا سرور ما چند تا آی‌پی داشته باشه، می‌تونیم روی هر کدام از این آی‌پی‌ها و یک پورت مشابه (مثلا ۴۴۳) یک Inbound جدا داشته باشیم.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
فقط در fallback این امکان وجود داره که روی یک پورت چند پروتکل بزنید
