### ISSUE TITLE
کانفیگ xray سایت های ایرانی

### ISSUE THREAD

**Issue by amiralibk** [MHSanaei/3x-ui#521]
سلام
وقت بخیر
این فایل کانفیگ بلاک کردن آیپی و دامنه های ایرانی رو جایگزین کردم ولی باز کار نمیکنه!
 نه سایت های بانک رو باز میکنه نه سایت نماد نه سایت دولتی!
احتمالا یجای کار ی باگی هست! اطلاع دادم که اگر ممکنه سرفرصت بررسی کنید
تشکر فراوان

**Comment by fakoor** [comment]
بلاک برای امنیت سرورتون هست.
یعنی وقتی اشتباها سایت‌های ایرانی رو موقع وصل بودن به وی‌پی‌ان مرور می‌کنید هدفش اینه که چیزی باز نشه.
به این شکل اون سایت نمی‌تونه سرور وی‌پی‌ان شما رو به جایی گزارش بده برای از کار انداختنش
پس اگر سایتی باز نمی‌شه، به اون معنیه که این قابلیت داره درست می‌کنه
(همان دلیلی که کانفیگ‌ها رو نباید از طریق پلتفورم‌های حامی سانسور نظیر پیامک اوپراتوری یا پیامرسان‌های ملی انتشار دهید)

**Comment by simboos** [comment]
> بلاک برای امنیت سرورتون هست. یعنی وقتی اشتباها سایت‌های ایرانی رو موقع وصل بودن به وی‌پی‌ان مرور می‌کنید هدفش اینه که چیزی باز نشه. به این شکل اون سایت نمی‌تونه سرور وی‌پی‌ان شما رو به جایی گزارش بده برای از کار انداختنش پس اگر سایتی باز نمی‌شه، به اون معنیه که این قابلیت داره درست می‌کنه (همان دلیلی که کانفیگ‌ها رو نباید از طریق پلتفورم‌های حامی سانسور نظیر پیامک اوپراتوری یا پیامرسان‌های ملی انتشار دهید)

نه منظورشون قابلیت دایرکت ایپی ایران هست که توی اپدیت جدید معرفی شده. برای منم کار نمیکنه  یا شاید باید اول ایپی های ایران رو از بلاک در بیارم تا قابلیتش فعال بشه. لطفا یه توضیح کوچیک به ما بدید

**Comment by amiralibk** [comment]
> > بلاک برای امنیت سرورتون هست. یعنی وقتی اشتباها سایت‌های ایرانی رو موقع وصل بودن به وی‌پی‌ان مرور می‌کنید هدفش اینه که چیزی باز نشه. به این شکل اون سایت نمی‌تونه سرور وی‌پی‌ان شما رو به جایی گزارش بده برای از کار انداختنش پس اگر سایتی باز نمی‌شه، به اون معنیه که این قابلیت داره درست می‌کنه (همان دلیلی که کانفیگ‌ها رو نباید از طریق پلتفورم‌های حامی سانسور نظیر پیامک اوپراتوری یا پیامرسان‌های ملی انتشار دهید)
> 
> نه منظورشون قابلیت دایرکت ایپی ایران هست که توی اپدیت جدید معرفی شده. برای منم کار نمیکنه یا شاید باید اول ایپی های ایران رو از بلاک در بیارم تا قابلیتش فعال بشه. لطفا یه توضیح کوچیک به ما بدید

دقیقا منظورم همینه . دایرکت نمیکنه

**Comment by MHSanaei** [comment]
برای کسانی هست که تانل میزنن و از dokodemo استفاده میکنند
