### ISSUE TITLE
Something went wrong!Fail: database is locked

### ISSUE THREAD

**Issue by armineyvazi** [MHSanaei/3x-ui#522]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

dalile in error chist ?

### Version of 3x-ui

v 1.8.1

### x-ui log reports or xray log

Something went wrong!Fail: database is locked

**Comment by MHSanaei** [comment]
یکی از این موارد
سرور ضعیف
ترافیک زیاد سرور
بی کیفیت بودن سرور

با تعویض سرور و خرید از سایت بهتر مشکل حل میشه

**Comment by GoneWithGoD** [comment]
من دقیقا با همین کانفیگ سرور تا دو روز قبلش کار میکردم هیچ مشکلی هم نبود
ای پی فیلتر شد، عوض کردن برام، بعد چندتا کانفیگ ساختم و همه چی اوکی بود، یهو خورد به این ارور
اگه از سرور بود با سرور قبلی مشکل پیدا میکرد
