### ISSUE TITLE
CPU Overload

### ISSUE THREAD

**Issue by Amirziplin** [MHSanaei/3x-ui#524]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

تو نسخه 1.5 با 80 تا یوزر مشکلی نداشتم ، به نسخه 1.6 آپدیت کردم  لود سی پی یو اکثرا 100 درصد میشد و سرعت دانلود پایین میومد.

### Version of 3x-ui

<details>

```console
#1.6.0
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by parvizdl** [comment]
من هم این مشکل رو دارم

**Comment by X-Oracle** [comment]
من هم همینطور . متاسفانه نمیدونم از کجا هست .

**Comment by parvizdl** [comment]
من الان تو مشکل یکی دیگه خوندم نوشته اون مهم نیست و پنل ارائه دهنده رو ببینید اون مستنده . برای مثال مال من مدام رو 99 ولی پنل هتزنر کامل رو 80

**Comment by X-Oracle** [comment]
حالا که دقت کردم درسته. یک نمودار از سی پی یو یوزیج گرفتم از خود سرور . ولی x-ui  خودش یکدفعه ۹۰ یا ۱۰۰ می‌ره و الکی هشدار تلگرام میده .

**Comment by parvizdl** [comment]
چند تا یوز روشه و چند هسته دارید ؟ من 160 تا یوز و 2 هسته

**Comment by X-Oracle** [comment]
1 هسته . ۱ گیگ .
۱۵ یوزر (خانوادگی هست)
ولی بازم اورلود میده

**Comment by parvizdl** [comment]
نه آقا این مشکل جدی داره ، با هر کی حرف میزنم همینجوری شده . الان سرور و پاک کردم دوباره اینجوری شده . از توی هتزنر هم نشون میده سی پی یو رو 98 درصده و من الان منابع رو زیاد هم کردم اوکی نشده الان 4 هسته دارم با 8 گیگ

**Comment by MHSanaei** [comment]
نسخه ۱.۶.۰ به عنوان نسخه اخر در نظر گرفته شد فعلا از همون استفاده کنید

**Comment by X-Oracle** [comment]
یک سوال.
@MHSanaei 

توی 1.8.1 گفتین که قابلیت سرعت سی پی یو و نمایش آیپی4 و 6 اضافه کردین .
ممکنه به خاطر چک کردن مداوم این ها باشه ؟
یا اینکه کد ایراد داشته باشه و لوپ ایجاد کنه ؟

- اگر اینجوری باشه که بهتره مکانیسم بهتری براش بزارید
 
- یا اینکه فقط یک چک اولیه موقع استارت x-ui شود و بعد گذینه ریفرش براش گذاشته شود تا هر قت خودمان خواستیم بزنیم تا اطلاعات ip به روز شود و مشکل موقت حل شود .
البته برای تعداد کور ها و سرعت سی پی یو همون چک استارت اولیه کافیه چون در صورت تغییر باز باید سرور ری استارت بشه که بازم مساوی با ری استارت شدن x-ui.

- اگر از api جایی هم برای دریافت اطلاعات ip استفاده میشه . به شخصه دیدم که بعضی سرورا رو بلاک کردن. ممکنه که لوپ ایجاد بشه.

**Comment by MHSanaei** [comment]
خیر به خاطر ای پی لیمیت هست

**Comment by hhamed1989** [comment]
> نسخه ۱.۶.۰ به عنوان نسخه اخر در نظر گرفته شد فعلا از همون استفاده کنید

حل شد، مصرف CPU، یک چهارم شد.

**Comment by Amirziplin** [comment]
> 

چطور حل شد؟نسخه 1.6 نصب کردی؟

**Comment by parvizdl** [comment]
نه 1.6.0

**Comment by X-Oracle** [comment]
@MHSanaei 
Is cpu overload primer l problem still exists in 1.7.0

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
