### ISSUE TITLE
!!!OVERUSE OF RAM HARD CPU PLZ HELP!!!

### ISSUE THREAD

**Issue by SAINTARK** [MHSanaei/3x-ui#526]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![D1FC2646-109D-4AAE-AE74-709D9EC31437](https://github.com/MHSanaei/3x-ui/assets/126692110/d2f157fb-1e6b-4d3c-a2a0-c2d0ce7d19f3)

!!لطفا کمک‌کنید‌دلیل این مشکل چیه راهنمایی کنید!!

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
سلام اگر از وارپ استفاده میکنید یکی از دلایل اصلی در مصرف رم بالا است درغیر این صورت مشکل رو در سرور خودتون دنبال کنید 
اپدیت اخر هم نصب کنید

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
