### ISSUE TITLE
نیاز به تغییر ادرس در کانفیگ با تی ال اس خاموش

### ISSUE THREAD

**Issue by Aronablade** [MHSanaei/3x-ui#528]
ببخشید دوباره پست زدم چون متن قبلی پیچیده شده بود،  میشه یکی راهنمایی کنه الان تو یه کانفیگ ساده مثل این که tls خاموش هست. چطوری میشه address رو از ادرس پنل به دامین دیگه ایی تغییر داد که وقتی از لینک سابسکرایب استفاده میشه هم تغییر کنه؟  تو عکس منظورم مشخص تره فکر کنم

![FEADD3AA-E2DD-47D0-8C00-A4AAAD908F5F](https://github.com/MHSanaei/3x-ui/assets/121737216/0587ef22-3381-48d1-a3f3-d7b1cd1e96af)

**Comment by MHSanaei** [comment]
این امکان به اون شکلی که مد نظر شماست بدون security در این پنل وجود نداره
