### ISSUE TITLE
بعد از بروزرسانی به نسخه جدید 1.6، سرویس ایکس ری استوپ میشود

### ISSUE THREAD

**Issue by sm-saeedmoosavi** [MHSanaei/3x-ui#529]
سلام
من از نسخه 1.3 به 1.6 ارتقا دادم. ولی سرویس استوپ شد و استارت نمیشه
حتی سرور رو ریبیلد کردم و از ابتدا نسخه 1.6 رو بصورت خام نصب کردم. که با موفقیت نصب شد و سرویس هم ران بود.
ولی وقتی فایل بکاپ دیتابیس نسخه قبل رو جاگذاری کردم باز هم سرویس استوپ شد.
لطفا راهنمایی کنید چطور بکاپ دیتابیسم رو روی نسخه جدید برگردونم که استوپ نکنه.
چون به یوزرهای تعریف شده داخل بکاپ نیاز دارم.
با تشکر

**Comment by amirnois3** [comment]
همه پروفایل هارو خاموش کن دونه دونه روشن کن ببین سر کدوم استوپ میکنه همونو بعد اصلاح کن.این کارو دقیق انجام بده ، برعکس دونه دونه خاموش نکنی!
