### ISSUE TITLE
افزایش ناگهانی مصرف cpu

### ISSUE THREAD

**Issue by mostafa5804** [MHSanaei/3x-ui#53]
با سلام
از طریق ربات تلگرامی میزان مصرف cpu رو تحت نظر قرار دادم
زمان زیادی هست که افزایش ناگهانی در سرور دیده میشه و تا ۱۰۰ درصد درگیر میکنه
![Screenshot_20230321-154339_Plus](https://user-images.githubusercontent.com/122720103/226602949-45afe85e-dec9-4a8b-be86-a6e2df46ce76.jpg)

از طریق دستور  htopتسک سرور رو تحت نظر گرفتم
سنگین ترین ها به ترتیب زیر هستن
 bin/xray-linux-amd64 -c bin/config.json -restrictedIPsPath ./bin/blockedIPs

![Screenshot_20230321-154125_Termius](https://user-images.githubusercontent.com/122720103/226603233-66f09060-ecc4-472f-9817-b46cc17c3533.jpg)

ممنون میشم راهنمایی کنید

**Comment by alireza0** [comment]
درود بر شما
مشکلش کجاست ؟
شما یک cpu دارید که خب برای انجام کارهای خود سیستم عامل ممکنه به 100% برسه.
بیشترین دلایل مصرف بالای cpu:
۱. استفاده از tls/xtls/reality
.۲ استفاده از access.log برای ip-limit باعث افزایش I/O  میشه و در نتیجه interrupt های رو بیشتر میکنه
۳. تعداد بالای مصرف کننده و پهنای باند مصرفی
۴. تعداد پورت های باز زیاد
۵. استفاده از سیستم عامل غیر مینیمال ( هر نرم افزاری مصرف cpu خودش رو داره )

**Comment by mostafa5804** [comment]
تشکر از پاسختون
چون اطلاع خاصی نداشتم گفتم بپرسم
چون نه پهنای باند زیادی دارم و نه مصرف کننده بالا که طبیعتا پورت باز کمی هم هست
پس در کل مشکل خاصی نیست و نباید پیگیرش باشم؟

**Comment by alireza0** [comment]
نه نگران نباشید، برای شما مصرف cpu نباید مهم باشه، مگر اینکه همه استفاده کننده ها مشکل طولانی مدت داشته باشند.
برای سرورهایی که تعداد cpu بیشتر و کاربر خیلی بالا دارند مسلما بیشتر شدن این فاکتور باید سریعا بررسی بشه.
