### ISSUE TITLE
مصرف همه یوزر ها صفره و نمیتونم آپدیت کنم !!!!

### ISSUE THREAD

**Issue by AghaFarokh** [MHSanaei/3x-ui#533]
سلام و خسته نباشید

من با API میزنم همچیو و چون باید کدم رو عوض کنم و هنوز نرسیدم نمیتونم ورژنی جدیدتر از 1.1.4 نصب کنم فعلا

یه عالمه یوزر دارم که مصرفشون صفره
نمیتونمم پاک کنم از نو بسازم همچیم بهم میریزه چون باید کلی دیتا توی دیتابیس خودمم عوض کنم

به من بگو چیکار کنم تو این وضعیت
تا اینجا صفر بوده اشکال نداره از اینجا به بعدو حساب کنه حداقل

قبلا 1.0.8 بودم اوکی بود بعد از عوض کردنش این مشکل پیش اومده
الان نه میتونم آپدیت کنم، نه میتونم یوزرارو پاک کنم و باید یحوری این مشکل 0 بودن حجم درست بشه

راهنمایی لطفا
ممنونتم

**Comment by AghaFarokh** [comment]
دانگرید کنم اوکی میشه ؟

**Comment by MHSanaei** [comment]
کسانی که ترافیک یوزراشون نمیفته 3تا حالت داره 
اگر کل یوزرهاتون ترافیک نمیندازه مشکل از کانفیگ ایکس ری هست برید داخل تنظیمات و دکمه reset to default رو بزنید و سیو و ریبوت کنید

اگر فقط تعدادی یوزر این مشکل رو دارن احتمالا بات دارید که مشکل از اون بات هست اطلاعات یوزر مثل ایمیل رو وارد نمیکنه

اگر بات ندارین کافیه نسخه اخر پنل رو نصب کنید اگر دیتابیس جابجا کردین بازم یه بار نسخه اخر پنل رو نصب کنید که مشکل دیتابیس شما رفع شه
