### ISSUE TITLE
Question about user UUID log

### ISSUE THREAD

**Issue by epsilonzeio** [MHSanaei/3x-ui#582]
Hi,
I'm using Hiddify panel as it's mentioned as one of the verified Web panels in Xcore main page repository.
But I faced an issue in my panel logs realizing that for each user& the UUID info is sent to a Hiddify automatic email. Please check the screenshots as below.

https://ibb.co/WfNCBxR
https://ibb.co/198nLtr
https://ibb.co/X7g43s3

As proxy webpanel is your field profession just want to be sure if is there any security or privacy issue about that.
It felt a warning about this issue.

**Comment by epsilonzeio** [comment]
Many thanks for the reply.
Do you know where the Hiddify team came from? I got many attacks from Iran
to my server after divulging these logs in their channel.

**Comment by MHSanaei** [comment]
they're Iranian

**Comment by epsilonzeio** [comment]
thanks. the issue with the email is it exists. I mean it's not a fake email.

**Comment by MHSanaei** [comment]
maybe, i don't know, go ask them

**Comment by epsilonzeio** [comment]
I asked. they banned me from their telegram support group without answering!

**Comment by MHSanaei** [comment]
sorry about that,just change your panel to something else

**Comment by epsilonzeio** [comment]
yes sure. I removed it. the issue is I needed a mutli user panel with reality and singbox and unfortunately Hiddify was the only that provided this. If you have any suggestion will be thankful.

**Comment by X-Oracle** [comment]
This panel has reality and xray . Unfortunately I can't find an alternative to use reality with sing-box.
