### ISSUE TITLE
تنظیم خاموش روشن کردن اعلان ورود به پنل آزار دهنده در ربات

### ISSUE THREAD

**Issue by Ikowsh** [MHSanaei/3x-ui#584]
درود به جناب ثنایی 
میشه لطفا دکمه ای تعبیه کنین که بشه اعلان ورود به پنل رو خاموش یا روشن کرد بصورت دلخواه
توی ربات بسیار آزار میده
سپاس بزرگوار

**Comment by X-Oracle** [comment]
بهتره که یک دکمه در قسمت تنظیمات ربات اضافه بشه و این قسمت رو تغییر بده .
