### ISSUE TITLE
ترکیب کانفیگ ها

### ISSUE THREAD

**Issue by alansec92** [MHSanaei/3x-ui#585]
سلام وقت بخیر
یک ایده داشتم بنظرم اگر بشه که برای مثال ما یک کانفیگ با پروتکل ws ایجاد کنیم یکی دیگه فقط tcp بعد کلاینت ها بین این دو مشترک باشند به نحوی که مثلا یک شخص از انواع پروتکل ها داشته باشه و زمانی که از هر کدوم استفاده کرد حجمش کم بشه به همون اندازه از بقیه موارد عالی میشه

**Comment by X-Oracle** [comment]
میتونه باشه ولی باید ساختار مثل مرزبان داشته باشه . یعنی :
ساخت اینباند و یوزر جدابشه .
بعد ui بیاد ویوزر های اضافه شده را به اینباند های مربوطه اضافه کنه .(هر یوزر یک ایمیلمشخص)
بعد حجم رو براساس ایمیل مرتب کنه و جمع بزنه و نمایش بده.

این ساختار با ساختاری که الان داریم زمین تا اسمون فرق میکنه طوری که میشه اسم پنل روهم عوض میشه کرد و اصلا با x-ui برابری نکنه .
احتمال اینکه ساخته بشه خیلی کمه .
