### ISSUE TITLE
add encryption methods to shadowsockes

### ISSUE THREAD

**Issue by vahiddastoori** [MHSanaei/3x-ui#586]
اگه ممکنه متد های دیگه رو هم به shadowsockes  اظافه کنید . چون برخی پروتکل ها مانند chacha20-ietf-poly1305 برای عبور از فیلترینگ قابل استفاده است . 

    "aes-256-cfb"
    "aes-128-cfb"
    "chacha20"
    "chacha20-ietf"
    "chacha20-poly1305" 
    "chacha20-ietf-poly1305"

**Comment by MHSanaei** [comment]
این متد ها روی مولتی یوزر کار نمیکنن
