### ISSUE TITLE
Can the connection be maintained while modifying the configuration

### ISSUE THREAD

**Issue by o02** [MHSanaei/3x-ui#587]
I use it to connect to the game. When user A runs out of traffic and the user expires, the game of user B will be disconnected. Can user B maintain network connection while user A's data is being updated?

**Comment by hamid-gh98** [comment]
I think [this commit](https://github.com/MHSanaei/3x-ui/commit/70f250dfe1e24249a4cc8102e3fef65959dfb15a) would fix your problem (it uses the xray api), and it will be available in the next release.
