### ISSUE TITLE
فعال کردن mux

### ISSUE THREAD

**Issue by omid-j-d** [MHSanaei/3x-ui#590]
سلام
میخواستم بدونم چجوری میتونم mux رو بر روی کانفیگ های خودم فعال کنم؟

**Comment by misagh72** [comment]
روی کلاینت باید انجام بدین روی سرور نمیشه

**Comment by omid-j-d** [comment]
آیا v2rayng پشتیبانی میکنه؟
چجوری میتونیم فعالش کنیم؟
چون من این ویژگی رو توی نکوری دیدم و اتصال سریع تری داشتم

**Comment by misagh72** [comment]
v2rayngفعلا ساپورت نمیکنه 
از nekobox استفاد کنید
