### ISSUE TITLE
ری استارت شدن سرور

### ISSUE THREAD

**Issue by saeidpour80** [MHSanaei/3x-ui#592]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام
من از سرور لینوکس با ورژن Ubuntu 22.04.2 استفاده میکنم و پنل ورژن 1.6.1 رو نصب کردم
یه مشکلی که بهش برخوردم اینه که از وقتی پنل رو نصب کردم سرور گاهی اوقات حدود 20 تا 30 ثانیه از دسترس خارج میشه و دیگه نمیتونم با ssh بهش متصل بشم و حتی پنل 3x-ui هم از دسترس خارج میشه
انگار که سرور ری استارت میشه با اینکه تعداد یوزرایی که من روی پنل دارم نهایتا 6 نفر هستند.
سخت افزار سرور من هم به این شکله :
CPU : 2 Core
Memory : 2048 MB
Disks : 40960 Mbyte

ممنون میشم اگر راهنماییم کنید

### Version of 3x-ui

<details>

```console
1.6.1
```

</details>

### x-ui log reports or xray log

<details>

```console
Jun 11 18:47:19 ubuntu22 systemd[1]: Started x-ui Service.
Jun 11 18:47:19 ubuntu22 x-ui[836]: 2023/06/11 15:17:19 x-ui 1.6.1
Jun 11 18:47:19 ubuntu22 x-ui[836]: 2023/06/11 15:17:19 INFO - web server run http on [::]:1221
Jun 11 19:12:31 ubuntu22 systemd[1]: Stopping x-ui Service...
Jun 11 19:12:31 ubuntu22 systemd[1]: x-ui.service: Killing process 905 (xray-linux-amd6) with signal SIGKILL.
Jun 11 19:12:31 ubuntu22 systemd[1]: x-ui.service: Deactivated successfully.
Jun 11 19:12:31 ubuntu22 systemd[1]: Stopped x-ui Service.
Jun 11 19:12:31 ubuntu22 systemd[1]: x-ui.service: Consumed 56.380s CPU time.
-- Boot 7f46fb2f9950493e95639da30a926edc --

Jun 12 18:40:22 ubuntu22 x-ui[836]: 2023/06/12 18:40:22 INFO - web server run http on [::]:6116
Jun 12 18:41:38 ubuntu22 x-ui[836]: 2023/06/12 18:41:38 WARNING - stop server err: multierr: close tcp [::]:6116: use of closed network connection |
```

</details>

**Comment by MHSanaei** [comment]
نسخه ۱.۶.۰ رو نصب و تست کنبد
