### ISSUE TITLE
Bug in ip limit and ip log

### ISSUE THREAD

**Issue by clockedzero** [MHSanaei/3x-ui#593]
قسمت ایجاد محدودیت ip limit برای client ساخته شده به طور کل عمل نمیکنه و با اینکه وقتی محدودیت روی عدد 1 قرار میگیره، باز هم بیش از یک آی پی مستقل بصورت همزمان میتوانند بدون مشکل متصل شوند و در عین حال حتی قسمت ip log هم فقط یک آی پی را نمایش میدهد در صورتی که بیش از یک آیپی مستقل به client ساخته شده متصل هستند.

update:
**مورد گزارش شده کاملا بصورت اتصال مستقیم تست شده نه با تانل یا
 cdn**

حتی 10 ثانیه بعد از اتصال کاربر دوم به بعد محدودیتی روی کلاینت ایجاد نمیشه، از طرفی **لاگ آی پی هم فقط برای یک آیپی ثبت میشه و اصلا نمیشه متوجه شد چند اتصال همزمان به آن کلاینت وجود دارد، در ورژن های قبل از 1.6 با اینکه قابلیت عمل نمیکرد اما لاگ هر چند تا آی پی متصل شده به کلاینت نمایش داده میشد اما در ورژن جدید فقط یک ای پی ثبت میشه**.
اگر امکان ایجاد محدودیت نیست در صورت امکان گزینه جایگزین میتونه این باشه که در صورت اتصال همزمان تعداد کاربر بیش از حد تعیین شده، اون کلاینت کامل به حال disable تغییر کنه و نیاز به enable کردن دستی داشته باشه یا با تعیین یک زمان،  پس از آن مجدد فعال شود.

### Version of 3x-ui

<1.6.1>

**Comment by mmdkevin** [comment]
لیمیت آیپی برا تانل کار نمیده

**Comment by SajjadSedaqat** [comment]
واسه cdn هم متاسفانه کار نمی کنه

**Comment by X-Oracle** [comment]
> لیمیت آیپی برا تانل کار نمیده

خب معلومه کار نمیکنه .  فقط میونم بگم که هرنفر که از سرور تانل وصل بشه به خارج فقط از یک ای پی که اونم مال سرورتون هست میاد به سمت سرور خارج . پس ای پی لیمیت معنی نداره.

راهکار داره که بچه ها بهتون میتونن بگن

> واسه cdn هم متاسفانه کار نمی کنه

واسه Cdn هم همینه . داره از ای پی کلاد میاد که تکه

**Comment by clockedzero** [comment]
**مورد گزارش شده کاملا بصورت اتصال مستقیم تست شده نه با تانل یا cdn**
حتی بعد از 10 ثانیه از اتصال کاربر دوم به بعد محدودیتی روی کلاینت ایجاد نمیشه، از طرفی لاگ آی پی هم فقط برای یک آیپی ثبت میشه و اصلا نمیشه متوجه شد چند اتصال همزمان به آن کلاینت وجود دارد.
اگر امکان ایجاد محدودیت نیست در صورت امکان گزینه جایگزین میتونه این باشه که در صورت اتصال همزمان تعداد کاربر بیش از حد تعیین شده، اون کلاینت کامل به حال disable تغییر کنه و نیاز به enable کردن دستی داشته باشه یا با تعیین یک زمان بصورت دستی،  پس از آن مجدد فعال شود.

**Comment by X-Oracle** [comment]
> **مورد گزارش شده کاملا بصورت اتصال مستقیم تست شده نه با تانل یا cdn** حتی 10 ثانیه بعد از اتصال کاربر دوم به بعد محدودیتی روی کلاینت ایجاد نمیشه، از طرفی **لاگ آی پی هم فقط برای یک آیپی ثبت میشه و اصلا نمیشه متوجه شد چند اتصال همزمان به آن کلاینت وجود دارد**. اگر امکان ایجاد محدودیت نیست در صورت امکان گزینه جایگزین میتونه این باشه که در صورت اتصال همزمان تعداد کاربر بیش از حد تعیین شده، اون کلاینت کامل به حال disable تغییر کنه و نیاز به enable کردن دستی داشته باشه یا با تعیین یک زمان، پس از آن مجدد فعال شود.

اگر پشت nginx باشه بازم قابلیت به هیچ دردی نمیخوره . 

متاسفانه xray قابلیت شناسایی چند تا کاربر رو نداره و فقط اجازه میده که اگر uuid شخص با uuid سرور برابری کرد وصل بشه .

اگر بخواهید فقط از xray کمک بگیرید یک راهش اینه که لیست ای پی ها ثبت بشه و در بازه زمانی کوچیکه چک بشه که چند تا آی پی مختلف لوگ شده . این کار سی پی یو بالایی میخواد مخصوصا برای یوزر های بالا. در ۱.۸.۱ به گفته سازنده پیاده شده . میتونید خودتون در ۱.۸.۱ بینید که یکدفعه مصرف منابع به ۱۰۰ درصد میرسه و همه یوزرا قطع میشن .و پنل دوباره ری استارت میشه .

چاره اینه که مکانیزم بهتری باید بیاد یا اینکه فراموشش کنید .

اگر جایی دیدید که این کار رو انجام میده و بدون اینکه مصرف منابع رو به ۱۰۰ ببره کار بکنه و اوپن سورس هست میتونید اینجا تگ کنید که سازنده الگوریتمشو اگر دوست داشت در x-ui پیاده کنه

**Comment by clockedzero** [comment]
> > **مورد گزارش شده کاملا بصورت اتصال مستقیم تست شده نه با تانل یا cdn** حتی 10 ثانیه بعد از اتصال کاربر دوم به بعد محدودیتی روی کلاینت ایجاد نمیشه، از طرفی **لاگ آی پی هم فقط برای یک آیپی ثبت میشه و اصلا نمیشه متوجه شد چند اتصال همزمان به آن کلاینت وجود دارد**. اگر امکان ایجاد محدودیت نیست در صورت امکان گزینه جایگزین میتونه این باشه که در صورت اتصال همزمان تعداد کاربر بیش از حد تعیین شده، اون کلاینت کامل به حال disable تغییر کنه و نیاز به enable کردن دستی داشته باشه یا با تعیین یک زمان، پس از آن مجدد فعال شود.
> 
> اگر پشت nginx باشه بازم قابلیت به هیچ دردی نمیخوره .
> 
> متاسفانه xray قابلیت شناسایی چند تا کاربر رو نداره و فقط اجازه میده که اگر uuid شخص با uuid سرور برابری کرد وصل بشه .
> 
> اگر بخواهید فقط از xray کمک بگیرید یک راهش اینه که لیست ای پی ها ثبت بشه و در بازه زمانی کوچیکه چک بشه که چند تا آی پی مختلف لوگ شده . این کار سی پی یو بالایی میخواد مخصوصا برای یوزر های بالا. در ۱.۸.۱ به گفته سازنده پیاده شده . میتونید خودتون در ۱.۸.۱ بینید که یکدفعه مصرف منابع به ۱۰۰ درصد میرسه و همه یوزرا قطع میشن .و پنل دوباره ری استارت میشه .
> 
> چاره اینه که مکانیزم بهتری باید بیاد یا اینکه فراموشش کنید .
> 
> اگر جایی دیدید که این کار رو انجام میده و بدون اینکه مصرف منابع رو به ۱۰۰ ببره کار بکنه و اوپن سورس هست میتونید اینجا تگ کنید که سازنده الگوریتمشو اگر دوست داشت در x-ui پیاده کنه

**دوست عزیز لطفا اسپم نکنید**. بنده مشخصا عرض کردم بصورت کاملا مستقیم تست شده و این توضیحاتی هم که دادید کمکی نمیکنه و راهکار شما به هیچ عنوان کاربردی نمیباشد.
اگر موردی رو میخواین گزارش یا پیشنهاد کنید بهتره تاپیک جدید باز کنید و اونجا عنوان کنید.

**Comment by X-Oracle** [comment]
اسپم! تاپیک جدید!

شرمنده پرحرفی کردم. 
به طور خلاصه : این قابلیت یک چیز فانتزیه در x-ui

فعلا

**Comment by clockedzero** [comment]
> قسمت ایجاد محدودیت ip limit برای client ساخته شده به طور کل عمل نمیکنه و با اینکه وقتی محدودیت روی عدد 1 قرار میگیره، باز هم بیش از یک آی پی مستقل بصورت همزمان میتوانند بدون مشکل متصل شوند و در عین حال حتی قسمت ip log هم فقط یک آی پی را نمایش میدهد در صورتی که بیش از یک آیپی مستقل به client ساخته شده متصل هستند.
> 
> update: **مورد گزارش شده کاملا بصورت اتصال مستقیم تست شده نه با تانل یا cdn**
> 
> حتی 10 ثانیه بعد از اتصال کاربر دوم به بعد محدودیتی روی کلاینت ایجاد نمیشه، از طرفی **لاگ آی پی هم فقط برای یک آیپی ثبت میشه و اصلا نمیشه متوجه شد چند اتصال همزمان به آن کلاینت وجود دارد، در ورژن های قبل از 1.6 با اینکه قابلیت عمل نمیکرد اما لاگ هر چند تا آی پی متصل شده به کلاینت نمایش داده میشد اما در ورژن جدید فقط یک ای پی ثبت میشه**. اگر امکان ایجاد محدودیت نیست در صورت امکان گزینه جایگزین میتونه این باشه که در صورت اتصال همزمان تعداد کاربر بیش از حد تعیین شده، اون کلاینت کامل به حال disable تغییر کنه و نیاز به enable کردن دستی داشته باشه یا با تعیین یک زمان، پس از آن مجدد فعال شود.
> ### Version of 3x-ui
> 
> <1.6.1>

سلام مجدد
برنامه ای برای رفع مشکل ip limit در آپدیت بعدی دارید یا خیر؟
