### ISSUE TITLE
مشکل کاربران آیفون با کانفیگvmess

### ISSUE THREAD

**Issue by mmdkevin** [MHSanaei/3x-ui#596]
سلام کاربران آیفونی که دارم با کانفیگ vmess مشکل سرعت دارن ولی وقتی vless میدم مشکلشون حل میشه ، دوستان هم تست کنن ببینن همین مشکل رو دارن ؟ و اینجا اعلام کنن !
این مشکل رو همه سرور هام هستش! و نرم افزاری هم که استفاده میکنن NapsternetV و V2box هستش.

**Comment by X-Oracle** [comment]
اگر vmess + tls بزنید یعنی دوبار رمزنگاری کردید که مصرف cpu میبره بالا و سرعت میاد پایین

**Comment by mmdkevin** [comment]
> اگر vmess + tls بزنید یعنی دوبار رمزنگاری کردید که مصرف cpu میبره بالا و سرعت میاد پایین

اصلا پنل من https نیست که بخوام tls بزنم واینجوری کانفیگ نزدم ، مصرف cpu هم نرماله 
درضمن کاربران اندروید مشکلی ندارن 100 تا یوزر اندروید هیچ کدوم مشکل نداره 
مثلا یه دونه یوزر آیفونم مشکل داره

**Comment by X-Oracle** [comment]
البته x-ui از xray اصلی استفاده میکنه و خودش کاری درباره سرعت نمیتونه بکنه .

چندکار میتونید بکنید :

- تنظیمات کانفیگ را تغییر دهید
- در x-ui از نسخه های قدیمی تر xray استفاده کنید و نتیجه را مقایسه کنید .
- در ios از کلاینت های مختلف استفاده کنید و نتیجه مقایسه کنید (توجه کنید که چون vmess هست میتونید روی انواع کلاینت ها چه قدیم و جدید میتونید تست کنید )


در غیر این صورت باید مشکل را در https://github.com/XTLS/Xray-core/  مطرح کنید
