### ISSUE TITLE
غیرفعال شدن پنل بعد از انتقال دیتابیس یوزرها

### ISSUE THREAD

**Issue by Amirjm20** [MHSanaei/3x-ui#598]
**سلام خسته  نباشید**
وقتی میخوام دیتابیس یوزهای سرور قبلی رو به سرور جدید انتقال بدم  بعد از آپلود دیتابیس یوزرها پنل رستارت میشه و دیگه xray بالا نمیاد و ارور میده

**Comment by hamid-gh98** [comment]
درود، ارور رو چک کنید و ارسال کنید

**Comment by sinaturkk** [comment]
سلام این مشکلو من دارم  لطفا کمک کنید

**Comment by Aronablade** [comment]
> **سلام خسته نباشید**
> وقتی میخوام دیتابیس یوزهای سرور قبلی رو به سرور جدید انتقال بدم بعد از آپلود دیتابیس یوزرها پنل رستارت میشه و دیگه xray بالا نمیاد و ارور میده

دلیلش وجود تنظیمات متفاوت مثلا تنظیم فایل cer و key هست ، وقتی شما از پنل قبلی بک اپ میگیرید ، تنظیمات هم بک اپ میشه و با ریستور روی سرور جدید خود اسکریپت دنبال فایل cer و key در مسیرش میگرده و وقتی پیدا نمیکنه اررور میده . برای حل این مشکل دو راه دارید .

۱- فایلهای cer و key سرور قبلی رو عینا در مسیری که در سرور قبلی بودن در مسیر سرور جدید قرار بدید و رفرش کنید و پنل بالا میاد .

۲- قبل از بک اپ گرفتن از سرور اول ، تنظیمات فایلهای cer و key رو از قسمت پنل و قسمت subscribe بردارید ذخیره کنید ، بک اپ بگیرید و بعد دوباره برش گردونید و بعد بک اپ بدون تنظیم مسیر فایلها رو ریستور کنید
