### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by AerEbi** [MHSanaei/3x-ui#599]
سلام،
سنایی جان دستت درد نکنه بخاطر نصب با docker. من وقتی دستور استارت رو میزنم ایمیچش بیلد میشه ولی نمیدونم چطوری باید اجراش کنم تا x-ui خط فرمان بده.
ممنون میشم راهنمایی کنی

**Comment by hamid-gh98** [comment]
> من وقتی دستور استارت رو میزنم ایمیچش بیلد میشه ولی نمیدونم چطوری باید اجراش کنم

درود،
این لینک رو چک کنید. [intall via docker](https://github.com/MHSanaei/3x-ui#install-with-docker)

```sh
docker compose up -d
```

یا

```sh
docker run -itd \
   -e XRAY_VMESS_AEAD_FORCED=false \
   -v $PWD/db/:/etc/x-ui/ \
   -v $PWD/cert/:/root/cert/ \
   --network=host \
   --restart=unless-stopped \
   --name 3x-ui \
   ghcr.io/mhsanaei/3x-ui:latest
```

** اگر خودتون دستی بیلد کردین، به جای `ghcr.io/mhsanaei/3x-ui:latest` اسم تگ که گذاشتین بزارین **
