### ISSUE TITLE
تعریف یک کاربر برای چند کانفیگ

### ISSUE THREAD

**Issue by farshadl** [MHSanaei/3x-ui#600]
سلام. وقت به خیر
راهی هست که برای چند کانفیگ، یک کاربر را تعیین کنیم؟ 
مثلا من Vless+WS ساختم و reality و میخوام حجم مصرفی کاربر، مجموع این دو کانفیگ باشه (به عبارتی به یک کاربر دو کانفیگ بدم و حجم مصرفیش بشه مجموع هر دو کانفیگ).

**Comment by X-Oracle** [comment]
نداریم
