### ISSUE TITLE
گزارش مکرر ربات برای ادمین مبنی بر ورود ناموفق

### ISSUE THREAD

**Issue by farshadl** [MHSanaei/3x-ui#601]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

من دو هفته هست که ربات تلگرام شما را فعال کردم. برای admin توی تلگرام مرتب این پیام میاد که ورود ناموفق داشتم.
من یک عکس از نمونه پیام‌ها را در زیر گذاشتم:
![Screenshot 2023-06-14 112032](https://github.com/MHSanaei/3x-ui/assets/127679551/6b0ee6cd-c3c9-4df2-88c5-27413d9f1a20)

### Version of 3x-ui

<details>

```console
# 1.6.3
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by hamid-gh98** [comment]
درود،
برای رفع این مورد، وارد تنظیمات پنل بشین -> و در بخش `Panel URL Root Path` یه سری حروف و عدد رندوم وارد کنید. 
 **توجه کنید که حتما اول و اخرش رو `/` اسلش قرار بدین -> `/PATH/` **  

برای مثال: اگر `/test123ff/` قرار بدین
ادرس شما از `yourdomain.com:2053/panel`  به `yourdomain.com:2053/test123ff/panel` تغییر میکنه
