### ISSUE TITLE
[HELP] What is the default username and password ?

### ISSUE THREAD

**Issue by dgqyushen** [MHSanaei/3x-ui#611]
I started the project by docker, then I use 'docker logs 3x-ui', it shows 
"
2023/06/16 13:39:59 x-ui 1.6.1
2023/06/16 13:39:59 INFO - web server run http on [::]:2053 
"
it didn't show the default username and password

**Comment by hamid-gh98** [comment]
Hello, try these:
1. Try `admin` for both username and password.
2. Open the db file and check the password in `users` table.
3. Use this command to change the password inside Docker (remember to change the username and password):
  ```sh
  docker run -it --rm --entrypoint /usr/local/x-ui/x-ui 3x-ui setting -username "admin" -password "admin"
  docker restart 3x-ui --time 3
  ```

**Comment by amalcev** [comment]
Is it required to do through command line or I ca change the password in admin interface?
