### ISSUE TITLE
مديريت پهنای باند

### ISSUE THREAD

**Issue by Morghak963** [MHSanaei/3x-ui#613]
سلام مهندس
وقت بخیر 
اگر ممکن هست قابلیتی ارائه بشه که برای هر کلاینت بشه مقداری پهنای باند تنظیم کرد که بشه پهنای باند کلی سرور رو مدیریت کرد و از طرفی کاربرهای پر مصرف پهنای باند بقیه کاربران رو اشغال نکنند
مثلا وقتی این مقدار برای یک کلاینت روی یک مگابایت ست میشه دیگه سرعت دانلود و آپلود اون بیشتر از این مقدار نره
باتشکر

**Comment by mohsenrahmani145** [comment]
فکر کنم چنین چیزی امکان پذیر نباشه چون تا جایی که من میدونم پهنا باند روی پورت اعمال میشه در حال حاضر اکثر کلاینت ها رو یک پورت متصل میشن بخوای پهنا باند یه پورت کم کنی برای همه کلاینت ها کم میشه ولی بازم منتظر باشید ببینید جواب خودشون چیه
