### ISSUE TITLE
how to compile to have a package?

### ISSUE THREAD

**Issue by sasansi** [MHSanaei/3x-ui#614]
@MHSanaei 

Hi there

As you mentioned in your support group that there will be no release update. (and yet you update the repository but there is no release).

Can you tell us how to compile this repository to have a built package? (by this I mean the needed packages that should be preinstalled and configuration regard it).

Please share them all, because you added a lot since last release.

regards,

**Comment by MHSanaei** [comment]
just wait for it because update is not ready
