### ISSUE TITLE
Generating json file takes too long

### ISSUE THREAD

**Issue by AghaFarokh** [MHSanaei/3x-ui#616]
سلام
میدونید که وقتی یک اینباند جدید میسازیم پنل میره و یک فایل جیسون برای xray-core میسازه و توی این مدت xray متوقف میشه
حالا من یه مشکلی دارم اونم اینه که باتم اتوماتیک با API توی پنل اینباند میسازه و گاها پیش میاد درخواست ها زیاد باشن
و xray برای مدت زیادی دان میشه چون هر دفعه که اینباندی تغییر میکنه باید اون فایل جیسون آپدیت بشه و چون تعداد اینباند ها زیاده زمان زیادی می‌بره جنریت اون فایل جیسون
بنطرتون برای این مشکل چیکار میشه کرد ؟
همیشه سرویسم قطعه بخاطر این مشکل

**Comment by MHSanaei** [comment]
این مشکل حل شده فقط باید اپدیت بدیم که هنوز بعضی از تغییرات کامل نشدن و اماده نیستن

**Comment by AghaFarokh** [comment]
چقدر طول میکشه ؟ تایم میتونید اعلام کنید ؟
