### ISSUE TITLE
Subscription manual

### ISSUE THREAD

**Issue by M-Sadegh-M** [MHSanaei/3x-ui#620]
سلام 
آموزش و متودی برای راه اندازی این قابلیت پیدا نکردم.
دوستان کسی میتونه یک توضیح مختصری بده تا اگه ممکنه براش wiki تهیه بشه.

ممنون

**Comment by Habib1385** [comment]
سلام 
خسته نباشید 
از قسمت Subscription در تنظیمات ، Subscription را فعال کنید 
و در قسمت ایمیل اسم برای Subscription رو انتخاب کنید 
بعد از قسمت اطلاعات کانفیگ قابل مشاهده هست
