### ISSUE TITLE
مشکل در نشون ندادن کانفینگ ها

### ISSUE THREAD

**Issue by sardar-mahdi** [MHSanaei/3x-ui#622]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

گزارش یک مشکل از آپدیت از نسخه ای قدیمی به جدید

با سلام من من اولین بار که پنلی سنایی رو نصب کردم نسخه ای 1.3.3 بود چند ماه بود با این نسخه پنل کار کردم و کانفینگ های مختلفی هم روش  زدم شاید نزدیک 10 تا روش بعدش دیدم آپدیت های مختلفی دارهه اومدم آپدیت کردم به آخرین نسخه ای همون 1.6.1 بود آپدیت شد و مشکلی نداشت اما یه مشکل داشت من وقتی میخاستم داخل کانفینگ هام بیام اصلا نشون نمیده چند بار فیلتر رو خاموش روشن میکنم تا سه تا دونه کانفینگ رو نشون بده بقیه رو نشون نمیده
----------
بعدش اومد نسخه ای که پنل قبلی رو نصب کنم ارور 404 میده و مجبور الان با آخرین نسخه استفاده بکنم اما فقط سه تا کانفینگ میاره و بقیه رو نمیاره با این که من بیش از 10 تا کانفینگ ساختم اما بالا نمیاد
حتی کانفینگم میسازم دوباره نمیاره و همون ارور قبلی
دلیلشو کسی میدونه؟ و این که توضیح بدید چطور باید رفعش کنم ممنون میشم

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
این اتفاق در صورتی میفته که شما در نسخه های قدیمی شادوساکس داشته باشید در ورژنی که شادوساکس مولتی یوزر شد این مورد به وجود اومد که باید قبل اپدیت اون اینباند های شادوساکس رو حذف میکردید 
البته میتونه مورد دیگه ای هم باشه مثلا باگ دیتابیس

**Comment by mohi18217** [comment]
سلام من این مشکل رو تو ورژن 2 و 2.2 پیدا کردم بعد آپدیت. یکسری از اینباندهارو نشون نمیده کلا. یک سرور هم باید حتما فیلتر رو روشن کنم تا نشون بده باز همونم بعضی اینباند هارو نشون نمیده کلا و دلی در x-ui.db هست. لطفا راهنمایی کنید چطور حل میشه ممنون
