### ISSUE TITLE
Deprecated XTLS Flows.

### ISSUE THREAD

**Issue by hawshemi** [MHSanaei/3x-ui#623]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

_Thanks for the great panel._

But the Flows in the XTLS section for users are deprecated since xray v1.7.5. 
Now only `xtls-rprx-vision` and `xtls-rprx-vision-udp443` are supported and updated.
Please update the panel to use the latest flows for XTLS. other flows like `xtls-rprx-origin` and `xtls-rprx-direct` are deprecated and not secure.

![xtls](https://github.com/MHSanaei/3x-ui/assets/16742123/ff421239-12b5-409e-9b39-74551844fffe)

### Version of 3x-ui

<details>

```console
1.6.1
```

</details>

### x-ui log reports or xray log

<details>

```console
xtls-vision for XTLS
```

</details>

**Comment by MHSanaei** [comment]
you choose xtls security
xtls doesn't support vision and has been removed on xray v1.8.0+
if you want to use vision you can use
vless tcp tls
vless tcp reality
