### ISSUE TITLE
مشکل تماس تصویری واتس آپ

### ISSUE THREAD

**Issue by AkramiPro** [MHSanaei/3x-ui#624]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

من از کانفیگ ss استفاده میکنم . 
موقع ساخت کانفیگ TCP+UDP رو فعال میکنم
رمزنگاری هم 256 هست
سمت کلاینت هم UDP over TCP رو داخل برنامه NekoBox فعال کردم . با هر 2 حالت فعال و غیر فعال این گزینه تست کردم
با 2 تا گوشی یکسان تست کردم 
تماس تصویری کار نمیده 
سر این UDP یه باگی داره ss 
ولی با تروجان که تست میکنم اوکی هست و تماس تصویری اوکی هست 
ولی تروجان خیلی پینگ بالا داره و سرعت پایین تره نصبت ss . من میخوام حتما ss کار کنم
ممنون میشم راهنمایی کنید 
تشکر

### Version of 3x-ui

![image](https://github.com/MHSanaei/3x-ui/assets/54323929/410ada71-f556-4cc3-accf-5c47355ad942)

![image](https://github.com/MHSanaei/3x-ui/assets/54323929/f23c0dff-f5f5-4f03-9bc3-eaed2d507988)

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by AkramiPro** [comment]
help please

**Comment by shehnipoor** [comment]
snifing رو خاموش کن

**Comment by AkramiPro** [comment]
روی هسته sing-box تست کردم اوکی شد
 و snifing  هم true هست روی اون 
چی هست اصلا snifing  ؟
