### ISSUE TITLE
امکان تعریف یک کاربر برای اینباند های مختلف

### ISSUE THREAD

**Issue by PouryaDe** [MHSanaei/3x-ui#625]
سلام و وقت بخیر

یه امکان خیلی مهمی که نیازش خیلی احساس میشه اینه که میخوایم پروتکل های مختلفی برای یه یوزر بدیم
مثلا وب سوکت با ریلیتی بدیم ولی مشکلی که وجود داره اینه که حجم مصرفی کاربر جدا از هم حساب میشه و یکپارچه نیست

اگر امکانی باشه که مثلا با یه email مشخص که در بخش کلاینت تعریف میشه، بتونیم روی اینباند های مختلف با همون ایمیل بسازیم و برای مثال کاربر چه از اینباند وب سوکت استفاده کنه و چه از ریلیتی از حجم کلی که براش تعریف شده کسر و محاسبه بشه

خیلی ممنون بابت تمام زحماتی که میکشید.

**Comment by saeidit1** [comment]
وقت بخیر
بله این امکانی که در پنل نیازه . اگر اضافه بشه خیلی از مشکلات حل میشه . مخصوصا برای اینکه کانفیگ هر اپراتور متفاوت هست

**Comment by internetfreedomir** [comment]
با سلام و تشکر از شما که به دور زدن فیلترینگ ناعادلانه کمک کردید 

الان یکی از قابلیت هایی که واقعا نیازه اینه که بشه به کاربر همزمان ۲ کانفیگ یعنی مستقیم (reality) و با cdn داد ولی در پنل شما باید کانفیگ ها رو جدا بسازیم و حجم جدا تعریف کنیم 
ممنون میشم این قابلیت رو اضافه کنید

**Comment by Aronablade** [comment]
> وقت بخیر
> بله این امکانی که در پنل نیازه . اگر اضافه بشه خیلی از مشکلات حل میشه . مخصوصا برای اینکه کانفیگ هر اپراتور متفاوت هست



> با سلام و تشکر از شما که به دور زدن فیلترینگ ناعادلانه کمک کردید
> 
> الان یکی از قابلیت هایی که واقعا نیازه اینه که بشه به کاربر همزمان ۲ کانفیگ یعنی مستقیم (reality) و با cdn داد ولی در پنل شما باید کانفیگ ها رو جدا بسازیم و حجم جدا تعریف کنیم ممنون میشم این قابلیت رو اضافه کنید

سلام ، ببینید شما میتونید چند اینباند بسازید و برای یک کاربر تو هر کدوم یک کلاینت درست کنید تنظیمات رو یکی کنید و تنها کارب که باید انجام بدید اینه که susbcribe id و UID همه اونها رو یکی کنید ، به عنوان مثال UID و Sub id که تو inbound 1 براش گذاشتید رو کپی کنید و تو کلاینتهای اینباندهای دیگه بذارید ، اینجوری طرف با زدن سابسکرایب لینک تمام کانکشنها براش اضافه میشه ، و در عین حال اگه تک کاربره تنظیم کرده باشید میتونه همزمان فقط از یکی از کانفیگها استفاده کنه و عملا همون چیزی میشه که شما مدنظرتون هست 

یادتون باشه جیزی که اتصال رو محدود میکنه UID هست و وقتی شما برای یک UID محدودیت میذارید این UID هست که چک میشه و اگه قبلا وصل شده باشه دیگه اجازه اتصال دیگه نمیده .

**Comment by internetfreedomir** [comment]
> > وقت بخیر
> > بله این امکانی که در پنل نیازه . اگر اضافه بشه خیلی از مشکلات حل میشه . مخصوصا برای اینکه کانفیگ هر اپراتور متفاوت هست
> 
> > با سلام و تشکر از شما که به دور زدن فیلترینگ ناعادلانه کمک کردید
> > الان یکی از قابلیت هایی که واقعا نیازه اینه که بشه به کاربر همزمان ۲ کانفیگ یعنی مستقیم (reality) و با cdn داد ولی در پنل شما باید کانفیگ ها رو جدا بسازیم و حجم جدا تعریف کنیم ممنون میشم این قابلیت رو اضافه کنید
> 
> سلام ، ببینید شما میتونید چند اینباند بسازید و برای یک کاربر تو هر کدوم یک کلاینت درست کنید تنظیمات رو یکی کنید و تنها کارب که باید انجام بدید اینه که susbcribe id و UID همه اونها رو یکی کنید ، به عنوان مثال UID و Sub id که تو inbound 1 براش گذاشتید رو کپی کنید و تو کلاینتهای اینباندهای دیگه بذارید ، اینجوری طرف با زدن سابسکرایب لینک تمام کانکشنها براش اضافه میشه ، و در عین حال اگه تک کاربره تنظیم کرده باشید میتونه همزمان فقط از یکی از کانفیگها استفاده کنه و عملا همون چیزی میشه که شما مدنظرتون هست
> 
> یادتون باشه جیزی که اتصال رو محدود میکنه UID هست و وقتی شما برای یک UID محدودیت میذارید این UID هست که چک میشه و اگه قبلا وصل شده باشه دیگه اجازه اتصال دیگه نمیده .

نمیشه حجم رو با این روش تنظیم کرد ، من می خوام مثلا ۵۰ گیگ بدم هم reality باشه و هم cdn و بتونه از هر کدوم که بخواد استفاده کنه پس اگر ۲۵ گیگ reality و ۲۵ گیگ cdn بدم هم نمیشه چون شاید ایرانسل هست و می خواد فقط reality استفاده کنه !

این روشی که شما گفتی برای لینک سابسکرایب خوبه ولی مشکل اصلی حجمه که باید تغییر ساختاری در 3x-ui اعمال بشه به طوری که حجم بر اساس id یا ایمیل باشه !
