### ISSUE TITLE
مشکل در ربات تلگرام

### ISSUE THREAD

**Issue by amirsheikhan** [MHSanaei/3x-ui#626]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![image](https://github.com/MHSanaei/3x-ui/assets/130313835/659d343e-9af1-4d07-a74f-80bbc52a38d2)
سلام وقت بخیر 
طبق عکس بالا مدام پیام ورود میاد و اصلا نمیشه با ربات کار کرد 
در هر ثانیه یک بار پیام ورود میاد 
دقیقه ای  60 بار مشکل چیه ؟

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Habib1385** [comment]
سلام 
در اپدیت بعدی این مشکل رفع شده

**Comment by MHSanaei** [comment]
این مشکل از سمت ما نیست که بخواد حل بشه، این دوستمون از بات داره استفاده میکنه اونم هربار لاگین میکنه به سرور ، من اپشن اینکه پیغام نده داخل بات رو اضافه کردم که بتونین خاموش کنید
