### ISSUE TITLE
هسته Sing-Box

### ISSUE THREAD

**Issue by Shellgate** [MHSanaei/3x-ui#629]
سلام و عرض ادب و خسته نباشید

خواهشمندیم هسته singbox رو همانند پنل hidify به پنل اضافه بشه و امکان سوییچ بین هسته ها هم با گزاشتن‌ گزینه ای فراهم شه

**Comment by misagh72** [comment]
نمیشه

**Comment by AkramiPro** [comment]
دقیقا خیلی نیاز هست . sing-box پرفرمنس بهتری داره
