### ISSUE TITLE
option - reset client traffic per month

### ISSUE THREAD

**Issue by okoklai** [MHSanaei/3x-ui#630]
I creat a clinet add 100G traffic,The account  expire days 365D,I wanna automatic reset the traffic every 31D for the client .for now I need login the panel and chick the reset menu.

**Comment by neerro** [comment]
Nice option. I would be see that in the future updates.

**Comment by RNDpacman** [comment]
This option would be much needed. Maybe until it is implemented, it is possible to reset traffic counter via api?
