### ISSUE TITLE
حذف گزارش لاگین

### ISSUE THREAD

**Issue by Mhmansouri** [MHSanaei/3x-ui#633]
سلام، خسته نباشید؛
لطفا گزینه‌ای برای ربات قرار بدید تا گزارش لاگین ارسال نکنه و یا اختیاری باشه، چون با ربات ویزویز که هر دقیقه کرون جاب ست کرده تداخل داره...
ممنون.

**Comment by MHSanaei** [comment]
اضافه شده

**Comment by Mhmansouri** [comment]
از چه طریقی میشه لغو کرد؟؟؟

**Comment by MHSanaei** [comment]
هروقت اپدیت بعدی رو بدم
