### ISSUE TITLE
ذخیره تنظیمات

### ISSUE THREAD

**Issue by roohino** [MHSanaei/3x-ui#642]
پنل را تازه نصب کردم ولی نمیتونم در بخش تنظیمات چیزی را تغییر بدم. مدام ارور میاد:

"Every change made here needs to be saved. Please restart the panel to apply changes."
روی دکمه ریستارت پنل هم که میزنم اتفاقی نمی افته. باز هم همان مشکل پیش میاد

**Comment by misagh72** [comment]
این که ارور نیست دوست عزیز این فقط یک یاد اوری هست

**Comment by roohino** [comment]
مشکل این بود که ظاهرا تنظیمات اجرا شده را چک میکنه در صورتی که کدهایی که در بخش تنظیمات وارد میشه مشکل داشته باشه اجازه ذخیره نمیده
پنل خفنیه
