### ISSUE TITLE
Is the current version not supporting single-port multi-user usage anymore

### ISSUE THREAD

**Issue by xx-iuxx** [MHSanaei/3x-ui#645]
I haven't seen any option to add more users on the same port.
![Snipaste_2023-06-25_10-57-25](https://github.com/MHSanaei/3x-ui/assets/102848205/f0824a8c-ea5d-4f8b-b6cb-52c1e290a493)

**Comment by Shellgate** [comment]
Your anser is
![Uploading Screenshot_۲۰۲۳-۰۶-۲۵-۰۶-۳۳-۲۴-۵۳۴_com.android.chrome-edit.jpg…]()

**Comment by Shellgate** [comment]
![Uploading IMG_۲۰۲۳۰۶۲۵_۰۶۳۵۴۴.jpg…]()

**Comment by Shellgate** [comment]
![IMG_۲۰۲۳۰۶۲۵_۰۶۳۵۴۴](https://github.com/MHSanaei/3x-ui/assets/128194280/19d94ce9-e95c-44d7-bef3-c912c234d5f6)

**Comment by Shellgate** [comment]
😂😂😂😊😊🤣

**Comment by xx-iuxx** [comment]
> 😂😂😂😊😊🤣

I asked a kinda dumb question. Thanks for your help.
