### ISSUE TITLE
Accept proxy protocol for h2 & gRPC

### ISSUE THREAD

**Issue by arsham6ix** [MHSanaei/3x-ui#646]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

درود خدمت شما ، ممنون بابت اپدیت جدید ، قبلا درخواست accept proxy protocol رو داده بودم که انجام دادید و گفتید اما تستش نمیکنم. الان و من و دوستان تست کردیم نسخه جدید پنل رو accept proxy protocol  کار نمیکرد برای gRPC و h2 ، اما برای tcp راحت جواب گو بود ، میخواستم بگم که پنل sing web از این قابلیت به خوبی پشتیبانی میکنه ، اگه وقت ازادی داشتید ممنون میشم سورس اون رو چک کنید و تغییرات مورد نیاز رو اعمال کنید که پنل تکمیل تر بشه. با تشکر

https://github.com/sing-web/x-ui

### Version of 3x-ui

<details>

```console
v1.7.0
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by mohsenrahmani145** [comment]
@arsham6ix یه توضیح میدی accept proxy protocol واسه چیه؟

**Comment by mohsenrahmani145** [comment]
اها فهمیدم داداش
یه سوال دیگه شما اطلاع داری بعضی کانفیگ ها مثلا روی ws میان از sni های وب سایت های معروف میزنن مثلا skyroom.online میدونی چجوری اینکارو میکنن ؟ @arsham6ix

**Comment by MHSanaei** [comment]
چیزی که شما گفتید اضافه کردم اگر شک دارید میتونید کانفیگ رو از صفحه اول ببینید
اینکه کار نمیکنه یعنی کدی که دادید مشکل داره و شما اشتباه کردید
