### ISSUE TITLE
api to get a UUID (or email) link

### ISSUE THREAD

**Issue by MG-Token** [MHSanaei/3x-ui#647]
hi
any api to get a UUID (or email) vless / vmess / ss link?
like export link in panel but we need in api 
for example: 
PostAsync($"{host}:{port}/panel/inbound/getClientlink/{email}", "");
or
PostAsync($"{host}:{port}/panel/inbound/getClientlink/{UUID}", "");
its return user link of vless / vmess / ss or encrypted link in Base32 or base64 (for more secure Base32 or base128)

**Comment by X-Oracle** [comment]
Right now it is generated in client panel

**Comment by MG-Token** [comment]
i kbow its generated at js code at back end its not helpful result of him is not a soure its code we need api

**Comment by KasperZzz** [comment]
Where api url_client?
