### ISSUE TITLE
اضافه کردن Telegram Id

### ISSUE THREAD

**Issue by MD-97** [MHSanaei/3x-ui#656]
لطفا اگه میشه قسمت تلگرام ایدی برای کاربر ها اضافه کنید. 
داخل database نگاه کردم فیلدش بود ولی ویزاردی نمیشه اضافه کرد.

![Screenshot 2023-06-25 223858](https://github.com/MHSanaei/3x-ui/assets/45558971/64ad4670-0faa-4f67-aad7-49d1820d139e)

**Comment by MHSanaei** [comment]
وقتی ربات داخل تنظیمات فعال بشه فیلد تلگرام هم اینجا نشون داده میشه

**Comment by MHSanaei** [comment]
وقتی ربات داخل تنظیمات فعال بشه فیلد تلگرام هم اینجا نشون داده میشه
