### ISSUE TITLE
مشکل اتصال همزمان ۲ کاربر با محدودیت ۱ ای پی

### ISSUE THREAD

**Issue by MD-97** [MHSanaei/3x-ui#658]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [x] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

من برای یک کاربر محدودیت اتصال یک ای پی گذاشتم ولی تست کردم یا دو اینترنت متفاوت ولی همزمان متصل شدن و مشکلی هم نداشتن.

![Screenshot_20230626_143310_Chrome](https://github.com/MHSanaei/3x-ui/assets/45558971/03b2cd08-a4f4-44a3-ac03-494253d3229f)

### Version of 3x-ui

اخرین ورژن

### x-ui log reports or xray log

...

**Comment by Hasan-Torabi** [comment]
This problem happened to me too. I have also installed fail2ban.

**Comment by arian2240** [comment]
> ### Welcome
> 
>     * [x]  Yes, I'm using the latest major release. Only such installations are supported.
> 
>     * [x]  Yes, I'm using the supported system. Only such systems are supported.
> 
>     * [x]  Yes, I have read all WIKI document,nothing can help me in my problem.
> 
>     * [x]  Yes, I've searched similar issues on GitHub and didn't find any.
> 
>     * [x]  Yes, I've included all information below (version, config, log, etc).
> 
> 
> ### Description of the problem,screencshot would be good
> 
> من برای یک کاربر محدودیت اتصال یک ای پی گذاشتم ولی تست کردم یا دو اینترنت متفاوت ولی همزمان متصل شدن و مشکلی هم نداشتن.
> 
> ![Screenshot_20230626_143310_Chrome](https://user-images.githubusercontent.com/45558971/248780395-03b2cd08-a4f4-44a3-ac03-494253d3229f.jpg)
> ### Version of 3x-ui
> 
> اخرین ورژن
> ### x-ui log reports or xray log
> 
> ...

Yes me too

**Comment by khzaei12001200** [comment]
بدلیل تونل کردن این اتفاق می افته

**Comment by Hasan-Torabi** [comment]
من از تونل استفاده نکرده‌ام و این مشکل وجود دارد.

**Comment by soroushsafaar** [comment]
راهکاری هم برای تونل وجود داره ؟

**Comment by aliChavoshi** [comment]
من هم الان این مشکل را دارم و هر  user  میتواند این کانفیگ را به  n  نفر  share  کند

**Comment by aliChavoshi** [comment]
برای حل این مشکل باید چیکار کنیم ؟

**Comment by aliChavoshi** [comment]
> بدلیل تونل کردن این اتفاق می افته

آیا راه حلی پیدا کردین ؟

**Comment by Mojtabaaba** [comment]
دوستان وقتی شما عدد ۱ رو میزارید برای محدودیت آی پی وقتی دو تا نمایش میده یکی از اونا بن شده و یکیش متصل هست

**Comment by aliChavoshi** [comment]
این داداش زمانی که تانل زدی کار نمیکنه . اگر مستقیم تانل زده باشی اوکی هست ولی از سرور ایران استفاده کنی کار نمیکنه که طبیعی هم هست که کار نکنه

**Comment by husen-hn** [comment]
> دوستان وقتی شما عدد ۱ رو میزارید برای محدودیت آی پی وقتی دو تا نمایش میده یکی از اونا بن شده و یکیش متصل هست

هردو آی پی وصل هستن و هردو کاملا بدون هیچ مشکل از فیلترشکن استفاده میکنن و اتصال مستقیم است و تانل هم نیست

**Comment by iamirhossein01** [comment]
سلام و وقت بخیر ، مشکل محدودیت ایپی رو حل کردید؟ اگر اره مونون میشم راهکار رو درمیان بذارید.

**Comment by iamirhossein01** [comment]
> ### Welcome
> * [x]  Yes, I'm using the latest major release. Only such installations are supported.
> * [x]  Yes, I'm using the supported system. Only such systems are supported.
> * [x]  Yes, I have read all WIKI document,nothing can help me in my problem.
> * [x]  Yes, I've searched similar issues on GitHub and didn't find any.
> * [x]  Yes, I've included all information below (version, config, log, etc).
> 
> ### Description of the problem,screencshot would be good
> من برای یک کاربر محدودیت اتصال یک ای پی گذاشتم ولی تست کردم یا دو اینترنت متفاوت ولی همزمان متصل شدن و مشکلی هم نداشتن.
> 
> ![Screenshot_20230626_143310_Chrome](https://user-images.githubusercontent.com/45558971/248780395-03b2cd08-a4f4-44a3-ac03-494253d3229f.jpg)
> 
> ### Version of 3x-ui
> اخرین ورژن
> 
> ### x-ui log reports or xray log
> ...

سلام و وقت بخیر ، مشکل محدودیت ایپی رو حل کردید؟ اگر اره مونون میشم راهکار رو درمیان بذارید.
