### ISSUE TITLE
Traffic Limit

### ISSUE THREAD

**Issue by ParsDev** [MHSanaei/3x-ui#662]
سلام موردی که من جایی ندیدم امکان لیمیت پهنای باند برای هر سرویس هست
آیا چنین امکانی میتونید اضافه کنید ؟
چه بصورت inbound traffic limit یا client traffic limit

**Comment by mmsh1370** [comment]
پنل هایی که ازهسته
 XrayR
 استفاده میکنن قابلیت کنترل پهنای باند رو دارن مثل

**Comment by mmsh1370** [comment]
پنل هایی که ازهسته
XrayR
https://github.com/XrayR-project/XrayR
استفاده میکنن قابلیت کنترل پهنای باند رو دارن مثل 
v2board   xmpluse  sspanel
تا اونجای که من خبر دارم فقط وی تو برد برای استفاده تجاری رایگانه که ویلس وشتیبانی نمیکنه
 و ایکس ام پلاس ۶۰ تتر    و 
 اس اس پنل ۱۰۰ تتر هزینه داره
