### ISSUE TITLE
User Enabling Problem after updating from 1.6.1 to 1.7.0

### ISSUE THREAD

**Issue by H-Ir** [MHSanaei/3x-ui#664]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi. I upgraded my version from 1.6.1 to 1.7.0, also I had 40 users via vless vision. I had not any isssues with v1.6.1 but after updating when I enable a disabled user, it don't work uless I restart the panel. when the user is disabled i see error "Unable to parse TLS packet header " in NapsternetV client and when I enable the user i see error "Connection Closed". after i restart the panel the connection is ok without any error! 
another case: when the users are enable and connection is ok, if i disable any of them, the user cannot connect and when i re-enable it, the client cannot connect again! thus, disabling is ok but enabling has problem!
please solve the problem.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by m484r** [comment]
بنده هم در این اپدیت این مشکل رو دارم
وقتی کاربران داخل ربات افزایش حجم میزنن
لینک قطع میشه و باید یکبار دکمه رو غیرفعال و فعال کرد تا دوباره وصل بشه
