### ISSUE TITLE
issue for sharing link to iphone devices 

### ISSUE THREAD

**Issue by danialsbr** [MHSanaei/3x-ui#667]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Links not working for import configuration to iphone by fair vpn or other apps

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by teal33t** [comment]
I still get error while import the link into Fair VPN for iOS, is this issue resolved?
