### ISSUE TITLE
مشکل کار نکردن Direct Country Configs روی سرور واسطه ایران

### ISSUE THREAD

**Issue by hosein-moayedi** [MHSanaei/3x-ui#668]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

پنل x-ui رو اومدم هم روی سرور ایران و هم روی سرور خارج ستاپ کردم.
کانفیگ اصلی رو روی سرور خارج ساختم و روی سرور ایران از dokodemo-door برای فروارد کردن ترافیک به سرور خارج استفاده کردم.

این گزینه ها رو هم فقط روی سرور ایران روشن کردم ولی همچنان کار نمیکنه!

<img width="1029" alt="Screenshot 2023-06-27 at 11 22 40 PM" src="https://github.com/MHSanaei/3x-ui/assets/38086978/4048ae2d-8b56-4c97-ad5f-cb5e4e2808ff">

اصلا کار نمیکنه!!
مثلا سایت tamin.ir نمیاد

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by hosein-moayedi** [comment]
@MHSanaei
شما فرموده بودین که این آپشن برای تانل کردن سرور ایران و خارج و استفاده از x-ui روی هر دو و روشن کردن این آپشن فقط روی سرور ایران طراحی شده. 
اما من هم روی سرور ایران روشن کردم و تست کردم و هم رو هر دو روشن کردم ولی اصلا کار نمیکنه!
میشه یه راهنمایی بفرمایید

**Comment by PillarsDev** [comment]
منم دقیقا همین مشکل رو دارم
ممنون میشم یه خورده توضیح بدین در این مورد
