### ISSUE TITLE
ARM based docker image

### ISSUE THREAD

**Issue by MR-Os1** [MHSanaei/3x-ui#669]
Hi
Thanks for wonderful work.
Please add docker image for ARM based processors.

**Comment by mmdjvdad** [comment]
available for arm64. Follow the steps

**Comment by leic4u** [comment]
> available for arm64. Follow the steps

@MHSanaei @mmdjvdad What are the steps? I didn't find any official guide to pull ARM64 docker images.

**Comment by mmdjvdad** [comment]
I don't know where is the image but the git command gets the compose file. Just fo the instructions here👇

https://github.com/MHSanaei/3x-ui#install-with-docker

**Comment by leic4u** [comment]
> I don't know where is the image but the git command gets the compose file. Just fo the instructions here
> 
> https://github.com/MHSanaei/3x-ui#install-with-docker

I followed these stpes and the container could not work. It seems that the image in [ghcr.io/mhsanaei/3x-ui:latest](https://ghcr.io/mhsanaei/3x-ui:latest) is only prepared for AMD64.

**Comment by mmdjvdad** [comment]
Previously I installed it on arm64 but, tried ten times and worked once

**Comment by leic4u** [comment]
> Previously I installed it on arm64 but, tried ten times and worked once

It's not a good news for me😂
