### ISSUE TITLE
Migration from niduka

### ISSUE THREAD

**Issue by pouriasharifzad** [MHSanaei/3x-ui#670]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام
وقتی دیتابیس خودم رو از نیدوکا روی سنایی ری استور میکنم اولش درست کار میکنه ولی  بعد از چند دقیقه اینباندی که از نیدوکا ری استور شده نشون داده نمیشه و قطع میشه

### Version of 3x-ui

<details>

```console
# 1.6.1
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
بعد از اینکه دیتابیس جابجا کردید یکبار نسخه اخر رو نصب کنید که مشکلات دیتابیس حل شه

**Comment by pouriasharifzad** [comment]
یعنی دوباره سنایی رو ری اینستال کنم یا آپدیت کنم؟

**Comment by pouriasharifzad** [comment]
> بعد از اینکه دیتابیس جابجا کردید یکبار نسخه اخر رو نصب کنید که مشکلات دیتابیس حل شه

یعنی دوباره سنایی رو ری اینستال کنم یا آپدیت کنم؟
