### ISSUE TITLE
فاقد حجم بودن کاربر اضافه شده از طریق API

### ISSUE THREAD

**Issue by thehexmor** [MHSanaei/3x-ui#671]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

با عرض سلام
متاسفانه بعضی از کاربر ها بدون فیلد حجم اضافه میشن این کاربر ها از طریق API اضافه میشن و حتی از طریق API هم نمیشه حجمشون رو دریافت کرد
لازم به ذکر هست مشکل از API نیست تا ورژن قبلی پنل درست کار میکرد و درحال حاضر هم از هر 100 یوزر 5 تا اینطوری میسازه

### Version of 3x-ui

<details>

```console
1.7
```

</details>

### x-ui log reports or xray log

<details>

```console
اطلاعات مفیدی در لاگ نیست

```

</details>

**Comment by thehexmor** [comment]
![image](https://github.com/MHSanaei/3x-ui/assets/47923870/ac18e4a8-5608-4bb8-b132-9ad690860bcf)

**Comment by thehexmor** [comment]
![image](https://github.com/MHSanaei/3x-ui/assets/47923870/091d1594-2ca7-4117-ad79-ddfcbffb1be4)

همینطور که میبینید کاربر فیلد حجم نداره

**Comment by MHSanaei** [comment]
وقتی یک کلاینت اضافه میکنید به تمام فیلد های ان دقت کنید از جمله ایمیل ، uuid

**Comment by thehexmor** [comment]
> وقتی یک کلاینت اضافه میکنید به تمام فیلد های ان دقت کنید از جمله ایمیل ، uuid

تمام فیلد ها از طریق API درست اضافه میشه همونطور که گفتم این مشکل توی اپدیت جدید به وجود اومده و اینکه برای تمام یوزر ها نیست بلکه صرفا بعضی از یوزر ها این مشکل رو دارن که همون یوزر ها وقتی مجدد توسط API اضافه بشن مشکل حل میشه

**Comment by MHSanaei** [comment]
کلاینت شما uuid نداره مشکل از سمت شماست نه پنل
