### ISSUE TITLE
Panel state and X-ray state not running every 10 min

### ISSUE THREAD

**Issue by rezamh79** [MHSanaei/3x-ui#672]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi 
Every 10 minutes panel state and X-ray state  changes to not running state and I have to manually restart the x-ui
In the log file I have found this in the log file
Stop server err: multierr:context canceled | close tcp [::]:8080: use of closed network connection 
And a lots of logs which says wrong username and password 
I get a lot of this as well 
Database is locked 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
You need to change your vps and find a better one

**Comment by rezamh79** [comment]
Do you mean my ip has issue ? As I have a few servers on this VPS
It is dedicated server and I’m using Panel to paleo tunnel

Regards
Reza Behbahani
________________________________
