### ISSUE TITLE
دلیل ریستارت شدن سرویس Xray

### ISSUE THREAD

**Issue by SahandSOne** [MHSanaei/3x-ui#676]
با سلام و خسته نباشید

پنل هر ۵ مین یا ۴ مین یه بار ریستارت میشه و error  میده و بعد از ۱۰ ثانیه دو باره  اتومات استارت میشه.
لطفا ممنون میشم راهنمایی کنید
دیگه نمیدونم کجا رو چک کنم
داخل دیتا بیس هم نگاه کردم ولی چیزه غیر طبعی ندیدم نگاه کردم 

![image](https://github.com/MHSanaei/3x-ui/assets/134105392/c5f5600c-33fc-4d04-b430-865f61570f82)

![image](https://github.com/MHSanaei/3x-ui/assets/134105392/1f3f41c2-a97c-43b4-bcd8-78010f4b35a7)

**Comment by SahandSOne** [comment]
> 

![image](https://github.com/MHSanaei/3x-ui/assets/134105392/37cc6fd1-9d74-4705-91dc-001246bcec67)

**Comment by mmdh-ir** [comment]
بله بنده هم دقیقا همین مشکل گاهی برام پیش میاد

**Comment by llllnima1011** [comment]
در دستورات ssh لطفا x-ui گزینه 12 chek x-ui logs رو بگیر و یه اسکرین شات ازش آپلو کن تا ببینیم داستان از چه قرار هست.

**Comment by behnamgolds** [comment]
من همچین مشکلی داشتم نمیدونم در مورد شما هم صدق میکنه یا نه ،  سرور من پارتیشن swap نداشت ، یک فایل swap درست کردم  و با اینکه رم خالی دارم چند مگ همیشه swap درگیره و از طرفی هم باگ memory leak در سرویس warp که مموری زیادی میخوره ، فعلا برای اون هم یک cron job درست کردم که هر چند دقیقه یک بار چک کنه اگر مصرف رم سرویس warp بالای صدو پنجاه مگ بود ریستارتش کنه. مشکل ریستارت سرویس xray رو مدتیه که ندیدم.

**Comment by ahwazi12** [comment]
سلام خوبید  اکانت های که تاریخ اتمام کردن نمیشه همه رو حذف کرد
