### ISSUE TITLE
مشکل نصب - امروز

### ISSUE THREAD

**Issue by shehnipoor** [MHSanaei/3x-ui#677]
سلام
امروز برای نصب خطا دریافت میکنم
روی 5 سرور تست زدم
ربطی ب سرور نداره
Downloading x-ui failed, please be sure that your server can access Github این خطا

کسی این مشکل یا راه حل داره؟

**Comment by Habib1385** [comment]
سلام 
روی سرور های خودتون dns ست کنید تست کنید 
سرورتون هم حتما اوبونتو باشه ترجیها 22.04 
nano /etc/resolv.conf
nameserver 8.8.8.8
nameserver 4.2.2.4
سیو کنید و تست کنید
