### ISSUE TITLE
api login

### ISSUE THREAD

**Issue by Akbar2750** [MHSanaei/3x-ui#678]
دوستان سلام ، من با php کدی رو نوشتم که به پنل سنایی لاگین کنه و بعد با ارسال email یکی از اکانت های اون پنل، میزان ترافیک مصرفی و ... رو بگیره. (مظابق دستورات زیر) ولی خروجی که در نهایت برای result2 میگیرم ، آرایه نیست و فقط مقدار true  رو داره. 

لطفا اگر امکان داره منو راهنمایی کنین.
ممنون

$url='http://IPAddress:Port/';   

$email="hlc8vgh8-1"; 

$file = tempnam ("tmp", "cookie");
 

$data1=array(username=>"UserName",
            password=>"Password",
           
            ); 

$jsonData1=json_encode($data1);  

$ch1 = curl_init($url."login");
         
    curl_setopt($ch1, CURLOPT_CUSTOMREQUEST, 'POST'); 
    curl_setopt($ch1, CURLOPT_POSTFIELDS, $jsonData1); 
    curl_setopt($ch1, CURLOPT_COOKIEJAR, $file);
    curl_setopt($ch1, CURLOPT_COOKIEFILE, $file);
    curl_setopt($curl, CURLOPT_COOKIESESSION, true);
    curl_setopt($ch1, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch1, CURLOPT_HTTPHEADER, array(
        'Content-Type: application/json',
        'Connection: keep-alive',
        'Content-Length: ' . strlen($jsonData1)
    )); 
             
$result1 = curl_exec($ch1);
$err1 = curl_error($ch1);
$result1 = json_decode($result1, true, JSON_PRETTY_PRINT);

$ch1 = curl_init($url."panel/api/inbounds/getClientTraffics/".$email);
        
    curl_setopt($ch1, CURLOPT_CUSTOMREQUEST, 'GET'); 
    
             
$result2 = curl_exec($ch1);
$err2 = curl_error($ch1); 
$result2 = json_decode($result2, true, JSON_PRETTY_PRINT);
curl_close($ch1); 

echo $result2 ;

**Comment by mehdikhody** [comment]
## Postman Collection
https://github.com/MHSanaei/3x-ui/issues/303#issuecomment-1528819380

## PHP Example
https://github.com/MHSanaei/3x-ui/issues/324#issuecomment-1613096700
