### ISSUE TITLE
ObtainFail: database disk image is malformed

### ISSUE THREAD

**Issue by amir-gharajedaghi** [MHSanaei/3x-ui#680]
ایکس ری  استاپ شده 
بعد فایل config.json از مسیر پاک شده 
ولی فایل x-ui.db در مسیر هست 
فایل config.json رو برگردوندم اوک نشد
مشکل از دیتابیس هست  دیتابیس رو ک ایمپورت میکنم ایکس ری استاپ میشه 
میشه پنل رو اوک کرد ؟
بقیه table ها اوک هست ب جز inbounds ک خطای اشاره شده رو نمایش میده 
database disk image is malformed

[vscode-sqlite][ERROR] Failed to open database '/home/amir/develop/x-ui.db': SQLite process failed to start: The argument 'file' cannot be empty. Received ''

**Comment by MHSanaei** [comment]
دیتابیس شما ناقص هست برای همین وقتی ایمپورت میکنید به مشکل میخورید 
اگر هم میخواید مشکل رو حل کنید باید با DB Browser (SQLite) دیتابیس رو باز کنید و بگردید ببینید مشکلش چیه و حلش کنید
