### ISSUE TITLE
درخواست اضافه کردن قابلیت مسدود کردن محتوای پورنوگرافی به پنل وی پی ان را دارم . با توجه به وجود کودکان در میان کاربران وی پی ان، ارائه یک محیط جستجوی ایمن برای آنان بسیار حائز اهمیت است.

### ISSUE THREAD

**Issue by soroushsafaar** [MHSanaei/3x-ui#684]
لطفا در صورت امکان ، مثل قابلیت بلاک کردن آی پی یا دامین های ایران که در پنل موجود هست ، قابلیتی برای محدود کردن محتوا های پونوگرافی را قرار بدید. 
یک نکته اینکه من با ست کردن dns های مخصوص این کار میتونستم محتوا ها رو محدود کنم ولی همزمان حالت safe mode فعال میشه وکلا خشک و تر باهم میسوزه در نتیجه اگه ممکنه فقط همین رول رو تو اپدیت های بعدیتون لحاظ کنید. 

علت این درخواست: 
از اونجایی که در شرایط فعلی اینترنت ایران از بچه پنج ساله تا پیرمرد/زن ۹۰ ساله مجبور به استفاده از سرویس های فیلتر شکن هست ، این قابلیت منجر به حفاظت بیشتر از کودکان در برابر محتوای نامناسب و ایجاد تجربه آنلاین ایمن‌تر میشود.

در نهایت: 
از در نظر گرفتن این درخواست از شما بی نهایت سپاسگزار خواهم بود.

**Comment by vahidxo** [comment]
تو قسمت Panel settings, تب Xray configuration  رو باز کنید و از قسمت Blocking configs, تیک Block Malware and Adult Content رو بزنید تا سایت‌های پورنوگرافی بلاک بشن

**Comment by Mas70ud** [comment]
این تنظیمات در بخش panel setting ->  xray config -> basic template -> Blocking Configs -> Block Malware and Adult Content هست.
درخواستم اضافه کردن قابلیت تنظیم یک پورت خاص برای این تنظیمات هست تا بشه ترافیک کودکان و بزرگسالان رو از هم جدا کرد.

**Comment by gogoliandmagoli** [comment]
سلام . من میخاستم وی پی ان رو محدود کنم تا کاربر فقط فقط از واتساپ بتونه استفاده کنه . ممنون میشم راهنماییم کنید .

**Comment by sajjadvn** [comment]
این کانفینگ در روش تانل هم جواب میده ؟ و اینکه چطور میشه یک اینباند مخصوص ایجاد کنیم ؟
