### ISSUE TITLE
درخواست اضافه شدن سینک بین چند سرور

### ISSUE THREAD

**Issue by danyalfa79** [MHSanaei/3x-ui#685]
با درود و احترام
باتوجه به تعدد سرور ها و یوزر ها، درخواست اضافه شدن قابلیتی رو داشتم که دیتای بین سرور ها رو اتوماتیک سینک بکنه
به عنوان مثال اگر در سرور A یوزر دانیال ساخته شد، همین یوزر با همین UUID داخل سرور B و C هم ساخته بشه. همچنین جزئیات یوزر مثل ترافیک مصرفی و فلو و... اتوماتیک سینک بشن
مزیت این اتفاق این هست اگر سرور جدیدی خواستیم اضافه کنیم، فقط با لینک کردن به سرور اصلی بتونیم تمام اطلاعات سرور ها رو روی سرور جدیدمون هم داشته باشیم

**Comment by behnamgolds** [comment]
<p dir=auto>
تا وقتی این امکان اضافه نشده میتونین با یک اسکریپت روی سرور مبدا و با کمک rsync و ssh و یا با scp این کار رو انجام بدین ،مثلا میتونین یک جاب cron اضافه کنین که هر دو دقیقه یک بار فایل کانفیگ رو چک کنه ، اگر modified time کمتر از دو دقیقه بود از طریق scp فایل رو به سرورهای دیگه ارسال کنه و از طریق ssh هم سرویس پنل رو روی اون سرورها ریستارت کنه.
</p>

**Comment by danyalfa79** [comment]
> تا وقتی این امکان اضافه نشده میتونین با یک اسکریپت روی سرور مبدا و با کمک rsync و ssh و یا با scp این کار رو انجام بدین ،مثلا میتونین یک جاب cron اضافه کنین که هر دو دقیقه یک بار فایل کانفیگ رو چک کنه ، اگر modified time کمتر از دو دقیقه بود از طریق scp فایل رو به سرورهای دیگه ارسال کنه و از طریق ssh هم سرویس پنل رو روی اون سرورها ریستارت کنه.

ایراد این مسئله اینه اگر یوزر به سرور B وصل بشه، ۱ گیگ استفاده کنه و بعد به سرور C وصل بشه و اونجا هم یک گیگ استفاده کنه، سرور A فقط یکی از این دوتا تغییر رو میپذیره

**Comment by behnamgolds** [comment]
بله ، شما این مورد رو مطرح نکردین ، پیشنهاد میکنم به پستتون اضافه کنین تا کامنت ها زیاد پینگ پنگی نشه. تا جایی که اطلاع دارم این حجم ها در دیتابیس sqlite3 در مسیر  زیر ذخیره میشه:
```
/etc/x-ui/x-ui.db
```
این مورد هم مثل موارد قبل میشه اسکریپت کرد که از طریق ssh بشه حجم ها رو هر چند دقیقه اضافه کرد ولی مطمئنا از حوصله ی کاربر خارج خواهد بود.
امیدوارم به درخواستتون رسیدگی بشه.

**Comment by Samiiix** [comment]
از طریقی که @behnamgolds گفتن، میتونین این کار رو انجام بدید، برای حجم مصرفی هم میتونید مشخص کنید که وقتی فایل دیتابیس کپی میشه، چه اطلاعاتی رو درونش حذف کنه، یا مقدار بخش خاصی رو 0 تنظیم کنه.
