### ISSUE TITLE
چرا لینک عضو شدن از ورژن های جدید حذف شده؟ Subscription 

### ISSUE THREAD

**Issue by elegance666** [MHSanaei/3x-ui#695]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

تا ورژن 1.4.1 هر کاربر امکان ایجاد Subscription  داشت، اما در ورژن های جدید این امکان خوب حدف شده

### Version of 3x-ui

1.4.1

### x-ui log reports or xray log

1.7

**Comment by rooshanak** [comment]
حذف نشده
