### ISSUE TITLE
رفع مشکل ارتباط با سایت گوگل با ارور443

### ISSUE THREAD

**Issue by khalilhosseini1361** [MHSanaei/3x-ui#699]
با سلام
ممنون از زحمت زیادی که در این راه متحمل می شید .
متاسفانه در استفاده از اکانت های vless / ws   مشکل دارم برای سرچ در گوگل و بطور کلی با سرویس های گوگل مشکل دارم می شه راهنمایی بفرمایید برای رفعش چه باید کنم .
ممنون از لطفتون

**Comment by mer30hamid** [comment]
توی قسمت Xray Configuration این موارد رو فعال کن باید درست بشه (یکی یکی امتحان کن)

- اول: در قسمت IPv4 Configs گزینه Use IPv4 for Google فعال کن و دکمه ریستارت پنل رو بزن چک کن
- دوم: اگه باز هم درست نشد از قسمت WARP Configs، وارپ رو براش فعال کن (توضیح داده چیکار باید بکنی)

**Comment by khalilhosseini1361** [comment]
بله 
ممنون از شما
