### ISSUE TITLE
کار نکردن IP Count Limit در حالت Nginx Reverse Proxy

### ISSUE THREAD

**Issue by nasiriscript** [MHSanaei/3x-ui#70]
**Describe the 3x-ui bug**
کار نکردن IP Count Limit در حالت Nginx Reverse Proxy 
**Expected behavior**
قسمت IP Count Limit بر روی 1 تنظیم میشود ولی کار نمیکند

**Server (please complete the following information):**
 - OS: [Ubuntu]
 - Version [22.0.4]

**Additional context**
راهی وجود دارد که درست بشه؟
[اینجا](https://github.com/FranzKafkaYu/x-ui/issues/304#issue-1629900967) برای پنل کافکا هم این مشکل گزارش شده و یه راهه حل هم پیشنهاد کرده از این طریق میشه کاری کرد؟

**Comment by nasiriscript** [comment]
بله، برای اینکه ترافیک تمام کانفیگ ها اعم از ویلس، ویمس و تروجان فقط از پورت 443 رد بشه و میشه یه وبسایت بالا آورد و ترافیک پروکسی پشت وبسایت مخفی میشه.

**Comment by alireza0** [comment]
@nasiriscript 
چرا از fallback استفاده نمیکنید؟

**Comment by alireza0** [comment]
توضیحات کامل رو [اینجا](https://github.com/XTLS/Xray-examples/tree/main/All-in-One-fallbacks-Nginx) میتونید ببینید.
البته این مثال خیلی کامله و شما میتونید آسونتر هم اجراش کنید.

**Comment by nasiriscript** [comment]
> توضیحات کامل رو [اینجا](https://github.com/XTLS/Xray-examples/tree/main/All-in-One-fallbacks-Nginx) میتونید ببینید. البته این مثال خیلی کامله و شما میتونید آسونتر هم اجراش کنید.
مچکرم
