### ISSUE TITLE
امکان ارتباط با شماره کاربر به جای نام کاربری تلگرام

### ISSUE THREAD

**Issue by khalilhosseini1361** [MHSanaei/3x-ui#700]
با سلام
می خواستم در ابتدا بدونم امکان ارسال ناتیفیکیشن به یوزر در بازه حداقلی تایم و حجم تعریف شده در پنل برای یوزر از طریق تلگرام وجود داره ، ثانیا امکان ارتباط با تلگرام یوزر با شماره یوزرها و نه آی دی تلگرام وجود داره یا خیر ؟
می شه این امکان را داشت ؟

**Comment by MHSanaei** [comment]
اولی خیر 
دومی بله میتونید ایدی نامبر تلگرام رو قرار بدید
