### ISSUE TITLE
راهنمای در مورد کامپایل سورس

### ISSUE THREAD

**Issue by alirezazarghi** [MHSanaei/3x-ui#701]
با سلام و حسته نباشید خدمت شما
آیا امکان دارد در مورد کامپایل کردن سورس من را راهنمایی کنید؟
من چند api اضافه کردم به سورس ولی از آنجا که با GO آشنایی زیادی ندارم 
لطفا من را راهنمایی کنید تا سورس را کامپایل نماییم 
با تشکر از شما

**Comment by MHSanaei** [comment]
برای تست کردن روی سیستم شخصی اگر ویندوز هستید go رو به همراه یک نسخه انتخابی از gcc نصب کنید بعدش میتونید روی ویندوز اجرا کنید
