### ISSUE TITLE
دایرکت دامین با dokodemo-door

### ISSUE THREAD

**Issue by jamiekarvans** [MHSanaei/3x-ui#705]
سلام خسته نباشید اقای ثنایی ممنون بابت تلاشاتون و وقتی که میزارید
من اومدم دوکدمودور زدم از سرور ایران به خارج و روی سرور ایران از پنل تیک که دامین ایران رو مستقیم وصل کنه و به سرور خارج نفرسته اما کار نکرد اینطور
حالا اومدم طبق اموزش خودتون توی کانال گزاشته بودید برای ریلیتی رفتم و همه چی اوکی بود و دامین ایران رو با سرور ایران میرفت اما 
 1. مشکل اول اینکه با این کار فقط یک اینباند میشه زد درسته؟ اگر بخوام من چندتا اینباند بزنم توی قسمت اوتباند سرور ایران چطور باید واردشون کنم؟ و چرا همون دوکدمودور جواب نمیده؟
2. و یک موضوع دیگه الان بهترین روش برای سرعت خوب و دیر فیلتر شدن کدومه هنوز همون ریلیتیو ویژن هست؟
ممنون بابت کمک هاتون

**Comment by MHSanaei** [comment]
دلیلی برای چندتا اینباند زدن در سرور خارج وجود نداره
و بهترین روش همین پنل به پنل هست ولی برای اینکه کدوم نتیجه و سرعت بهتری میده باید پروتکل های مختلف رو تست کنید
