### ISSUE TITLE
مشکل ارور database is lockedدر پنل

### ISSUE THREAD

**Issue by ariomohammad** [MHSanaei/3x-ui#708]
هفته هاست که ارورdatabase is locked در تمام نسخه ها و ورژن های پنل سنایی برام میاد و گاهی اوقات به مدت یکروز کامل اجازه دسترسی و تغییرات در پنل و یوزرهامو بهم نمیده...چندین پنل دارم و همه این مشکل رو دارن

**Comment by MHSanaei** [comment]
مشکل از هارد ضعیف سرور شماست برای حل این مشکل لاگ access رو از کانفیگ حذف کنید داخل تنظیمات هست
