### ISSUE TITLE
DNS over HTTPS

### ISSUE THREAD

**Issue by vm-project-repo** [MHSanaei/3x-ui#709]
Hi everyone,

i'm RU user of your best of the best VPN server but i have 1 problem: 
i have no access to linkedin.com , my verifications brocken after capcha checking and linkedin.com displayed message about page refrashing, i think problem is not secured DNS. I already try to install wrap and AdguardHome in docker-compose.yml but my DNS not DNS over HTTPS or DNSCrypt . I think that server need Xray Configuration Template editing but i have no needed skills ...
Could anybody help me with  DNS over HTTPS or DNSCrypt configurations

**Comment by ali-cloudy** [comment]
Buddy you must come to one the guys that can learn to you in pv . It's difficult hear explain it man.

**Comment by RangerRU** [comment]
Так это в клиенте делается
Зачем тебе конфиги править

Вот пример с V2rayNG:
![image](https://github.com/MHSanaei/3x-ui/assets/171711/55a419d0-f55a-4e66-ad06-1c5ed54b48ca)
