### ISSUE TITLE
Can you please add the aes-128/256-gcm encryption method for Shadowsocks?

### ISSUE THREAD

**Issue by Jadelog** [MHSanaei/3x-ui#711]
**Is your feature request related to a problem? Please describe.**
Shadowsocks 2022 Edition is not supported by Clash premium core yet.
 
**Describe the solution you'd like**
Please add the aes-128/256-gcm encryption method for Shadowsocks.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by MHSanaei** [comment]
old ss method add to v1.7.1

**Comment by MHSanaei** [comment]
old ss method added to v1.7.1
