### ISSUE TITLE
مشکل در کانفیگ

### ISSUE THREAD

**Issue by omrani77** [MHSanaei/3x-ui#715]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام . 
من پنل رو نصب کردم و طبق تمام مراحل عمل کردم و SSL رو هم فعال کردم . اما همچنان کانفیگی که بهم میده با ارور Fail to detect connection : io:read/write on closed pipe مواجه میشه . مشکل کارم کجاست ؟ 
یکی گفت VPS رو از پرووایدر اشتباهی گرفتی . ممکنه مشکل از اون باشه ؟ 

همین VPS برای SSH مشکلی نداره !

### Version of 3x-ui

1.7

1.8.3

### x-ui log reports or xray log

[x-ui.log](https://github.com/MHSanaei/3x-ui/files/11990532/x-ui.log)

**Comment by AliBelali** [comment]
با سلام
با توجه به لاگی که به اشتراک گذاشتید به نظر میرسه که فایل سرتیفیکیت رو اشتباه تعریف کردید

در قسمت Public Key Path
باید فایل fullchain.pem رو معرفی کنید
در قسمت Private Key Path
فایل privkey.pem باید معرفی بشه
