### ISSUE TITLE
cpu usage and traffic 

### ISSUE THREAD

**Issue by omrani77** [MHSanaei/3x-ui#716]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

با وجود اینکه هیچ یوزر فعالی وجود نداره ترافیک مصرفی و CPU Usage انقدر بالاست . علت چیه ؟
مشخصات سرور : 
CPU: AMD EPYC 7702P
Core(s): 2
Memory: 4GB RAM
Storage:  75GB NVMe

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by AliBelali** [comment]
باسلام

لطفا در ترمینال سرور خودتون دستور top رو اجرا کنید و خروجی رو به اشتراک بذارید و همچنین در وسط صفحه موس رو روی اون علامت سوال کنار error بذارید یه متن نمایش داده میشه اون رو هم عکس بگیرید و به اشتراک بذارید
ترجیحا تو عکسی که به اشتراک گذاشتید قسمت دامنه که تو آدرس بار مشخص هست رو هم بلور کنید

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
