### ISSUE TITLE
CPU 100% !!!

### ISSUE THREAD

**Issue by pooria1380** [MHSanaei/3x-ui#717]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام لطفا راهنمایی کنید چجوری مشکل درگیر شدن کامل CPU رو حل کنم
این قسمت صد درصد درگیر میکنه CPU رو
bin/xray-linux-amd64 -c bin/config.json -restrictedIPsPath bin/BlockedIps

### Version of 3x-ui

<details>

```console
# Paste here
latest version

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by SamanKhalife** [comment]
سرورتا ری استارت کنی احتمال زیاد رفع میشه 
اگه هم با یه نصب نرم افزار خاص (مثل x-ui) در گیر شده یه systemctl stauts از اون بگیر ببین حال اون سرویس خوبه بعد وضعیت سرور با top یا htop چک کن

**Comment by curkan** [comment]
Xray load 
Whenever a client uses the network, the system boots up to 100

<img width="1038" alt="Снимок экрана 2023-08-09 в 22 58 43" src="https://github.com/MHSanaei/3x-ui/assets/1681501/2634ced2-dc2a-4168-a9d7-79b2681ee8e5">

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
