### ISSUE TITLE
مکان ذخیره سازی پروفایل کاربران

### ISSUE THREAD

**Issue by sohrabp72** [MHSanaei/3x-ui#720]
سلام
من کاربرام روی x-ui نسخه انگلیسی هستن و فایل backup که یوزر ها توش هستن در آدرس 
`/etc/x-ui/x-ui-english.db`
هست
میخوام این فایلو کپی کنم جایی که پنل سنایی یوزر هارو ذخیره میکنه تا کاربرام رو  بتونم بیارم روی این پنل.
آدرس فایلی که پنل سنایی یوزر هارو ذخیره میکنه کجاست؟

**Comment by AliBelali** [comment]
قبل از اینکه پنل سنایی رو بخواید نصب کنید این دستور رو اجرا کنید
cp /etc/x-ui/x-ui-english.db /etc/x-ui/x-ui.db
کلا قبل از نصب پنل جدید هم یه بکاپ کامل از پنل قبل بگیرید

**Comment by sohrabp72** [comment]
ممنون
