### ISSUE TITLE
اینترنت همراه

### ISSUE THREAD

**Issue by mrmasiha0** [MHSanaei/3x-ui#722]
درود
من وقتی از اینترنت همراه (ایرانسل یا همراه اول) استفاده می کنم با پیام خطای زیر مواجه میشم ولی با همون کانکشن به راحتی به اینترنت ثابت وصل میشم. ممنون میشم راهنمایی کنید.

Fail to detect internet connection: io: read/write on closed pipe

**Comment by misagh72** [comment]
سرورتون محدود شده روی ایرانسل و همراه اول

**Comment by mrmasiha0** [comment]
> سرورتون محدود شده روی ایرانسل و همراه اول

نه خوشبختانه. با هیدیفای تست کردم قبلش اوکی بود. اما به دلایلی میخوام از این پنل استفاده کنم. ممنون میشم اگر از اینترنت ایرانسل یا همراه اول استفاده می کنید کانفیگی که برای این پنل دارید  تنظیماتش رو برام اسکرین بگذارید.
