### ISSUE TITLE
نمایش تعداد  Ip limit  در صفحه اصلی 

### ISSUE THREAD

**Issue by aliChavoshi** [MHSanaei/3x-ui#725]
باسلام تعداد  IP limit  هایی که برای کاربران زدیم رو لطفا در صفحه اصلی نمایش بدین که بدونیم تک کاربر هستن یا دو کاربر ممنونم

**Comment by AmoAlireza** [comment]
پیشنهاد خوبیه, مثلا همچنین چیزی:
![Capture](https://github.com/MHSanaei/3x-ui/assets/79990596/16744d64-1424-4430-bd77-1316961daf0c)

**Comment by aliChavoshi** [comment]
عالی
