### ISSUE TITLE
گرفتن لینک کاربر

### ISSUE THREAD

**Issue by masoodshams** [MHSanaei/3x-ui#727]
در بخش API لطفاً ارسال کد کاربر رو اضافه کنید تا بشه باهاش اکانت ساخت و به کاربر ارائه داد.

در حال حاضر کاربر ساخته میشه ولی برای دریافت کد و کیوآر کد باید به پنل مراجعه کرد.

**Comment by mohamad6996** [comment]
> دقیقا واقعا این لازمه الان مثلا میخوام کانفیگ های کلاینت با ایمیل amir رو بگیرم باید لیست کل inbounds ها رو بگیرم بعد توی ستینگ تنظیماتو بردارم و لینک بسازم توی تعداد کاربر کم مشکلی نداره ولی مثلا من که بالای ۲ هزار کاربر دارم واقعا این پروسه گرفتن کل و ساختنش طول میکشه توی هاست
> 
> بهتره همونجا که کلاینت اد میکنیم توی api پاسخ برگشتی لینک رو بده بهمون مستقیم . نه اینکه کل ورودی ها رو بگیرم و حالا بیام بسازم برای اون کاربر
> 
> قابلیت جستجو هم داشته باشه خوبه یعنی ایمیل کلاینت و شماره inbound رو بزنی و لینک رو بده بهت مستقیم اینجوری خیلی استاندارد تر میشه به نظرم
> 
> اخه هربار بیاد کل دیتابیس رو با get inbounds list بگیره خیلی زمان بر میشه و منابع زیادی مصرف میشه
> 
> بعد اینکه توی api ساخت کلاینت هم تایین کردن ساب رو بزارید اینم خیلی لازمه



> دقیقا واقعا این لازمه الان مثلا میخوام کانفیگ های کلاینت با ایمیل amir رو بگیرم باید لیست کل inbounds ها رو بگیرم بعد توی ستینگ تنظیماتو بردارم و لینک بسازم توی تعداد کاربر کم مشکلی نداره ولی مثلا من که بالای ۲ هزار کاربر دارم واقعا این پروسه گرفتن کل و ساختنش طول میکشه توی هاست
> 
> بهتره همونجا که کلاینت اد میکنیم توی api پاسخ برگشتی لینک رو بده بهمون مستقیم . نه اینکه کل ورودی ها رو بگیرم و حالا بیام بسازم برای اون کاربر
> 
> قابلیت جستجو هم داشته باشه خوبه یعنی ایمیل کلاینت و شماره inbound رو بزنی و لینک رو بده بهت مستقیم اینجوری خیلی استاندارد تر میشه به نظرم
> 
> اخه هربار بیاد کل دیتابیس رو با get inbounds list بگیره خیلی زمان بر میشه و منابع زیادی مصرف میشه
> 
> بعد اینکه توی api ساخت کلاینت هم تایین کردن ساب رو بزارید اینم خیلی لازمه

سلام من با مشکل قطعی و سرعت خیلی کم و پینگ بالا مواجه سدم امکانش دارید در مورد تنظیمات و sni راهنمایی کنید اشکر

**Comment by ali-cloudy** [comment]
عزیز بنظرت اینجا جای سوال راجب کندی سرعت و sni !?  دغدغه ی دوستان تو این کامنت ریسپاند به کلاینت از پنل بابت دریافت مشخصات کانفیگیه ک‌ خریده . بعدشم مشکل شما بدست بقیه حل نمیشه . چون که باید هر هفته دوبار به باتوجه ب تعداد یوزرهات sni اسکن کنی است کنی و مرتب و دسته بندی شده داخل ی نوت پد ذخیره کنی . دلیل اول . اگر از یک سرورت ۵۹ نفر از یک آی پی ثابت با یک sni فینگرپرینت شن ترافیک تو چشم و باعث فیلتر شدن . چون ۱۲۰ مگا بیت ترافیک از ی ای پی مرتبط میشه به ی سایت مداوم ؟! پیدا کردن sni هم از آب خوردن راحت تره حتی اسکن هم نکردی نکن . سایت های معروف رو ک‌مطمعنی فیلتر نیستن و پینگ پایینی میدن بهت رو دامنه خالی بدون ساب رو بزار داخل کانفیگ تست کن رو اپراتورها . همین الان چندتا بهت sni بدم ؟! فک کنم بعد از یک سال دیگه وقتشه ب جای سوال سوال سوال سوال بیایم تجربیات و دانش و ... کسب کردیم باهم ب اشتراک بزاریم ولی متاسفانه هنوز میبینیم که طرف فروشندست کانال و تبلیغ و مشتری هارو میبینی ویکی دمش گرم میگ چرا سرور درام می‌کنه بیرون چک میکنیم میبینیم ۲۲ پورتش هنوز . متاسفانه نه sni پشتیبان دارن نه پنل پشتیبان نه سروره پشتیبان نه دامنه ی پشتیبان نه پلن پشتیبان و میان ی هو ۵۰۰ نفرو میریزن تو ی سرور ۲۰ دلاری هتزنر با ذوق و سر سینه جلو پز هم میدن .فک نمیکنن ک تو قطعی و فیلترینگ و اصلا مشکل دیتاسنتر خارجی داشتم من سرور معتبر آمریکایی ۹ روز پایین بوده ۵۰۰ نفرو بدون ساب چ جوری قراره کانفیگ جدید بدن ؟! و جالبه هنوز دارن ورود میزنن افراد که تازه میخوان کار رو آغاز کنن ب اون خدای دروغی اسلام و پایم آور زشتی ها و فساده اسلام و یک میلیارد ناقص العقل ۸۰ م‌جمعیت داریم ۹۰ م فروشنده . فقط قیمت آوردن پایین چند وقت دیگ فک کنم بشه ۵ هزارتومان . ولی امنیت صفر . کیفیت زیر صفر . کمیت وجود ندارد . کانفیگ هاشون لخت بدون آس آس ال بدون هیچ لایه ی امنیتی قابل اسنیف شدن و کمتر از ۲۴ ساعت فیلتر میشه یا نهایت ۳روز ۴ روز . و تنها کاری هم ک بلدن خرید اکانت اشن و ولت آر و هتزنر و لینود و ... چون کردیت رایگان ۲ ماهه داره . تا ۲۵۰ دلار ولت آر سریع ای پی عوض میکنن . اینجوری شد که ایرانی ها تونستن تنها ابزار و بهترین و با ارزش ترین دیتاسنترای ساعتیشون رو نابود کنند ک‌ الان همرو ب بدبختی انداختن . در ضمن بگم من نه وی پی آن فروشم نه پنل زنم و ... کارشناس حوزه ی تکنولوژی هستم و در حال راه اندازی یک سایت برای ارایه و فروش سرور خارجی فقط ای پی تمیز منتهی نه دزدی و کلاه برداری با قیمت های مریض گونه . و تا الان ک شمردیم بیشترین تعداد لوکیشن و تنوع آیتم رو دارم تو کشور . از گیم تا مناسب ویژوال بیسیک ران کردن و تا سرورای جده و کراچی و ... مناسب پی پال تا نوشتن پنل برای لینک کردن به سرور ۲م تومنی اختصاصی ایران واس ارتباط ۱۰۰۰ نفر و صد البته سعی میکنم تمام تحربیاتم و آموخته هام رو ک از دوستام و شما و حتی دانشگاه ک ۱۲ سال پیش فقط میرفتم و میومدم و یادمه تو نوت پد html بهمون یاد دادن ‌. هنوز ایندکس نشده تو گوگل . ران بشه داخل کیت هابم میزارم و قصد دارم تمام داشته هام راحب فیلترینگ رایگان ب اشتراک بزارم داخل کیت هابم . بهترین پنل ها . متدها . کد ها . همه مرتب . تست شده ب روز و قوی و عالی . قراره ۹۰٪ مابقی پنل ها و آموزش مفاهیم لینوکس ای پی ، دی آن اس ، ارتباطات و .... رو آموزش کنم و سورپرایز های عجیب ک بفهمید وی تورای مناسب فروشنده هاست و محبورن . ولی واس استفاده ی شخصی ‌. 
Sslh , tls ssh , ssh multiplex , tls tunneling vpn , و از همه مهم تر و بهتر و عزیز تر و خدا openvpn
بچه وایرگارد من خیلی تست کردم نتونستم . پس مانور نمیدم . چون دیدم مابقی بچه های حوزه هم وقت کزاشتن و حتی یک بایت ریسیو نداشتن ‌. اپن کانکت خوبه ولی اعتراف ک سخته ‌. چرا سخته چون ک ما مجبور ب تانلیم وگرنه مشکلی نداشت . تا الان ۳ تا تانل استفاده کردم فقط رو stunnel ج داده ولی در حد ۲۰ کیلوبایت . مونده گست و اسپلیت و فیک تی ال اس و .... ولی مطمعنم که نیاز دوتا سرور روون و قوی و فوق العاده نیاز داره و بدرد فروشنده ها نمیخوره مگ طرف تحربش رو از قدیم داشته باشیم ب درد مصرف کننده ی خونکی ام نمیخوره ‌. در ضمن میشهدنبال ای پی تمیز کلاد و ‌‌... نگردید هم کم شده هم زود ممکن بخوره ولی داریم طرف ۳ ماهه ی دونه پیدا کرده هنوز مث بنز رو تمام سروراش ست کرده و فک کنم ۸۰۰ نفری رو همون ی دونه هستن ‌. در ضمن هرمی گفت تضمین میدم قطع نشه و فیلترینگ و ... تعطیل دروغ میگه مث بز . اونی ام ک باور می‌کنه اسبی بیش نیست و هنوز تو توهم و رویای زیبای دین و سیاست مداران ایران گیر کرده و دروغ رو دوست داره و امید رو با شنیدن دروغ جا ب جا کرده و اشتباه گرفته . اگر کانالی با ظرفیت ۸۰ کا کبیر اسم نمیارم فیلتر نشه . سروراش همیشه بالان همشون تانل هستن و نیم بها و جوری مانور میده که مردمم تشکر و عشق ک من چهارستون بدنم مبارزه که میون این همه بزغاله زندگی میکنیم . برای فیلترچی بهتره که از مثلا ۱۰۰٪ استفاده کننده های وی پی آن ۳۰ ٪ رو آنلاین نگه داره دایم و کیفیت و قیمت قابل قبول ارایه کنه و ... و ۷۰ بزنه بترکونه ٪ سودش دو طرفست هم از این ۳۰٪ درآمد زایی می‌کنه هم اینکه اسنیف می‌کنه تمام زندگی افراد زیره دستش شما می‌بینید ۳۰٪ اسنیف می‌کنه ب واسطه ی اون ۳۰ ٪ افراد مختطبشون رو هم حداقل اطلاعاتشون رو بدست میاره از همه بدتر دوستان دانشمند و دانا و زرنگ و بفروش و ما خنگ ما نابلد ما کودن . ی کانکشن بدون داشتن رمز نگاری ب راحتی قابل رصد و بیرون کشیدن اطلاعات هست . اطلاعات ک فقط عکسای نود و ... نیست . من ک میگم اصلا فعالیت سیاسی نکنید با سرورای فروشی مگر اینکه خودتون متخصصص یا حداقل متبحر حوزه باشید . بازم رو دستتون بلند میشن ‌. دزدیدن کد ریکاوری کیف پول های محازیتون . از داخل درایو مجازی گوگل یا مایکروسافت وان از طریق بدست آوردن یوزر پس ایمیلتون یا هزارتا راه و روش دیگ من هکر نیستم ولی دوستانم چرا ب چشم تو ۳ دقیقه تمام یوزر پس های ی رفیق دیگمون رو از داخل کروم طرف فقط با ی لینکی ک با پایتون نوشته بود و داخل سوشال فرستاده بود و چون علاقه مندی طرف بود بدون درنگ کلیک و دسترسی و ترانسفر اطلاعات کروم با پرسیدن چند سوال ک‌ سوالات واقعی نبود یعنی سوال ی چیز ولی اکت سوال ی چیره دیگه کلیک رو لینک تخفیف دیتاسنتر ب مناسب اضافه شدن ۳۱ امین لوکیشنش تا ۶۰٪ ی دیتاسنتر معروف ک‌ میدونستم دوست داره ازش سرور بگیره چون گرونه نگرفته بوده تا حالا . و باز شدن ی وب پیج دقیقا شبیه پیج سایت اصلی و تا طرف بیاد داخل صفحه ی ثبت نام ک مشخصات بزنه با زدن ۳ تا دکمه یس و در آخرین تاییدیه ک اثرانگشت رو بعنوان راهی برای احراز هویت فرد ک‌ربات نیست و جوری اون فیلد هارو چیده بوده که زمان کافی رو داشته باشه برای گرفتن یوزر پس ها . و اینکه مگ ۱۰۰ تا یوزر پس چقدر حجم داره تازه ۱۰۰۰ تا زیاد گفتم . تو فیلدها داخل فیلد اسم نباید اندر لاین میزدی و . و ... ولی باید حتما از ۳ تا ساین استفاده میکردی این ی وقت کشی . تو پسسورد ک ۵ تا رول فیکس کرده بود . تو چیدمان و نوشتن آدرس . شماره تلفن و رفرش شدن پیج از دوباره ک اگر ی موقع ارتباط قطع شد بتونه دوباره با رفرش شدن و سوالی ک سایت میپرسید ک با رفرش مشخصات باید از اول وارد کنید پرمیشن دسترسی رو رینیو میکرد . حالا شما با چ جراتی میرین از کانفیگ ۱۰۰ تومنی ترید میکنید من پشمی دیگ ندارم دو دلیل . ۱ ای پی ذکر ثابت نبود چی ؟! اگر پست سی دی آن بود و پراکسی شده . اگر وارد داینامیک . اگر داخل سایت های مث duckdns یا noip ک بعصیاشون با پرداخت سالیانه فقط ۶ دلار ی دامنه و ساب رو یک سال میتونی پنهان و تمیز نگه داری البته در اصل ای پی ک‌به دامنه متصل شده رو و با ی سری کاره دیگه اگرم ساب بسته شد پولی از دست ندادی چون دامنه نخریدی سایت ساب انداخته پشت دامنه ی خودش ک ی عالمین و خودتون انتخاب میکنید . آها اینم بگم تا دوست دارید نرید خودتون ببینید زحمت بکشید بچرخید برای آموختن و فقط سوال و خواهش و تمنا . عذت نفس مرده . منتهی ی چیزایی از دست میدید ک ماهایی ک عشقشو داریم خودمون بگردیم و بچرخیم و بفهمیم و بیاموزیم ک عمرا شماها تو خوابم نمبینید . دوتا مثال . سرور با ۴ هسته سی پی یو فرکانس ۳.۵ رایزن . ۱۶ گیگ رم ec² ddr4 
هارد nvme² hybrid 180GB
در ضمن غیر از پورت تمام منابع اختصاصی پورت هم بین ۵ نفر تقسیم میشه ک هوشمنده اگر همزمان هر ۵ تا متصل نباشند تا حدودی از سهم همسایه قرض میگیره ک آور لود نشین و بهتون میل میرنه ک عامو ظرفیت پردازش و یا ترافیک کم‌کن وگرنه ب چه میری که البته بک آپ رایگان داره . هفته ای دوبار ‌. پینگ ۱۱۰ . لوک هلند . ترافیک ۳۳۰،۰۰۰ ترابایت . دقت کنید ترا نه ها . یعنی اگر تقسیم بر ۱۰۰ گ‌کنید میشه ۳،۳۰۰ نفر . قیمت ۱۶ دلار که البته شروع تابستان تخفیف زد ۶۰٪ به مدت ۳ روز یعنی ۶ دلار . بازم میگم اختصاصیه ها یعنی اگر ۲۵ دلارم بود باز نصف قیمت ی اختصاصی مضخرف بود . کنترل پنل اختصاصی سایت . قابلیت دانلود تمام سیستم عامل هاشون و آپلود و کانت ایزو شما ب راحتی . لوکیشن ها . توکیو . برزیل .هلند . بمبیی . سنگاپور و ۵ ایالت آمریکا . دالاس . بوفالو . میامی و ... و اگر ای پی کثیف خورد بهت بهت ی ماه جایزه میدن سرور رایگان چون امر بخوره رایگان برات ای پیتون تیکت میزنی عوض میکنن . دهن ها ال نیفته این ی دونه از اون ۸۰ تا دیتاسنتری ک وریفای کامل و فعال دارم و دارم چینش میکنم تو وورد پرس هاستم . همین دیشب از لاس وگاس سرور ۶ دلاری ی دلار با پرفکت مانی گرفتم . دوستان پیام ندید ک اسماشون بدم . تو کوگلم پیدا نکنید همشون خصوصی و لاکچری و بخصوص هستند از کل دنیا و نکته ی بعد از من زرنک ترم زیاده ک بتونه پیدا کنه نکته ام این نیست . احراز هویتشه . گلم پی پال درست درمون ۸ میلیون ایرانیکارت میده . مداارک تمیز نیاز دارید ک ۳۰ دلار خامش باید بخرید چ خودتون از دارک و...ب چ از آیرانیکارت و تیر خلاص با وی پی آن نمیشه ثبت نام کرد مث وی تورای و هیچ وی پی آنی فرق ندارن اپن وی پی آن حتی برین وی پی آن پولی خارجی بخرید بازم نمیشه چون میفهمن . در ضمن ی سریشون هربار بخواین برین داخل پنلتون یا سایت ب شمارتون پیام میده کد رو شماره آلمان و هلند و اصن هرحارو دایمی چطوری میخواین بکیرید ؟! البته هست ها از ۱۰ م شروع میشه . بعد میتونید پاسپورت خام ب قدری حرفه ای درست کنید که هوش مصنوعی نفهمه،؟!!؟! و در نهایت حتی اگر ی وقت اینترنتتون قطع ش یا هرچی اصلا الان میگن کیل سوییچ اکتیو میکنیم رو هوا بلاک میشید و حتی مک‌ادرس اون دستگاه ثبت میشه تو دیتابیسشون و دیک نمی‌تونید عضو شید و سرورتون و ۵۰۰ تا یوزر روش پرید . در جا ایمیلتونم بلاک می‌کنه ک حتی میل هم میتونید بزنید یا اگر خطتتون درست باشه. حالا ثبت نام دانشگاه . فری لنسری . صرافی ها . پی پال . فارکس و انجمن های دانشجویی و پزشکی و علمی و ... و ... باید بتونید ثبت نام کنید اینا همه آیتم کاره بندست با اجازتون گفتم ک حرفی نمونه بابت دوستان فش ب دهن و بی شخصیت و پلشت دور از جون همه خوبان و با ادبا . و اینکه دنبال پاس و ای دی وای احراز ولت آر و این و ... نباید چون خام نمیدم بهتون نمیخوام تو دزدی بعضی ها ک کمم هستن شریک. باشم دور از جون همه . پنل هم فقط خودت پنل میدم یعنی مشخصات و آدرس دانلودش و آموزش استفادش چون اگر غیر ازین باشه طرف جر میده ۲۴ ساعت که یوزر بساز برام . چرا کنده. Sni بده و خلاصه فکر می‌کنه ما ادمشیم و مردمم حکم گنج گمشده رو داره براشون جالب میان با مظلوم نمایی از من رایگان آموزش ببینند ک‌ در جا بلاک یا طرف باید قول بده که تمام کانفیگ هاش خیرات کنه و رایگان بده مردم منم رایگان آموزش خفن میدم وکر

**Comment by mehdikhoram** [comment]
@NekoHanaku 
از کش استفاده کنید تا در درخواست های بعدی نیاز به پردازش کل لیست و کاربران نباشد.
یا هنگام ساخت کاربر توی کش هم اطلاعات را ذخیره داشته باشید.
