### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by navid221** [MHSanaei/3x-ui#728]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام وقت بخیر. هنگام اضافه کردن و یا پاک کردن یوزرها تغییرات ذخیره نمیشه و خطای database is locked نشون داده میشه مشکل از کجاست؟

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
مشکل از هارد ضعیف سرور شماست برای حل این مشکل لاگ access رو از کانفیگ حذف کنید داخل تنظیمات هست

**Comment by u-gayashan** [comment]
> The problem is the weak hard drive of your server. To solve this problem, remove the access log from the configuration. It is in the settings

Can you write in english?

**Comment by MHSanaei** [comment]
@u-gayashan just remove the access log
