### ISSUE TITLE
Can't Edit Xray Template In Panel!.

### ISSUE THREAD

**Issue by deepsm0ke** [MHSanaei/3x-ui#731]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi
I Can't Edit Xray Template In Panel!.

Please Check.

Tnx

### Version of 3x-ui

1.7.0

### x-ui log reports or xray log

---

**Comment by MHSanaei** [comment]
there is no problem
