### ISSUE TITLE
Spotify application

### ISSUE THREAD

**Issue by stingy64** [MHSanaei/3x-ui#735]
Hi.
I have installed warp and it's working just fine.
the problem is, when I want to use the spotify application, it doesn't work.
but everything is ok with the spotify web app player.
I think it might be something with the geosite.dat file.
any advice?

thanks.

**Comment by Sorenawr** [comment]
> USE WARP FOR ALL SITES AND IPS

How?

**Comment by MHSanaei** [comment]
#734

**Comment by stingy64** [comment]
The problem is resolved by checking the "Enable local DNS" and "Enable fake DNS" options in the V2rayng settings.

**Comment by Shm9220** [comment]
@stingy64 what about ios?
