### ISSUE TITLE
bug in Start after first use !

### ISSUE THREAD

**Issue by clockedzero** [MHSanaei/3x-ui#740]
وقتی کاربر به کلاینت متصل میشه
از بعد از اون اگه مجدد "شروع بعد از اولین استفاده" فعال بشه دیگه عمل نمیکنه و قبل از اتصال کاربر خودش تاریخ میزنه
این موضوع برای بار اول که کلاینت ساخته میشه بوجود نمیاد، اما پس از اولین اتصال به اون کلاینت دیگه "شروع بعد از اولین استفاده"پس از تنظیم عمل نمیکنه و وقتی از inbound خارج بشیم و مجدد به این صفحه برگردیم،  خودش تاریخ خورده
این مورد در ورژن 1.6.1 پنل بدون مشکل بوده است.

### Version of 3x-ui

1.7.0

**Comment by MHSanaei** [comment]
تست شد مشکلی وجود ندارد
