### ISSUE TITLE
⚠️ Please help to do this 🙏 - route to Multi outbounds by value of "Host" in request header 🙏

### ISSUE THREAD

**Issue by hosein-moayedi** [MHSanaei/3x-ui#742]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hey guys!
I want to do this and I know this should be work but I very tried to do this and failed!

env:
1 Iran server --- ir.mydomain.site,
1 Germany server --- de.mydomain.site,
1 Finlond server --- fl.mydomain.site

desc:
I want to give 2 vless configs to the client from the iran server with define one inbound inside of the iran server and all info of these two configs is same, like address, port, type, etc.. and there is just one thing that is differents. that is value of "Host" parameter on request header in WS or TCP that is the domain of my target server that iran server should route all client traffic to that target server.

ex: if the user selected config 1 with address: "ir.mydomain.site" and "Host"="fl.mydomain.site", he should connect to Iran server and rout to Finlond server through outbound of Finland that I defined in iran outbounds array.

This is example of my client config:
vless://81c78225-9470-44fb-9e79-e4137b9eb60d@**ir.mydomain.site**:443?type=tcp&path=%2F&**host=fl.mydomain.site**&headerType=http&security=none#VPN-409431573-169224425

This is Xray config file of my IRAN server but not working true, and all traffics is routed trough first index of outbounds array (germany server).

**I also tested "domainStrategy"="IPIfNonMatch" but not working! 😢**

What is the problem??
Please help me 🙏

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

```
{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "log": {
    "access": "./access.log",
    "error": "./error.log",
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "tag": "germany",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "de.mydomain.site",
            "port": 334,
            "users": [
              {
                "id": "390e5224-7822-4136-955b-fe95384542cc",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/",
          "headers": {}
        }
      }
    },
    {
      "tag": "finland",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "fl.mydomain.site",
            "port": 334,
            "users": [
              {
                "id": "390e5224-7822-4136-955b-fe95384542cc",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/",
          "headers": {}
        }
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "domain": [
          "geosite:category-ads-all",
          "ext:iran.dat:ads"
        ]
      },
      {
        "type": "field",
        "domain": [
          "fl.mydomain.site"
        ],
        "outboundTag": "finland"
      },
      {
        "type": "field",
        "domain": [
          "de.mydomain.site"
        ],
        "outboundTag": "germany"
      },
      {
        "type": "field",
        "domain": [
          "skyroom.online"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "direct"
      }
    ]
  },
  "stats": {}
}
```

**Comment by hosein-moayedi** [comment]
لطفا راهنمایی بفرمایید:
@alireza0 @MHSanaei

**Comment by alireza0** [comment]
توی نرم افزار xray-core نمیتونید با پارامتر های تنظیمات داخلی inbound ها عملیات routing رو دسته بندی کنید.
برای اینکار شما فقط میتونید از inbound-tag استفاده کنید.
یعنی یک یا چند inbound رو میتونید ( حتی با تنظیمات مسیریابی مثل دامنه و آدرس ) به سمت یک خروجی هدایت کنید.
```json
{
  "domainMatcher": "hybrid",
  "type": "field",
  "domain": ["baidu.com", "qq.com", "geosite:cn"],
  "ip": ["0.0.0.0/8", "10.0.0.0/8", "fc00::/7", "fe80::/10", "geoip:cn"],
  "port": "53,443,1000-2000",
  "sourcePort": "53,443,1000-2000",
  "network": "tcp",
  "source": ["10.0.0.1"],
  "user": ["love@xray.com"],
  "inboundTag": ["tag-vmess"],
  "protocol": ["http", "tls", "bittorrent"],
  "attrs": { ":method": "GET" },
  "outboundTag": "direct",
  "balancerTag": "balancer"
}
```
[منبع](https://xtls.github.io/en/config/routing.html#ruleobject)

**Comment by alireza0** [comment]
البته میتونید از طریق attrs یه سری حالت ها رو از اینباند بگیرید:

> Currently, only the inbound HTTP proxy sets this attribute.
Examples:
Detect HTTP GET：{":method": "GET"}
Detect HTTP Path：{":path": "/test"}"
Detect Content Type：{"accept": "text/html"}"

**Comment by hosein-moayedi** [comment]
> البته میتونید از طریق attrs یه سری حالت ها رو از اینباند بگیرید:
> 
> 
> 
> > Currently, only the inbound HTTP proxy sets this attribute.
> 
> Examples:
> 
> Detect HTTP GET：{":method": "GET"}
> 
> Detect HTTP Path：{":path": "/test"}"
> 
> Detect Content Type：{"accept": "text/html"}"

ممنونم از پاسختون مهندس جان
امام من خیلی از این پارامتر ها رو تست کردم و اصلا انگار روتینگم کار نمیکنه. مثلا از همین attrs و حتی از port هم استفاده کردم ولی اصلا انگار نه انگار

و یه چیز عجیب دیگری که هست این بود که وقتی من میام دو تا outbound برای سرور ایران میزارم که هر کدوم به یه سرور خارج اشاره میکنه انگار بشدت اختلال و پکت لاست توی کانکشن کلاینت به ایران به وجود میاد و اصلا باعث میشه کلی اختلال تو این کانکشن بیفته

ایا دلیل خاصی وجود داره؟ 

و یه سوال بسیار مهمی که داشتم که فکر میکنم یه جور ⚠️ باگ در پنل باشه این هست:

فرض کنید که من میخوام روی پنلم دو تا inbound از نوع vless که یکی از نوع tcp و اونیکی از نوع ws هست رو روی دو تا پرت جدا بسازم. میام برای یه کاربر مشخص یه پروفایل در هر دو inbound میسازم و میام هر دو را روی یک ای دی ساب قرار میدم که کلاینت با ادد کردن لینک ساب هر دو کانفیگ رو دریافت کنه

مشکل اصلی اینجا هست که وقتی من میخوام برای این کاربر فقط حجم ۱۰ گیگ رو مشخص کنم واقعا نمیدونم باید چه کار کنم چون حجم مصرفی بین inbound های یک پنل برای یک یوزر مشخص سینک نیست.
یا من باید بیام اون حجم رو تقسیم بر تعداد inbound ها کنم و تو هر کدوم یه حجمی بزارم که واقعا کار غیر منطقی هست.
ایا تدبیری برای این کار و سینک کردن حجم مصرفی کاربر در تمام in ound ها وجود دارد؟ ⚠️

**Comment by alireza0** [comment]
اگر کار نمیکنه، احتمال داره اولویت ها رو رعایت نکرده باشین.
ولی کلا با پارامتر هدر هاست نمیتونید روت انجام بدین.

در مورد تجمیع ترافیک، x-ui نمیتونه کاربر یکسان ایجاد کنه و ترافیک رو جمع کنه.
