### ISSUE TITLE
X-ui command doesn't work with debian trixie

### ISSUE THREAD

**Issue by parsahatami98** [MHSanaei/3x-ui#744]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello ;
I've installed the latest debian by accident when i was trying to install dnscrypt in debian
So now the linux is ; Debian GNU/Linux trixie/sid ; and x-ui command respond whit : Please use Debian 10 or higher 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/769
