### ISSUE TITLE
لطفا لطفا لطفا اگه کسی راه حلی یرای مشکل قفل شدن دیتابیس داره رو بگه

### ISSUE THREAD

**Issue by navid221** [MHSanaei/3x-ui#746]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام بنده با خطای database is locked جن روزه دارم سر وکله میزنم. حتی بکاپ گرفتم از دیتابیس و سرور رو ریبیلد کردم و از اول گنل رو نصب کردم بازم همین مشکل برقراره! لاگ سرور مدام همین ها رو تکرار میکنه

Jul 13 17:49:15 vm1382579 x-ui[944]: 2023/07/13 17:49:15 WARNING - add traffic failed: database is locked
Jul 13 17:49:21 vm1382579 x-ui[944]: 2023/07/13 17:49:21 WARNING - AddClientTraffic update data  database is locked
Jul 13 17:49:45 vm1382579 x-ui[944]: 2023/07/13 17:49:45 WARNING - add traffic failed: database is locked
Jul 13 17:49:50 vm1382579 x-ui[944]: 2023/07/13 17:49:50 WARNING - Error in disabling invalid clients: database is locked
Jul 13 17:49:50 vm1382579 x-ui[944]: 2023/07/13 17:49:50 WARNING - add client traffic failed: database is locked

مشکل از کجاست؟

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
مشکل از هارد ضعیف شماست برای حل این مشکل لاگ access رو از کانفیگ حذف کنید داخل تنظیمات هست

**Comment by arashammm** [comment]
> مشکل از هارد ضعیف شماست برای حل این مشکل لاگ access رو از کانفیگ حذف کنید داخل تنظیمات هست

والا ما این قسمت هم غیرفعال کردیم باز داره اتفاق می افته این مشکل. لطفا یه نفر یه راهکار عملی ارائه بده چون همیشه باید پنل رو ری استارت کرد تا مشکل حل بشه و هیچ راه حلی وجود نداره
