### ISSUE TITLE
مشکل حریم خصوصی

### ISSUE THREAD

**Issue by sevSnape2000** [MHSanaei/3x-ui#749]
با سلام و تشکر
در ورژن جدید فایلی به نام accessp.log اضافه شده که لاگ تمامی سایت هایی که کاربران می بینند رو ذخیره میکنه. این فایل به روز میشه و مانند ورژن های قبل فقط وضعیت لحظه ای رو نگه نمی داره که این موضوع شدیدا مشکلات عدم رعایت حریم خصوصی رو در پی داره. چرا این اتفاق افتاده؟

**Comment by MHSanaei** [comment]
این فایل در تمام ورژن ها بود در ورژن اخر حذف خودکار برداشته شده در صورتی که نیازی به این لاگ ندارید میتونید از صفحه تنظیمات قسمت کانفیگ acccess log رو حذف کنید

**Comment by sevSnape2000** [comment]
موضوع اینه که چرا باید کسی به این فایل «نیاز» داشته باشه؟ ظاهراً مشخصه که هیچ توجیه فنی هم نداره. مسلما متوجه نگرانی بنده هستید و پاسختون «اگه نمیخای میتونی استفاده نکنی» نیست.
