### ISSUE TITLE
مشکل تماس با واتس اپ

### ISSUE THREAD

**Issue by amirfxfx** [MHSanaei/3x-ui#751]
سلام
هنگام تماس در واتس اپ روی connecting می مونه و وصل نمیشه.
لطفاً کسی می تونه راهنمایی کنه؟
ممنون

**Comment by Samiiix** [comment]
با برنامه SPEEDTEST یه تست سرعت بگیرین، اگه جیتر بالا باشه، این مشکل رو خواهید داشت.
جیتر ایده آل باید بین 5 تا 15 باشه.

**Comment by amirfxfx** [comment]
گرفتم و ۱۰ms هست
ولی وصل نمیشه
کانفیگ خاصی باید بزنم؟

**Comment by Samiiix** [comment]
اگه جیتر شما 10 هست پس مشکل از سمت شما نیست. از سمت دیگر تماس هست که کانکشن فعالشون جیتر بالایی داره. در کل برای حالت Connecting واتس اپ جیتر مهمه که برای شما خیلی خوبه.

**Comment by amirfxfx** [comment]
من با خارج از ایران تماس می گیرم که اونها از vpn استفاده نمی کنند و در ضمن با فیلتر شکن مثلاً windscribe خیلی راحت تماس واتس اپ دارم ولی با v2ray همیشه روی connecting می مونه.
سرعت و جیتر خیلی خوب هم دارم ولی گیج شدم و نمی دونم چیکار کنم 
لطفاً کمکم کنید.
