### ISSUE TITLE
سرور مناسب 

### ISSUE THREAD

**Issue by alirezazarghi** [MHSanaei/3x-ui#752]
با سلام 
من چندین هاست تهیه کردم و روی اقدام به نصب کردم
مشکل اینجاست که بسیار کند هستند
مشخصات آخرین هاست :
Cpu : 2
Ram: 4
Os:ubuntu 20.04 lts
لطفاً من را راهنمایی کنید

**Comment by Samiiix** [comment]
درود
رفیق کاری به مشخصات نداره چون این سیستم اصلا سخت افزار خاصی مصرف نمیکنه.
کند بودن به خاطر همون سروری هست که تهیه کردی، پورت شبکه محدودی داره و از سرویس دهنده خوبی نیست به احتمال زیاد. از سایت های ایرانی خرید نکن.

**Comment by alirezazarghi** [comment]
با سلام من به چه نحوی می توان پورت شبکه را تست کنم
از سایتهای ایرانی هم خریداری نکردم

**Comment by Samiiix** [comment]
> با سلام من به چه نحوی می توان پورت شبکه را تست کنم از سایتهای ایرانی هم خریداری نکردم

درود
معمولا توی مشخصات سرور در صفحه معرفی پلن های موجود نوشته میشه.
برای تست سرعت سرور، Speedtest-cli رو نصب کنید و با کامند speedtest میتونید حداکثر سرعت آپلود و دانلود سرور خودتون رو ببینید. (برای نصب همین عبارت رو گوگل کنید
البته در نظر داشته باشید که بعضی از کشور ها هستن که برای ما سرعت پایینی دارن (مثلا سرور های آمریکا) اما در کل، آلمان، هلند، سوئد، فرانسه و انگلیس (به همین ترتیب که نوشته شده) سرعت های بهتری رو دارن.

**Comment by alirezazarghi** [comment]
با تشکر از شما ،من تست رو انجام دادم روی سرور عالیه و در زمان وصل شدن خیلی افت می کنه
آیا امکان داره بابت ساخت کانفیگ ها باشه

**Comment by Samiiix** [comment]
> با تشکر از شما ،من تست رو انجام دادم روی سرور عالیه و در زمان وصل شدن خیلی افت می کنه آیا امکان داره بابت ساخت کانفیگ ها باشه

ساخت کانفیگ ها نمیتونه تاثیری توی سرعت داشته باشه.
با تمامی اینترنت ها این مشکل رو دارین یا سرویس دهنده خاصی فقط؟

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
