### ISSUE TITLE
ban duration in ip limit management

### ISSUE THREAD

**Issue by clockedzero** [MHSanaei/3x-ui#753]
اگر در محدودیت کلاینت 1 تعریف شده باشد و  آی پی دوم توسط fail2ban در لیست بن قرار بگیرد، پس از طی مدت زمان تعیین شده در قسمت ban duration (مثلا 2 دقیقه) چه اتفاقی می افتد؟ دسترسی آی پی دوم مجاز میشود مجدد؟ 

ممنون میشم اگر کسی از عملکرد  آن اطلاع دارد توضیح بدهد.

**Comment by MHSanaei** [comment]
بله ای پی بن شده 2باره امکان اتصال خواهد داشت
