### ISSUE TITLE
every 10 seconds cpu high usage

### ISSUE THREAD

**Issue by bmv2020** [MHSanaei/3x-ui#755]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

When I updated to version 1.7.0 and investigate the CPU usage , I noticed that cpu usage go to the roof in every 10 seconds for 2 seconds and then fall down. I down grade to v 1.61. and the problem solved. so I think some feature that added in 1.7.0 caused this issue and I guess the IP limit feature is the reason of it.
وقتی برنامه را به نسخه 1.7.0 آپدیت کردم و میزان استفاده از CPU را بررسی کردم، متوجه شدم که مصرف cpu در هر 10 ثانیه به مدت 2 ثانیه صد در صد و سپس پایین می آید. سپس نسخه را به 1.61 برگرداندم و مشکل حل شد بنابراین فکر میکنم برخی از ویژگی های اضافه شده در 1.7.0 باعث این مشکل شده است و حدس می زنم مربوط به ویژگی محدودیت تعداد IP همزمان متصل باشد.

### Version of 3x-ui

<details>

```console
1.7.0
```

</details>

### x-ui log reports or xray log

<details>

```console
no log
```

</details>

**Comment by sbh96** [comment]
برای منم این مشکل داره

**Comment by Samiiix** [comment]
با کامند htop یا top میزان مصرف منابع رو اسکرین بگیرین و ارسال کنین. مخصوصا زمانی که روی high usage میره

**Comment by neon-bartmoss** [comment]
برای منم این مشکل رو داره  نسخه بر برگردوندم به 1.61 مشکل فعلا حل شده

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
