### ISSUE TITLE
ارور 404 هنگام پاک کردن یوزر

### ISSUE THREAD

**Issue by 9390067696** [MHSanaei/3x-ui#757]
سلام وقت بخیر
ما یه کلاینت زیر مجوعه اینباند اشتباه ساختیم و ایدی نداره 
حالا پنل غیر فعال شده و ارور داره
و موقع پاک یا دیسیبل کردن اون یوزر این ارور میده
Error: Request failed with status code 404

**Comment by Samiiix** [comment]
به صورت دستی از توی فایل دیتابیس حذفش کنید بعد پنل رو ریستارت کنید.
قبلش حتما بک آپ بگیرید از دیتابیس

**Comment by 9390067696** [comment]
با چه برنامه ای باز کنم دیتابیسش رو؟

**Comment by Samiiix** [comment]
> با چه برنامه ای باز کنم دیتابیسش رو؟

RazorSQL
Notepad ++
یا هر برنامه دیگه ای که باهاش راحت تر هستین کار کنین

**Comment by MHSanaei** [comment]
به صورت دستی حذف کنید با برنامه 
DB Browser (SQLite)
