### ISSUE TITLE
shadowsocks protocol dosn't have any inbound option to choose

### ISSUE THREAD

**Issue by Parto451** [MHSanaei/3x-ui#760]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I guess there is something wrong in 3x-ui panel UI, When I choose "shadowsocks" protocol, there is no "Transmission" option to choose, therefore it's not possible to use shadowsocks with "ws" transmission.
 
![3x-ui shadow bug](https://github.com/MHSanaei/3x-ui/assets/131576965/8611cead-df6e-40e6-87ac-7e2ac526c5bb)

### Version of 3x-ui

<details>

```console
# 1.7.0
```

</details>

### x-ui log reports or xray log

<details>

```console
# no need to log report!
```

</details>

**Comment by MHSanaei** [comment]
use v1.7.1
done
