### ISSUE TITLE
ارور403هنگام ورود به سایت گوگل بارد

### ISSUE THREAD

**Issue by rezakhosh78** [MHSanaei/3x-ui#761]
باسلام هنگام ورود به سایت گوگل بارد با ارور403 مواجه میشم.تو پنل ipv4 هم برای google روشن هست.راهی برای این مشکل هست؟

**Comment by hawshemi** [comment]
Use WARP+ for google.

**Comment by MHSanaei** [comment]
ipv4 only or warp
