### ISSUE TITLE
مشکل در لاگ و کند شدن شدید سرور

### ISSUE THREAD

**Issue by roozbehsat** [MHSanaei/3x-ui#766]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام. امروز خیلی سیستمم کند شده بود کلا هم 15 یوزر دارم. رفتم لاگ x-ui رو چک کردک که با چنین صحنه ای مواجه شدم. کسی میدونه چرا؟ ممنون میشم راهنمایی کنین که مشکل از کجاست...
![Screenshot (275)](https://github.com/MHSanaei/3x-ui/assets/119633123/100dd688-d2ad-4b13-885f-0d3d6999e3a2)

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by roozbehsat** [comment]
میشه راهنماییم کنین که چه جوری ریورت کنم؟

**Comment by Samiiix** [comment]
> دانگرید کردک به 1.6.1 ولی بازم همونجوریه!!!! 

باید ببینید چه پروسه ای داره از دیتابیس استفاده میکنه که نمیزاره تغییری روش ایجاد بشه.

کامند های زیر رو به ترتیب  وارد کنید و شات ها رو ارسال کنید تا چک کنم
`$ fuser /etc/x-ui/x-ui.db`
`$ htop`

**Comment by roozbehsat** [comment]
سلام مجدد... اسکرین خدمت شما:
![Screenshot (278)](https://github.com/MHSanaei/3x-ui/assets/119633123/38fba7b9-62e8-45b8-b8fa-19b7bcf64b9a)
![Screenshot (277)](https://github.com/MHSanaei/3x-ui/assets/119633123/b845e1ba-8b51-4e7f-a0d3-dd482fff208a)

**Comment by Samiiix** [comment]
از فایل x-ui.db که توی مسیر قبلی گفتم، بک آپ بگیرید. یه نسخه هم از طریق خود پنل اسکریپت بک آپ بگیرید.
کامند های زیر رو یه بار اجرا کنید، نتیجه رو بهم بگید
`kill -9 553`
`x-ui restart`

**Comment by roozbehsat** [comment]
ممنون بابت راهنماییتون ... انجام دادم اون 553 هم عوض شده به 37415 ولی متاسفانه بازم همونجوریه....
![Screenshot (279)](https://github.com/MHSanaei/3x-ui/assets/119633123/345d0c8a-aaa0-4c63-a412-d21b683b1721)

**Comment by MHSanaei** [comment]
این مشکل در سرور های که i/o  ضعیفی دارند اتفاق میفتاد راه حل این است که فشار رو با استفاده نکردن از iplimit و موارد مشابه مثل حذف access log از کانفیگ ایکس ری کمتر کرد که این اتفاق رخ ندهد

**Comment by roozbehsat** [comment]
ممنون جناب سنایی بابت پاسخگویی تون... فقط زحمت میکشی راهنمایی کنین که چه طوری access log رو از کانفیگ ایکس ری حذف کنم؟

**Comment by MHSanaei** [comment]
این خط رو حذف کن 
 "access": "./access.log",
 داخل Complete Template
