### ISSUE TITLE
Problem with installing and running x-ui on Amazon Lightsail instances

### ISSUE THREAD

**Issue by OnceUponATimeInAmerica** [MHSanaei/3x-ui#769]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

Hello and many thanks for your efforts.

When trying to install/upate the x-ui (yours and others)  panel on some Amazon (Lightsail) Debian 11 instances the x-ui utility exits with `Please use Debian 10 or higher`.

I think there might be some problems in your [version detection code](https://github.com/MHSanaei/3x-ui/blob/65e35c17113d2f3cee06f583b28cb4b762ff186a/install.sh#L36)  which might be that it is not general enough to cover all cases.

For reference, here are contents of my stock (I did NOT modify it in any way)   `/etc/os-release ` file from 2 of my Amazon (Debian 11) instances on which x-ui refuses to run/update:   

```
PRETTY_NAME="Debian GNU/Linux trixie/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=trixie
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

If I manually add the `version_id="11" `line/var to it, then the x-ui will work ok. But I think the version detection code in install script, needs to be more robust.

Thank you.

### Version of 3x-ui

<details>
Version 1.7.1 and earlier
```console
```

</details>

### x-ui log reports or xray log

<details>

```console
```

</details>

**Comment by MHSanaei** [comment]
version_id should be on os-release, or it won't let you install it.
