### ISSUE TITLE
Accept proxy protocol

### ISSUE THREAD

**Issue by arsham6ix** [MHSanaei/3x-ui#773]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

درود خدمت شما ، ممنون بابت اپدیت پنل ، راجب مسئله Accept proxy protocol باید بگم که من جیسون رو چک کردم و فهمیدم که یک قسمت جای درستی قرار نگرفته و خواستم گزارش بدم بابت ایمیل قبلی که زحمت کشیدید بهم دادید.

اگه کد های جیسون رو چک کنید میبینید که قسمت مورد نظر به بلاک grpcSettings در grpc و در h2 به بلاک httpSettings اضافه شده که این ۲ تا بلاک هم زیر شاخه streamSettings هستند 👇
``
"sockopt": {
            "acceptProxyProtocol": false
}
``
بلاک sockopt خود مختار هست و نباید به این بلاک ها که معرفی کردم اضافه بشن ، باید به خود streamSettings اضافه بشه ، برای نمونه هم من ۲ تا عکس میزارم زیر این متن

![photo_2023-07-18_13-08-28](https://github.com/MHSanaei/3x-ui/assets/89599368/cba52e8c-05f7-4d26-80a9-40c9d0fb85a2)

![photo_2023-07-18_13-07-32](https://github.com/MHSanaei/3x-ui/assets/89599368/0b148b4f-be00-4425-a1b2-52ec34f64ffd)

### Version of 3x-ui

1.7.1

### x-ui log reports or xray log

..

**Comment by MHSanaei** [comment]
done
