### ISSUE TITLE
قطع و وصل شدن سرور

### ISSUE THREAD

**Issue by Mojtabaaba** [MHSanaei/3x-ui#774]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

دوستان سرور هی قطع و وصل میشه و این خطا رو میده مشکل از چیه؟
![Screenshot_20230718-233645_Chrome](https://github.com/MHSanaei/3x-ui/assets/139058161/7882b257-abb6-4f58-b959-bb170cb74857)
.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NoRRt** [comment]
ورژن xray رو به 1.8.3 تغییر بدید.

**Comment by MHSanaei** [comment]
Ipv6 
شما مشکل داره اید با ست کردن dns در سرور مشکل حل شه اگر حل نشد ipv6 رو غیرفعال کنید
