### ISSUE TITLE
مشکل نصب هنگام اپدیت به نسخه 1.7.1

### ISSUE THREAD

**Issue by SahandSOne** [MHSanaei/3x-ui#777]
با سلام.
هنگام اپگرید از نسخه 1.7 به نسخه 1.7.1 این قسمت میمونه ... 
ممنون میشم راهنماییم کنید 

![last](https://github.com/MHSanaei/3x-ui/assets/134105392/9310a729-3c3e-465a-b060-14857c786a2e)

**Comment by MHSanaei** [comment]
مشکل از سرور شماست

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/677#issuecomment-1614484233
