### ISSUE TITLE
ip limit bug

### ISSUE THREAD

**Issue by AmoAlireza** [MHSanaei/3x-ui#778]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام
ورژن جدید 1.7.1 یه سری باگ داره اولیش اینه که نمیشه تایم بن تغیر داد و تست کردم بعد چند ثانیه از بن در میاد.
![1](https://github.com/MHSanaei/3x-ui/assets/79990596/d349c6ea-12c3-4b89-aab8-b0161037ed7d)

لاگ ban و unbanned قسمت ip limit دیگه آپدیت نمیشه.
کلا fail2ban هم باگ خورده.
![Capture](https://github.com/MHSanaei/3x-ui/assets/79990596/e78d413b-dfc5-4d0a-8e84-e186268d8d7d)

موقع unban کردن هم میگه این فایل 3x-ipl وجود نداره ولی با این حال میگه unban شدن.
![2](https://github.com/MHSanaei/3x-ui/assets/79990596/80673103-e122-42ae-ac34-9dccdf530906)

### Version of 3x-ui

1.7.1

### x-ui log reports or xray log

​

**Comment by MHSanaei** [comment]
اگدر اپدیت ۱.۷.۱ به خاطر تغییرات جدید کانفیگ باید fail2ban رو یکبار کامل حذف کنید و مجدد نصب کنید

**Comment by AmoAlireza** [comment]
بله انجام دادم ولی باز همین مشکلات روبرو میشم.
@MHSanaei

**Comment by MHSanaei** [comment]
فردا تست میکنم این جز موارد تغییرات مهندس حمید هست که من تست نکردم 
@hamid-gh98

**Comment by hamid-gh98** [comment]
درود
ممنونم از گزارش شما.
میتونین فایل x-ui رو اپدیت کنید و تست کنید

```sh
wget -O /usr/bin/x-ui https://raw.githubusercontent.com/MHSanaei/3x-ui/main/x-ui.sh
chmod +x /usr/bin/x-ui
```

**Comment by AmoAlireza** [comment]
تشکر بابت آپدیت.
متاسفانه باگ های آپدیت نشدن لاگ و unban شدن سریع بعد از چند ثانیه و مشکل سرویس fail2ban(service fail2ban status) هنوز وجود داره من برای احتیاط از اول ip limit حذف و نصب کردم ولی متاسفانه مشکل هنوز هست ولی آپدیت کردن تایم unban کردن درست شده و پیام Created Ip Limit jail files with a bantime of 10 minutes. میده همچنین داخل پنل UI لاگ ای پی کاربران به شکل زیر شده:
![1](https://github.com/MHSanaei/3x-ui/assets/79990596/6a1a21b9-384e-4a77-b7f3-5dafe6c3c75c)

@hamid-gh98

**Comment by hamid-gh98** [comment]
> مشکل سرویس fail2ban(service fail2ban status) هنوز وجود داره

چه مشکلی در سرویس fail2ban هست؟ start نمیشه؟ یا مشکل دیگه‌ای هست

**Comment by hamid-gh98** [comment]
@AmoAlireza لظفا دوباره نصب کنید
چندین بار تست کردم الان درسته

![image](https://github.com/MHSanaei/3x-ui/assets/70919649/dae77d3c-59c6-49df-92f5-ce368240d3cd)

**Comment by AmoAlireza** [comment]
> @AmoAlireza لظفا دوباره نصب کنید چندین بار تست کردم الان درسته
> 
> ![image](https://user-images.githubusercontent.com/70919649/254540022-dae77d3c-59c6-49df-92f5-ce368240d3cd.png)

از قبل داشتید خودتون یا x-ui شما نصب تازس؟

**Comment by hamid-gh98** [comment]
> از قبل داشتید خودتون یا x-ui شما نصب تازس؟

همین الان روی سرور جدید نصب کردم

**Comment by AmoAlireza** [comment]
حمید جان این مشکل اینگار مربوط به دیتا بیس هستش چون با حذف و نصب x-ui و fail2ban هم حل نشد.
کار های که انجام دادم اول دیتا بیس کپی کردم و کلا x-ui پاک کردم با کامند خودش بعدش rm /usr/bin/x-ui -f زدم و سرور ریبوت کردم بعد از 
 اون fail2ban نصب کردم اون دیتا بیس قبلی گزاشتم ولی هنوز مشکلات وجود دارن.

**Comment by MHSanaei** [comment]
@AmoAlireza 
یکبار با این دستور fail2ban رو حذف کنید و مجدد از طریق منو نصب کنید و سپس status رو چک کنید 
```
rm -rf /etc/fail2ban
apt purge fail2ban -y
```

`service fail2ban status`

**Comment by jeet8200** [comment]
looks like it ok for me
![image](https://github.com/MHSanaei/3x-ui/assets/135669873/80279bc2-d63e-4adc-b670-60253134a608)

**Comment by AmoAlireza** [comment]
تشکر از شما آقا حمید و حسین جان.
مشکل برطرف شد ولی برای من هنوز اون مشکل اینکه سریع unban میشدن و لاگ بن و unban شده ها خالی بود وجود داشت که من برای همه کاربرا یکبار ای پی لیمیت برداشتم و 0 گزاشتم و x-ui پاک کردم و دوباره نصب کردم با fail2ban و با این روش جواب داد و درست شد.

**Comment by MHSanaei** [comment]
[fail2ban status + apt-get purge](https://github.com/MHSanaei/3x-ui/commit/0dd0ba717fe88814ce2053c8b6019278fde4bed5)

```
wget -O /usr/bin/x-ui https://raw.githubusercontent.com/MHSanaei/3x-ui/main/x-ui.sh
chmod +x /usr/bin/x-ui
```

**Comment by Mikailpishi** [comment]
رو ورژن جدید هم میزنه fail و ران نمیشه fail2ban 
ورژن 1.7.5
