### ISSUE TITLE
عدم نمایش ترافیک استفاده شده کلاینتها

### ISSUE THREAD

**Issue by Parsa-n** [MHSanaei/3x-ui#781]
سلام. داخل پنل من باگ دارم که ترافیک کلاینتهارو نشون نمیده و همه رو 0 زده برام. ولی ترافیک خوده اکانت یوزری که میسازم اوکیه و نشون میده. کلاینت اد میکنم نشون نمیده چقدر استفاده شده. ممنون میشم راهنمایی کنید

**Comment by MHSanaei** [comment]
برید داخل تنظیمات دکمه ریست رو بزنید

**Comment by Parsa-n** [comment]
> برید داخل تنظیمات دکمه ریست رو بزنید

همه چیو ریست میکنم بازم فرقی نمیکنه. کلا کلاینت های زیرمجموعه کانفیگ اکانتا ترافیکشونو نشون نمیده و همشون رو 0 میزنه برام.

**Comment by Parsa-n** [comment]
![image](https://github.com/MHSanaei/3x-ui/assets/77966472/44268f41-fe3e-40db-b271-ad6637343b94)
