### ISSUE TITLE
عدم نمایش تزافیک کلاینتها

### ISSUE THREAD

**Issue by Parsa-n** [MHSanaei/3x-ui#782]
سلام. داخل پنل من باگ دارم که ترافیک کلاینتهارو نشون نمیده و همه رو 0 زده برام. ولی ترافیک خوده اکانت یوزری که میسازم اوکیه و نشون میده. کلاینت اد میکنم نشون نمیده چقدر استفاده شده. ممنون میشم راهنمایی کنید

![254517598-44268f41-fe3e-40db-b271-ad6637343b94](https://github.com/MHSanaei/3x-ui/assets/77966472/2c91309e-8b6a-494f-9d5c-4177dc075a42)

**Comment by MHSanaei** [comment]
برید داخل تنظیمات و دکمه reset to default رو بزنید تا تنظیمات کانفیگ شما به حالت اولیه دربیاد چرا که این مشکل به خاطر این به وجود میاد که کانفیگ تنظیمات xray دستکاری شده باشه
