### ISSUE TITLE
Ip limit duration error

### ISSUE THREAD

**Issue by LoneStalkerz** [MHSanaei/3x-ui#783]
Hi, i just installed the iplimit command but as im going to change the ban time this error shows up, how can i solve it? Thanks 
![IMG_9900](https://github.com/MHSanaei/3x-ui/assets/131772239/abed90a5-17d7-4d09-98ba-f766e2ee16bb)

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/778#issuecomment-1641714982
fixed

**Comment by LoneStalkerz** [comment]
Good job, appreciate that
