### ISSUE TITLE
تست عملکرد Direct Country Configs

### ISSUE THREAD

**Issue by ir00ni** [MHSanaei/3x-ui#784]
چطور عملکرد Direct Country Configs رو تست کنم؟
بنظرم کار این تنظیمات اینه که ترافیک سایت های ایرانی و ای پی های ایرانی از سرور خارج رد نمیکنه و مستقیم وصل میشه به سایت ها و ای پی های ایران

یه سایت ایرانی که ای پی رو نمایش بده لازمه که واردش بشم و ای پی اصلی (بدون فیلترشکن) رو نشون بده
چنین سایتی معرفی کنید

چندتا سایت ایرانی که این ای پی رو نمایش میدن تست کردم، ای پی پشت فیلترشکن رو نمایش میداد

**Comment by MHSanaei** [comment]
#668

**Comment by ir00ni** [comment]
پس این مورد برای تانل دکومودور هست و من اشتباه برداشت کردم
