### ISSUE TITLE
X-ui Service Won't Run in New Docker v1.7.1

### ISSUE THREAD

**Issue by AliBelali** [MHSanaei/3x-ui#785]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [ ] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi
x-ui service won't exec after running new docker v1.7.1 ; It seems DockerEntry.sh should run it but it won't. DockerEntry.sh just runs fail2ban and not the x-ui.
Please if possible add x-ui command to docker. old versions does not support x-ui command in docker shell.
thanks

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by cetygamer** [comment]
Hi.

I faced the same issue and managed to fix it by editing DockerEntrypoint.sh and re-building docker image from source.

I changed this line:

```bash
fail2ban-client -x -f start
```

to this (& at the end):

```bash
fail2ban-client -x -f start &
```

**Comment by hamid-gh98** [comment]
Please build the docker manually and test it now.
@AliBelali @cetygamer

**Comment by cetygamer** [comment]
@hamid-gh98, I quickly verified commit https://github.com/MHSanaei/3x-ui/commit/2f05d4960e851556e13e157c4231a71410f8190b, seems OK.

**Comment by AliBelali** [comment]
@hamid-gh98 Thanks a lot, after new commit it works fine.

**Comment by hamid-gh98** [comment]
@MHSanaei do you mind rebuild the docker for version v1.7.1?
