### ISSUE TITLE
نمایش میزان باقیمانده حجم و زمان در بخش remark

### ISSUE THREAD

**Issue by ir00ni** [MHSanaei/3x-ui#786]
اگر مانند پنل مرزبان بشه میزان باقیمانده حجم و زمان در بخش remark نمایش داد عالیه
دیگه کاربر از تو برنامه v2rayng یا NV یا ... میتونه راحت میزان باقیمانده حجم و زمان رو ببینه

**Comment by uzer0098** [comment]
این موارد را چطور میشه برای کاربر در برنامه سمت کلاینت نمایش داد؟
شورت کدش چیه؟
