### ISSUE TITLE
قابلیت تفکیک ترافیک داخلی و خارجی

### ISSUE THREAD

**Issue by ir00ni** [MHSanaei/3x-ui#787]
**مستقیم کردن ترافیک وبسایت های داخلی**
این قابلیت به اینصورت هست که اگر کاربر بخواد سایت ها یا ای پی های ایرانی رو بازدید کنه به پنل وصل نشه و مستقیم با ای پی خودش بره تو اون سایتا و اگر خواست از سایت ها و ای پی های خارج از ایران بازدید کنه بیاد به پنل وصل بشه

این قابلیت تو تنظیمات برنامه های سمت کلاینت مثل v2rayng با یکسری روتینگ قابل پیاده سازی هست
اگه روی پنل و سمت سرور قبل پیاده سازی باشه عالیه

یک ویدیو در این رابطه در یوتیوب
https://www.youtube.com/watch?v=PIaUHsnzR-g

علت و مزایا:
اولا با توجه به اینکه برای جلوگیری از فیلترشدن ای پی و دامین مجبور به تانل و استفاده از سرورهای داخلی هستیم و سرورهای داخلی نیز محدودیت ترافیک دارند، تفکیک ترافیک بازدید داخلی از خارجی باعث صرفه جویی زیادی در ترافیک مصرفی سرور ایران و کاهش هزینه ها خواهد داشت.
دوما سرعت بارگزاری یک سایت داخلی بدلیل اینکه به سایت خارج متصل نمیشه که از اونجا مجدد به سایت داخل وصل بشه بشدت افزایش پیدا میکنه 
سوم اینکه با این روش دیگه نیاز به بستن سایت ها و ای پی های ایران نیست ، جون یوزر با ای پی خودش وارد سایت ها و ای پی ایران میشه و خطر لو رفتن ای پی و دامین فیلترشکن هم از بین میره

**Comment by misagh72** [comment]
سمت سرور نمیشه دوست عزیز

**Comment by MHSanaei** [comment]
اگر مستقیم وصل باشید فقط میشه بلاک کرد 
اگر تانل کرده باشید میشه ترافیک های خاصی مثلا سایت های داخلی رو به سرور اول که همون ایران منظور هست فرستاد در این حالت گزینه های لازم داخل تنظیمات هست 
حالت دیگه ای هم هست که همون مستقیم وصل باشید ولی سایت های ایرانی رو بلاک کنید و از داخل اپ کلاینت ترافیک داخلی رو دایرکت کنید
