### ISSUE TITLE
کاربرا

### ISSUE THREAD

**Issue by morrovat** [MHSanaei/3x-ui#788]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

صفه کاربرا بالا نمیاد و خطای که پیوست کردم رو میده   

### Version of 3x-ui

Jul 19 22:50:13 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:13 MSK 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
Jul 19 22:50:13 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:13 MSK 2023] ERROR Retrying to get updates in 8s
Jul 19 22:50:24 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:24 MSK 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
Jul 19 22:50:24 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:24 MSK 2023] ERROR Retrying to get updates in 8s
Jul 19 22:50:31 abject-agreement.aeza.network x-ui[1044]: 2023/07/19 22:50:31 WARNING - access.log doesn't exist in your config.json
Jul 19 22:50:35 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:35 MSK 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
Jul 19 22:50:35 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:35 MSK 2023] ERROR Retrying to get updates in 8s
Jul 19 22:50:47 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:47 MSK 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
Jul 19 22:50:47 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:47 MSK 2023] ERROR Retrying to get updates in 8s
Jul 19 22:50:51 abject-agreement.aeza.network x-ui[1044]: 2023/07/19 22:50:51 WARNING - access.log doesn't exist in your config.json
Jul 19 22:50:58 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:58 MSK 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
Jul 19 22:50:58 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:58 MSK 2023] ERROR Retrying to get updates in 8s
Jul 19 22:51:09 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:51:09 MSK 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
Jul 19 22:51:09 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:51:09 MSK 2023] ERROR Retrying to get updates in 8s
Jul 19 22:51:11 abject-agreement.aeza.network x-ui[1044]: 2023/07/19 22:51:11 WARNING - access.log doesn't exist in your config.json
Jul 19 22:51:20 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:51:20 MSK 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
Jul 19 22:51:20 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:51:20 MSK 2023] ERROR Retrying to get updates in 8s
Jul 19 22:51:31 abject-agreement.aeza.network x-ui[1044]: 2023/07/19 22:51:31 WARNING - access.log doesn't exist in your config.json
Jul 19 22:51:31 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:51:31 MSK 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
Jul 19 22:51:31 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:51:31 MSK 2023] ERROR Retrying to get updates in 8s

### x-ui log reports or xray log

Jul 19 22:50:13 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:13 MSK 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
Jul 19 22:50:13 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:13 MSK 2023] ERROR Retrying to get updates in 8s
Jul 19 22:50:24 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:24 MSK 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
Jul 19 22:50:24 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:24 MSK 2023] ERROR Retrying to get updates in 8s
Jul 19 22:50:31 abject-agreement.aeza.network x-ui[1044]: 2023/07/19 22:50:31 WARNING - access.log doesn't exist in your config.json
Jul 19 22:50:35 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:35 MSK 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
Jul 19 22:50:35 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:35 MSK 2023] ERROR Retrying to get updates in 8s
Jul 19 22:50:47 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:47 MSK 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
Jul 19 22:50:47 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:47 MSK 2023] ERROR Retrying to get updates in 8s
Jul 19 22:50:51 abject-agreement.aeza.network x-ui[1044]: 2023/07/19 22:50:51 WARNING - access.log doesn't exist in your config.json
Jul 19 22:50:58 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:58 MSK 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
Jul 19 22:50:58 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:50:58 MSK 2023] ERROR Retrying to get updates in 8s
Jul 19 22:51:09 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:51:09 MSK 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
Jul 19 22:51:09 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:51:09 MSK 2023] ERROR Retrying to get updates in 8s
Jul 19 22:51:11 abject-agreement.aeza.network x-ui[1044]: 2023/07/19 22:51:11 WARNING - access.log doesn't exist in your config.json
Jul 19 22:51:20 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:51:20 MSK 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
Jul 19 22:51:20 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:51:20 MSK 2023] ERROR Retrying to get updates in 8s
Jul 19 22:51:31 abject-agreement.aeza.network x-ui[1044]: 2023/07/19 22:51:31 WARNING - access.log doesn't exist in your config.json
Jul 19 22:51:31 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:51:31 MSK 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
Jul 19 22:51:31 abject-agreement.aeza.network x-ui[1044]: [Wed Jul 19 22:51:31 MSK 2023] ERROR Retrying to get updates in 8s

**Comment by MHSanaei** [comment]
داخل این لاگ مشخص نیست دلیل بالا نیومد چیه فقط یه ارور دیگه دارید 
access.log doesn't exist in your config.json
که یعنی iplimit فعال دارید ولی access log رو داخل کانفیگ xray ندارید که باید برید داخل تنظیمات و دکمه reset to default رو بزنید

**Comment by morrovat** [comment]
ریست رو زدم بازم نمیاد

**Comment by MHSanaei** [comment]
قسمت اینباند ها باید دیتابیس رو چک کنی ببینی مشکلش چیه

**Comment by morrovat** [comment]
سرویس جدید ساخته بودم یهو اون رفت قسمت کاربرا چیزی نمیاد دیگه

**Comment by morrovat** [comment]
![image](https://github.com/MHSanaei/3x-ui/assets/138860891/7758b257-6f9f-468c-a4ea-0e5111c52b46)

**Comment by morrovat** [comment]
data:application/text;charset=utf-8,Jul%2019%2023%3A01%3A13%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A01%3A13%20MSK%202023%5D%20ERROR%20Getting%20updates%3A%20telego%3A%20getUpdates()%3A%20api%3A%20409%20%22Conflict%3A%20terminated%20by%20other%20getUpdates%20request%3B%20make%20sure%20that%20only%20one%20bot%20instance%20is%20running%22%0AJul%2019%2023%3A01%3A13%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A01%3A13%20MSK%202023%5D%20ERROR%20Retrying%20to%20get%20updates%20in%208s%0AJul%2019%2023%3A01%3A24%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A01%3A24%20MSK%202023%5D%20ERROR%20Getting%20updates%3A%20telego%3A%20getUpdates()%3A%20api%3A%20409%20%22Conflict%3A%20terminated%20by%20other%20getUpdates%20request%3B%20make%20sure%20that%20only%20one%20bot%20instance%20is%20running%22%0AJul%2019%2023%3A01%3A24%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A01%3A24%20MSK%202023%5D%20ERROR%20Retrying%20to%20get%20updates%20in%208s%0AJul%2019%2023%3A01%3A35%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A01%3A35%20MSK%202023%5D%20ERROR%20Getting%20updates%3A%20telego%3A%20getUpdates()%3A%20api%3A%20409%20%22Conflict%3A%20terminated%20by%20other%20getUpdates%20request%3B%20make%20sure%20that%20only%20one%20bot%20instance%20is%20running%22%0AJul%2019%2023%3A01%3A35%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A01%3A35%20MSK%202023%5D%20ERROR%20Retrying%20to%20get%20updates%20in%208s%0AJul%2019%2023%3A01%3A46%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A01%3A46%20MSK%202023%5D%20ERROR%20Getting%20updates%3A%20telego%3A%20getUpdates()%3A%20api%3A%20409%20%22Conflict%3A%20terminated%20by%20other%20getUpdates%20request%3B%20make%20sure%20that%20only%20one%20bot%20instance%20is%20running%22%0AJul%2019%2023%3A01%3A46%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A01%3A46%20MSK%202023%5D%20ERROR%20Retrying%20to%20get%20updates%20in%208s%0AJul%2019%2023%3A01%3A57%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A01%3A57%20MSK%202023%5D%20ERROR%20Getting%20updates%3A%20telego%3A%20getUpdates()%3A%20api%3A%20409%20%22Conflict%3A%20terminated%20by%20other%20getUpdates%20request%3B%20make%20sure%20that%20only%20one%20bot%20instance%20is%20running%22%0AJul%2019%2023%3A01%3A57%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A01%3A57%20MSK%202023%5D%20ERROR%20Retrying%20to%20get%20updates%20in%208s%0AJul%2019%2023%3A02%3A09%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A02%3A09%20MSK%202023%5D%20ERROR%20Getting%20updates%3A%20telego%3A%20getUpdates()%3A%20api%3A%20409%20%22Conflict%3A%20terminated%20by%20other%20getUpdates%20request%3B%20make%20sure%20that%20only%20one%20bot%20instance%20is%20running%22%0AJul%2019%2023%3A02%3A09%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A02%3A09%20MSK%202023%5D%20ERROR%20Retrying%20to%20get%20updates%20in%208s%0AJul%2019%2023%3A02%3A20%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A02%3A20%20MSK%202023%5D%20ERROR%20Getting%20updates%3A%20telego%3A%20getUpdates()%3A%20api%3A%20409%20%22Conflict%3A%20terminated%20by%20other%20getUpdates%20request%3B%20make%20sure%20that%20only%20one%20bot%20instance%20is%20running%22%0AJul%2019%2023%3A02%3A20%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A02%3A20%20MSK%202023%5D%20ERROR%20Retrying%20to%20get%20updates%20in%208s%0AJul%2019%2023%3A02%3A31%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A02%3A31%20MSK%202023%5D%20ERROR%20Getting%20updates%3A%20telego%3A%20getUpdates()%3A%20api%3A%20409%20%22Conflict%3A%20terminated%20by%20other%20getUpdates%20request%3B%20make%20sure%20that%20only%20one%20bot%20instance%20is%20running%22%0AJul%2019%2023%3A02%3A31%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A02%3A31%20MSK%202023%5D%20ERROR%20Retrying%20to%20get%20updates%20in%208s%0AJul%2019%2023%3A02%3A42%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A02%3A42%20MSK%202023%5D%20ERROR%20Getting%20updates%3A%20telego%3A%20getUpdates()%3A%20api%3A%20409%20%22Conflict%3A%20terminated%20by%20other%20getUpdates%20request%3B%20make%20sure%20that%20only%20one%20bot%20instance%20is%20running%22%0AJul%2019%2023%3A02%3A42%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A02%3A42%20MSK%202023%5D%20ERROR%20Retrying%20to%20get%20updates%20in%208s%0AJul%2019%2023%3A02%3A53%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A02%3A53%20MSK%202023%5D%20ERROR%20Getting%20updates%3A%20telego%3A%20getUpdates()%3A%20api%3A%20409%20%22Conflict%3A%20terminated%20by%20other%20getUpdates%20request%3B%20make%20sure%20that%20only%20one%20bot%20instance%20is%20running%22%0AJul%2019%2023%3A02%3A53%20abject-agreement.aeza.network%20x-ui%5B1044%5D%3A%20%5BWed%20Jul%2019%2023%3A02%3A53%20MSK%202023%5D%20ERROR%20Retrying%20to%20get%20updates%20in%208s%0A

**Comment by morrovat** [comment]
[x-ui (2).log](https://github.com/MHSanaei/3x-ui/files/12099708/x-ui.2.log)

**Comment by MHSanaei** [comment]
باید دیتابیس رو چک کنید با برنامه ی DB Browser (SQLite)  راه دیگه ای ندارید

**Comment by morrovat** [comment]
امکانش هست بهتون دسترسی بدم؟

**Comment by MHSanaei** [comment]
ایدی تلگرامتو بده

**Comment by morrovat** [comment]
@Omidmorrovat
