### ISSUE TITLE
مشکل  xray

### ISSUE THREAD

**Issue by maltima** [MHSanaei/3x-ui#789]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Xray 1.7.5 (Xray, Penetrates Everything.) Custom (go1.20.4 linux/arm64)

A unified platform for anti-censorship.

2023/07/19 20:34:58 [Info] infra/conf/serial: Reading config: bin/config.json

2023/07/19 20:34:58 [Warning] core: Xray 1.7.5 started

panic: runtime error: index out of range [189] with length 127

goroutine 10457 [running]:

github.com/xtls/xray-core/common/strmatcher.(*ACAutomaton).Match(...)

github.com/xtls/xray-core/common/strmatcher/ac_automaton_matcher.go:228

github.com/xtls/xray-core/common/strmatcher.(*MphMatcherGroup).Match(0x400080e2d0, {0x4003aefb30, 0x86})

github.com/xtls/xray-core/common/strmatcher/mph_matcher.go:186 +0x358

github.com/xtls/xray-core/app/router.(*DomainMatcher).ApplyDomain(0x40007f05b0, {0x4004085680?, 0xd3ad3e?})

github.com/xtls/xray-core/app/router/condition.go:102 +0x54

github.com/xtls/xray-core/app/router.(*DomainMatcher).Apply(0x4000810040?, {0xf07e38?, 0x40037bc600?})

github.com/xtls/xray-core/app/router/condition.go:111 +0x54

github.com/xtls/xray-core/app/router.(*ConditionChan).Apply(0x4003feecf8?, {0xf07e38, 0x40037bc600})

github.com/xtls/xray-core/app/router/condition.go:32 +0x70

github.com/xtls/xray-core/app/router.(*Rule).Apply(...)

github.com/xtls/xray-core/app/router/config.go:63

github.com/xtls/xray-core/app/router.(*Router).pickRouteInternal(0x4000191800, {0xf07e38, 0x40037bc600})

github.com/xtls/xray-core/app/router/router.go:94 +0x158

github.com/xtls/xray-core/app/router.(*Router).PickRoute(0xeffb40?, {0xf07e38?, 0x40037bc600?})

github.com/xtls/xray-core/app/router/router.go:72 +0x24

github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0x40007e9ce0, {0xeffb40, 0x40039b0990}, 0x400374a580, {{0xf01548, 0x40033e3070}, 0x1bb, 0x2})

github.com/xtls/xray-core/app/dispatcher/default.go:517 +0x24c

github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()

github.com/xtls/xray-core/app/dispatcher/default.go:390 +0x42c

created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch

github.com/xtls/xray-core/app/dispatcher/default.go:371 +0x320

### Version of 3x-ui

<details>

```console
# 1.7.1 & 1.7.0
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
لطفا issue بدون توضیحات باز نکنید 
باید قبلش بگید این کی اتفاق میفته 
روی چه سروری نصب کردید 
ایا از این پنل های بات تلگرامی که هست استفاده میکنید یا نه
لاگ xray رو بزارید
