### ISSUE TITLE
Visual bug in 1.7.1 ( first inbound shows all clients as disabled )

### ISSUE THREAD

**Issue by Arman-nsb** [MHSanaei/3x-ui#790]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Visual bug in 1.7.1: First inbound displays clients as disabled even though they are not.
![Screenshot 2023-07-20 142849](https://github.com/MHSanaei/3x-ui/assets/84615037/e8983fe3-e965-42be-963a-283df3379d81)

**Comment by behnamgolds** [comment]
It might be that, you have set expire date on your inbound itself (not the clients). Or it could be wrong date settings on your OS . You can check it with date command in the terminal.

**Comment by Arman-nsb** [comment]
> It might be that, you have set expire date on your inbound itself (not the clients). Or it could be wrong date settings on your OS . You can check it with date command in the terminal.

Thanks for your reply,
Sadly, none of those is the case. I have 4 servers and it's the same on all of them which makes me sure the bug is related to the latest release, v1.7.1 .
