### ISSUE TITLE
IP limiting

### ISSUE THREAD

**Issue by iamirhossein01** [MHSanaei/3x-ui#793]
Hi and thanks for the panel , IP limiting is not working at all and i couldn't figure it out why🤨? , I saw other people hade same problem but there wasn't a solution for it.
So i want to ask again if there is a solution or anny thing can fix help with that. I'll be grateful if you guys can help me with that. 🙏🏻

**Comment by AmoAlireza** [comment]
maybe you and other people don't how it work :)
cause for me working fine.

**Comment by hamid-gh98** [comment]
Hello,
If you are using version v1.7.0 and newer:
1. use `x-ui` command in shell
2. select `16. IP Limit Management`
3. select `1. Install Fail2ban and configure IP Limit`

if this didn't help you, please send this:
1. the version of panel you are using.
2. log of panel

**Comment by ali-cloudy** [comment]
.سلام . سوال . چرا اگر تانل کنیم ای پی لیمیت کار نمیکنه ؟! و اگر بخواهیم از آی پی لیمیت استفاده کنیم تو حالت تک سروره حتما باید fail2ban نصب کنیم ؟! و اینکه نصب این پاک کافیه دیگه یا باید داخل سرور تنظیمات خاصی بابت فیل تو بن انجام داد . مرسی

**Comment by hamid-gh98** [comment]
> .سلام . سوال . چرا اگر تانل کنیم ای پی لیمیت کار نمیکنه ؟! و اگر بخواهیم از آی پی لیمیت استفاده کنیم تو حالت تک سروره حتما باید fail2ban نصب کنیم ؟! و اینکه نصب این پاک کافیه دیگه یا باید داخل سرور تنظیمات خاصی بابت فیل تو بن انجام داد . مرسی 

درود،
موقع تانل آیپی از ایران، ایپی لیمیت کار نمیکنه، چون از سرور ایران وصل میشه به خارج، پس نمیشه استفاده کرد.

از ورژن v1.7.0 به بعد باید fail2ban وصل بشه که میتونین از کامند `x-ui` استفاده کنید بعد گزینه `ip limit management` سپس گزینه اول رو انتخاب کنید برای نصب fail2ban و فایل های مورد نیاز اون.

**Comment by iamirhossein01** [comment]
> Hello, If you are using version v1.7.0 and newer:
> 
> 1. use `x-ui` command in shell
> 2. select `16. IP Limit Management`
> 3. select `1. Install Fail2ban and configure IP Limit`
> 
> if this didn't help you, please send this:
> 
> 1. the version of panel you are using.
> 2. log of panel

thank you so much , yes it worked. there is a guide or tutorial for panel to read ?

**Comment by ali-cloudy** [comment]
Tnx sir i did it and i make it right 👍 but when use one server it's work
perfectly. But when i use tunnel like panel to panel and dekodomdor it
shouldn't work man . There is any way that in tunnel mode i can use ip
limit too?!
Both of servers are Ubuntu 22.4 . My foregein server is turkey and my ir
server is arvan . And i test in reality mode & ws mode & tcp & tls or every
protocole that you imagine . ممنون میشم کمک کنید .
But totally mhsanaie in my opinion is the best x-ui panel that ever made
and provided. Tnx guys really tnx for your patience, devotion , pride , and
genius. Im as an Iranian really proud of you buddies ▶️🎯👌🌏😳❤️🌟

**Comment by ali-cloudy** [comment]
Soory about version of my panel is 1.7.1 af course i test it in 1.7.0 but
it didn't work in tunnel mode . For me it doesn't matter that Wich tunnel
format maybe work for ip limiting just wanna knows can i do it totally?!
And I'm not vpn seller I'm sell servers just raw servers but some time i
install diffent protocols fory customers and few of them are seller's and
ask me for ip limiting in tunnel mode  .

**Comment by AmoAlireza** [comment]
if you want to use tunnel+IP limit should use that:
https://t.me/panel3xui/65

**Comment by MHSanaei** [comment]
@ali-cloudy 
از روش پنل به پنل استفاده کنید (اموزش داخل کانال)
و یوزر رو روی سرور ایران بسازید
در این صورت میتونید لیمیت بزارید

**Comment by ali-cloudy** [comment]
مرسی رفیق لطف کردی صبح حتما میبینم و ران میکنم .
Tnx my man tnx bro
