### ISSUE TITLE
Domain Host in TCP (NO TLS)

### ISSUE THREAD

**Issue by AmirmahdiHI** [MHSanaei/3x-ui#794]
سلام خسته نباشید ببخشید من می خواستم کانفیگ TCP بسازم تونل بعد می خوام از تونل رد بشه ولی جایی نداره برای اینکه Domain host رو بنویستم باید چی کار کنم ؟
بدون هیچ tls xtls reality لطفا این قابلیت رو اضافه کنید که برای هر کانفیگ بتونیم ادرس رو خودمون مشخص کنیم (راستش می خوام از آپدیت ساپ استفاده کنم و اگر این قابلیت نباشه باید دستی اضافه کنم !)

**Comment by hamed0mh** [comment]
اینو منم چند بار پیشنهاد دادم ولی ادمین جوابی نداد
.
تنها راه حلی که تونستم پیدا کنم reality بودش
