### ISSUE TITLE
مشکل خرید و تمدید اکانت در 1.7.1

### ISSUE THREAD

**Issue by sadra-naseri** [MHSanaei/3x-ui#795]
### Welcome

- [x] Yes, I'm using the latest major release. Only such installations are supported.
- [x] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

وقتی از طریق ویزویز یه اکانتی تمدید میشه یا خریداری میشه کار نمیکنه
باید بری تو پنل یه بار اکانت رو ریستارت کنی تا اوکی شه

تو نسخه 1.6.1 نیست 
ولی تو 1.7.0 و 1.7.1 هست

### Version of 3x-ui

<details>

```console
# 1.6.1
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by EryX0** [comment]
دقیقا همین مشکل، من حواسم نبود شما ایشو باز کردین، خودمم همچین ایشویی باز کردم، امیدوارم پیگیری شه

**Comment by MHSanaei** [comment]
مشکلتون رو در گیت هاب مربوطه باز کنید به پنل مربوط نیست
