### ISSUE TITLE
مشکل در استفاده از دو سرور مجزای ایران برای تانل کردن یک پنل با دامنه متفاوت

### ISSUE THREAD

**Issue by aht95** [MHSanaei/3x-ui#796]
سلام و درود بنده از تانل استفاده میکنم و میخواستم جهت کاهش هزینه های تانل پنل رو مثلا با دوسرور تانل ایران بالا بیارم خب برای اینکار از دو دامین متفاوت ( یا یک ساب دامین از همون قبلی) استفاده کردم و همشون هم پشت کلود فلر هستد با پروکسی خاموش.
اما حالا مشکل ای هست که وقتی با دامین دوم یعنی از طریق سرور دوم تانل پنل رو بالا میارم با https نمیاد و ارور میده و خیلی کند و دیر بالا میاد و سرعت کانفیگ هاش هم مشکل داره که فکر میکنم بخاطر ssl هست درصورتی که دامنه ssl رو داره. راه حل چیه؟ اینم اضافه بکنم که در حال حاضر توی تنطیمات من پرایوت کد و پایلیک کد دامین اصلی رو وارد کردم و پنل اصلی من با https بالا میاد بدون هیچ مشکلی ولی برای بالا اورد پنل از طریق دامین دوم که به سرور دوم ایران وصل هست مشکل کندی دارم. کمک کنید لطفا

**Comment by elegance666** [comment]
تانل کلا کند میکنه کار رو چه اصراری به تانل داری؟

**Comment by aht95** [comment]
پیشنهاد بهتری دارین؟

**Comment by aht95** [comment]
> تانل کلا کند میکنه کار رو چه اصراری به تانل داری؟

پیشنهاد بهتری دارین؟

**Comment by ali-cloudy** [comment]
داداش خدایی اگر واس رفع مشکل همراه اول رو وی تو رای پیشنهادی داری تایتل بده توضیحم نمی‌خواد بدی . وگرنه منکل ک نیستیم خداتومن پول شارژ و امکان فیلتر شکن سرورای خداتومنی رو بدیم با دلار ۵۵ تومنی و یورو ۶۰ و خورده ای
