### ISSUE TITLE
راه اندازی با داکر

### ISSUE THREAD

**Issue by jpyNicolas** [MHSanaei/3x-ui#799]
سلام وقتتون بخیر
من طبق روش راه اندازی با داکر پیش میرم و با پورت پیش فرض 2053 چیزی بالا نمیاره.
آیا کار خاص دیگه ای باید انجام بدم؟

**Comment by hamid-gh98** [comment]
درود
داکر آپدیت و فیکس شده، لطفا از آخرین ورژن استفاده کنید
```sh
docker pull ghcr.io/mhsanaei/3x-ui:v1.7.2
```

**Comment by jpyNicolas** [comment]
خب الان مشکل پورت پیش فرضش حل شد منتهی ادرس رو که بصورت زیر میزنم هیچی بالا نمیاره (یه صفحه مشکی خالی میاد داخل فایرفاکس و اررور This page isn’t working right now داخل کروم میده ).
http://ip:2053/panel

**Comment by drbakh94** [comment]
سلام.چطور میشه از دوروش معمولی و داکر پنل رو بالا اورد؟ینی دو پنل روی یک سرور باشن؟من از طریق داکر و هم معمولی نصب کردم ولی مشکلی که دارم وقتی x-ui رو میزنم فقط پنلی رو میاره که به صورت عادی نصب کردم.نه پنلی که روی داکر نصب شده

**Comment by hamid-gh98** [comment]
> خب الان مشکل پورت پیش فرضش حل شد منتهی ادرس رو که بصورت زیر میزنم هیچی بالا نمیاره (یه صفحه مشکی خالی میاد داخل فایرفاکس و اررور This page isn’t working right now داخل کروم میده ).
> http://ip:2053/panel

لطفا log پنل رو چک کنین ببینین اروری میده یا مشکلی هست
میتوتین با یه مرورگر دیگه هم تست کنید

**Comment by hamid-gh98** [comment]
> سلام.چطور میشه از دوروش معمولی و داکر پنل رو بالا اورد؟ینی دو پنل روی یک سرور باشن؟من از طریق داکر و هم معمولی نصب کردم ولی مشکلی که دارم وقتی x-ui رو میزنم فقط پنلی رو میاره که به صورت عادی نصب کردم.نه پنلی که روی داکر نصب شده

درود، میتونین با docker-compose چند container از یه image اجرا کنید، و پورت هرکدوم رو جدا کنید،

یا با استفاده از env variables ها میتونید چند پنل روی یک سرور نصب کنید، مثل XUI_LOG_FOLDER، XUI_DB_FOLDER و ....

و کامند x-ui  در حال حاظر وقت برای default کار میکنه، باید برای خودتون یه اسکریپت جدا بنویسین. یا اگر از داکر استفاده کردین باید از داخل داکر کامند رو اجرا کنید.

**Comment by drbakh94** [comment]
ممنون از توضیحاتتون.بر فرض اینکه من روی‌داکر پنل رو اوردم بالا و پورت متفاوت هست.دستورات اجرای پنل در داکر چی‌هستن؟چگونه به پوشه بکاپ پنل روی داکر دسترسی داشته باشم ( جز از طریق پنل)؟

**Comment by hamid-gh98** [comment]
> ممنون از توضیحاتتون.بر فرض اینکه من روی‌داکر پنل رو اوردم بالا و پورت متفاوت هست.دستورات اجرای پنل در داکر چی‌هستن؟چگونه به پوشه بکاپ پنل روی داکر دسترسی داشته باشم ( جز از طریق پنل)؟


@drbakh94 
درود، لطفا بخش [Docker](https://github.com/MHSanaei/3x-ui#install-with-docker) چک کنید.
برای مثال اگر از docker-compose استفاده میکنید. مثل این مثال زیر میشه:

این بحش رو در فایل docker-compose.yml ذخیره کنید،
لطفا مواردی که داره رو تغییر بدین بر اساس نیاز خودتون

```docker-compose
---
version: "3.9"

services:
  3x-ui-1:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui-1
    hostname: yourhostname-1
    volumes:
      - $PWD/app1/db/:/etc/x-ui/
      - $PWD/app1/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    ports:
      # Map 2053 internal to 2053 of host
      - 2053:2053
      # Add Other ports used for Inbounds
    restart: unless-stopped

  3x-ui-2:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui-2
    hostname: yourhostname-2
    volumes:
      - $PWD/app2/db/:/etc/x-ui/
      - $PWD/app2/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    ports:
      # Map 2053 internal to 2096 of host
      - 2096:2053
      # Add Other ports used for Inbounds
    restart: unless-stopped
```

سپس با دستور زیر اجرا کنید
```sh
docker compose up -d
```

**Comment by jpyNicolas** [comment]
لاگ رو چک کردم این رو لاگ کرده

```
Server ready
/app/x-ui: line 1: syntax error: unexpected "("
```

**Comment by shirmoz3** [comment]
> > ممنون از توضیحاتتون.بر فرض اینکه من روی‌داکر پنل رو اوردم بالا و پورت متفاوت هست.دستورات اجرای پنل در داکر چی‌هستن؟چگونه به پوشه بکاپ پنل روی داکر دسترسی داشته باشم ( جز از طریق پنل)؟
> 
> @drbakh94 درود، لطفا بخش [Docker](https://github.com/MHSanaei/3x-ui#install-with-docker) چک کنید. برای مثال اگر از docker-compose استفاده میکنید. مثل این مثال زیر میشه:
> 
> این بحش رو در فایل docker-compose.yml ذخیره کنید، لطفا مواردی که داره رو تغییر بدین بر اساس نیاز خودتون
> 
> ```
> ---
> version: "3.9"
> 
> services:
>   3x-ui-1:
>     image: ghcr.io/mhsanaei/3x-ui:latest
>     container_name: 3x-ui-1
>     hostname: yourhostname-1
>     volumes:
>       - $PWD/app1/db/:/etc/x-ui/
>       - $PWD/app1/cert/:/root/cert/
>     environment:
>       XRAY_VMESS_AEAD_FORCED: "false"
>     tty: true
>     ports:
>       # Map 2053 internal to 2053 of host
>       - 2053:2053
>       # Add Other ports used for Inbounds
>     restart: unless-stopped
> 
>   3x-ui-2:
>     image: ghcr.io/mhsanaei/3x-ui:latest
>     container_name: 3x-ui-2
>     hostname: yourhostname-2
>     volumes:
>       - $PWD/app2/db/:/etc/x-ui/
>       - $PWD/app2/cert/:/root/cert/
>     environment:
>       XRAY_VMESS_AEAD_FORCED: "false"
>     tty: true
>     ports:
>       # Map 2053 internal to 2096 of host
>       - 2096:2053
>       # Add Other ports used for Inbounds
>     restart: unless-stopped
> ```
> 
> سپس با دستور زیر اجرا کنید
> 
> ```shell
> docker compose up -d
> ```

من ازین روش استفاده کردم ولی مشکلی که هست اینه که x-ui رو بهش دسترسی ندارم و نمیتونم bbr نصب کنم یا وارپ رو
میشه لطفا داخل پنل این قابلیت هارو اضافه کنین که نیازی به x-ui bash نباشه
و مشکلی که وجود داره اینه که وقتی دوتا پنل رو باهم روی داکر اجرا میکنم توی یکیش که لاگین میکنم پنل دومی میره صفحه لاگین
و همزمان نمیتونم توی هر دوتا پنل لاگین کنم
کلا اگه امکانات x-ui bash داخل پنل باشه ازونجا بتونم مدیریت کنم و روی داکر هم بدون باگ بشه نصبش کرد خیلی ممنون میشم

**Comment by hamid-gh98** [comment]
> 
> من ازین روش استفاده کردم ولی مشکلی که هست اینه که x-ui رو بهش دسترسی ندارم و نمیتونم bbr نصب کنم یا وارپ رو میشه لطفا داخل پنل این قابلیت هارو اضافه کنین که نیازی به x-ui bash نباشه و مشکلی که وجود داره اینه که وقتی دوتا پنل رو باهم روی داکر اجرا میکنم توی یکیش که لاگین میکنم پنل دومی میره صفحه لاگین و همزمان نمیتونم توی هر دوتا پنل لاگین کنم کلا اگه امکانات x-ui bash داخل پنل باشه ازونجا بتونم مدیریت کنم و روی داکر هم بدون باگ بشه نصبش کرد خیلی ممنون میشم


درود،
شما باید bbr و warp رو روی سیستم خودتون یکبار نصب کنید. 
و `network_mode: host` رو به هر سرویس اضافه کنید و پورت رو پاک کنید.

فقط باید ابتدا پنل اول رو با docker compose بالا بیارین، سپس پورت پنل رو تغییر بدین مثلا به 2096.
و بعد پنل دوم رو بالا بیارین که میتونین پورت این پنل هم تغییر بدین مثلا به 2087.
الان شما اگر وارپ رو فعال کنید در پنل متصل میشه.


*docker-compose.yml*
```yaml
---
version: "3.9"

services:
  3x-ui-1:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui-1
    hostname: yourhostname-1
    volumes:
      - $PWD/app1/db/:/etc/x-ui/
      - $PWD/app1/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped

  3x-ui-2:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui-2
    hostname: yourhostname-2
    volumes:
      - $PWD/app2/db/:/etc/x-ui/
      - $PWD/app2/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped
```

**Comment by shirmoz3** [comment]
خیلی خب ولی این مشکلو چجوری حل کنم که وقتی توی پنل اول لاگین میکنم توی پنل دوم سشن منقضی میشه و در لحظه فقط میتونم تو یه پنل لاگین باشم و توی همه پنلا باهم لاگین نمیمونه

**Comment by shirmoz3** [comment]
> > من ازین روش استفاده کردم ولی مشکلی که هست اینه که x-ui رو بهش دسترسی ندارم و نمیتونم bbr نصب کنم یا وارپ رو میشه لطفا داخل پنل این قابلیت هارو اضافه کنین که نیازی به x-ui bash نباشه و مشکلی که وجود داره اینه که وقتی دوتا پنل رو باهم روی داکر اجرا میکنم توی یکیش که لاگین میکنم پنل دومی میره صفحه لاگین و همزمان نمیتونم توی هر دوتا پنل لاگین کنم کلا اگه امکانات x-ui bash داخل پنل باشه ازونجا بتونم مدیریت کنم و روی داکر هم بدون باگ بشه نصبش کرد خیلی ممنون میشم
> 
> درود، شما باید bbr و warp رو روی سیستم خودتون یکبار نصب کنید. و `network_mode: host` رو به هر سرویس اضافه کنید و پورت رو پاک کنید.
> 
> فقط باید ابتدا پنل اول رو با docker compose بالا بیارین، سپس پورت پنل رو تغییر بدین مثلا به 2096. و بعد پنل دوم رو بالا بیارین که میتونین پورت این پنل هم تغییر بدین مثلا به 2087. الان شما اگر وارپ رو فعال کنید در پنل متصل میشه.
> 
> _docker-compose.yml_
> 
> ```yaml
> ---
> version: "3.9"
> 
> services:
>   3x-ui-1:
>     image: ghcr.io/mhsanaei/3x-ui:latest
>     container_name: 3x-ui-1
>     hostname: yourhostname-1
>     volumes:
>       - $PWD/app1/db/:/etc/x-ui/
>       - $PWD/app1/cert/:/root/cert/
>     environment:
>       XRAY_VMESS_AEAD_FORCED: "false"
>     tty: true
>     network_mode: host
>     restart: unless-stopped
> 
>   3x-ui-2:
>     image: ghcr.io/mhsanaei/3x-ui:latest
>     container_name: 3x-ui-2
>     hostname: yourhostname-2
>     volumes:
>       - $PWD/app2/db/:/etc/x-ui/
>       - $PWD/app2/cert/:/root/cert/
>     environment:
>       XRAY_VMESS_AEAD_FORCED: "false"
>     tty: true
>     network_mode: host
>     restart: unless-stopped
> ```

خیلی خب ممنون ولی این مشکلو چجوری حل کنم که وقتی توی پنل اول لاگین میکنم توی پنل دوم سشن منقضی میشه و در لحظه فقط میتونم تو یه پنل لاگین باشم و توی همه پنلا باهم لاگین نمیمونه

**Comment by hamid-gh98** [comment]
> > > من ازین روش استفاده کردم ولی مشکلی که هست اینه که x-ui رو بهش دسترسی ندارم و نمیتونم bbr نصب کنم یا وارپ رو میشه لطفا داخل پنل این قابلیت هارو اضافه کنین که نیازی به x-ui bash نباشه و مشکلی که وجود داره اینه که وقتی دوتا پنل رو باهم روی داکر اجرا میکنم توی یکیش که لاگین میکنم پنل دومی میره صفحه لاگین و همزمان نمیتونم توی هر دوتا پنل لاگین کنم کلا اگه امکانات x-ui bash داخل پنل باشه ازونجا بتونم مدیریت کنم و روی داکر هم بدون باگ بشه نصبش کرد خیلی ممنون میشم
> > 
> > درود، شما باید bbr و warp رو روی سیستم خودتون یکبار نصب کنید. و `network_mode: host` رو به هر سرویس اضافه کنید و پورت رو پاک کنید.
> > 
> > فقط باید ابتدا پنل اول رو با docker compose بالا بیارین، سپس پورت پنل رو تغییر بدین مثلا به 2096. و بعد پنل دوم رو بالا بیارین که میتونین پورت این پنل هم تغییر بدین مثلا به 2087. الان شما اگر وارپ رو فعال کنید در پنل متصل میشه.
> > 
> > _docker-compose.yml_
> > 
> > ```yaml
> > ---
> > version: "3.9"
> > 
> > services:
> >   3x-ui-1:
> >     image: ghcr.io/mhsanaei/3x-ui:latest
> >     container_name: 3x-ui-1
> >     hostname: yourhostname-1
> >     volumes:
> >       - $PWD/app1/db/:/etc/x-ui/
> >       - $PWD/app1/cert/:/root/cert/
> >     environment:
> >       XRAY_VMESS_AEAD_FORCED: "false"
> >     tty: true
> >     network_mode: host
> >     restart: unless-stopped
> > 
> >   3x-ui-2:
> >     image: ghcr.io/mhsanaei/3x-ui:latest
> >     container_name: 3x-ui-2
> >     hostname: yourhostname-2
> >     volumes:
> >       - $PWD/app2/db/:/etc/x-ui/
> >       - $PWD/app2/cert/:/root/cert/
> >     environment:
> >       XRAY_VMESS_AEAD_FORCED: "false"
> >     tty: true
> >     network_mode: host
> >     restart: unless-stopped
> > ```
> 
> خیلی خب ممنون ولی این مشکلو چجوری حل کنم که وقتی توی پنل اول لاگین میکنم توی پنل دوم سشن منقضی میشه و در لحظه فقط میتونم تو یه پنل لاگین باشم و توی همه پنلا باهم لاگین نمیمونه
> 

در حال حاظر امکان لاگین با یک ادرس نیست، نیاز به سری تغییرات هست، اگر وقت کنم انجام میدم.

میتونین برای هر پنل یک subdomain بسازید و با اون subdomain وارد بشین.

**Comment by shirmoz3** [comment]
> > > > من ازین روش استفاده کردم ولی مشکلی که هست اینه که x-ui رو بهش دسترسی ندارم و نمیتونم bbr نصب کنم یا وارپ رو میشه لطفا داخل پنل این قابلیت هارو اضافه کنین که نیازی به x-ui bash نباشه و مشکلی که وجود داره اینه که وقتی دوتا پنل رو باهم روی داکر اجرا میکنم توی یکیش که لاگین میکنم پنل دومی میره صفحه لاگین و همزمان نمیتونم توی هر دوتا پنل لاگین کنم کلا اگه امکانات x-ui bash داخل پنل باشه ازونجا بتونم مدیریت کنم و روی داکر هم بدون باگ بشه نصبش کرد خیلی ممنون میشم
> > > 
> > > 
> > > درود، شما باید bbr و warp رو روی سیستم خودتون یکبار نصب کنید. و `network_mode: host` رو به هر سرویس اضافه کنید و پورت رو پاک کنید.
> > > فقط باید ابتدا پنل اول رو با docker compose بالا بیارین، سپس پورت پنل رو تغییر بدین مثلا به 2096. و بعد پنل دوم رو بالا بیارین که میتونین پورت این پنل هم تغییر بدین مثلا به 2087. الان شما اگر وارپ رو فعال کنید در پنل متصل میشه.
> > > _docker-compose.yml_
> > > ```yaml
> > > ---
> > > version: "3.9"
> > > 
> > > services:
> > >   3x-ui-1:
> > >     image: ghcr.io/mhsanaei/3x-ui:latest
> > >     container_name: 3x-ui-1
> > >     hostname: yourhostname-1
> > >     volumes:
> > >       - $PWD/app1/db/:/etc/x-ui/
> > >       - $PWD/app1/cert/:/root/cert/
> > >     environment:
> > >       XRAY_VMESS_AEAD_FORCED: "false"
> > >     tty: true
> > >     network_mode: host
> > >     restart: unless-stopped
> > > 
> > >   3x-ui-2:
> > >     image: ghcr.io/mhsanaei/3x-ui:latest
> > >     container_name: 3x-ui-2
> > >     hostname: yourhostname-2
> > >     volumes:
> > >       - $PWD/app2/db/:/etc/x-ui/
> > >       - $PWD/app2/cert/:/root/cert/
> > >     environment:
> > >       XRAY_VMESS_AEAD_FORCED: "false"
> > >     tty: true
> > >     network_mode: host
> > >     restart: unless-stopped
> > > ```
> > 
> > 
> > خیلی خب ممنون ولی این مشکلو چجوری حل کنم که وقتی توی پنل اول لاگین میکنم توی پنل دوم سشن منقضی میشه و در لحظه فقط میتونم تو یه پنل لاگین باشم و توی همه پنلا باهم لاگین نمیمونه
> 
> در حال حاظر امکان لاگین با یک ادرس نیست، نیاز به سری تغییرات هست، اگر وقت کنم انجام میدم.
> 
> میتونین برای هر پنل یک subdomain بسازید و با اون subdomain وارد بشین.

خیلی ممنون تونستم مشکلم رو حل کنم

**Comment by babakazizigithub** [comment]
> > > > من ازین روش استفاده کردم ولی مشکلی که هست اینه که x-ui رو بهش دسترسی ندارم و نمیتونم bbr نصب کنم یا وارپ رو میشه لطفا داخل پنل این قابلیت هارو اضافه کنین که نیازی به x-ui bash نباشه و مشکلی که وجود داره اینه که وقتی دوتا پنل رو باهم روی داکر اجرا میکنم توی یکیش که لاگین میکنم پنل دومی میره صفحه لاگین و همزمان نمیتونم توی هر دوتا پنل لاگین کنم کلا اگه امکانات x-ui bash داخل پنل باشه ازونجا بتونم مدیریت کنم و روی داکر هم بدون باگ بشه نصبش کرد خیلی ممنون میشم
> > > 
> > > 
> > > درود، شما باید bbr و warp رو روی سیستم خودتون یکبار نصب کنید. و `network_mode: host` رو به هر سرویس اضافه کنید و پورت رو پاک کنید.
> > > فقط باید ابتدا پنل اول رو با docker compose بالا بیارین، سپس پورت پنل رو تغییر بدین مثلا به 2096. و بعد پنل دوم رو بالا بیارین که میتونین پورت این پنل هم تغییر بدین مثلا به 2087. الان شما اگر وارپ رو فعال کنید در پنل متصل میشه.
> > > _docker-compose.yml_
> > > ```yaml
> > > ---
> > > version: "3.9"
> > > 
> > > services:
> > >   3x-ui-1:
> > >     image: ghcr.io/mhsanaei/3x-ui:latest
> > >     container_name: 3x-ui-1
> > >     hostname: yourhostname-1
> > >     volumes:
> > >       - $PWD/app1/db/:/etc/x-ui/
> > >       - $PWD/app1/cert/:/root/cert/
> > >     environment:
> > >       XRAY_VMESS_AEAD_FORCED: "false"
> > >     tty: true
> > >     network_mode: host
> > >     restart: unless-stopped
> > > 
> > >   3x-ui-2:
> > >     image: ghcr.io/mhsanaei/3x-ui:latest
> > >     container_name: 3x-ui-2
> > >     hostname: yourhostname-2
> > >     volumes:
> > >       - $PWD/app2/db/:/etc/x-ui/
> > >       - $PWD/app2/cert/:/root/cert/
> > >     environment:
> > >       XRAY_VMESS_AEAD_FORCED: "false"
> > >     tty: true
> > >     network_mode: host
> > >     restart: unless-stopped
> > > ```
> > 
> > 
> > خیلی خب ممنون ولی این مشکلو چجوری حل کنم که وقتی توی پنل اول لاگین میکنم توی پنل دوم سشن منقضی میشه و در لحظه فقط میتونم تو یه پنل لاگین باشم و توی همه پنلا باهم لاگین نمیمونه
> 
> در حال حاظر امکان لاگین با یک ادرس نیست، نیاز به سری تغییرات هست، اگر وقت کنم انجام میدم.
> 
> میتونین برای هر پنل یک subdomain بسازید و با اون subdomain وارد بشین.

درود و ارادت 
بنده نمیتونم به مسیری که mount کردم از داخل پنل دسترسی داشته باشم و سرتیفیکیت رو ثبت کنم .. مشکل از کجاست؟
