### ISSUE TITLE
از کار افتادن قسمت جستجو برای کاربران در اپدیت 1.7.1

### ISSUE THREAD

**Issue by LiamAghamohammadi** [MHSanaei/3x-ui#800]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام خسته نباشید
بعد از اپدیت به نسخه 1.7.1 قسمت باکس جستجو که در قسمت کابران بود از کار افتاده...

### Version of 3x-ui

1.7.1

### x-ui log reports or xray log

idk. test your panel

**Comment by Arman-nsb** [comment]
It works just fine, clearing the browser cache may help solve the problem.

**Comment by BehnamSaedi** [comment]
بله اگه تعداد یوزر ها بالا 100 تا باشه جستوجو کاربران ازکار میوفته

**Comment by Aronablade** [comment]
نه ربطی به تعداد نداره ، با ۵ تا یوزرم مشکل داره ، رو حروف درست عمل میکنه ولی عدد و علامت باشه دیگه نمیاره
