### ISSUE TITLE
مشکل کم نکردن حجم در ساب اکانتهای با پورت ثابت

### ISSUE THREAD

**Issue by bashir59** [MHSanaei/3x-ui#801]
سلام
من در Add Inbound  ساب اکانت های  با پورت ثابت ساختم که همه زیر مجوعه یک Remark با پورت ثابت هستن، مشکلی که دارم الان از هیچکدم از ساب اکانتها نه زمان کم میکنه و نه حجم  و  فقط در سربرگ Remark  تاریخ و حجم کم میکونه، ممنون میشم راهنمایی کنید.
متشکرم

**Comment by bashir59** [comment]
کسی این مشکل رو نداره ؟ لطفاً اگر تجربه ای دارید به اشتراک بزارید.
ممنون

**Comment by sarboy1371** [comment]
> سلام من در Add Inbound ساب اکانت های با پورت ثابت ساختم که همه زیر مجوعه یک Remark با پورت ثابت هستن، مشکلی که دارم الان از هیچکدم از ساب اکانتها نه زمان کم میکنه و نه حجم و فقط در سربرگ Remark تاریخ و حجم کم میکونه، ممنون میشم راهنمایی کنید. متشکرم

منم این مشکل رو دارم ولی تو برنامه از قسمت update subscrtion با هر بار اپدیت زدن درست میشه
