### ISSUE TITLE
Option to add cloudflare to WARP tunnel

### ISSUE THREAD

**Issue by mmrabbani** [MHSanaei/3x-ui#807]
**Is your feature request related to a problem? Please describe.**
راه جدیدی شناسایی شده است که با وجود بلاک شدن آی پی و دامین های ایرانی، باز هم آی پی سرور قابل شناسایی و فیلتر شدن باشد. این روش حداقل به صورت مشخص در برنامه ایرانسل من استفاده شده است. به این صورت که برنامه به آدرس زیر کوئری میزند
cloudflare.com/cdn-cgi/trace
و آی پی سرور را بدست می‌آورد و میتوانند آن را به سرور خود ارسال کند. در این حالت حتی اگر آدرس های ایرانی در کلاینت دیرکت باشد، آی پی سرور بدست می‌آید.
منبع:
https://twitter.com/imMohammad20000/status/1666761832952995841?s=19
من خودم تست کردم و ادعا درست است.

**Describe the solution you'd like**
قبلا راه حلی پیشنهاد داده بودم که اگرچه مشکل را حل می‌کرد، ولی مشکلاتی را هم به وجود می‌آورد و در نتیجه درخواست رد شد: https://github.com/MHSanaei/3x-ui/pull/578
الان پیشنهادی دارم که هیچ مشکلی برای کاربر ایجاد نمی‌کند. پیشنهاد آن است که در بخش warp گزینه ای برای کلودفلر ایجاد شود و در توضیح هم نوشته شود که این گزینه می‌تواند امنیت IP سرور را بالا ببرد. در صورتی که کاربر این گزینه را فعال کند geosite:cloudflare به بخش warp اضافه شود. من خودم این کار را دستی انجام دادم و دیگر آدرس فوق IP کلودفلر را به که جای IP سرور من برمیگرداند.

**Additional context**
این راه حل تجربه کاربر نهایی را بهبود نمی‌دهد. چون در همان مثال برنامه ایرانسل من، چون IP کلودفلر هم خارج از ایران است، برنامه باز نمی‌شود. ولی امنیت سرور را ارتقا می‌دهد و شانس شناسایی شدن آن را کم می‌کند.

**Comment by MHSanaei** [comment]
خودتون میتونید در قسمت manual list اضافه کنید نیازه نیست که یه دکمه اضافه در پنل قرار داده بشه
