### ISSUE TITLE
دانگرید کردن نسخه پنل

### ISSUE THREAD

**Issue by ho3ein-yazdan** [MHSanaei/3x-ui#808]
چه جوری میشه بدون اینکه اططلاعاتی حذف بشه پنل رو از مثلا ورژن 1.7.1 به ورژن 1.7.0 برگردوند ؟
بدون اینکه مشکلی پیش بیاد مثل هون اپدیت کردن باشه ولی به جای اینکه یک ورژن پنل رو نسخه اش رو ببره بالا یک نسخه بیاره پایین؟

**Comment by hamed0mh** [comment]
bash <(curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh) v1.7.0

**Comment by hamed0mh** [comment]
نه هیچ آسیبی به کاربر ها نمیزنه ولی در کل بکاپ رو داشته باشی عیبی نداره

**Comment by ali-cloudy** [comment]
مرسی سوال ب جا و هالی .از موقعی که ورژن وی تورای و هسته ایکس رای پنل آپدیت کردم . میتونم بگم راحت تنها چیزی ک باهاش م‌تجهم باگ هست . فروشنده نیستم و شخصی استفاده میکنم و حوزه ی کاریم ۱۰ سال حدودا تک و ارتباطات و کد و ... نه فقط وی تو رای . برنامه ی نکوباکس هم آپدیت زدم اون هم هستش ب مشکل خورده

**Comment by MHSanaei** [comment]
@ali-cloudy 
هسته 1.8.3 باگ زیادی داره بهتره فعلا به هیچ عنوان ازش استفاده نکنید 
نسخه پیشنهادی 1.8.1 هست بدون مشکل کار میکنه

**Comment by ali-cloudy** [comment]
دقیقا . یعنی ۱.۸.۱ هرچقدر بدون باگ و خوشگل و ناز و ماه کار می‌کنه و باور کن یا م رفته بود کلا فیلترینگ چ هست تا آپگرید کردم فلج شدم . من کلا کارم فروش سرور فکر کن چقدر سرور شخصی رنک و وا رنگ و ... واس خودم دارم . جالب بود همزمان برنامه های نکوباکس و وی تورای هم هست و آپدیت زدم تمام سرورا هیچ کانفیکی باز نمیشد پینک تک میداد بعد failed . آخ خدایی ۳ ماهه فیلترم نشدم غیر از ssh ک نامردا راش پیدا کردن ی هو هروی ssh و deffie+helman داشتم خورد مک‌مییشه تو ی ثانیه همه باهم هرکدومم واس ی دیتاسنتر بگم پنلمم ایرانی نبود . ی چیره خفنه که رو stunnel5 کار می‌کنه تک سروره بدون تاتل ‌
