### ISSUE TITLE
import backup file

### ISSUE THREAD

**Issue by p3im4n** [MHSanaei/3x-ui#809]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام و ارادت
تو نسخه  1.7.1 وقتی فایل x-ui.db رو به سرور جدید با دامنه متفاوت میبرم بعد از گذشت زمان طولانی پنل  stop  میشه و دیگه  start  هم نمیشه

### Version of 3x-ui

<details>

```console
# 1.7.1
```

</details>

### x-ui log reports or xray log

<details>

```console
#no log
```

</details>

**Comment by AliMajidi1** [comment]
احتمالا چون ssl فعال داری و فرم فایل سرتیفیکیت به این صورت هست /root/.acme.sh/domain1.com_ecc/domain1.com.cer

**Comment by AliMajidi1** [comment]
سلام
احتمالا چون ssl فعال داری و فرم فایل سرتیفیکیت به این صورت هست: /root/.acme.sh/domain1.com_ecc/domain1.com.cer
وقتی میری روی سرور جدید این فایل دیگه وجود نداره حتی اگه دوباره سرتیفیکیت بگیری به فرم  این هست: /root/.acme.sh/domain2.com_ecc/domain2.com.cer 
چون دامنت عوض شده
پس اگه میخوای بکاپ بگیری تو ستینگ اول ssl رو پاک کن بعد بکاپ بگیر
