### ISSUE TITLE
قراردادن یک دامنه در وایت لیست

### ISSUE THREAD

**Issue by bashir59** [MHSanaei/3x-ui#810]
سلام
تنظیمات  Disable connection to Iran IP ranges  رو روشن کردم والان دسترسی به آی پی های ایران اط طرف کاربرها بسته شده، چطور میتوانم برخی دومین ها یا آی پی ها رو  وایت لیست کنم که دسترسی به انها باز بشه.
متشکرم

**Comment by Mamal1999** [comment]
سلام منم همچین چیزی میخوام که بشه یه سری دامنه ها رو توی وایت لیست قرار داد

**Comment by MHSanaei** [comment]
میتونید مثل این بنویسید و به manual list قسمت مورد نظر اضافه کنید 
  "avamovie.info",
