### ISSUE TITLE
مشکل api routes

### ISSUE THREAD

**Issue by Mahdi-HFar** [MHSanaei/3x-ui#811]
سلام , موقع کار با api , وقتی اطلاعات اپدیت رو به صورت json ارسال میکنم این ارور دریافت میکنم 
<Response>

```console
 {"success":false,"msg":"Something went wrong!Fail: record not found","obj":null}
```

</Response>

###  Post Data :

> id=880&settings=%7B%22clients%22%3A%5B%7B%22id%22%3A%222b282d98-4de3-441e-b509-3a5f915e4805%22%2C%22flow%22%3A%22%22%2C%22email%22%3A%2285ulen9z-115%22%2C%22limitIp%22%3A0%2C%22totalGB%22%3A67645734912%2C%22expiryTime%22%3A1691167189000%2C%22enable%22%3Afalse%2C%22tgId%22%3A%22%22%2C%22subId%22%3A%22%22%7D%5D%7D

### Version of 3x-ui

<details>

```console
X-UI 1.8.1 , Panel 1.7.1
```

</details>

### x-ui log reports or xray log

<details>

```console
{"success":false,"msg":"Something went wrong!Fail: record not found","obj":null}
```

</details>

**Comment by mehdikhoram** [comment]
برای بروزرسانی باید از متد `POST` استفاده کنید و داده باید به صورت `JSON` باشد نه `urlencoded`.

```HTTP
POST /panel/api/inbounds/updateClient/{uuid} HTTP/1.1
Host: localhost:2053
Accept: application/json
Content-Type: application/json
Content-Length: 254

{
    "id": 1,
    "settings": "{\"clients\":[{\"id\":\"95e4e7bb-7796-47e7-e8a7-f4055194f776\",\"alterId\":0,\"email\":\"mehdikhody\",\"limitIp\":2,\"totalGB\":42949672960,\"expiryTime\":1682864675944,\"enable\":true,\"tgId\":\"\",\"subId\":\"\"}]}"
}
```
