### ISSUE TITLE
uuid مشکل

### ISSUE THREAD

**Issue by sarboy1371** [MHSanaei/3x-ui#814]
یه کلاینت ساختم و uuid شو پاک کردم و به اشتباه سیو کردم.حالا پنلم به ارور خورده و این کلاینت ویرایش یا حذف نمی شه و ارور Error: Request failed with status code 404میده و بقیه کلاینت ها به مشکل خوردن.چطوری حذفش کنم ؟؟؟

**Comment by sarboy1371** [comment]
کسی جواب سوالمو نداد ولی راه حلشو اینجا میذارم تا اگه کسی همچین مشکلی داشت برطرف کنه .
 با سرچی که کردم و ایمیلی که به @alireza0 زدم فهمیدم باید دیتا بیس رو دانلود کنم و با برنامه DB browser ویرایش کنم و کلاینت رو حذف کنم و فایل ادیت شده رو آپلود کنم تو پنل.
از من به شما نصیحت هر شب از پنل بک آپ بگیرید.

**Comment by Ghasem1243** [comment]
من که با  api کار میکنم خود پنل هر روز صبح و شب بکاپ میگره
