### ISSUE TITLE
کار با api

### ISSUE THREAD

**Issue by pouyaSanjari** [MHSanaei/3x-ui#819]
سلام 
موقع دریافت دیتا از api قسمت settings و streamSettings  به این شکل هست
"settings": "{\n  \"clients\": [\n    {\n      \"email\": \"nddjczcy\",\n      \"enable\": true,\n      \"expiryTime\": 0,\n      \"flow\": \"\",\n      \"id\": \"0786df55-929f-43c0-a0e0-bd40a7a7a2b3\",\n      \"limitIp\": 0,\n      \"subId\": \"\",\n      \"tgId\": \"\",\n      \"totalGB\": 0\n    }\n  ],\n  \"decryption\": \"none\",\n  \"fallbacks\": []\n}",

چطور باید این اطلاعات رو پردازش کرد؟ 
بنظر میرسه json باشه اما /n های وسطش مشکل ایجاد میکنه

مورد دیگه اینکه کاش خود api قابلیت ساخت لینک رو داشت. یا حداقل یه راهنمایی در این مورد در داکیومنت وجود داشت

**Comment by hamid-gh98** [comment]
درود، بله این json هست که encode شده، شما باید این رو decode کنید.

**Comment by pouyaSanjari** [comment]
بله json هست ولی مشکل حرف اضافه بینش هست که قابل پردازش نیست
منظورم n\ و یکسری \ های اضافه است که مشکل ایجاد میکنه
اگه هم دستی اینارو حذف کنیم باید موقع ارسال هم دوباره اینارو اضافه کنیم چون تو کالکشن postman که داخل داکیومنتیشن هست برای ارسال هم همین علایم وجود داره!
دلیلی نداره این علایم وجود داشته باشن بنظرم

**Comment by hamid-gh98** [comment]
> بله json هست ولی مشکل حرف اضافه بینش هست که قابل پردازش نیست منظورم n\ و یکسری \ های اضافه است که مشکل ایجاد میکنه اگه هم دستی اینارو حذف کنیم باید موقع ارسال هم دوباره اینارو اضافه کنیم چون تو کالکشن postman که داخل داکیومنتیشن هست برای ارسال هم همین علایم وجود داره! دلیلی نداره این علایم وجود داشته باشن بنظرم

`\` برای escape کردن یک کاراکتر و `\n` برای رفتن به خط بعدی هست.
این ها فک نمیکنم مشکلی در decode کردن بوجود بیاره و طبیعی هست که باشه!
نمیدونم از چه زبانی برای decode کردن استفاده میکنید که مشکل هست براتون،
ولی برای مثال برای javascript به این صورت هست:
```javascript
const decoded = JSON.parse(.......);
```
