### ISSUE TITLE
نصب دو پنل همزمان بدون داکر

### ISSUE THREAD

**Issue by arsoltani72** [MHSanaei/3x-ui#821]
سلام آیا اماکن داره که روی یه سرور دو تا x-ui بالا بیارم بدون استفاده از داکر ؟

**Comment by misagh72** [comment]
نه خیر امکانش نیست

**Comment by hamid-gh98** [comment]
درود، بله
با استفاده از [env variables](https://github.com/MHSanaei/3x-ui#environment-variables) ها میتونید چند پنل روی یک سرور نصب کنید.

باید پوشه ها رو بسازین و فایل کامپایل شده پنل رو در مسیر تعریف شده بزارین و به این صورت اجرا کنید.

```sh
XUI_BIN_FOLDER="/app/3x-ui-1/bin" XUI_DB_FOLDER="/app/3x-ui-1/db"
XUI_LOG_FOLDER="/app/3x-ui-1/log" /app/3x-ui-1/x-ui

XUI_BIN_FOLDER="/app/3x-ui-2/bin" XUI_DB_FOLDER="/app/3x-ui-2/db"
XUI_LOG_FOLDER="/app/3x-ui-2/log" /app/3x-ui-2/x-ui
```

**Comment by arsoltani72** [comment]
میشه بیشتر راهنمایی بفرمایید ؟

**Comment by hamid-gh98** [comment]
درود،

1. ابتدا از قسمت release اخرین ورژن پنل رو دانلود کنید. 
2. فایل `x-ui` رو برای مسیر `/app/3x-ui-1/x-ui` کپی کنید.
3. پوشه `bin` هم در مسیر `/app/3x-ui-1/bin` کپی کنید.
4. و سپس پوشه های `/app/3x-ui-1/db` و `/app/3x-ui-1/log` رو بسازید.

همینکار رو برای پنل 2 هم انجام بدین فقط اسم پوشه رو تغییر بدین مثلا به `3x-ui-2`

**Comment by wulfric93** [comment]
> درود،
> 
> 1. ابتدا از قسمت release اخرین ورژن پنل رو دانلود کنید.
> 2. فایل `x-ui` رو برای مسیر `/app/3x-ui-1/x-ui` کپی کنید.
> 3. پوشه `bin` هم در مسیر `/app/3x-ui-1/bin` کپی کنید.
> 4. و سپس پوشه های `/app/3x-ui-1/db` و `/app/3x-ui-1/log` رو بسازید.
> 
> همینکار رو برای پنل 2 هم انجام بدین فقط اسم پوشه رو تغییر بدین مثلا به `3x-ui-2`

مسیر /app/  کجاست ؟

**Comment by hamid-gh98** [comment]
> > درود،
> > 
> > 1. ابتدا از قسمت release اخرین ورژن پنل رو دانلود کنید.
> > 2. فایل `x-ui` رو برای مسیر `/app/3x-ui-1/x-ui` کپی کنید.
> > 3. پوشه `bin` هم در مسیر `/app/3x-ui-1/bin` کپی کنید.
> > 4. و سپس پوشه های `/app/3x-ui-1/db` و `/app/3x-ui-1/log` رو بسازید.
> > 
> > همینکار رو برای پنل 2 هم انجام بدین فقط اسم پوشه رو تغییر بدین مثلا به `3x-ui-2`
> 
> مسیر /app/  کجاست ؟

این فقط یه مثال بود که زدم، پوشه ها رو باید بسازید.
میتونین با این کامند بسازین
```bash
mkdir -p /app/3x-ui-1/{db,log,bin}
```

**Comment by wulfric93** [comment]
> 

توی root  میسازه ؟

**Comment by wulfric93** [comment]
آیا بعد میشه دستور x-ui رو برای این جدیده هم داست مثلا x-ui2

**Comment by hamid-gh98** [comment]
> آیا بعد میشه دستور x-ui رو برای این جدیده هم داست مثلا x-ui2
> 

خیر، در حال حاظر دستور `x-ui` فقط از  مسیر های پیش‌فرض استفاده میکنه

**Comment by hamid-gh98** [comment]
> > آیا بعد میشه دستور x-ui رو برای این جدیده هم داست مثلا x-ui2
> > 
> 
> خیر، در حال حاظر دستور `x-ui` فقط از  مسیر های پیش‌فرض استفاده میکنه

فقط env variable برای مسیر log ها میتونین استفاده کنید در x-ui

**Comment by arashammm** [comment]
ببخشید من یه مورد رو متوجه نشدم. الان در حال حاضر این env variable ها رو کجا باید پیدا کرد و ویرایش کرد؟‌این ها مربوط به فایل داکر نیستن؟
اگر مربوط به داکر هستن که ما هدفمون اینه که بدون داکر چند تا پنل رو همزمان استفاده کنیم در  یک سرور. 
@hamid-gh98

**Comment by hamid-gh98** [comment]
> ببخشید من یه مورد رو متوجه نشدم. الان در حال حاضر این env variable ها رو کجا باید پیدا کرد و ویرایش کرد؟‌این ها مربوط به فایل داکر نیستن؟ اگر مربوط به داکر هستن که ما هدفمون اینه که بدون داکر چند تا پنل رو همزمان استفاده کنیم در یک سرور. @hamid-gh98

درود،
از [این لینک](https://github.com/MHSanaei/3x-ui#environment-variables) میتونین مشاهده کنید.
فرقی نمیکنه از اینها هم میشه بدون داکر استفاده کرد و هم در داکر!!

در حال حاظر فقط از `XUI_LOG_FOLDER` برای دستور `x-ui` استفاده کنید.
مثلا میتونین بدون داکر به این صورت استفاده کتید.
```sh
XUI_LOG_FOLDER="/app/3x-ui-1/log" x-ui
```

اما بقیه مثلا برای اجرای پنل هم میشه استفاده کرد. مثال:
```sh
XUI_BIN_FOLDER="/app/3x-ui-1/bin" XUI_DB_FOLDER="/app/3x-ui-1/db" XUI_LOG_FOLDER="/app/3x-ui-1/log" /app/3x-ui-1/x-ui
```

**Comment by m2tts2001** [comment]
هر دو پنل باید به این صورت نصب بشه؟ نمیشه یکیش رو عادی نصب کرد و دومی رو به این شکل؟

**Comment by wulfric93** [comment]
من که بیخیال داستان شدم والا

**Comment by hamid-gh98** [comment]
> هر دو پنل باید به این صورت نصب بشه؟ نمیشه یکیش رو عادی نصب کرد و دومی رو به این شکل؟

بله میشه یکیش رو مسیر پیش فرض نصب کرد، مشکلی نیست.

**Comment by arashammm** [comment]
خیلی ممنون من الان موفق شدم یک پنل دیگه هم بالا بیارم  با این روش
فقط میشه لطفا راهنمایی کنید که کجای اسکریپت x-ui.sh رو باید ادیت کنم که بتونم کامند اختصاصی برای پنل جدید ران کنم و با وارد کردن این دستور تنظیمات پنل جدید بیاد بالا؟
@hamid-gh98

**Comment by ahwazi12** [comment]
سلام خوبی اگه میشه اکانت های که غیر فعال شده رو همه با هم حذف کرد

**Comment by wulfric93** [comment]
> سلام خوبی اگه میشه اکانت های که غیر فعال شده رو همه با هم حذف کرد

![image](https://github.com/MHSanaei/3x-ui/assets/117269334/cbb6dea3-0ef9-41e6-86ca-32a6bcbd5d19)

**Comment by ahwazi12** [comment]
این گذینه فقط اکانت های منقضی شده که بصورد عدد قرمز نشون میده حذف می کنه  اوکی غیر فعال هست بصورت عدد خاکستری هست پاک نمیشن

**Comment by aliamg1356** [comment]
> > > درود،
> > > 
> > > 1. ابتدا از قسمت release اخرین ورژن پنل رو دانلود کنید.
> > > 2. فایل `x-ui` رو برای مسیر `/app/3x-ui-1/x-ui` کپی کنید.
> > > 3. پوشه `bin` هم در مسیر `/app/3x-ui-1/bin` کپی کنید.
> > > 4. و سپس پوشه های `/app/3x-ui-1/db` و `/app/3x-ui-1/log` رو بسازید.
> > > 
> > > همینکار رو برای پنل 2 هم انجام بدین فقط اسم پوشه رو تغییر بدین مثلا به `3x-ui-2`
> > 
> > 
> > مسیر /app/  کجاست ؟
> 
> این فقط یه مثال بود که زدم، پوشه ها رو باید بسازید. میتونین با این کامند بسازین
> 
> ```shell
> mkdir -p /app/3x-ui-1/{db,log,bin}
> ```

با درود  هر کاری کردم با این کار پنل دوم آپ نشد  برای اجرای پنل دقیقا باید چیکار کرد؟

**Comment by jamiekarvans** [comment]
با سلام برای اجرای دو پنل به حداقل چه cpu و رم مورد نیاز هست و چقدر مصرف داره خود دو پنل؟

**Comment by bmv2020** [comment]
> با سلام برای اجرای دو پنل به حداقل چه cpu و رم مورد نیاز هست و چقدر مصرف داره خود دو پنل؟

میزان رم و cpu خیلی ربطی به تعداد پنل نداره (شاید در حد ۵۰ مگ به ازای هر instance) 
مصرف اصلی رم و cpu به تعداد کانکشن ها و میزان ترافیک بستگی داره.

**Comment by qar4al** [comment]
> درود، بله با استفاده از [env variables](https://github.com/MHSanaei/3x-ui#environment-variables) ها میتونید چند پنل روی یک سرور نصب کنید.
> 
> باید پوشه ها رو بسازین و فایل کامپایل شده پنل رو در مسیر تعریف شده بزارین و به این صورت اجرا کنید.
> 
> XUI_BIN_FOLDER="/app/3x-ui-1/bin" XUI_DB_FOLDER="/app/3x-ui-1/db"
> XUI_LOG_FOLDER="/app/3x-ui-1/log" /app/3x-ui-1/x-ui
> 
> XUI_BIN_FOLDER="/app/3x-ui-2/bin" XUI_DB_FOLDER="/app/3x-ui-2/db"
> XUI_LOG_FOLDER="/app/3x-ui-2/log" /app/3x-ui-2/x-ui

یک مشکل اساسی داره که هر کاری کردم نشد . مشکل نمایش کاربران انلاین وقتی پنل دوم اجرا میشه کاربرای انلاین پنل یک دیده نمیشه و وقتی پنل دوم رو غیرفعال میکنی کاربرای پنل اول به خوبی انلاین بودنش نشون داده میشه 

برای این مشکل راه کاری دارید ؟
