### ISSUE TITLE
اضافه کردن جای وب سوکت 

### ISSUE THREAD

**Issue by qar4al** [MHSanaei/3x-ui#822]
با سلام و خسته نباشید لطفا با توجه به خالی بودن جای وب سوکت که تو تصویر ارسالی مشاهده میکنید و در لینک های سابسکریپشن نمیشه 
اضافه کرد و باید دستی ویرایش بشه جای وب سوکت را اضافه کنی تا در خروجی گرفته شده خودکار کپی بشه تشکر

![Screenshot 2023-07-27 094139](https://github.com/MHSanaei/3x-ui/assets/63839880/bc23a016-60c4-4f00-b145-73d7f045f3a0)

![Screenshot 2023-07-27 094201](https://github.com/MHSanaei/3x-ui/assets/63839880/b9756c9d-922d-4f38-ba1b-ab089ae71869)

**Comment by Arman-nsb** [comment]
تو تصویر مقدار host رو نشون دادید، اگر نیاز دارید این مقدار خودکار پر بشه تو کانفیگ inbound ، دکمه + جلوی Request Header رو بزنید و مقدار مدنظرتون رو در کادر جلوی Host وارد کنید.
