### ISSUE TITLE
محل ذخیره log Fail2ban

### ISSUE THREAD

**Issue by mohsenrahmani145** [MHSanaei/3x-ui#825]
سلام وقتتون بخیر خسته نباشید میخواستم بدونم فایل log که ایپی های که بن شدن و ان بن شدن کجا ذخیره میشه که به صورت فایل بتونم دانلود کنم و نیاز نباشه از داخل cmd ببینم

**Comment by AmoAlireza** [comment]
`/var/log/3xipl.log`
`/var/log/3xipl-banned.log`
`/var/log/3xipl-access-persistent.log`
