### ISSUE TITLE
اتصال مستقیم به دامنه های ایرانی

### ISSUE THREAD

**Issue by shindiria** [MHSanaei/3x-ui#828]
برا فعال شدن تنظیمات قسمت اتصال مستقیم به دامنه ها و آی پی های ایرانی باید تو تنظیمات آتباند یا جای دیگه کاری کرد؟ چون من تیک مستقیم شو زدم ولی همچنان باز نمیشن.

**Comment by MHSanaei** [comment]
قبلا به این سوال پاسخ داده شده لطفا پست های قبلی رو مطالعه کنید
