### ISSUE TITLE
نصب چند پنل 

### ISSUE THREAD

**Issue by parham-re** [MHSanaei/3x-ui#829]
سلام وقت بخیر میخواستم بپرسم میشه روی یه سرور که چند ای پی بهش متصل هست برای هر ای پی یک پنل جداگانه نصب کرد ؟

**Comment by hamid-gh98** [comment]
درود
[این لینک](https://github.com/MHSanaei/3x-ui/issues/821#issuecomment-1653782039) رو چک کنید.

**Comment by arsoltani72** [comment]
روشش رو مرحله به مرحله ممنون میشم توضیح بدید

**Comment by hamid-gh98** [comment]
> روشش رو مرحله به مرحله ممنون میشم توضیح بدید

@parham-re 
@wulfric93 

https://github.com/MHSanaei/3x-ui/issues/821#issuecomment-1666806511
