### ISSUE TITLE
مشکل استفاده 100 درصد از منابع cpu

### ISSUE THREAD

**Issue by SAEEDZZZ** [MHSanaei/3x-ui#830]
سلام وقت بخیر از مسیر /usr/local/x-ui/x-ui درگیری ۱۰۰درصد cpu رو دارم روی سرور و باعث میشه سرور کلا فریز شه بره تو هنگ علت چیه ؟؟

**Comment by SAEEDZZZ** [comment]
x-ui.service main process exited, code=killed , status=9/kill
x-ui.service : failed with result 'signal'

**Comment by Arman-nsb** [comment]
احتمالا از قابلیت ip limit استفاده نمیکنید برای یوزرهاتون؟ چون این مشکل رو من هم داشتم کلا ip limit رو 0 کردم برای یوزرها فیکس شد. نمیدونم دقیقا علتش چیه!

**Comment by SAEEDZZZ** [comment]
نه ایپی لیمیت استفاده نمیکنم خیلی چند روزه اذیت میکنه این داستان

**Comment by zingunlock** [comment]
راه حلش همين مشخص كردن تعداد ip هاست؟

**Comment by SAEEDZZZ** [comment]
کسی همچین مشکلی نداشته درگیری cpu خیلی بالاس کانفیگ ارتقا هم دادم ولی باز درگیری بالای ۶۰ ۷۰ هس

**Comment by molaeian** [comment]
برای منم همین مشکلو داره

**Comment by molaeian** [comment]
متوجه شدم مشکل از کجاست : نباید در قسمت تعریف یوزر چلوی ip limit خالی باشه و بصورت دیفالت 0 هست و نباید پاکش کنید یا باید 0 باشه یا هر  رقمی ، حتی یوزر هم غیر فعال باشه بازم ارور میندازه رو پنل و منابع CPU رو تو پنل XRAY بالا میبره

**Comment by molaeian** [comment]
![Screenshot 2023-08-27 202241](https://github.com/MHSanaei/3x-ui/assets/131392088/d847ac87-811c-407f-a9a5-1479e1429c20)

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499

**Comment by chakkal9877** [comment]
من اصلا این قسمت آیپی لیمیت رو ندارم تو پنل جریان چیه
