### ISSUE TITLE
اضافه کردن چند ویژگی جدید

### ISSUE THREAD

**Issue by Bazareco** [MHSanaei/3x-ui#838]
#پیشنهاد
جناب ثنایی با تشکر از زحمات شما.
در صورت امکان این امکانات رو اضافه کنید.
اضافه کردن domain name در حالت بدون tls.
امکان حذف و ویرایش گزینه های حجم و روز باقیمانده در قسمت ساب.
برای بوزر های نامحدود امکان این باشه تایم و حجم رو بر اساس استفاده نشون بده. از کم به زیاد
امکان sort کاربرها بر اساس حجم و تاریخ.

**Comment by danyalfa79** [comment]
ویژگی نمایش حجم و روز های باقی مونده هم توی پنل مرزبان اضافه شده میتونه خیلی قابلیت کاربردی  برای یوزر باشه

**Comment by Bazareco** [comment]
> ویژگی نمایش حجم و روز های باقی مونده هم توی پنل مرزبان اضافه شده میتونه خیلی قابلیت کاربردی برای یوزر باشه

تو ورژن 1.7.1 اضافه شده. گفتم اگه امکانش باشه بتونیم یکم شخصی سازیش کنیم بهتره.

**Comment by danyalfa79** [comment]
> > ویژگی نمایش حجم و روز های باقی مونده هم توی پنل مرزبان اضافه شده میتونه خیلی قابلیت کاربردی برای یوزر باشه
> 
> تو ورژن 1.7.1 اضافه شده. گفتم اگه امکانش باشه بتونیم یکم شخصی سازیش کنیم بهتره.

کجا اضافه شده؟

**Comment by kalilovers** [comment]
واقعا اضافه کردن دامین نیم برای اینباندهای بدون tls که http هدر استفاده میشه خیلی ضروریه ! اصن نیستش ساب و هیچی بدرد نمیخوره برا هر کانفیگ باید دستی ست کرد
