### ISSUE TITLE
مشکل اتصال ربات تلگرام در سرور دیتاسنتر ایران

### ISSUE THREAD

**Issue by creationd66** [MHSanaei/3x-ui#840]
با درود، یه سرور تو ایران داریم که تانل شده به سرور خارج، میخوام سرور ایرانم وصل شه به ربات تلگرام، چیکار باید کرد با توجه به اینکه سرور ایران نمیتونه از api تلگرام استفاده کنه؟

**Comment by MHSanaei** [comment]
https://github.com/alireza0/x-ui/issues/252
