### ISSUE TITLE
باگ اضطراری

### ISSUE THREAD

**Issue by OghabTeam** [MHSanaei/3x-ui#841]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

من 700 تا کلاینت دارم همین الان یکی از کاربرا اومد گزارش کرد که کانفیگش نامحدود شده! رفتم دیدم بله داخل ui پنل نشون میده که ده گیگ کلاینت تموم شده اما یارو 20 گیگ مصرف کرده بود و هنوزم فعال بود و میشد که استفاده کرد!!!! جالب اینکه تو همون پنل کلاینت رو مسدود شده نشون میداد!!! جدیدا میدیدم چرا مصرف کاربرا خیلی بیش از حد مجاز بالاتره ولی فک میکردم خب شاید دیر مسدود شده فلان نگو همشون فعالن!!!!! تازه یه باگ رو مخ دیگه هم وجود داره اونم اینه که بعضی وقتا زمانی که با api یک کلاینتی رو تمدید میکنی مصرفش صفر میشه اما تاریخ جدیدی که دادی تا ست بشه داخل ui ست میشه و نشون میده که مثلا برای چند ماه بعد هست سررسیدش ولی وقتی با api همون کانفیگ رو گت میکنی expiryTime مال همون تاریخ قبلیه که موقع ساخت ست کرده بودیم و درواقع بروز نشده! لطفا سریع اوکی کنید اینارو تشکر.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by PouryaDe** [comment]
سلام
من هم از api پنل استفاده میکنم ولی این مواردی که گفتید رو چک کردم اصلا همچین چیزی وجود نداره
لطفا اطلاعات دقیق تری بدید و یه سری مستندات هم بفرستید
