### ISSUE TITLE
سورس کد روبات برای شخصی سازی

### ISSUE THREAD

**Issue by I-MrFlutter** [MHSanaei/3x-ui#844]
توی کدوم بخش میشه سورس کد روبات رو پیدا کرد برای شخصی سازی ؟

-به طور مثال میخوام که به جای ساعت UTC زمانه تاریخ انقضای کانفیگ رو به تاریخ و ساعت خوده ایران به کاربر نشون داده بشه.
-گاهی اوقات پیش میاد که حجم یوزر ها خیلی زود تر از تاریخ انقضای کانفیگ ها تموم میشه . میخوام دقیقا در همون زمان که کانفیگ یوزر از کار میوفته ثبت بشه و زمانی که یوزر ها استعلام گرفتن در یک فیلد جدا به یوزر نشون بده که در چه تاریخ و زمانی کانفیگ از کار افتاده .

**Comment by MHSanaei** [comment]
در اپدیت اخر تاریخ نمیزنه تعداد روز باقیمانده رو داخل ساب نشون میده مثلا
3 days
اگر به این شکل برای شما نمایش داده نمیشه نسخه اخر رو مجدد نصب کنید
