### ISSUE TITLE
مشکل 403

### ISSUE THREAD

**Issue by rapomid** [MHSanaei/3x-ui#846]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام 
دوستلن اکه کسی میتونه  یا بلده لطف بگه مشکل 403 که مربوط به باز شدن صفحات هست رو چطور رفع کنم
گوگل من ارور 403 میده و سرچ کار نمیکنه وقتی فیلتر روشنه

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by sarboy1371** [comment]
> 

تو پنل از تنطیمات xray قسمت تنطیمات برای ipv4 گزینه استفاده از ipv4برای اتصال به گوگل رو فعال کن

**Comment by rapomid** [comment]
> آی پی سرورتون کثیف شده . آدرس های گوگل رو بندازید روی warp.

ممنون یه اموزش  میزاری

**Comment by rapomid** [comment]
> > 
> 
> تو پنل از تنطیمات xray قسمت تنطیمات برای ipv4 گزینه استفاده از ipv4برای اتصال به گوگل رو فعال کن

اقا دمت گرم درست شد

**Comment by mostafajafari00** [comment]
اقا من او دو گزینه رو هم فعال میکنم اما باز تاثیر نداره
