### ISSUE TITLE
请问有中文版的吗？

### ISSUE THREAD

**Issue by watermelonhahaha** [MHSanaei/3x-ui#851]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

请问有中文版的吗？

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
just change the language to Chinese

**Comment by watermelonhahaha** [comment]
您好！您的邮件我已经收到。

**Comment by MHSanaei** [comment]
转到面板设置/语言
并将语言更改为中文
