### ISSUE TITLE
مشکل fail2ban در محدود کردن آی پی یوزر

### ISSUE THREAD

**Issue by PouryaDe** [MHSanaei/3x-ui#853]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام
این قابلیت محدود کردن آی پی خیلی خوب کار میکنه ولی یه سری ایراد داره و اونم اینه که وقتی یه کلاینت رو تک کاربره میکنیم، زمانی که دومین نفر وصل میشه نفر اول رو بلاک میکنه و نفر دوم استفاده میکنه
حالت درستش اینه که نفر دوم نتونه وصل بشه و نفر اول وصل بمونه

و اگر امکانش باشه یه بخشی رو اضافه کنید که به جای اینکه از داخل سرور Check Logs رو بزنیم که ببینیم چه موقعی کدوم آی پی بن شده، اینو بذارید داخل صفحه کلاینت که اونجا آمارشو داشته باشیم
ممنون

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by arman2012** [comment]
نه دیگه داداش 
اونوقت ایراد به وجود میاد طرف مثلا میخواد از نت خط وصل بشه به وایرلس اونوقت نمیشه چون فکر میکنه شخص جدیده نمیذاره وصل بشه ولی الان میذاره وصل بشه و آی پی خطش فقط مثلا برای ده دقیقه بن میشه. الان بهتره کسی که میده کانفیگو به بقیه خودش طعم قطع شدن کانفیگشو بچشه

**Comment by elegance666** [comment]
fail2ban کجای پنل هستش پیداش نمیکنم
