### ISSUE TITLE
Merge database

### ISSUE THREAD

**Issue by mehdikhoram** [MHSanaei/3x-ui#856]
**Is your feature request related to a problem? Please describe.**
Imagine that you have two servers, and one of them becomes less active than the other. So, you decide to combine the servers together for the sake of efficiency. Now, you need to write a custom script to fetch all inbound data and user information from the less active one and create the same representation on the more active one.

**Describe the solution you'd like**
<img width="398" alt="Screenshot 2023-08-03 120721" src="https://github.com/MHSanaei/3x-ui/assets/137898378/06887553-6698-40b6-91dd-2158af78d41d">
It would be nice to add a button beside the "Download" and "Upload" database buttons, named "Merge database", so we can achieve the same results without all those overheads.

**Additional context**
I would like to use this opportunity to thank you and all contributors who work hard on this project, so others like me can reach the goal of an uncensored internet

**Comment by hrasoul2** [comment]
سلام
همین روش اسکرپیت که خودتون میگید رو میتونید ساده توضیحش بدید خیلیا مثه من نیاز دارن ولی بلد نیستن
ممنونم
