### ISSUE TITLE
bug in install fail2ban after update 3x-ui

### ISSUE THREAD

**Issue by clockedzero** [MHSanaei/3x-ui#857]
درود
بعد از آپدیت 3x-ui از ورژن 1.6.1 به آخرین نسخه (1.7.5) ، موقعی که fail2ban رو نصب میکنم انجام نمیشه:

Fail2ban is not installed. Installing now...!
.
.
Fail2ban installed successfully!
.
.
Configuring IP Limit...

/usr/bin/x-ui: line 710: /etc/fail2ban/jail.d/3x-ipl.conf: No such file or directory
/usr/bin/x-ui: line 721: /etc/fail2ban/filter.d/3x-ipl.conf: No such file or directory
/usr/bin/x-ui: line 728: /etc/fail2ban/action.d/3x-ipl.conf: No such file or directory
Created Ip Limit jail files with a bantime of 5 minutes.
Failed to start fail2ban.service: Unit fail2ban.service not found.
Failed to enable unit: Unit file fail2ban.service does not exist.
IP Limit installed and configured successfully!.
ممنون میشم راهنمایی بفرمایید.
 

### Version of 3x-ui

1.7.5

**Comment by kavehasgari** [comment]
سلام. 
اگر همچنان این مشکل رو دارید دو کامند زیر رو در سرورتون اگر Debian یا Ubuntu هست اجرا کنید به ترتیب.

apt-get install fail2ban

cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local

سپس از طریق پنل x-ui به ترتیب گزینه 17 و بعد از آن 1 را اجرا کنید تا خودکار تنظیمات مورد نظر رو اعمال کند.
