### ISSUE TITLE
 محدودیت اتصال هم زمان یک کاربر با uuid

### ISSUE THREAD

**Issue by MD-97** [MHSanaei/3x-ui#864]
سلام.
اگه امکانش هست بجای محدودیت با ip محدودیت اتصال uuid رو کنترل کنید که مثلا یک uuid فقط به تعداد درخواست ادمین برای هر user اعمال بشه.
این عمل باعث جلو گیری از اتصال همزمان uuid به تعداد محدودیت اتصال هر کاربر میشه.

ولی اگه امکانش باشه با Mac address محدودیت انجام بشه که حتی کاربر در دستگاه دیگه ای  نتونه وصل بشه بجز دستگاهی که vpn خریداری کرده.

این عمل برای گوشی موبایل با برنامه NapsternetV امکان پذیر هست با HardwareId ولی برای PC امکانش نیست.

**-(اگه کاربری درخواست اکانت PC داشته باشه دیگه نمیشه محدودیت برای گوشی اعمال کرد، همون لینک رو در تمام گوشی ها استفاده میکنه.)

ممنون میشم اگه این مسیر ها امکانش هست به پنلتون اعمال کنید.
یا راهی برای حل مشکل من (**)

**Comment by AliMajidi1** [comment]
پیاده سازی محدودیت با mac address که در سمت سرور امکان پذیر نیست چون سرور اصلا دسترسی به مک آدرس افراد متصل نداره و فقط به آیپیشون دسترسی داره
ولی خوب میشه اگه محدودیت اتصال همزمان بذارن تو پنل
