### ISSUE TITLE
مصرف غیر عادی ترافیک

### ISSUE THREAD

**Issue by kalilovers** [MHSanaei/3x-ui#872]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام جناب ثنایی خسته نباشید . مدتی هستش که برخی کاربران مشکل مصرف غیرعادی اکانت دارند من چک کردم درسته . مثلا با یک بسته اینترنت 7 گیگ 30 گیگ اکانتشون تموم میشه قبل از اتمام اینترنت خودشون 
قبلا فکر میکردیم از برنامه های پشت زمینه یا.. باشه که خودشون مصرف میکنن ولی با بسته اینترنتی هم بررسی شد مصرف تو سرور غیرعادی هست و اکانت زودتر از اینترنت واقعی مصرف شده هستش ینی کاربرا کلا 5 گیگ مصرف میکنه چند برابرش مصرف میشه تو سرور 
پروتکل :
vless tcp http header 
تو بقیه پروتکل ها هم دیده شده

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
ترافیک رو خود ایکس ری محاسبه میکنه پنل فقط نمایش میده
باید ببینید مشکل شما کجاست
به عنوان مثال روی یک سرور چند پنل نصب نکرده باشید

**Comment by kalilovers** [comment]
> ترافیک رو خود ایکس ری محاسبه میکنه پنل فقط نمایش میده باید ببینید مشکل شما کجاست به عنوان مثال روی یک سرور چند پنل نصب نکرده باشید

من بررسی کردم موردی نبود شما روش خاصی برای بررسیش دارید ممنون میشم بگید چک کنیم ببینیم از کجاست . غز از اونم یه موردی هست که مصرف بعد از نصب پنل و اتصال یوزرا از نظر مصرف کلی و یوزا هم فرق پیدا میکنه عکسارو میفرستم ببینید . مصرف یوزرا مثلا 1.7 ترا هستش ولی سرور (مصرفی که پنل نشون میده از کل شکبه ها) 1.9 هستش . غیر از پنل چیزی نصب نیست .
