### ISSUE TITLE
WARP Config

### ISSUE THREAD

**Issue by Saleh-Mumtaz** [MHSanaei/3x-ui#877]
درود، 
لطفا امکان ساخت کانفیگی که به طور کلی پشت وارپ باشه رو اضافه کنید.
 در حال حاضر قابلیت عبور دادن ترافیک سایت های خاص مثل گوگل یا نتفلیکس و چت جی پی تی وجود داره که به طور کلی روی تمام inbound ها اعمال میشه، لذا گزینه ای در قسمت ساخت inbound جدید در نظر گرفته شود که کل ترافیک inbound مذکور از وارپ عبور داده شود. (پورت دیفالت هم که همان 40000 هست)
در اسکریپت وارپی که قرار دادید امکان ارتقا به وارپ پلاس وجود داره و افت سرعت انچنانی مشاهده نمیشه، برای مخفی کردن کامل ایپی سرور بسیار کارامد خواهد بود.

**Comment by Mammad3861** [comment]
من هم دنبال اینم باید تو xray configuration اعمال بشه تنظیماتش
فقط من فعلا بجایی نرسیدم

**Comment by Mammad3861** [comment]
گشتم این رو پیدا کردم
باید تو Xray configuration اضافش کنی


```
{
        "type": "field",
        "outboundTag": "WARP",
        "domain": [
          "regexp:.*"
        ],
        "ip": [
          "0.0.0.0/0"
        ]
      }
```

**Comment by Saleh-Mumtaz** [comment]
@Mammad3861 
بسیار عالی، متشکرم، اگر میشد جناب ثنایی در همون قسمت ساخت اینبوند حالت دکمه قرار مثلا Put behind WARP

**Comment by hosein-moayedi** [comment]
> گشتم این رو پیدا کردم باید تو Xray configuration اضافش کنی
> 
> ```
> {
>         "type": "field",
>         "outboundTag": "WARP",
>         "domain": [
>           "regexp:.*"
>         ],
>         "ip": [
>           "0.0.0.0/0"
>         ]
>       }
> ```

آقا اینو پاک کن لطفا
این کاری که کردی باعث میشه پنل ترافیک ازش رد نشه و در نتیجه نتونیم ترافیک مصرفی کاربرا رو اندازه گیری کنیم
@Mammad3861

**Comment by Mammad3861** [comment]
> > گشتم این رو پیدا کردم باید تو Xray configuration اضافش کنی
> > ```
> > {
> >         "type": "field",
> >         "outboundTag": "WARP",
> >         "domain": [
> >           "regexp:.*"
> >         ],
> >         "ip": [
> >           "0.0.0.0/0"
> >         ]
> >       }
> > ```
> 
> آقا اینو پاک کن لطفا این کاری که کردی باعث میشه پنل ترافیک ازش رد نشه و در نتیجه نتونیم ترافیک مصرفی کاربرا رو اندازه گیری کنیم @Mammad3861

سلام عزیز
این کانفیگ رو در بخش اوتباند میشه گذاشت اجباری نیست! صرفا برای این که ترافیک کل خروجی سرور از warp رد بشه
و هیچ مشکلی در محاسبه ترافیک برای من تو این دو ماه ایجاد نکرده! اگه سوال دارید فایل json کانفیگ پنلتون رو به تلگرام t.me/mammad_3861 بفرستید!

**Comment by Mammad3861** [comment]
> > > گشتم این رو پیدا کردم باید تو Xray configuration اضافش کنی
> > > ```
> > > {
> > >         "type": "field",
> > >         "outboundTag": "WARP",
> > >         "domain": [
> > >           "regexp:.*"
> > >         ],
> > >         "ip": [
> > >           "0.0.0.0/0"
> > >         ]
> > >       }
> > > ```
> > 
> > 
> > آقا اینو پاک کن لطفا این کاری که کردی باعث میشه پنل ترافیک ازش رد نشه و در نتیجه نتونیم ترافیک مصرفی کاربرا رو اندازه گیری کنیم @Mammad3861
> 
> سلام عزیز این کانفیگ رو در بخش اوتباند میشه گذاشت اجباری نیست! صرفا برای این که ترافیک کل خروجی سرور از warp رد بشه و هیچ مشکلی در محاسبه ترافیک برای من تو این دو ماه ایجاد نکرده! اگه سوال دارید فایل json کانفیگ پنلتون رو به تلگرام t.me/mammad_3861 بفرستید!

به این صورت ...
@hosein-moayedi 

`{
  "log": {
    "loglevel": "warning",
    "access": "./access.log",
    "error": "./error.log"
  },
  "api": {
    "tag": "api",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ]
  },
  "inbounds": [
    {
      "tag": "api",
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    },
    {
      "tag": "WARP",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 40000
          }
        ]
      }
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "ip": [
          "geoip:private"
        ]
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ]
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "domain": [
          "geosite:category-ads-all",
          "ext:iran.dat:ads"
        ]
      },
      {
        "type": "field",
        "outboundTag": "WARP",
        "domain": [
          "regexp:.*"
        ],
        "ip": [
          "0.0.0.0/0"
        ]
      }
    ]
  },
  "stats": {}
}`

**Comment by Saleh-Mumtaz** [comment]
@Mammad3861 
درود جناب، ایا راهی میشناسید ترافیک فقط یک اینباوند خاص از وارپ عبور کنه؟ در اسکریپت اف اسکارمن، میشه حالت وارپ رو برد گلوبال، لاکن روی ریورس تی ال اس تانل تاثیر مخرب میگذاره، لذا ترجیح من روی کنترل بیشتر روی دیتای عبوری از وارپ هست.

**Comment by hosein-moayedi** [comment]
@Saleh-Mumtaz 
آخرین کانفیگت که داره کار میکنه رو از پنل صفحه اصلی و زدن دکمه کانفیگ که کنار backup/restore هست بفرست ادیت کنم برات

**Comment by hosein-moayedi** [comment]
@Saleh-Mumtaz 
نوشته Download config.json

**Comment by hosein-moayedi** [comment]
@Saleh-Mumtaz 
البته نمیخواد بفرستی چون فکر کنم کله دیتا یوزر توشه
ببین:
اول برو تو پنلت بعد تو صفحه اصلی که داره مصرف رم و cpu رو نشون، سمت راست وسط صفحه نوشته config. میزنی روش
بعد از لیست inbounds باید اسم تگی که برای inbound قرار داده رو پیدا کنید (معمولا نام گذاریش به این شکل  inbound-port مثلا inbound-443)

بعد که اسم تگ رو دراوردی باید بری تو بخش زیر:
Panel Setting > xray-config > Advance Template > Configuration of routing rules

حالا باید این رو بهش اضافه کنی:
```
{
        "inboundTag": [
          "inbound-443" // اسم تگی که پیدا کردی
        ],
        "outboundTag": "WARP", // چک کن ببین اسم تگ outbound وارپ همینه یا فرق داره
        "type": "field"
},
```

حواست به , ها باشه تا درست ادد کنی

**Comment by Saleh-Mumtaz** [comment]
درود جناب ممنون از پاسخگوییتون و دقت به نکات امنیتی، جسارتا در inboundtag به جای inbound-443 چطوری یک اینباوند خاص رو تگ کنم. در قسمت اینباوند تگ ها فقط تگ api موجود هست.
{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "log": {
    "error": "./error.log",
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    },
    {
      "tag": "WARP",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 40000
          }
        ]
      }
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "type": "field",
        "outboundTag": "WARP",
        "domain": [
          "geosite:openai",
          "geosite:netflix",
          "geosite:spotify",
          "geosite:google"
        ]
      }
    ]
  },
  "stats": {}
}

**Comment by hosein-moayedi** [comment]
@Saleh-Mumtaz 

بیا پی وی بهت بگم اینجا خیلی سخت
tele: @xrois

**Comment by Saleh-Mumtaz** [comment]
درود دوستان، نتیجه نهایی این بخش:
برای عبور دادن یک inbound خاص باید تگ ان را به صورت زیر در Configuration of routing rules قرار داد.
توجه داشته باشید که اگر:
۱- می‌خواهید کلید های عبور گوگل و اسپاتیفای و نتفلیکس و openai خاموش باشند باید تعریف تگ وارپ را خودتان در تمپلیت قرار دهید در غیر این صورت با وجود تگ وارپ کردم یک اینباوند خروجی  همچنان ایپی اصلی سرور خواهد بود. 
۲- حتی با روشن بودن یک کلید عبور وارپ تعریف تگ وارپ در تمپلیت خواهد بود.
۳- در صورت روشن بودن کلیدهای وارپ ، رول اینباوند های مورد نظر را بعد از رول های کلید های وارپ قرار دهید.
۴- کانفیگ تگ شده در وارپ ممکن است گاهی به مشکل بخورد.

**Comment by Saleh-Mumtaz** [comment]
`
{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "log": {
    "error": "./error.log",
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    },
    {
      "tag": "WARP",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 40000
          }
        ]
      }
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "type": "field",
        "outboundTag": "WARP",
        "domain": [
          "geosite:google",
          "geosite:openai",
          "geosite:netflix",
          "geosite:spotify"
        ]
      },
      {
        "inboundTag": [
          "inbound-32470"
        ],
        "outboundTag": "WARP",
        "type": "field"
      }
    ]
  },
  "stats": {}
}
`

**Comment by Saleh-Mumtaz** [comment]
[
  {
    "inboundTag": [
      "api"
    ],
    "outboundTag": "api",
    "type": "field"
  },
  {
    "type": "field",
    "outboundTag": "WARP",
    "domain": [
      "geosite:google",
      "geosite:openai",
      "geosite:netflix",
      "geosite:spotify"
    ]
  },
  {
    "inboundTag": [
      "inbound-32470"
    ],
    "outboundTag": "WARP",
    "type": "field"
  }
]

**Comment by hosein-moayedi** [comment]
@Saleh-Mumtaz 

```
[
    {
        "inboundTag": [
            "api"
        ],
        "outboundTag": "api",
        "type": "field"
    },
    {
        "type": "field",
        "outboundTag": "WARP",
        "domain": [
            "geosite:google",
            "geosite:openai",
            "geosite:netflix",
            "geosite:spotify"
        ]
    },
    {
        "inboundTag": [
            "inbound-32470"
        ],
        "outboundTag": "WARP",
        "type": "field"
    }
]
```

**Comment by Saleh-Mumtaz** [comment]
تگ هر کانفیگ در اینباوند به صورت زیر خواهد بود:
inbound-port
به جای پورت مقدار پورت کانفیگ مد نظر را قرار دهید.

**Comment by Saleh-Mumtaz** [comment]
```
{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "log": {
    "error": "./error.log",
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    },
    {
      "tag": "WARP",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 40000
          }
        ]
      }
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "type": "field",
        "outboundTag": "WARP",
        "domain": [
          "geosite:google",
          "geosite:openai",
          "geosite:netflix",
          "geosite:spotify"
        ]
      },
      {
        "inboundTag": [
          "inbound-32470"
        ],
        "outboundTag": "WARP",
        "type": "field"
      }
    ]
  },
  "stats": {}
}
```

**Comment by Saleh-Mumtaz** [comment]
کد به صورت بهینه ترین شکل خودش رو داره و کمترین اختلال برای کانفیگ پشت وارپ ایجاد می‌شود:
‍‍‍‍‍```
[
  {
    "inboundTag": [
      "api"
    ],
    "outboundTag": "api",
    "type": "field"
  },
  {
    "type": "field",
    "outboundTag": "WARP",
    "inboundTag": [
      "inbound-32470"
    ]
  },
  {
    "type": "field",
    "outboundTag": "WARP",
    "domain": [
      "geosite:google",
      "geosite:openai",
      "geosite:netflix",
      "geosite:spotify"
    ]
  }
]
```
