### ISSUE TITLE
Issue with editing shadowsocks clients on 3X-UI 1.7.6

### ISSUE THREAD

**Issue by Dr4tez** [MHSanaei/3x-ui#884]
![1](https://github.com/MHSanaei/3x-ui/assets/98910606/046a7c74-c1e2-47a0-a12d-8ab555cbb3e5)
![2](https://github.com/MHSanaei/3x-ui/assets/98910606/68e34727-6a34-41d0-aa8e-f45614b88308)
### Welcome

- [x] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

If there are two or more shadowsocks clients, then when editing any of them, only the first client is edited. The same problem was on 3X-UI 1.7.5. There is no such problem on 3X-UI 1.7.1.
A friend of mine has the same situation.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by jeet8200** [comment]
same here cant edit shadow socks(the ones with more than 1 client ) second client each time show the first client data to edit with 17.5&6

**Comment by alireza0** [comment]
Thank you for reporting this issue.
It will be fixes in next version
