### ISSUE TITLE
CPU spikes to 100 every few seconds

### ISSUE THREAD

**Issue by Stevemoretz** [MHSanaei/3x-ui#895]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

If you keep looking at `htop` output or the cpu usage in UI in the panel, you'll see every few seconds this happens this has nothing to do with number of users as the server has only one user and it keeps going back to 1% then 100% and it keeps happening every few seconds, this has been happening for quite some time now and makes the connection too slow, the same thing happened at version 1.7.5, all clean install and no upgrades and still happened and still does for 1.7.6.

<img width="332" alt="Screen Shot 1402-05-20 at 19 44 29" src="https://github.com/MHSanaei/3x-ui/assets/27680142/0aa3e73c-428b-4ddb-bb9c-ce11a96145ac">
<img width="503" alt="Screen Shot 1402-05-20 at 19 43 34" src="https://github.com/MHSanaei/3x-ui/assets/27680142/c6477776-774d-4016-a96e-edde8ec1f3f9">

### Version of 3x-ui

<details>

```console
1.7.6, 1.7.5
```

</details>

### x-ui log reports or xray log

<details>

```console
empty for today.
```

</details>

**Comment by Stevemoretz** [comment]
Is `x-ui` process the web-panel itself? can we disable it for now and let the xray itself run still?

**Comment by AEydi** [comment]
تو یکی دوتا نسخه اخیر این شکلی شده
برای مثال قبلا کلا cpu روی 10 درصد بوده
ولی الان چند ثانیه یه بار به 100 میرسه
![image](https://github.com/MHSanaei/3x-ui/assets/22270854/59746646-df96-482b-a840-2c4e84819242)
این مقدار مموری که نشون میدین روز به روز مقدارش بیشتر میشه و میزان مصرف cpu هم متعاقبش بیشتر میشه
ریستارت که میکنیم کمی پایین میاد ولی دوباره بالا میره
قبلا این مشکل رو نداشت

**Comment by AEydi** [comment]
> ### Welcome
> * [x]  Yes, I'm using the latest major release. Only such installations are supported.
> * [x]  Yes, I'm using the supported system. Only such systems are supported.
> * [x]  Yes, I have read all WIKI document,nothing can help me in my problem.
> * [x]  Yes, I've searched similar issues on GitHub and didn't find any.
> * [x]  Yes, I've included all information below (version, config, log, etc).
> 
> ### Description of the problem,screencshot would be good
> If you keep looking at `htop` output or the cpu usage in UI in the panel, you'll see every few seconds this happens this has nothing to do with number of users as the server has only one user and it keeps going back to 1% then 100% and it keeps happening every few seconds, this has been happening for quite some time now and makes the connection too slow, the same thing happened at version 1.7.5, all clean install and no upgrades and still happened and still does for 1.7.6.
> 
> <img alt="Screen Shot 1402-05-20 at 19 44 29" width="332" src="https://user-images.githubusercontent.com/27680142/260059825-0aa3e73c-428b-4ddb-bb9c-ce11a96145ac.png"> <img alt="Screen Shot 1402-05-20 at 19 43 34" width="503" src="https://user-images.githubusercontent.com/27680142/260059842-c6477776-774d-4016-a96e-edde8ec1f3f9.png">
> ### Version of 3x-ui
> ### x-ui log reports or xray log

I think the issue comes from utilizing an outdated database on the new panel. Deleting the clients and subsequently recreating them with the same email and id should resolve this problem.

**Comment by skylastn** [comment]
same issue @Stevemoretz

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
