### ISSUE TITLE
یک سوال مهم در مورد وارپ لظفا اگه کسی بلده جواب بده

### ISSUE THREAD

**Issue by navid221** [MHSanaei/3x-ui#897]
سلام وقت همگی بخیر باشه. طبق اطلاعاتی که به دست آوردم میشه فقط با یه سرورایران و فعال کردن وارپ روی کل سرور فیلترینگ رو دور زد. خیلیا همین کارو کردن و جواب داده. و چون منم از اپلیکیشن وارپ 1.1.1.1 روی گوشی استفاده میکنم و راحت همه سایت ها رو باز میکنه خواستم همین روش رو روی سرور ایران پیاده کنم ولی وقتی وارپ فعال میشه سرور قطع میشه حتی اومدم به صورت دستی فقط یه سایت بخصوص رو از سرور وارپ کردم و اون سرور دیگه باز نشد. به عبارت دیگه هر سایتی که از روی سرور وارپ بشه باز نمیشه ولی سایت های عادی که فیلتر نیستن باز میشه گفتم شاید مشکل از اسکریپت وارپ پنل هستم به همین خاطر رفتم و اسکریپت yonggekkk رو تست کردم و جالب اینه وقتی دستور نصب رو میزنم هیچ اتفاقی نمیوفته! در حالی که این اسکریپت روی همه ی سرورهای خارجم راحت نصب میشه! گفتم شاید سرور ایران وارپ رو محدود کرده رفتم 1.1.1.1 رو پینگ گرفتم اوکی بود و ایپی های کلودفلیر راحت پینگ میدادن! کسی میدونه مشکل از کجاست؟ چرا با فعال شدن وارپ سایت ها باز نمیشن؟ و چرا اسکریپتyonggekkk  رو سرور نصب نمیشه؟؟؟؟؟

**Comment by Arman-nsb** [comment]
روی اکثر سرورهای ایران قابلیت warp مسدود شده و امکان فعالسازی نداره. ( حداقل ابرآروان رو مطمئنم که بلاک کرده)
