### ISSUE TITLE
Multi domain for reality 

### ISSUE THREAD

**Issue by Morghak963** [MHSanaei/3x-ui#903]
سلام وقت بخیر
درصورت امکان قابلیت multi domain name برای قسمت ریالیتی هم فعال بشه
در قسمت های دیگه با زدن روی دکمه multi domain امکان اضافه کردن چندتا وجود داره ولی در قسمت ریالیتی بیشتر از یکی نمیشه

ممنون میشم این قابلیت فعال بشه
با تشکر🌹

**Comment by misagh72** [comment]
multi domain برای ریلیتی کاربردی نداره

**Comment by Morghak963** [comment]
چرا داره
من الان واسه ریالیتی ساب میدم به یوزر
وقتی مولتی دامین باشه
دوتا دامین مختلف میزنم که وقتی ساب رو آپدیت میکنه دوتا کانفیگ براش بیار با دامین مختلف
یکی تانل واسه همراه مثلا ، یکی غیر تانل

**Comment by thecyanide** [comment]
امیدوارم هرچه زودتر اضافه بشه. یه کاربرد دیگش برا استفاده از هردو ipv4 و ipv6 در سابسکریپشن هست که اگه الان بخوایم اینطوری به ساب اضافه کنیم باید روی یک پورت دیگه ipv6 رو بزنیم.

**Comment by master88wi** [comment]
+1

**Comment by vR3za** [comment]
+1

**Comment by master88wi** [comment]
+1
