### ISSUE TITLE
 ERROR - location <Asia/Tehran> not exist, using default location: Asia/Tehran

### ISSUE THREAD

**Issue by ali6344** [MHSanaei/3x-ui#905]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Aug 14 12:13:51 paris /usr/local/x-ui/x-ui[529]: ERROR - location <Asia/Tehran> not exist, using default location: Asia/Tehran

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by ali6344** [comment]
Ubuntu 23.04

**Comment by behnamgolds** [comment]
```
apt install --reinstall tzdata
```

**Comment by silenceleaf** [comment]
windows version has same error
