### ISSUE TITLE
مسدود نشدن

### ISSUE THREAD

**Issue by OghabTeam** [MHSanaei/3x-ui#906]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

توی نسخه جدید بعد از به اتمام رسیدن حجم سرویس داخل ui نشون میده که مسدود شده ولی درواقع فعال هست و همچنان میتونن ازش استفاده کنن :// خیلی خیته این باگ لطفا درستش کنید تشکر

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
تست شد مشکلی وجود نداره
