### ISSUE TITLE
نصب WARP

### ISSUE THREAD

**Issue by Parsa-n** [MHSanaei/3x-ui#909]
سلام. نصب وارپ همیشه طول میکشه ؟ چون برا من یه 20 دقیقه ای همینجور تو نصب مونده. عکسشم میزارم الان.
![image](https://github.com/MHSanaei/3x-ui/assets/77966472/27d78fdf-3c51-4fae-89df-9ee5524c65d2)

**Comment by MHSanaei** [comment]
قبلش سرورتون رو اپدیت کنید
