### ISSUE TITLE
Direct Country Settings Doesn't work for RU IPs & domains

### ISSUE THREAD

**Issue by westruk** [MHSanaei/3x-ui#910]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Direct Country Configs Settings doesn't work for RU IPs & domains

![изображение](https://github.com/MHSanaei/3x-ui/assets/64413688/fc7f6c4f-5567-4f2c-801e-a78e644c5005)

### Version of 3x-ui

v1.7.6

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Nuke142** [comment]
Same trouble

**Comment by zertf** [comment]
Same problem. These settings don't seem to be working at all. (not only RU)

**Comment by Sergo1217** [comment]
2.2.1 same

**Comment by Nuke142** [comment]
Lol 💩
![7975591_0](https://github.com/MHSanaei/3x-ui/assets/19406558/4263b76c-feae-4e6f-9949-8c942b5881af)

**Comment by westruk** [comment]
@MHSanaei why you close issue?

**Comment by MHSanaei** [comment]
Became there is no issue, you guys just don't know how to use it
Direct work when you have more than one server and don't want to for example your traffic Russian domains connect to a second server then you can use direct

**Comment by Sergo1217** [comment]
> Became there is no issue, you guys just don't know how to use it Direct work when you have more than one server and don't want to for example your traffic Russian domains connect to a second server then you can use direct

It is worth mentioning this in the readme.

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/commit/95416cd553e32adbaf02058460866c3ba48a9acd

**Comment by zertf** [comment]
Thank you!
