### ISSUE TITLE
مشکل وارپ. لطفا هرکی میدونه جواب بده

### ISSUE THREAD

**Issue by Parsa-n** [MHSanaei/3x-ui#911]
سلام. وارپ رو فعال کردم و تو قسمت دامین هم گذاشتم ولی https://developer.android.com/studio از این سایت نمیتونم چیزی دانلود کنم و ارور 404 بهم میده. چجوری حلش کنم ؟؟

**Comment by sadegh1210** [comment]
سایتی ک مدنظرت هست ک از وارپ رد بشه رو برو تو قسمت manual list و List of WARP Domains و سایتت رو اینجوری بزار داخلش : "developer.android.com"
