### ISSUE TITLE
مشکل دکمه سویچ کلاینت

### ISSUE THREAD

**Issue by farid220** [MHSanaei/3x-ui#913]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام وقتتون بخیر

اول از همه تشکر میکنم بابت زحمتی که واسه این پنل کشیدید.
بنده به یه مشکلی بر خوردم و البته مشکل کوچیکیه.
ظاهرا فایل ریلیز یکم با سورس متفاوته و زمانی که بنده سورس رو کامپایل میکنم تو UI یه مشکلی میبینم که تو نسخه Release نیست.
کلاینت ها (ایمیل ها) یه دکمه تاگل مانندی دارن که Enable/Disable میشه کرد. وقتی سورس رو کامپایل میکنیم این Button درست کار نمیکنه و توی دیباگر خطای TypeError: clients[index] is undefined رو میده. ممنون میشم یه بررسی بکنید.

با تشکر

### Version of 3x-ui

<details>

```console
v1.7.6 (Source Code)
```

</details>

### x-ui log reports or xray log

X-UI Front Browser Debugger message:
TypeError: clients[index] is undefined

How to reproduce:
1- COMPILE the source
2- Open the X-UI Panel
3- Expand the Inbound
4- Click on the (Enable/Disable) Switch button for any (client/Email)

**Comment by farid220** [comment]
در فایل http://URL:PORT/panel/inbounds و در خط 1145 ما اینا رو داریم:
index = this.findIndexOfClient(clients, client);
                clients[index].enable = !clients[index].enable;
و تابع findIndexOfClient میاد مقدار "-1" (منفی یک) رو به عنوان index برمیگردونه

**Comment by farid220** [comment]
مشکل رو پیدا کردم:
 در فایل Inbouds.html این قطعه کد رو عوض کردم:
findIndexOfClient(clients, client) {
     return clients.findIndex(item => JSON.stringify(item) === JSON.stringify(client));
}
به:

findIndexOfClient(clients, client) {
     firstKey = Object.keys(client)[0];
     return clients.findIndex(c => c[firstKey] === client[firstKey]);
},
زمانی که ایندکس client در متغییر client میگشت چون زیر متغییر client.enable متفاوت از آنچه در clients هست بود باعث میشد بجای ایندکسش عدد منفی 1 برگرده.
و با اینکار درست شد. لطفا در سورس اصلاحش کنید.

**Comment by farid220** [comment]
زمانی که تابع میخواست ایندکس متغییر client در متغییر clients پیدا کنه چون زیر متغییر client.enable متفاوت از آنچه در clients هست بود باعث میشد عدد منفی 1 به عنوان ایندکس برگرده و ارور بخوره و پست دیتا updateClient رو هم ارسال نکنه.

لطفا در سورس با صلاحدید خودتون اصلاحش کنید. باتشکر

**Comment by MHSanaei** [comment]
این تغییر https://github.com/MHSanaei/3x-ui/commit/ae7283fc730fd64ab91f39c2c8947efce1009525 به خاطر این مشکل بود #884
و برای حل مشکل enable مهندس علیرضا زحمت کشیدن این تغییر رو ایجاد کردن 
https://github.com/MHSanaei/3x-ui/commit/edfc2d8d9350611f68d0be881dc045f04eb38691

ممنون از توجه شما

**Comment by Ghasem1243** [comment]
چطور سورس را کامپایل کنم ؟؟
