### ISSUE TITLE
xray state: Not Running

### ISSUE THREAD

**Issue by farazt69** [MHSanaei/3x-ui#914]
سلام وقت بخیر
وضعیت با رنگ قرمز به حالا Not Running درمیاد بعد چند دقیقه از نصب 
یکی دوبار هم سیستم عامل سرور رو تغییر دادم اوبانتو22 ولی همچنان همینطوریه

**Comment by MHSanaei** [comment]
لاگ پنل رو بررسی کنید مشکل مشخص میشه
