### ISSUE TITLE
چرا API مجزا طراحی شده ؟

### ISSUE THREAD

**Issue by vR3za** [MHSanaei/3x-ui#916]
سلام وقت بخیر 
چرا برای ارتباط با پنل API مجزا طراحی شده 
خود پنل یک سری API داره 
اگر از اون ها استفاده کنیم چی میشه ؟

**Comment by mehdikhoram** [comment]
احتمالا API های اصلی پنل محدود به خود پنل و زیر دامنه های پنل هست و شما دسترسی از خارج نخواهید داشت. یا به عبارتی CORS وجود ندارد.
