### ISSUE TITLE
سرورم فیلتر نیست اما وارد پنل نمیشه و فقط با وی پی ان وارد مبشه

### ISSUE THREAD

**Issue by shayan-py** [MHSanaei/3x-ui#920]
سرورم فیلتر نیست اما وارد پنل نمیشه و فقط با وی پی ان وارد مبشه کانفیگ هم میسازم کار نمیکنه لطفا کمک کنید

**Comment by saeidpour80** [comment]
سلام

**Comment by saeidpour80** [comment]
سلام
وقت بخیر
احتمالا رو سرورتون فایروال فعاله و همین باعث ایجاد این مشکل شده
باید پورت ورود به پنل و همچنین پورت 80 و 443 رو در فایروال باز کنید
اگه از فایروال ufw استفاده می کنید از دستورات زیر استفاده کنید :
sudo ufw allow پورت پنل
sudo ufw allow 80
sudo ufw allow 443
و همچنین پورت کانفیگایی رو هم که میسازید باید برای فایروال تعریف کنید
مثلا اگه پورت یک کانفیگ 2222 باشه، باید دستور زیر پورتشو در فایروال ufw آزاد کنید :
sudo ufw 2222
و اگر از فایروال iptables استفاده می کنید، همون دستورات بالا به شکل زیر میشن :
sudo iptables -A INPUT -p tcp --dport پورت پنل -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
sudo iptables -A OUTPUT -p tcp --sport پورت پنل -m conntrack --ctstate ESTABLISHED -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 80 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
sudo iptables -A OUTPUT -p tcp --sport 80 -m conntrack --ctstate ESTABLISHED -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
sudo iptables -A OUTPUT -p tcp --sport 443 -m conntrack --ctstate ESTABLISHED -j ACCEPT
sudo iptables -A INPUT -p tcp --dport پورت کانفیگ -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
sudo iptables -A OUTPUT -p tcp --sport پورت کانفیگ -m conntrack --ctstate ESTABLISHED -j ACCEPT
و اگر پرتکول کانفیگتون udp است بجای tcp باید udp جایگزین بشه :
sudo iptables -A INPUT -p udp --dport پورت کانفیگ -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
sudo iptables -A OUTPUT -p udp --sport پورت کانفیگ -m conntrack --ctstate ESTABLISHED -j ACCEPT

**Comment by maaffii79** [comment]
سلام، وقت شما بخیر؛
من هم همچین مشکلی دارم (البته مشکل کانفیگ ندارم)، سرورم فیلتر نیست ولی پنل رو بایستی با فیلترشکن باز کنم؛ همچنین وقتی لینک Subscription رو که وارد نرم‌افزار مربوطه میکنم، هر چقدر روی گزینه Update Subscription میزنم، کانفیگ‌ها اضافه نمیشن مگر اینکه یه فیلترشکن دیگه روشن کنم.
پیشنهادی که دادید رو تست کردم ولی در قدم اول اصلا فایروالی رو سرورم نصب نبود، برای تست فایروال ufw رو نصب کردم و پورت‌های 80 و 443 رو باز کردم، ولی بازم مشکل حل نشد.
اگر ممکنه یه راهنمایی داشته باشید.
با تشکر

**Comment by hosein-moayedi** [comment]
@maaffii79 
سرورت فیلتر داداش
فیلترینگ جدید سرعت رو روی ۱۰ کیلوبیت لیمیت میکنه و حتی پنل رو هم نمیتونی بیاری
مشکل ریلیتی مستقیم که جدیدا دارن تشخصیش میدن

از تانل استفاده کن
