### ISSUE TITLE
راهی هست اکانتی که شر کرده کانکشن رو پیدا کرد؟

### ISSUE THREAD

**Issue by elegance666** [MHSanaei/3x-ui#921]
من یک مشکلی دارم با اینکه تمام اکانت ها آی پی لیمیت دارند اما پهنای باند استفاده شده خیلی بالاست، راهی هست بفهمم کدوم اکامته چون IP LIMIT به نظرم کار نمیکنه

**Comment by MHSanaei** [comment]
اگر از مدت نصب fail2ban بیشتر از یک ماه میگذره
از طریق منوی پنل حذف کنید مجدد نصب کنید
مدت زمان بن شدن ای پی هم زیاد کنید

**Comment by elegance666** [comment]
الان سرچ کردم fail2ban  برای apache log استفاده میشه، توی پنل شما گذاشته شده، یا راهنمایی هست برای تنطیمش با پنل شما؟

**Comment by elegance666** [comment]
پیداش کردم ولی این پیام میده زمان نصب:


Fail2ban installed successfully!

Configuring IP Limit...

/usr/bin/x-ui: line 789: /etc/fail2ban/jail.d/3x-ipl.conf: No such file or directory
/usr/bin/x-ui: line 800: /etc/fail2ban/filter.d/3x-ipl.conf: No such file or directory
/usr/bin/x-ui: line 807: /etc/fail2ban/action.d/3x-ipl.conf: No such file or directory
Created Ip Limit jail files with a bantime of 5 minutes.
Failed to start fail2ban.service: Unit fail2ban.service not found.
Failed to enable unit: Unit file fail2ban.service does not exist.
IP Limit installed and configured successfully!

**Comment by elegance666** [comment]
service fail2ban status
Unit fail2ban.service could not be found.

**Comment by elegance666** [comment]
حل شد ممنوم
