### ISSUE TITLE
API

### ISSUE THREAD

**Issue by maltima** [MHSanaei/3x-ui#922]
python:

URL = "https://xxxx.com:8080/path/"

USERNAME = "uname"
PASSWORD = r"@ahsbsg"

url_login = "login"
url_lists = "xui/inbound/list"
url_sanaei = "panel/api/inbounds/list/"

session = requests.Session()

payload = {
    "username": USERNAME,
    "password": PASSWORD
}

response = session.post(URL + url_login, data=payload)
if response.status_code == 200:
    print("success")

panel_data = session.post("https://xxxx.com:8080/path/panel/api/inbounds/list/").content
print(panel_data)

خروجی:
success
b'404 page not found'

هیچ جوره نمیتونم لیست کنم حتی از ادرس های
panel/inbound/list
panel/api/inbounds/list/
و... استفاده کردمو نشد
لطفا راهنمایی کنید

**Comment by Ghasem1243** [comment]
از هدر استفاده نکردی باید از هدر استفاده کنی

**Comment by mehdikhoram** [comment]
برای دریافت لیست باید از متد `GET` استفاده کنید.

```python
import requests

url = "http://localhost:2053/panel/api/inbounds/list"

payload = {}
headers = {
  'Accept': 'application/json',
  'Cookie': 'session={session_id}'
}

response = requests.request("GET", url, headers=headers, data=payload)
```
