### ISSUE TITLE
nginx

### ISSUE THREAD

**Issue by rasa68** [MHSanaei/3x-ui#925]
همراه با نصب پنل ثنایی nginx  هم نصب و فعال میشه رو سرور یا باید خودمون نصب کنیم؟
با نصب بعضی از پنل ها مثل هیدیفای nginx هم به صورت خودکار نصب و فعال میشه.

**Comment by MHSanaei** [comment]
این پنل و پنل های مشابه x-ui نیازی به ngnix ندارند
