### ISSUE TITLE
امكان آدرس دامنه متفاوت براي سابسكريپشن و كانفيگ

### ISSUE THREAD

**Issue by sm-saeedmoosavi** [MHSanaei/3x-ui#926]
سلام
اول بابت بروزرسانيهاي خوب و مخصوصا نشان دادن حجم و زمان در سابسكريپشن خيلي تشكر ميكنم.
الان اگر براي سابسكريپشن يك دامنه تعريف كنيم، توي كانفيگهاي tcp و ws هم همون دامنه رو بجاي سرور ميندازه و براي اين نوع از كانفيگها نميشه دامنه متعلق به دانلود سابسكريپشن با دامنه داخل كانفيگ متفاوت باشه. ولي كانفيگ از نوع reality امكان تعريف دامنه مجزا داخل خودش داره و ميشه آدرس ساب يه چيز باشه و آدرسي كه توي كانفيگ ميشينه چيز ديگه.
اگر بشه اين امكان براي tcp و ws هم ايجاد بشه خيلي خوب ميشه.

ممنون

**Comment by sm-saeedmoosavi** [comment]
البته وقتي tls فعال بشه امكان تعريف نام دامنه هم توش هست. ولي براي حالت بدون tls منظورم هست كه امكانش تعريف نام دامنه باشه

**Comment by hamed0mh** [comment]
منم چند بار گفتم آقای سنایی جواب نمیدن بابت این مشکل

**Comment by MHSanaei** [comment]
شما میتونید توی تنظیمات قسمت subscription دامنه جداگانه تعریف کنید که کاملا با دامنه پنل متفاوت باشه

**Comment by GOLSEFIDI** [comment]
من با به یه هاست و کد زیر تونستم آدرس دامنه را متفاوت کنم 
<?php

$base="https://server.com:2096"; //server address
$url1 =substr( basename ( $_SERVER['REQUEST_URI'] ),1);

$url= $base . $url1;
$ch = curl_init("$url");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);  
$output = curl_exec($ch);  


$s1=   base64_decode($output);
$s2=json_decode($s1 , true);
 $s2["add"]="server2.com";  //change address
 
$r3=json_encode($s2);
$r4 =(base64_encode($r3));

echo $r4;
curl_close($ch);

?>
