### ISSUE TITLE
ساب

### ISSUE THREAD

**Issue by Ghasem1243** [MHSanaei/3x-ui#927]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

مشکل ساب دارد لینک ساب اگر با زبان فارسی نوشته شده باشد به زبان مرورگر تبدیل نمیشود 
و مشکل دیگر اینه که لینک ساب با  base64 رمزگذاری شده و برنامه v2box در آیفون از base64 پشتیبانی نمیکند لطفا یک کلید در تنظیمات بزارید که اگر تیک برداشته شود به صورت رمزگذاری نباشد 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
https://github.com/MHSanaei/3x-ui/issues/928#issuecomment-1684884925
