### ISSUE TITLE
ساب

### ISSUE THREAD

**Issue by Ghasem1243** [MHSanaei/3x-ui#928]
مشکل ساب دارد لینک ساب اگر با زبان فارسی نوشته شده باشد به زبان مرورگر تبدیل نمیشود 
و مشکل دیگر اینه که لینک ساب با  base64 رمزگذاری شده و برنامه v2box در آیفون از base64 پشتیبانی نمیکند لطفا یک کلید در تنظیمات بزارید که اگر تیک برداشته شود به صورت رمزگذاری نباشد

**Comment by MHSanaei** [comment]
بهتره به پشتیبانی اون برنامه پیام بدید و base64 رو اضافه کنه
