### ISSUE TITLE
عبور ترافیک ربات تلگرام از پراکسی Socks5

### ISSUE THREAD

**Issue by wulfric93** [MHSanaei/3x-ui#930]
سلام وقتتون به خیر 
من warp روی سرور نصب کردم (سرور ایران)
ربات تلگرام رو راهی هست که ترافیک ش از پروکسی warp عبور بده ؟

**Comment by wulfric93** [comment]
یعنی منظورم ربات تلگرام متصل به پنل هست که روی سرور ایران کار نمیکنه

**Comment by amin3536** [comment]
https://superuser.com/questions/854653/redirect-web-traffic-socks-proxy-for-a-specific-domain
this link can helpful

**Comment by wulfric93** [comment]
how can I route all of the system(VPS) traffic through a local socks5 proxy ? for example tor or warp ?
