### ISSUE TITLE
SSL for docker

### ISSUE THREAD

**Issue by amirhossein5592** [MHSanaei/3x-ui#933]
یا سلام میشه لطفا توضیح بدین چطور میشه برای پنلی که روی داکر هست SSl بگیریم ممنون میشم کسی بگه

**Comment by antonavy** [comment]
I am struggling to understand that too @MHSanaei

**Comment by maanimis** [comment]
یا سلام میشه لطفا توضیح بدین چطور میشه برای پنلی که روی داکر هست SSl بگیریم ممنون میشم کسی بگه



I am struggling to understand that too @MHSanaei

بعد اینکه روی داکر بالا اوردین با این مراحل:
https://github.com/MHSanaei/3x-ui#install-with-docker
اتومات یه دایرکتوری به اسم cert ساخته میشه cd میکنی بهش بعد نوبت نصب ssl میرسه:
https://github.com/MHSanaei/3x-ui#certbot
این دستوراتو به نوبت میزنید (که بجای yourdomain.com باید دامین خودتون باشه) که توی دستور دوم یه خروجی به این شکل هستش:
```
Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/yourdomain/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/yourdomain/privkey.pem
```
اینو داشته باشید که بعد زدن دستور سوم میریم که همینارو کپی کنیم:
```
cp /etc/letsencrypt/live/yourdomain/fullchain.pem ./
cp /etc/letsencrypt/live/yourdomain/privkey.pem ./
```
خب الان میرید داخل پنل بدین شکل وارد میکنید:`
```
/root/cert/fullchain.pem
/root/cert/privkey.pem
```

![image](https://github.com/MHSanaei/3x-ui/assets/106465992/ae865dbc-2b42-42cf-bcf4-2aa2105d685b)


سیو و ریستارت کنید و تامام

**Comment by Chipmax64** [comment]
1. In the docker-compose.yml file, replace

   - $PWD/cert/:/root/cert/
to
   - /etc/letsencrypt/:/etc/letsencrypt/:rw
   
3. docker compose down

4. docker compose up -d

5. In the web panel set:

/etc/letsencrypt/live/yourdomain/fullchain.pem
/etc/letsencrypt/live/yourmain/privkey.pem

6. Only after installing two certificates in the web panel, save and reload it.
