### ISSUE TITLE
آدرس دامنه وارد شده در تنظیمات سابسکریپشن، داخل کانفیگ نیاید

### ISSUE THREAD

**Issue by sm-saeedmoosavi** [MHSanaei/3x-ui#934]
سلام.
اول از اینکه کامنتها را میخونید و با حوصله جواب میدین سپاسگزارم.
من قبلا هم این مورد رو گفته بودم و شما جواب دادین که دامنه سابسکریپشن بصورت مجزا از دامنه پنل قابل تعریفه که این موضوع رو میدونستم و منظور سوالم این نبود.
منظورم اینه که اگر شما یک دامنه متفاوت برای تنظیمات سابسکریپشن تعریف کرده باشید، حالا وقتی یک کانفیگ ساده tcp یا ws (بدون tls) ایجاد کنید، و با سابسکریپشن لینک اون رو دریافت و ملاحظه کنید خواهید دید که داخل کانفیگی که بهتون تحویل میده آدرس دامنه سابسکریپشن  بعنوان آدرس سرور نشسته. درحالیکه من میخوام آدرس دامنه دیگه ای که به سرور ایرانم اشاره میکنه داخل کانفیگ بشینه.
این مورد مخصوصا برای کسانی که از تونل استفاده میکنند و میخواهند یک دامنه مجزا از دامنه سابسکریپشن برای اشاره به سرور ایران توی کانفیگ داشته باشند مسئله است.

با تشکر
سعید

**Comment by sm-saeedmoosavi** [comment]
این مورد مورد درخواست زیاد داره: https://github.com/MHSanaei/3x-ui/issues/940
کافیه فیلد domain از قسمت تنظیمات tls بیاد بیرون و داخل تنظیمات اصلی کانفیگ قرار بگیره.
اگر انجام بشه مشکل خیلی ها که تونل میزنند برطرف میشه.

**Comment by razidvb** [comment]
مشکل خیلیهاست ک اگر رفع بشه بسیار عالی میشه
