### ISSUE TITLE
سرورم فیلتر نیست اما وارد پنل نمیشه و فقط با وی پی ان وارد مبشه فایور وام هم قیر فغال هست

### ISSUE THREAD

**Issue by shayan-py** [MHSanaei/3x-ui#935]
سرورم فیلتر نیست اما وارد پنل نمیشه و فقط با وی پی ان وارد میشه فایور وال هم غیر فعال هست

**Comment by hosein-moayedi** [comment]
سرورت فیلتر داداش
فیلترینگ جدید سرعت رو روی ۱۰ کیلوبیت لیمیت میکنه و حتی پنل رو هم نمیتونی بیاری
مشکل ریلیتی مستقیم که جدیدا دارن تشخصیش میدن

از تانل استفاده کن

**Comment by hosein-moayedi** [comment]
@shayan-py
