### ISSUE TITLE
مشکل همراه اول

### ISSUE THREAD

**Issue by Gray13hat** [MHSanaei/3x-ui#937]
پنل روی همراه اول بالا نمیاد. وارد ترمینال میشه شد. یعنی با نت همراه میشه Shh زد به سرور ولی پنل و کاربرهای همراه اولی نمیتونن وصل بشن. پورت های پنل و کانفیگ‌ها هم بازه.

لطفا اگه کسی راهی بلده بگه مشکل خیلیاست.

**Comment by hosein-moayedi** [comment]
@Gray13hat 
آی پیت فیلتر شده
ربطی به اوپراتور نداره
احتمالا یا خودت یا نفر قبلی اومده از ریلیتی مستقیم استفاده کرده و آی پی فیلتر شده. فیلترینگ جدید هم اینطوری که سرعت رو لیمیت میکنن روی ۱۰ کیلوبیت که فقط بتونی ssh و پینگ و این چیزا رو بگیری ولی نمیتونی به عنوان وی پی ان استفاده کنی. حتی پنل و نمیتونی لود کنی

باید از تانل استفاده کنی وگرنه کله آی پی های تمیز رو فیلتر میکنید. یا دیگه از ریلیتی استفاده نکن و tcp+tls بزن برای مستقیم و وارپ هم کامل روشن کن

**Comment by Gray13hat** [comment]
> @Gray13hat آی پیت فیلتر شده ربطی به اوپراتور نداره احتمالا یا خودت یا نفر قبلی اومده از ریلیتی مستقیم استفاده کرده و آی پی فیلتر شده. فیلترینگ جدید هم اینطوری که سرعت رو لیمیت میکنن روی ۱۰ کیلوبیت که فقط بتونی ssh و پینگ و این چیزا رو بگیری ولی نمیتونی به عنوان وی پی ان استفاده کنی. حتی پنل و نمیتونی لود کنی
> 
> باید از تانل استفاده کنی وگرنه کله آی پی های تمیز رو فیلتر میکنید. یا دیگه از ریلیتی استفاده نکن و tcp+tls بزن برای مستقیم و وارپ هم کامل روشن کن

اگه فیلتر شده چرا پینگ میده؟ چرا هدر کلود فلر میزنی جواب میده

**Comment by Whh-32** [comment]
منم به همین مشکل بر خوردم ولی تمام سرویس های روی سرورم بالا و داره کار میکنه فقط پنل لود نمیشه و برای همراه اول کار نمیکنه
