### ISSUE TITLE
نیاز به تغییر دستی آدرس وقتی کانفیگ TLS نیست

### ISSUE THREAD

**Issue by ach1992** [MHSanaei/3x-ui#940]
سلام خسته نباشید
وقتی تونل میزنیم دامنه ایران خب متفاوت از دامنه پنل هست اگر کانفیگی که میدیم tls نباشه وقتی خروجی کیوآرکد میگیریم خودکار دامنه پنل گذاشته میشه و مجبوریم دستی به دامنه تونل ایران تغییر بدیم 
اگر امکانی اضافه بشه که حتی در کانفیگ های غیر tls بشه تنظیم کرد address چی باشه خیلی خوبه اینجوری دیگه لازم نیست کانفیگ رو هر بار خروجی بگیری و دوباره دستی تغییر بدی و بعد بدی به مشتری
با تشکر

**Comment by sm-saeedmoosavi** [comment]
من هم این موضوع رو مطرح کرده بودم(https://github.com/MHSanaei/3x-ui/issues/934) و بنظرم خیلی لازمه و احتمالا خیلی تغییرات اساسی نخواد.
کافیه فیلد domain از قسمت تنظیمات tls بیاد بیرون و داخل تنظیمات اصلی کانفیگ قرار بگیره.
اگر انجام بشه مشکل خیلی ها که تونل میزنند برطرف میشه.
