### ISSUE TITLE
اضافه کردن reCAPTCHA در صفحه لاگین

### ISSUE THREAD

**Issue by Hesam-Mahmoodi** [MHSanaei/3x-ui#941]
لطفا در زمان لاگین reCAPTCHA اضافه کنید

**Comment by karo-yousefi** [comment]
اگه از دامنه برای دسترسی به پنل استفاده میکنی میتونی با استفاده از خدمات cloudflare این امکان رو اضافه کنی و قبل ورود به پنل از کپچای کلاودفلیر گذر کنید.

**Comment by Hesam-Mahmoodi** [comment]
روی دامنه هست ولی با ip هم باز میشه و بات تلگرام فعال کردم هر روز تعداد خیلی زیادی لاگین ناموفق نوتیفیکیشن میاد برام! مشخصه که ربات هستش
اگر کپچا یا یک چیزی شبیهش باشه حداقل جلوگیری کنه از این اتفاق

**Comment by karo-yousefi** [comment]
اگه ربات ویز ویز (که برای فروش کانفیگ هست) رو ادی ، ممکن است دلیل اون باشه.
البته اگه میگی ناموفق احتمالش رو کم میکنه. باید بگم که بازم از طریق خدمات کلاوفلیر میشه درسترسی یه کشور خاص به ایپی رو کلا بست یا کپچا فعال کرد. اگه ورود های ناموفق از طریق کشور های دیگه باشن، میتونی کل کشور هارو جز ایران بست تا نتونن به پنل دسترسی پیدا کنن. در اون حالت دیگه خودتم با فیلترشکن نمیتونی وارد پنلت بشی چون ایپیت مال خارج میشه.
از طریق همین ربات پنل سنایی میتونی ایپی طرفی که میخواد وصل بشه رو پیدا کنی و بر اساس اون موقعیتشو تعین کنی تا بعدا راحت در کلاودفلر ببندی.
یه جیز دیگم که ممکن باعث ورود های ناموفق بشه اینه که مشتری هات (یا کلا کسای که بهشون کانفیگ دادی) میخوان وارد پنلت بشن. به ادرس پنلت با ادرس کانفیگ هات یکی نیستن که؟ اگر یکین، در تنظیمات پنل در قسمت Panel URL Root Path، یه چیزی وارد کن. تا ادرس پنلت خود روت دامنه نباشه.
