### ISSUE TITLE
استپ شدن ایکس ری

### ISSUE THREAD

**Issue by ZedSoftOfficial** [MHSanaei/3x-ui#946]
سلام یکی به من بگه این چیه هر چن روز یه بار میاد 

2023/08/22 10:23:15 WARNING - start xray failed:Failed to generate xray configuration file: json: error calling MarshalJSON for type json_util.RawMessage: invalid character ',' looking for beginning of value

**Comment by karimiorg** [comment]
اینباند ها و کلاینت ها هستند یا مخفی شدن؟

**Comment by MHSanaei** [comment]
#995

**Comment by ZedSoftOfficial** [comment]
کلاینت ها مخفی نمیشن اکثر مواقع ولی یکی دوبار هم مخفی شده
