### ISSUE TITLE
Fix GLIBC

### ISSUE THREAD

**Issue by quydang04** [MHSanaei/3x-ui#947]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello, I have installed 3X-UI on my VPS. My VPS is running Ubuntu 20.04.6, and I can't install it on my vps. Can you fix this problem in the next version?
![image](https://github.com/MHSanaei/3x-ui/assets/81231812/7126ec14-cfeb-445d-adf0-939e2b00919f)

### Version of 3x-ui

<details>

```console
1.7.6
```

</details>

### x-ui log reports or xray log

<details>

```console

Initializing, please wait...
/usr/local/x-ui/x-ui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/x-ui/x-ui)
/usr/local/x-ui/x-ui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/local/x-ui/x-ui)
/usr/local/x-ui/x-ui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/x-ui/x-ui)
Account name and password set successfully!
/usr/local/x-ui/x-ui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/x-ui/x-ui)
/usr/local/x-ui/x-ui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/local/x-ui/x-ui)
/usr/local/x-ui/x-ui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/x-ui/x-ui)
Panel port set successfully!
/usr/local/x-ui/x-ui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/x-ui/x-ui)
/usr/local/x-ui/x-ui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/local/x-ui/x-ui)
/usr/local/x-ui/x-ui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/x-ui/x-ui)
Created symlink /etc/systemd/system/multi-user.target.wants/x-ui.service → /etc/systemd/system/x-ui.service.
```
</details>

**Comment by ahwazi12** [comment]
سلام خوبی اگه میشه اکانت های  که غیر فعال  شده رو همه با هم  حذف کرد
