### ISSUE TITLE
Docker: IP Limit not working

### ISSUE THREAD

**Issue by AliBelali** [MHSanaei/3x-ui#949]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

hi
although fail2ban service is running in docker ,IP limit not working at all
I found this issue 
https://github.com/MHSanaei/3x-ui/issues/918
but honestly I have no idea how to make this changes and export an image for other devices
and is there anyway to make it work without  cap_add : - NET_ADMIN
currently on some machines I don't have access to add this flag
@hamid-gh98
thanks
 

### Version of 3x-ui

<details>

1.7.6

</details>

### x-ui log reports or xray log

<details>

</details>

**Comment by hamid-gh98** [comment]
> hi
> although fail2ban service is running in docker ,IP limit not working at all
> I found this issue 
> https://github.com/MHSanaei/3x-ui/issues/918
> but honestly I have no idea how to make this changes and export an image for other devices
> and is there anyway to make it work without  cap_add : - NET_ADMIN
> currently on some machines I don't have access to add this flag
> @hamid-gh98
> thanks
>  

Hello, i though that some ppl may dont want to use ip limit, so i did like this.

u should run the `x-ui` command inside docker, then select ip limit management, and install it, so it will create the files for u.

Hopefully in some days, i will also change it for docker to always create these files, since some other ppl also have this problem.

**Comment by AliBelali** [comment]
thanks a lot
sadly x-ui command not working in docker terminal
`
/ # x-ui
/bin/sh: x-ui: not found
/ # xui
/bin/sh: xui: not found
/ # x
/bin/sh: x: not found
/ # /app/x-ui
2023/08/22 14:56:40 x-ui 1.7.6
2023/08/22 14:56:40 listen tcp :8090: bind: address already in use
/ # 
`
also
`
/ # /app/x-ui setting -fail2ban
flag provided but not defined: -fail2ban
Usage of setting:
  -enabletgbot
        enable telegram bot notify
  -password string
        set login password
  -port int
        set panel port
  -reset
        reset all settings
  -show
        show current settings
  -tgbotRuntime string
        set telegram bot cron time
  -tgbotchatid string
        set telegram bot chat id
  -tgbottoken string
        set telegram bot token
  -username string
        set login username
`

**Comment by AliBelali** [comment]
I worked around a little and copied ip3xl.conf files to fail2ban folders (jail.d,filter.d,action.d) although fail2ban detects which ip should be limited and shows ip in log, It can't drop connection because fail2ban action for ip3xl uses iptables and iptables in docker need net-admin flag to work; sadly net-admin flag is not accessable in my machine so I was wondering is there any way to use old ip limit method instead of fail2ban (method before 1.7.5 I think)?

**Comment by AliBelali** [comment]
Finally I found a solution. I think it's not a good solution and it's a little bit silly , but it worked for me.
I changed 3xipl.conf in action.d to work with route not with iptables so there is no need to have net-admin flag
it will add unreachable route for each ip should be banned
and removes unreachable route for each ip should be unbanned
here is /etc/fail2ban/action.d/3x-ipl.conf:

> [INCLUDES]
> before = iptables-common.conf
> [Definition]
> actionstart = ip route add unreachable 100.64.0.0
> actionstop = ip route del unreachable 100.64.0.0
> actioncheck = ip route show | grep -q 'unreachable 100.64.0.0'
> actionban = ip route add unreachable <ip>
>             echo "$(date +"%%Y/%%m/%%d %%H:%%M:%%S")   BAN   [Email] = <F-USER> [IP] = <ip> banned for <bantime> seconds." >> /var/log/3xipl-banned.log
> actionunban = ip route del unreachable <ip>
>               echo "$(date +"%%Y/%%m/%%d %%H:%%M:%%S")   UNBAN   [Email] = <F-USER> [IP] = <ip> unbanned." >> /var/log/3xipl-banned.log
> [Init]

I think there is no need to

> actionstart = ip route add unreachable 100.64.0.0
> actionstop = ip route del unreachable 100.64.0.0
> actioncheck = ip route show | grep -q 'unreachable 100.64.0.0'

I just filled them to not break something accidentally

**Comment by hamid-gh98** [comment]
> I worked around a little and copied ip3xl.conf files to fail2ban folders (jail.d,filter.d,action.d) although fail2ban detects which ip should be limited and shows ip in log, It can't drop connection because fail2ban action for ip3xl uses iptables and iptables in docker need net-admin flag to work; sadly net-admin flag is not accessable in my machine so I was wondering is there any way to use old ip limit method instead of fail2ban (method before 1.7.5 I think)?

try `--privileged` arg, myb this works.

for old ip_limit method u should change some files, or use version before that.

**Comment by AliBelali** [comment]
thanks
sadly I don't have access to use --privileged too
but today I tested route method for fail2ban seems good
thanks for your guides
