### ISSUE TITLE
api updateClient

### ISSUE THREAD

**Issue by Bestsenator** [MHSanaei/3x-ui#953]
سلام وقتتون بخیر
من با کد پایین درخواست میزنم به سرور برای اپدیت کردن ولی ارور بهم میده 
دیتایی که میخواد ارسال بشه اینطوریه :
{"id": 1, "settings": {"clients": [{"id": "54c53fbb-ab22-454b-ad9d-109bc3d9b2dc", "alterId": 0, "email": "Alireza.Safe-29", "limitIp": 1, "totalGB": 32212254720, "expiryTime": -2592000000, "enable": true, "tgId": "", "subId": "wea53en9paggh69z"}]}}

و بعد با استفاده از json.dumps توی پایتون، تبدیلش میکنم به raw که و توی  contentمیذارم
کد :
url = 'https://{}:{}/panel/api/inbounds/updateClient/{}'.format(infoConfig.Server.Domain, infoConfig.Server.Port,
                                                                    infoConfig.Uuid)
    response = requests.post(url=url, data=content, cookies={'session': str(infoConfig.Server.Session)})
    
    ارور : 
    b'{"success":false,"msg":"Something went wrong!Fail: unexpected end of JSON input","obj":null}'

**Comment by Ghasem1243** [comment]
e = f"id={idinbund}&settings=%7B%22clients%22%3A%20%5B%7B%0A%20%20%22id%22%3A%20%22{uuid}%22%2C%0A%20%20%22flow%22%3A%20%22xtls-rprx-vision%22%2C%0A%20%20%22email%22%3A%20%22{name}%22%2C%0A%20%20%22limitIp%22%3A%20{self.iplimit}%2C%0A%20%20%22totalGB%22%3A%20{total}%2C%0A%20%20%22expiryTime%22%3A%20{expire}%2C%0A%20%20%22enable%22%3A%20true%2C%0A%20%20%22tgId%22%3A%20%22%22%2C%0A%20%20%22subId%22%3A%20%22{subname}%22%0A%7D%5D%7D"

سلام اینطور باید بهش بدی

**Comment by Athirst1998** [comment]
سلام
منم همین ارور رو میگیرم و روش
@Ghasem1243

رو هم پیش رفتم ولی باز ارور میگیرم.

**Comment by Ghasem1243** [comment]
بیا تلگرام  Ghasomi

**Comment by Ghasem1243** [comment]
کلا داری اشتباه میزنی

**Comment by Athirst1998** [comment]
مرسی درستش کردم
@Ghasem1243

**Comment by hr1510** [comment]
درود من هم همین مشکل رو دارم ، میشه راهنمایی کنید 
مقدار زیر ارسال میشه:
{"id":1,"settings":"{\"clients\":[{\"id\":\"280aef07-4a2f-46a4-b43c-bd45d4429946\",\"alterId\":0,\"email\":\"New client\",\"limitIp\":2,\"totalGB\":42949672960,\"expiryTime\":0,\"enable\":true,\"tgId\":\"\",\"subId\":\"\"}]}"}
جواب :
{"success":false,"msg":"Something went wrong!Fail: unexpected end of JSON input","obj":null}

**Comment by hr1510** [comment]
> e = f"id={idinbund}&settings=%7B%22clients%22%3A%20%5B%7B%0A%20%20%22id%22%3A%20%22{uuid}%22%2C%0A%20%20%22flow%22%3A%20%22xtls-rprx-vision%22%2C%0A%20%20%22email%22%3A%20%22{name}%22%2C%0A%20%20%22limitIp%22%3A%20{self.iplimit}%2C%0A%20%20%22totalGB%22%3A%20{total}%2C%0A%20%20%22expiryTime%22%3A%20{expire}%2C%0A%20%20%22enable%22%3A%20true%2C%0A%20%20%22tgId%22%3A%20%22%22%2C%0A%20%20%22subId%22%3A%20%22{subname}%22%0A%7D%5D%7D"
> 
> سلام اینطور باید بهش بدی

با توجه به راهنمایی @Ghasem1243

من با استفاده از php اطلاعات رو برای افزودن کلاینت جدید به کانفگ ارسال میکردم .
البته با استفاده از کد دوستان
منتها این مشکل که برخوردن بابت نوع دیتا ارسال شده به API هست.
که باید دیتا را در قدم اخر با استفاده از http_build_query برای تبدیل آرایه به رشته‌ای از پارامترهای URL-encoded تبدیل کنیم بعد ارسال کنیم و مثلا :
در این کد که اساتید زحمت کشیدن : 
https://github.com/MHSanaei/3x-ui/issues/324
تنظیم پست فیلد برای CURL در متند sendPOST باید به شکل زیر باشد :+1: 
CURLOPT_POSTFIELDS => http_build_query($data),

به جای 
CURLOPT_POSTFIELDS => json_encode($data)
