### ISSUE TITLE
tunneling issue using config.json "core"

### ISSUE THREAD

**Issue by darhelm** [MHSanaei/3x-ui#954]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

last official release to date 
can't tunnel using outbound config on relay server and i suspect it's due to this error
the ports are open, the firewall is down and the destination port returns a ssl certificate  i will include the config file down further in the description 

outbound relay:
{
    "protocol": "trojan",
    "settings": {
      "servers": [
        {
          "address": "domain",
          "port":port,
          "password": "pass"
        }
      ]
    },
    "streamSettings": {
      "network": "tcp",
      "security": "tls"
    }
  }

inbound destination server:
  {
    "listen": "0.0.0.0",
    "port": same port,
    "protocol": "trojan",
    "settings": {
      "clients": [
        {
          "password": "pass",
          "email": "whatever"
        }
      ]
    },
    "streamSettings": {
      "network": "tcp",
      "security": "tls",
      "tlsSettings": {
        "alpn": [],
        "certificates": [
          {
            "certificateFile": "/root/cert.crt",
            "keyFile": "/root/private.key"
          }
        ]
      }
    }
  }

### Version of 3x-ui

<details>

```console
latest official version
```

</details>

### x-ui log reports or xray log

<details>

```console

Aug 23 11:42:57 localhost /usr/local/x-ui/x-ui[2059]: WARNING - access.log doesn't exist in your config.json
Aug 23 11:43:02 localhost x-ui[2059]: [Wed Aug 23 11:43:02 UTC 2023] ERROR Execution error getUpdates: request call: fasthttp do request: dialing to the given TCP address timed out
Aug 23 11:43:02 localhost x-ui[2059]: [Wed Aug 23 11:43:02 UTC 2023] ERROR Getting updates: telego: getUpdates(): internal execution: request call: fasthttp do request: dialing to the given TCP address timed out
Aug 23 11:43:02 localhost x-ui[2059]: [Wed Aug 23 11:43:02 UTC 2023] ERROR Retrying to get updates in 8s


```

</details>

**Comment by darhelm** [comment]
apparently 
this error is for the telegram bot and after turning it off the error message went away on the iran server
telegram is filtered in iran (thought might work on vps but it won't)


Aug 23 11:43:02 localhost x-ui[2059]: [Wed Aug 23 11:43:02 UTC 2023] ERROR Execution error getUpdates: request call: fasthttp do request: dialing to the given TCP address timed out
Aug 23 11:43:02 localhost x-ui[2059]: [Wed Aug 23 11:43:02 UTC 2023] ERROR Getting updates: telego: getUpdates(): internal execution: request call: fasthttp do request: dialing to the given TCP address timed out
Aug 23 11:43:02 localhost x-ui[2059]: [Wed Aug 23 11:43:02 UTC 2023] ERROR Retrying to get updates in 8s

**Comment by dsemagin** [comment]
make sure you have access.log on your Xray Configuration

  "log": {
  "loglevel": "warning",
  "access": "./access.log",
  "error": "./error.log"
  },
