### ISSUE TITLE
پیشهاد برای مشهاده کاربران انلاین

### ISSUE THREAD

**Issue by ho3ein-yazdan** [MHSanaei/3x-ui#955]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام ممنون بابت پنل و  اپدیت ها و زحمات شما 
اگر امکان داره در اپدیت های بعدی امکانی رو اضافه کنید که در صفحه اصلی تعداد کاربانی که در لحظه انلاین هستن رو نشون بده خیلی عالی میشه و فقط جای این اپشن خالیه در پنل 

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by iPbaz** [comment]
و البته جای آپشن نود و اضافه کردن سرور های مختلف به لینک سابسکریپشن هم خالیه.
