### ISSUE TITLE
Open Source 

### ISSUE THREAD

**Issue by Ghasem1243** [MHSanaei/3x-ui#956]
سلام خسته نباشید ممنون از شما 
چطور میتوانم اوپن سورس رو تبدیل به برنامه کنم و نصب کنم یه تغییر کوچک توی سورس انجام دادم که میخوام این رو تبدیل به برنامه کنم ونصب کنم

**Comment by hamid-gh98** [comment]
درود،

```sh
ARCH=$(uname -m)

if [[ "${ARCH}" == "aarch64" ]]; then
  GO_ARCH="arm64";
  CC=aarch64-linux-gnu-gcc;
else 
  GO_ARCH="amd64";
fi

CGO_ENABLED="1" GOOS="linux" GOARCH="${GO_ARCH}" go build main.go
```

**Comment by Ghasem1243** [comment]
> درود،
> 
> ```shell
> ARCH=$(uname -m)
> 
> if [[ "${ARCH}" == "aarch64" ]]; then
>   GO_ARCH="arm64";
>   CC=aarch64-linux-gnu-gcc;
> else 
>   GO_ARCH="amd64";
> fi
> 
> CGO_ENABLED="1" GOOS="linux" GOARCH="${GO_ARCH}" go build main.go
> ```

این کد رو توی ترمینال بزنم ؟؟
