### ISSUE TITLE
انتقال کاربران از x-ui به ثنایی

### ISSUE THREAD

**Issue by rezaj1394** [MHSanaei/3x-ui#957]
سلام
من از پنل زیر استفاده میکنم
https://github.com/NidukaAkalanka/x-ui-english
میخواستم کاربران رو از این پنل به ثنایی انتقال بدم
کسی از دوستان میتونه راهکاری ارایه بده؟

**Comment by rezaj1394** [comment]
حجم باقی مانده کاربر یا کاربر غیر فعال یا تاریخ باقی مانده کاربر رو میشه انتقال داد؟ راهکار سریعتر و بهتری وجود نداره؟
تنظیمات سرور و اس اس ال چی؟

**Comment by MHSanaei** [comment]
@rezaj1394 سلام لازم نیست کار خاصی انجام بدید
فقط جهت اطمینان دیتابیس رو داخل سیستمتون ذخیره کنید
و بعد لینک نصب پنل رو روی سرورتون بزنید و نصب کنید بدون مشکل باید بتونید وارد پنلتون بشید

**Comment by rezaj1394** [comment]
@MHSanaei 
سلام اگه منظورتون اینه که فایل db رو کپی کنم، این کار رو کردم و کاربران هم به سیستم ثنایی منتقل شدن ولی پنل استارت نمیشه و خطا میده
`Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.3 linux/amd64)

A unified platform for anti-censorship.

2023/08/25 11:02:00 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: VLESS clients: "flow" doesn't support "xtls-rprx-direct" in this version`
![xray](https://github.com/MHSanaei/3x-ui/assets/59175584/0ceec728-93b3-42fb-af40-b3dbd561a632)

**Comment by MHSanaei** [comment]
بعد از اینکار دوباره لینک نصب پنل مارو اجرا کنید که تغییرات لازم روی دیتابیس شما اجرا بشه و این مشکلات از دیتابیس قدیمی شما حل بشه

**Comment by rezaj1394** [comment]
@MHSanaei 
عالی دم شما گرم
api
سوال بعد اینکه ای پی ای شما با این پنل قدیمی یکی هست یا فرق داره؟

**Comment by mehdikhoram** [comment]
#303

**Comment by ir00ni** [comment]
> بعد از اینکار دوباره لینک نصب پنل مارو اجرا کنید که تغییرات لازم روی دیتابیس شما اجرا بشه و این مشکلات از دیتابیس قدیمی شما حل بشه

پنل بالا نمیاد و  ریستارت که میکنم هم پیام خطا میده
[ERR] Panel restart failed, Probably because it takes longer than two seconds to start, Please check the log information later

**Comment by hrasoul2** [comment]
> اگر هدف جابجایی به سرور جدید است فایل `/etc/x-ui/x-ui.db` را داخل سرور جدید کپی کنید.
> 
> اگر هدف اغام دو سرور است باید یک اسکریپت بنویسید. ابتدا باید لاگین کنید و `session` را ذخیر کنید.
> 
> ```httpspec
> POST /login HTTP/1.1
> Host: localhost:222
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 29
> 
> username=admin&password=admin
> ```
> 
> و بعد لیست `inbounds` ها را دریافت کنید:
> 
> ```httpspec
> GET /xui/API/inbounds HTTP/1.1
> Host: localhost:222
> Accept: application/json
> Cookie: session={session_id}
> ```
> 
> حالا با یک حقله تک تک `inbounds` ها را به همراه تمام `clients` های آن در پنل جدید ایجاد کنید.
> 
> ```httpspec
> POST /panel/api/inbounds/add HTTP/1.1
> Host: localhost:2053
> Accept: application/json
> Content-Type: application/json
> Content-Length: 422
> 
> {
>   "enable": true,
>   "remark": "New inbound",
>   "listen": "",
>   "port": 48965,
>   "protocol": "vmess",
>   "expiryTime": 0,
>   "settings": "{\"clients\":[],\"decryption\":\"none\",\"fallbacks\":[]}",
>   "streamSettings": "{\"network\":\"ws\",\"security\":\"none\",\"wsSettings\":{\"acceptProxyProtocol\":false,\"path\":\"/\",\"headers\":{}}}",
>   "sniffing": "{\"enabled\":true,\"destOverride\":[\"http\",\"tls\"]}"
> }
> ```
سلام
خیلی ممنون بابت این پیامتون..من خیلی دنبال همین میگشتم...میشه لطف کنید ساده تر توضیح بدید ...دستوراتی که لازمه بزنیم...میدونم خیلی اذیت میشید احتمالن ولی ممنون میشم یه توضیح ساده تر بدید چطور ادغام کنیم یوزر هارو

**Comment by erfangh2** [comment]
shayea8487 /smsbank32bot /smsbank32bot /6982285433
