### ISSUE TITLE
قابلیت اضافه کردن نود

### ISSUE THREAD

**Issue by iPbaz** [MHSanaei/3x-ui#959]
درود
لطفا قابلیت اضافه کردن نود رو به پنل اضافه کنید. الان ما 4 تا سرور داریم و 4 تا پنل و مجبوریم به کاربر یک اکانت از یک پنل بدیم. اما وقتی نود باشه میشه یک اکانت داد به کاربر از 4 تا سرور و با کانفیگ های مختلف و دست کاربر کاملا باز میمونه حتی اگر یک سرور فیلتر بشه و یا یک کانفیگ از کار بیفته میتونه از بقیه نودها استفاده کنه.
با تشکر

**Comment by iPbaz** [comment]
مشکل تاریخ و حجم هست. آیا اینجوری اگر از سرورهای مختلف باشه همگی یک اکانت حساب میشن و یک حجم و تاریخ دارن؟ مثلا اگر کاربر 10 گیگ از سرور 1 استفاده کنه و 20 گیگ از سرور دو استفاده کنه اینجوری در مجموع 30 گیگ حساب میشه؟

**Comment by mehdikhoram** [comment]
اون رو خودتان باید اسکریپت بنویسید که هر چند دقیقه یک بار تمامی سرورها و کاربران با email یکسان را بررسی کنند و در صورتی که مجموع حجم مصرفی در تمامی سرورها بشتر از محدودیت حجم کاربر شد. تمامی سرویس های آن کاربر غیرفعال شود.

**Comment by iPbaz** [comment]
امیدوارم این قابلیت به پنل اضافه بشه چون خیلی کاربردی هست و پنل های دیگه دارن در حال حاضر.

**Comment by zifulx** [comment]
دوستان این آپشن رو ما شخصی سازی و اضافه کردیم.
