### ISSUE TITLE
inbound routing rules

### ISSUE THREAD

**Issue by MrRomka** [MHSanaei/3x-ui#962]
Dear developers, good day. Could you please provide an example of configurations based on my case? I would like to understand how I can set up routing using my own example. Specifically, what do I need to add to the control panel? For instance, I want the connection with "tag": "inbound-441" to have access only to the private network 10.0.0.0/16. I want the connection with "tag": "inbound-442" to be directed only to 10.20.0.0/16. And for the "tag": "inbound-443" connection, I want it to remain unchanged and have internet access as configured by default.

I apologize in advance, but I believe that having an example like this in the documentation of such a great product would be really beneficial. It would provide a clear demonstration of how to quickly configure these settings and enhance understanding for users like me who are new to XRay. Thank you in advance.

[config.json.txt](https://github.com/MHSanaei/3x-ui/files/12440514/config.json.txt)
[xray.json.txt](https://github.com/MHSanaei/3x-ui/files/12440515/xray.json.txt)

**Comment by Wladimir-N** [comment]
Good day. Did you manage to figure out how to make routing different for different connections?
