### ISSUE TITLE
تنظیم flow از طرق API

### ISSUE THREAD

**Issue by Salarsdg** [MHSanaei/3x-ui#965]
سلام  ، من میخوام از طریق api کاربر اضافه کنم ، چطوری میشه flow رو هم از طریق api تنظیم کرد که داخل پنل none قرار نگیره؟

**Comment by hosein-moayedi** [comment]
> سلام ، من میخوام از طریق api کاربر اضافه کنم ، چطوری میشه flow رو هم از طریق api تنظیم کرد که داخل پنل none قرار نگیره؟

هلو!
کافی پارامتر زیر رو به بادی ریکوئستت اضافه کنی:
flow: 'xtls-rprx-vision' 

{
      id: uuid || uuidv4(),
      flow: 'xtls-rprx-vision',
      email: `reza123`,
      limitIp: 2,
      totalGB: traffic * 1024 * 1024 * 1024,
      expiryTime: 214125214,
      enable: true,
      tgId: "",
      subId: '2134142'
}

**Comment by Salarsdg** [comment]
و یک سوال دیگه میخوام یک کلاینت به اینباند شماره 3 ( آیدی 3 ) اضافه بشه و اینکه یه سری از کانفیگ ها ایدی دارن ( مثل ریلیتی ) و یک سری ها پسوورد دارن ( مثل تروجان ) داخل api چطوری میتونم مقدار آیدی برای ریلیتی ، پسوورد برای تروجان و اون موضوع اد کردن کلاینت به اینباند دلخواه رو پیاده سازی کنم؟

**Comment by hosein-moayedi** [comment]
> و یک سوال دیگه میخوام یک کلاینت به اینباند شماره 3 ( آیدی 3 ) اضافه بشه و اینکه یه سری از کانفیگ ها ایدی دارن ( مثل ریلیتی ) و یک سری ها پسوورد دارن ( مثل تروجان ) داخل api چطوری میتونم مقدار آیدی برای ریلیتی ، پسوورد برای تروجان و اون موضوع اد کردن کلاینت به اینباند دلخواه رو پیاده سازی کنم؟

کلا وقتی میخوای اسم پارامتر ها رو بدونی کافیه از طریق خود پنل یه اینبود و یه یوزر بسازی بعد یه ریکوئست گرفتن اینبند رو بزنی بعد تو جواب اسم پارامتر ها کامل هست
