### ISSUE TITLE
برگرداندن قابلیت ip limit به خود پنل

### ISSUE THREAD

**Issue by saeidpour80** [MHSanaei/3x-ui#967]
سلام وقت بخیر

لطفا اگه امکانش هست قابلیت ip limit رو مثل گذشته به داخل خود پنل برگردونید تا نیاز به نصب fail2ban نباشه و در کل دسترسی راحت تری داشته باشه

ممنون

**Comment by clockedzero** [comment]
همین الان هم این قابلیت از داخل خود پنل میباشد.

برای فعالسازی پس از نصب x-ui باید اقدام به نصب fail2ban کنید.

**Comment by saeidpour80** [comment]
وقتی fail2ban رو نصب میکنم فعال نمیشه و جلوی active مینوسه faild
هرکاری هم میکنم درست نمیشه
