### ISSUE TITLE
دریافت ارور هنگام نصب پنل سنایی

### ISSUE THREAD

**Issue by ehsansanyfx** [MHSanaei/3x-ui#970]
من موقع نصب پنل سنایی ارور زیر رو دریافت میکنم
Failed to fetch x-ui version, it maybe due to Github API restrictions, please try it later
همه چیز هم اپدیت و اپگرید شده ست
مشکل از کجاست؟

**Comment by Saeedg21** [comment]
سلام

چطوری نصب میکنی ؟
دستور نصب رو بفرست

**Comment by ir00ni** [comment]
بعضی وقتا اپدیت و اپگرید کردن سرور باعث مشکل میشه
سعی کن بدون اپدیت و اپگرید کردن سرور، نصب رو انجام بدی

**Comment by ehsansanyfx** [comment]
سلام
تشکر
مشکل اینه که اصلا سرور پینگ github نمیده بهم
حتی dns ها رو هم گذاشتم‌روی گوگل اما مشکل حل نشد
درخواست تغییر ای پی سرور دادم به پرووایدر ببینم چی میشه

**Comment by ir00ni** [comment]
راستش من یکبار این مشکل داشتم، سرور مجدد ریبلد کردم و درست شد

**Comment by ehsansanyfx** [comment]
یه ای پی وایت لیست بهم دادن اوکی شد
حالا ویزویز رو نصب کردم
لینک پنل رو که میزنم ارور 404 not found میده
علتش چیه؟

**Comment by uzer0098** [comment]
احتمالا پورت 80 اشغال بوده که موقع نصب نتونسته درست Apache رو نصب و اجرا کنه
ببین Apache ران هست تو سرور
