### ISSUE TITLE
How to route all traffic through WARP

### ISSUE THREAD

**Issue by Miltar7** [MHSanaei/3x-ui#977]
I live in Russia and tried to use this vpn to access blocked sites and play blocked games, but blizzard games and riot games dont work. is routing all traffic through WARP a viable option or is there another solution?

**Comment by IshanArdithya** [comment]
@Miltar7 If you found any solution for this please let me know. Thanks!

**Comment by romikkazan** [comment]
I'm also looking for options on how to direct the traffic I need through WARP

**Comment by LitenBuzzTh** [comment]
just add this part to your advanced templates in the warp section : 

`      {
        "type": "field",
        "ip": [
          "0.0.0.0/0"
        ],
        "domain": [
          "regexp:.*"
        ],
        "outboundTag": "WARP"
      },`

it will route all ips and domains through warp
