### ISSUE TITLE
حذف اکانت های غیر فعال 

### ISSUE THREAD

**Issue by ahwazi12** [MHSanaei/3x-ui#978]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام خوبی اگه میشه اکانت های که غیر فعال شده رو همه با هم حذف کرد

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by clockedzero** [comment]
این امکان خیلی وقته اضافه شده
inbounds > General actions > Delete depleted clients

**Comment by ir00ni** [comment]
این مورد اگه بصورت اتوماتیک باشه خوبه
مثلا بعد یک هفته یا دوهفته خودکار حذف بشه

**Comment by ahwazi12** [comment]
چند باز   زدم پاک نمیشه اوکی که غیر فعال شده  که بصورت اعداد  خاکستری نشون میده  پاک نمیشه فقط اعداد اعدای که قرمز نسون میده  پاک نیشه

**Comment by ahwazi12** [comment]
اعداد قرمز نشون میده  پاک میشه   ولی اعدادی که  خاکستری هست  پاک نمیشه

**Comment by ahwazi12** [comment]
![Screenshot_۲۰۲۳۰۸۲۹-۰۱۰۹۳۲_Chrome](https://github.com/MHSanaei/3x-ui/assets/119062798/a4640b33-57f4-4543-9b59-f5bc13bc2159)

**Comment by ahwazi12** [comment]
![۲۰۲۳۰۸۲۹_۰۱۱۱۴۲](https://github.com/MHSanaei/3x-ui/assets/119062798/25ebd460-3cea-418c-83fa-068db5766789)

**Comment by ahwazi12** [comment]
عکس فرستادم نگاه  این اکانت ها پاک نمیشن

**Comment by Arman-nsb** [comment]
اکانت هایی که خاکستری رنگ هستن تو حالت Disabled هستن و با دکمه delete depleted clients پاک نمیشن. باید دستی حذف کنید.

**Comment by amirsheikhan** [comment]
سلام من هم همین مشکل را دارم 
روی پورت های اختصاصی اکانت ها بعد از اتمام زمان خاکستری رنگ میشن 
و با گزینه Delete depleted clients
پاک نمیشن 
لطفا گزینه پاک کردن این اشتراک ها را هم اضافه کنید 
ممنون تشکر
