### ISSUE TITLE
cpu bug

### ISSUE THREAD

**Issue by Mfdrtj** [MHSanaei/3x-ui#985]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

مجدد باگ مصرف سیپیو مشاهده شده وقتی بپنل باگ cpu میخوره پهنای باند سرور بشدت با اختلال روبرو میشه1
پنل رو مجدد بردم نسخه 1.6.0 درست شد
![Shot 0205](https://github.com/MHSanaei/3x-ui/assets/88208290/c99b4a95-0b01-420d-b566-0a7849ef7714)
![Shot 0206](https://github.com/MHSanaei/3x-ui/assets/88208290/d7b889a4-40d0-467f-9b61-dd6c79adc936)

### Version of 3x-ui

<details>

```console
#1.7.7
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by AlexKoup** [comment]
I have the same problem. Up to 100% CPU. 1.7.8

**Comment by MHSanaei** [comment]
if you don't use ip limit remove access log on xray config

**Comment by AlexKoup** [comment]
What if i use it?

**Comment by AlexKoup** [comment]
> if you don't use ip limit remove access log on xray config

What if i use it?

**Comment by MHSanaei** [comment]
If you use iplimit don't forget to install fail2ban

**Comment by AlexKoup** [comment]
> If you use iplimit don't forget to install fail2ban

Fail2ban installed.

**Comment by d7coders** [comment]
I have the same issue
when I run SpeedTest.net the cpu goes to 100%

**Comment by mehdikhody** [comment]
https://github.com/MHSanaei/3x-ui/issues/1288#issuecomment-1925150499
