### ISSUE TITLE
Panel state: Not Running -  ERROR Getting updates: telego: getUpdates():

### ISSUE THREAD

**Issue by elegance666** [MHSanaei/3x-ui#986]
x-ui[2384]: [Tue Aug 29 02:48:27 UTC 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: can't                                use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first"
 x-ui[2384]: [Tue Aug 29 02:48:27 UTC 2023] ERROR Retrying to get updates in 8s
 x-ui[2384]: [Tue Aug 29 02:48:38 UTC 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: can't                                use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first"
x-ui[2384]: [Tue Aug 29 02:48:38 UTC 2023] ERROR Retrying to get updates in 8s
x-ui[2384]: [Tue Aug 29 02:48:49 UTC 2023] ERROR Getting updates: telego: getUpdates(): api: 409 "Conflict: can't use getUpdates metho           d while webhook is active; use deleteWebhook to delete the webhook first"
x-ui[2384]: [Tue Aug 29 02:48:49 UTC 2023] ERROR Retrying to get updates in 8s

----------------
Panel state: Not Running
Start automatically: Yes
xray state: Running

این اشکال چرا بوجود آمده؟

**Comment by hiwara** [comment]
سلام . حل شد مشکل شما ؟ چون من الان این مشکلو دارم و پنلم بالا نمیاد

**Comment by Pljas** [comment]
```
ERROR Execution error getUpdates: request call: fasthttp do request: dialing to the given TCP address timed out
ERROR Getting updates: telego: getUpdates(): internal execution: request call: fasthttp do request: dialing to the given TCP address timed out
ERROR Retrying to get updates in 8s
```
After updating to v2.2.0, my TG-Bot stopped working. In the logs I see this error, everything else works without changes.
