### ISSUE TITLE
 Request for Individual IP Speed Limit Feature for Employees

### ISSUE THREAD

**Issue by Vlad0sMiner** [MHSanaei/3x-ui#987]
Hello, could you please add a speed limit for a specific IP? For example, I have 10 employees, and I would like to set a limit of 10 megabits per second for each of them. I think many people would find this feature useful. Thank you!

**Comment by pro9793** [comment]
I use this code to limit 2 clients (each client has it's Inbound) on ports 64001 and 64002 for example up to 20mbit download rate:
tc qdisc add dev ens3 root handle 1: htb default 1000
tc class add dev ens3 parent 1: classid 1:1 htb rate 20mbit
tc class add dev ens3 parent 1: classid 1:2 htb rate 20mbit
tc filter add dev ens3 protocol ip parent 1:0 prio 1 u32 match ip sport 64001 0xffff flowid 1:1
tc filter add dev ens3 protocol ip parent 1:0 prio 1 u32 match ip sport 64002 0xffff flowid 1:2

**Comment by drno88** [comment]
personally, I just set up 3proxy and redirect the client to a local socks proxy, but it already limits the speed)
