### ISSUE TITLE
مشکل در ورود به پنل

### ISSUE THREAD

**Issue by Alirezaa4085** [MHSanaei/3x-ui#989]
پنل رو نصب کردم همه چی اوکی بوده اما وقتی ip و port وی پی اس خودم رو میزنم هیچ اتفاقی نمیوفته و صفحه لاگین رو نشون نمیده
سرور هم فیلتر نیست و پینگ میده

**Comment by iammrfarhadi** [comment]
سلام ، تست کنید از سرور ببینید x-ui بدون مشکل نصب و اجرا شده اگر مشکلی نمیبینید پورت های فایروال رو برسی کنید

**Comment by uzer0098** [comment]
با فیلترشکن امتحان کن

**Comment by mehrdadmis** [comment]
من هم همین مشکل رو دارم مننون میشم کسی پاسخ بده
