### ISSUE TITLE
مشکل QR code

### ISSUE THREAD

**Issue by mehrdadrzy** [MHSanaei/3x-ui#993]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

درود ، در آپدین جدید وقتی با گوشی اندروید و ای او اس اسکن میکنم اررور failur میده ، ممنون میشم راهنمایی بفرمایید

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Hasan-Torabi** [comment]
برای من هم در ورژن جدید برای کانفیگ هایی که نام آن‌ها فارسی است این مشکل پیش آمده است!

**Comment by Hasan-Torabi** [comment]
این مشکل فقط وقتی پیش میاد که نام یا email کلاینت یا کاربر جدید فارسی باشه و فقط در صورتی که در نام حرف "ی" وجود داشته باشه مشکل پیش میاد.
با تشکر از توسعه دهندگان 3x-ui ، لطفا در ورژن جدید رفع کردن این باگ رو در نظر بگیرید. سپاس

**Comment by mehrdadrzy** [comment]
فقط در اسم کلاین های من عدد و پرچم وجود داره که مشکل میخورم
