### ISSUE TITLE
H2 Transmission

### ISSUE THREAD

**Issue by StayAway32** [MHSanaei/3x-ui#994]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

دوستان خسته نباشید

در آپدیت جدید که ورژن دیفالت Xray شده 1.8.4 موردی هستش که بعضی مواقع یوزرهایی که از H2 استفاده میکنن و ورژن 1,8.5 که آخرین بروزرسانی اندروید V2rayNG هست با Xray 1.8.1 به مشکل No Internet EOF میخورن و تا زمانی که یا گوشی رو ریستارت نکنی یا برنامه رو Force Stop نکنی هم مشکل به هیچ وجه حتی با تعویض نت هم حل نمیشه

ممکنه یه راه حل موقت و قابل درک برای کاربر عمومی بدید تا وقتی این مورد پچ میشه یا آپدیت جدید 1.8.6 اندروید Release میشه ؟
اینم بگم اگر Xray پنل رو رویه 1.8.1 مثلا بزارم دیگه برای H2 مشکل EOF پیش نمیاد
متشکرم

### Version of 3x-ui

<details>

```1.7.8
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>

**Comment by MHSanaei** [comment]
این مسئله برای هسته xray هست که باید کلاینت هم اپدیت باشه 
میتونید هسته رو عوض کنید و به ۱.۸.۱ برگردید

**Comment by StayAway32** [comment]
پس منتظر آپدیت V2rayNG میمونیم
ممنونم
