### ISSUE TITLE
غیب شدن تمامی اینباند ها و ارور X-ray

### ISSUE THREAD

**Issue by karimiorg** [MHSanaei/3x-ui#995]
سلام از نسخه آخر پنل سنایی استفاده میکنم، اینباند هام پنهان شدند ولی کانفیگ ها متصل هستن و کار میکنند.

زمانی که این اتفاق افتاد X-ray متوقف شد و من پنل رو آپدیت کردم ، اتصال برقرار شده ولی همچنان اینباند ها نیستند

![image](https://github.com/MHSanaei/3x-ui/assets/132637250/69ca1863-96d0-487c-af60-b74ab9b9caf3)

**Comment by MHSanaei** [comment]
به نظر میرسه بات برای پنل نصب کردید که باگ روی دیتابیس انداخته
بک اپ قدیمی رو بندازید
